### ISSUE TITLE
Inconsistent value of indcheckxmin on master and segment breaks visibility

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#1774] opened 2017-02-16 00:04 UTC
Based on discussion in PR https://github.com/greenplum-db/gpdb/pull/1764 and reading through https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/heap/README.HOT came up with this simpler repro to demonstrate the wrong query result. HOT feature came from 8.3 postgres merge.

Steps:
```
T1: drop table hot;
T1: create table hot (dummy int, a int, b char, c char);
T1: create index idx_a on hot (a);
T1: insert into hot values (1,1,'A','#');

T2: BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
T2: select * from hot where c = '#';

T1: update hot set c = '$' where c = '#';
T1: create index idx_c on hot (c);
T1: select * from gp_dist_random('pg_index') where indexrelid in (select oid from pg_class where relname='idx_c');

T2: select * from hot where c = '#';
T2: set enable_indexscan=1;set enable_seqscan=0;
T2: explain select * from hot where c = '#';
T2: select * from hot where c = '#'; -- produces wrong result
T2: select * from hot where c = '$';  -- produces wrong result
```

Isolation test spec for the same would be
```
setup
{
    create table hot (dummy int, a int, b char, c char);
    create index idx_a on hot (a);
    insert into hot values (1,1,'A','#');
}

teardown
{
    drop table hot;
}

session "s1"
step "s1update" { update hot set c = '$' where c = '#'; }
step "s1createindexonc" { create index idx_c on hot (c); }
step "s1printindcheckxmin_segments" {select indcheckxmin from gp_dist_random('pg_index') where indexrelid in (select oid from pg_class where relname='idx_c'); }
step "s1printindcheckxmin_master" {select indcheckxmin from pg_index where indexrelid in (select oid from pg_class where relname='idx_c'); }

session "s2"
step "s2begin"  { BEGIN ISOLATION LEVEL SERIALIZABLE; }
step "s2select#"        { select * from hot where c = '#'; }
step "s2select$"        { select * from hot where c = '$'; }
step "s2enableindexscan" { set enable_indexscan=1; }
step "s2disableseqscan" { set enable_seqscan=0; }
teardown        { abort; }

permutation "s2begin" "s2select#" "s1update" "s1createindexonc" "s1printindcheckxmin_segments" "s1printindcheckxmin_master" "s2select#" "s2enableindexscan" "s2disableseqscan" "s2se\
lect#" "s2select$"
```

which produced following incorrect result out file
```
Parsed test spec with 2 sessions

starting permutation: s2begin s2select# s1update s1createindexonc s1printindcheckxmin_segments s1printindcheckxmin_master s2select# s2enableindexscan s2disableseqscan s2select# s2s\
elect$
step s2begin: BEGIN ISOLATION LEVEL SERIALIZABLE;
step s2select#: select * from hot where c = '#';
dummy          a              b              c

1              1              A              #
step s1update: update hot set c = '$' where c = '#';
step s1createindexonc: create index idx_c on hot (c);
step s1printindcheckxmin_segments: select indcheckxmin from gp_dist_random('pg_index') where indexrelid in (select oid from pg_class where relname='idx_c');
indcheckxmin

f
f
t
step s1printindcheckxmin_master: select indcheckxmin from pg_index where indexrelid in (select oid from pg_class where relname='idx_c');
indcheckxmin

f
step s2select#: select * from hot where c = '#';
dummy          a              b              c

1              1              A              #
step s2enableindexscan: set enable_indexscan=1;
step s2disableseqscan: set enable_seqscan=0;
step s2select#: select * from hot where c = '#';
dummy          a              b              c

step s2select$: select * from hot where c = '$';
dummy          a              b              c

1              1              A              #
```

Automating with serializable was easier hence close the same but it can technically happen similarly for distributed queries. Essentially planner shouldn't pick the index scan for this case but as indcheckxmin is false on master but true on one of segment it doesn't know and produces incorrect result.

Should we always set indcheckxmin = true for GPDB ? What are the downsides of the same ?

**Comment by hlinnaka** [comment] 2017-05-16 08:06
Yeah, I think always setting indcheckxmin = true would fix that. The downside is mentioned in the README.HOT:
```
Practically, we prevent old transactions from using the new index by
setting pg_index.indcheckxmin to TRUE.  Queries are allowed to use such an
index only after pg_index.xmin is below their TransactionXmin horizon,
thereby ensuring that any incompatible rows in HOT chains are dead to them.
(pg_index.xmin will be the XID of the CREATE INDEX transaction.  The reason
for using xmin rather than a normal column is that the regular vacuum
freezing mechanism will take care of converting xmin to FrozenTransactionId
before it can wrap around.)

This means in particular that the transaction creating the index will be
unable to use the index.  We alleviate that problem somewhat by not setting
indcheckxmin unless the table actually contains HOT chains with
RECENTLY_DEAD members.  (In 8.4 we may be able to improve the situation,
at least for non-serializable transactions, because we expect to be able to
advance TransactionXmin intratransaction.)
```

The "index cannot be used in the same transaction that created it" part is a bit troubling. That could screw up complicated user-defined functions that use temporary tables with indexes, for example.

To improve on just always setting indcheckxmin, we could issue a query to the segments after CREATE INDEX itself has finished, to check if indcheckxmin was set in any of the segments, and only set it in the master if it was set in any segment. This adds a round-trip to CREATE INDEX, but I think we can live with that. It's a small amount of extra overhead to every CREATE INDEX, which is unfortunate especially for the regression tests, because they contain a lot of CREATE INDEX commands on very small tables. But it shouldn't be a problem for production use. OTOH, completely forbidding using an index that was created in the same transaction could bite some real-world use case.

If each segment could send that flag back as a return value from the CREATE INDEX command itself, we could avoid the round-trip, but I don't think the dispatch mechanism has support for sending back additional data like that.

**Comment by hlinnaka** [comment] 2017-05-16 08:12
Created PR #2455 to fix this, with the extra query after dispatching CREATE INDEX. It includes your isolation test case with minor changes.

**Comment by hlinnaka** [comment] 2017-05-17 07:07
Pushed the fix, closing.

**Closed by hlinnaka** 2017-05-17 07:07 UTC
