### ISSUE TITLE
pg_get_expr does not support InvalidOid as reloid

### ISSUE THREAD

**Issue by leskin-in** [greenplum-db/gpdb#11144] opened 2020-11-11 13:35 UTC
### Greenplum version or build
[Current 7.X](https://github.com/greenplum-db/gpdb/tree/4207c3000c6823d0ae25ea9afb77bb8044a0bed0)
[Current 6.X](https://github.com/greenplum-db/gpdb/tree/826699c7b931ae5ba16c0362bcf4397a3737fb0b)

### Expected behavior
`pg_get_expr` must support `InvalidOid` passed as its second argument for `Var`-free expressions. This is described [in its comment](https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/utils/adt/ruleutils.c#L1832), and [in PostgreSQL documentation](https://www.postgresql.org/docs/9.4/functions-info.html):
> if no Vars are expected, zero is sufficient

### Actual behavior
Due to presence of [this code](https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/utils/adt/ruleutils.c#L1876) (6.X), `NULL` is always returned when the second argument of `pg_get_expr` is `InvalidOid`.

The code in question is still [present in 7.X](https://github.com/greenplum-db/gpdb/blob/4207c3000c6823d0ae25ea9afb77bb8044a0bed0/src/backend/utils/adt/ruleutils.c#L2437), although `pg_catalog.pg_partitions` has been dropped in [PostgreSQL 12 merge](https://github.com/greenplum-db/gpdb/commit/19cd1cf4b68faff2e29bc2fa884c480e4644cdb4#diff-a0e160aa93677ab1087c2cd3ddf5da762966b366e40ae99a6377f1c4db8a9f23L948). 

Moreover, `pg_partitions` is still referred to in:
* [`pg_dump`](https://github.com/greenplum-db/gpdb/blob/4207c3000c6823d0ae25ea9afb77bb8044a0bed0/src/bin/pg_dump/pg_dump.c#L17998)
* [A regression test](https://github.com/greenplum-db/gpdb/blob/4207c3000c6823d0ae25ea9afb77bb8044a0bed0/src/bin/pg_upgrade/test_gpdb_pre_drop_partition_indices.sql#L19)
* 7 files in documentation

### Discussion
What is the purpose of the lock acquired? Why a call of `pg_get_expr` in `pg_partitions` https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/catalog/system_views.sql#L826 cannot be replaced by a call with the second parameter set to `InvalidOid`: `pg_get_expr(pr1.parlistvalues, InvalidOid)`? As far as I understand, `pg_partitions` passes only `Const` nodes to `pg_get_expr`, and they do not require a valid OID.

As far as I can [see](https://github.com/greenplum-db/gpdb/blame/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/utils/adt/ruleutils.c#L1881), the change was introduced by @pengzhout originally in https://github.com/greenplum-db/gpdb/pull/7478.

I have read [a report on the related bug](https://www.postgresql.org/message-id/15775-beb18bcc52db9e36@postgresql.org), but it is quite brief. Is it possible to clarify it?

**Comment by JunfengYang** [comment] 2020-11-12 09:24
I check the code.
https://github.com/greenplum-db/gpdb/blob/12296f0fa4a1a97e236a8b62d4628aabc006d585/src/backend/utils/adt/ruleutils.c#L2393-L2404
Only `pg_get_expr_ext_lock` could hold lock for target relation.
And we don't have any test using `pg_get_expr_ext_lock`. So I assume the code is not cleaned enough.

Could you help to open a PR to remove these question codes?

**Comment by x4m** [comment] 2020-11-12 09:56
#7478 was introduced to cure flaky tests invoking pg_partitions. That PR assumes errors were raise when opening the relation to get column names. This implies that not only Const nodes were passed to pg_get_expr().

**Comment by x4m** [comment] 2020-11-12 10:01
Meanwhile I totally agree that if 0 oid is passed as second argument we have to try to return non-NULL result

**Comment by leskin-in** [comment] 2020-11-12 11:29
> That PR assumes errors were raise when opening the relation to get column names. This implies that not only Const nodes were passed to pg_get_expr().

A relation is [opened by `pg_get_expr_worker()`](https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/utils/adt/ruleutils.c#L1952) independent of the kind of node is passed to `pg_get_expr()`. 

I question the assumption that those locks are necessary. I suppose the tests were flaky in the first place *because* the second parameter of `pg_get_expr()` was *not* `InvalidOid`.

I made some research of the code and could not find evidence of nodes other than `Const` that could be present in `pg_partition_rule` columns used by `pg_partitions`. As for `Const`, these are where they are assumed: [1](https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/parser/parse_partition.c#L2499), [2](https://github.com/greenplum-db/gpdb/blob/826699c7b931ae5ba16c0362bcf4397a3737fb0b/src/backend/executor/execQual.c#L4998). But I may be missing something.

**Comment by x4m** [comment] 2020-11-12 12:52
This reasoning seems correct to me.

**Comment by d** [comment] 2020-11-14 06:51
That extra code looks bogus, we can rip it out, yes?

**Comment by x4m** [comment] 2020-11-14 09:07
I don't think it is possible to remove any exposed function or modify existing system view in released version.
Actually, as far as I understand, this issue is more about extra locking of pg_partitions than about extra code.

**Comment by d** [comment] 2020-11-15 05:32
> Actually, as far as I understand, this issue is more about extra locking of pg_partitions than about extra code.

But the problem is the _use_ of `pg_partitions`. I bet most of the uses of `pg_partitions` in tests are uncalled for. The extra locking is just insults to the code on top of the sleazy use of a view that's not really meant for tests...

**Comment by d** [comment] 2020-11-15 05:32
> I don't think it is possible to remove any exposed function or modify existing system view in released version

Correct, but we can rip this nonsense out from HEAD, yes?

**Comment by x4m** [comment] 2020-11-15 05:38
Yes, we can remove any nonsense from HEAD. Locks included. Is there anything else you would suggest to remove?

**Comment by leskin-in** [comment] 2020-11-16 10:11
@x4m thanks for https://github.com/greenplum-db/gpdb/commit/fa00e2321cfc4ac2be410dd6b991d56cfc02f1a4.

In addition to these changes, I would suggest to remove `pg_partitions` from the [regression test](https://github.com/greenplum-db/gpdb/blob/4207c3000c6823d0ae25ea9afb77bb8044a0bed0/src/bin/pg_upgrade/test_gpdb_pre_drop_partition_indices.sql#L19), [`pg_dump`](https://github.com/greenplum-db/gpdb/blob/4207c3000c6823d0ae25ea9afb77bb8044a0bed0/src/bin/pg_dump/pg_dump.c#L17998) and from documentation, as mentioned [above](https://github.com/greenplum-db/gpdb/issues/11144#issue-740771080).

**Comment by x4m** [comment] 2020-11-16 10:27
@leskin-in it's not regression tests. It's part of upgrdae scripts.
I'm hesitant to remove anything from code paths without test coverage. I think ripping out pg_partitions (or re-implementing it) is unrelated big chunk of work.

**Comment by d** [comment] 2020-11-26 05:37
Heads up, a big chunk of the team will be in and out of the (virtual) office for the next 6 weeks, and by in-and-out, I really meant out. Response will be less frequent but this issue is still on our mind.

Happy holidays,
Jesse

**Comment by x4m** [comment] 2020-11-26 05:49
No worries, Jesse. It's been an unusually long year, I think it's a good idea to have a good vacation :) Thanks you. Happy holidays!

**Comment by d** [comment] 2021-02-05 19:32
Heads up Ivan and Maksim, #11482 likely resolves this issue, would you like to try it out?

**Comment by leskin-in** [comment] 2021-02-16 08:19
https://github.com/greenplum-db/gpdb/pull/11482 resolves this issue.

Note the documentation of [current 7X](https://github.com/greenplum-db/gpdb/tree/58e5ca05fefb0aa17e76017013f8ffc938dd92db), its [`pg_dump`](https://github.com/greenplum-db/gpdb/blob/58e5ca05fefb0aa17e76017013f8ffc938dd92db/src/bin/pg_dump/pg_dump.c#L18002), and [a test](https://github.com/greenplum-db/gpdb/blob/58e5ca05fefb0aa17e76017013f8ffc938dd92db/src/bin/pg_upgrade/test_gpdb_pre_drop_partition_indices.sql#L19) still refer `pg_partitions`. But as this is a different issue; the current one should be closed, I suppose.

**Comment by ashwinstar** [comment] 2021-02-20 01:59
> Note the documentation of [current 7X](https://github.com/greenplum-db/gpdb/tree/58e5ca05fefb0aa17e76017013f8ffc938dd92db), its [`pg_dump`](https://github.com/greenplum-db/gpdb/blob/58e5ca05fefb0aa17e76017013f8ffc938dd92db/src/bin/pg_dump/pg_dump.c#L18002), and [a test](https://github.com/greenplum-db/gpdb/blob/58e5ca05fefb0aa17e76017013f8ffc938dd92db/src/bin/pg_upgrade/test_gpdb_pre_drop_partition_indices.sql#L19) still refer `pg_partitions`. But as this is a different issue; the current one should be closed, I suppose.

Thanks for pointing them out. Those pieces of code (pg_upgrade, pg_dump and documentation) are still work-in-progress for GPDB7 and should be resolved before GA of the same.

**Closed by ashwinstar** 2021-02-20 01:59 UTC
