### ISSUE TITLE
grouping by use rollup function casue query slow

### ISSUE THREAD

**Issue by zhongyibill** [greenplum-db/gpdb#9736] opened 2020-03-13 03:33 UTC
### Greenplum version or build
PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit compiled on Mar 10 2020 22:01:20 (with asse
rt checking)
### Expected behavior
we perform grouping sets aggregation in partial stage and normal aggregation in final stage.
### Actual behavior
we get data from segments and perfmon grouping sets aggregation in master.
### Step to reproduce the behavior
create table test_info( a int, b int);
explain select a, b, sum(a*b) from test_info group by rollup(a,b);
                                         QUERY PLAN
--------------------------------------------------------------------------------------------
 GroupAggregate  (cost=8018.50..10912.86 rows=9611 width=16)
   Group Key: a, b
   Group Key: a
   Group Key: ()
   ->  Gather Motion 6:1  (slice1; segments: 6)  (cost=8018.50..9955.75 rows=86100 width=8)
         Merge Key: a, b
         ->  Sort  (cost=8018.50..8233.75 rows=14350 width=8)
               Sort Key: a, b
               ->  Seq Scan on test_info  (cost=0.00..961.00 rows=14350 width=8)
 Optimizer: Postgres query optimizer

**Comment by baobao0206** [comment] 2020-07-29 08:12
The final agg in rollup running on master node is a problem. We lost the efficient implementation during pg96 merge. I think the team will get the expected behavior soon.

**Comment by hlinnaka** [comment] 2020-07-29 11:08
The planner is capable of producing the kind of plan you expected. However, it estimates that it is cheaper to just gather all the rows to the master node, and perform the aggregation there. If the table has more rows, and/or if you tweak `gp_motion_cost_per_row`, you'll see the plan you expected:

```
postgres=# create table test_info( a int, b int);
psql: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# insert into test_info select g%1000, g%1000 from generate_series(1, 10000) g;
INSERT 0 10000
postgres=# explain analyze  select a, b, sum(a*b) from test_info group by rollup(a,b);
                                                                QUERY PLAN                                                                 
-------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=776.39..1121.40 rows=2001 width=16) (actual time=14.277..49.635 rows=2001 loops=1)
   Group Key: a, b
   Group Key: a
   Group Key: ()
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=776.39..1001.39 rows=10000 width=8) (actual time=14.192..32.097 rows=10000 loops=1)
         Merge Key: a, b
         ->  Sort  (cost=776.39..801.39 rows=3334 width=8) (actual time=11.481..12.730 rows=3400 loops=1)
               Sort Key: a, b
               Sort Method:  quicksort  Memory: 452kB
               ->  Seq Scan on test_info  (cost=0.00..112.00 rows=3334 width=8) (actual time=0.107..1.627 rows=3400 loops=1)
 Planning time: 1.726 ms
   (slice0)    Executor memory: 80K bytes.
   (slice1)    Executor memory: 151K bytes avg x 3 workers, 152K bytes max (seg2).  Work_mem: 152K bytes max.
 Memory used:  128000kB
 Optimizer: Postgres query optimizer
 Execution time: 51.048 ms
(16 rows)

postgres=# set gp_motion_cost_per_row =10;
SET
postgres=# explain analyze  select a, b, sum(a*b) from test_info group by rollup(a,b);
                                                                   QUERY PLAN                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize GroupAggregate  (cost=53392.06..53477.22 rows=2001 width=16) (actual time=30.002..36.215 rows=2001 loops=1)
   Group Key: (GROUPINGSET_ID()), a, b
   ->  Sort  (cost=53392.06..53405.09 rows=5212 width=16) (actual time=29.987..30.799 rows=2003 loops=1)
         Sort Key: (GROUPINGSET_ID()), a, b
         Sort Method:  quicksort  Memory: 114kB
         ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=776.39..53070.30 rows=5212 width=16) (actual time=16.072..19.932 rows=2003 loops=1)
               ->  Partial GroupAggregate  (cost=776.39..953.50 rows=1738 width=16) (actual time=11.078..20.175 rows=681 loops=1)
                     Group Key: a, b
                     Group Key: a
                     Group Key: ()
                     ->  Sort  (cost=776.39..801.39 rows=3334 width=8) (actual time=11.033..12.478 rows=3400 loops=1)
                           Sort Key: a, b
                           Sort Method:  quicksort  Memory: 452kB
                           ->  Seq Scan on test_info  (cost=0.00..112.00 rows=3334 width=8) (actual time=0.094..1.613 rows=3400 loops=1)
 Planning time: 0.938 ms
   (slice0)    Executor memory: 186K bytes.  Work_mem: 114K bytes max.
   (slice1)    Executor memory: 151K bytes avg x 3 workers, 152K bytes max (seg2).  Work_mem: 152K bytes max.
 Memory used:  128000kB
 Optimizer: Postgres query optimizer
 Execution time: 37.680 ms
(20 rows)

```
The first plan is the one you reported, but after setting `gp_motion_rows=10`, you get a two-stage plan.

**Comment by kainwen** [comment] 2020-07-29 11:34
> The planner is capable of producing the kind of plan you expected. However, it estimates that it is cheaper to just gather all the rows to the master node, and perform the aggregation there. If the table has more rows, and/or if you tweak `gp_motion_cost_per_row`, you'll see the plan you expected:
> 
> ```
> postgres=# select version();
>                                                                                                           version                                                                             
>                               
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> ------------------------------
>  PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0+dev.7153.g8a580df7f68 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit compiled on Jul 29 2020 11
> :41:20 (with assert checking)
> (1 row)
> 
> postgres=# create table test_info( a int, b int);
> psql: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
> HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
> CREATE TABLE
> postgres=# insert into test_info select g%1000, g%1000 from generate_series(1, 10000) g;
> INSERT 0 10000
> postgres=# explain analyze  select a, b, sum(a*b) from test_info group by rollup(a,b);
>                                                                 QUERY PLAN                                                                 
> -------------------------------------------------------------------------------------------------------------------------------------------
>  GroupAggregate  (cost=776.39..1121.40 rows=2001 width=16) (actual time=14.277..49.635 rows=2001 loops=1)
>    Group Key: a, b
>    Group Key: a
>    Group Key: ()
>    ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=776.39..1001.39 rows=10000 width=8) (actual time=14.192..32.097 rows=10000 loops=1)
>          Merge Key: a, b
>          ->  Sort  (cost=776.39..801.39 rows=3334 width=8) (actual time=11.481..12.730 rows=3400 loops=1)
>                Sort Key: a, b
>                Sort Method:  quicksort  Memory: 452kB
>                ->  Seq Scan on test_info  (cost=0.00..112.00 rows=3334 width=8) (actual time=0.107..1.627 rows=3400 loops=1)
>  Planning time: 1.726 ms
>    (slice0)    Executor memory: 80K bytes.
>    (slice1)    Executor memory: 151K bytes avg x 3 workers, 152K bytes max (seg2).  Work_mem: 152K bytes max.
>  Memory used:  128000kB
>  Optimizer: Postgres query optimizer
>  Execution time: 51.048 ms
> (16 rows)
> 
> postgres=# set gp_motion_cost_per_row =10;
> SET
> postgres=# explain analyze  select a, b, sum(a*b) from test_info group by rollup(a,b);
>                                                                    QUERY PLAN                                                                    
> -------------------------------------------------------------------------------------------------------------------------------------------------
>  Finalize GroupAggregate  (cost=53392.06..53477.22 rows=2001 width=16) (actual time=30.002..36.215 rows=2001 loops=1)
>    Group Key: (GROUPINGSET_ID()), a, b
>    ->  Sort  (cost=53392.06..53405.09 rows=5212 width=16) (actual time=29.987..30.799 rows=2003 loops=1)
>          Sort Key: (GROUPINGSET_ID()), a, b
>          Sort Method:  quicksort  Memory: 114kB
>          ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=776.39..53070.30 rows=5212 width=16) (actual time=16.072..19.932 rows=2003 loops=1)
>                ->  Partial GroupAggregate  (cost=776.39..953.50 rows=1738 width=16) (actual time=11.078..20.175 rows=681 loops=1)
>                      Group Key: a, b
>                      Group Key: a
>                      Group Key: ()
>                      ->  Sort  (cost=776.39..801.39 rows=3334 width=8) (actual time=11.033..12.478 rows=3400 loops=1)
>                            Sort Key: a, b
>                            Sort Method:  quicksort  Memory: 452kB
>                            ->  Seq Scan on test_info  (cost=0.00..112.00 rows=3334 width=8) (actual time=0.094..1.613 rows=3400 loops=1)
>  Planning time: 0.938 ms
>    (slice0)    Executor memory: 186K bytes.  Work_mem: 114K bytes max.
>    (slice1)    Executor memory: 151K bytes avg x 3 workers, 152K bytes max (seg2).  Work_mem: 152K bytes max.
>  Memory used:  128000kB
>  Optimizer: Postgres query optimizer
>  Execution time: 37.680 ms
> (20 rows)
> ```
> 
> The first plan is the one you reported, but after setting `gp_motion_rows=10`, you get a two-stage plan.

Hi @hlinnaka 

There is a comment https://github.com/greenplum-db/gpdb/pull/9517#discussion_r380075887
in your previous merged pr by @pengzhout 

I think @pengzhout 's comment makes sense. So it seems we do something wrong in cost model.

Can you take a look at the above comment? Thanks.

**Comment by kainwen** [comment] 2020-07-29 11:46
> explain analyze  select a, b, sum(a*b) from test_info group by rollup(a,b);

Compared both plan in your comments with the one 6X generate:


6x plan:

```sql
gpadmin=# explain (costs off)  select a, b, sum(a*b) from test_info group by rollup(a,b);
                                                    QUERY PLAN
-------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)
   ->  HashAggregate
         Group Key: "rollup".a, "rollup".b, "rollup"."grouping", "rollup"."group_id"
         ->  Subquery Scan on "rollup"
               ->  Redistribute Motion 3:3  (slice1; segments: 3)
                     Hash Key: rollup_1.a, rollup_1.b, (Grouping), group_id()
                     ->  GroupAggregate
                           Group Key: rollup_1."grouping", rollup_1."group_id", rollup_1.a, rollup_1.b
                           ->  Subquery Scan on rollup_1
                                 ->  GroupAggregate
                                       Group Key: rollup_2.a, rollup_2."grouping", rollup_2."group_id", rollup_2.b
                                       ->  Subquery Scan on rollup_2
                                             ->  GroupAggregate
                                                   Group Key: test_info.a, test_info.b
                                                   ->  Sort
                                                         Sort Key: test_info.a, test_info.b
                                                         ->  Seq Scan on test_info
```

I think 6X's plan is better two-sage plan. It only gathers all the data at last step which maximum the distributed segments to compute.

Both plans generated from master branch's planner gather data and do agg computation in QD, which is in-efficient.

**Comment by baobao0206** [comment] 2020-07-29 11:46
@hlinnaka I think a two-stage plan is not enough. We need a plan that can be executed in a distributed manner in the second stage. Like the plan without rollup  blow.
```
demo=# explain select c, sum(b*c) from t group by c;
                                                 QUERY PLAN
------------------------------------------------------------------------------------------------------------
 Gather Motion 6:1  (slice1; segments: 6)  (cost=80818.16..84319.46 rows=116710 width=12)
   ->  Finalize HashAggregate  (cost=80818.16..81985.26 rows=19452 width=12)
         Group Key: c
         ->  Redistribute Motion 6:6  (slice2; segments: 6)  (cost=56535.00..77349.14 rows=115635 width=12)
               Hash Key: c
               ->  Partial HashAggregate  (cost=56535.00..63473.05 rows=115635 width=12)
                     Group Key: c
                     ->  Seq Scan on t  (cost=0.00..34035.00 rows=500000 width=8)
 Optimizer: Postgres query optimizer
(9 rows)
```

**Comment by kainwen** [comment] 2020-07-29 12:23
I believe this issue is the same as an early one: https://github.com/greenplum-db/gpdb/issues/9156

**Comment by hlinnaka** [comment] 2020-07-29 12:37
> @hlinnaka I think a two-stage plan is not enough. We need a plan that can be executed in a distributed manner in the second stage.

Hmm. I think you'll need a lot more groups and segments than in this example, for the extra redistribution step to become worthwhile. But yeah, you could have a query like that, and then the third step would be useful.

**Comment by baobao0206** [comment] 2020-07-29 14:27
@hlinnaka I have add the segments to 10 and increase the tuples to 30,000,000. But a distributed final aggregate still did not appear.
```
create table t3(a int, b int, c int) ;

demo=# insert into t3 select i, RANDOM()*3000000, RANDOM() * 1000000 from generate_series(1, 30000000)i;
INSERT 0 30000000
demo=# analyze t3;
ANALYZE
demo=# explain select b, c, sum(b+c) from t3 group by rollup(b,c);
                                                   QUERY PLAN
----------------------------------------------------------------------------------------------------------------
 Finalize GroupAggregate  (cost=252427719.86..252792216.57 rows=5882895 width=16)
   Group Key: (GROUPINGSET_ID()), b, c
   ->  Sort  (cost=252427719.86..252488853.41 rows=24453421 width=16)
         Sort Key: (GROUPINGSET_ID()), b, c
         ->  Gather Motion 10:1  (slice1; segments: 10)  (cost=4168636.37..249322374.71 rows=24453421 width=16)
               ->  Partial GroupAggregate  (cost=4168636.37..4788170.58 rows=2445343 width=16)
                     Group Key: b, c
                     Group Key: b
                     Group Key: ()
                     ->  Sort  (cost=4168636.37..4243636.37 rows=3000000 width=8)
                           Sort Key: b, c
                           ->  Seq Scan on t3  (cost=0.00..340328.00 rows=3000000 width=8)
 Optimizer: Postgres query optimizer
(13 rows)
```
Are we considering distributed final aggregates in the current path?

**Comment by hlinnaka** [comment] 2020-07-29 16:46
No, the planner doesn't currently consider distributing the final aggregate. There's this in `add_twostage_group_agg_path()`:
```

	/*
	 * GroupAgg -> GATHER MOTION -> GroupAgg.
	 *
	 * This has the advantage that it retains the input order. The
	 * downside is that it gathers everything to a single node. If that's
	 * where the final result is needed anyway, that's quite possibly better
	 * than scattering the partial aggregate results and having another
	 * motion to gather the final results, though,
	 *
	 * Alternatively, we could redistribute based on the GROUP BY key. That
	 * would have the advantage that the Finalize Agg stage could run in
	 * parallel. However, it would destroy the sort order, so it's probaly
	 * not a good idea.
	 */
	CdbPathLocus_MakeSingleQE(&singleQE_locus, getgpsegmentCount());
	path = cdbpath_create_motion_path(root,
									  initial_agg_path,
									  motion_pathkeys,
									  false,
									  singleQE_locus);
```
The comment makes sense for a simple GROUP BY, but not so much for grouping sets, because with grouping sets, you need the Sort step anyway. So yeah, I think we should consider redistributing there, at least when grouping sets are involved.

I can open a PR for that.

One piece that's still missing after that on 'master' is doing Hash Aggs. The code doesn't currently support Hash Aggs at all, when there grouping sets. We can revisit that after the PostgreSQL v12 merge, a we'll get the support for that with the merge.

**Closed** 2020-09-09 06:28 UTC
