### ISSUE TITLE
fileam.c:927:10: error: ‘error_caught’ is used uninitialized in this function [-Werror=uninitialized]

### ISSUE THREAD

**Issue by pivotal-ning-yu** [greenplum-db/gpdb#8262] opened 2019-07-30 03:08 UTC
### Greenplum version or build

```sh
$ git branch
* master
```

### OS version and uname -a

```sh
$ cat /etc/issue.net
Ubuntu Eoan Ermine (development branch)

$ uname -a
Linux nyu-vm-ubuntu 5.2.0-8-generic #9-Ubuntu SMP Mon Jul 8 13:07:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ gcc-9 -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc-9
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.1.0-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
gcc version 9.1.0 (Ubuntu 9.1.0-9ubuntu2)
```

### autoconf options used ( config.status --config )

```sh
$ ./config.status --config
'--cache-file=/home/u/.cache/my/gpdb.debug._g__O3__march_native.cache' '--with-python' '--with-perl' '--disable-mapreduce' '--disable-orca' '--with-libxml' '--with-openssl' '--disable-codegen' '--disable-gpcloud' '--disable-gpfdist' '--disable-debug' '--disable-cassert' '--enable-depend' '--disable-coverage' '--prefix=/home/u/opt/gpdb' '--with-includes=/home/u/opt/orca/include' '--with-libraries=/home/u/opt/orca/lib' 'CC=gcc-9' 'CFLAGS=-g -O3 -march=native' 'CXX=g++-9' 'CXXFLAGS=-g -O3 -march=native'
```

### Installation information ( pg_config )

```
$ pg_config
BINDIR = /home/u/opt/gpdb/bin
DOCDIR = /home/u/opt/gpdb/share/doc/postgresql
HTMLDIR = /home/u/opt/gpdb/share/doc/postgresql
INCLUDEDIR = /home/u/opt/gpdb/include
PKGINCLUDEDIR = /home/u/opt/gpdb/include/postgresql
INCLUDEDIR-SERVER = /home/u/opt/gpdb/include/postgresql/server
LIBDIR = /home/u/opt/gpdb/lib
PKGLIBDIR = /home/u/opt/gpdb/lib/postgresql
LOCALEDIR = /home/u/opt/gpdb/share/locale
MANDIR = /home/u/opt/gpdb/share/man
SHAREDIR = /home/u/opt/gpdb/share/postgresql
SYSCONFDIR = /home/u/opt/gpdb/etc/postgresql
PGXS = /home/u/opt/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--cache-file=/home/u/.cache/my/gpdb.debug._O0__g__fuse_ld_gold__march_native.cache' '--with-python' '--with-perl' '--disable-mapreduce' '--disable-orca' '--with-libxml' '--with-openssl' '--disable-codegen' '--disable-gpcloud' '--disable-gpfdist' '--enable-debug' '--enable-cassert' '--enable-depend' '--disable-coverage' '--prefix=/home/u/opt/gpdb' '--with-includes=/home/u/opt/orca/include' '--with-libraries=/home/u/opt/orca/lib' 'CC=gcc-9' 'CFLAGS=-O0 -g -fuse-ld=gold -march=native' 'CXX=g++-9' 'CXXFLAGS=-O0 -g -fuse-ld=gold -march=native'
CC = gcc-9
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/home/u/opt/orca/include -I/home/u/opt/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Wno-format-truncation -Wno-stringop-truncation -g -ggdb -O0 -g -fuse-ld=gold -march=native -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/home/u/opt/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/home/u/opt/orca/lib -Wl,--as-needed -Wl,-rpath,'/home/u/opt/gpdb/lib',--enable-new-dtags -L/home/u/opt/gpdb/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxml2 -lrt -lzstd -lrt -lcrypt -ldl -lm -L/home/u/opt/gpdb/lib
VERSION = PostgreSQL 9.4.20
```

### Expected behavior

Should compiles successfully.

### Actual behavior

Compilation failed with below error:

```
make -C external all
make[4]: Entering directory '/home/u/src/gpdb.git/src/backend/access/external'
gcc-9 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Wno-format-truncation -Wno-stringop-truncation -g -O3 -march=native -std=gnu99   -Werror=uninitialized -Werror=implicit-function-declaration -I../../../../src/include -D_GNU_SOURCE -I/usr/include/libxml2  -I/home/u/opt/orca/include  -c -o fileam.o fileam.c -MMD -MP -MF .deps/fileam.Po
fileam.c: In function ‘externalgettup_custom’:
fileam.c:927:10: error: ‘error_caught’ is used uninitialized in this function [-Werror=uninitialized]
  927 |    bool  error_caught = false;
      |          ^~~~~~~~~~~~
In file included from ../../../../src/include/postgres.h:53,
                 from fileam.c:34:
../../../../src/include/utils/elog.h:425:15: error: ‘save_exception_stack’ is used uninitialized in this function [-Werror=uninitialized]
  425 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |               ^~~~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:425:15: note: ‘save_exception_stack’ was declared here
  425 |   sigjmp_buf *save_exception_stack = PG_exception_stack; \
      |               ^~~~~~~~~~~~~~~~~~~~
fileam.c:932:4: note: in expansion of macro ‘PG_TRY’
  932 |    PG_TRY();
      |    ^~~~~~
../../../../src/include/utils/elog.h:426:25: error: ‘save_context_stack’ is used uninitialized in this function [-Werror=uninitialized]
  426 |   ErrorContextCallback *save_context_stack = error_context_stack; \
      |                         ^~~~~~~~~~~~~~~~~~
../../../../src/include/utils/elog.h:426:25: note: ‘save_context_stack’ was declared here
  426 |   ErrorContextCallback *save_context_stack = error_context_stack; \
      |                         ^~~~~~~~~~~~~~~~~~
fileam.c:932:4: note: in expansion of macro ‘PG_TRY’
  932 |    PG_TRY();
      |    ^~~~~~
cc1: some warnings being treated as errors
make[4]: *** [../../../../src/Makefile.global:826: fileam.o] Error 1
make[4]: Leaving directory '/home/u/src/gpdb.git/src/backend/access/external'
```

### Step to reproduce the behavior

I have tested with several gcc versions, the issue is reported on gcc 7, 8 and 9; gcc-6 will not report any issue.

And gcc-9 only reports the issue with `-O2`, `-O3` and `-Ofast`; there is no such issue with `-O`, `-O0`, `-O1`, `-Os` and `-Og`.

The reported error itself is weird:

```
fileam.c:927:10: error: ‘error_caught’ is used uninitialized in this function [-Werror=uninitialized]
  927 |    bool  error_caught = false;
      |          ^~~~~~~~~~~~
```

It reports an uninitialized variable on its initialization statement.  This might be a bug of GCC, maybe it does not detect the initialization correctly, or maybe there do is an uninitialized variable but it reports on the wrong one.

**Comment by pivotal-ning-yu** [comment] 2019-07-30 03:32
With gcc `-O1` we could also trigger the issue with additional arguments: `-O1 -fexpensive-optimizations -fno-tree-pre`.

So with `-O3` we could get rid of the issue by turning PRE `-O3 -fno-tree-pre`.

But I would also try to check the gpdb source code to see whether it is a real issue or just a false alarm from gcc.

**Comment by pivotal-ning-yu** [comment] 2019-07-30 03:34
BTW, below is the manpage of the PRE:

```
       -ftree-pre
           Perform partial redundancy elimination (PRE) on trees.  This flag is enabled by default
           at -O2 and -O3.
```

**Comment by pivotal-ning-yu** [comment] 2019-07-30 05:27
I had a rough check on gpdb source code and found nothing wrong around the variables reported by gcc.  So maybe we really triggered a gcc bug.  In such a case we could consider adding `-fno-tree-pre` for this `.c` source file.

**Comment by d** [comment] 2019-07-30 06:19
sounds like a dupe of #4499

**Comment by pivotal-ning-yu** [comment] 2019-07-30 06:46
> sounds like a dupe of #4499

Yes, they should be the same issue.

**Comment by pivotal-ning-yu** [comment] 2019-07-30 08:50
A quick workaround is like this:

```diff
diff --git a/src/backend/access/external/Makefile b/src/backend/access/external/Makefile
index f6f0377822..9f27d45efb 100644
--- a/src/backend/access/external/Makefile
+++ b/src/backend/access/external/Makefile
@@ -13,3 +13,4 @@ OBJS = fileam.o url.o url_curl.o url_file.o url_execute.o url_custom.o

 include $(top_srcdir)/src/backend/common.mk

+fileam.o: CFLAGS+=-fno-tree-pre
diff --git a/src/backend/access/transam/Makefile b/src/backend/access/transam/Makefile
index 4d05262ad2..02782fbd79 100644
--- a/src/backend/access/transam/Makefile
+++ b/src/backend/access/transam/Makefile
@@ -22,3 +22,5 @@ include $(top_srcdir)/src/backend/common.mk

 # ensure that version checks in xlog.c get recompiled when catversion.h changes
 xlog.o: xlog.c $(top_srcdir)/src/include/catalog/catversion.h
+
+fileam.o: CFLAGS+=-fno-tree-pre
```

**Comment by jchampio** [comment] 2019-07-30 15:52
@d @pivotal-ning-yu 

That code is likely interacting with the `PG_TRY`/`PG_CATCH` implementation, which uses `siglongjmp()` and friends. Here's [a newer piece of Postgres documentation on the issue](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=4b2a254793be50e31d43d4bfd813da8d141494b8) and [a GCC note about possible false positives](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-longjmp-warnings).

> It reports an uninitialized variable on its initialization statement.

Here's what I think may be happening: because of the `while` loop, the compiler sees that the function-local variables are being modified after `sigsetjmp()` (inside `PG_TRY`) is called. Those aren't marked `volatile`, so GCC thinks that a `siglongjmp()` back into the function could theoretically result in an "impossible" variable state -- where we enter the `PG_CATCH` block with `error_caught` already set to `true`, or `save_context_stack` set to the context from a prior loop iteration instead of the current one.

Whether or not this is actually possible, I'm not sure, but I'm guessing GCC isn't sophisticated enough to prove correctness in all cases, so it tells us we haven't properly initialized the variables.

But! If I pull the `PG_TRY` block implementation into its own helper function (so that each function call results in only one `sigsetjmp()`), and call that helper from inside the while loop, the errors disappear. That's not proof that my analysis is correct -- maybe it just reorders the code enough to make GCC analyze it differently -- but it might be a better workaround than messing with compiler optimizations.

**Comment by pivotal-ning-yu** [comment] 2019-07-31 01:08
@jchampio thanks for the analysis.  That reminds me to come out a minimal reproducer to trigger this issue:

```C
#include <setjmp.h>

extern int other(void);
extern void trigger(int *raw_buf_len, int *fe_eof);
extern sigjmp_buf *PG_exception_stack;

void
trigger(int *raw_buf_len, int *fe_eof)
{
    while (!*fe_eof)
    {
        /* part A */
        if (*raw_buf_len == 0)
            *raw_buf_len = other();

        while (*raw_buf_len)
        {
            sigjmp_buf *save_exception_stack = PG_exception_stack;
            sigjmp_buf local_sigjmp_buf;

            if (sigsetjmp(local_sigjmp_buf, 0) == 0)
                PG_exception_stack = &local_sigjmp_buf;
            else
                PG_exception_stack = (sigjmp_buf *) save_exception_stack;

            PG_exception_stack = (sigjmp_buf *) save_exception_stack;
        }
    }
}
```

```sh
$ gcc-9 -Werror=uninitialized -O1 -fexpensive-optimizations -ftree-pre -c -o /dev/null /tmp/a.c
/tmp/a.c: In function ‘trigger’:
/tmp/a.c:17:16: error: ‘save_exception_stack’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   17 |    sigjmp_buf *save_exception_stack = PG_exception_stack;
      |                ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

Note about part A, I had some experiments with its variants, here are the results:

```C
        /* variant 1: will trigger the issue */
        if (*raw_buf_len == 0)
            *raw_buf_len = other();

        /* variant 2: will trigger the issue */
        if (*raw_buf_len == 0)
            *raw_buf_len = other();
        else
            *raw_buf_len = other();

        /* variant 3: will not trigger the issue */
        *raw_buf_len = other();
```

Variants 2 and 3 actually equal to each other, but GCC doesn't think so, `-O3` has the same weird behavior.  So I still think this is a bug of GCC.

Per my experiment if we change `raw_buf_len` to `volatile int *` then there will not be the issue, but again that doesn't explain why an error should be reported on `save_exception_stack`.  As a contrast changing `save_exception_stack` and/or `PG_exception_stack` to volatile pointers do not help.

**Comment by jchampio** [comment] 2019-07-31 16:57
> Variants 2 and 3 actually equal to each other, but GCC doesn't think so, -O3 has the same weird behavior. So I still think this is a bug of GCC.

I'm not sure what "weird behavior" you mean -- as far as I can tell, the warning is correct. It may seem strange that different optimizations or code constructions mask that warning, but in my experience that's pretty common -- some of the algorithms for finding these things are best-effort and could be thwarted by different layouts.

> Per my experiment if we change raw_buf_len to volatile int * then there will not be the issue, but again that doesn't explain why an error should be reported on save_exception_stack. As a contrast changing save_exception_stack and/or PG_exception_stack to volatile pointers do not help.

I think the only relevant variable to touch with `volatile` here is `save_exception_stack`, since that's the only function-local variable that is modified after the `sigsetjmp()`.

Also, when I replicate your experiment, I do find that marking that pointer `volatile`, with
```c
sigjmp_buf * volatile save_exception_stack = PG_exception_stack;
```
causes the warning to go away.

**Comment by pivotal-ning-yu** [comment] 2019-08-07 02:43
Call for volunteers!

So far we have several possible workarounds for this issue:

1. refactor the function to not confuse gcc;
2. add `-fno-tree-pre` for the affected source files;
3. mark `save_exception_stack` as `volatile` in `PG_TRY()`;

We need to put one of them (or maybe other better solution) to gpdb master to fix the w/o assert pipeline, it has been red for weeks.  Personally I do not have enough time to have this last step done, could anyone help to take the turn to open a PR and push the analysis, review and discussion, please?

**Comment by adam8157** [comment] 2019-08-07 09:58
FYI, I'm working on this, might be close to the answer, if not I will do the workaround tomorrow (Beijing time).

**Comment by berlin-ab** [comment] 2019-08-07 13:57
> FYI, I'm working on this, might be close to the answer, if not I will do the workaround tomorrow (Beijing time).

Thanks for picking this up.

**Comment by adam8157** [comment] 2019-08-08 05:11
Observations:
1, it reports all local variables used in PG_CATCH.
2, asm code re-ordering changes the behavior.
3, when it reports warning, initializing asm codes are before the setjmp().

When it warns:
```
                        sigjmp_buf *save_exception_stack = PG_exception_stack;
  2f:   48 8b 1d 00 00 00 00    mov    0x0(%rip),%rbx        # 36 <trigger+0x36>
  36:   48 89 5c 24 18          mov    %rbx,0x18(%rsp)
                        sigjmp_buf local_sigjmp_buf;

                        if (sigsetjmp(local_sigjmp_buf, 0) == 0)
```

When it doesn't complain:
```
                        sigjmp_buf *save_exception_stack = PG_exception_stack;
                        sigjmp_buf local_sigjmp_buf;

                        if (sigsetjmp(local_sigjmp_buf, 0) == 0)
  29:   48 8d 44 24 20          lea    0x20(%rsp),%rax
  2e:   48 89 44 24 08          mov    %rax,0x8(%rsp)
...
                        sigjmp_buf *save_exception_stack = PG_exception_stack;
  3c:   48 8b 1d 00 00 00 00    mov    0x0(%rip),%rbx        # 43 <trigger+0x43>
  43:   48 89 5c 24 18          mov    %rbx,0x18(%rsp)
```

My conclusions:
1, Jacob is right.
> because of the while loop, the compiler sees that the function-local variables are being modified after sigsetjmp() (inside PG_TRY) is called. Those aren't marked volatile, so GCC thinks that a siglongjmp() back into the function could theoretically result in an "impossible" variable state -- where we enter the PG_CATCH block with error_caught already set to true, or save_context_stack set to the context from a prior loop iteration instead of the current one.

2, gcc is kind of right.
3, it might be an optimization regression of gcc, it was always smart enough to reorder the local variables to avoid this issue (initializing them after setjmp() obviously has no such issue because it will be initialized as we wish after longjmp() wherever anyway), but higher version gcc's updates  lost the optimization in some cases.

What I will do today:
1, refactor the code to make the pipeline green. (in a way not confusing gcc, or triggering gcc's warning as you say)
2, send out mails to Postgres and gcc mailing list.

What I will do in the near future:
summary the feedbacks, add `-fno-tree-pre`, or wait for gcc update, or update our codes.  Absolutely not only refactoring the code to workaround.

**Comment by adam8157** [comment] 2019-08-08 06:22
Filed a gcc bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91395

**Comment by adam8157** [comment] 2019-08-08 08:26
The gcc community suggests making the save_*_stack variables volatile. Mailed the Postgres mailing list.

**Comment by ashwinstar** [comment] 2019-08-08 16:03
@jchampio analysis is correct and Tom Lane suggests [here](https://www.postgresql.org/message-id/25875.1565275667%40sss.pgh.pa.us), pulling out code in TRY/CATCH into separate function as a solution similar to @jchampio tried above.

**Closed** 2019-08-09 09:41 UTC

**Comment by adam8157** [comment] 2019-08-09 09:50
The final decision is let it be, if it triggers again, separate the function then.
