### ISSUE TITLE
Greenplum 7 crashed and is not working anymore

### ISSUE THREAD

**Issue by zlokomatic** [greenplum-db/gpdb#17129] opened 2024-02-28 21:45 UTC
## Bug Report
While importing data, the gpdb crashed and now with every query i get an error

```
WARNING:  terminating connection because of crash of another server process  (seg1 slice1 ip:6001 pid=2245)
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
```

Segment logs look like this:

```
2024-02-28 22:32:16.253226 CET,,,p517,th682339776,,,,0,,,seg32,,,,,"LOG","00000","end of transaction log location is 53/D68EFA90",,,,,,,0,,"xlog.c",7788,
2024-02-28 22:32:16.253396 CET,,,p517,th682339776,,,,0,,,seg32,,,,,"LOG","00000","latest completed transaction id is 499753 and next transaction id is 499754",,,,,,,0,,"xlog.c",8176,
2024-02-28 22:32:16.253857 CET,,,p517,th682339776,,,,0,,,seg32,,,,,"LOG","00000","database system is ready",,,,,,,0,,"xlog.c",8202,
2024-02-28 22:32:16.260674 CET,,,p453,th682339776,,,,0,,,seg32,,,,,"LOG","00000","PostgreSQL 12.12 (Greenplum Database 7.0.0 build commit:0a7a3566873325aca1789ae6f818c80f17a9402d) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on Sep 20 2023 23:19:57",,,,,,,0,,"postmaster.c",3525,
2024-02-28 22:32:16.260701 CET,,,p453,th682339776,,,,0,,,seg32,,,,,"LOG","00000","database system is ready to accept connections","PostgreSQL 12.12 (Greenplum Database 7.0.0 build commit:0a7a3566873325aca1789ae6f818c80f17a9402d) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit compiled on Sep 20 2023 23:19:57",,,,,,0,,"postmaster.c",3529,
2024-02-28 22:32:16.261648 CET,,,p533,th682339776,,,,0,,,seg32,,,,,"LOG","00000","ic-proxy: server setting up",,,,,,,0,,"ic_proxy_main.c",532,
2024-02-28 22:32:16.262434 CET,,,p533,th682339776,,,,0,,,seg32,,,,,"LOG","00000","ic-proxy: server running",,,,,,,0,,"ic_proxy_main.c",573,
2024-02-28 22:32:16.430101 CET,"gpadmin",,p560,th682339776,"ip","39740",2024-02-28 22:32:16 CET,0,,,seg32,,,,,"LOG","00000","standby ""gp_walreceiver"" is now a synchronous standby with priority 1",,,,,,"START_REPLICATION SLOT ""internal_wal_replication_slot"" 53/D4000000 TIMELINE 1",0,,"syncrep.c",595,
2024-02-28 22:32:21.426314 CET,"gpadmin","postgres",p583,th682339776,"ip","52868",2024-02-28 22:32:21 CET,0,con2,,seg32,,,,sx1,"LOG","00000","tried to terminate all (0) mpp backends except self",,,,,,"select * from gp_terminate_mpp_backends()",0,,"signalfuncs.c",222,
2024-02-28 22:32:21.514786 CET,,,p611,th682339776,,,,0,,,seg32,,,,,"LOG","00000","Metrics collector: background worker starts",,,,,,,0,,"metrics_collector_gp.c",295,
2024-02-28 22:32:57.583381 CET,,,p961,th0,,,2024-02-28 22:32:57 CET,0,con34,cmd1,seg32,slice1,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0x7fb428694cf0 libpthread.so.0 <symbol not found> + 0x28694cf0
2    0x7da736 postgres <symbol not found> (aocsam.c:1005)
3    0x7dd041 postgres aocs_get_target_tuple (aocsam.c:1049)
4    0x7d73e5 postgres <symbol not found> (aocsam_handler.c:1735)
5    0x8865b7 postgres <symbol not found> (tableam.h:1738)
6    0x8886a2 postgres <symbol not found> (analyze.c:733)
7    0x88a7f2 postgres analyze_rel (analyze.c:422)
8    0x924b07 postgres gp_acquire_sample_rows (analyzefuncs.c:146)
9    0x952df7 postgres ExecMakeFunctionResultSet (execSRF.c:619)
10   0x97d32f postgres <symbol not found> (nodeProjectSet.c:175)
11   0x97d498 postgres <symbol not found> (nodeProjectSet.c:112)
12   0x94f5a7 postgres <symbol not found> (execProcnode.c:645)
13   0x992dc4 postgres <symbol not found> (executor.h:271)
14   0x94f5a7 postgres <symbol not found> (execProcnode.c:645)
15   0x94636b postgres <symbol not found> (execMain.c:2678)
16   0x946d75 postgres standard_ExecutorRun (execMain.c:922)
17   0x946f05 postgres ExecutorRun (execMain.c:793)
18   0xb5cddc postgres <symbol not found> (pquery.c:1149)
19   0xb5ee11 postgres PortalRun (pquery.c:992)
20   0xb57c76 postgres <symbol not found> (postgres.c:1448)
"
2024-02-28 22:32:57.598061 CET,,,p453,th682339776,,,,0,,,seg32,,,,,"LOG","00000","server process (PID 961) was terminated by signal 11: Segmentation fault","Failed process was running: select pg_catalog.gp_acquire_sample_rows(17255, 357, 'f');",,,,,,0,,"postmaster.c",4224,
2024-02-28 22:32:57.598106 CET,,,p453,th682339776,,,,0,,,seg32,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3945,
2024-02-28 22:32:57.598833 CET,"gpmon","gpperfmon",p907,th682339776,"ip","35846",2024-02-28 22:32:47 CET,0,con22,,seg32,,,,,"WARNING","57P02","terminating connection because of crash of another server process","The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.","In a moment you should be able to reconnect to the database and repeat your command.",,,,,0,,"postgres.c",3506,
```

Greenplum version or build
GPDB Version 7.0.0

OS version and uname -a
Im running gpdb in a alma linux 8 container on a ubuntu 22.04 host
Linux dwh-poc-master01 5.15.0-91-generic https://github.com/greenplum-db/gpdb/pull/101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

autoconf options used ( config.status --config )

Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-7.0.0/bin
DOCDIR = /usr/local/greenplum-db-7.0.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-7.0.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-7.0.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-7.0.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-7.0.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-7.0.0/lib
PKGLIBDIR = /usr/local/greenplum-db-7.0.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-7.0.0/share/locale
MANDIR = /usr/local/greenplum-db-7.0.0/man
SHAREDIR = /usr/local/greenplum-db-7.0.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-7.0.0/etc/postgresql
PGXS = /usr/local/greenplum-db-7.0.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-gssapi' '--enable-orafce' '--enable-orca' '--enable-gpcloud' '--with-libxml' '--with-openssl' '--with-pam' '--with-ldap' '--with-uuid=e2fs' '--with-llvm' '--with-pgport=5432' '--disable-debug-extensions' '--disable-tap-tests' '--enable-ic-proxy' '--with-perl' '--with-python' 'PYTHON=python3.9' '--with-includes=/tmp/build/c8e4a0da/gpdb_src/gpAux/ext/rocky8_x86_64/include /tmp/build/c8e4a0da/gpdb_src/gpAux/ext/rocky8_x86_64/include/libxml2' '--with-libraries=/tmp/build/c8e4a0da/gpdb_src/gpAux/ext/rocky8_x86_64/lib' '--disable-rpath' 'LDFLAGS=-Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib' '--prefix=/usr/local/greenplum-db-devel' '--mandir=/usr/local/greenplum-db-devel/man' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g' 'PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib -L/usr/lib64 -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lpam -lrt -lssl -lcrypto -lgssapi_krb5 -luv -lz -lreadline -lrt -lcrypt -ldl -lm -lcurl -L/usr/lib -lzstd
VERSION = PostgreSQL 12.12

### Expected behavior
A working database

### Actual behavior
On every query the database crashes

### Coredump

```
#0  0x00007fdd330bbb8f in raise () from /home/gpadmin/core/packcore-core-postgres-11-1000-1000-128357-1709196198/lib64/libpthread.so.0
(gdb) bt
#0  0x00007fdd330bbb8f in raise () from /home/gpadmin/core/packcore-core-postgres-11-1000-1000-128357-1709196198/lib64/libpthread.so.0
#1  0x0000000000ce2fb8 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5104
#2  <signal handler called>
#3  DatumStreamBlockRead_AdvanceDense (dsr=0x2df15c8) at ../../../../src/include/utils/datumstreamblock.h:1980
#4  DatumStreamBlockRead_Advance (dsr=0x2df15c8) at ../../../../src/include/utils/datumstreamblock.h:2056
#5  datumstreamread_advance (acc=0x2df1450) at ../../../../src/include/utils/datumstream.h:221
#6  datumstreamread_find (datumStream=datumStream@entry=0x2df1450, rowNumInBlock=40) at datumstream.c:1394
#7  0x00000000007da736 in aocs_gettuple_column (scan=scan@entry=0x2bb0550, attno=attno@entry=14, startrow=<optimized out>, endrow=endrow@entry=41,
    chkvisimap=chkvisimap@entry=false, slot=slot@entry=0x2c8b800) at aocsam.c:1000
#8  0x00000000007dd041 in aocs_gettuple (slot=0x2c8b800, targrow=41, scan=0x2bb0550) at aocsam.c:1049
#9  aocs_get_target_tuple (aoscan=aoscan@entry=0x2bb0550, targrow=41, slot=slot@entry=0x2c8b800) at aocsam.c:1157
#10 0x00000000007d73e5 in aoco_acquire_sample_rows (onerel=0x7fdd333a8170, elevel=13, rows=0x2ba4500, targrows=357, totalrows=0x7ffc80d99b40,
    totaldeadrows=0x7ffc80d99b48) at aocsam_handler.c:1735
#11 0x00000000008865b7 in table_relation_acquire_sample_rows (totaldeadrows=0x7ffc80d99b48, totalrows=0x7ffc80d99b40, targrows=357, rows=0x2ba4500,
    elevel=13, rel=0x7fdd333a8170) at ../../../src/include/access/tableam.h:1738
#12 gp_acquire_sample_rows_func (onerel=onerel@entry=0x7fdd333a8170, elevel=elevel@entry=13, rows=rows@entry=0x2ba4500, targrows=targrows@entry=357,
    totalrows=totalrows@entry=0x7ffc80d99b40, totaldeadrows=totaldeadrows@entry=0x7ffc80d99b48) at analyze.c:1496
#13 0x00000000008886a2 in do_analyze_rel (onerel=onerel@entry=0x7fdd333a8170, params=params@entry=0x7ffc80d99f50, va_cols=va_cols@entry=0x0,
    acquirefunc=0x8861f0 <gp_acquire_sample_rows_func>, relpages=9, inh=inh@entry=false, in_outer_xact=true, elevel=13, ctx=0x2c8e850) at analyze.c:733
#14 0x000000000088a7f2 in analyze_rel_internal (ctx=0x2c8e850, bstrategy=0x2c8ecd0, in_outer_xact=true, va_cols=0x0, params=0x7ffc80d99f50,
    relation=0x2c8e8d0, relid=17255) at analyze.c:422
```

**Comment by ashwinstar** [comment] 2024-02-28 23:32
PANIC must have generated the core file. If you can provide us with packcore then would be helpful to RCA the problem. It seems to be analyze operation on CO table that hitting the crash.

**Comment by zlokomatic** [comment] 2024-02-29 06:58
Hi,

where can i find the file?

**Comment by kainwen** [comment] 2024-02-29 08:09
> Hi,
> 
> where can i find the file?

1. you need config your OS can generate core
2. location can be found by `cat /proc/sys/kernel/core_pattern`

**Comment by zlokomatic** [comment] 2024-02-29 08:58
I cant add the generated files here so i uploaded it here:

https://github.com/zlokomatic/gpdb-packcore/blob/main/packcore-core-postgres-11-1000-1000-128357-1709196198.tar.gz

**Comment by kainwen** [comment] 2024-02-29 12:48
Thanks @zlokomatic packcore can be read. I update the issue. Will look into later.

**Comment by zlokomatic** [comment] 2024-03-04 09:31
Hey @kainwen,

did you have time to look into the problem?
Our db cluster is not usable at the moment so we would be happy about any information regarding this ticket :)

**Comment by z-wenlin** [comment] 2024-03-04 09:39
Hi @zlokomatic, we have taken a look at the core today and tried to reproduce it on our side, but unfortunately, we can't reproduce it. 
Do you have the minirepro that can reproduce the problem? 
Also, we noticed that you are using GPCC? Have you tried to stop it and see if the problem still happens?
Thanks.

**Comment by zlokomatic** [comment] 2024-03-04 11:23
Hi @z-wenlin 

I have no minirepo to reproduce the problem as i have no clue how the problem occured. It is a cluster with some TB of data which suddenly stopped working.

I tried running without gpcc but that did not change anything

**Comment by z-wenlin** [comment] 2024-03-05 09:53
Some findings from the core:
1. It panics at `DatumStreamBlockRead_AdvanceDense` because the `dst->datmp` is out of bound when analyze the `gpcc_pg_log_history_1_prt_2` at column 15 `loglocalxact`
```
     s = (struct varlena *) dsr->datump;
     dsr->datump += VARSIZE_ANY(s);   ->    datump = 0x1d27a610 <Address 0x1d27a610 out of bounds>,
```
2. We also checked column 14 `logdistxact` datump, datum_beginp and datum_afterp, which don't have the problem.

We think that it might be data-related., so it would be helpful to provide the data for `gpcc_pg_log_history_1_prt_2` so that we could try to reproduce the problem. 

Suggestions so far:
1. Open the GUC `Debug_appendonly_print_scan_tuple` to collect more info about datum stream block.
2. Try to run analyze gpcc_pg_log_history_1_prt_2 and see if the panic happens again.
3. Collect the data in table `gpcc_pg_log_history_1_prt_2`, especially for the column 13/14/15.

Thanks.

**Comment by zlokomatic** [comment] 2024-03-05 10:43
Unfortunately i cant give you the data for gpcc_pg_log_history_1_prt_2 as i dropped the gpperfmon database this morning.
The good thing is the database works again but now the data for gpcc_pg_log_history_1_prt_2 is gone

**Comment by haolinw** [comment] 2024-03-05 12:27
> Unfortunately i cant give you the data for gpcc_pg_log_history_1_prt_2 as i dropped the gpperfmon database this morning. The good thing is the database works again but now the data for gpcc_pg_log_history_1_prt_2 is gone

Did you mean without gpperfmon database (hence no GPCC workload), the importing data job could finish successfully ?

**Comment by zlokomatic** [comment] 2024-03-05 12:37
Yes, after dropping the gpperfmon database everything is working normal again

**Comment by zlokomatic** [comment] 2024-03-06 06:24
What i mean is no segfaults anymore but i still got the error from the other issue:

https://github.com/greenplum-db/gpdb/issues/17102

**Comment by haolinw** [comment] 2024-03-06 07:15
Thanks, that's a different issue and we are looking into it.

**Comment by haolinw** [comment] 2024-03-08 08:38
For this ANALYZE crash issue, we haven't reproduced it successfully so far. It looks more like a corrupt data read issue that happened accidentally.

However, need to be aware of that we do see there was an internal bug in ANALYZE CO table which was fixed by https://github.com/greenplum-db/gpdb/pull/16629/commits/41ee9d1e77fca8cab508efa15f440e902d8959c8 on 7.1.0. This issue could impact sampling result as well as internal data alignment which may result in undefined behaviors, so recommend to patch it first for later monitoring.

**Comment by haolinw** [comment] 2024-05-21 08:03
The root cause of the issue is in sampling scenario, before swapping to next segfile scan, it was lack of resetting `blockRowCount` for new segfile reading, which would make the logic enter into wrong path to read unexpected data that messed up datum pointer, resulting in accessing out-of-bound memory address.

The issue was already fixed in commit [Fix CO sampling crashed on added column. · greenplum-db/gpdb@c0730c2](https://github.com/greenplum-db/gpdb/commit/c0730c2f0c58af4a7b12d626c21596e8b4f35864#diff-cbf9b92c771d83387a714dfbe43b5c7dda453ea457c20bffba648689479e4f7c).

**Closed by haolinw** 2024-05-21 08:03 UTC
Labels: type: bug, Priority 1, area: aoco
