### ISSUE TITLE
`ExecSquelchNode` is busted if node has PARAM changes

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#11984] opened 2021-05-13 22:05 UTC
### Step to reproduce the behavior

regression in 6X and master

```sql
CREATE TABLE foo (a int, b int);
CREATE TABLE bar (c int, d int);
CREATE TABLE baz (x int, y int);

INSERT INTO foo VALUES (1,1), (1,2);
INSERT INTO bar VALUES (1,1);

SET debug_print_plan TO on;
SET client_min_messages TO log;

EXPLAIN
SELECT *, (SELECT x FROM baz EXCEPT SELECT c FROM bar WHERE d = a) FROM foo;

```

Error message on 6X_STABLE:

```
psql:/workspace/gpdb/sql.sql:8: ERROR:  XX000: unexpected internal error (nodeMotion.c:169)
HINT:  Likely motion node is incorrectly squelched earlier
LOCATION:  ExecMotion, nodeMotion.c:169

```

### Expected behavior

Not busted

### Additional notes

Insight from @hardikar : The implementation of ExecSquelchNode is busted. It should be checking for chgParam like in 5X.

**Comment by JunfengYang** [comment] 2021-07-19 07:41
The issue is fixed by commit 361f2117968feedd98c4bad8383802edfed18548 on Master and c44a07d1ca8809076afda470eba837f37b8635f5 on 6X.
So close it.

**Closed by JunfengYang** 2021-07-19 07:41 UTC
Labels: version: 6X_STABLE, version: 7X_ALPHA
