### ISSUE TITLE
ERROR:  invalid memory alloc request size (context 'MemoryAccountMemoryContext')

### ISSUE THREAD

**Issue by kelvien** [greenplum-db/gpdb#1645] opened 2017-01-27 03:30 UTC
Hi, does anyone know why I'm getting this error : 
Full error message : 
ERROR:  invalid memory alloc request size 1073741824 (context 'MemoryAccountMemoryContext') (mcxt.c:1257) (mcxt.c:477)  (seg25 slice4 a4.local:1026 pid=604599) (cdbdisp.c:1320)
DETAIL:  
SQL statement "SELECT schema.func(10)"
PL/pgSQL function "getVal" line 4 at execute statement
********** Error **********
ERROR: invalid memory alloc request size 1073741824 (context 'MemoryAccountMemoryContext') (mcxt.c:1257) (mcxt.c:477)  (seg25 slice4 a4.local:1026 pid=604599) (cdbdisp.c:1320)
SQL state: XX000
Detail: 
SQL statement "SELECT schema.func(10)"
PL/pgSQL function "getVal" line 4 at execute statement

This happens quite a few times, and pretty random. So, I'm not sure why it sometimes happens

**Comment by asimrp** [comment] 2017-01-27 06:46
Hi @kelvien, can you dig out the stack trace from seg25 logs?  The logs should be at `a4.local:<segment_data_directory>/pg_log`.

Also, the exact query along with definition of udf `schema.func()` will be helpful.

**Comment by kelvien** [comment] 2017-01-27 15:31
@asimrp , sure.
The query for schema.func() is something along : 
`CREATE FUNCTION func (function_name TEXT, value TEXT) RETURNS AS TEXT
DECLARE
          res TEXT;
BEGIN
          EXECUTE 'SELECT ' || function_name || '(' || value || ')' INTO res; RETURN res;
END
$$ language plpgsql`
I'm still working on getting the log

**Comment by danielgustafsson** [comment] 2017-01-30 08:00
This seems to be a fairly old installation of Greenplum, are you building from source or is this a 4.3 installation?

**Comment by kelvien** [comment] 2017-01-30 15:58
@asimrp , sorry for the delay, I don't have access to view the log, but once I get it, I can post it here.
@danielgustafsson , I'm using greenplum-loaders-4.3.8.1. I notice that GP is on version 4.3.11 now, but the file they provide [here](http://gpdb.docs.pivotal.io/43100/client_tool_guides/load/unix/unix_load_install.html) is 4.3.8.1 which is what I have now. And apparently that link is also broken as of 1/30/17 10:57am EST

**Comment by mkiyama** [comment] 2017-01-30 16:14
Sorry about the broken link in the docs. 
FYI - In the 4.3.11.3 docs (updated 26Jan) the link has been fixed. 
Link to the updated page.
http://gpdb.docs.pivotal.io/43110/client_tool_guides/load/unix/unix_load_install.html

The link now points to https://network.pivotal.io/

**Comment by kelvien** [comment] 2017-01-30 16:59
@mkiyama , is greenplum loaders still in v.4.3.8 ?
I am looking at this [page](https://network.pivotal.io/products/pivotal-gpdb/) and it only has that version.
I want to try using the -S flag, but it's not for gp-loader v4.3.8. which is mentioned in the documentation for gpfdist [here](http://gpdb.docs.pivotal.io/4380/client_tool_guides/load/unix/gpfdist.html), the documentation doesn't state which version it is.

**Comment by mkiyama** [comment] 2017-01-30 17:16
hmmm... I am afraid that is the latest version. 
I will do a little more digging to figure stuff out.

**Comment by ivannovick** [comment] 2017-02-10 12:16
Hi, so the error is that the query is trying to return more than 1GB of memory which is the max for a single row.  

Looking at your function it takes 2 params and returns a simple string, which should not have this error.  Are you sure you have provided the correct function and the correct invocation?

`CREATE FUNCTION func (function_name TEXT, value TEXT) RETURNS AS TEXT DECLARE res TEXT; BEGIN EXECUTE 'SELECT ' || function_name || '(' || value || ')' INTO res; RETURN res; END $$ language plpgsql

SELECT schema.func(10)
`

**Comment by kelvien** [comment] 2017-02-10 14:48
That `func` is the function that is being referred to by the error. 
And the way I invoke it is through a bulk insert within a function. It essentially looks like 
`CREATE OR REPLACE FUNCTION dynamic_bulk_insert ()RETURNS VOID
....
EXECUTE 
'INSERT INTO big_table (name, transformed_address)
        SELECT name, func(address)
         FROM ' || staging_table_name;
...
END $$ language plpgsql;`

**Comment by ascherbaum-pivotal** [comment] 2017-02-14 15:00
What does

```
SELECT MAX(LENGTH(address)) FROM staging_table_name;
```
return?

**Comment by kelvien** [comment] 2017-02-14 16:20
@ascherbaum-pivotal , address column is of type TEXT, and the value of `MAX` I retrieve now might differ than when I got the error. But I now have it as `1000`

**Comment by amosbird** [comment] 2017-03-15 02:25
I encountered this when setting a large value of `statement_mem = 32GB`. Shrinking it to 320MB walks around this issue.

**Comment by hlinnaka** [comment] 2019-01-21 06:14
Looks like the trail has gone cold on this one. It certainly looks like a bug, but there isn't much we can do without more details. I'm closing this, but please re-open, if you can still reproduce this on the latest version. A self-contained reproducer script would be very helpful.

**Closed by hlinnaka** 2019-01-21 06:14 UTC
Labels: bug

**Comment by cobolbaby** [comment] 2024-04-21 14:56
Same issue with 6.26.3

```
2024-04-21 22:48:02.468301 CST,"gpadmin","F6_BDC",p2274946,th532646016,"192.168.2.11","49136",2024-04-21 22:44:27 CST,0,con512921,cmd86,seg16,,dx8384470,,sx1,"ERROR","XX000","invalid memory alloc request size 18446744073709551613 (mcxt.c:1312)",,,,,,"COPY fis.pca_pca_label_print_log TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-6.26.3/bin/gpbackup_s3_plugin backup_data /tmp/20240421224344_gpbackup_s3_backup.yml <SEG_DATA_DIR>/backups/20240421/20240421224344/gpbackup_<SEGID>_20240421224344_864318.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;",0,,"mcxt.c",1312,"Stack trace:
1    0xc01657 postgres errstart (elog.c:557)
2    0xc044ee postgres elog_finish (elog.c:1728)
3    0x6b4cbc postgres <symbol not found> (mcxt.c:1180)
4    0xc3c5a3 postgres <symbol not found> (mcxt.c:1305)
5    0xbb5ce3 postgres text_to_cstring (discriminator 16)
6    0xc096b8 postgres FunctionCall1Coll (fmgr.c:1317)
7    0xc101d7 postgres OutputFunctionCall (fmgr.c:1969)
8    0x8384ab postgres CopyOneRowTo (copy.c:3309)
9    0x83e9ed postgres <symbol not found> (copy.c:3052)
10   0x83f512 postgres DoCopy (copy.c:1179)
11   0xa9f78d postgres standard_ProcessUtility (utility.c:638)
12   0x7e271888ec4d metrics_collector.so AdaptorProcessUtility + 0x72
13   0x7e271888efc9 metrics_collector.so EmitUtilityQueryInfo + 0x379
14   0xa9bc91 postgres <symbol not found> (palloc.h:174)
15   0xa9c7ae postgres <symbol not found> (pquery.c:1525)
16   0xa9df37 postgres PortalRun (pquery.c:1035)
17   0xa96789 postgres <symbol not found> (postgres.c:1393)
18   0xa9b40a postgres PostgresMain (postgres.c:5489)
19   0x6b3873 postgres <symbol not found> (postmaster.c:4492)
20   0xa1efc6 postgres PostmasterMain (postmaster.c:1517)
21   0x6b7751 postgres main (main.c:205)
22   0x7e271c5a0555 libc.so.6 __libc_start_main + 0xf5
23   0x6c35fc postgres <symbol not found> + 0x6c35fc
"
2024-04-21 22:48:02.468538 CST,"gpadmin","F6_BDC",p2274946,th532646016,"192.168.2.11","49136",2024-04-21 22:44:27 CST,0,con512921,cmd86,seg16,,dx8384470,,sx1,"LOG","00000","An exception was encountered during the execution of statement: COPY fis.pca_pca_label_print_log TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-6.26.3/bin/gpbackup_s3_plugin backup_data /tmp/20240421224344_gpbackup_s3_backup.yml <SEG_DATA_DIR>/backups/20240421/20240421224344/gpbackup_<SEGID>_20240421224344_864318.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;",,,,,,"COPY fis.pca_pca_label_print_log TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-6.26.3/bin/gpbackup_s3_plugin backup_data /tmp/20240421224344_gpbackup_s3_backup.yml <SEG_DATA_DIR>/backups/20240421/20240421224344/gpbackup_<SEGID>_20240421224344_864318.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;",0,,"elog.c",2174,
```
