### ISSUE TITLE
to_char(time,'YYMMWW') function problem

### ISSUE THREAD

**Issue by wmq534** [greenplum-db/gpdb#802] opened 2016-05-31 08:14 UTC
```
1.  postgres=# SELECT EXTRACT(WEEK FROM TIMESTAMP '2016-05-13 17:40:18');
 date_part 
-----------
        19

2.select to_char(start_time,'YYMMWW') from call_detail where start_time='2016-05-13 00:00:00';
    to_char 
--------------
 160520
```
please explain why this is so,thanks

**Comment by danielgustafsson** [comment] 2016-05-31 14:09
(The Github markdown formatting was breaking readability of the question, updated to wrap SQL output in code block)

**Comment by hlinnaka** [comment] 2016-06-03 13:11
Hi!

Bizarrely enough, that's working as intended, although it looks very strange. It's because to_char()'s WW and EXTRACT(WEEK ...) have different definitions of how weeks are numbered. In to_char()'s WW format, the first week starts on January 1st, the 2nd week starts on January 8th, and so on. EXTRACT, however, works accordingly to ISO 8601. In ISO 8601, the week changes on Monday (or Sunday, depending on locale? I'm not sure), and the first Thursday in a year is on week 1. You can get ISO 8601 output from to_char() as well, with the IW format.

Some examples:
```
postgres=# select to_char('2016-01-01 00:00:00'::timestamp,'dy WW IW');;
  to_char  
-----------
 fri 01 53
(1 row)

postgres=# select to_char('2016-01-03 00:00:00'::timestamp,'dy WW IW');
  to_char  
-----------
 sun 01 53
(1 row)

postgres=# select to_char('2016-01-04 00:00:00'::timestamp,'dy WW IW');
  to_char  
-----------
 mon 01 01
(1 row)
```

There's some comments on this on the PostgreSQL user manual, too, see https://www.postgresql.org/docs/current/static/functions-formatting.html.

Hope this helps!

**Comment by wmq534** [comment] 2016-06-11 08:59
ok,thank you

**Comment by danielgustafsson** [comment] 2016-06-12 21:12
Closing this as it was answered.

**Closed by danielgustafsson** 2016-06-12 21:12 UTC
