### ISSUE TITLE
Different results on count distinct

### ISSUE THREAD

**Issue by shurik005** [greenplum-db/gpdb#15396] opened 2023-04-20 08:22 UTC
## Bug Report
I got a problem on some tables (Greenplum Database 6.22.2 build dev) with unstable result of query: 
select period, count(distinct oip) from dma_pre.tmp_iiv_v_oms_local group by period;
The execution plan contains only 2 levels of aggregation, as a result - different and incorrect results for every execution.
After executing some ddl (analyze by field, alter schema rename), the bug disappears and the plan contains 3 levels of aggregation with  stable and correct result.
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.22.2 build dev) on x86_64-unknown-linux-gnu, compiled by x86_64-alt-linux-gcc (GCC) 8.4.1 20200305 (ALT p9 8.4.1-alt0.p9.1), 64-bit compiled
### OS version and uname -a
Linux 5.10.83-std-def-alt0.c9f.2 #1 SMP x86_64 GNU/Linux
### autoconf options used ( config.status --config )
'--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--with-libxslt' '--with-openssl' '--with-pythonsrc-ext' '--with-uuid=ossp' '--with-apr-config=/usr/bin/apr-1-config' '--with-apu-config=/usr/bin/apu-1-config' '--enable-debug_extensions' '--enable-gpperfmon' '--enable-ic_proxy' '--enable-mapreduce' '--prefix=/usr/local/greenplum-db-6.22.2'
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.22.2/bin
DOCDIR = /usr/local/greenplum-db-6.22.2/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.22.2/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.22.2/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.22.2/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.22.2/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.22.2/lib
PKGLIBDIR = /usr/local/greenplum-db-6.22.2/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.22.2/share/locale
MANDIR = /usr/local/greenplum-db-6.22.2/share/man
SHAREDIR = /usr/local/greenplum-db-6.22.2/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.22.2/etc/postgresql
PGXS = /usr/local/greenplum-db-6.22.2/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--with-libxslt' '--with-openssl' '--with-pythonsrc-ext' '--with-uuid=ossp' '--with-apr-config=/usr/bin/apr-1-config' '--with-apu-config=/usr/bin/apu-1-config' '--enable-debug_extensions' '--enable-gpperfmon' '--enable-ic_proxy' '--enable-mapreduce' '--prefix=/usr/local/greenplum-db-6.22.2'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.22.2/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3 -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.22.2/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-6.22.2/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.22.2/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxerces-c -lxslt -lxml2 -lrt -lyaml -lgssapi_krb5 -luv -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.22.2/lib
VERSION = PostgreSQL 9.4.26
### Expected behavior
Plan from a copy of the cluster, the bug also manifested itself there, but was fixed by a ddl.
```
QUERY PLAN                                                                                                         |
-------------------------------------------------------------------------------------------------------------------+
Gather Motion 4:1  (slice3; segments: 4)  (cost=0.00..59479.77 rows=4 width=19)                                    |
  ->  HashAggregate  (cost=0.00..59479.77 rows=1 width=19)                                                         |
        Group Key: period                                                                                          |
        ->  Redistribute Motion 4:4  (slice2; segments: 4)  (cost=0.00..59254.13 rows=1847628 width=24)            |
              Hash Key: period                                                                                     |
              ->  HashAggregate  (cost=0.00..59115.33 rows=1847628 width=24)                                       |
                    Group Key: period, oip                                                                         |
                    ->  Redistribute Motion 4:4  (slice1; segments: 4)  (cost=0.00..58637.09 rows=1847628 width=24)|
                          Hash Key: period, oip                                                                    |
                          ->  HashAggregate  (cost=0.00..58498.30 rows=1847628 width=24)                           |
                                Group Key: period, oip                                                             |
                                ->  Seq Scan on tmp_iiv_v_oms_local  (cost=0.00..15609.43 rows=144487680 width=24) |
Optimizer: Pivotal Optimizer (GPORCA)                                                                              |

13 row(s) fetched.
```
### Actual behavior
```
QUERY PLAN                                                                                                          |
--------------------------------------------------------------------------------------------------------------------+
Gather Motion 9:1  (slice3; segments: 9)  (cost=0.00..46361.90 rows=3 width=19)                                     |
  ->  HashAggregate  (cost=0.00..46361.90 rows=1 width=19)                                                          |
        Group Key: period                                                                                           |
        ->  Redistribute Motion 9:9  (slice2; segments: 9)  (cost=0.00..28725.89 rows=48135304 width=24)            |
              Hash Key: period                                                                                      |
              ->  HashAggregate  (cost=0.00..23261.57 rows=48135304 width=24)                                       |
                    Group Key: period, oip                                                                          |
                    ->  Redistribute Motion 9:9  (slice1; segments: 9)  (cost=0.00..10802.23 rows=48135304 width=24)|
                          Hash Key: period, oip, oip                                                                |
                          ->  Seq Scan on tmp_iiv_v_oms_local  (cost=0.00..5037.55 rows=48135304 width=24)          |
Optimizer: Pivotal Optimizer (GPORCA)  

11 row(s) fetched.
```
### Step to reproduce the behavior
Unfortunately, it is not possible to generate a test case.

**Comment by Smyatkin-Maxim** [comment] 2023-04-20 09:02
Likely a duplicate of https://github.com/greenplum-db/gpdb/issues/14993 ?

**Comment by shurik005** [comment] 2023-04-20 13:27
Thanks, that's it - I missed this bug

**Closed** 2023-04-20 14:34 UTC
Labels: type: bug
