### ISSUE TITLE
Wrong answer in WITH RECURSIVE query with small statement_mem

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#3284] opened 2017-09-14 11:22 UTC
Bumped into this case from the `join_gp` regression test:

```
create table dept
(
	id int,
	pid int,
	name char(40)
);
insert into dept values(3, 0, 'root');
insert into dept values(4, 3, '2<-1');
insert into dept values(5, 4, '3<-2<-1');
insert into dept values(6, 4, '4<-2<-1');
insert into dept values(7, 3, '5<-1');
insert into dept values(8, 7, '5<-1');
insert into dept select i, i % 6 + 3 from generate_series(9,50) as i;
insert into dept select i, 99 from generate_series(100,15000) as i;
ANALYZE dept;

postgres=# WITH RECURSIVE subdept(id, parent_department, name) AS
(
-- non recursive term
SELECT * FROM dept WHERE name = 'root'
UNION ALL
-- recursive term
SELECT d.* FROM dept AS d, subdept AS sd
WHERE d.pid = sd.id
)
SELECT count(*) FROM subdept;
 count 
-------
    48
(1 row)
```

But when I run the same query with a smaller `statement_mem`, you get a different result:
```
postgres=# set statement_mem='700kB';
SET
postgres=# WITH RECURSIVE subdept(id, parent_department, name) AS
(
-- non recursive term
SELECT * FROM dept WHERE name = 'root'
UNION ALL
-- recursive term
SELECT d.* FROM dept AS d, subdept AS sd
WHERE d.pid = sd.id
)
SELECT count(*) FROM subdept;
 count 
-------
    26
(1 row)
```

Looking at the EXPLAIN ANALYZE output, the difference seems to be that with the smaller `statement_mem`, a multi-batch hash join is performed, while with a larger `statement_mem`, it fits in a single batch. Here's the EXPLAIN ANALYZE output with smaller `statement_mem`, where you get the incorrect result:

```
                                                                                         QUERY PLAN                                                                                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=3363.62..3363.63 rows=1 width=8)
   Rows out:  1 rows with 35 ms to end, start offset by 17 ms.
   ->  Gather Motion 3:1  (slice2; segments: 3)  (cost=3363.55..3363.60 rows=1 width=8)
         Rows out:  3 rows at destination with 33 ms to first row, 35 ms to end, start offset by 17 ms.
         ->  Aggregate  (cost=3363.55..3363.56 rows=1 width=8)
               Rows out:  Avg 1.0 rows x 3 workers.  Max 1 rows (seg0) with 34 ms to end, start offset by 18 ms.
               ->  Subquery Scan subdept  (cost=0.00..2989.82 rows=49831 width=0)
                     Rows out:  48 rows (seg1) with 0.067 ms to first row, 34 ms to end, start offset by 18 ms.
                     ->  Recursive Union  (cost=0.00..19073.84 rows=49831 width=49)
                           Rows out:  48 rows (seg1) with 0.065 ms to first row, 34 ms to end, start offset by 18 ms.
                           ->  Seq Scan on dept  (cost=0.00..204.86 rows=1 width=49)
                                 Filter: name = 'root'::bpchar
                                 Rows out:  1 rows (seg1) with 0.061 ms to first row, 1.849 ms to end, start offset by 18 ms.
                           ->  Hash Join  (cost=1326.04..1587.92 rows=4983 width=49)
                                 Hash Cond: sd.id = d.pid
                                 Rows out:  47 rows (seg1) with 29 ms to first row, 30 ms to end of 4 scans, start offset by 50 ms.
                                 Executor memory:  468K bytes avg, 468K bytes max (seg0).
                                 Work_mem used:  468K bytes avg, 468K bytes max (seg0). Workfile: (0 spilling)
                                 (seg1)   Hash chain length 1868.6 avg, 14901 max, using 8 of 262144 buckets.
                                 ->  WorkTable Scan on subdept sd  (cost=0.00..0.24 rows=5 width=4)
                                       Rows out:  48 rows (seg1) with 0.003 ms to first row, 0.025 ms to end of 4 scans, start offset by 50 ms.
                                 ->  Hash  (cost=765.45..765.45 rows=14949 width=49)
                                       Rows in:  Avg 14949.0 rows x 3 workers.  Max 14949 rows (seg0) with 27 ms to end, start offset by 22 ms.
                                       ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..765.45 rows=14949 width=49)
                                             Rows out:  Avg 14949.0 rows x 3 workers at destination.  Max 14949 rows (seg0) with 0.698 ms to first row, 16 ms to end, start offset by 22 ms.
                                             ->  Seq Scan on dept d  (cost=0.00..167.49 rows=4983 width=49)
                                                   Rows out:  Avg 4983.0 rows x 3 workers.  Max 4999 rows (seg2) with 0.072 ms to first row, 1.053 ms to end, start offset by 19 ms.
 Slice statistics:
   (slice0)    Executor memory: 418K bytes.
   (slice1)    Executor memory: 224K bytes avg x 3 workers, 224K bytes max (seg0).
   (slice2)    Executor memory: 6519K bytes avg x 3 workers, 6519K bytes max (seg0).  Work_mem: 468K bytes max.
 Statement statistics:
   Memory used: 128000K bytes
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
 Total runtime: 52.362 ms
(36 rows)
```

**Comment by hsyuan** [comment] 2017-09-15 06:05
It may be caused by this commit: https://github.com/greenplum-db/gpdb/pull/2770

**Comment by hsyuan** [comment] 2017-09-15 06:25
I think this commit https://github.com/greenplum-db/gpdb/commit/391e9ea7fa21574791ed2735266cc2f1ed328934 lacks thorough test cases.
I would prefer to just revert the changes for rescanning hash table, and materialize all the motions under recursive term (right child) of recursive union and work table scan can be on either side of the join. 
What do you think, @hlinnaka ?

**Comment by hlinnaka** [comment] 2017-09-15 06:34
On 09/15/2017 09:25 AM, Haisheng Yuan wrote:
> I think this commit https://github.com/greenplum-db/gpdb/commit/391e9ea7fa21574791ed2735266cc2f1ed328934 lacks thorough test cases.
> I would prefer to just revert the changes for rescanning hash table, and materialize all the motions under recursive term (right child) of recursive union and work table scan can be on either side of the join.
> What do you think, @hlinnaka ?

If you think that's easier..

Sounds like we need to add more tests for this in any case. I'd suggest 
that we do that first, and see how difficult it would be to fix the 
current code. It might turn out to be easy. But if it's badly broken, 
then revert and add the materialize node instead.

- Heikki

**Comment by jchampio** [comment] 2017-09-15 16:47
@hsyuan I was under the impression that 391e9ea was the commit that *added* the test to begin with?

**Comment by hsyuan** [comment] 2017-09-18 17:17
@jchampio Yes, you are right. But the test in ICG only sets statement_mem to 1MB. The test fails when the statement_mem is 700KB, in which case the hash table has different number of batch files.

**Comment by jchampio** [comment] 2017-09-18 19:37
In case it helps at all, here is the log output from the statement when running on top of Postgres 8.4:

```
regression=# WITH RECURSIVE subdept(id, parent_department, name) AS                                                   (
    -- non recursive term
    SELECT * FROM dept WHERE name = 'root'
    UNION ALL
    -- recursive term
    SELECT d.* FROM dept AS d, subdept AS sd
    WHERE d.pid = sd.id
)
SELECT count(*) FROM subdept;
LOG:  statement: WITH RECURSIVE subdept(id, parent_department, name) AS
(

    SELECT * FROM dept WHERE name = 'root'
    UNION ALL

    SELECT d.* FROM dept AS d, subdept AS sd
        WHERE d.pid = sd.id
)
SELECT count(*) FROM subdept;
LOG:  2017-09-18 12:30:09:291552 PDT,THD000,NOTICE,"Feature not supported by the Pivotal Query Optimizer: WITH RECURSIVE",
LOG:  Planner produced plan :0
LOG:  ExecChooseHashTableSize results: 1024 buckets, 4 batches  (seg0 slice2 127.0.0.1:25432 pid=90132)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 4, mintuples 7, maxtuples 12799  (seg0 slice2 127.0.0.1:25432 pid=90132)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 8, mintuples 0, maxtuples 12799  (seg0 slice2 127.0.0.1:25432 pid=90132)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 16, mintuples 0, maxtuples 12801  (seg0 slice2 127.0.0.1:25432 pid=90132)
LOG:  HJ: Disabling further increase of nbatch  (seg0 slice2 127.0.0.1:25432 pid=90132)
LOG:  ExecChooseHashTableSize results: 1024 buckets, 4 batches  (seg1 slice2 127.0.0.1:25433 pid=90133)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 4, mintuples 7, maxtuples 12799  (seg1 slice2 127.0.0.1:25433 pid=90133)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 8, mintuples 0, maxtuples 12799  (seg1 slice2 127.0.0.1:25433 pid=90133)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 16, mintuples 0, maxtuples 12801  (seg1 slice2 127.0.0.1:25433 pid=90133)
LOG:  HJ: Disabling further increase of nbatch  (seg1 slice2 127.0.0.1:25433 pid=90133)
LOG:  ExecChooseHashTableSize results: 1024 buckets, 4 batches  (seg2 slice2 127.0.0.1:25434 pid=90134)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 4, mintuples 7, maxtuples 12799  (seg2 slice2 127.0.0.1:25434 pid=90134)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 8, mintuples 0, maxtuples 12799  (seg2 slice2 127.0.0.1:25434 pid=90134)
LOG:  Extreme skew in the innerside of Hashjoin, nbatch 16, mintuples 0, maxtuples 12801  (seg2 slice2 127.0.0.1:25434 pid=90134)
LOG:  HJ: Disabling further increase of nbatch  (seg2 slice2 127.0.0.1:25434 pid=90134)
 count
-------
    26
(1 row)
```

**Comment by jchampio** [comment] 2017-09-18 21:05
Also interesting: it looks like master *is* spilling to disk at 1000kB, or at the very least it is triggering the multi-batch hashjoin code. But it doesn't actually fail.

The multi-batch code fails when the new 8.4 hash function is put into use.

**Comment by hsyuan** [comment] 2017-09-28 00:31
Fixed in PR https://github.com/greenplum-db/gpdb/pull/3330

**Closed by hsyuan** 2017-09-28 00:31 UTC
Labels: Planner
