### ISSUE TITLE
Fail to install ORCA with dependency on macOS

### ISSUE THREAD

**Issue by dayuebai** [greenplum-db/gpdb#5579] opened 2018-08-24 00:16 UTC
@xinzweb 

### Greenplum version or build
5.10.2

### OS version and uname -a
macOS High Sierra Version 10.13.6

### autoconf options used ( config.status --config )
N/A

### Installation information ( pg_config )
N/A

### Expected behavior
compile and install ORCA successfully with dependency (conan)

### Actual behavior
After I change directory to ```gpdb/depends``` and execute ```make``` command, it gives me the following error:

> ERROR: orca/v2.70.0@gpdb/stable: Error in build_requirements() method, line 35
> if int(vers.split(".")[0]) < 3:
> TypeError: a bytes-like object is required, not 'str'
> make: *** [orca] Error 1

### Step to reproduce the behavior
After [installing dependency for macOS](https://github.com/greenplum-db/gpdb#installing-dependencies-for-macos-developers), I try to [build the optimizer](https://github.com/greenplum-db/gpdb#build-the-optimizer)

```
cd depends
./configure
make
```

**Comment by bhuvnesh2703** [comment] 2018-08-24 19:00
Hello @dayuebai, thanks for reporting the issue
The error reported comes while trying to parse the cmake version. Relevant code here:
```
            vers = subprocess.check_output(["cmake", "--version"]).split()[2]
            if int(vers.split(".")[0]) < 3:
                if int(vers.split(".")[1]) < 1:
                    raise Exception("CMake version 3.1 or higher is required")

```
Could you please share the output of below command:
```
cmake --version
```

**Comment by dayuebai** [comment] 2018-08-24 20:14
Hello @bhuvnesh2703 , thank you for your response. Below is the output of the ```cmake --version``` command:

```cmake version 3.12.1```

When this part of code: ```int(vers.split(".")[0])``` runs, it tries to convert a string: ```cmake version 3``` into an integer, then python throws the exception: ```TypeError: a bytes-like object is required, not 'str'```

**Comment by bhuvnesh2703** [comment] 2018-09-05 21:11
@dayuebai 
if `cmake --version` command on your system is giving the output as `cmake version 3.12.1`, i will expect it to parse it successfully.
`subprocess.check_output(["cmake", "--version"]).split()[2]` ==> will give `3.12.1`
`vers.split(".")[0]` ==> will give `3`

For instance, output from my system:
```
here is the output ======>
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

here is the version string =====> 3.7.2
here is the first digit of version string =====> 3
```
I just added some print statements for debugging.

Can you give me the output of it 
```
#!/usr/bin/env python
import subprocess
cmake_version = subprocess.check_output(["cmake", "--version"])
print "here is the output ======> \n{0}".format(cmake_version)
vers = cmake_version.split()[2]
print "here is the version string =====> {0}".format(vers)
first_digit = vers.split(".")[0]
print "here is the first digit of version string =====> {0}".format(first_digit)
if int(first_digit) < 3:
    if int(vers.split(".")[1]) < 1:
        raise Exception("CMake version 3.1 or higher is required")
```
and your python version.

**Comment by dayuebai** [comment] 2018-09-05 21:26
FYI, I have manually installed ORCA successfully without dependency.

**Comment by bhuvnesh2703** [comment] 2018-09-05 21:29
@dayuebai thanks for the update, if you have the environment where is the issue is reproducible, send me an email at bchaudhary@pivotal.io, we can pair over hangout and debug.
If you think this is no longer an issue, let me know, i can close this.

**Comment by divyabhargov** [comment] 2018-09-07 18:34
@bhuvnesh2703  I have a similar environment and I can reproduce the exact issue mentioned by @dayuebai. Happy to pair to have this resolved on my mac

**Comment by dayuebai** [comment] 2018-09-07 22:10
@divyabhargov @bhuvnesh2703 Great, feel free to ask me if you still need me to reproduce the issue.

**Comment by schnjaso2** [comment] 2019-03-21 21:47
getting the same failure as OP

mac osx 10.14.3
cmake version 3.14.0
Python 3.7.0


mac:bin jasonschneider$ ./env
SSH_AGENT_PID=11486
NVM_CD_FLAGS=
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/6y/f54whxk159jdfdp9tt750hwr0000gn/T/
SSH_CLIENT=127.0.0.1 61399 22
SSH_TTY=/dev/ttys007
NVM_DIR=/Users/jasonschneider/.nvm
USER=jasonschneider
SSH_AUTH_SOCK=/var/folders/6y/f54whxk159jdfdp9tt750hwr0000gn/T//ssh-DL9BeVdD99vn/agent.11484
MAIL=/var/mail/jasonschneider
PATH=/Users/jasonschneider/go/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxml2/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/jasonschneider/.rbenv/shims:/Users/jasonschneider/miniconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jasonschneider/go/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/libxml2/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/jasonschneider/.rbenv/shims:/Users/jasonschneider/miniconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/jasonschneider/google-cloud-sdk/bin
PWD=/usr/bin
HOMEBREW_GITHUB_API_TOKEN=f854609479f9b890df4063ef7fcae1ffb9099590
LANG=en_US.UTF-8
PGHOST=mac.local
RBENV_SHELL=bash
SHLVL=1
HOME=/Users/jasonschneider
LOGNAME=jasonschneider
SSH_CONNECTION=127.0.0.1 61399 127.0.0.1 22
GOPATH=/Users/jasonschneider/go
_=./env
OLDPWD=/

**Comment by dreamedcheng** [comment] 2019-05-29 03:44
you can use find command to find the conanfile.py file under depends dir, and then modify vers.split(".")[0] to vers.decode().split(".")[0].  This works for me.

**Comment by odinms** [comment] 2019-08-08 07:28
Same goes here..

 cmake version : cmake3 version 3.13.5
python: 3.7.4


This looks like the right solution for the issue, I did run the code in python and  funtion decode() is needed to get the rigth version number '3'.   But it seems gp team has stored the python code in a cloud OSS, I can't find  conanfile.py file under depends dir now for realese 5.21.2 . Back to the manually make way to solve this problem....
> you can use find command to find the conanfile.py file under depends dir, and then modify vers.split(".")[0] to vers.decode().split(".")[0]. This works for me.

**Comment by dreamedcheng** [comment] 2019-08-13 02:01
> Same goes here..
> 
> cmake version : cmake3 version 3.13.5
> python: 3.7.4
> 
> This looks like the right solution for the issue, I did run the code in python and funtion decode() is needed to get the rigth version number '3'. But it seems gp team has stored the python code in a cloud OSS, I can't find conanfile.py file under depends dir now for realese 5.21.2 . Back to the manually make way to solve this problem....
> 
> > you can use find command to find the conanfile.py file under depends dir, and then modify vers.split(".")[0] to vers.decode().split(".")[0]. This works for me.

When you execute make install_local under depends, it will download the python script from OSS.

**Comment by divyabhargov** [comment] 2022-02-08 20:48
@bhuvnesh2703 is this closeable ?

**Comment by bhuvnesh2703** [comment] 2022-02-08 22:08
This can be closed. This code existing in conanfile.py which has now been removed.

**Closed by bhuvnesh2703** 2022-02-08 22:08 UTC
Labels: area: gporca
