### ISSUE TITLE
some times Redistribute Motion run slowly

### ISSUE THREAD

**Issue by cowcomic** [greenplum-db/gpdb#15137] opened 2023-03-06 06:35 UTC
## Bug Report
run a simple sql with "group by"
most of time it runs fast
some time it runs slow 

```sql
explain analyze select sdeptname,count(*) from dm_signs.dm_sgxpt_kafka_11111_t0015_jnq_d group by sdeptname;
```
```
 Gather Motion 18:1  (slice3; segments: 18)  (cost=0.00..524.98 rows=41 width=16) (actual time=5419.007..5419.404 rows=52 loops=1)
   ->  HashAggregate  (cost=0.00..524.98 rows=3 width=16) (actual time=5418.881..5418.895 rows=5 loops=1)
         Group Key: (CASE WHEN ((sdeptname)::text = 'aaaaa'::text) THEN 'bbbbb'::character varying WHEN ((sdeptname)::text = 'ccccc'::text) THEN 'ddddd'::character varying WHEN ((sdeptname)::text = 'eeeee'::text) THEN 'fffff'::character varying ELSE sdeptname END)
         Extra Text: (seg0)   Hash chain length 1.3 avg, 2 max, using 3 of 32 buckets; total 0 expansions.
         Extra Text: (seg17)  Hash chain length 1.2 avg, 2 max, using 4 of 32 buckets; total 0 expansions.
         ->  Redistribute Motion 18:18  (slice2; segments: 18)  (cost=0.00..524.98 rows=3 width=16) (actual time=5335.622..5418.898 rows=71 loops=1)
               Hash Key: (CASE WHEN ((sdeptname)::text = 'aaaaa'::text) THEN 'bbbbb'::character varying WHEN ((sdeptname)::text = 'ccccc'::text) THEN 'ddddd'::character varying WHEN ((sdeptname)::text = 'eeeee'::text) THEN 'fffff'::character varying ELSE sdeptname END)
               ->  Result  (cost=0.00..524.98 rows=3 width=16) (actual time=5337.379..5337.401 rows=46 loops=1)
                     ->  HashAggregate  (cost=0.00..524.98 rows=3 width=16) (actual time=5337.378..5337.390 rows=46 loops=1)
                           Group Key: CASE WHEN ((sdeptname)::text = 'aaaaa'::text) THEN 'bbbbb'::character varying WHEN ((sdeptname)::text = 'ccccc'::text) THEN 'ddddd'::character varying WHEN ((sdeptname)::text = 'eeeee'::text) THEN 'fffff'::character varying ELSE sdeptname END
                           Extra Text: (seg10)  Hash chain length 1.9 avg, 4 max, using 24 of 32 buckets; total 0 expansions.
                           ->  Result  (cost=0.00..523.65 rows=10538 width=8) (actual time=5311.799..5359.946 rows=26683 loops=1)
                                 ->  Result  (cost=0.00..523.57 rows=10538 width=14) (actual time=5311.791..5349.606 rows=26683 loops=1)
                                       Filter: ((row_number() OVER (?)) = 1)
                                       ->  WindowAgg  (cost=0.00..522.70 rows=26344 width=22) (actual time=5311.784..5343.068 rows=26689 loops=1)
                                             Partition By: pkid
                                             Order By: insert_time
                                             ->  Sort  (cost=0.00..521.86 rows=26344 width=32) (actual time=5311.772..5314.510 rows=26689 loops=1)
                                                   Sort Key: pkid, insert_time
                                                   Sort Method:  quicksort  Memory: 157058kB
                                                   ->  Redistribute Motion 18:18  (slice1; segments: 18)  (cost=0.00..451.67 rows=26344 width=32) (actual time=2.219..5275.038 rows=26689 loops=1)
                                                         Hash Key: pkid
                                                         ->  Seq Scan on ods_sgxpt_kafka_12345_t0015_jnq_d  (cost=0.00..447.46 rows=26344 width=32) (actual time=0.004..19.538 rows=26597 loops=1)
 Planning time: 10.752 ms
   (slice0)    Executor memory: 255K bytes.
   (slice1)    Executor memory: 189K bytes avg x 18 workers, 189K bytes max (seg0).
   (slice2)    Executor memory: 8918K bytes avg x 18 workers, 9176K bytes max (seg0).  Work_mem: 8953K bytes max.
   (slice3)    Executor memory: 112K bytes avg x 18 workers, 120K bytes max (seg0).
 Memory used:  128000kB
 Optimizer: Pivotal Optimizer (GPORCA) version 3.80.0
 Execution time: 5421.786 ms
(34 rows)
```

from explain Redistribute Motion cost all the slow time

how to solve this problem?

### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.1.0 build commit:6788ca8c13b2bd6e8976ccffea07313cbab30560) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04
.1) 7.4.0, 64-bit compiled on Nov  1 2019 22:05:47

### OS version and uname -a
Linux XXX 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kainwen** [comment] 2023-03-06 07:45
First reading your description, I feel this is not a bug. Maybe some network related configuration.

* what is the gp_max_packet_size?
* what is your network's MTU?
* what is you kernel parameter config of network?

Plus, the issue is opened on the version `6.1.0`, which is super super old. Please upgrade to recent-released Greenplum 6.

I doubt there is anyone who is interested in hunting bugs in such an old version.

**Comment by cowcomic** [comment] 2023-03-07 09:42
> First reading your description, I feel this is not a bug. Maybe some network related configuration.
> 
> * what is the gp_max_packet_size?
> * what is your network's MTU?
> * what is you kernel parameter config of network?
> 
> Plus, the issue is opened on the version `6.1.0`, which is super super old. Please upgrade to recent-released Greenplum 6.
> 
> I doubt there is anyone who is interested in hunting bugs in such an old version.

```
gp_max_packet_size  8192

mtu 1500
```

kernel parameter config
```
kernel.shmmax = 500000000
kernel.shmmni = 4096
kernel.shmall = 4000000000
kernel.sem = 250 512000 100 2048
kernel.sysrq = 1
kernel.core_uses_pid = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.msgmni = 2048
net.ipv4.tcp_syncookies = 0
net.ipv4.ip_forward = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_max_syn_backlog = 200000
net.ipv4.conf.all.arp_filter = 1
net.ipv4.ip_local_port_range = 1025 65535
net.core.netdev_max_backlog = 200000
fs.nr_open = 3000000
kernel.threads-max = 798720
kernel.pid_max = 798720
net.core.rmem_max=2097152
net.core.wmem_max=2097152
vm.overcommit_memory=2
vm.dirty_background_ratio = 10
vm.dirty_ratio = 6
vm.overcommit_ratio = 80
```

we found that the failure rate decreased when gp_interconnect_type changed to tcp instead of udp

**Comment by kainwen** [comment] 2023-03-07 09:48
> > First reading your description, I feel this is not a bug. Maybe some network related configuration.
> > 
> > * what is the gp_max_packet_size?
> > * what is your network's MTU?
> > * what is you kernel parameter config of network?
> > 
> > Plus, the issue is opened on the version `6.1.0`, which is super super old. Please upgrade to recent-released Greenplum 6.
> > I doubt there is anyone who is interested in hunting bugs in such an old version.
> 
> ```
> gp_max_packet_size  8192
> 
> mtu 1500
> ```
> 
> kernel parameter config
> 
> ```
> kernel.shmmax = 500000000
> kernel.shmmni = 4096
> kernel.shmall = 4000000000
> kernel.sem = 250 512000 100 2048
> kernel.sysrq = 1
> kernel.core_uses_pid = 1
> kernel.msgmnb = 65536
> kernel.msgmax = 65536
> kernel.msgmni = 2048
> net.ipv4.tcp_syncookies = 0
> net.ipv4.ip_forward = 0
> net.ipv4.conf.default.accept_source_route = 0
> net.ipv4.tcp_tw_recycle = 1
> net.ipv4.tcp_max_syn_backlog = 200000
> net.ipv4.conf.all.arp_filter = 1
> net.ipv4.ip_local_port_range = 1025 65535
> net.core.netdev_max_backlog = 200000
> fs.nr_open = 3000000
> kernel.threads-max = 798720
> kernel.pid_max = 798720
> net.core.rmem_max=2097152
> net.core.wmem_max=2097152
> vm.overcommit_memory=2
> vm.dirty_background_ratio = 10
> vm.dirty_ratio = 6
> vm.overcommit_ratio = 80
> ```
> 
> we found that the failure rate decreased when gp_interconnect_type changed to tcp instead of udp

If you use UDP, based on you configuration of 

```
gp_max_packet_size  8192

mtu 1500
```

gpdb's package size is larger than mtu.


You can try to enlarge the the value of `net.ipv4.ipfrag_high_thresh ` might help.

There is a blog on this topic from Internet (in Chinese):  https://blog.hidva.com/2020/05/04/mtu-query-block/, please refer to it if needed.

Close this issue, this is not a bug actually.

**Closed by kainwen** 2023-03-07 09:48 UTC
Labels: type: bug

**Comment by cobolbaby** [comment] 2023-03-08 03:13
Same as https://github.com/greenplum-db/gpdb/issues/14321
