### ISSUE TITLE
Configuring --with-libxml on macOS Sierra links psql against the wrong libpq

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpdb#3215] opened 2017-09-08 18:11 UTC
On macOS Sierra, running the configure script with `--with-libxml` occasionally leads to the dreaded

    psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?

when running psql. The root cause appears to be that`xml2-config --libs` returns a link path to the macOS SDK, which includes its own version of libpq that then takes precedence over the one we have built.

To reproduce, you can configure and build with the `--with-libxml` option, then run `otool -l src/bin/psql/psql` to see where the binary is linked. In my case, I expect to see an entry similar to
```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name /usr/local/gpdb/lib/libpq.5.dylib (offset 24)    <-- good
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 5.3.0
compatibility version 5.0.0
```
but instead I see
```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libpq.5.dylib (offset 24)     <-- bad
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 5.6.0
compatibility version 5.0.0
```
As [many others have discovered](https://stackoverflow.com/questions/13868730/socket-file-var-pgsql-socket-s-pgsql-5432-missing-in-mountain-lion-os-x-ser), this problem can be worked around by setting `PGHOST`.

**Comment by xinzweb** [comment] 2018-02-05 22:48
I hit the same issue as mentioned in #3627 on High Sierra (10.13.3) with latest master from (d7da51221382866a253d6805e6a442493ad4e588), and then following the instruction from #3627 and also clean-up my local repo, the problem is fixed in `make create-demo-cluster`.

Running `psql` and see whether `connections on Unix domain socket "/tmp/.s.PGSQL.15432"` this one is used is really helpful to narrow down the issue. Thanks a lot for the debugging context.

In this case, @jchampio is there any other thing to do before we can resolve this issue? Thanks.

**Comment by jchampio** [comment] 2018-02-11 18:44
@xinzweb The workaround I have in place on my machine is to modify `src/bin/psql/Makefile`:

```diff
 psql: $(OBJS) $(libpq_builddir)/libpq.a
-       $(CC) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_EX) $(OBJS) $(libpq_pgport) $(LIBS) -o $@$(X)
+       $(CC) $(CFLAGS) $(libpq_pgport) $(LDFLAGS) $(LDFLAGS_EX) $(OBJS) $(LIBS) -o $@$(X)
```

This ensures that our library takes precedence. I haven't really put too much thought into whether this is the *correct* fix, so I haven't put it into a PR.

**Comment by jchampio** [comment] 2018-02-11 18:46
(The correct fix is probably to not put libraries into `LDFLAGS`; that's what `LDLIBS` is supposed to be for.)

**Comment by xinzweb** [comment] 2018-02-26 17:57
As you have mentioned `The correct fix is probably to not put libraries into LDFLAGS; that's what LDLIBS is supposed to be for.`, we should just chase where the LDFLAGS included in the libraries and fix from there. :) Thanks a lot for the pointer.

**Comment by xinzweb** [comment] 2018-03-02 16:21
Well, look at the `Makefile.global.in` file, and it has comments regarding to LDFLAGS will include the `libpgport.a` file as the first in `LDFLAGS`, which is defined in the line 277. The `libpq_pgport` variable is actually defined in same file at line 489.

@jchampio maybe your fix above to switch the order of the `libpq_pgport` would be a best localized fix to have the psql connect to the proper `libpq` then?

Also, seems like this issue only happened on MacOs, and not on Ubuntu. This is the configuration flags i used, and it has `--with-libxml`, and the psql linked to the proper version of the `libpq`.

```
xzhang@xzhang-iMac:~/workspace/gpdb$ ldd /usr/local/gpdb/bin/psql 
	linux-vdso.so.1 =>  (0x00007ffe2b992000)
	libpq.so.5 => /usr/local/gpdb/lib/libpq.so.5 (0x00007f3ede4b3000)
	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007f3ede269000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3edde89000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3eddc6a000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f3edda41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3ede958000)
xzhang@xzhang-iMac:~/workspace/gpdb$ ./config.status --config
'--with-libxml' '--with-perl' '--with-python' '--without-rt' '--enable-cassert' '--disable-option-checking' '--enable-profiling' '--enable-mapreduce' '--enable-debug' '--disable-orca' '--disable-pxf' 'CC=ccache cc'
```

**Comment by jchampio** [comment] 2018-03-07 02:11
@xinzweb So I just noticed... upstream's version of this Makefile has the correct order. I'll run it through the pipeline; maybe we can just close this easily.

**Comment by xinzweb** [comment] 2018-03-12 21:26
+1 on that. We can have one less issue to work around. Cannot wait for the PR.

**Closed** 2018-03-25 23:58 UTC
