### ISSUE TITLE
could not fsync file "N/N/N.129"" (is_ao: 0): No such file or directory

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#11257] opened 2020-12-09 06:19 UTC
### Greenplum version or build
greenplum 6.4.0

In our mirror segment of GP, there are logs likes below, causing mirror  frequently replay WAL to catch up with primary, which resulting high I/O
```
2020-10-14 11:07:01.038529 WIB,,,p75411,th-477783936,,,,0,,,seg6,,,,,"PANIC","58P01","could not fsync file ""base/29022/48242.129"" (is_ao: 0): No such file or directory",,,,,,,0,,"md.c",1321,"Stack trace:
1    0x9d024c postgres errstart + 0x1dc
2    0x869284 postgres mdsync + 0x264
3    0x83a8f0 postgres CheckPointBuffers + 0xf0
4    0x54cd16 postgres CreateRestartPoint + 0x466
5    0x7edd37 postgres CheckpointerMain + 0x417
6    0x58cb2a postgres AuxiliaryProcessMain + 0x52a
7    0x7f96b5 postgres <symbol not found> + 0x7f96b5
8    0x7fadfc postgres <symbol not found> + 0x7fadfc
9    0x7f61e0497620 libpthread.so.0 <symbol not found> + 0xe0497620
10   0x7f61df909fe3 libc.so.6 __select + 0x13
11   0x4cb248 postgres <symbol not found> + 0x4cb248
12   0x7fccea postgres PostmasterMain + 0x108a
13   0x4cdf3b postgres main + 0x1db
14   0x7f61df837445 libc.so.6 __libc_start_main + 0xf5
15   0x4ce741 postgres <symbol not found> + 0x4ce741
"
2020-10-14 11:07:01.052198 WIB,,,p79458,th-477783936,,,,0,,,seg6,,,,,"LOG","00000","checkpointer process (PID 75411) was terminated by signal 6: Aborted",,,,,,,0,,"postmaster.c",3962,
2020-10-14 11:07:01.052224 WIB,,,p79458,th-477783936,,,,0,,,seg6,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3679,
2020-10-14 11:07:01.054219 WIB,,,p79458,th-477783936,,,,0,,,seg6,,,,,"LOG","00000","all server processes terminated; reinitializing",,,,,,,0,,"postmaster.c",4214,
```
I have search the issue list,  and found some similar issue #9034 but has been fixed before GP6.4.So, I think it is a new bug.
I just has logs (maintenance staff had restart the DB, so now we just has logs, the table related may also be deleted) but do not know the root cause, could you please give us some advice about this PANIC? 
In detail， what does the is_ao means? what does the error message indicate?
Thanks~

**Comment by paul-guo-** [comment] 2020-12-10 01:26
Can you check on the pg data directory of the panic segment

```
ls base/29022/48242*
```

`is_ao: 0` means the fsync request is not for ao table, but the file name `48242.129` looks more like an ao table file (of course it is possible that it is a large heap table). Not sure if this would be a clue.

Also 6.4.0 is a bit old, better upgrade to see if there have been fixes for such kind of issues.

**Comment by LittleWuCoding** [comment] 2020-12-10 12:32
@paul-guo-  Thanks for your replies~
As for your advice:
1) I have had checked the pg data directory, did not find the file
2) I have had asked the business person， find that most table in the database is partitioned AOCO table
3) And in their business, they frequently add/delete partitions of the AOCO table mentioned above in 2)  around the time this issue occurs
4) Now ,I failed to reprodued it. Also, we has a test env which has running well for about half month

**Comment by ashwinstar** [comment] 2021-02-19 23:33
Based on earlier comments from @LittleWuCoding the issue is not reproducible and no further action can be taken based on what we have so far reported on the issue. Closing the same.

**Closed by ashwinstar** 2021-02-19 23:33 UTC
