### ISSUE TITLE
error:Lookup of object 0.0.0.0 in cache failed

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [greenplum-db/gpdb#11655] opened 2021-03-16 01:36 UTC
### Greenplum version or build
6.15.0
### OS version and uname -a
CentOS Linux release 7.3.1611 (Core)
Linux gp01 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.15.0/bin
DOCDIR = /usr/local/greenplum-db-6.15.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.15.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.15.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.15.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.15.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.15.0/lib
PKGLIBDIR = /usr/local/greenplum-db-6.15.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.15.0/share/locale
MANDIR = /usr/local/greenplum-db-6.15.0/man
SHAREDIR = /usr/local/greenplum-db-6.15.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.15.0/etc/postgresql
PGXS = /usr/local/greenplum-db-6.15.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-quicklz' '--enable-gpperfmon' '--with-gssapi' '--enable-mapreduce' '--enable-orafce' '--enable-orca' '--with-libxml' '--with-pgport=5432' '--disable-debug-extensions' '--disable-tap-tests' '--enable-ic-proxy' '--with-perl' '--with-python' '--with-includes=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include /tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include/libxml2' '--with-libraries=/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib' '--with-openssl' '--with-pam' '--with-ldap' '--disable-rpath' 'LDFLAGS=-Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib' '--prefix=/usr/local/greenplum-db-devel' '--mandir=/usr/local/greenplum-db-devel/man' 'CC=gcc -m64' 'CFLAGS=-m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc -m64
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/include -I/usr/local/greenplum-db-6.15.0/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -m64 -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.15.0/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/../lib -L/tmp/build/f8c7ee08/gpdb_src/gpAux/ext/rhel7_x86_64/lib -Wl,--as-needed -L/usr/local/greenplum-db-6.15.0/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lyaml -lgssapi_krb5 -luv -lquicklz -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.15.0/lib
VERSION = PostgreSQL 9.4.24
### Actual behavior
query partitioned table with errors
### Step to reproduce the behavior
CREATE TABLE test.sal_goods_summ (
	oc varchar(15) NOT NULL,
	sd varchar(8) NOT NULL,
	t_id varchar(30) NOT NULL,
	s_id varchar(30) NOT NULL,
	bc varchar(32) NOT NULL,
	sn numeric(18) NULL
)
DISTRIBUTED BY (oc, sd, t_id, s_id, bc)
PARTITION BY RANGE(sd) 
          (
          PARTITION bef START ('0'::character varying(8)) END ('20210630'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210701 START ('20210701'::character varying(8)) END ('20210702'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210702 START ('20210702'::character varying(8)) END ('20210703'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210703 START ('20210703'::character varying(8)) END ('20210704'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210704 START ('20210704'::character varying(8)) END ('20210705'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210705 START ('20210705'::character varying(8)) END ('20210706'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210706 START ('20210706'::character varying(8)) END ('20210707'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210707 START ('20210707'::character varying(8)) END ('20210708'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210708 START ('20210708'::character varying(8)) END ('20210709'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210709 START ('20210709'::character varying(8)) END ('20210710'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210710 START ('20210710'::character varying(8)) END ('20210711'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210711 START ('20210711'::character varying(8)) END ('20210712'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210712 START ('20210712'::character varying(8)) END ('20210713'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210713 START ('20210713'::character varying(8)) END ('20210714'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210714 START ('20210714'::character varying(8)) END ('20210715'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210715 START ('20210715'::character varying(8)) END ('20210716'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210716 START ('20210716'::character varying(8)) END ('20210717'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210717 START ('20210717'::character varying(8)) END ('20210718'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210718 START ('20210718'::character varying(8)) END ('20210719'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210719 START ('20210719'::character varying(8)) END ('20210720'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210720 START ('20210720'::character varying(8)) END ('20210721'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210721 START ('20210721'::character varying(8)) END ('20210722'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210722 START ('20210722'::character varying(8)) END ('20210723'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210723 START ('20210723'::character varying(8)) END ('20210724'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210724 START ('20210724'::character varying(8)) END ('20210725'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210725 START ('20210725'::character varying(8)) END ('20210726'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210726 START ('20210726'::character varying(8)) END ('20210727'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210727 START ('20210727'::character varying(8)) END ('20210728'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210728 START ('20210728'::character varying(8)) END ('20210729'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210729 START ('20210729'::character varying(8)) END ('20210730'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210730 START ('20210730'::character varying(8)) END ('20210731'::character varying(8)) WITH (appendonly='false'), 
          PARTITION day20210731 START ('20210731'::character varying(8)) END ('20210801'::character varying(8)) WITH (appendonly='false'),
          DEFAULT PARTITION other
          );

execute:
         select * from   
         test.sal_goods_summ
         where sd between '20210710' and '20210719'

with log errors:
2021-03-16 09:31:38.662730 CST,"gpadmin","mrt_analysis_db",p31956,th-897820544,"XXX","65150",2021-03-16 08:58:53 CST,0,con427,cmd71,seg-1,,,,sx1,"LOG","00000","2021-03-16 09:31:38:662305 CST,THD000,ERROR,""Lookup of object 0.0.0.0 in cache failed"",
2021-03-16 09:31:38:662540 CST,THD000,ERROR,""Lookup of object 0.0.0.0 in cache failed"",
",,,,,,"         select * from   
         test.sal_goods_summ
         where sd between '20210710' and '20210719'",0,,"COptTasks.cpp",271,
2021-03-16 09:31:38.690598 CST,"gpadmin","mrt_analysis_db",p31956,th-897820544,"XXX","65150",2021-03-16 08:58:53 CST,0,con427,cmd72,seg-1,,dx30,,sx1,"LOG","00000","execute <unnamed>:          select * from   
         test.sal_goods_summ
         where sd between '20210710' and '20210719'",,,,,,"         select * from   
         test.sal_goods_summ
         where sd between '20210710' and '20210719'",0,,"postgres.c",2725,

**Comment by zellerh** [comment] 2021-03-24 01:15
Thanks you, @WholeWorld-Timothy, for submitting this issue! I was able to reproduce it and hope to have a PR with a fix in a few days.

In case you are interested in the details: What happens is that we come across a BCC (Binary Coercible Cast, an example is a cast from varchar to text) and try to look up the cast function for it to do a check. The problem is that a BCC doesn't have a cast function, since it is basically a no-op. So, the fix is simple, just ensure the check passes for BCCs without doing the lookup.

**Comment by zellerh** [comment] 2021-04-05 23:52
Fix was merged into 6X_STABLE, hope that fixes the issue. Thank you again for reporting it! See also https://github.com/greenplum-db/gpdb/pull/11705, which contains a fix for 7X, just in case the code will be used there (so far it isn't).

**Closed by zellerh** 2021-04-05 23:52 UTC
Labels: area: gporca

**Comment by WholeWorld-Timothy** [comment] 2021-04-06 01:37
Thanks for being able to position and solve problems so quickly, expect to use them in new versions and solve current problems。
