### ISSUE TITLE
GUC passed to QE unexpectedly when process started

### ISSUE THREAD

**Issue by Dontpushme** [greenplum-db/gpdb#9429] opened 2020-01-15 08:05 UTC
### Greenplum version or build
master branch latest [commit](https://github.com/greenplum-db/gpdb/commit/a5fb66d318e4b7b80a5fbada3afe5fbb4a37f330)
### OS version and uname -a
centos7
### Expected behavior
Table created successfully.
### Actual behavior

```
postgres=# create table ccdd1 (a, b) as (select 1, 1 union select 1, 1 union select 1, 1);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named '?column?' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  no pre-assigned OID for relation "ccdd1" (oid_dispatch.c:720)  (seg1 192.168.10.200:6001 pid=25380) (oid_dispatch.c:720)
```
### Step to reproduce the behavior

```
create schema qp_misc_rio;
--use '\c' to destroy gang created by last command
\c
set search_path to qp_misc_rio;
reset all;
create table ccdd1 (a, b) as (select 1, 1 union select 1, 1 union select 1, 1);
```
### Preliminary findings
psql create QD backend only. And "set search_path to qp_misc_rio;" is dispatched to QE, but guc string "search_path=qp_misc_rio" included when create gang, it will set guc_varialble->reset_val to "qp_misc_rio" when InitPostgres and future "reset all" command will be no effect on QEs, their search_path are still "qp_misc_rio".

**Comment by hlinnaka** [comment] 2020-01-15 08:12
Works for me:
```
postgres=# create schema qp_misc_rio;
CREATE SCHEMA
postgres=# set search_path to qp_misc_rio;
SET
postgres=# reset all;
RESET
postgres=# create table ccdd1 (a, b) as (select 1, 1 union select 1, 1 union select 1, 1);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named '?column?' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
SELECT 1
```

**Comment by Dontpushme** [comment] 2020-01-15 08:23
> Works for me:
> 
> ```
> postgres=# create schema qp_misc_rio;
> CREATE SCHEMA
> postgres=# set search_path to qp_misc_rio;
> SET
> postgres=# reset all;
> RESET
> postgres=# create table ccdd1 (a, b) as (select 1, 1 union select 1, 1 union select 1, 1);
> NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named '?column?' as the Greenplum Database data distribution key for this table.
> HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
> SELECT 1
> ```

My apologys, after "create schema qp_misc_rio;" you need to add a '\c'

**Comment by hlinnaka** [comment] 2020-01-15 08:35
Ah, got it. I can reproduce it now, too.

I think this is the same issue as https://github.com/greenplum-db/gpdb/issues/685. Your repro is simpler, though.

**Comment by kainwen** [comment] 2021-02-20 11:21
It seems the master branch does not have the issue. 6X still has the issue.

**Comment by gfphoenix78** [comment] 2021-08-24 05:38
Fixed in https://github.com/greenplum-db/gpdb/pull/12441 and https://github.com/greenplum-db/gpdb/pull/12480

**Closed by gfphoenix78** 2021-08-24 05:38 UTC
