### ISSUE TITLE
sql with group by/group by grouping sets and grouping throw exception

### ISSUE THREAD

**Issue by ryonchen** [greenplum-db/gpdb#12532] opened 2021-09-02 10:28 UTC
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 10 2021 22:30:36
### OS version and uname -a
Centos

### Expected behavior
SQL can execute normally with group by/group by grouping sets and grouping

### Actual behavior
```
WITH temp_chuda
     AS (SELECT uv.user_id,
                'a' 期次
         FROM   test.t1 uv
                LEFT JOIN test.t2 ta
                       ON uv.oper_id = ta.admin_id
                          AND ta.end_time = '9999-12-31'
         WHERE  ( uv.content LIKE '%1%'
                   OR uv.content LIKE '%2%'
                   OR uv.content LIKE '%3%'
                   OR uv.content LIKE '%4%'
                   OR uv.content LIKE '%5%' ))
SELECT "活动名称",
       "期次",
       Grouping("活动名称") AS "_grouping_活动名称",
       Grouping("期次")       AS "_grouping_期次",
       Grouping("活动名称")
       + Grouping("期次")     AS "_grouping_all",
       Sum("账户id")          AS "sum(账户id)"
FROM   (SELECT '四课时兑换' 活动名称,
               a.期次,
               1                 AS "账户id"
        FROM   (SELECT a.*,
                       CASE
                         WHEN b.user_id IS NOT NULL THEN '是'
                         ELSE '否'
                       END is_on_list,
                       CASE
                         WHEN c.user_id IS NOT NULL THEN '是'
                         ELSE '否'
                       END "is_on_list2"
                FROM   temp_chuda a
                       LEFT JOIN test.t3 b
                              ON a.user_id = b.user_id
                       LEFT JOIN test.t4 c
                              ON a.user_id = c.user_id
                                 AND c.type = '6万8名单')a) t
GROUP  BY t."活动名称",
          t."期次";
```

When I execute this SQL, it throws an exception: `ERROR:  column "t"."活动名称" is not in GROUP BY. But the sql already group by  活动名称.`
After my test, it works normally when I remove function `grouping(grouping("活动名称") AS "_grouping_活动名称",grouping("期次") AS "_grouping_期次"     ,grouping("活动名称")+grouping("期次") AS "_grouping_all"   ,   )`.
When I change `group by` to `group by grouping sets ((t."活动名称", t."期次"))`, it throws an exception: `ERROR:  could not identify an ordering operator for type unknown.HINT:  Use an explicit ordering operator or modify the query.`

Why?

**Comment by kainwen** [comment] 2021-09-26 00:59
Would you please offer the full reproduce script so that it is easy for others to debug? 

At least, it needs the table definition to run the query locally.

@ryonchen

**Comment by adam8157** [comment] 2021-10-12 06:51
`unknown` identifies a not-yet-resolved type, e.g., of an undecorated string literal. https://www.postgresql.org/docs/10/datatype-pseudo.html, it has no ordering operator, I would suggest you cast `unknown` type strings to `text`.

The reason for different behaviors of `GROUP BY` and `GROUPING SETS`, I guess, is because the planner chose different aggregate methods, hash and sort, the sort method needs the ordering operator.

**Comment by lij55** [comment] 2022-08-16 09:35
Hi @ryonchen , 可以把表结构也贴一下吗？最好也带上explain的结果，谢谢。

**Comment by dpandhi-git** [comment] 2022-11-20 02:09
Closing as no further information provided

**Closed by dpandhi-git** 2022-11-20 02:09 UTC
Labels: needs: more information
