### ISSUE TITLE
Scan all partition when I limit the range of partition column value.

### ISSUE THREAD

**Issue by Yato-song** [greenplum-db/gpdb#15341] opened 2023-04-06 12:20 UTC
I meet a strange problom when I use GP. I have a table with 85 partiotions. This table is partitioned by a date-type column and each partition corresponds to a month. when I run the plan of following sql, I find that GP scan all partiotion of this table, but the dates in my 'where' just contain 13 partitions. And when I reduce the number of date in 'where', the partition scaned return to 13.
sql:
```
explain analyze
select count(1)
from
edw_dws.dws_loan_duebill_detail
where dt in ('2023-01-07','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15','2023-01-15','2022-01-28','2022-02-19','2022-03-19','2022-04-19','2022-05-19','2022-06-19','2022-07-19','2022-08-22','2022-09-19','2022-10-19','2022-11-19','2022-12-04','2023-01-15'
);
```

explain
```
Aggregate  (cost=0.00..115287.54 rows=1 width=8) (actual time=65719.001..65719.001 rows=1 loops=1)
   ->  Gather Motion 420:1  (slice1; segments: 420)  (cost=0.00..115287.54 rows=1 width=8) (actual time=62525.322..65718.765 rows=420 loops=1)
         ->  Aggregate  (cost=0.00..115287.54 rows=1 width=8) (actual time=63858.446..63858.446 rows=1 loops=1)
               ->  Sequence  (cost=0.00..115287.54 rows=2892336 width=4) (actual time=606.336..63856.157 rows=6940419 loops=1)
                     ->  Partition Selector for dws_loan_duebill_detail (dynamic scan id: 1)  (cost=10.00..100.00 rows=1 width=4) (never executed)
                           Partitions selected: 85 (out of 85)
                     ->  Dynamic Seq Scan on dws_loan_duebill_detail (dynamic scan id: 1)  (cost=0.00..115287.54 rows=2892336 width=4) (actual time=606.317..63407.038 rows=6940419 loops=1)
                           Filter: (dt = ANY ('{2023-01-07,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-
28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-1
9,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15
,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,
2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2
023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,20
22-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,2022-12-04,2023-01-15,2022-01-28,2022-02-19,2022-03-19,2022-04-19,2022-05-19,2022-06-19,2022-07-19,2022-08-22,2022-09-19,2022-10-19,2022-11-19,202
2-12-04,2023-01-15}'::date[]))
                           Partitions scanned:  Avg 85.0 (out of 85) x 420 workers.  Max 85 parts (seg0).
 Planning time: 41.606 ms
   (slice0)    Executor memory: 203K bytes.
   (slice1)    Executor memory: 20398K bytes avg x 420 workers, 20409K bytes max (seg350).
 Memory used:  57344kB
 Optimizer: Pivotal Optimizer (GPORCA)
 Execution time: 65802.603 ms
(15 rows)
```

All dates are in the range of 2022-01 to 2023-01

**Comment by kainwen** [comment] 2023-04-06 13:17
There is a GUC to control this.

`optimizer_array_expansion_threshold`. The default value is `100` and in your case above you have 139 elements.

Please refer to doc  https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-config_params-guc-list.html#optimizer_array_expansion_threshold

and try:

```sql
show optimizer_array_expansion_threshold;
set optimizer_array_expansion_threshold = 200;
-- run you SQL explain analyze....
```

I think this issue can be closed and it is not a bug. Close it. Feel free to discuss here if you have more questions.

**Closed by kainwen** 2023-04-06 13:17 UTC
Labels: type: bug

**Comment by Yato-song** [comment] 2023-04-07 01:56
> There is a GUC to control this.
> 
> `optimizer_array_expansion_threshold`. The default value is `100` and in your case above you have 139 elements.
> 
> Please refer to doc https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-config_params-guc-list.html#optimizer_array_expansion_threshold
> 
> and try:
> 
> ```sql
> show optimizer_array_expansion_threshold;
> set optimizer_array_expansion_threshold = 200;
> -- run you SQL explain analyze....
> ```
> 
> I think this issue can be closed and it is not a bug. Close it. Feel free to discuss here if you have more questions.

thanks!!
