### ISSUE TITLE
Canceling query because of high VMEM usage 

### ISSUE THREAD

**Issue by cartooku** [greenplum-db/gpdb#10165] opened 2020-05-21 15:38 UTC
I have a small Greenplum cluster in which some queries abort.

System related information:

Greenplum Version: 6.3
Master Host: 1
Segment Host: 2
RAM per Segmenthost: 32GB
SWAP per Segmenthost: 32GB
TOTAL segment: 8 Primary + 0 mirror
segment per host: 4

vm_overcommmit_ratio: 95
gp_vmem_protect_limit: 8072MB
statement_mem: 250MB
The queries are executed with a none superuser.

Symptom:

The query failed with the following error massage:

Canceling query because of high VMEM usage. Used: 7245MB, available 801MB, red zone: 7264MB (runaway_cleaner.c:189) 
What we tried:

We calculate the Greenplum Parameter with this information: https://gpdb.docs.pivotal.io/6-3/best_practices/sysconfig.html

This help us for some "simple" queries but for more complicated ones the error happend again.

In the next Step we configured the max_statement_mem: 2000MB

This didn't have any effect to the memory consumption on the segmenthosts. We track this with following Query:

select segid, sum (vmem_mb) from session_state.session_level_memory_consumption
where query like '%<some snippet of the query>%'
group by segid
order by segid;
The memory consumption increases very quickly and the error happend again.

We tried to restrict the memory consumption by setting the following resource queue for the user:
CREATE RESOURCE QUEUE adhoc with (ACTIVE_STATEMENTS=6, MEMORY_LIMIT=6291);
ALTER ROLE user1 RESOURCE QUEUE adhoc;
The Database is set to use the resource queue with the parameter gp_resource_manager: queue

We see in the Table 'gp_toolkit.gp_resqueue_status' when we execute a statement that the 'rsqmemoryvalue' is 1048 but the memory consumption in the session_state.session_level_memory_consumption table shows higher values for the segments until the error occurs again.

Has anyone a tip to fix this problem?

**Comment by gaos1** [comment] 2020-05-22 03:27
max_statement_mem is just used to limit the max value that you can set to statement_mem. if you want to strict limit group memory usage, you can enable resource group. 

it seems your query is indeed using a lot of memory. with resource group, if you still hit the similar error, it will print memory usage in details in logs, and please paste them and also your query (with explain output, and table schema) for further analysis.

**Comment by cartooku** [comment] 2020-05-23 13:56
The SQL text  like this :
select count(*) as num
   from PA_KC24 kc24 join PA_KC22 kc22
     on kc22.aaa027= kc24.aaa027
	 and kc22.aaz217 =kc24.aaz217
	 and kc22.aaz216 = kc24.aaz216
	 where kc24.aka130='101'
	 and kc24.removed='0' and kc24.paz002 is not null
	 and kc24.date_updated >='2020-05-19 12:06:15'::timestamp
	 and kc24.date_updated <='2020-05-19 12:10:15'::timestamp

Before I  using "analyze pa_kc24" and "analyze pa_kc22"， The query is indeed using a lot of memory , I strict it wih resource group,But it still hit the similar error. the explain shows the GP choosed the "nested  loop"(I cannot paste them , because I didn't record the bad explain) 


 After collecting statistics by "analyze pa_kc24" and "analyze pa_kc22"  command, the execution plan shows the GP choosed  the "hash join", and then the query becomes very fast。

My problem have been fixed .But I   still have some questiones: 
If "nested loop" is selected in the execution plan, the memory usage of SQL will not be limited by  resource queue or the statement_mem  in GP?

**Comment by ashwinstar** [comment] 2022-03-10 22:50
> If "nested loop" is selected in the execution plan, the memory usage of SQL will not be limited by resource queue or the statement_mem in GP?

Resource queue or group should limit the memory usage for the query. There are currently open PRs to fix a issue for resource group. Given the problem is resolved, closing this issue.

**Closed by ashwinstar** 2022-03-10 22:50 UTC
