### ISSUE TITLE
ERROR:  XX000: could not find hash function for hash operator 1070 (nodeHash.c:374)

### ISSUE THREAD

**Issue by nurikk** [greenplum-db/gpdb#471] opened 2016-03-04 09:31 UTC
Hi all! I have trouble with GP db. I have this db schema
https://gist.github.com/nurikk/e81554f07b5840989918#file-shema-sql

When performing this 
https://gist.github.com/nurikk/e81554f07b5840989918#file-query-sql

I have error
`ERROR:  XX000: could not find hash function for hash operator 1070 (nodeHash.c:374)  (seg1 slice7 gp-node-1.int.avs.io:40001 pid=29672) (cdbdisp.c:1324)
LOCATION:  cdbdisp_finishCommand, cdbdisp.c:1324`
If remove 
`count(distinct(s.yasen_uuid)) as searches_count,`

everything works good

Db version:
PostgreSQL 8.3devel (Greenplum Database 4.3.99.00 build dev) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3) compiled on Mar  3 2016 20:22:53

**Comment by nurikk** [comment] 2016-03-04 13:06
It seems an error occurs only in small amounts of data. I make a request for 76M rows and everything is working, 7M rows got on an error

**Comment by nurikk** [comment] 2016-03-04 16:09
I localized the problem, it occurs when the array grouping performs
```sql
create table a (
  id integer,
  a CHAR(3)[]
) DISTRIBUTED by(id);

create table b (
  id integer
) DISTRIBUTED by(id);

select a,
count(distinct(a.id)),
count(distinct(b.id))
from a
left outer join b
on a.id = b.id
group by 1;
--ERROR:  could not find hash function for hash operator 1070 (nodeHash.c:374)  (seg1 slice5 gpdbvagrant.pivotal.io:40001 pid=21220) (cdbdisp.c:1324)

--group by string
select a[1],
count(distinct(a.id)),
count(distinct(b.id))
from a
left outer join b
on a.id = b.id
group by 1;
-- a | count | count 
-----+-------+-------
--(0 rows)
```

**Comment by BaiShaoqi** [comment] 2019-01-08 07:03
@nurikk@melanieplageman and I have tried to reproduce this issue on the latest Greenplum master and were unable to reproduce it. Are you still running into this error?
Orca does not support multiple distinct qualified aggregates in a query, so this error would have had to come from planner. We did not insert data, however.
Do you have a more recent repro? This may have been fixed in the time between when this issue was filed and now.
@Eulerizeit

**Comment by Eulerizeit** [comment] 2019-02-07 23:13
I'm going to close this given our inability to reproduce. If you continue to have this issue please reopen.

**Closed by Eulerizeit** 2019-02-07 23:13 UTC
Labels: GPORCA, Planner
