### ISSUE TITLE
"CREATE TABLE AS" generate "ERROR:  duplicate DISTRIBUTED BY column 'id'."

### ISSUE THREAD

**Issue by yew011** [greenplum-db/gpdb#10895] opened 2020-09-24 03:37 UTC
### Greenplum version or build

**5.28.1**

### OS version and uname -a

**CentOS Linux release 7.7.1908 (Core)**

### Expected behavior

The following command correctly create the final table
```
create table test_base (id uuid, ip inet, tsa timestamptz, tsb timestamptz, atype integer, btype integer) distributed by (id);
create table test_00 as select * from test_base DISTRIBUTED BY (atype, btype);
create table test_01 (ts timestamptz, a uuid, b uuid) distributed by (a, b);
create table test_final as
    with test_x as (
        select a from test_01 where a = b
    )
    select distinct id
    from test_00
    left join test_x on id = test_x.a;
```

### Actual behavior

```
=# create table test_final as
-#     with test_x as (
(#         select a from test_01 where a = b
(#     )
-#     select distinct id
-#     from test_00
-#     left join test_x on id = test_x.a;
ERROR:  duplicate DISTRIBUTED BY column 'id'
```

### Step to reproduce the behavior

```
create table test_base (id uuid, ip inet, tsa timestamptz, tsb timestamptz, atype integer, btype integer) distributed by (id);
create table test_00 as select * from test_base DISTRIBUTED BY (atype, btype);
create table test_01 (ts timestamptz, a uuid, b uuid) distributed by (a, b);
create table test_final as
    with test_x as (
        select a from test_01 where a = b
    )
    select distinct id
    from test_00
    left join test_x on id = test_x.a;

```

**Comment by kainwen** [comment] 2020-09-24 03:49
Tested, it still exists in master branch.

**Comment by kainwen** [comment] 2021-05-17 07:49
The root cause is planner generate a plan:

```sql
gpadmin=# explain
    with test_x as (
        select a from test_01 where a = b
    )
    select distinct id
    from test_00
    left join test_x on id = test_x.a;
                                                QUERY PLAN
-----------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=2.21..2.22 rows=1 width=16)
   ->  HashAggregate  (cost=2.21..2.22 rows=1 width=16)
         Group Key: test_00.id
         ->  Hash Right Join  (cost=1.03..2.20 rows=2 width=16)
               Hash Cond: (test_01.a = test_00.id)
               ->  Seq Scan on test_01  (cost=0.00..683.75 rows=16 width=16)
                     Filter: (a = b)
               ->  Hash  (cost=1.02..1.02 rows=1 width=16)
                     ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..1.02 rows=1 width=16)
                           Hash Key: test_00.id, test_00.id
                           ->  Seq Scan on test_00  (cost=0.00..1.00 rows=1 width=16)
 Optimizer: Postgres query optimizer
```

looking the the bottom `redist motion`'s dist key: `test_00.id, test_00.id`, it should be `test_01.a` and `test_01.b`, with `a=b` it deduce such distkey.

So the final plan's flow contains two duplicated exprs, but it is not allowed to have duplicated keys in distkeys.

I think a simple fix should be checking this case, and if so, just return a null policy.

**Comment by dpandhi-git** [comment] 2022-12-22 23:38
closing as its working on latest 6x & 7x

**Closed by dpandhi-git** 2022-12-22 23:38 UTC
Labels: type: bug, topic: planner, version: 6X_STABLE
