### ISSUE TITLE
7X: Executor PANIC for EXISTS query

### ISSUE THREAD

**Issue by ashwinstar** [greenplum-db/gpdb#16268] opened 2023-08-22 17:14 UTC
### Greenplum version or build
7X BETA.5 build

### Expected behavior
6X_STABLE gives this output

```sql
postgres=# explain select (select exists (select from pg_views where schemaname = a)) from foo;
                                           QUERY PLAN                                           
------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..89451.14 rows=52800 width=32)
   ->  Seq Scan on foo  (cost=0.00..89451.14 rows=17600 width=32)
         SubPlan 2  (slice1; segments: 1)
           ->  Result  (cost=1.67..1.68 rows=1 width=0)
                 InitPlan 1 (returns $1)  (slice2)
                   ->  Hash Join  (cost=1.12..917.50 rows=1652 width=0)
                         Hash Cond: (c.relnamespace = n.oid)
                         ->  Seq Scan on pg_class c  (cost=0.00..856.50 rows=11564 width=4)
                               Filter: (relkind = 'v'::"char")
                         ->  Hash  (cost=1.10..1.10 rows=1 width=4)
                               ->  Seq Scan on pg_namespace n  (cost=0.00..1.10 rows=1 width=4)
                                     Filter: (nspname = (foo.a)::name)

postgres=# select (select exists (select from pg_views where schemaname = a)) from foo;
 exists 
--------
(0 rows)
```

### Actual behavior
PANIC

### Step to reproduce the behavior
```sql
create table tmp (a varchar, b varchar, c varchar);
select (SELECT EXISTS
                 (SELECT
                  FROM pg_views
                  WHERE schemaname = a)) from tmp;
```

**Comment by kainwen** [comment] 2023-08-22 23:20
Root cause is as below.

InitPlan should never refer to params from main plan:

```
InitPlan 1 (returns $1)  (slice2)
                   ->  Hash Join  (cost=1.12..917.50 rows=1652 width=0)
                         Hash Cond: (c.relnamespace = n.oid)
                         ->  Seq Scan on pg_class c  (cost=0.00..856.50 rows=11564 width=4)
                               Filter: (relkind = 'v'::"char")
                         ->  Hash  (cost=1.10..1.10 rows=1 width=4)
                               ->  Seq Scan on pg_namespace n  (cost=0.00..1.10 rows=1 width=4)
                                     Filter: (nspname = (foo.a)::name)
```

The filter `Filter: (nspname = (foo.a)::name)` is refering outside vars, but this is InitPlan. In Greenplum InitPlan will dispatch firstly and then the main plan.

**Comment by hyongtao-db** [comment] 2023-08-23 14:00
This bug is strong related with function `isParamExecutableNow()`.

**Comment by kainwen** [comment] 2023-08-23 14:27
Postgres SubPlan does not have the field `extParam`:

```c
    bool        parallel_safe;  /* is the subplan parallel-safe? */
    /* Note: parallel_safe does not consider contents of testexpr or args */
    /* Information for passing params into and out of the subselect: */
    /* setParam and parParam are lists of integers (param IDs) */
    List       *setParam;       /* initplan and MULTIEXPR subqueries have to
                                 * set these Params for parent plan */
    List       *parParam;       /* indices of input Params from parent plan */
    List       *args;           /* exprs to pass as parParam values */
    /* Estimated execution costs: */
    Cost        startup_cost;   /* one-time setup cost */
    Cost        per_call_cost;  /* cost for each subplan evaluation */
    /* Copied from original SubLink, but placed at end for ABI stability */
    int         subLinkId;      /* ID (1..n); 0 if not MULTIEXPR */
} SubPlan;
```

But Greenplum has the field `extParam`, and need this field.

```c
    /* Information for passing params into and out of the subselect: */
    /* setParam and parParam are lists of integers (param IDs) */
    List       *setParam;       /* initplan subqueries have to set these
                                 * Params for parent plan */
    List       *parParam;       /* indices of input Params from parent plan */
    List       *args;           /* exprs to pass as parParam values */
    List       *extParam;       /* indices of input Params from ancestor plan */
    /* Estimated execution costs: */
    Cost        startup_cost;   /* one-time setup cost */
    Cost        per_call_cost;  /* cost for each subplan evaluation */
} SubPlan;
```

It means that current Greenplum main branch (kernel 12) will use Postgres's main routines to generate SubPlan (or InitPlan) so that no logical thus not set the field during make_subplan.

This is because later version of Postgres change the API of `subquery_planner`.

A simple patch can fix the issue:

```diff
diff --git a/src/backend/optimizer/plan/subselect.c b/src/backend/optimizer/plan/subselect.c
index c7f2a5dd5c2..2758e2e65fd 100644
--- a/src/backend/optimizer/plan/subselect.c
+++ b/src/backend/optimizer/plan/subselect.c
@@ -533,6 +533,8 @@ build_subplan(PlannerInfo *root, Plan *plan, PlannerInfo *subroot,
        Bitmapset  *plan_param_set;
        int         paramid;

+       SS_finalize_plan(subroot, plan);
+
        /*
         * Initialize the SubPlan node.  Note plan_id, plan_name, and cost fields
         * are set further down.
```

**Comment by hyongtao-db** [comment] 2023-08-23 14:38
@kainwen Oh, your solution and explanation are so cool. Thank you.

**Comment by charliettxx** [comment] 2023-08-24 07:40
I suppose It's better to handle with `subplan->extParam` in function `SS_finalize_plan` after all plans done(in standard_panner). But it's a  bit tricky and I didn't find a proper approach did such things above. BTW......
Do you have a PR to fix this issue already?

**Comment by charliettxx** [comment] 2023-08-24 12:56
I suppose another approach for this issue, please feel free to review it. I'm not it's workable or not and still working on pipeline failure. @kainwen @hyongtao-db https://github.com/greenplum-db/gpdb/pull/16288

**Comment by kainwen** [comment] 2023-11-16 12:50
Fixed by https://github.com/greenplum-db/gpdb/pull/16288

**Closed by kainwen** 2023-11-16 12:50 UTC
Labels: type: bug, topic: planner, version: 7X_ALPHA, Priority 1, 7X_beta_testing, 7X_only
