### ISSUE TITLE
An  I/O error  when send to backend

### ISSUE THREAD

**Issue by wangbinhe3db** [greenplum-db/gpdb#11685] opened 2021-03-22 09:30 UTC
### Greenplum version or build
gp5.28.4
### OS version and uname -a
redhat 7.6
### Actual behavior
![image](https://user-images.githubusercontent.com/78577992/111968526-33e2e480-8b34-11eb-8a12-56e76cbd0f79.png)
jdbc  report  the error

**Comment by zhangh43** [comment] 2021-03-25 06:39
Do you have the reproduce step? which JDBC driver you are using ?

**Comment by wangbinhe3db** [comment] 2021-03-26 07:32
the log of master  at the time is 
database process Segmentation fault :
,"server process (PID 58151) was terminated by signal 11: Segmentation fault",,,,,,,0,,"postmaster.c",5620,
,"terminating any other active server processes",,,,,,,0,,"postmaster.c",5299,
,"sweeper process (PID 49654) exited with exit code 2",,,,,,,0,,"postmaster.c",5600,
,"seqserver process (PID 49652) exited with exit code 2",,,,,,,0,,"postmaster.c",5600,
,"ftsprobe process (PID 49653) exited with exit code 2",,,,,,,0,,"postmaster.c",5600,
,"BeginResetOfPostmasterAfterChildrenAreShutDown: counter 188",,,,,,,0,,"postmaster.c",2162,
,"gp_session_id high-water mark is 383154",,,,,,,0,,"postmaster.c",2188,
,"resetting shared memory",,,,,,,0,,"postmaster.c",3980,
,"temporary files using default filespace",,,,,,,0,,"primary_mirror_mode.c",2582,
,"transaction files using default pg_system filespace",,,,,,,0,,"primary_mirror_mode.c",2650,
,"PrimaryMirrorMode: Processing postmaster reset with recent mode of 1",,,,,,,0,,"primary_mirror_mode.c",1134,
,"PrimaryMirrorMode: Processing postmaster reset to non-fault state",,,,,
![image](https://user-images.githubusercontent.com/78577992/112597673-64829100-8e48-11eb-9057-089ca17f97f3.png)

@zhangh43

**Comment by wangbinhe3db** [comment] 2021-03-26 07:38
As  i see a error log  ,
""GPDB Expression type: {PARAM :paramkind 0 :paramid 1 :paramtype 1043 :paramtypmod -1} not supported in DXL"",",,,,,"SQL statement ""UPDATE MD_P。。。。
 END_TIME = now(), ERROR_MSG = '存储过程成功完成' WHERE TRIM(UPPER(PROCESS_NAME)) = TRIM(UPPER( $1 )) AND STAT_DATE =  $2  AND PARTION_ID =  $3 ""
PL/pgSQL function ""sp_status"" line 59 at SQL statement line 59 at SQL statement
SQL statement  SELECT  sp_status（） $1 , $2 ,'0', $3  ,0)""

i  see  Stored Procedures  ,  whether  is affected by the  Stored Procedures

**Comment by zhangh43** [comment] 2021-03-30 02:05
"GPDB Expression type:....not supported in DXL" is an ORCA message. It's OK and can fall back to planner.
It's hard to have any useful suggestion for you. Could you supply the gpdb version, reproduce step as described in the issue template?

**Comment by asimrp** [comment] 2021-04-22 02:47
> server process (PID 58151) was terminated by signal 11: Segmentation fault

That crash should have created a core file.  Do you see a core file for PID 58151?  If so, can you share the back trace @wangbinhe3db ?

**Comment by adam8157** [comment] 2021-12-14 06:33
Closing because of no information, feel free to reopen with more details.

**Closed by adam8157** 2021-12-14 06:33 UTC
Labels: version: 5X_STABLE, needs: more information
