### ISSUE TITLE
inconsistent serial column value on replicated table after insert as select

### ISSUE THREAD

**Issue by m7onov** [greenplum-db/gpdb#9737] opened 2020-03-13 06:23 UTC
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.4.0 build commit:564b89a8c6bef5e329a59f39dac438b13d9cb3fa) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Feb 12 2020 00:38:58

### OS version and uname -a
centos-release-7-6.1810.2.el7.centos.x86_64
Linux dwh-3 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.4.0/bin
DOCDIR = /usr/local/greenplum-db-6.4.0/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.4.0/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.4.0/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.4.0/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.4.0/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.4.0/lib
PKGLIBDIR = /usr/local/greenplum-db-6.4.0/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.4.0/share/locale
MANDIR = /usr/local/greenplum-db-6.4.0/man
SHAREDIR = /usr/local/greenplum-db-6.4.0/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.4.0/etc/postgresql
PGXS = /usr/local/greenplum-db-6.4.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--prefix=/usr/local/greenplum-db-oss' '--mandir=/usr/local/greenplum-db-oss/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.4.0/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.4.0/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-oss/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.4.0/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.4.0/lib
VERSION = PostgreSQL 9.4.24

### Expected behavior
serial column value in replicated table is consistent in all segments

### Actual behavior
serial column values differ on all segments in gp cluster

### Step to reproduce the behavior
```
-- this is the table where we will insert data
create table test_table1 (a serial, b integer) distributed replicated;
-- this is source of data; distribution policy doesn't matter here
create table test_table2 (b integer) distributed by (b);

insert into test_table2(b) values (1);
insert into test_table1(b) select * from test_table2;

-- function for figuring out serial column values on segments
create or replace
function test_function() returns setof test_table1
as $$
begin
  return query
    select *
      from test_table1;
end;
$$ language plpgsql execute on all segments;

select * from test_function() t order by t.b;

/*
inconsistent serial column "a" on all 8 segments in gp cluster
?????????
┌────┬───┐
│ a  │ b │
├────┼───┤
│  6 │ 1 │
│  5 │ 1 │
│  1 │ 1 │
│  7 │ 1 │
│  2 │ 1 │
│  8 │ 1 │
│  3 │ 1 │
│  4 │ 1 │
└────┴───┘
(24 rows)
*/
```

**Comment by pengzhout** [comment] 2020-03-13 06:54
Hmm, that is indeed a problem, we didn't consider such cases, thanks for your reporting.

**Comment by asimrp** [comment] 2020-03-13 13:53
For replicated tables, we need to find a way to avoid every segment calling `nextval()`.  Instead, get the next sequence value once on QD and broadcast the same value to all QEs.

**Comment by asimrp** [comment] 2020-03-19 11:48
The plan clearly indicates that `nextval()` is executed on each segment for every tuple that's inserted in the replicated table.  That's what is causing wrong results here.
```SQL
explain (verbose, costs off) insert into test_table1 (b) select b from test_table2;
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Insert on public.test_table1
   ->  Result
         Output: int4(nextval('test_table1_a_seq'::regclass)), test_table2.b
         ->  Broadcast Motion 3:3  (slice1; segments: 3)
               Output: test_table2.b
               ->  Seq Scan on public.test_table2
                     Output: test_table2.b
```
In comparison, if `VALUES` clause is used, the data inserted is correct and the plan looks like this:
```SQL
explain (verbose, costs off) insert into test_table1 (b) values (1), (2), (3);
                                          QUERY PLAN
-----------------------------------------------------------------------------------------------
 Insert on public.test_table1
   ->  Result
         Output: (int4(nextval('test_table1_a_seq'::regclass))), "Values".column1, (0)
         ->  Broadcast Motion 1:3  (slice1)
               Output: "Values".column1, (int4(nextval('test_table1_a_seq'::regclass))), (0)
               ->  Values Scan on "Values"
                     Output: "Values".column1, int4(nextval('test_table1_a_seq'::regclass)), 0
```
Note the 1:3 broadcast motion, causing `nextval()` to be executed in the entry-db slice, once per tuple.

**Comment by asimrp** [comment] 2020-03-19 11:50
We need something similar for insert-into-select case.  I'm a beginner in the area of plan nodes but I think if we need to generate a plan like the following to solve this problem:
```SQL
explain (verbose, costs off) insert into test_table1 (b) select b from test_table2;
                                 QUERY PLAN
-----------------------------------------------------------------------------
 Insert on public.test_table1
   ->  Result
         Output: int4(nextval('test_table1_a_seq'::regclass)), test_table2.b
         ->  Broadcast Motion 3:3  (slice1; segments: 3)
               Output: test_table2.b
               ->  Result (is that the right node???)
                     Output: test_table2.b, int4(nextval('test_table1_a_seq'::regclass))
                     ->  Seq Scan on public.test_table2
                           Output: test_table2.b
                     ->  Broadcast Motion 1:3 (slice2)  -- this is additional entry-db slice
                           Output: int4(nextval('test_table1_a_seq'::regclass))
                           ->  FuncScan
                                 Output: int4(nextval('test_table1_a_seq'::regclass))
```
The objective is to execute `nextval()` only in the entry-db, once per tuple, similar to the `VALUES()` case.

**Comment by d** [comment] 2020-03-19 15:52
> but I think if we need to generate a plan like the following to solve this problem:

Wait, that plan makes no sense... Did you mean to just execute the `nextval` right at the `Seq Scan`? Because I think that's gonna be the solution: once we've moved above a broadcast motion, don't do anything that dilutes the relation's "replicatedness" (projecting a volatile function clearly diverges an already-replicated relation into something not)

**Comment by asimrp** [comment] 2020-03-20 04:39
That's utterly true! @d, your suggestion to invoke nextval() at SeqScan makes total sense.  It seems to be a matter of constructing ProjectionInfo having the right targetlist such that nextval() is evaluated during SeqScan.  Let me figure that out, thanks again!

**Comment by kainwen** [comment] 2020-03-20 07:56
In my mind, at the last step (where we add the broadcast motion),
we should take a look at the result relation, if it meets some condition (
replicated table and has serial column in this issue), let's do more work.

For this issue, at the place of the above:
1. create a gather motion to singleQE
2. create a projection path that involves next_val
3. create a broadcast motion

**Comment by asimrp** [comment] 2020-03-20 13:10
@d, @kainwen the exact same plan as per your suggestion is already generated by planner:
```SQL
explain (verbose, costs off) insert into test_table1 (b) select * from test_table2;
                                       QUERY PLAN
-----------------------------------------------------------------------------------------
 Insert on public.test_table1
   ->  Broadcast Motion 3:3  (slice1; segments: 3)
         Output: ((nextval('test_table1_a_seq'::regclass))::integer), test_table2.b, (0)
         ->  Seq Scan on public.test_table2
	       Output: nextval('test_table1_a_seq'::regclass), test_table2.b, 0
 Optimizer: Postgres query optimizer
 Settings: optimizer=off
```
The problem is with the plan generated by Orca.

@m7onov as a temporary workaround, `set optimizer = off` before running the replicated table insert command will give you correct results.

**Comment by m7onov** [comment] 2020-03-20 13:18
@asimrp yeah, that works, thanks for the workaround

**Comment by darthunix** [comment] 2020-07-09 07:57
@asimrp I have found a bad scenario where postgres planner doesn't produce a correct plan as well:
```sql
create table tr(a int) distributed replicated;
create sequence seq;
set optimizer = off;

explain analyze verbose insert into tr select nextval('seq');
                                                  QUERY PLAN                                                   
---------------------------------------------------------------------------------------------------------------
 Insert on public.tr  (cost=0.00..0.02 rows=1 width=8) (never executed)
   ->  Subquery Scan on "*SELECT*"  (cost=0.00..0.02 rows=1 width=8) (actual time=0.556..0.559 rows=1 loops=1)
         Output: "*SELECT*".nextval
         ->  Result  (cost=0.00..0.01 rows=1 width=0) (actual time=0.545..0.546 rows=1 loops=1)
               Output: nextval('seq'::regclass)
 Planning time: 0.771 ms
   (slice0)    Executor memory: 65K bytes avg x 3 workers, 65K bytes max (seg0).
 Memory used:  128000kB
 Optimizer: Postgres query optimizer
 Settings: optimizer=off
 Execution time: 3.474 ms
(11 rows)

select * from gp_dist_random('tr');
 a 
---
 1
 3
 2
(3 rows)
```

**Comment by asimrp** [comment] 2020-07-09 10:03
Thank you @darthunix for another repro.  @kainwen is this issue somewhat related to the problem you are tackling in PR #10418?

**Comment by kainwen** [comment] 2020-07-10 06:43
> Thank you @darthunix for another repro. @kainwen is this issue somewhat related to the problem you are tackling in PR #10418?

The case mentioned by @darthunix should be fixed by PR https://github.com/greenplum-db/gpdb/pull/10418.

**Comment by kainwen** [comment] 2020-07-10 07:07
> @asimrp I have found a bad scenario where postgres planner doesn't produce a correct plan as well:
> 
> ```sql
> create table tr(a int) distributed replicated;
> create sequence seq;
> set optimizer = off;
> 
> explain analyze verbose insert into tr select nextval('seq');
>                                                   QUERY PLAN                                                   
> ---------------------------------------------------------------------------------------------------------------
>  Insert on public.tr  (cost=0.00..0.02 rows=1 width=8) (never executed)
>    ->  Subquery Scan on "*SELECT*"  (cost=0.00..0.02 rows=1 width=8) (actual time=0.556..0.559 rows=1 loops=1)
>          Output: "*SELECT*".nextval
>          ->  Result  (cost=0.00..0.01 rows=1 width=0) (actual time=0.545..0.546 rows=1 loops=1)
>                Output: nextval('seq'::regclass)
>  Planning time: 0.771 ms
>    (slice0)    Executor memory: 65K bytes avg x 3 workers, 65K bytes max (seg0).
>  Memory used:  128000kB
>  Optimizer: Postgres query optimizer
>  Settings: optimizer=off
>  Execution time: 3.474 ms
> (11 rows)
> 
> select * from gp_dist_random('tr');
>  a 
> ---
>  1
>  3
>  2
> (3 rows)
> ```

@asimrp @darthunix Add this as test case in pr 10418.

**Comment by kainwen** [comment] 2020-07-22 12:27
Two pr to fix the issue for planner have been merged into master (https://github.com/greenplum-db/gpdb/pull/10418)  and 6X (https://github.com/greenplum-db/gpdb/pull/10495). 

I test the issue and confirm it is fixed under planner. 

Keep it open until orca fixes this.

**Comment by lij55** [comment] 2022-03-31 08:06
orca works as well, tested on 6.19.1:
```sql
test=# set optimizer=on;
SET
test=# select * from test_function() t order by t.b;
 a | b 
---+---
 1 | 1
 1 | 1
(2 rows)

test=# set optimizer=off;
SET
test=# select * from test_function() t order by t.b;
 a | b 
---+---
 1 | 1
 1 | 1
(2 rows)

```
closing issue.

**Closed by lij55** 2022-03-31 08:06 UTC
Labels: area: gporca
