### ISSUE TITLE
gpactivatestandby fails

### ISSUE THREAD

**Issue by volkovandr** [greenplum-db/gpdb#1202] opened 2016-10-12 15:03 UTC
Hello,

I have a cluster of 2 master nodes and 2 data nodes, 1 primary and 1 mirror segment on each data node. Cluster is up and running normally.

I want to test how the standby master takes over if the primary master dies. I kill the primary master with 
```
gpadmin@mustard11:~$ ps -aux | grep postgres
gpadmin   1368  0.0  0.3 353952 14812 ?        Ss   14:30   0:00 postgres: port  5432, wal sender process gpadmin 10.1.4.62(4303) con2671 10.1.4.62(4303) streaming 0/14A91910                    
gpadmin   1609  0.0  0.0  14196  2212 pts/2    R+   14:32   0:00 grep postgres
gpadmin  26385  0.0  5.0 351120 205872 ?       Ss   12:57   0:01 /usr/local/gpdb/bin/postgres -D /opt/data/master/gpseg-1 -p 5432 --gp_dbid=1 --gp_num_contents_in_cluster=2 --silent-mode=true -i -M master --gp_contentid=-1 -x 0 -E
gpadmin  26386  0.0  0.1 131592  7300 ?        Ss   12:57   0:00 postgres: port  5432, master logger process                                                                                      
gpadmin  26389  0.0  0.1 131604  7056 ?        Ss   12:57   0:00 postgres: port  5432, stats collector process                                                                                    
gpadmin  26390  0.0  0.1 351144  7196 ?        Ss   12:57   0:02 postgres: port  5432, writer process                                                                                             
gpadmin  26391  0.0  0.2 351440  9396 ?        Ss   12:57   0:00 postgres: port  5432, checkpoint process                                                                                         
gpadmin  26392  0.0  0.2 352204  9884 ?        S    12:57   0:00 postgres: port  5432, seqserver process                                                                                          
gpadmin  26393  0.0  0.3 489700 13364 ?        S    12:57   0:00 postgres: port  5432, ftsprobe process                                                                                           
gpadmin  26394  0.0  0.1 351136  4092 ?        S    12:57   0:00 postgres: port  5432, sweeper process                                                                                            
gpadmin  26395  0.0  0.1 351260  7592 ?        Ss   12:57   0:01 postgres: port  5432, wal writer process                                                                                         

gpadmin@mustard1:~$ kill -9 26385
```
now I go to the standby master and try to activate it
```
gpadmin@mustard2:~$ gpactivatestandby
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:------------------------------------------------------
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Standby data directory    = /opt/data/master/gpseg-1
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Standby port              = 5432
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Standby running           = yes
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Force standby activation  = no
20161012:15:10:22:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:------------------------------------------------------
Do you want to continue with standby master activation? Yy|Nn (default=N):
> y
20161012:15:10:24:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-found standby postmaster process
20161012:15:10:24:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Updating transaction files filespace flat files...
20161012:15:10:24:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Updating temporary files filespace flat files...
20161012:15:10:24:010649 gpactivatestandby:mustard2:gpadmin-[INFO]:-Promoting standby...
20161012:15:10:24:010649 gpactivatestandby:mustard2:gpadmin-[DEBUG]:-Waiting for connection...
20161012:15:11:15:010649 gpactivatestandby:mustard2:gpadmin-[CRITICAL]:-Error activating standby master: Either the set port is incorrect or the postmaster could not come up.
```
there is nothing relevant the startup.log 
but in the gpdb log I see this:
```
2016-10-12 15:10:24.878855 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","received promote request",,,,,,,0,,"xlog.c",12052,
2016-10-12 15:10:24.878861 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","redo done at 0/14B3E258",,,,,,,0,,"xlog.c",7033,
2016-10-12 15:10:24.878867 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","last completed transaction was at log time 2016-10-12 15:09:44.376634+00",,,,,,,0,,"xlog.c",7038,
2016-10-12 15:10:24.881677 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","end of transaction log location is 0/14B3E290",,,,,,,0,,"xlog.c",7083,
2016-10-12 15:10:24.886050 UTC,"gpadmin","postgres",p10685,th-133273792,"::1","52220",2016-10-12 15:10:24 UTC,0,,,seg-1,,,,,"FATAL","57P03","the database system is starting up",,,,,,,0,,"postmaster.c",2926,
2016-10-12 15:10:24.949345 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_relation_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:10:24.949432 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_database_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:10:24.949502 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_tablespace_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:10:24.949552 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_filespace_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:10:24.949586 UTC,,,p10548,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup pass 1.  Proceeding to startup crash recovery passes 2 and 3.",,,,,,,0,,"xlog.c",7342,
2016-10-12 15:10:24.959632 UTC,,,p10686,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup crash recovery pass 2",,,,,,,0,,"xlog.c",7518,
2016-10-12 15:10:24.964892 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","record with zero length at 0/14B3E290",,,,,,,0,,"xlog.c",4216,
2016-10-12 15:10:24.968738 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","58P01","could not create archive status file ""pg_xlog/archive_status/00000002.history.ready"": No such file or directory",,,,,,,0,,"xlog.c",1599,
2016-10-12 15:10:24.968810 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","selected new timeline ID: 2",,,,,,,0,,"xlog.c",7655,
2016-10-12 15:10:25.171054 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","Oldest active transaction from prepared transactions 909",,,,,,,0,,"xlog.c",6128,
2016-10-12 15:10:25.171246 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","latest completed transaction id is 908 and next transaction id is 909",,,,,,,0,,"xlog.c",6143,
2016-10-12 15:10:25.238431 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","database system is almost ready",,,,,,,0,,"xlog.c",6179,
2016-10-12 15:10:25.238487 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","PostgreSQL 8.3.23 (Greenplum Database 4.3.99.00 build dev) on x86_64-unknown-linux-gnu, compiled by GCC gcc (Debian 4.9.2-10) 4.9.2 compiled on Oct 10 2016 11:32:52",,,,,,,0,,"xlog.c",6197,
2016-10-12 15:10:25.243371 UTC,,,p10687,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup crash recovery pass 3",,,,,,,0,,"xlog.c",7703,
2016-10-12 15:10:25.252700 UTC,,,p10688,th-133273792,,,,909,,,seg-1,,,x909,sx1,"LOG","00000","Current tuple for heap_update: tid (0,1), xmin 681, xmin_status 'Hint-Committed', xmin_commit_distrib_id '(info not avail)', xmax 909, xmax_status 'CLog-In-Progress', command_id 0, infomask '{HEAP_XMIN_COMMITTED}', update_tid (0,1), visibility 'Now'",,,,,,,0,,"heapam.c",2585,
2016-10-12 15:10:25.271336 UTC,,,p10688,th-133273792,,,,909,,,seg-1,,,x909,sx1,"FATAL","XX000","tuple already updated by self (heapam.c:3628)",,,,,,,0,,"heapam.c",3628,"Stack trace:
1    0x9091e9 postgres errstart (??:?)
2    0x90aea4 postgres elog_finish (??:?)
3    0x4efa25 postgres simple_heap_update (??:?)
4    0x9654fc postgres gp_activate_standby (??:?)
5    0x90f7b6 postgres DirectFunctionCall1 (??:?)
6    0x520265 postgres StartupXLOG_Pass4 (??:?)
7    0x52a2e0 postgres StartupProcessMain (??:?)
8    0x57ac69 postgres AuxiliaryProcessMain (??:?)
9    0x79c670 postgres <symbol not found> (postmaster.c:?)
10   0x79efa0 postgres <symbol not found> (postmaster.c:?)
11   0x7a4d1e postgres <symbol not found> (postmaster.c:?)
12   0x7a631a postgres PostmasterMain (??:?)
13   0x4c5bcb postgres main (??:?)
14   0x7f17f4e99b45 libc.so.6 __libc_start_main (??:0)
15   0x4c6434 postgres <symbol not found> (??:?)
"
2016-10-12 15:10:25.276706 UTC,,,p10531,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","startup pass 4 process (PID 10688) exited with exit code 1",,,,,,,0,,"postmaster.c",5597,
2016-10-12 15:10:25.276725 UTC,,,p10531,th-133273792,,,,0,,,seg-1,,,,,"LOG","00000","aborting startup due to startup process failure",,,,,,,0,,"postmaster.c",4618,
```

That was working fine with binaries complied from source some months ago but that was on different cluster and I can not really tell if the issue is related to recent changes in the source code or the configuration of the server.

The attempts to start it with gpstart fail with similar output to the log files.

**Comment by volkovandr** [comment] 2016-10-12 15:19
That's the log file after gpstart:
```
2016-10-12 15:16:28.513598 UTC,,,p10992,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","TransitionToMasterOrMirrorless: initializing XLog startup",,,,,,,0,,"primary_mirror_mode.c",1883,
2016-10-12 15:16:28.513665 UTC,,,p10992,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","TransitionToMasterOrMirrorless: starting database",,,,,,,0,,"primary_mirror_mode.c",1897,
2016-10-12 15:16:28.514652 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","database system was interrupted post new TLI was setup on standby promotion at 2016-10-12 15:10:25 UTC",,"If this has occurred more than once something unexpected is happening after standby has been promoted and new TLI has been set",,,,,0,,"xlog.c",6505,
2016-10-12 15:16:28.515135 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","database system was not properly shut down; automatic recovery in progress",,,,,,,0,,"xlog.c",6810,
2016-10-12 15:16:28.517463 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","redo starts at 0/14B3E328",,,,,,,0,,"xlog.c",6942,
2016-10-12 15:16:28.517750 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","invalid magic number 0000 in log file 0, segment 5, offset 11829248",,,,,,,0,,"xlog.c",4495,
2016-10-12 15:16:28.517788 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","redo done at 0/14B47F08",,,,,,,0,,"xlog.c",7033,
2016-10-12 15:16:28.517843 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","end of transaction log location is 0/14B47FB8",,,,,,,0,,"xlog.c",7083,
2016-10-12 15:16:28.521703 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_relation_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:16:28.521772 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_database_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:16:28.521849 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_tablespace_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:16:28.521916 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","beginning free list validation for gp_persistent_filespace_node, maxFreeOrderNum = 0",,,,,,,0,,"cdbpersistentstore.c",351,
2016-10-12 15:16:28.521952 UTC,,,p10994,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup pass 1.  Proceeding to startup crash recovery passes 2 and 3.",,,,,,,0,,"xlog.c",7342,
2016-10-12 15:16:28.530477 UTC,,,p10995,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup crash recovery pass 2",,,,,,,0,,"xlog.c",7518,
2016-10-12 15:16:28.533453 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","invalid magic number 0000 in log file 0, segment 5, offset 11829248",,,,,,,0,,"xlog.c",4495,
2016-10-12 15:16:28.533534 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","Oldest active transaction from prepared transactions 909",,,,,,,0,,"xlog.c",6128,
2016-10-12 15:16:28.533715 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","latest completed transaction id is 908 and next transaction id is 909",,,,,,,0,,"xlog.c",6143,
2016-10-12 15:16:28.540089 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","database system is almost ready",,,,,,,0,,"xlog.c",6179,
2016-10-12 15:16:28.540128 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","PostgreSQL 8.3.23 (Greenplum Database 4.3.99.00 build dev) on x86_64-unknown-linux-gnu, compiled by GCC gcc (Debian 4.9.2-10) 4.9.2 compiled on Oct 10 2016 11:32:52",,,,,,,0,,"xlog.c",6197,
2016-10-12 15:16:28.543053 UTC,,,p10996,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","Finished startup crash recovery pass 3",,,,,,,0,,"xlog.c",7703,
2016-10-12 15:16:28.550788 UTC,,,p10997,th1878017856,,,,909,,,seg-1,,,x909,sx1,"LOG","00000","Current tuple for heap_update: tid (0,1), xmin 681, xmin_status 'Hint-Committed', xmin_commit_distrib_id '(info not avail)', xmax 909, xmax_status 'CLog-In-Progress', command_id 0, infomask '{HEAP_XMIN_COMMITTED}', update_tid (0,1), visibility 'Now'",,,,,,,0,,"heapam.c",2585,
2016-10-12 15:16:28.562815 UTC,,,p10997,th1878017856,,,,909,,,seg-1,,,x909,sx1,"FATAL","XX000","tuple already updated by self (heapam.c:3628)",,,,,,,0,,"heapam.c",3628,"Stack trace:
1    0x9091e9 postgres errstart (??:?)
2    0x90aea4 postgres elog_finish (??:?)
3    0x4efa25 postgres simple_heap_update (??:?)
4    0x9654fc postgres gp_activate_standby (??:?)
5    0x90f7b6 postgres DirectFunctionCall1 (??:?)
6    0x520265 postgres StartupXLOG_Pass4 (??:?)
7    0x52a2e0 postgres StartupProcessMain (??:?)
8    0x57ac69 postgres AuxiliaryProcessMain (??:?)
9    0x79c670 postgres <symbol not found> (postmaster.c:?)
10   0x79efa0 postgres <symbol not found> (postmaster.c:?)
11   0x7a4d1e postgres <symbol not found> (postmaster.c:?)
12   0x7a631a postgres PostmasterMain (??:?)
13   0x4c5bcb postgres main (??:?)
14   0x7f996ccb7b45 libc.so.6 __libc_start_main (??:0)
15   0x4c6434 postgres <symbol not found> (??:?)
"
2016-10-12 15:16:28.564318 UTC,,,p10992,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","startup pass 4 process (PID 10997) exited with exit code 1",,,,,,,0,,"postmaster.c",5597,
2016-10-12 15:16:28.564346 UTC,,,p10992,th1878017856,,,,0,,,seg-1,,,,,"LOG","00000","aborting startup due to startup process failure",,,,,,,0,,"postmaster.c",4618,
```

**Comment by volkovandr** [comment] 2016-10-12 17:27
Checked out the repository at randomly chosen commit 30948311d2cbba4154a88a731ef57b083688cbf1 which was somewhere in the beginning of August and compiled the binaries again. The only difference is that the DB is now compiled without GPORCA.

Repeated the same steps to make the standby master take over and now it was successful! 
So I believe some changes after that commit broke the standby master activation. Or GPORCA is the reason but that does not seem related.

**Comment by volkovandr** [comment] 2016-10-12 20:04
Now checked out the repository at commit 1287e6317ec3e1d0ccf090e3575711960c159025 which was in the middle of September.
The issue is there now. So the problem arose somewhere between beginning of August and middle of September. And there was another issue with starting the standby master after restarting the cluster, i think that is fixed already.

**Comment by jimmyyih** [comment] 2016-10-12 22:03
It's failing to update gp_segment_configuration relation on the standby master.  The issue is easily reproducible and I think was introduced in commit 8df78e67f4de4bda603f021f573e81745102902b for function segment_config_activate_standby() in src/backend/utils/gp/segadmin.c.

**Comment by jimmyyih** [comment] 2016-10-13 18:57
Fix merged into master:
https://github.com/greenplum-db/gpdb/commit/67963ee0b169820274097fe771faca38725f8f0a

Thanks again @volkovandr for the detailed report!  Closing this issue.  Please reopen if the issue persists.

**Closed by jimmyyih** 2016-10-13 18:57 UTC
