### ISSUE TITLE
Every time stop cluster, then Standby Master could not be started

### ISSUE THREAD

**Issue by zhangyuvip** [greenplum-db/gpdb#1121] opened 2016-09-14 04:31 UTC
Every time stop cluster, then Standby Master could not be started (4.3.99.00 build dev)

gpstop -M fast
20160914:10:49:58:019358 gpstop:mdw:gpadmin-[INFO]:-Successfully shutdown 8 of 8 segment instances 
20160914:10:49:58:019358 gpstop:mdw:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20160914:10:49:58:019358 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20160914:10:49:58:019358 gpstop:mdw:gpadmin-[INFO]:-No leftover gpmmon process found
20160914:10:49:58:019358 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20160914:10:49:59:019358 gpstop:mdw:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20160914:10:49:59:019358 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover shared memory

gpstart
20160914:10:54:15:019459 gpstart:mdw:gpadmin-[INFO]:-Successfully started 8 of 8 segment instances 
20160914:10:54:15:019459 gpstart:mdw:gpadmin-[INFO]:-----------------------------------------------------
20160914:10:54:15:019459 gpstart:mdw:gpadmin-[INFO]:-Starting Master instance mdw directory /data/master/gpseg-1/ 
20160914:10:54:16:019459 gpstart:mdw:gpadmin-[INFO]:-Command pg_ctl reports Master mdw instance active
20160914:10:54:21:019459 gpstart:mdw:gpadmin-[INFO]:-Starting standby master
20160914:10:54:21:019459 gpstart:mdw:gpadmin-[INFO]:-Checking if standby master is running on host: smdw  in directory: /data/master/gpseg-1
20160914:10:56:15:019459 gpstart:mdw:gpadmin-[WARNING]:-Could not start standby master
20160914:10:56:15:019459 gpstart:mdw:gpadmin-[WARNING]:-Standby Master could not be started

**Comment by Chibin** [comment] 2016-09-14 16:53
Can you try rerunning gpstart with the -v option? `gpstart -v`
-v should show the command that gpstart uses to start up the standby master and may help find the cause.

**Comment by Chibin** [comment] 2016-09-16 17:11
any updates?

**Comment by Eulerizeit** [comment] 2016-09-16 18:03
A similar issue exists on an AWS install.  Asim worked on it some
yesterday.

**Comment by asimrp** [comment] 2016-09-16 18:28
Yes, I witnessed that standby cannot come up successfully when initialized as `gpinitsystem -s`.  But when `gpinitstandy` is used to initialize standby after `gpinitsystem` has completed, it comes up successfully.

**Comment by zhangyuvip** [comment] 2016-09-18 01:29
gpstart -v
20160918:09:20:12:031197 gpstart:mdw:gpadmin-[INFO]:-Starting standby master
20160918:09:20:12:031197 gpstart:mdw:gpadmin-[INFO]:-Checking if standby master is running on host: smdw  in directory: /data/master/gpseg-1
20160918:09:20:12:031197 gpstart:mdw:gpadmin-[DEBUG]:-Starting standby: start standby master cmdStr='ssh -o 'StrictHostKeyChecking no' smdw ". /opt/gpdb/greenplum_path.sh; env GPSESSID=0000000000 GPERA=c34965b82547181d_160918091932 $GPHOME/bin/pg_ctl -D /data/master/gpseg-1 -l /data/master/gpseg-1/pg_log/startup.log -t 600 -o \" -p 5432 --gp_dbid=10 --gp_num_contents_in_cluster=4 --silent-mode=true -i -M master --gp_contentid=-1 -x 0 -y -E \" start"'  had result: cmd had rc=0 completed=True halted=False
  stdout='server starting
'
  stderr=''
20160918:09:20:12:031197 gpstart:mdw:gpadmin-[DEBUG]:-Starting standby master results: cmd had rc=0 completed=True halted=False
  stdout='server starting
'
  stderr=''
20160918:09:20:13:031197 gpstart:mdw:gpadmin-[DEBUG]:-get pids cmdStr='ssh -o 'StrictHostKeyChecking no' smdw ". /opt/gpdb/greenplum_path.sh; python -c 'from gppylib.commands import unix; print unix.getDescendentProcesses(1364)'"'  had result: cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:20:13:031197 gpstart:mdw:gpadmin-[DEBUG]:-cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:20:14:031197 gpstart:mdw:gpadmin-[DEBUG]:-get pids cmdStr='ssh -o 'StrictHostKeyChecking no' smdw ". /opt/gpdb/greenplum_path.sh; python -c 'from gppylib.commands import unix; print unix.getDescendentProcesses(1364)'"'  had result: cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:20:14:031197 gpstart:mdw:gpadmin-[DEBUG]:-cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:20:16:031197 gpstart:mdw:gpadmin-[DEBUG]:-get pids cmdStr='ssh -o 'StrictHostKeyChecking no' smdw ". /opt/gpdb/greenplum_path.sh; python -c 'from gppylib.commands import unix; print unix.getDescendentProcesses(1364)'"'  had result: cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:20:16:031197 gpstart:mdw:gpadmin-[DEBUG]:-cmd had rc=0 completed=True halted=False
  stdout='[1390, 1391]
'
  stderr=''
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[WARNING]:-Could not start standby master
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[WARNING]:-Standby Master could not be started
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-WorkerPool haltWork()
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker0] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker1] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker2] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker3] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker4] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker5] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker6] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker7] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker8] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker9] haltWork
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker8] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker9] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker5] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker4] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker6] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker3] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker7] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker0] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker2] stopping
20160918:09:21:56:031197 gpstart:mdw:gpadmin-[DEBUG]:-[worker1] stopping

**Comment by hlinnaka** [comment] 2016-10-07 07:39
I just pushed commit e95907077a0728bbdd9d3f4a398e34e8ee210f6d to fix an issue that might've been the same as this one. Can you retry with a fresh checkout, to see if it works now?

**Comment by ashwinstar** [comment] 2016-10-20 16:59
Closing the issue as most likely commit e959070 fixed the problem. If not please feel free to re-open.

**Closed by ashwinstar** 2016-10-20 16:59 UTC
