### ISSUE TITLE
Create table as select  failed when using  function  in select sql

### ISSUE THREAD

**Issue by mirai280535831** [greenplum-db/gpdb#9365] opened 2020-01-07 02:52 UTC
### Greenplum version or build
postgres=# select version();
                                                                                            version
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Dec 24 2019 09:59:35
(1 row)
### OS version and uname -a
[gpadmin@node1 regress]$ uname -a
Linux  3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
1.create function
```
CREATE OR REPLACE FUNCTION array_unnest_2d_to_1d(
  x ANYARRAY,
  OUT unnest_row_id INT,
  OUT unnest_result ANYARRAY
)
RETURNS SETOF RECORD
AS
$BODY$
  SELECT t2.r::int, array_agg($1[t2.r][t2.c] order by t2.c) FROM
  (
    SELECT generate_series(array_lower($1,2),array_upper($1,2)) as c, t1.r
    FROM
    (
      SELECT generate_series(array_lower($1,1),array_upper($1,1)) as r
    ) t1
  ) t2
GROUP BY t2.r
$BODY$ LANGUAGE SQL IMMUTABLE
;

DROP TABLE IF EXISTS unnest_2d_tbl01;
CREATE TABLE unnest_2d_tbl01 (id INT, val DOUBLE PRECISION[][]);
INSERT INTO unnest_2d_tbl01 VALUES
  (1, ARRAY[[1::float8,2],[3::float8,4],[5::float8,6],[7::float8,8]]),
  (2, ARRAY[[101::float8,202],[303::float8,404],[505::float8,606]])
;
```
2.create table unnest_2d_tbl01_out  successfull
```
DROP TABLE IF EXISTS unnest_2d_tbl01_out;
CREATE TABLE unnest_2d_tbl01_out AS
  SELECT id, (array_unnest_2d_to_1d(val)).* FROM unnest_2d_tbl01;
```
### Actual behavior
1.create function
```
CREATE OR REPLACE FUNCTION array_unnest_2d_to_1d(
  x ANYARRAY,
  OUT unnest_row_id INT,
  OUT unnest_result ANYARRAY
)
RETURNS SETOF RECORD
AS
$BODY$
  SELECT t2.r::int, array_agg($1[t2.r][t2.c] order by t2.c) FROM
  (
    SELECT generate_series(array_lower($1,2),array_upper($1,2)) as c, t1.r
    FROM
    (
      SELECT generate_series(array_lower($1,1),array_upper($1,1)) as r
    ) t1
  ) t2
GROUP BY t2.r
$BODY$ LANGUAGE SQL IMMUTABLE
;
DROP TABLE IF EXISTS unnest_2d_tbl01;
CREATE TABLE unnest_2d_tbl01 (id INT, val DOUBLE PRECISION[][]);
INSERT INTO unnest_2d_tbl01 VALUES
  (1, ARRAY[[1::float8,2],[3::float8,4],[5::float8,6],[7::float8,8]]),
  (2, ARRAY[[101::float8,202],[303::float8,404],[505::float8,606]])
;
```
2.create table unnest_2d_tbl01_out  fail
```
DROP TABLE IF EXISTS unnest_2d_tbl01_out;
CREATE TABLE unnest_2d_tbl01_out AS
  SELECT id, (array_unnest_2d_to_1d(val)).* FROM unnest_2d_tbl01;
```
create table failed, the error log is:
```

postgres-#   SELECT id, (array_unnest_2d_to_1d(val)).* FROM unnest_2d_tbl01;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
ERROR:  relation not found (OID 69730)  (seg0 10.121.66.121:6000 pid=19689)
DETAIL:  This can be validly caused by a concurrent delete operation on this object.
```

**Comment by kainwen** [comment] 2020-01-08 06:28
This runs correctly in 6, but fails for the master branch.

It is a regression issue, will spend time to fix this.

Thanks for the reporting.

**Comment by kainwen** [comment] 2020-01-10 07:41
The issue (#9365) is gone in the PR #9093
as heikki's gets rid off plan->dispatch.

PR (https://github.com/greenplum-db/gpdb/pull/9391) is merged to add a case, so this issue fixed.

**Closed by kainwen** 2020-01-10 07:41 UTC
Labels: type: bug, version: 7X_ALPHA

**Comment by mirai280535831** [comment] 2020-07-07 02:33
> The issue (#9365) is gone in the PR #9093
> as heikki's gets rid off plan->dispatch.
> 
> PR (#9391) is merged to add a case, so this issue fixed.

PR (#9391)  is removed  by @hlinnaka in commit 93abe741cd67f04958e2951edff02b45ab6e280f ,
do you need to push it again?

**Comment by mirai280535831** [comment] 2020-07-07 02:33
@kainwen

**Comment by kainwen** [comment] 2020-07-07 02:36
> @kainwen

The PR introduces a test case. And heikki refactored the code and also includes test case.

So I believe the issue is fixed.

Do you have problem with latest code?
