### ISSUE TITLE
Welcome to discussion:"query plan with multiple segworker groups is not supported"

### ISSUE THREAD

**Issue by geostar123** [greenplum-db/gpdb#11485] opened 2021-02-06 06:37 UTC
### Greenplum version or build
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14163.g327f60a build dev) on x86_64-pc-linux-gnu
### OS version and uname -a
Linux pgdb-master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--prefix=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -O3  -Werror=uninitialized
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lzstd -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl
VERSION = PostgreSQL 12beta2
### Expected behavior
I often encountered the issue when executing "create extension ....". what it means and how to solve it? There is no meaningful result on Google.Could you give me some clues?Thanks.

**Comment by geostar123** [comment] 2021-02-06 06:37
Any help will be appericated.

**Comment by kainwen** [comment] 2021-02-06 10:30
> Any help will be appericated.

The issue is reported by different community users. But I cannot reproduce it locally so it is hard for me to debug.

Can you show the detailed steps that you reproduce the issue. It would be a great help.

**Comment by kainwen** [comment] 2021-02-06 14:27
With the help from some other open-source community user, I have find the root cause of this issue. Will update here soon.

**Comment by kainwen** [comment] 2021-02-07 11:07
1. Please retry the create statement that throws the error you mentioned, and paste the log in segment (any segment should be OK, not master's log) here
2. Please verify the the two dirs' content is or is not the same, and paste answer here:
    * `$GPHOME/lib/postgresql` on master host machine
    * `$GPHOME/lib/postgresql` on segment host machine

With the above info, the issue should be clarified.

**Comment by kainwen** [comment] 2021-02-07 11:07
@geostar123

**Comment by geostar123** [comment] 2021-02-21 07:19
@kaiwen,thank you.I am looking forward to your analysis.

**Comment by kainwen** [comment] 2021-02-21 12:36
> @kaiwen,thank you.I am looking forward to your analysis.

It should be the same issue as https://github.com/greenplum-db/gpdb/issues/10241

But the root cause should be the extension not correctly installed on segments.

Please provide the information I mentioned in https://github.com/greenplum-db/gpdb/issues/11485#issuecomment-774655169

**Comment by dusx1981** [comment] 2021-03-22 01:21
it should be the same as [#11304 ](https://github.com/greenplum-db/gpdb/issues/11304)

**Comment by kainwen** [comment] 2021-03-23 09:22
Fixed by https://github.com/greenplum-db/gpdb/commit/58628039c5369a520fc65adb87f0d29fd1203fd7 in master
and in 6x https://github.com/greenplum-db/gpdb/commit/4d185c05c8406cd38659a3aee952150c4cecb2b2

**Closed by kainwen** 2021-03-23 09:22 UTC
