### ISSUE TITLE
Some issues of Locking behaviour for Greenplum Partition table

### ISSUE THREAD

**Issue by kainwen-zz** [greenplum-db/gpdb#8362] opened 2019-08-13 06:45 UTC
GPDB version: 6 and master (I do not check 5, let's check it in future).

## Expected Behaviour

The locking behaviour of DMLs(insert, delete, update) on partition tables is complex.

Before a query executes, we hold locks on tables first at parsing stage, and then when initplan. We should make sure lock mode on the same table to be the same at these two stages.

Also, Greenplum supports polymorphic storage types which means that different leaf partitions may have different storage types(ao, heap, aoco). And when GDD is enabled, UPDATE|DELETE on ao table behaves differently from heap table.

So in all:
1. When DML operates on root partition,  during parsing stage, we should lock the root and every other partition within it in correct lock mode:
  - When GDD is disabled, for both heap and ao table,  lockmodes = `{insert: rowexlusive , update: exclusive, delete: exclusive}`
  - When GDD is enabled, for heap table, lockmodes  = `rowexclusive for all`; for ao table, lockmodes = `rowexclusive for insert, exclusive for update|delete`

2. During initplan, hold the same lock as the parsing stage.

## Current problems

With ORCA enabled, for update|delete, the plan does not contain leaf partions, and during parsing stage, it will does not hold locks on leaf partitions, and when initplan, it will hold Exclusive lock on leafs. And this is too late because we have got snapshot.

## A simple reproducer

Enable orca

```sql
CREATE TABLE t (c1 int, c2 int, c3 int) 
with(appendonly=true)
DISTRIBUTED BY (c1)
PARTITION BY RANGE (c2)
( START (0) END (10) EVERY (1), 
  DEFAULT PARTITION extra ); 

insert into t (1, 100, 1);

-- step1
--txn1:
begin;
delete from t_1_prt_extra where c2 > 20;

-- step2
--txn2:
begin;
delete from t where c2 > 20; -- this will hang

--step3:
--txn1:
end; -- it commits transaction 1, so transaction 2 will wake up

-- step4:
--txn2, wake up
on segment we will hit the unique constrain fail of ao visibitily map table
```

-----------------------------

After fixing this, we should update the documents.

**Comment by asimrp** [comment] 2019-08-15 05:03
This is a related PR https://github.com/greenplum-db/gpdb/pull/8133

**Comment by bhuvnesh2703** [comment] 2019-08-16 22:00
created a story, as well to track it, it will need some effort to fix it and test it.

**Comment by asimrp** [comment] 2021-06-07 08:08
Sooner than later, we will have to bite this bullet @wuj21

**Comment by kainwen** [comment] 2021-09-29 04:30
This should be fixed by the above pr https://github.com/greenplum-db/gpdb/pull/11895

**Closed by kainwen** 2021-09-29 04:30 UTC
Labels: status: done triaging

**Comment by cobolbaby** [comment] 2023-04-26 05:16
Concurrently executing INSERT/DELETE on the AO table will cause  `exclusive` lock;

![2023-04-26 13-10-23屏幕截图](https://user-images.githubusercontent.com/11460848/234475585-06a3cbed-9283-4cd1-a33f-794ffee61db2.png)

**Comment by ashwinstar** [comment] 2023-04-26 06:24
Yes. Delete and Update on AO table takes exclusive lock. That's by design mostly due to limitation of visimap table implementation used for tracking the tuple deletion.
