### ISSUE TITLE
psql: ERROR: path of type 46 is missing distribution locus (pathnode.c:472)(Could not executing aggregation query)

### ISSUE THREAD

**Issue by geostar123** [greenplum-db/gpdb#11407] opened 2021-01-25 07:27 UTC
### Greenplum version or build
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14163.g327f60a build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled
### OS version and uname -a
Linux pgdb-master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--pre fix=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels - Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces s-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -O3 -Werror=uninitialized -Werror=implicit-function-dec laration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5 -lzstd -lz -lreadline -lrt -lcrypt -ldl -lm -lcurl
VERSION = PostgreSQL 12beta2
### Actual behavior
I can execute aggregation query over foreign table on greenplum cluster.
### Step to reproduce the behavior
ostgresql 11.6 Physical Table:
create table m9_x86(id int,s smallint,c text,l bigint,f numeric(12,2), d double precision,t date,ts1 timestamp with time zone,ts2 timestamp without time zone,g GEOMETRY,PRIMARY KEY(id));
CREATE INDEX m9_x86_gix ON m9_x86 USING GIST (g);

Step 1:
//Postgresql 11.6 server is installed on host fdw8-laptop-pc,and now it started.
psql>CREATE SERVER postgres_svr FOREIGN DATA WRAPPER postgres_fdw OPTIONS(host 'fdw8-laptop-pc', port '5432', dbname 'postgres');
Step 2:
psql>CREATE USER MAPPING FOR gpadmin SERVER postgres_svr OPTIONS(user 'test', password '1');
Step 3:
//On host fdw8-laptop-pc,there is one spatial table named m9_x86 metioned above
psql>CREATE FOREIGN TABLE m9_x86_pg11(id int,s smallint,c text,l bigint,f numeric(38,15), d double precision,t date,ts1 timestamp with time zone,ts2 timestamp without time zone,g GEOMETRY) SERVER postgres_svr OPTIONS (table_name 'm9_x86');

Step 4://add data
psql>insert into m9_x86_pg11(id,s,c,l,f,d,t,ts1,ts2,g) values(48,12,'postgres',999999999999,12.34,99.999999999,make_date(2020,4,8),make_timestamp(2020,4,8,14,47,12.34),make_timestamptz(2020,4,8,14,47,12.34,'Asia/Shanghai'),ST_GeomFromText('POINT(20 20)',4326));
INSERT 0 1

Step 5 > select avg(l) from m9_x86_pg11 where id < 1000 group by id;
errors occured:
psql: ERROR:  path of type 46 is missing distribution locus (pathnode.c:472)

Any help will be appericated,Thanks.

**Comment by geostar123** [comment] 2021-01-28 08:30
Has someone encounter this issue?

**Comment by kainwen** [comment] 2021-01-31 11:13
I can reproduce this issue locally.

I think this is a bug because the function `create_foreign_upper_path` forget to set the path's locus field.

**Comment by geostar123** [comment] 2021-02-03 07:12
I fixed this issue.

**Comment by kainwen** [comment] 2021-02-03 07:49
> I fixed this issue.

Can you share more?

**Comment by geostar123** [comment] 2021-02-03 09:56
ERROR:  path of type 46 is missing distribution locus (pathnode.c:472)
    
    Analysis:The value of grouppath's locustype  is 0(CdbLocusType_Null) when processing foreign table aggregation,then macro CdbLocusType_IsValid will return false and throw
    exception "path of type 46 is missing distribution locus (pathnode.c:472)"
    
   
   
    
    #define CdbLocusType_IsValid(locustype)     \
    ((locustype) > CdbLocusType_Null &&     \
     (locustype) < CdbLocusType_End)

#define CdbLocusType_IsValidOrNull(locustype)   \
    ((locustype) >= CdbLocusType_Null &&        \
     (locustype) < CdbLocusType_End)
     
     
     
    
    relevant file:cdb/cdbpathlocus.h,optimizer/util/pathnode.c
    
    typedef enum CdbLocusType
    {
    CdbLocusType_Null,
    CdbLocusType_Entry,         /* a single backend process on the entry db:
                                 * usually the qDisp itself, but could be a
                                 * qExec started by the entry postmaster.
                                 */
    CdbLocusType_SingleQE,      /* a single backend process on any db: the
                                 * qDisp itself, or a qExec started by a
                                 * segment postmaster or the entry postmaster.
                                 */
    CdbLocusType_General,       /* compatible with any locus (data is
                                 * self-contained in the query plan or
                                 * generally available in any qExec or qDisp) */
    CdbLocusType_SegmentGeneral,/* generally available in any qExec, but not
								 * available in qDisp */
	CdbLocusType_OuterQuery,	/* generally available in any qExec or qDisp, but
								 * contains correlated vars from outer query, so must
								 * not be redistributed */
    CdbLocusType_Replicated,    /* replicated over all qExecs of an N-gang */
    CdbLocusType_Hashed,        /* hash partitioned over all qExecs of N-gang */
    CdbLocusType_HashedOJ,      /* result of hash partitioned outer join, NULLs can be anywhere */
    CdbLocusType_Strewn,        /* partitioned on no known function */
    CdbLocusType_End            /* = last valid CdbLocusType + 1 */
  } CdbLocusType;

    
    Solve:
      Set the value of grouppath's locustype  to be 3(CdbLocusType_General) as following: 
      postgres_fdw.c functions add_foreign_grouping_paths and add_foreign_ordered_paths from line 5895:
      ......
      add_foreign_grouping_paths
      
      /* Create and add foreign path to the grouping relation. */
	grouppath = create_foreign_upper_path(root,
										  grouped_rel,
										  grouped_rel->reltarget,
										  rows,
										  startup_cost,
										  total_cost,
										  NIL,	/* no pathkeys */
										  NULL,
										  NIL); /* no fdw_private */

  //***********************************************************
  //Modified by geostar123
  //Date:28 Jan,2021
  Path* new_path = (Path*)grouppath;
  elog(INFO,"locustype:%u",new_path->locus.locustype);
  elog(INFO,"pathtype:%u",new_path->pathtype);
  new_path->locus.locustype = 3;
  //***********************************************************
	/* Add generated path into grouped_rel by add_path(). */
	add_path(grouped_rel, (Path *) /*grouppath*/new_path);
	
	.....


   add_foreign_ordered_paths
   
   ...
  //***********************************************************
  //Modified by geostar123
  //Date:28 Jan,2021
  Path* new_path = (Path*)ordered_path;
  elog(INFO,"locustype:%u",new_path->locus.locustype);
  elog(INFO,"pathtype:%u",new_path->pathtype);
  new_path->locus.locustype = 3;
  //***********************************************************
	/* and add it to the ordered_rel */
	add_path(ordered_rel, (Path *) /*ordered_path*/new_path);
	
	...

**Comment by geostar123** [comment] 2021-02-03 09:57
Testing is ok.

**Comment by kainwen** [comment] 2021-02-03 10:00
That is the correct place to fix.

You can ref the code of `create_foreignscan_path` to set the correct locus.

Would you please open a pr to fix this? 

Thanks!

**Comment by adam8157** [comment] 2021-03-01 05:21
Fixed by https://github.com/greenplum-db/gpdb/commit/53ab3b8284584991e9432c95ca804e160fa7f98c, closing

**Closed by adam8157** 2021-03-01 05:21 UTC
