### ISSUE TITLE
ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by wonb168** [greenplum-db/gpdb#17403] opened 2024-04-26 16:08 UTC
## Bug Report
```
Error occurred during SQL query execution

原因：
 SQL 错误 [42P10]: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
  位置：74
```
### Greenplum version or build
7.1.0
### OS version and uname -a
centos9

### Step to reproduce the behavior
```
select distinct day_date ,year_id 
from dim_date dd order by year_id+1
```
If no distinct, it's also OK! and this sql in gp6 is also OK.

my sql need order by GBK, but table is UTF-8, like this:
```
select distinct ... from ...
     ORDER BY convert_to(plan_name,'GBK'), plan_code
```
how to solve this, thank you!

**Comment by cobolbaby** [comment] 2024-04-26 16:22
Duplicate of #17288

**Closed** 2024-04-26 23:40 UTC
Labels: type: bug
