### ISSUE TITLE
after analyze gp_select_invisible not working

### ISSUE THREAD

**Issue by tianshisiyi** [greenplum-db/gpdb#6622] opened 2019-01-05 08:25 UTC
### Greenplum version or build
GPDB5.x and GPDB6.x

### Step to reproduce the behavior
--session 1
pivotal=# drop table hello;
DROP TABLE

pivotal=# create table hello(id int,name text);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'id' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE

pivotal=# insert into hello select generate_series(1,1000),'good';
INSERT 0 1000

pivotal=# update hello set name='bad';
UPDATE 1000

pivotal= set gp_select_invisible=true;
SET

pivotal=# select count(*) from hello;
 count
-------
  2000
(1 row)

--setssion 2
analyze hello;

--session 1
pivotal=# select count(*) from hello; 
 count
-------
  1000
(1 row)

Because we set gp_select_invisible=true,and don't do any vacuum action,It should be 2000, but the return result is 1000

**Comment by hlinnaka** [comment] 2019-01-15 11:03
I cannot reproduce this on GPDB master, with this sequence of commands. Replacing `analyze hello` with `select count(*) from hello` in the second session does the trick, though.

My theory on why it works like that: SELECT (and ANALYZE in GPDB5) does heap page "HOT pruning", in an opportunistic way. It removes the dead tuples, so the other session can't see them anymore, even with `gp_select_invisible=true`.

In general, there is no guarantee on how long dead tuples are kept around, so `gp_select_invisible` is just a best-effort attempt. In other words, this is not a bug.

Closing, please re-open if you still think this is a bug.

**Closed by hlinnaka** 2019-01-15 11:03 UTC
