### ISSUE TITLE
why disable creation of GIN indexes? (MPP-9329)

### ISSUE THREAD

**Issue by LJoNe** [greenplum-db/gpdb#239] opened 2016-01-05 09:40 UTC
We got an extension library with GIN index, which was however disabled by GP. So  I compared the code of GIST index and GIN index, and found out some differences in HA.  Then I add some code (mainly adding MIRROREDLOCK_BUFMGR_LOCK before ReadBuffer and MIRROREDLOCK_BUFMGR_UNLOCK in the end )and enabled creation of GIN.  After some tests.,  it turned out to be running well so far.  Can anybody inform me of the reason behind disabling GIN and any further detailed information of MPP-9329? Also, would you please share with me a test case of MPP-9329?

**Comment by jimmyyih** [comment] 2016-01-07 00:12
Hello LJoNe,

Unfortunately, I'm not as knowledgeable in this particular area but digging out information should be easy.  GIN has been disabled in GPDB since the 4.0.0.0 release back in 2010.  The specific JIRA MPP-9329 itself actually doesn't give much information on why the decision was made.  A small chat I had with an old Greenplum dev mentioned that it might have been due to GIN not working nicely with the file replication feature that was going out in GPDB 4.0.0.0 so GIN was disabled until further investigation.  Some other JIRAs around that time related to GIN somewhat confirm this as well.

From an old JIRA relative to GIN and FileRep, they have reproduction steps as outlined:
1. Put the cluster into ChangeTracking mode
2. Run mkcheck (this is a private internal testsuite)
3. Run gprecoverseg
4. Wait for system to resync
5. Run checkmirrorseg

Some relevant JIRA comments (copy/paste with names removed):
This actually make the system unusable and weird thing about this crash is it does not update catalog tables about segment pair going down. No evidence in gp_configuration_history as to what happened to other two segments which were in cl.  After this crash segments that were up and running in cl also goes down and prober never gets notified about the crash and hence did not update catalog.

Just realized its kind of double fault so prober might not detect double faults in system. There are only 2P+2M to start with. While in CL mirrors were down and primary segments were in cl. After this crash primary segments also crashed so prober has no way to identify this. i believe this is by design will check with <name removed>.

Please note that all this information is from 2010 and there have been significant changes to FileRep and GPDB in general since then.  Let us know if you need any other information.  I believe other developers may be more knowledgeable on this topic.

**Comment by ivannovick** [comment] 2016-01-07 00:16
I think we need to try to re-enable GIN index and make sure we have good test cases to ensure its working with node failure and HA... its a critical feature we are needing it

**Comment by LJoNe** [comment] 2016-01-07 02:34
thanks very much. @jimmyyih I am going to  test the scene by your description. BTW, would you please provide me with  more test cases or test scenes?

**Comment by jimmyyih** [comment] 2016-01-11 22:15
Hmm, another scenario could be using GIN indexes with AO/CO tables especially since append-only was changed recently in late 2014 to append-optimized.

**Comment by ashwinstar** [comment] 2016-08-12 07:10
@LJoNe How did the experiments go to make GIN work, please feel free to post the patch if you have it working based on above inputs. Seems mostly this issue can be closed as intended inputs were received.

**Comment by LJoNe** [comment] 2016-08-19 06:56
@ashwinstar my patch worked just fine in my project and it solved my problem. but due to restriction i'm afraid i cannot share it right now,sorry. Thanks jimmyyih again. Close this issue .

**Closed** 2016-08-19 06:56 UTC

**Comment by giaconiamark** [comment] 2017-04-21 21:32
So, is it possible to make GIN indexes work now? Has anything changed that allows this patch to go out?

**Comment by danielgustafsson** [comment] 2017-04-24 10:31
GIN indexes will not be enabled in the 5.0.0 release we're currently working towards (which is nearing beta), I hope we can make progress during the  Greenplum 6 cycle.

**Comment by giaconiamark** [comment] 2018-04-10 14:00
Are GIN text indexes available now?

**Comment by ivannovick** [comment] 2018-04-10 15:44
They should be enabled in MASTER branch now, want to give it a try?
