### ISSUE TITLE
ERROR:  no relation entry for relid 4 (relnode.c:246)

### ISSUE THREAD

**Issue by zhbp366** [greenplum-db/gpdb#7357] opened 2019-04-04 02:29 UTC
### Greenplum version or build
6.x
### OS version and uname -a
centos 7.5
### Expected behavior
no errors
### Actual behavior
ERROR:  no relation entry for relid 4 (relnode.c:246)
### Step to reproduce the behavior

CREATE CAST (integer AS text) WITH  inout  as IMPLICIT;

CREATE TABLE imp_zixun_baodan_detail_v13 (
    xh character varying(61),
    khmc character varying(2000),
    cjsj character varying(62),
    rq character varying(63),
    cjr character varying(50),
    ywlx1 character varying(51),
    ywlx2 character varying(52),
    ywlx3 character varying(53),
    jxfs character varying(54),
    province character varying(55),
    city character varying(56),
    mobile character varying(501),
    gdnr character varying(5000),
    bdlx character varying(57),
    shywlx character varying(61),
    djr character varying(58),
    djbm character varying(59),
    gdlx character varying(60),
    dqclr character varying(64),
    tslx character varying(150),
    tsyy character varying(2050),
    oper_id character varying(32),
    excel_line character varying(30),
    dt character varying(10),
    gdh character varying(2001),
    gdzt character varying(2002),
    qmsid character varying(2003),
    zxlx character varying(201),
    sfbd character varying(202)
) DISTRIBUTED BY (dt);

CREATE TABLE mid_es_ronglian (
    sid character varying(255) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    sessionid character varying ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    start_time text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    end_time text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    his_time text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    his_type character varying(10) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    platform character varying(20) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    kefu_user character varying(100) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    deal_status character varying(20) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    message text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    area character varying(255) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    ip character varying(255) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    fromurl text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    urltitle text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    sname character varying(255) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    sid_status character varying(20) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    seosource character varying(50) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    seokeywords character varying(255) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    finishreason character varying(30) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    sessionvistorid text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    vistorid text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    dt text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576)
)
WITH (appendonly=true, orientation=column, compresstype=zlib, compresslevel=3, blocksize=1048576) DISTRIBUTED BY (sid);

CREATE TABLE dm_page_analytics_newvisitor (
    dt character varying(8) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    logtimestr character varying(16) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    reqid character varying(48) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    vistoridnew character(1) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    url text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    referrer text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    vistorid character varying(48) ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576),
    jsonstr text ENCODING (compresstype=zlib,compresslevel=3,blocksize=1048576)
)
WITH (appendonly=true, orientation=column, compresstype=zlib, compresslevel=3, blocksize=1048576) DISTRIBUTED BY (vistorid);

CREATE TABLE imp_channels_config (
    rq text,
    no text,
    url text,
    chanel_source text,
    channel_name text,
    oper_id character varying(32),
    excel_line character varying(30),
    dt character varying(10)
) DISTRIBUTED BY (rq);

 CREATE TABLE ods_web_page_visit (
    dt character varying(8),
    log_source character varying(20),
    logtimestr character varying(14),
    reqid character varying(40),
    xforwardfor character varying(500),
    xrealip character varying(20),
    xrealip_desc character varying(60),
    sessionvisitorid character varying(40),
    sessionvistoridnew character varying(2),
    visitorid character varying(40),
    vistoridnew character varying(2),
    browserinfo character varying(200),
    ozuid character varying(20),
    halfhourfirstvisit character varying(10),
    wtoipsessionid character varying(40),
    useragent character varying(400),
    domain character varying(40),
    url character varying(4000),
    title character varying(1000),
    referrer character varying(4000),
    sh character varying(10),
    sw character varying(10),
    cd character varying(10),
    lang character varying(10),
    _locationhash character varying(4000),
    _locationhref character varying(4000),
    _locationsearch character varying(4000),
    _locationurl character varying(4000)
) DISTRIBUTED BY (reqid);

select channel_name,order_cnt,finish_cnt,rate,pv,uv from  ( 
WITH 
 t_work_order AS (
	SELECT
		qmsid  AS m7_sid,
	case when gdzt ='ok' then 1 else 0 end   is_finish,
	gdh AS order_no
from imp_zixun_baodan_detail_v13
	where  dt >= '20190327'
	AND  dt <= '20190402'
),
 t_dialogue AS (
	SELECT
		m7.sessionvistorid,
		sid,
		vistorid
	FROM
		mid_es_ronglian m7
		,t_work_order wo
	WHERE m7.sid=wo.m7_sid
	and
		m7.sessionvistorid IS NOT NULL
	GROUP BY
		m7.sessionvistorid,
		sid,
		vistorid
),
T_NEWVISITOR AS
(
SELECT url,r.vistorid
FROM 
dm_page_analytics_newvisitor r
,t_dialogue D
WHERE r.vistorid=D.vistorid
and 
 r.dt >= '20190327'
	AND r.dt <= '20190402'
	AND vistoridnew = 1
)
,
t_visitor_channel AS (
	SELECT
		coalesce(C .channel_name,r.url) channel_name,
		r.vistorid,
		r.url
	FROM
	 T_NEWVISITOR r
	LEFT JOIN
	imp_channels_config C
	ON r.url LIKE '%' || C .url || '%'
	GROUP BY
		coalesce(C .channel_name,r.url),
		r.vistorid,
		r.url
),
 t_traffic_channel AS (
	SELECT
		channel_name,
		SUM (pv) pv,
		SUM (uv) uv
	FROM
		(
			SELECT
				C .channel_name,
				r.dt dt,
				COUNT (r.reqid) pv,
				COUNT (DISTINCT r .visitorid) uv
			FROM
				t_visitor_channel C
			LEFT JOIN ods_web_page_visit r ON C .url = r.url
			AND r.dt >= '20190327'
			AND r.dt <= '20190402'
			GROUP BY
				channel_name 
				,r.dt
		) T
	GROUP BY
		channel_name
),

 t_ord_channel AS (
	SELECT
		vc.channel_name,
		COUNT (DISTINCT order_no) order_cnt
		,
		COUNT (
			DISTINCT CASE
			WHEN is_finish = 1 THEN
				order_no
			END
		) finish_cnt 
	FROM
		t_visitor_channel vc 
	LEFT JOIN t_dialogue dia
	ON vc.vistorid = dia.vistorid
	LEFT JOIN t_work_order ord ON dia.sid = ord.m7_sid
	GROUP BY
		vc.channel_name
) 
SELECT
	T .channel_name,
	T .pv,
	T .uv,
	vc.order_cnt 
	,
	vc.finish_cnt 
	,case when uv=0 then 0 else order_cnt*100/uv end rate
FROM
	t_traffic_channel T 
LEFT JOIN t_ord_channel vc
ON T .channel_name = vc.channel_name) t where 1=1   order by 1,2,3,4,5,6;

**Comment by Eulerizeit** [comment] 2019-04-04 02:55
Just a copy of your DDL and query

```SQL
CREATE CAST (integer AS text) WITH inout as IMPLICIT;

CREATE TABLE imp_zixun_baodan_detail_v13 (
	xh character varying(61),
	khmc character varying(2000),
	cjsj character varying(62),
	rq character varying(63),
	cjr character varying(50),
	ywlx1 character varying(51),
	ywlx2 character varying(52),
	ywlx3 character varying(53),
	jxfs character varying(54),
	province character varying(55),
	city character varying(56),
	mobile character varying(501),
	gdnr character varying(5000),
	bdlx character varying(57),
	shywlx character varying(61),
	djr character varying(58),
	djbm character varying(59),
	gdlx character varying(60),
	dqclr character varying(64),
	tslx character varying(150),
	tsyy character varying(2050),
	oper_id character varying(32),
	excel_line character varying(30),
	dt character varying(10),
	gdh character varying(2001),
	gdzt character varying(2002),
	qmsid character varying(2003),
	zxlx character varying(201),
	sfbd character varying(202)
) DISTRIBUTED BY (dt);

CREATE TABLE mid_es_ronglian (
  sid character varying(255) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  sessionid character varying ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  start_time text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  end_time text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  his_time text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  his_type character varying(10) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  platform character varying(20) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  kefu_user character varying(100) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  deal_status character varying(20) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  message text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  area character varying(255) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  ip character varying(255) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  fromurl text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  urltitle text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  sname character varying(255) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  sid_status character varying(20) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  seosource character varying(50) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  seokeywords character varying(255) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  finishreason character varying(30) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  sessionvistorid text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  vistorid text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  dt text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  )
) WITH (
  appendonly = true, orientation = column, 
  compresstype = zlib, compresslevel = 3, 
  blocksize = 1048576
) DISTRIBUTED BY (sid);


CREATE TABLE dm_page_analytics_newvisitor (
  dt character varying(8) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  logtimestr character varying(16) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  reqid character varying(48) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  vistoridnew character(1) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  url text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  referrer text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  vistorid character varying(48) ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  ), 
  jsonstr text ENCODING (
    compresstype = zlib, compresslevel = 3, 
    blocksize = 1048576
  )
) WITH (
  appendonly = true, orientation = column, 
  compresstype = zlib, compresslevel = 3, 
  blocksize = 1048576
) DISTRIBUTED BY (vistorid);

CREATE TABLE imp_channels_config (
	rq text,
	no text,
	url text,
	chanel_source text,
	channel_name text,
	oper_id character varying(32),
	excel_line character varying(30),
	dt character varying(10)
) DISTRIBUTED BY (rq);

CREATE TABLE ods_web_page_visit (
	dt character varying(8),
	log_source character varying(20),
	logtimestr character varying(14),
	reqid character varying(40),
	xforwardfor character varying(500),
	xrealip character varying(20),
	xrealip_desc character varying(60),
	sessionvisitorid character varying(40),
	sessionvistoridnew character varying(2),
	visitorid character varying(40),
	vistoridnew character varying(2),
	browserinfo character varying(200),
	ozuid character varying(20),
	halfhourfirstvisit character varying(10),
	wtoipsessionid character varying(40),
	useragent character varying(400),
	domain character varying(40),
	url character varying(4000),
	title character varying(1000),
	referrer character varying(4000),
	sh character varying(10),
	sw character varying(10),
	cd character varying(10),
	lang character varying(10),
	_locationhash character varying(4000),
	_locationhref character varying(4000),
	_locationsearch character varying(4000),
	_locationurl character varying(4000)
) DISTRIBUTED BY (reqid);

select 
  channel_name, 
  order_cnt, 
  finish_cnt, 
  rate, 
  pv, 
  uv 
from 
  (
    WITH t_work_order AS (
      SELECT 
        qmsid AS m7_sid, 
        case when gdzt = 'ok' then 1 else 0 end is_finish, 
        gdh AS order_no 
      from 
        imp_zixun_baodan_detail_v13 
      where 
        dt >= '20190327' 
        AND dt <= '20190402'
    ), 
    t_dialogue AS (
      SELECT 
        m7.sessionvistorid, 
        sid, 
        vistorid 
      FROM 
        mid_es_ronglian m7, 
        t_work_order wo 
      WHERE 
        m7.sid = wo.m7_sid 
        and m7.sessionvistorid IS NOT NULL 
      GROUP BY 
        m7.sessionvistorid, 
        sid, 
        vistorid
    ), 
    T_NEWVISITOR AS (
      SELECT 
        url, 
        r.vistorid 
      FROM 
        dm_page_analytics_newvisitor r, 
        t_dialogue D 
      WHERE 
        r.vistorid = D.vistorid 
        and r.dt >= '20190327' 
        AND r.dt <= '20190402' 
        AND vistoridnew = 1
    ), 
    t_visitor_channel AS (
      SELECT 
        coalesce(C.channel_name, r.url) channel_name, 
        r.vistorid, 
        r.url 
      FROM 
        T_NEWVISITOR r 
        LEFT JOIN imp_channels_config C ON r.url LIKE '%' || C.url || '%' 
      GROUP BY 
        coalesce(C.channel_name, r.url), 
        r.vistorid, 
        r.url
    ), 
    t_traffic_channel AS (
      SELECT 
        channel_name, 
        SUM (pv) pv, 
        SUM (uv) uv 
      FROM 
        (
          SELECT 
            C.channel_name, 
            r.dt dt, 
            COUNT (r.reqid) pv, 
            COUNT (DISTINCT r.visitorid) uv 
          FROM 
            t_visitor_channel C 
            LEFT JOIN ods_web_page_visit r ON C.url = r.url 
            AND r.dt >= '20190327' 
            AND r.dt <= '20190402' 
          GROUP BY 
            channel_name, 
            r.dt
        ) T 
      GROUP BY 
        channel_name
    ), 
    t_ord_channel AS (
      SELECT 
        vc.channel_name, 
        COUNT (DISTINCT order_no) order_cnt, 
        COUNT (
          DISTINCT CASE WHEN is_finish = 1 THEN order_no END
        ) finish_cnt 
      FROM 
        t_visitor_channel vc 
        LEFT JOIN t_dialogue dia ON vc.vistorid = dia.vistorid 
        LEFT JOIN t_work_order ord ON dia.sid = ord.m7_sid 
      GROUP BY 
        vc.channel_name
    ) 
    SELECT 
      T.channel_name, 
      T.pv, 
      T.uv, 
      vc.order_cnt, 
      vc.finish_cnt, 
      case when uv = 0 then 0 else order_cnt * 100 / uv end rate 
    FROM 
      t_traffic_channel T 
      LEFT JOIN t_ord_channel vc ON T.channel_name = vc.channel_name
  ) t 
where 
  1 = 1 
order by 
  1, 2, 3, 4, 5, 6
;
```

**Comment by d** [comment] 2019-08-16 16:49
Hi @zhbp366 ,
Thanks for reporting this issue! We tried your steps and couldn't reproduce the issue on [latest master](https://github.com/greenplum-db/gpdb/commit/8181972e4faa507af758d23ad0a1bde97a5ccdd2). We're closing this for now. If you find that this is still an issue, please leave a comment and we'll reopen the issue.

Thanks,
Jesse and Ivan (@leskin-in )

**Closed by d** 2019-08-16 16:49 UTC
Labels: needs: reproduction, status: triage
