### ISSUE TITLE
auto_explain causes segmentation fault when Greenplum Admin Utilities (gpstop/gpstate/gpinitstandby) are run

### ISSUE THREAD

**Issue by CodeGood** [greenplum-db/gpdb#9982] opened 2020-04-22 21:19 UTC
### Description

The Greenplum utilities like gpstate fail with the following error

```
20200422:21:34:28:031322 gpstate:arc-classichanossl-525:gpadmin-[CRITICAL]:-gpstate failed. (Reason='error 'server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.)
```
However I am able to access the database through psql, and all my SQL queries are executing as expected

### Expected behavior

gpstate should return the cluster status

### Actual behavior

gpstate exits with error, and pg_log on master segment shows a segmentation fault (output of gpstate and relevant log snippet from master segment are present below)

### Step to reproduce the behavior

1. Add auto_explain to shared_preload_libraries
2. Set auto_explain.log_min_duration to 0 so that it explains all statements (full auto-explain config below) and restart the Greenplum cluster
3. Put the cluster under mild load for a soak testing (I can reproduce the issue only after 6-10 hours, not immediately after setting the configs)
4. Attempt a gpstate or gpstop

### Greenplum version or build

```
greenplum=# SELECT version();
-[ RECORD 1 ]-------------------------------------
version | PostgreSQL 9.4.24 (Greenplum Database 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Oct 11 2019 18:47:35
```
### OS version and uname -a

AWS Linux 2 .

```
[gpadmin@arc-classichanossl-525 ~]$ uname -a
Linux arc-classichanossl-525.devservers.scalegrid.io 4.14.173-137.228.amzn2.x86_64 #1 SMP Thu Mar 19 16:50:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Installation information ( pg_config )

```
[gpadmin@arc-classichanossl-525 ~]$ pg_config
BINDIR = /usr/local/greenplum-db-6.0.1/bin
DOCDIR = /usr/local/greenplum-db-6.0.1/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.0.1/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.0.1/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.0.1/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.0.1/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.0.1/lib
PKGLIBDIR = /usr/local/greenplum-db-6.0.1/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.0.1/share/locale
MANDIR = /usr/local/greenplum-db-6.0.1/man
SHAREDIR = /usr/local/greenplum-db-6.0.1/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.0.1/etc/postgresql
PGXS = /usr/local/greenplum-db-6.0.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--prefix=/usr/local/greenplum-db-oss' '--mandir=/usr/local/greenplum-db-oss/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.0.1/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.0.1/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-oss/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.0.1/lib
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.0.1/lib
VERSION = PostgreSQL 9.4.24
```

### auto_explain configuration on master

```
auto_explain.log_format=json
auto_explain.log_verbose=true
auto_explain.log_min_duration=0
auto_explain.log_analyze=true
```

Note - auto_explain is not loaded on the segments

### gpstate output

```
[gpadmin@arc-classichanossl-525 ~]$ gpstate
20200422:21:34:27:031322 gpstate:arc-classichanossl-525:gpadmin-[INFO]:-Starting gpstate with args:
20200422:21:34:27:031322 gpstate:arc-classichanossl-525:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc'
20200422:21:34:27:031322 gpstate:arc-classichanossl-525:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.0.1 build commit:053a66ae19cd7301ec8c8910ed85ec2c20ad60cc) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Oct 11 2019 18:47:35'
20200422:21:34:27:031322 gpstate:arc-classichanossl-525:gpadmin-[INFO]:-Obtaining Segment details from master...
20200422:21:34:28:031322 gpstate:arc-classichanossl-525:gpadmin-[CRITICAL]:-gpstate failed. (Reason='error 'server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
' in '
        SELECT dbid, content, role, preferred_role, mode, status,
        hostname, address, port, datadir
        FROM pg_catalog.gp_segment_configuration
        ORDER BY content, preferred_role DESC
        '') exiting...
```

### pg_log from Greenplum Master
```

2020-04-22 21:08:55.280065 UTC,"gpadmin","template1",p29204,th-1531618048,"127.0.0.1","41050",2020-04-22 21:08:55 UTC,0,con25,cmd11,seg-1,,,,sx1,"LOG","00000","statement:
        SELECT dbid, content, role, preferred_role, mode, status,
        hostname, address, port, datadir
        FROM pg_catalog.gp_segment_configuration
        ORDER BY content, preferred_role DESC",,,,,,"
        SELECT dbid, content, role, preferred_role, mode, status,
        hostname, address, port, datadir
        FROM pg_catalog.gp_segment_configuration
        ORDER BY content, preferred_role DESC
        ",0,,"postgres.c",1617,
2020-04-22 21:08:55.376062 UTC,,,p29204,th0,,,2020-04-22 21:08:55 UTC,0,con25,cmd12,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f21a11297e0 libpthread.so.0 <symbol not found> + 0xa11297e0
2    0x655c22 postgres ExplainPrintPlan (explain.c:744)
3    0x7f2195c613f3 auto_explain.so <symbol not found> + 0x95c613f3
4    0x66b8be postgres PortalCleanup (discriminator 2)
5    0xa2e69c postgres PortalDrop (portalmem.c:536)
6    0x88a930 postgres <symbol not found> (postgres.c:1809)
7    0x88d0c5 postgres PostgresMain (postgres.c:5214)
"
2020-04-22 21:08:55.454979 UTC,,,p6957,th-1531618048,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 29204) was terminated by signal 11: Segmentation fault","Failed process was running:
        SELECT dbid, content, role, preferred_role, mode, status,
        hostname, address, port, datadir
        FROM pg_catalog.gp_segment_configuration
        ORDER BY content, preferred_role DESC",,,,,,0,,"postmaster.c",3962,
2020-04-22 21:08:55.455025 UTC,,,p6957,th-1531618048,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3679,                                                                                                                                                                 
```

**Comment by CodeGood** [comment] 2020-04-22 21:51
Here is the [core dump](https://github.com/greenplum-db/gpdb/files/4519158/auto_explain.seg.fault.core.dump.zip) if that helps. (This is a test cluster, with no proprietary data)

**Comment by wuj21** [comment] 2021-06-02 02:33
@CodeGood Greenplum 6.0.1 is a very old build. Would you please try the latest 6.16?

**Comment by lij55** [comment] 2022-03-31 10:31
I couldn't reproduce it on 6.19.0. closing the issue.

**Closed by lij55** 2022-03-31 10:31 UTC
Labels: version: 6X_STABLE
