### ISSUE TITLE
gporca optimizer max()

### ISSUE THREAD

**Issue by zj511025** [greenplum-db/gpdb#10508] opened 2020-07-23 01:09 UTC
### Greenplum version or build
greenplum 6.7.1
### OS version and uname -a
centos7.6+
### Step to reproduce the behavior
create table xxx
(
a int,
b varchar(100),
c varchar(100),
primary key(a)
)
distributed by (a);

start psql
\timing on

insert into xxx 2000000000 rows;

one:
set  optimizer=on;
select max(a) from xxx;
use time > 180s

tow:
set  optimizer=off;
select max(a) from xxx;
use time < 100ms

**Comment by asimrp** [comment] 2020-07-23 06:56
@zj511025 what happens if you analyze the table after insert?

**Comment by zj511025** [comment] 2020-07-23 12:21
执行查询 select  max（a）from xxx；在启用gporca优化的情况下非常慢，耗时3分钟，而关闭gporca优化之后，非常快，毫秒级返回。由于表上创建了a字段的btree索引，正常情况下，无论哪种优化器，这个查询都应该非常的快。故我认为gporca优化器，针对select max（）的查询，是不是有bug？

**Comment by kainwen** [comment] 2020-07-23 12:41
> 执行查询 select max（a）from xxx；在启用gporca优化的情况下非常慢，耗时3分钟，而关闭gporca优化之后，非常快，毫秒级返回。由于表上创建了a字段的btree索引，正常情况下，无论哪种优化器，这个查询都应该非常的快。故我认为gporca优化器，针对select max（）的查询，是不是有bug？

Please paste the plan for orca and planner here. You can paste the following SQL's output in your env:

```sql
create table xxx
(
a int,
b varchar(100),
c varchar(100),
primary key(a)
)
distributed by (a);

start psql
\timing on

insert into xxx 2000000000 rows;

one:
set optimizer=on;
explain select max(a) from xxx;
select max(a) from xxx;
```

**Comment by chrishajas** [comment] 2020-07-23 16:08
This optimization currently does not exist in Orca, though it does in planner, see https://github.com/greenplum-db/gpdb/pull/4786.

**Comment by zj511025** [comment] 2020-07-24 01:39
和#4786中描述一样。explain select max(a) from xxx; 在orca中是顺序扫描，在非orca中是索引扫描。

**Comment by zj511025** [comment] 2020-07-24 01:59
> 执行查询 select max（a）from xxx；在启用gporca优化的情况下非常慢，耗时3分钟，而关闭gporca优化之后，非常快，毫秒级返回。由于表上创建了a字段的btree索引，正常情况下，无论哪种优化器，这个查询都应该非常的快。故我认为gporca优化器，针对select max（）的查询，是不是有bug？
> 
> Please paste the plan for orca and planner here. You can paste the following SQL's output in your env:
> create table xxx
> (
> a int,
> b varchar(100),
> c varchar(100),
> primary key(a)
> )
> distributed by (a);
> 
> start psql
> \timing on
> 
> insert into xxx 2000000000 rows;
> 
> one:
> set optimizer=on;
> explain select max(a) from xxx;
> select max(a) from xxx;

很抱歉，我们内外网不通，不好贴

**Comment by kainwen** [comment] 2020-07-24 02:03
> > 执行查询 select max（a）from xxx；在启用gporca优化的情况下非常慢，耗时3分钟，而关闭gporca优化之后，非常快，毫秒级返回。由于表上创建了a字段的btree索引，正常情况下，无论哪种优化器，这个查询都应该非常的快。故我认为gporca优化器，针对select max（）的查询，是不是有bug？
> > Please paste the plan for orca and planner here. You can paste the following SQL's output in your env:
> > create table xxx
> > (
> > a int,
> > b varchar(100),
> > c varchar(100),
> > primary key(a)
> > )
> > distributed by (a);
> > start psql
> > \timing on
> > insert into xxx 2000000000 rows;
> > one:
> > set optimizer=on;
> > explain select max(a) from xxx;
> > select max(a) from xxx;
> 
> 很抱歉，我们内外网不通，不好贴

The root cause is clear. ORCA does not consider index scan for max.

For workaround, you can use planner if you find very slow query due to this reason.

**Comment by iwanttobepowerful** [comment] 2022-08-19 02:40
37169.450 ms vs 407.354 ms

orca's plan:
```
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=0.00..431.00 rows=1 width=4)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=4)
         ->  Partial Aggregate  (cost=0.00..431.00 rows=1 width=4)
               ->  Seq Scan on xxx  (cost=0.00..431.00 rows=1 width=4)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)
```

pg's plan:
```
                                                   QUERY PLAN
-----------------------------------------------------------------------------------------------------------------
 Result  (cost=0.22..0.23 rows=1 width=4)
   InitPlan 1 (returns $0)  (slice1)
     ->  Limit  (cost=564671.14..0.22 rows=1 width=4)
           ->  Gather Motion 3:1  (slice2; segments: 3)  (cost=0.19..564671.14 rows=20000000 width=4)
                 Merge Key: xxx.a
                 ->  Index Only Scan Backward using xxx_pkey on xxx  (cost=0.19..298004.47 rows=6666667 width=4)
                       Index Cond: (a IS NOT NULL)
 Optimizer: Postgres query optimizer
(8 rows)
```

**Comment by chrishajas** [comment] 2023-12-18 23:28
Fixed with https://github.com/greenplum-db/gpdb/pull/16480, thanks for the report!

**Closed by chrishajas** 2023-12-18 23:28 UTC
Labels: type: enhancement, area: gporca
