### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by hbzxcym** [greenplum-db/gpdb#8411] opened 2019-08-19 02:48 UTC
### Greenplum version or build
5.17
### OS version and uname -a
3.10.0-514.el7.x86_64 1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

CPU memory  128G、 2 CPU、32logical core 
### Installation information ( pg_config )
Master config:
gp_resqueue_memory_policy='auto'
memory_spill_ratio=20
gp_vmem_protect_limit=20480
effective_cache_size=20480MB
gp_workfile_limit_files_per_query=100000
gp_workfile_limit_per_segment=89128960
max_statement_mem=4096MB
statement_mem=2048MB
shared_buffers=10240MB
gp_resqueue_priority_cpucores_per_segment=25

Segment config:
gp_resqueue_memory_policy='auto'
emory_spill_ratio=20
gp_vmem_protect_limit=20480
effective_cache_size=20480MB
gp_workfile_limit_files_per_query=100000
gp_workfile_limit_per_segment=89128960
max_statement_mem=4096MB
statement_mem=2048MB
shared_buffers=10240MB
gp_resqueue_priority_cpucores_per_segment=4

### Step to reproduce the behavior
run 15 SQL， I will get

![image](https://user-images.githubusercontent.com/4327485/63236015-add32d80-c26e-11e9-9914-cc56a78db51c.png)

**Comment by yydzero** [comment] 2019-08-19 04:02
Thanks for reporting. Could you please provide:

1) System memory usage using top
2) Would you please paste 'explain plan of SQL 15'

**Comment by gaos1** [comment] 2019-08-19 09:21
please also check if your gp_vmem_protect_limit is set properly. you can refer to https://greenplum.org/calc/.

how many concurrent queries are you running? 

please upload sql_20.sql and related table schemas, which are helpful to check why this query needs so much memory.

**Comment by hbzxcym** [comment] 2019-08-22 05:44
**when cpu usage  up to 95%**
![image](https://user-images.githubusercontent.com/4327485/63488298-09a4ed00-c4e1-11e9-9c4f-8d21fdf92a73.png)

 **system will get  "out of memory"**
 Logging memory usage for reaching system memory limit",,,,,,,0,,,,
2019-08-22 12:13:00.369186 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd1,seg-1,,dx26788,,sx1,"LOG","00000","Planner produced plan :0",,,,,,"SELECT sess_id, current_query FROM pg_stat_activity;",0,,"orca.c",60,
2019-08-22 12:13:00.388623 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","Logging memory usage for reaching system memory limit",,,,,,,0,,,,
2019-08-22 12:13:00.388674 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: session_id, is_runaway, qe_count, active_qe_count, dirty_qe_count, vmem_mb, runaway_vmem_mb, runaway_command_cnt
",,,,,,,0,,,,
2019-08-22 12:13:00.388710 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: 24739, 0, 1, 1, -1, 34, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.388737 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: 24734, 0, 1, 1, -1, 104, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.388763 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: 24707, 0, 1, 0, -1, 1, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389610 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: 23009, 0, 1, 0, -1, 5, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389635 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","session_state: 22779, 0, 1, 0, -1, 17, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389660 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: account_name, account_id, parent_account_id, quota, peak, allocated, freed, current
",,,,,,,0,,,,
2019-08-22 12:13:00.389689 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Vmem, -1, -1, 0, 69206016, 69206016, 0, 69206016
",,,,,,,0,,,,
2019-08-22 12:13:00.389716 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Peak, -2, -2, 0, 36030760, 36030760, 0, 36030760
",,,,,,,0,,,,
2019-08-22 12:13:00.389742 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Root, 1, 1, 0, 0, 0, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389766 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: SharedHeader, 2, 1, 0, 11040, 16720, 5680, 11040
",,,,,,,0,,,,
2019-08-22 12:13:00.389794 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Rollover, 3, 1, 0, 1445568, 1420032, 0, 1420032
",,,,,,,0,,,,
2019-08-22 12:13:00.389821 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: MemAcc, 4, 1, 0, 1536, 1536, 0, 1536
",,,,,,,0,,,,
2019-08-22 12:13:00.389846 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: X_Alien, 5, 1, 0, 0, 0, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389872 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Top, 9, 1, 0, 0, 0, 0, 0
",,,,,,,0,,,,
2019-08-22 12:13:00.389896 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Main, 10, 9, 0, 100432, 604328, 530784, 73544
",,,,,,,0,,,,
2019-08-22 12:13:00.389922 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Optimizer, 11, 10, 0, 10816304, 12600096, 12296640, 303456
",,,,,,,0,,,,
2019-08-22 12:13:00.389949 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","memory: Planner, 12, 10, 0, 241168, 1420288, 1206176, 214112
",,,,,,,0,,,,

2019-08-22 12:13:00.390922 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 2048, 680, 2048, 0, CacheMemoryContext/pg_authid_rolresqueue_index
",,,,,,,0,,,,
@
/VM
2019-08-22 12:13:00.392628 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 24576, 5712, 24576, 0, MdSmgr
",,,,,,,0,,,,
2019-08-22 12:13:00.392653 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 24576, 15768, 24576, 0, LOCALLOCK hash
",,,,,,,0,,,,
2019-08-22 12:13:00.392679 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 8192, 8168, 8192, 0, MetricsCollectorMemCtxt
",,,,,,,0,,,,
2019-08-22 12:13:00.392705 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 104104, 3672, 104104, 0, Timezones
",,,,,,,0,,,,
2019-08-22 12:13:00.392731 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 1040384, 488328, 1057832, 17448, Postmaster
",,,,,,,0,,,,
2019-08-22 12:13:00.392757 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 8192, 6552, 8192, 0, MemoryAccountMemoryContext
",,,,,,,0,,,,
2019-08-22 12:13:00.392783 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"LOG","00000","context: 1, 8192, 8056, 8192, 0, ErrorContext
",,,,,,,0,,,,
2019-08-22 12:13:00.392809 CST,"gpmon","gpperfmon",p18815,th-301467520,"[local]",,2019-08-22 12:13:00 CST,0,con24739,cmd2,seg-1,,dx26788,,sx1,"ERROR","53400","**Out of memory","VM protect failed to allocate 33554480 bytes from system, VM Protect 11917 MB available**",,,,,"SELECT sess_id, current_query FROM pg_stat_activity;",0,,"memprot.c",314,

**when I connect gpdb this time ,  gpdb in "recovery" and cannot connect .**

**Comment by gaos1** [comment] 2019-08-26 23:14
it is hard to figure out the root cause from these messages. could you answer our questions above and also upload one entire log file from master and one segment at least?

**Comment by ashwinstar** [comment] 2020-01-01 01:11
Based on current info @hbzxcym can't help on this issue. Only way we would be able to investigate is please can provide repro for the same and answers to previously asked questions. I am closing the issue for now, given on activity since long time,

**Closed by ashwinstar** 2020-01-01 01:11 UTC
Labels: needs: reproduction
