### ISSUE TITLE
server closed the connection unexpectedly

### ISSUE THREAD

**Issue by luowencai** [greenplum-db/gpdb#9906] opened 2020-04-13 03:02 UTC
### Greenplum version or build 
select version();
                                                                                               version                                                                                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.5.0 build commit:27520b0e901cefe748684c02e5155fb015cd5cc2) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 18 2020 23:06:28
### Step to reproduce the behavior
we meet this error unexpectedly, and it recover after a few minutes.
`<Unknown error>>: 7 ERROR:  Error on receive from seg6 slice1 173.16.1.160:35100 pid=32493: server closed the connection unexpectedly
DETAIL:  
#011This probably means the server terminated abnormally
#011before or while processing the request.`
and the system messages was 
`kernel: traps: postgres[6598] trap divide error ip:8215df sp:7ffdc96f2e30 error:0 in postgres[400000+9ee000]`
Just want to know the reason,How can we solve it.thx

**Comment by kainwen** [comment] 2020-04-13 03:04
Would you please provide the related logs and detailed reproduce-steps, or the coredump?

**Comment by luowencai** [comment] 2020-04-13 03:21
After watching the pg_log,finded the follow error message
`Feature not supported: DISTINCT operation on a subset of target list columns`

`4492",2020-04-13 10:34:04 CST,0,con345965,cmd18,seg-1,,dx5670597,,sx1,"ERROR","58M01","Error on receive from seg6 slice1 173.16.1.160:35100 pid=32493: server closed the connection unexpectedly","
	This probably means the server terminated abnormally
	before or while processing the request.",,,,,"`

**Comment by xiong-gang** [comment] 2020-04-13 03:49
The coredump file and detailed logs should be on seg6, could you please check that?

**Comment by luowencai** [comment] 2020-04-13 04:02
`2020-04-13 10:34:07.426518 CST,"job_owner","gpdata",p32504,th1838680192,"173.16.1.149","57718",2020-04-13 10:34:06 CST,39115302,con345971,cmd35,seg6,,dx5670578,x39115302,sx1,"LOG","00000","An exception was encountered during the execution of statement: insert into xxxxx.channel(channel_id.....) values((33,'FT','4399H",,,,,,,0,,,,
2020-04-13 10:34:09.256379 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","worker process: sweeper process (PID 6598) was terminated by signal 8: Floating point exception",,,,,,,0,,"postmaster.c",3955,
2020-04-13 10:34:09.256420 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3672,
2020-04-13 10:34:09.313456 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","all server processes terminated; reinitializing",,,,,,,0,,"postmaster.c",4207,
2020-04-13 10:34:11.024138 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","database system was interrupted; last known up at 2020-04-13 10:33:19 CST",,,,,,,0,,"xlog.c",6437,
2020-04-13 10:34:11.025456 CST,"gpadmin2",,p32532,th1838680192,"173.16.1.161","16752",2020-04-13 10:34:11 CST,0,,,seg6,,,,,"FATAL","57P03","the database system is in recovery mode","last replayed record at 0/0",,,,,,0,,"postmaster.c",2538,
2020-04-13 10:34:14.100467 CST,"gpadmin2",,p32545,th1838680192,"173.16.1.161","16754",2020-04-13 10:34:14 CST,0,,,seg6,,,,,"FATAL","57P03","the database system is in recovery mode","last replayed record at 0/0",,,,,,0,,"postmaster.c",2538,
2020-04-13 10:34:16.239427 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","database system was not properly shut down; automatic recovery in progress",,,,,,,0,,"xlog.c",6843,
2020-04-13 10:34:16.249104 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","redo starts at 4AA/B3A7E298",,,,,,,0,,"xlog.c",7109,
2020-04-13 10:34:16.822344 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","record with zero length at 4AA/BFB86AC8",,,,,,,0,,"xlog.c",4279,
2020-04-13 10:34:16.822393 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","redo done at 4AA/BFB86960",,,,,,,0,,"xlog.c",7371,
2020-04-13 10:34:16.822404 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","last completed transaction was at log time 2020-04-13 10:34:09.251795+08",,,,,,,0,,"xlog.c",7376,
2020-04-13 10:34:16.829677 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","end of transaction log location is 4AA/BFB86AC8",,,,,,,0,,"xlog.c",7427,
2020-04-13 10:34:18.844797 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","latest completed transaction id is 39115324 and next transaction id is 39115325",,,,,,,0,,"xlog.c",7715,
2020-04-13 10:34:18.862077 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","MultiXact member wraparound protections are now enabled",,,,,,,0,,"multixact.c",2619,
2020-04-13 10:34:18.862127 CST,,,p32531,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","database system is ready",,,,,,,0,,"xlog.c",7739,
2020-04-13 10:34:18.883956 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","starting background worker process ""sweeper process""",,,,,,,0,,"postmaster.c",6132,
2020-04-13 10:34:18.884484 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","PostgreSQL 9.4.24 (Greenplum Database 6.5.0 build commit:27520b0e901cefe748684c02e5155fb015cd5cc2) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 18 2020 23:05:38",,,,,,,0,,"postmaster.c",3258,
2020-04-13 10:34:18.884526 CST,,,p6585,th1838680192,,,,0,,,seg6,,,,,"LOG","00000","database system is ready to accept connections","PostgreSQL 9.4.24 (Greenplum Database 6.5.0 build commit:27520b0e901cefe748684c02e5155fb015cd5cc2) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 18 2020 23:05:38",,,,,,0,,"postmaster.c",3262,
2020-04-13 10:34:19.336117 CST,"gpadmin2",,p32575,th1838680192,"173.16.1.161","16756",2020-04-13 10:34:19 CST,0,,,seg6,,,,,"LOG","00000","standby ""gp_walreceiver"" is now the synchronous standby with priority 1",,,,,,,0,,"syncrep.c",558,`

**Comment by luowencai** [comment] 2020-04-13 04:35
our gcc
`gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`
if it`s the reason?

**Comment by luowencai** [comment] 2020-04-14 09:03
Am i need to update gcc to 6.4.0?

**Comment by luowencai** [comment] 2020-06-09 03:38
We meet this again:
```
2020-06-08 22:28:16.248424 CST,,,p23023,th459180160,,,,0,,,seg2,,,,,"LOG","00000","worker process: sweeper process (PID 23032) was terminated by signal 8: Floating point exception",,,,,,,0,,"postmaster.c",3960,
2020-06-08 22:28:16.248470 CST,,,p23023,th459180160,,,,0,,,seg2,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3677,
2020-06-08 22:28:16.303661 CST,,,p23023,th459180160,,,,0,,,seg2,,,,,"LOG","00000","all server processes terminated; reinitializing",,,,,,,0,,"postmaster.c",4212,
2020-06-08 22:28:17.692831 CST,"gpadmin2",,p11435,th459180160,"172.16.1.149","54770",2020-06-08 22:28:17 CST,0,,,seg2,,,,,"FATAL","57P03","the database system is in recovery mode","last replayed record at 0/0",,,,,,0,,"postmaster.c",2543,
2020-06-08 22:28:17.693437 CST,,,p11434,th459180160,,,,0,,,seg2,,,,,"LOG","00000","database system was interrupted; last known up at 2020-06-08 22:23:40 CST",,,,,,,0,,"xlog.c",6437,
2020-06-08 22:28:17.958330 CST,,,p11434,th459180160,,,,0,,,seg2,,,,,"LOG","00000","database system was not properly shut down; automatic recovery in progress",,,,,,,0,,"xlog.c",6843,
```

**Comment by hlinnaka** [comment] 2020-08-28 07:01
I believe this is a duplicate of https://github.com/greenplum-db/gpdb/issues/10381, closing.

**Closed by hlinnaka** 2020-08-28 07:01 UTC
