### ISSUE TITLE
volatile EquivalenceClass has no sortref

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#9076] opened 2019-11-20 14:56 UTC
### Greenplum version or build
5.0.0

### OS version and uname -a
CentOS Linux release 7.2 (Final)

### Step to reproduce the behavior
run err.txt（created by tableau） get ret : 
"psql:err.txt:57: ERROR:  volatile EquivalenceClass has no sortref (pathkeys.c:853)"

log as follow:
1    0x926e36 postgres errstart + 0x1f6
2    0x92890b postgres elog_finish + 0xab
3    0x75737e postgres <symbol not found> + 0x75737e
4    0x73f8d2 postgres <symbol not found> + 0x73f8d2
5    0x7403e5 postgres make_one_rel + 0x65
6    0x763e7a postgres query_planner + 0x22a
7    0x7668ff postgres <symbol not found> + 0x7668ff
8    0x768720 postgres subquery_planner + 0x710
9    0x768c37 postgres standard_planner + 0x167
10   0x769385 postgres planner + 0x145
11   0x80d92c postgres <symbol not found> + 0x80d92c
12   0x80ee82 postgres <symbol not found> + 0x80ee82
13   0x811254 postgres PostgresMain + 0x1a84
14   0x7b3fe6 postgres <symbol not found> + 0x7b3fe6
15   0x7b59e2 postgres PostmasterMain + 0xc52
16   0x4c833d postgres main + 0x39d
17   0x7f246b767b35 libc.so.6 __libc_start_main + 0xf5
18   0x4c88d1 postgres <symbol not found> + 0x4c88d1

Please find enclosed files : err.txt and schema.txt 

[err.txt](https://github.com/greenplum-db/gpdb/files/3869782/err.txt)
[schema.txt](https://github.com/greenplum-db/gpdb/files/3869787/schema.txt)

You can reproduce the problem.
By the way, there is no data in the cluster.

**Comment by lambgong** [comment] 2019-11-26 08:45
Anybody can help here?
I already upgrade to the latest 5X_STABLE，and the issue still exist!

**Comment by kainwen** [comment] 2019-11-26 08:56
I cannot reproduce the issue because of lack of the c code for the UDF.

Can you provide a minirepo?

**Comment by lambgong** [comment] 2019-11-26 09:42
What UDF?
Can you describe minirepo carefully

**Comment by lambgong** [comment] 2019-11-26 11:21
this sql can run on gp6

**Comment by lambgong** [comment] 2019-11-26 15:10
it seems that tableau use psqlodbc 0906 version driver to connect gp 5x.
Dose gp odbc dirver download for free?

**Comment by asimrp** [comment] 2019-12-03 04:15
@lambgong I tried your repro scripts on that latest Greenplum code and it worked.  The query in `err.txt` ran successfully without any error.

Note that a lot of fixes have been made even on 5X_STABBLE branch since 5.0.0.  Would you please consider upgrading your cluster to the latest 5X release and try again?

**Comment by asimrp** [comment] 2019-12-12 03:13
@lambgong did you get a chance to upgrade your 5X Greenplum cluster to the latest 5X release?

**Comment by kainwen** [comment] 2020-04-22 11:30
@xiong-gang 
Can the PR https://github.com/greenplum-db/gpdb/pull/9959 fix this?

**Comment by xiong-gang** [comment] 2020-04-23 00:36
> @xiong-gang
> Can the PR #9959 fix this?
It looks like the same issue

**Comment by kainwen** [comment] 2020-04-26 07:15
@lambgong 
The fix pr is merged into 5X. You can use test env to verify that if your issue is fixed. If so, please help close this issue. Thanks.

**Comment by kainwen** [comment] 2020-04-29 06:14
I believe this has been fixed.

Close the issue.

Feel free to reopen it if there are more issues.

**Closed by kainwen** 2020-04-29 06:14 UTC
