### ISSUE TITLE
GUCs are not reset correctly in QE backends

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#685] opened 2016-04-29 11:06 UTC
See test case:

```

set gp_select_invisible=true;

-- Create a test table to work with. This also has the side effect of
-- creating a gang and establishing connections to segments.
-- XXX: The gp_select_invisible=true option is sent to the QEs when the
-- connections are established, as a per-connection, or "command-line",
-- parameter
create temp table guctest (i int);

-- Reset the guc.
-- XXX A "RESET gp_select_invisible" command is also sent to all the QE
-- backends, but it doesn't have the desired effect there: because the
-- gp_select_invisible=true was sent as a per-connection parameter,
-- RESET will just reset it to 'on' in the QEs.
reset gp_select_invisible;

-- Insert some rows, and delete them.
insert into guctest select i from generate_series(1, 5) i;
delete from guctest;

-- Should return 0 rows, because they were deleted.
-- XXX: However, if gp_select_invisible is effectively still enabled in
-- the QE workers, this will display the deleted rows.
select * from guctest;

-- clean up
drop table guctest;
```

On master, this returns 5 rows, demonstrating that the gp_select_invisible GUC is not reset correctly in the QE backends. I didn't check older branches. The test case above contains commentary on how I think the bug occurs, although I'm not 100% sure on the details.

**Comment by hlinnaka** [comment] 2016-04-29 11:07
Should add that this isn't 100% reproducible. After starting the cluster, it seems that it often works correctly on the first attempt, but when you disconnect and reconnect, it fails.

**Comment by hlinnaka** [comment] 2016-04-29 11:14
Oh, and not sure if this is related or even the root cause, but:

SetPGVariable() uses CdbSetGucOnAllGangs() to dispatch the "SET ..." command to all the segments, but for a RESETs the code in ProcessUtility uses CdbDoCommand() to dispatch it. That seems like a contradiction, surely we should treat SET and RESET the same.

**Comment by vraghavan78** [comment] 2016-05-11 22:13
Thanks @hlinnaka created a story for QX team to look into it https://www.pivotaltracker.com/story/show/119411997

**Comment by Eulerizeit** [comment] 2017-07-03 13:33
@danielgustafsson did you fix this issue? Can it be closed?

**Comment by jchampio** [comment] 2019-08-13 19:30
@slari-pivotal and I ran into something that looks the same, but we're not sure if it has the same root cause:
```sql
CREATE OR REPLACE FUNCTION public.segment_setting(guc text)
  RETURNS SETOF text
  EXECUTE ON ALL SEGMENTS
  LANGUAGE plpgsql
AS $$
BEGIN
  RETURN NEXT pg_catalog.current_setting(guc);
END
$$;
```
```
postgres=# select public.segment_setting('search_path');
 segment_setting
------------------
 '"$user",public'
 '"$user",public'
 '"$user",public'
(3 rows)

-- Now wait for the gang that was created by the above SELECT to go away...

postgres=# set search_path to other_schema;
SET
postgres=# set search_path to another_schema;
SET
postgres=# reset search_path;
RESET
postgres=# select public.segment_setting('search_path');
 segment_setting
-----------------
 'other_schema'
 'other_schema'
 'other_schema'
(3 rows)
```

**Comment by Eulerizeit** [comment] 2019-08-14 01:40
@weinan003  this seems related to the work you are currently doing.

**Comment by weinan003** [comment] 2019-08-30 07:32
I'm watching on this issue.
root cause is that. When new gang create, we just use '-c' command to synchronize guc which contain `GUC_GPDB_NEED_SYNC` flag. `-c` will change guc default value, which means 

```
set gp_select_invisible=true;
 -- create gang ,qd current guc value is true, default value is false
 -- qe current value is true, default value is false

exec some queries

reset gp_select_invisible
 -- qd reset guc value to false
 -- qe reset guc value to true.
```
Hence, you still can fetch delete tuple for this case.

I will organize a proper PR to fix this.

**Comment by weinan003** [comment] 2019-09-02 09:44
Actually, QE should not have guc default value, if a guc has **SYNC** flag. QE guc value needs to keep same with QD. For `reset guc` command, QD still need to dispatch `set` command after it reset guc value and the guc value is default QD guc value.

**Comment by asimrp** [comment] 2021-04-22 05:55
This issue exists in 6.15.0.  Jacob and Shoaib's repro continues to exhibit the anomalous behavior.

**Comment by gfphoenix78** [comment] 2021-08-10 11:05
The root cause is that the reset values between the coordinator and primaries are inconsistent. When the QD process is created, the reset values of the QD are inherited from its postmaster process and the `{{PGOPTIONS}}`. The reset values are different for the QEs, it depends on whether the GUC is `sync` or `unsync`. `unsync` GUC values of a QE are mainly inherited from its postmaster and possibly affected by the option values passed from the QD(I don't verify it). All the `sync`ed GUCs are passed from its QD process. When the QE is created, the `config_XXX.reset_val` of the GUCs are overridden by the options passed from the QD.
The QD passes its current GUC values to for the creation of the QE. When the QD has updated its sync GUC(s), the state of the reset_val is inconsistent between the QD and QEs.

For the above example, the first SET statement will first change the GUC gp_select_invisible to true in the QD, and then the QD dispatch gp_select_invisible=true to the newly created QEs.
Next, the QEs set the reset_val of gp_select_invisible to true. When the QE runs reset gp_select_invisible, it uses the reset_value to set the current value.

For more details, see
```
PGOPTION='-c statement_mem=64MB' psql postgres
-- the reset_val of statement_mem should be 65536, which is probably different from the postmaster's
(gdb) p *(struct config_int*)find_option("statement_mem", 1, 0)
$1 = {gen = {name = 0x13a70b0 "statement_mem", context = PGC_USERSET, group = RESOURCES_MEM,
    short_desc = 0x13a0868 "Sets the memory to be reserved for a statement.", long_desc = 0x0, flags = 4198400, vartype = PGC_INT,
    status = 0, source = PGC_S_CLIENT, reset_source = PGC_S_CLIENT, scontext = PGC_SU_BACKEND, reset_scontext = PGC_SU_BACKEND,
    stack = 0x0, extra = 0x0, sourcefile = 0x0, sourceline = 0}, variable = 0x175dc64 <statement_mem>, boot_val = 128000, min = 50,
  max = 2147483647, check_hook = 0xd19270 <gpvars_check_statement_mem>, assign_hook = 0x0, show_hook = 0x0, reset_val = 65536,
  reset_extra = 0x0}

-- in QD
postgres > set statement_mem = '32MB';
-- the following SELECT will create a new slice in the current session.
-- the newly created QEs will have the new value '32MB' as the reset_val of statement_mem.
postgres > select * from t1, t2;

-- gpdb attach to another QE(newly created process in the same session)
(gdb) p *(struct config_int*)find_option("statement_mem", 1, 0)
$1 = {gen = {name = 0x13a70b0 "statement_mem", context = PGC_USERSET, group = RESOURCES_MEM,
    short_desc = 0x13a0868 "Sets the memory to be reserved for a statement.", long_desc = 0x0, flags = 4198400, vartype = PGC_INT,
    status = 0, source = PGC_S_CLIENT, reset_source = PGC_S_CLIENT, scontext = PGC_SU_BACKEND, reset_scontext = PGC_SU_BACKEND,
    stack = 0x0, extra = 0x0, sourcefile = 0x0, sourceline = 0}, variable = 0x175dc64 <statement_mem>, boot_val = 128000, min = 50,
  max = 2147483647, check_hook = 0xd19270 <gpvars_check_statement_mem>, assign_hook = 0x0, show_hook = 0x0, reset_val = 32768,
  reset_extra = 0x0}

-- after reset statement, the QD, the statement_mem is very different on these QD/QEs.
reset statement_mem;
```

Here is my proposal:

1. We always pass the reset_val of the synced GUC to the newly created QEs.
2. Update the current value of the `synced` GUCs if the current value is not equal to the reset_val

**Comment by gfphoenix78** [comment] 2021-08-13 14:35
The PR(https://github.com/greenplum-db/gpdb/pull/12441) should fix this issue.

**Comment by gfphoenix78** [comment] 2021-08-24 04:51
Fixed in https://github.com/greenplum-db/gpdb/pull/12441

**Closed by gfphoenix78** 2021-08-24 04:51 UTC
Labels: type: bug, topic: dispatch gucs, area: server
