### ISSUE TITLE
gpinitsystem --help throws an error about missing value

### ISSUE THREAD

**Issue by andreasscherbaum** [greenplum-db/gpdb#1071] opened 2016-08-25 19:14 UTC
```
[gpadmin@localhost ~]$ gpinitsystem --help
20160825:18:13:30:022761 gpinitsystem:localhost:gpadmin-[FATAL]:-Missing value for option help
```

**Comment by Chibin** [comment] 2016-08-25 21:00
Confirmed that the reported issue happens.

Looking at the code, it looks like there are no options for ```--help``` ... we only have ```-?``` as the argument for calling help.

**Comment by andreasscherbaum** [comment] 2016-08-26 08:18
Then it should throw an error about an unknown option, and not an unknown value for --help, right?

**Comment by Chibin** [comment] 2016-08-26 21:59
Yes, the output message is misleading and needs to be clearer.

**Comment by skahler-pivotal** [comment] 2017-05-16 16:15
Fixed in
https://github.com/greenplum-db/gpdb/pull/1077

**Closed by skahler-pivotal** 2017-05-16 16:15 UTC
