### ISSUE TITLE
gpinitstandby joins standby master server with wrong hostname

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#11092] opened 2020-11-01 15:13 UTC
### Greenplum version or build
GPDB v6.x
### OS version and uname -a
RHEL/CentOS 7.x
### autoconf options used ( config.status --config )
GPDB Enterprise Edition
### Installation information ( pg_config )
GPDB Enterprise Edition
### Expected behavior
After `gpinitstandby`, DB records joined standby master server in `pg_catalog.gp_segment_configuration` with its hostname and in the address column should stores the specified address label.
```
postgres=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |       datadir        
------+---------+------+----------------+------+--------+------+----------+---------+----------------------
    1 |      -1 | p    | p              | n    | u      | 5432 | mdwee    | mdw     | /data/master/gpseg-1
    3 |       1 | p    | p              | s    | u      | 6000 | sdw2ee   | sdw2    | /data/primary/gpseg1
    5 |       1 | m    | m              | s    | u      | 7000 | sdw1ee   | sdw1    | /data/mirror/gpseg1
    2 |       0 | p    | p              | s    | u      | 6000 | sdw1ee   | sdw1    | /data/primary/gpseg0
    4 |       0 | m    | m              | s    | u      | 7000 | sdw2ee   | sdw2    | /data/mirror/gpseg0
    6 |      -1 | m    | m              | s    | u      | 5432 | smdwee   | smdw    | /data/master/gpseg-1
(5 rows)

postgres=# 
```
### Actual behavior
After `gpinitstandby`, the entry of the standby master server in `pg_catalog.gp_segment_configuration` stores the same value for both `hostname` and `address` columns.
```
postgres=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |       datadir        
------+---------+------+----------------+------+--------+------+----------+---------+----------------------
    1 |      -1 | p    | p              | n    | u      | 5432 | mdwee    | mdw     | /data/master/gpseg-1
    3 |       1 | p    | p              | s    | u      | 6000 | sdw2ee   | sdw2    | /data/primary/gpseg1
    5 |       1 | m    | m              | s    | u      | 7000 | sdw1ee   | sdw1    | /data/mirror/gpseg1
    2 |       0 | p    | p              | s    | u      | 6000 | sdw1ee   | sdw1    | /data/primary/gpseg0
    4 |       0 | m    | m              | s    | u      | 7000 | sdw2ee   | sdw2    | /data/mirror/gpseg0
    6 |      -1 | m    | m              | s    | u      | 5432 | smdw     | smdw    | /data/master/gpseg-1
(5 rows)

postgres=# 
```
### Step to reproduce the behavior

Initialize the cluster with the configuration shown as the following `/etc/hosts` content.
```
[gpadmin@mdwee ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

# External NICs, 1Gbs network
192.168.1.10   mdwee
192.168.1.11   sdw1ee
192.168.1.12   sdw2ee
192.168.1.13   smdwee

# Interconenct NICs, 10Gbs network
10.18.0.185   mdw
10.18.0.150   sdw1
10.18.0.182   sdw2
10.18.0.187   smdw
[gpadmin@mdwee ~]$ 
```

And the cluster is initialized with the following `hostfile_gpinitsystem` content.
```
[gpadmin@mdwee ~]$ cat ~/gpconfigs/hostfile_gpinitsystem
sdw1
sdw2
[gpadmin@mdwee ~]$ 
```

After the DB cluster starts, prepare a new server as the standby master node.
```
[gpadmin@mdwee ~]$ gpssh -h smdw -e hostname
[smdw] hostname
[smdw] smdwee
[gpadmin@mdwee ~]$ 
```

Then join the server as a new standby master node to the GPDB cluster, specifying interconnect NIC label rather than its real hostname.
```
[gpadmin@mdwee ~]$ gpinitstandby -s smdw
```

According to the [GPDB installation guide](https://gpdb.docs.pivotal.io/latest/install_guide/init_gpdb.html#topic4), it is valid to initialize a GPDB cluster without associating servers' real hostname to interconnect NICs.

But it seems that `gpinitstandby` command does not capture the real hostname of a joined standby master server.

Hope GPDB team can fix this tool.

Best Regards.

**Comment by kalensk** [comment] 2020-11-03 00:19
Thanks for letting us know! We have added this to our list of work and will review the reproduction.

**Comment by dpandhi-git** [comment] 2022-11-13 03:27
Duplicate of https://github.com/greenplum-db/gpdb/issues/9531
Closing

**Closed** 2022-11-20 02:22 UTC
