### ISSUE TITLE
alter table add partition on a appendonly table make the index on partitioned table lose function

### ISSUE THREAD

**Issue by lanjie-nb** [greenplum-db/gpdb#9394] opened 2020-01-10 09:28 UTC
### Greenplum version or build
6.0.0
### OS version and uname -a
Red Hat Enterprise Linux Server release 7.2 (Maipo) 
### Step to reproduce the behavior
Step 1. Create a appendonly table and partition it.
```sql
DROP TABLE IF EXISTS citizen;
CREATE TABLE citizen(id INT,name VARCHAR ,age INT) WITH(appendonly=true) distributed by(id) PARTITION BY RANGE(age)
(
PARTITION child START(1) END(10) inclusive,
PARTITION young START(11) END(20) inclusive
);
```

Step 2. Insert some datas for test;
```sql
INSERT INTO citizen(id,name,age)values(1,'Tom',8);
INSERT INTO citizen(id,name,age)values(2,'Tony',18);
INSERT INTO citizen(id,name,age)values(3,'Jerry',7);
```

Step 3. Create a index on the table citizen;
```sql
CREATE INDEX idx on citizen(name);
```

Step 4. Query one data and observe wether index is used;
```sql
EXPLAIN SELECT * FROM citizen where name='Tom';
```

We can see: 
![image](https://user-images.githubusercontent.com/55053271/72201722-0c08e300-3492-11ea-84df-30539c7e2208.png)
index is used;

Step 5.  Add a partition ;
```sql
ALTER TABLE citizen ADD partition middle START(30) END(40) inclusive;
```

Step 6. Query and obeserve the query plan.
```sql
EXPLAIN SELECT * FROM citizen where name='Tom';
```

![image](https://user-images.githubusercontent.com/55053271/72201800-a10bdc00-3492-11ea-8207-06ab68d0a5bb.png)

Now,the index lose its function!

**Comment by ashwinstar** [comment] 2020-01-29 06:53
This is something specifically to do with Pivotal Optimizer (GPORCA), as with Postgres query optimizer it's working fine. I tried creating all the tables upfront as part of create and not do `alter` later and for that case without any change in data Pivotal Optimizer (GPORCA) is able to use index scan.

So, `alter` is playing role causing Pivotal Optimizer (GPORCA) to not generate or pick the indexscan plans. @vraghavan78

**Comment by lij55** [comment] 2022-03-25 08:26
6.19.1 and master (by 71664c2a) have still this issue.

**Comment by Smyatkin-Maxim** [comment] 2022-12-03 14:19
Was it fixed? Can`t reproduce on 6X_STABLE

**Comment by ashwinstar** [comment] 2023-05-10 00:52
I am closing this issue as not able to reproduce on main branch with ORCA or planner, so seems to be fixed.

**Closed by ashwinstar** 2023-05-10 00:52 UTC
Labels: type: enhancement, topic: planner, area: gporca, area: server, version: 6X_STABLE, version: 7X_ALPHA
