### ISSUE TITLE
unexpected data beyond EOF in block

### ISSUE THREAD

**Issue by tcyang11** [greenplum-db/gpdb#10134] opened 2020-05-18 09:13 UTC
### Greenplum version or build
6.7.1
### OS version and uname -a
Linux master1 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tcyang11** [comment] 2020-05-18 09:16
tdb=# insert into t2 select generate_series(1,1000);
ERROR:  unexpected data beyond EOF in block 0 of relation base/24578/173296 (bufmgr.c:489)  (seg0 100.25.12.5:7000 pid=17053) (bufmgr.c:489)
HINT:  This has been seen to occur with buggy kernels; consider updating your system.

**Comment by paul-guo-** [comment] 2020-05-19 02:48
Please provide the steps about how to reproduce this issue. Also please check kernel message, pg_logs to see if that is kernel relevant.

**Comment by tcyang11** [comment] 2020-05-19 03:15
The cause is 173296  file corruption。

"ERROR","XX000","unexpected data beyond EOF in block 0 of relation base/24578/173296 (bufmgr.c:489)",,"This has been seen to occur with buggy kernels; consider updating your system.",,,"COPY t2, line 41","copy t2 from '/home/gpadmin/t2_7000.txt';",0,,"bufmgr.c",489,"Stack trace:
1    0xbe7c3c postgres errstart (elog.c:557)
2    0xa4ab92 postgres <symbol not found> (bufmgr.c:486)
3    0xa4ac34 postgres ReadBufferExtended (bufmgr.c:341)
4    0x7003ab postgres RelationGetBufferForTuple (hio.c:90)
5    0x6fab53 postgres heap_multi_insert (heapam.c:2732)
6    0x826621 postgres <symbol not found> (copy.c:4458)
7    0x82fdf1 postgres <symbol not found> (copy.c:4264)
8    0x833e30 postgres DoCopy (copy.c:1129)
9    0xa87105 postgres standard_ProcessUtility (utility.c:637)
10   0xa83711 postgres <symbol not found> (palloc.h:158)
11   0xa8420e postgres <symbol not found> (pquery.c:1512)
12   0xa85927 postgres PortalRun (pquery.c:1022)
13   0xa80040 postgres <symbol not found> (postgres.c:1842)
14   0xa827ce postgres PostgresMain (postgres.c:5257)
15   0x6ad8b8 postgres <symbol not found> (postmaster.c:4462)
16   0xa09b62 postgres PostmasterMain (postmaster.c:1513)
17   0x6b1141 postgres main (main.c:205)
18   0x7fc06bd4a505 libc.so.6 __libc_start_main + 0xf5
19   0x6bcd4c postgres <symbol not found> + 0x6bcd4c
"

**Comment by tcyang11** [comment] 2020-05-19 03:17
Create an empty file that can be read, not written。
e.g.
touch 173296

**Comment by hlinnaka** [comment] 2020-08-28 06:45
> Create an empty file that can be read, not written。
> e.g.
> touch 173296

If you need to do that to induce the error, that's not a bug, it's just a case of "don't do that then". Closing, but please feel free to re-open if there's a way to encounter this without manually corrupting the data directory.

**Closed by hlinnaka** 2020-08-28 06:45 UTC
