### ISSUE TITLE
Where clause doesn't work proper with numeric and date datatypes.

### ISSUE THREAD

**Issue by tkhannan** [greenplum-db/gpdb#5729] opened 2018-09-10 09:19 UTC
### Greenplum version or build
PostgreSQL 8.3.23 (Greenplum Database 5.9.0 build commit:214d9aef83b1aeb1ba7d2c2f9bf1c50ca6aa7c1d) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Jun 15 2018 00:39:56
### OS version and uname -a
CentOS Linux 7
Linux kzgreenplum5 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior
Select with where clause lose records if it contains numeric and date datatypes.

### Step to reproduce the behavior
--PostgreSQL 8.3.23 (Greenplum Database 5.9.0 build commit:214d9aef83b1aeb1ba7d2c2f9bf1c50ca6aa7c1d) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Jun 15 2018 00:39:56
--PostgreSQL 8.2.15 (Greenplum Database 4.2.1.2 build 2) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.2 compiled on Jun 11 2012 16:28:44

drop table if exists public.t1;
drop table if exists public.t_temp;

create table public.t1
(s_varchar10 VARCHAR(10) 
,s_varchar5  VARCHAR(5)
,s_tm 		 TIMESTAMP
,s_dec 		 NUMERIC(31, 10)
,s_date 	 DATE
,s_date2	 DATE
);

create table public.t_temp
(s_varchar10 VARCHAR(10) 
,s_varchar5  VARCHAR(5)
,s_tm 		 TIMESTAMP
,s_dec 		 NUMERIC(31, 10)
,s_date 	 TIMESTAMP
,s_date2	 TIMESTAMP
);

insert into public.t_temp
(s_varchar10, s_varchar5, s_tm, s_dec, s_date, s_date2)
values
('Q@@WERT$$$',	'@CHAR',	'2005-05-14 10:39:53',	376752867723003027456.8534298230,	'2032-04-15 00:00:00',	'2012-05-17 00:00:00'),
('Q@@WERT$$$',	'@CHAR',	'2005-05-14 10:39:53',	376752861723003027456.8534298230,	'2032-04-15 00:00:00',	'2012-05-17 00:00:00');

INSERT INTO public.t1
(s_varchar10, s_varchar5, s_tm,	s_date,	s_dec, s_date2)
values
('Q@@W$',		'@AR',		'2005-05-10 10:09:53',	'2032-04-15',	'376752861723003027456.8534298230',	'2002-04-15'),
('Q@@WERT$$$',	'@CHAR',	'2005-05-14 10:39:53',	'2032-04-15',	'376752861723003027456.8534298230',	'2012-05-17'),
('Q@@WERT$$$',	'@CHAR',	'2005-05-14 10:39:53',	'2032-04-15',	'376752867723003027456.8534298230',	'2012-05-17'),
('Q@@W$',		'@AR',		'2005-05-10 10:09:53',	'2032-04-15',	'376752861423003027456.8534298230',	'2002-04-15');

        SELECT * FROM  public.t1
        WHERE (
        s_varchar10 ,s_varchar5 ,s_tm ,s_dec 
        ) in (
        SELECT s_varchar10 ,s_varchar5 ,s_tm ,s_dec 
        FROM public.t_temp
        ); 
--expected 2 rows
--Greenplum 4.2.1.2  returns 2
--Greenplum 5.9.0  returns 2
       
        SELECT * FROM  public.t1
        WHERE (
        s_dec, s_date 
        ) in (
        SELECT s_dec, s_date
        FROM public.t_temp
        );
--expected 3 rows
--Greenplum 4.2.1.2  returns 3
--Greenplum 5.9.0  returns 0

**Comment by deem0n** [comment] 2018-09-10 10:28
Is it optimizer related bug ? Can you check results when GPORCA is disabled?
```
set optimizer = off;
```

**Comment by Darych** [comment] 2018-09-10 10:41
With optimizer=off the same result.

**Comment by paul-guo-** [comment] 2018-09-10 10:45
I could not reproduce this on greenplum5 master with orca off so probably this is fixed in latest greenplum 5 (at least planner). I'm not able to test orca since I fail to install orca via conan (seems that a dependent http server is down). You might want to check the explain output to see which optimizer generates the final plan.

test=#    SELECT * FROM  public.t1
    WHERE (
    s_dec, s_date
    ) in (
    SELECT s_dec, s_date
    FROM public.t_temp
    );
 s_varchar10 | s_varchar5 |        s_tm         |              s_dec               |   s_date   |  s_date2
-------------+------------+---------------------+----------------------------------+------------+------------
 Q@@wert$$$  | @char      | 2005-05-14 10:39:53 | 376752861723003027456.8534298230 | 2032-04-15 | 2012-05-17
 Q@@wert$$$  | @char      | 2005-05-14 10:39:53 | 376752867723003027456.8534298230 | 2032-04-15 | 2012-05-17
 Q@@W$       | @ar        | 2005-05-10 10:09:53 | 376752861723003027456.8534298230 | 2032-04-15 | 2002-04-15
(3 rows)

test=# select version();
                                                                                              version

-------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.10.0+dev.91.gdfe0557a44 build dev) on x86_64-pc-linux-gnu, compiled by GCC
 gcc (GCC) 6.2.0, 64-bit compiled on Sep  3 2018 23:41:40 (with assert checking)
(1 row)

test=# show optimizer;
 optimizer
-----------
 off
(1 row)

**Comment by kapustor** [comment] 2018-09-10 10:46
Thats because `2032-04-15 00:00:00` != `2032-04-15`, so the JOIN doesn't join these two rows. As I believe, this is correct behavior of the query.
You can rewrite the query as the following:
```
SELECT * FROM  public.t1
    WHERE (
    s_dec, s_date::date
    ) in (
    SELECT s_dec, s_date::date
    FROM public.t_temp
    );
```
Then it works as in 4.3.X:
```
adb=# SELECT * FROM  public.t1
adb-#     WHERE (
adb(#     s_dec, s_date::date
adb(#     ) in (
adb(#     SELECT s_dec, s_date::date
adb(#     FROM public.t_temp
adb(#     );
 s_varchar10 | s_varchar5 |        s_tm         |              s_dec               |   s_date   |  s_date2
-------------+------------+---------------------+----------------------------------+------------+------------
 Q@@W$       | @ar        | 2005-05-10 10:09:53 | 376752861723003027456.8534298230 | 2032-04-15 | 2002-04-15
 Q@@wert$$$  | @char      | 2005-05-14 10:39:53 | 376752861723003027456.8534298230 | 2032-04-15 | 2012-05-17
 Q@@wert$$$  | @char      | 2005-05-14 10:39:53 | 376752867723003027456.8534298230 | 2032-04-15 | 2012-05-17
(3 rows)
```

**Comment by paul-guo-** [comment] 2018-09-10 10:52
Relates to this?

```
commit 7426b4fbe86a01049f8a65de100905a815730a59
Author: Jinbao Chen <jinchen@pivotal.io>
Date:   Thu Aug 23 12:06:03 2018 +0800

    Fix redistribute bug on some types which need to convert (#5496)


    After 8.4 merge, we have two restrictlist 'mergeclause_list'
    and 'hashclause_list' in function 'add_paths_to_joinrel'. We
    use mergeclause_list in cdb motion in hashjoin. But some of
    keys should not been used as distribution keys.

    Add a whitelist that which operator is  distribution-compatible.
```

**Comment by vraghavan78** [comment] 2018-09-10 23:42
Just an FYI. GPORCA falls back to planner.

```
LOG:  2018-09-10 16:33:40:941045 PDT,THD000,NOTICE,"Feature not supported by the Pivotal Query Optimizer: Non-Scalar Subquery",
LOG:  Planner produced plan :0
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=1.18..3.28 rows=4 width=50)
   ->  Hash Semi Join  (cost=1.18..3.28 rows=2 width=50)
         Hash Cond: t1.s_dec = t_temp.s_dec
         Join Filter: t1.s_date = t_temp.s_date
         ->  Seq Scan on t1  (cost=0.00..2.04 rows=2 width=50)
         ->  Hash  (cost=1.10..1.10 rows=2 width=29)
               ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..1.10 rows=2 width=29)
                     ->  Seq Scan on t_temp  (cost=0.00..1.02 rows=1 width=29)
 Optimizer: legacy query optimizer
(9 rows)
```

**Comment by Eulerizeit** [comment] 2018-09-11 23:40
We are planning to release 5.11 soon. Could you test this with that
version. I think we will have addressed it.

-- Rob

**Comment by kapustor** [comment] 2018-09-13 17:59
```   SELECT * FROM  public.t1
    WHERE (
    s_dec, s_date 
    ) in (
    SELECT s_dec, s_date
    FROM public.t_temp
    );```
in 5.11 gives 3 lines.
@Eulerizeit

**Comment by Eulerizeit** [comment] 2018-09-13 18:18
@kapustor awesome. thanks for checking I'm going to close this issue.

**Closed by Eulerizeit** 2018-09-13 18:18 UTC
Labels: Planner
