### ISSUE TITLE
Assertion failure while pfree() inside advance_combine_function

### ISSUE THREAD

**Issue by soumyadeep2007** [greenplum-db/gpdb#9916] opened 2020-04-14 00:15 UTC
w/ @d :
### Greenplum version or build
master
### Expected behavior
There should be no assertion failure
### Actual behavior
```
                                              QUERY PLAN
-------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=256.60..273.27 rows=513 width=68)
   Output: (sum(a) FILTER (WHERE false)), (max(c)), b
   ->  HashAggregate  (cost=256.60..263.01 rows=171 width=68)
         Output: sum(a) FILTER (WHERE false), max(c), b
         Group Key: foo.b
         ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..225.88 rows=1366 width=65552)
               Output: b, a, c
               Hash Key: b
               ->  Seq Scan on pg_temp_10.foo  (cost=0.00..143.96 rows=1366 width=65552)
                     Output: b, a, c
 Optimizer: Postgres query optimizer
(11 rows)

SET
psql:/tmp/denis_repro_works_on_6x.sql:14: WARNING:  Any temporary tables for this session have been dropped because the gang was disconnected (session id = 10)
psql:/tmp/denis_repro_works_on_6x.sql:14: ERROR:  Unexpected internal error (mcxt.c:1195)  (seg0 slice1 127.0.0.1:7002 pid=37987) (mcxt.c:1195)
DETAIL:  BadArgument("!(((context) != ((void*)0) && (((((const Node*)((context)))->type) == T_AllocSetContext))))", File: "mcxt.c", Line: 1195)

XX000","Unexpected internal error (mcxt.c:1195)","BadArgument(""!(((context) != ((void*)0) && (((((const Node*)((context)))->type) == T_AllocSetContext))))"", File: ""mcxt.c"", Line: 1195)",,,,,"EXPLAIN (COSTS OFF, ANALYZE)

Stack trace:
1    0x10af28c8d postgres errstart + 0x5ad
2    0x10af27470 postgres ExceptionalCondition + 0x30
3    0x10af75939 postgres pfree + 0xc9
4    0x10aaaba24 postgres advance_combine_function + 0x204
5    0x10aafaefc postgres agg_hash_reload + 0x63c
6    0x10aafa5e6 postgres agg_hash_next_pass + 0x546
7    0x10aaabd2f postgres agg_retrieve_hash_table + 0xdf
8    0x10aaabb59 postgres ExecAgg + 0xa9
9    0x10aa8c450 postgres ExecProcNode + 0x4c0
10   0x10aaedd79 postgres execMotionSender + 0x109
11   0x10aaed3a8 postgres ExecMotion + 0x1f8
12   0x10aa8c50d postgres ExecProcNode + 0x57d
13   0x10aa83df3 postgres ExecutePlan + 0xb3
14   0x10aa83a25 postgres standard_ExecutorRun + 0x3f5
15   0x10aa8362a postgres ExecutorRun + 0x4a
16   0x10ad379d8 postgres PortalRunSelect + 0x128
17   0x10ad373c6 postgres PortalRun + 0x286
18   0x10ad31bb0 postgres exec_mpp_query + 0xcf0
```
### Step to reproduce the behavior
```sql
CREATE TEMP TABLE foo (a int8, b int, c char(65536) DEFAULT 's');
INSERT INTO foo SELECT i, (i | 7) FROM generate_series(1, 4096) i;
ANALYZE foo;
SELECT $$
SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b
$$ AS qry \gset
SELECT count(DISTINCT b) FROM foo;
EXPLAIN VERBOSE
:qry ;
SET statement_mem='1984kB';
EXPLAIN (COSTS OFF, ANALYZE)
:qry ;
```

We don't know if the issue is in other versions.

**Comment by kainwen** [comment] 2021-09-22 06:42
Using the reproduce method, I cannot reproduce this in 6x and master. Close it.

Feel free to re-open if needed. Thanks.

**Closed by kainwen** 2021-09-22 06:42 UTC
Labels: version: 7X_ALPHA
