### ISSUE TITLE
Travis having an issue with `env:` fields with `.tar.gz` in them?

### ISSUE THREAD

**Issue by cjcjameson** [greenplum-db/gpdb#3256] opened 2017-09-12 17:44 UTC
I think the travis failures are a change in how Travis handles the `env:` section of `.travis.yml`.

https://github.com/greenplum-db/gpdb/blob/357f8d2205e135ca9e748a3f7ac0434d9f9457c7/.travis.yml#L62-L63 still shows the `.tar.gz`

But https://travis-ci.org/greenplum-db/gpdb/builds/274708729#L469-L470 calculated APR_TAR without the `.tar.gz` for some reason

If someone can point to Travis acknowledging the issue, feel free to close this.

**Comment by jimmyyih** [comment] 2017-09-12 22:17
Mmmm... so I've already pushed in https://github.com/greenplum-db/gpdb/commit/361994582f6f56fdf1979803d872bc1a5e1653fd to fix the issue but it seems like the TravisCI team has pushed in fix https://github.com/travis-ci/travis-build/commit/a818e1e12ff1afa5d20e993ba68d19b646fda0af.  So someone can revert my commit or we leave it be...  Either way, the issue is fixed now so closing this issue.

**Closed by jimmyyih** 2017-09-12 22:17 UTC
