### ISSUE TITLE
error when gpstop -ar on mac using master code

### ISSUE THREAD

**Issue by yydzero** [greenplum-db/gpdb#5352] opened 2018-07-30 09:53 UTC
### Greenplum version or build
master

### OS version and uname -a
mac

```
20180730:17:52:48:065235 gpstop:yydzero:yydzero-[ERROR]:-Unable to clean up shared memory for segment: (ipcrm: shmid(196613): : Invalid argument
)
Traceback (most recent call last):
  File "/Users/yydzero/work/build/master/lib/python/gppylib/commands/base.py", line 243, in run
    self.cmd.run()
  File "/Users/yydzero/work/build/master/lib/python/gppylib/operations/__init__.py", line 53, in run
    self.ret = self.execute()
  File "/Users/yydzero/work/build/master/lib/python/gppylib/operations/utils.py", line 52, in execute
    raise ret
Exception: Unable to clean up shared memory for segment: (ipcrm: shmid(196613): : Invalid argument
)
```

**Comment by skahler-pivotal** [comment] 2018-07-30 15:06
@yydzero was this directly on the mac OS (which version) or inside a container? I don't see any arguments that we pass which are unrecognized at the ipcrm level on mac . That would leave a bad pid mapping to process or that the process was taking awhile and kicked in the two minute cleanup window, but managed to finish before the cleanup got to it.

**Comment by yydzero** [comment] 2018-07-30 22:56
It is directly on mac without container. macOS version is 10.12.5.  
I encountered similar problems several times recently. 

I remember we use ipcclean before, now we changed to ipcrm?

**Comment by skahler-pivotal** [comment] 2018-07-31 15:01
We've been using ipcrm as part of that specific process since 4x. 

Is it possible the shutdown was taking a long time and that issue popped or was it a message you immediately received?

**Comment by yydzero** [comment] 2018-08-01 00:29
this issue does not break anything, just displayed as an error when 'gpstop -ar'

Minor issue, if you folks could not reproduce it, I will try to dig deeper when it appears next time.

Thanks @boogabee

**Comment by adam8157** [comment] 2020-09-23 08:22
Could not reproduce, close it. Feel free to reopen if someone hits it again, thanks.

**Closed by adam8157** 2020-09-23 08:22 UTC
Labels: area: management utilities, topic: cluster mgmt
