### ISSUE TITLE
could not determine which collation to use for view column "max"

### ISSUE THREAD

**Issue by martkeller** [greenplum-db/gpdb#8376] opened 2019-08-14 10:58 UTC
### Greenplum version or build
GPDB 6.0.0-beta.6
### Expected behavior
same statement works in 4.3.32 and 5.19
### Actual behavior
German customer R+V started to test Beta6
### Step to reproduce the behavior
CREATE TEMP TABLE t1
(
    f1 smallint,
    f2 text
)
DISTRIBUTED RANDOMLY;

CREATE TEMP VIEW v1 AS
SELECT
count(*) OVER (PARTITION BY f1 ),
max(f2)
FROM t1
GROUP BY f1

ERROR: could not determine which collation to use for view column "max"
HINT: Use the COLLATE clause to set the collation explicitly.
SQL state: 42P22

**Comment by berlin-ab** [comment] 2019-08-16 17:41
What is the expected behavior here?

**Comment by berlin-ab** [comment] 2019-08-16 17:44
I removed the window function from the view creation and the temp table was successfully created:

```
adamberlin=# create temp view v1 as select max(f2) from t1 group by f1;
LOG:  00000: statement: create temp view v1 as select max(f2) from t1 group by f1;
LOCATION:  exec_simple_query, postgres.c:1617
CREATE VIEW
Time: 38.889 ms

**Comment by berlin-ab** [comment] 2019-08-16 17:47
Here's the explain plan for `create temp table` (`explain create temp view` is not allowed):

```
adamberlin=# explain create temp table v1 as SELECT                                                                                                                         count(*) OVER (PARTITION BY f1 ),                                                                                                                                           max(f2)                                                                                                                                                                     FROM t1                                                                                                                                                                     GROUP BY f1;
LOG:  00000: statement: explain create temp table v1 as SELECT
count(*) OVER (PARTITION BY f1 ),
max(f2)
FROM t1
GROUP BY f1;
LOCATION:  exec_simple_query, postgres.c:1617
NOTICE:  00000: Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'count' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
LOCATION:  apply_motion, cdbmutate.c:504
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                   QUERY PLAN                                                    │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Redistribute Motion 3:3  (slice2; segments: 3)  (cost=971.33..988.83 rows=334 width=34)                         │
│   Hash Key: (count(*) OVER (?))                                                                                 │
│   ->  WindowAgg  (cost=971.33..988.83 rows=334 width=34)                                                        │
│         Partition By: t1.f1                                                                                     │
│         ->  Sort  (cost=971.33..973.83 rows=334 width=34)                                                       │
│               Sort Key: t1.f1                                                                                   │
│               ->  HashAggregate  (cost=901.50..911.50 rows=334 width=34)                                        │
│                     Group Key: t1.f1                                                                            │
│                     ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=866.50..886.50 rows=334 width=34) │
│                           Hash Key: t1.f1                                                                       │
│                           ->  HashAggregate  (cost=866.50..866.50 rows=334 width=34)                            │
│                                 Group Key: t1.f1                                                                │
│                                 ->  Seq Scan on t1  (cost=0.00..611.00 rows=17034 width=34)                     │
│ Optimizer: Postgres query optimizer                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(14 rows)

Time: 4.154 ms
```

**Comment by adam8157** [comment] 2019-08-19 02:32
The expected behavior is successfully created I tried on 5X.

The root cause is `aggcollid` was lost, the plan is not supposed to matter.

**Comment by adam8157** [comment] 2019-08-19 09:56
I have a fix now, will submit the PR tomorrow.

**Comment by adam8157** [comment] 2019-08-22 09:20
Fixed on master and 6X

**Closed by adam8157** 2019-08-22 09:20 UTC
Labels: status: triage
