### ISSUE TITLE
Incorrect privileges on protocols after 9.2 merge

### ISSUE THREAD

**Issue by chrishajas** [greenplum-db/gpdb#5382] opened 2018-08-02 18:56 UTC
### Greenplum version or build
 PostgreSQL 9.2beta2 (Greenplum Database 6.0.0-alpha.0+dev.7544.g4750e1b655 build dev-oss) on x86_64-apple-darwin17.7.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.1), 64-bit compiled on Aug  2 2018 10:47:26

### Expected behavior
Privileges for protocols correctly populated in pg_extprotocol (and therefore pg_dump correctly dumps it)
### Actual behavior
Privileges incorrectly populated (and contain a `USAGE` permission, which I'm not sure if that was intentional. Currently GPDB doesn't allow to grant USAGE on a protocol.

### Step to reproduce the behavior

```
CREATE ROLE testrole;
CREATE OR REPLACE FUNCTION public.read_from_s3() RETURNS integer AS '$libdir/gps3ext.so', 's3_import' LANGUAGE C STABLE;
CREATE TRUSTED PROTOCOL s3_read (readfunc = public.read_from_s3);
GRANT ALL ON PROTOCOL s3_read TO testrole;
```

```
select * from pg_extprotocol where ptcname='s3_read';
``` 
returns
```
 ptcname |                     ptcacl
---------+------------------------------------------------
 s3_read | {=U/chajas,chajas=U/chajas,testrole=ar/chajas}
```

On 5X, it returns
```
 ptcname |                     ptcacl
---------+------------------------------------------------
 s3_read | {=chajas=ar/chajas,testrole=ar/chajas}
```

When we run pg_dump, we get this for the ACL:
```
REVOKE ALL ON PROTOCOL s3_read FROM PUBLIC;
REVOKE ALL ON PROTOCOL s3_read FROM chajas;
GRANT ALL ON PROTOCOL s3_read TO testrole;
```

which revokes all permissions on the protocol, but never grants them back as they should. There should be an additional line, `GRANT ALL ON PROTOCOL s3_read TO chajas;` (which exists in 5X).

**Comment by paul-guo-** [comment] 2018-08-05 03:36
This is caused by a missing 'break' in switch in related code which was introduced in 'git merge'. We've seen similar issues a couple of times when merging pg 9.2. There was a short discussion several days ago about how to prevent this in the future. gcc option -Wimplicit-fallthrough is probably a solution.

**Comment by chrishajas** [comment] 2018-08-06 21:51
Thanks! If we've been bitten by this before, this would probably be a good idea. A missing break can inject subtle bugs in areas that we don't have tests for.

**Comment by paul-guo-** [comment] 2018-08-07 01:59
Closing this issue. @chrishajas you could test and undo your workaround.

**Closed by paul-guo-** 2018-08-07 01:59 UTC
