### ISSUE TITLE
motion deadlock

### ISSUE THREAD

**Issue by maliangzhu** [greenplum-db/gpdb#15719] opened 2023-06-08 02:16 UTC
### os: centos 7

With 4 segments cluster, the sql will be deadlock within 10 seconds and cpu is 0%

```
drop table t1;
create table t1 ( a int, b char(100), c char(100), d char(100), e char(100));
insert into t1 select generate_series(1,1000000);
update t1 set b = ( random()*1000)::int;
update t1 set c = ( random()*1000)::int;
update t1 set d = ( random()*1000)::int;

set gp_interconnect_queue_depth =1;
set gp_interconnect_snd_queue_depth =1;
set work_mem='1GB';
set enable_mergejoin=0;
set optimizer = 0;

explain 
update t1 set e =
( select d from t1 t2 where t1.b = t2.b order by t1.c desc limit 1)
where t1.c is not null and exists ( select 1 from t1 t2 where t1.d = t2.d);

                                                       QUERY PLAN                                                         
---------------------------------------------------------------------------------------------------------------------------
 Update on t1  (cost=45.19..108.86 rows=237 width=1636)
   ->  Explicit Redistribute Motion 4:4  (slice1; segments: 4)  (cost=45.19..108.86 rows=237 width=1636)
         ->  Hash Semi Join  (cost=45.19..104.12 rows=237 width=1636)
               Hash Cond: (t1.d = t2.d)
               ->  Redistribute Motion 4:4  (slice3; segments: 4)  (cost=0.00..39.24 rows=475 width=1226)
                     Hash Key: t1.d
                     ->  Seq Scan on t1  (cost=0.00..29.75 rows=475 width=1226)
                           Filter: (c IS NOT NULL)
               ->  Hash  (cost=39.25..39.25 rows=475 width=410)
                     ->  Redistribute Motion 4:4  (slice4; segments: 4)  (cost=0.00..39.25 rows=475 width=410)
                           Hash Key: t2.d
                           ->  Seq Scan on t1 t2  (cost=0.00..29.75 rows=475 width=410)
               SubPlan 1
                 ->  Limit  (cost=0.00..0.04 rows=1 width=808)
                       ->  Result  (cost=0.00..82.00 rows=1900 width=808)
                             Filter: (t1.b = t2_1.b)
                             ->  Materialize  (cost=0.00..63.00 rows=1900 width=808)
                                   ->  Broadcast Motion 4:4  (slice2; segments: 4)  (cost=0.00..53.50 rows=1900 width=808)
                                         ->  Seq Scan on t1 t2_1  (cost=0.00..29.75 rows=475 width=808)
 Optimizer: Postgres query optimizer
(20 rows)


explain analyze
update t1 set e =
( select d from t1 t2 where t1.b = t2.b order by t1.c desc limit 1)
where t1.c is not null and exists ( select 1 from t1 t2 where t1.d = t2.d);
```

**Comment by fairyfar** [comment] 2023-06-15 01:07
@kainwen  
The problem can be reproduced using the Topo of GBPD as follows:
```sql
postgres=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port | hostname  |  address  |               datadir
------+---------+------+----------------+------+--------+------+-----------+-----------+--------------------------------------
    1 |      -1 | p    | p              | n    | u      | 5404 | localhost | localhost | /home/yz/gpdb/db/coordinator/gpseg-1
    2 |       0 | p    | p              | s    | u      | 6404 | localhost | localhost | /home/yz/gpdb/db/primary/gpseg0
    5 |       0 | m    | m              | s    | u      | 6504 | localhost | localhost | /home/yz/gpdb/db/mirror/gpseg0
    3 |       1 | p    | p              | s    | u      | 6405 | localhost | localhost | /home/yz/gpdb/db/primary/gpseg1
    6 |       1 | m    | m              | s    | u      | 6505 | localhost | localhost | /home/yz/gpdb/db/mirror/gpseg1
    4 |       2 | p    | p              | s    | u      | 6406 | localhost | localhost | /home/yz/gpdb/db/primary/gpseg2
    7 |       2 | m    | m              | s    | u      | 6506 | localhost | localhost | /home/yz/gpdb/db/mirror/gpseg2
(7 rows)
```

**Comment by kainwen** [comment] 2023-06-15 01:54
I think I understand and RCA the problem. Will give more comments later.

**Comment by kainwen** [comment] 2023-06-15 14:49
I have created a simple reproducible SQL with the same deadlock pattern (with some hack of code on the cost model, because it is easy to reproduce using right join in my env)

## Another Reproducible SQL

The env is a demo cluster with only 2 segments.

```sql
create table t1(a int, b int, c int) distributed by (a);
create table t2(a int, b int, c int) distributed by (a);
create table t3(a int, b int, c int) distributed by (a);

explain (verbose, costs off)
select
  (select count(1) from t3 where t3.b < t1.a + t2.b) x
from
  t1 right join t2
on
  t1.b = t2.b;


--                                  QUERY PLAN
-- -----------------------------------------------------------------------------
--  Gather Motion 2:1  (slice1; segments: 2)
--    Output: ((SubPlan 1))
--    ->  Hash Right Join
--          Output: (SubPlan 1)
--          Hash Cond: (t1.b = t2.b)
--          ->  Redistribute Motion 2:2  (slice3; segments: 2)
--                Output: t1.a, t1.b
--                Hash Key: t1.b
--                ->  Seq Scan on public.t1
--                      Output: t1.a, t1.b
--          ->  Hash
--                Output: t2.b
--                ->  Redistribute Motion 2:2  (slice4; segments: 2)
--                      Output: t2.b
--                      Hash Key: t2.b
--                      ->  Seq Scan on public.t2
--                            Output: t2.b
--          SubPlan 1
--            ->  Aggregate
--                  Output: count(1)
--                  ->  Result
--                        Filter: (t3.b < (t1.a + t2.b))
--                        ->  Materialize
--                              Output: t3.b
--                              ->  Broadcast Motion 2:2  (slice2; segments: 2)
--                                    Output: t3.b
--                                    ->  Seq Scan on public.t3
--                                          Output: t3.b

-- Wait Events

-- Sj: join slice
-- So: outer slice, scan and redistribute t1 (hash key: t1.b)
-- Si: inner slice, scan and redistribute t2 (hash key: t2.b)
-- Ss: subplan slice, scan t3 and broadcast t3

-- Sj.0 wait for tuples from So
----  let's suppose nothing will send to Sj.0, only EOS
----  so, t1 redistribute by (t1.b) will all send to seg1
insert into t1 select 1, 1 from generate_series(1, 10000); -- all tuples will be stored on seg1

-- t2's data does not matter
insert into t2 select i, i from generate_series(1, 10)i;

-- t3 is broadcast, just let it has many data
insert into t3 select i, i from generate_series(1, 10000)i;
delete from t3 where gp_segment_id = 1;

explain (verbose, costs off)
select
  (select count(1) from t3 where t3.b < t1.a + t2.b) x
from
  t1 right join t2
on
  t1.b = t2.b;

select
  (select count(1) from t3 where t3.b < t1.a + t2.b) x
from
  t1 right join t2
on
  t1.b = t2.b;
```

--------------------

## Analysis

The deadlock pattern is:

* there is motion in a Join plan's outer plan (left tree)
* there is motion in the Join plan's target list (subplan)
* The part of algorithm of the join is:
  - loop
    + fetch one tuple from outer plan
    + exec the target list

Deadlock chains:

* One QE of the join slice (call it `SJ.1`) is waiting for an outer tuple from the motion of outer plan
* A simple case is that only no QEs in outer slice would send tuple to the above QE, so in fact the above QE is wait for EOS (which means the all sender QEs must have to firstly finish)
* One QE of the outer slice is sending tuples to another QE of the join slice (call it `SJ.2`)
  - its sender buffer is full and waiting for ACK to clear sender buffer
  - it is hanging and waiting for ACK
* this QE of join slice alreay get an outer tuple and now are eval target list (the subplan), it is waiting for the subplan's broadcast motion
* the subplan's sender QE is a broadcast motion
   - it has to finish sending tuples to seg0, seg1 (one by one) in serial
   - it is sending tuples to `SJ.1` and it sender buffer is full and wait for ACK to clear
 * `SJ.1`'s main thread want outer tuples and will not read subplan motion's data and the recv buffer of subplan is full thus will not ACK the broadcast motion.

## Quick Fix to verify

* use ic TCP there should be no deadlock
* make table in subplan replicated table can avoid subplan contain motion, also will not deadlock
* if no motion of outer plan, there will not be deadlock

prefetch subplan can fix, below is a demo code of fix idea (just show the diea, super far from a formal fix):

```diff
diff --git a/src/backend/executor/nodeHashjoin.c b/src/backend/executor/nodeHashjoin.c
index 76b8fbb0e5..dcbbdaeb2e 100644
--- a/src/backend/executor/nodeHashjoin.c
+++ b/src/backend/executor/nodeHashjoin.c
@@ -367,6 +367,38 @@ ExecHashJoinImpl(PlanState *pstate, bool parallel)
                                if (hashtable->totalTuples == 0 && !HJ_FILL_OUTER(node))
                                        return NULL;

+                               if (node->prefetch_inner)
+                               {
+                                       node->prefetch_inner = false;
+                                       if (list_length(node->js.ps.subPlan) > 0)
+                                       {
                                        return NULL;

+                               if (node->prefetch_inner)
+                               {
+                                       node->prefetch_inner = false;
+                                       if (list_length(node->js.ps.subPlan) > 0)
+                                       {
+                                               ListCell *cell = NULL;
+                                               foreach(cell, node->js.ps.subPlan)
+                                               {
+                                                       PlanState *sps = ((SubPlanState *) lfirst(cell))->planstate;
+                                                       PlanState *a = sps;
+                                                       PlanState *b = sps->lefttree;
+                                                       bool found = false;
+                                                       while (a && b)
+                                                       {
+                                                               if (IsA(a, MaterialState) &&
+                                                                       IsA(b, MotionState))
+                                                               {
+                                                                       found = true;
+                                                                       break;
+                                                               }
+                                                               a = b;
+                                                               b = a->lefttree;
+                                                       }
+                                                       ((Material *) (a->plan))->cdb_strict = true;
+                                                       if (found)
+                                                       {
+                                                               ExecProcNode(a);
+                                                       }
+                                               }
+                                       }
+                               }
```

**Comment by maliangzhu** [comment] 2023-06-21 02:47
gp7

subplan without materialize also may deadlock ( slice1 and slice3)

```sql
CREATE TABLE base_tbl (a int);
CREATE TABLE ref_tbl (a int PRIMARY KEY);
INSERT INTO ref_tbl SELECT * FROM generate_series(1,10);
CREATE VIEW rw_view1 AS
SELECT * FROM base_tbl b
WHERE EXISTS(SELECT 1 FROM ref_tbl r WHERE r.a = b.a)WITH CHECK OPTION;
INSERT INTO rw_view1 VALUES (5); -- ok

explain(costs off) UPDATE rw_view1 SET a = a+5;
                           QUERY PLAN                            
-----------------------------------------------------------------
 Update on base_tbl b
   ->  Explicit Redistribute Motion 2:2  (slice1; segments: 2)
         ->  Split
               ->  Hash Join
                     Hash Cond: (b.a = r.a)
                     ->  Seq Scan on base_tbl b
                     ->  Hash
                           ->  Seq Scan on ref_tbl r
   SubPlan 1
     ->  Result
           Filter: (r_1.a = b.a)
           ->  Materialize
                 ->  Broadcast Motion 2:2  (slice2; segments: 2)
                       ->  Seq Scan on ref_tbl r_1
   SubPlan 2
     ->  Broadcast Motion 2:2  (slice3; segments: 2)
           ->  Seq Scan on ref_tbl r_2
 Optimizer: Postgres query optimizer
(18 rows)
```

**Comment by kainwen** [comment] 2023-06-21 02:58
> ```sql
> CREATE TABLE base_tbl (a int);
> CREATE TABLE ref_tbl (a int PRIMARY KEY);
> INSERT INTO ref_tbl SELECT * FROM generate_series(1,10);
> CREATE VIEW rw_view1 AS
> SELECT * FROM base_tbl b
> WHERE EXISTS(SELECT 1 FROM ref_tbl r WHERE r.a = b.a)WITH CHECK OPTION;
> INSERT INTO rw_view1 VALUES (5); -- ok
> 
> explain(costs off) UPDATE rw_view1 SET a = a+5;
> ```

Let me check it later. With the first glance I feel planner should add a materialize motion.

**Comment by kainwen** [comment] 2023-06-23 12:13
> ```sql
> SubPlan 2
>      ->  Broadcast Motion 2:2  (slice3; segments: 2)
>            ->  Seq Scan on ref_tbl r_2
> ```

The same root cause and the same bug pattern and the same fix method as this issue.

deadlock between:
* update's outer plan
* update's subplan (this time it is from check option of updatable view).

**Comment by kainwen** [comment] 2023-06-23 12:14
> gp7
> 
> subplan without materialize also may deadlock ( slice1 and slice3)
> 
> ```sql
> CREATE TABLE base_tbl (a int);
> CREATE TABLE ref_tbl (a int PRIMARY KEY);
> INSERT INTO ref_tbl SELECT * FROM generate_series(1,10);
> CREATE VIEW rw_view1 AS
> SELECT * FROM base_tbl b
> WHERE EXISTS(SELECT 1 FROM ref_tbl r WHERE r.a = b.a)WITH CHECK OPTION;
> INSERT INTO rw_view1 VALUES (5); -- ok
> 
> explain(costs off) UPDATE rw_view1 SET a = a+5;
>                            QUERY PLAN                            
> -----------------------------------------------------------------
>  Update on base_tbl b
>    ->  Explicit Redistribute Motion 2:2  (slice1; segments: 2)
>          ->  Split
>                ->  Hash Join
>                      Hash Cond: (b.a = r.a)
>                      ->  Seq Scan on base_tbl b
>                      ->  Hash
>                            ->  Seq Scan on ref_tbl r
>    SubPlan 1
>      ->  Result
>            Filter: (r_1.a = b.a)
>            ->  Materialize
>                  ->  Broadcast Motion 2:2  (slice2; segments: 2)
>                        ->  Seq Scan on ref_tbl r_1
>    SubPlan 2
>      ->  Broadcast Motion 2:2  (slice3; segments: 2)
>            ->  Seq Scan on ref_tbl r_2
>  Optimizer: Postgres query optimizer
> (18 rows)
> ```

The same root cause and the same bug pattern and the same fix method as this issue.

deadlock between:

* update's outer plan
* update's subplan (this time it is from check option of updatable view).

**Comment by kainwen** [comment] 2023-07-12 12:30
Fixed by https://github.com/greenplum-db/gpdb/pull/15842

**Closed by kainwen** 2023-07-12 12:30 UTC
Labels: type: bug, version: 7X_ALPHA, Priority 1, 7X_beta_testing
