### ISSUE TITLE
failed to configure resource group

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#9907] opened 2020-04-13 03:07 UTC
### Greenplum version or build
PostgreSQL 9.4.24 (Greenplum Database 6.2.1 build commit:d90ac1a1b983b913b3950430d4d9e47ee8827fd4) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Dec 16 2019 03:07:27

### OS version and uname -a
Linux R4412 3.10.0-693.21.1.el7.x86_64 #1 SMP Thu Jun 13 10:40:15 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

### Step to reproduce the behavior

1、create role wdl with login

2、using the follow cmd to create resource group
postgres=# create resource group test with(concurrency=1,cpu_rate_limit =10);
WARNING:  resource group is disabled
HINT:  To enable set gp_resource_manager=group
CREATE RESOURCE GROUP

3、Follow the prompts to execute the following cmd：
 gpconfig -c gp_resource_manager -v group -m group

Output the following error：
```
20200411:16:44:38:053836 gpconfig:R4412:gpadmin-[CRITICAL]:-new GUC value failed validation: [R4412:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist]
new GUC value failed validation: [R4412:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist]
/sys/fs/cgroup/memory/gpdb/
new GUC value failed validation: [R4412:cgroup is not properly configured: directory '/sys/fs/cgroup/cpuset/gpdb/' does not exist]
```
The directory does not exist, so I manually created the relevant gpdb directory under cgroup

[gpadmin@R4412 ~]$ gpconfig -c gp_resource_manager -v group -m group
20200411:16:57:19:079496 gpconfig:R4412:gpadmin-[INFO]:-completed successfully with parameters '-c gp_resource_manager -v group -m group'

4、after that，we  gpstop -r
 
5、alter role wdl resource group test;
WARNING:  resource group is disabled
HINT:  To enable set gp_resource_manager=group
ALTER ROLE

6、show the param  gp_resource_manager but found it was already on:
```
show gp_resource_manager;
 gp_resource_manager
---------------------
 group
 ```

7、
```
postgres=# select * from gp_toolkit.gp_resgroup_config;
 groupid |   groupname   | concurrency | cpu_rate_limit | memory_limit | memory_shared_quota | memory_spill_ratio | memory_auditor | cpuset 
---------+---------------+-------------+----------------+--------------+---------------------+--------------------+----------------+--------
    6437 | default_group | 20          | 30             | 0            | 80                  | 0                  | vmtracker      | -1
    6438 | admin_group   | 10          | 10             | 10           | 80                  | 0                  | vmtracker      | -1
   23801 | test          | 1          | 10             | 0            | 80                  | 0                  | vmtracker      | -1
```

 8、we test to see if the resource group is take effact . the concurrency=1 but I can run parallel  5 SQL use role wdl，which means that resource group is not work.

BTW: I set master and segment in same  one  machine:
```
postgres=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port  | hostname | address |           datadir            
------+---------+------+----------------+------+--------+-------+----------+---------+------------------------------
    1 |      -1 | p    | p              | n    | u      | 15432 | R4412    | R4412   | /data2/gpdata/master/gpseg-1
    2 |       0 | p    | p              | n    | u      | 33000 | R4412    | R4412   | /data2/gpdata/gp1/gpseg0
    3 |       1 | p    | p              | n    | u      | 33001 | R4412    | R4412   | /data2/gpdata/gp2/gpseg1
    4 |       2 | p    | p              | n    | u      | 33002 | R4412    | R4412   | /data2/gpdata/gp3/gpseg2
    5 |       3 | p    | p              | n    | u      | 33003 | R4412    | R4412   | /data2/gpdata/gp4/gpseg3
```
Is resource group not supported on my situation? but  resource queue is supported~

**Comment by xiong-gang** [comment] 2020-04-13 03:48
I did exactly the same steps but cannot reproduce the issue. Can you please check `postgresql.conf` to see if there's a line like `gp_resource_manager='group'` and please also check pg_log to see if there's some detailed information about the warning. Thanks

**Comment by LittleWuCoding** [comment] 2020-04-13 06:00
@xiong-gang  Thanks for your quick reply.
I have check the postgresql.conf and found the line:
```
gp_resource_manager='group'
```
And as for log, 
startup.log
```
2020-04-13 09:22:12.113498 CST,,,p92159,th615721088,,,,0,,,seg-1,,,,,"LOG","00000","redirecting log output to logging collector process",,"Future log output will appear in directory ""pg_log"".",,,,,,"SysLogger_Start","syslogger.c",984,
2020-04-13 09:22:25.830048 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","gpdb dir for cgroup component ""cpu"": /sys/fs/cgroup/cpu/gpdb/",,,,,,,,"dumpCompDirs","resgroup-ops-linux.c",470,
2020-04-13 09:22:25.830354 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","gpdb dir for cgroup component ""cpuacct"": /sys/fs/cgroup/cpuacct/gpdb/",,,,,,,,"dumpCompDirs","resgroup-ops-linux.c",470,
2020-04-13 09:22:25.830641 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","gpdb dir for cgroup component ""memory"": /sys/fs/cgroup/memory/gpdb/",,,,,,,,"dumpCompDirs","resgroup-ops-linux.c",470,
2020-04-13 09:22:25.830974 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","gpdb dir for cgroup component ""cpuset"": /sys/fs/cgroup/cpuset/gpdb/",,,,,,,,"dumpCompDirs","resgroup-ops-linux.c",470,
2020-04-13 09:22:25.832245 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","registering background worker ""ftsprobe process""",,,,,,,,"RegisterBackgroundWorker","bgworker.c",774,
2020-04-13 09:22:25.832577 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","registering background worker ""global deadlock detector process""",,,,,,,,"RegisterBackgroundWorker","bgworker.c",774,
2020-04-13 09:22:25.832837 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","registering background worker ""dtx recovery process""",,,,,,,,"RegisterBackgroundWorker","bgworker.c",774,
2020-04-13 09:22:38.925825 CST,,,p93498,th-1492031360,,,,0,,,seg-1,,,,,"LOG","00000","redirecting log output to logging collector process",,"Future log output will appear in directory ""pg_log"".",,,,,,"SysLogger_Start","syslogger.c",984,
```
csv log is to large to add on, but there is no ERROR here.

**Comment by xiong-gang** [comment] 2020-04-13 07:09
Please paste the detailed log of "WARNING: resource group is disabled", thanks

**Comment by gaos1** [comment] 2020-04-13 09:38
it seems you didn't perform Prerequisite as described in the doc below to setup cgroup properly. please follow the doc to config cgroup on all nodes, and try again:
https://gpdb.docs.pivotal.io/6-6/admin_guide/workload_mgmt_resgroups.html#topic71717999

**Comment by LittleWuCoding** [comment] 2020-04-14 01:23
@xiong-gang  @gaos1  Thanks you all.
I had get it done.
The problem is that somebody changes param **resource_scheduler** to off. Now I turn it to on ,and the problem is solved with restarting the DB.
BTW1:  the param resource_scheduler as well as some other param were not mentioned in the official docs.
BTW2:  when 1) set resource_scheduler to off ;2) create a resource group with CONCURRENCY=0 3) set resource_scheduler to on and restarting DB. The DB start  hang here:
```
20200413:19:49:44:003974 gpstart:R4412:gpadmin-[INFO]:-Command pg_ctl reports Master R4412 instance active
20200413:19:49:44:003974 gpstart:R4412:gpadmin-[INFO]:-Connecting to dbname='template1' connect_timeout=15
```
I think it is puzzling. At the time I connect to master ,and execute SQL, found that my SQL wae hanged even like "select 1". Then I connected to primary segment in utility mode, here I can execute any SELECT SQL. Maybe it is a bug?

**Comment by gaos1** [comment] 2020-04-14 09:56
thanks for update. let's close this issue and please open a new issue for hang problem with related master/primary/mirror logs.  it is not clear to me that you see hang during gpstart or after gpstart yet.

**Closed by gaos1** 2020-04-14 09:56 UTC
