### ISSUE TITLE
expand failed with event trigger

### ISSUE THREAD

**Issue by cstarc** [greenplum-db/gpdb#15276] opened 2023-03-28 01:27 UTC
## Bug Report
expand failed with event trigger

### Greenplum version or build
7.0.0-beta.1
### OS version and uname -a
Linux 10-19-36-11 4.19.90-24.4.v2101.ky10.aarch64 #1 SMP Mon May 24 14:45:37 CST 2021 aarch64 aarch64 aarch64 GNU/Linuxt

### autoconf options used ( config.status --config )
'--prefix=/data/chuhx/stage' '--with-uuid=ossp' '--with-libxml' '--with-openssl' 'CFLAGS=-g' 'CXXFLAGS=-g'

### Installation information ( pg_config )
BINDIR = /data/chuhx/stage/bin
DOCDIR = /data/chuhx/stage/share/doc/postgresql
HTMLDIR = /data/chuhx/stage/share/doc/postgresql
INCLUDEDIR = /data/chuhx/stage/include
PKGINCLUDEDIR = /data/chuhx/stage/include/postgresql
INCLUDEDIR-SERVER = /data/chuhx/stage/include/postgresql/server
LIBDIR = /data/chuhx/stage/lib
PKGLIBDIR = /data/chuhx/lstage/lib/postgresql
LOCALEDIR = /data/chuhx/stage/share/locale
MANDIR = /data/chuhx/stage/share/man
SHAREDIR = /data/chuhx/stage/share/postgresql
SYSCONFDIR = /data/chuhx/stage/etc/postgresql
PGXS = /data/chuhx/stage/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/data/chuhx/stage' '--with-uuid=ossp' '--with-libxml' '--with-openssl' 'CFLAGS=-g' 'CXXFLAGS=-g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -g  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/data/chuhx/stage/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lssl -lcrypto -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -lzstd 

### Expected behavior
expand success

### Actual behavior
expand table failed

20230327:09:33:31:081635 gpexpand:10-19-36-11:chuhx-[INFO]:-Expanding postgres.hint_plan.hints
20230327:09:33:32:081635 gpexpand:10-19-36-11:chuhx-[ERROR]:-Table postgres.hint_plan.hints failed to expand: ERROR:  unrecognized node type: 733 (copyfuncs.c:7014)  (seg1 10.20.137.130:41001 pid=81671) (copyfuncs.c:7014)

### Step to reproduce the behavior
create event trigger on coordinator, then expand segment.  （I found this problem because I was trying to use the pgaudit plug-in and found that expand failed. After looking it up, I found that it was due to the event trigger）

new segment is created by using pg_basebackup from  coordinator. then event trigger will exist on new segment. finilly result in
copyObject(parsetree) in EventTriggerAlterTableStart. but T_AlteredTableInfo type is not processed.

**Comment by SmartKeyerror** [comment] 2023-03-28 01:48
Since the trigger is not supported by Greenplum, I don't know if this is a real BUG, will take some time to look at this.

**Comment by ashwinstar** [comment] 2023-03-28 02:00
Event triggers are supported :-) so its a bug

**Comment by SmartKeyerror** [comment] 2023-03-30 00:47
When I investigate this issue, I found another problem:

```
create table t(a int);

1. create a event trigger function
create or replace function abort_any_ddl() returns event_trigger as
$$
begin
        raise exception 'command % is diabled.', tg_tag;
end
$$
language plpgsql IMMUTABLE;

2. create event trigger
create event trigger abort_drop on ddl_command_start when TAG in ('DROP TABLE') execute function abort_any_ddl();

3. we can not drop table
drop table t;
ERROR:  command DROP TABLE is diabled.
CONTEXT:  PL/pgSQL function abort_any_ddl() line 3 at RAISE

4. expand cluster, add one or more segments

5. drop event trigger
drop event trigger abort_drop;

6. drop table t, since event trigger has been dropped, this should succeed. But it failed, cause `drop event trigger` will not dispatch to the QE, and the new segment was built by pg_basebackup from coordinator
drop table t;
ERROR:  command DROP TABLE is diabled.  (seg3 127.0.1.1:7005 pid=3268892)
CONTEXT:  PL/pgSQL function abort_any_ddl() line 3 at RAISE
```

**Comment by cstarc** [comment] 2023-03-30 01:36
> When I investigate this issue, I found another problem:
> 
> ```
> create table t(a int);
> 
> 1. create a event trigger function
> create or replace function abort_any_ddl() returns event_trigger as
> $$
> begin
>         raise exception 'command % is diabled.', tg_tag;
> end
> $$
> language plpgsql IMMUTABLE;
> 
> 2. create event trigger
> create event trigger abort_drop on ddl_command_start when TAG in ('DROP TABLE') execute function abort_any_ddl();
> 
> 3. we can not drop table
> drop table t;
> ERROR:  command DROP TABLE is diabled.
> CONTEXT:  PL/pgSQL function abort_any_ddl() line 3 at RAISE
> 
> 4. expand cluster, add one or more segments
> 
> 5. drop event trigger
> drop event trigger abort_drop;
> 
> 6. drop table t, since event trigger has been dropped, this should succeed. But it failed, cause `drop event trigger` will not dispatch to the QE, and the new segment was built by pg_basebackup from coordinator
> drop table t;
> ERROR:  command DROP TABLE is diabled.  (seg3 127.0.1.1:7005 pid=3268892)
> CONTEXT:  PL/pgSQL function abort_any_ddl() line 3 at RAISE
> ```

Maybe the event trigger on the segment(seg3 127.0.1.1:7005) was not removed. Normally, there should be no event trigger under the segment. but when expand，there will be

**Comment by SmartKeyerror** [comment] 2023-03-30 02:25
> event trigger need to be EVT_DDLCommandEnd to make trackDroppedObjectsNeeded fuc true. finally make EventTriggerBeginCompleteQuery to set currentEventTriggerState.
> 
> ProcessUtilitySlow EventTriggerBeginCompleteQuery //will set currentEventTriggerState trackDroppedObjectsNeeded // return true, then will set currentEventTriggerState EventTriggerAlterTableStart copyObject(parsetree) here failed.

Yeah, I know that. I have not reproduced this error, could you provide your a simplified script?

**Comment by cstarc** [comment] 2023-03-30 02:44
> > event trigger need to be EVT_DDLCommandEnd to make trackDroppedObjectsNeeded fuc true. finally make EventTriggerBeginCompleteQuery to set currentEventTriggerState.
> > ProcessUtilitySlow EventTriggerBeginCompleteQuery //will set currentEventTriggerState trackDroppedObjectsNeeded // return true, then will set currentEventTriggerState EventTriggerAlterTableStart copyObject(parsetree) here failed.
> 
> Yeah, I know that. I have not reproduced this error, could you provide your a simplified script?

event trigger must be create on ddl_command_end， then type will be EVT_DDLCommandEnd.

**Comment by kainwen** [comment] 2023-04-17 02:10
Fixed by https://github.com/greenplum-db/gpdb/pull/15287

**Closed by kainwen** 2023-04-17 02:10 UTC
Labels: type: bug, version: 7X_ALPHA
