### ISSUE TITLE
Out of memory during resgroup/resgroup_memory_spilltodisk regress test

### ISSUE THREAD

**Issue by Eulerizeit** [greenplum-db/gpdb#3345] opened 2017-09-21 18:48 UTC
Reached out about this earlier and we will enact the proposed fix. This is a reminder if the team wished to look further into the issue. 

> The test machine we use is x2.medium, only have 3GB memory. We run the query 'insert into spilltest2 select a from generate_series(1,400000) a' in admin_group, which has 10% of the host memory. I think your changes on tuplestore made this function scan take too much memory and cause the failure. 
For this test, it's ok to increase the memory_limit use this statement "ALTER RESOURCE GROUP admin_group set memory_limit 30"

**Comment by Eulerizeit** [comment] 2017-09-21 19:51
Note the suggested fix didn't work so we are working to get this test green.

**Comment by jchampio** [comment] 2017-09-21 22:05
The above commit seems to fix issues on our "local" tests; the new resource group under test needed to be changed as well as the `admin_group`. This feels like something we need to get a better solution for.

**Comment by macroyuyang** [comment] 2017-10-31 05:07
The root cause is, for 5.x, the plan for


[12:21] 
 ```insert into spilltest2 select a from generate_series(1,400000)```
, the generate_series is called by projection in ResultNode, which just use memory_context_per_tuple


[12:22] 
But for merge_84, the plan use a function scan node for generate_series:
```lefttree {FUNCTIONSCAN :plan_node_id 3 :startup_cost 0.00 :total_cost 0.00 :plan_rows 1000 :plan_width 4 :targetlist ({TARGETENTRY :expr {VAR :varno 2 :varattno 1 :vartype 23 :vartypmod -1 :varlevelsup 0 :varnoold 2 :varoattno 1} :resno 1 :resname generate_series :ressortgro```


[12:22] 
Then it will use tuple store to store tuples


[12:23] 
There maybe a bug in tuple store:
```/*
 * Similar to tuplestore_puttuple(), but work from values + nulls arrays.
 * This avoids an extra tuple-construction operation.
 */
void
tuplestore_putvalues(Tuplestorestate *state, TupleDesc tdesc,
                     Datum *values, bool *isnull)
{
    MemoryContext oldcxt = MemoryContextSwitchTo(state->context);

    MemTupleBinding *mt_bind = create_memtuple_binding(tdesc);
    MemTuple tuple = memtuple_form_to(mt_bind, values, isnull, NULL, NULL, false);

    USEMEM(state, GetMemoryChunkSpace(tuple));

    tuplestore_puttuple_common(state, (void *) tuple);

    MemoryContextSwitchTo(oldcxt);
}```


[12:24] 
state->context points to memory context of per query. Here we create memtuple using that memory context, as result causes OOM


[12:24] 
Because if state->status == TSS_WRITEFILE, we need to create memtuple for function tuplestore_puttuple_common in temporary memory context instead of per query context


[12:25] 
So the plan changes trigger this tuple store bugs

**Comment by macroyuyang** [comment] 2017-10-31 07:12
One possible fix is call create_memtuple_binding only once, store it in Tuplestorestate, and reuse it every call for tuplestore_putvalues

**Comment by macroyuyang** [comment] 2017-11-15 09:58
The PR https://github.com/greenplum-db/gpdb/pull/3726 already merged and fixed this issue

**Closed by macroyuyang** 2017-11-15 09:58 UTC
Labels: 8.4 Merge
