### ISSUE TITLE
error result for concurrent update of distribution key

### ISSUE THREAD

**Issue by hli1992** [greenplum-db/gpdb#8919] opened 2019-10-26 03:33 UTC
### Greenplum version or build
postgres=# select version();
                                                                             version                                                                              
------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.20 (Greenplum Database 7.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 5.4.0, 64-bit compiled on Aug  9 2019 15:26:08
(1 row)

master branch of gpdb.

I have tested concurrent updating distribution key in gpdb, like:

first session session_1, update distribution key:

postgres=# \d+ t1
                          Table "public.t1"
 Column |  Type   | Modifiers | Storage | Stats target | Description 
--------+---------+-----------+---------+--------------+-------------
 a      | integer |           | plain   |              | 
 b      | integer |           | plain   |              | 
Distributed by: (a)

postgres=# begin;
BEGIN
postgres=# select gp_segment_id, * from t1;
 gp_segment_id | a | b 
---------------+---+---
             0 | 3 | 3
             1 | 1 | 1
(2 rows)

postgres=# update t1 set a = 3 where a = 1;
UPDATE 1

now, open another session session_2 to delete all tuples in t1:

postgres=# begin;
BEGIN
postgres=# select gp_segment_id,* from t1;
 gp_segment_id | a | b 
---------------+---+---
             1 | 1 | 1
             0 | 3 | 3
(2 rows)

postgres=# delete from t1;

session_2 is waiting session_1 to commit.

commit session_1:

postgres=# commit;

session_2 should delete all tuples, but only delete one tuple:
commit session_2:
postgres=# commit;
postgres=# select gp_segment_id,* from t1;
 gp_segment_id | a | b 
---------------+---+---
             0 | 3 | 1
(1 row)

tuples = (3, 1) is from gp_segment_id 1, which is not deleted expected.

And tuples (3, 1) can be deleted in PG.

**Comment by xiong-gang** [comment] 2020-01-13 08:41
Hi @hli1992 ,

Thanks for reporting the issue. I built Greenplum with the commit (38dd2da) on Aug 7, 2019 but I can't reproduce the problem with the same exact steps.

Do you remember what is the top commit you used to build the binary?
Did you hit this issue every time you run the steps, or occasionally?

Thanks.

**Comment by hli1992** [comment] 2020-01-13 09:42
not occasionally, try turn off global deadlock detection GUC option，and retry again.
sorry, i forget the commit id.

**Comment by kainwen** [comment] 2020-04-16 06:27
A pr to fix this on 6X is opened: https://github.com/greenplum-db/gpdb/pull/9939

We will wait for merging finish in master branch and then try to fix this on master branch.

**Comment by asimrp** [comment] 2020-06-18 12:34
Fixed in #9939

**Comment by kainwen** [comment] 2020-06-18 12:42
Hi @asimrp 

Great job to fix this on 6X. Thanks so much!

This need to be fixed in master branch also.

We should wait for master branch merge finish, and then fix. It is much easier to fix on mastrer branch.

So I reopen this.

**Comment by kainwen** [comment] 2020-10-05 13:04
Fixed on master by: https://github.com/greenplum-db/gpdb/pull/10919
on 6X by: https://github.com/greenplum-db/gpdb/pull/9939

**Closed by kainwen** 2020-10-05 13:04 UTC
