### ISSUE TITLE
Core dump when truncation of index with SQL function on AO table

### ISSUE THREAD

**Issue by liming01** [greenplum-db/gpdb#13911] opened 2022-08-08 07:04 UTC
### Greenplum version or build

gpdb7 master branch (top commit 9258ac5) will PANIC; 

gpdb6 (top commit a859132f74) works well.

### OS version and uname -a
```SQL
postgres=# select version();
                                                                                                                 version

------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------
 PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.15454.ga1307499a3 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.2.1 20210130 (Red Ha
t 10.2.1-11), 64-bit compiled on Jun 30 2022 21:18:16 (with assert checking)
(1 row)
```
### Step to reproduce the behavior

The original test case src/test/regress/sql/temp.sql in gpdb6 is testing on heap table, if here change it to the AO table, then it will crash.

```SQL
postgres=# set gp_default_storage_options to 'appendoptimized=TRUE, orientation=row';
ERROR:  invalid storage option "appendoptimized"
HINT:  For table access methods use "default_table_access_method" instead.

postgres=# set default_table_access_method = ao_row;
SET

postgres=# CREATE TEMP TABLE temptest(col int) ON COMMIT DELETE ROWS;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'col' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE

-- while we're here, verify successful truncation of index with SQL function
postgres=# CREATE INDEX ON temptest(bit_length('')); 
FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(ActiveSnapshotSet())", File: "postgres.c", Line: 1009)
CONTEXT:  SQL function "bit_length" during startup
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

#### coredump 
```
...
Core was generated by `postgres:  7000, gpadmin postgres [local] con7 cmd15 CREATE INDEX             '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f2d28907387 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f2d2abd0880 (LWP 4850))]
...
(gdb) bt
#0  0x00007f2d28907387 in raise () from /lib64/libc.so.6
#1  0x00007f2d28908a78 in abort () from /lib64/libc.so.6
#2  0x0000000000d23dc3 in ExceptionalCondition (conditionName=conditionName@entry=0x12ca96b "!(ActiveSnapshotSet())",
    errorType=errorType@entry=0x1265017 "FailedAssertion", fileName=fileName@entry=0x14504bd "postgres.c", lineNumber=lineNumber@entry=1009) at assert.c:40
#3  0x0000000000ba137d in pg_plan_query (querytree=0x88f13c8, cursorOptions=256, boundParams=0x0) at postgres.c:1009
#4  pg_plan_query (querytree=querytree@entry=0x88f13c8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:1000
#5  0x00000000009976f8 in init_execution_state (lazyEvalOK=true, fcache=0x88f0530, queryTree_list=<optimized out>) at functions.c:599
#6  init_sql_fcache (lazyEvalOK=true, collation=100, finfo=<optimized out>) at functions.c:885
#7  fmgr_sql (fcinfo=0x8853758) at functions.c:1188
#8  0x000000000097c857 in ExecInterpExpr (state=<optimized out>, econtext=0x8853bc8, isnull=<optimized out>) at execExprInterp.c:659
#9  0x0000000000abc830 in ExecEvalExprSwitchContext (isNull=0x7ffef85962cc, econtext=<optimized out>, state=0x8853668)
    at ../../../../src/include/executor/executor.h:353
#10 evaluate_expr (expr=<optimized out>, result_type=result_type@entry=23, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0)
    at clauses.c:5156
#11 0x0000000000abca6e in evaluate_function (func_tuple=0x7f2d2aa81c08, func_tuple=0x7f2d2aa81c08, context=0x7ffef85964c0, funcvariadic=false,
    args=0x8943788, input_collid=100, result_collid=0, result_typmod=-1, result_type=23, funcid=1811) at clauses.c:4698
#12 simplify_function (funcid=1811, result_type=23, result_typmod=-1, result_collid=0, input_collid=100, args_p=0x7ffef8596440, funcvariadic=false,
    process_args=true, allow_non_const=true, context=0x7ffef85964c0) at clauses.c:4288
#13 0x0000000000abd432 in eval_const_expressions_mutator (node=<optimized out>, context=0x7ffef85964c0) at clauses.c:2709
#14 0x0000000000a06e3b in expression_tree_mutator (node=<optimized out>, mutator=0xabd2f0 <eval_const_expressions_mutator>, context=0x7ffef85964c0)
    at nodeFuncs.c:3145
#15 0x0000000000abebf4 in eval_const_expressions (root=root@entry=0x0, node=node@entry=0x89436d0) at clauses.c:2495
#16 0x0000000000d0e7a5 in RelationGetIndexExpressions (relation=relation@entry=0x7f2d2aa847e0) at relcache.c:4831
#17 0x0000000000828c28 in BuildIndexInfo (index=index@entry=0x7f2d2aa847e0) at index.c:2269
#18 0x0000000000826b37 in RelationTruncateIndexes (heapRelation=0x7f2d2aa7ebc8) at heap.c:3680
#19 heap_truncate_one_rel (rel=0x7f2d2aa7ebc8) at heap.c:3767
#20 heap_truncate (relids=relids@entry=0x89bfe70) at heap.c:3735
#21 0x000000000093a1a0 in PreCommit_on_commit_actions () at tablecmds.c:18384
#22 0x00000000007c2769 in CommitTransaction () at xact.c:2797
#23 0x00000000007c4515 in CommitTransactionCommand () at xact.c:4016
#24 0x0000000000ba37de in finish_xact_command () at postgres.c:3364
#25 finish_xact_command () at postgres.c:3357
#26 exec_simple_query (query_string=query_string@entry=0x86b58c0 "CREATE INDEX ON temptest(bit_length(''));") at postgres.c:1952
#27 0x0000000000ba5b1b in PostgresMain (argc=<optimized out>, argv=argv@entry=0x86e5e58, dbname=<optimized out>, username=<optimized out>)
    at postgres.c:5350
#28 0x0000000000af99cf in BackendRun (port=0x86de3c0) at postmaster.c:4951
#29 BackendStartup (port=0x86de3c0) at postmaster.c:4636
#30 ServerLoop () at postmaster.c:1964
#31 0x0000000000afa7a5 in PostmasterMain (argc=argc@entry=5, argv=0x7ffef85973a0, argv@entry=0x86b0200) at postmaster.c:1590
#32 0x00000000006f4386 in main (argc=5, argv=0x86b0200) at main.c:240
```

**Comment by SmartKeyerror** [comment] 2022-08-08 10:33
Actually, QD will PANIC even if the default storage is the heap, so this issue is irrelevant to what storage we chose:

```sql
postgres=# show default_table_access_method;
 default_table_access_method 
-----------------------------
 heap
(1 row)

postgres=# CREATE TEMP TABLE temptest(col int) ON COMMIT DELETE ROWS;

postgres=# CREATE INDEX ON temptest(bit_length('')); 
FATAL:  Unexpected internal error (assert.c:44)
DETAIL:  FailedAssertion("!(ActiveSnapshotSet())", File: "postgres.c", Line: 1009)
CONTEXT:  SQL function "bit_length" during startup
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by kainwen** [comment] 2022-08-08 12:58
Thanks for reporting.

This bug is from upstream, and upstream has fixed it by https://github.com/postgres/postgres/commit/b154d70f743039452f2cadee9566d754e79e3653.

The above commit contains in postgres:

```
gpadmin@zlyu:~/workspace/postgres$ git tag --contains b154d70f743039452f2cadee9566d754e79e3653
REL_12_10
REL_12_11
REL_12_2
REL_12_3
REL_12_4
REL_12_5
REL_12_6
REL_12_7
REL_12_8
REL_12_9
```

Then I checkout to 12.1 and reproduce under Postgres 12.1:

```
gpadmin=# select version();
                                                version
-------------------------------------------------------------------------------------------------------
 PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)

gpadmin=# CREATE TEMP TABLE temptest(col int) ON COMMIT DELETE ROWS;
CREATE TABLE
gpadmin=# CREATE INDEX ON temptest(bit_length(''));
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
gpadmin=#
```

The core dump' stack is the same:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fca04373859 in __GI_abort () at abort.c:79
#2  0x000055897cbf7d0a in ExceptionalCondition (conditionName=conditionName@entry=0x55897cc9ac1e "!(ActiveSnapshotSet())", errorType=errorType@entry=0x55897cc4e01d "FailedAssertion", fileName=fileName@entry=0x55897cdcc148 "postgres.c",
    lineNumber=lineNumber@entry=870) at assert.c:54
#3  0x000055897cacfc2b in pg_plan_query (querytree=0x55897d96c370, cursorOptions=256, boundParams=0x0) at postgres.c:870
#4  pg_plan_query (querytree=querytree@entry=0x55897d96c370, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:861
#5  0x000055897c963d3f in init_execution_state (lazyEvalOK=true, fcache=0x55897d96b518, queryTree_list=<optimized out>) at functions.c:507
#6  init_sql_fcache (lazyEvalOK=true, collation=<optimized out>, finfo=<optimized out>) at functions.c:770
#7  fmgr_sql (fcinfo=0x55897d969810) at functions.c:1053
#8  0x000055897c94f569 in ExecInterpExpr (state=0x55897d969720, econtext=0x55897d969c80, isnull=<optimized out>) at execExprInterp.c:649
#9  0x000055897ca16be4 in ExecEvalExprSwitchContext (isNull=0x7ffe648e77c4, econtext=<optimized out>, state=0x55897d969720) at ../../../../src/include/executor/executor.h:307
#10 evaluate_expr (expr=<optimized out>, result_type=result_type@entry=23, result_typmod=result_typmod@entry=-1, result_collation=result_collation@entry=0) at clauses.c:4827
#11 0x000055897ca18503 in evaluate_function (context=0x7ffe648e7a80, func_tuple=0x7fc9fb159b48, funcvariadic=false, args=0x55897d95e490, input_collid=100, result_collid=0, result_typmod=-1, result_type=23, funcid=1811) at clauses.c:4369
#12 simplify_function (funcid=1811, result_type=23, result_typmod=-1, result_collid=0, input_collid=100, args_p=<optimized out>, funcvariadic=false, process_args=true, allow_non_const=true, context=0x7ffe648e7a80) at clauses.c:3999
#13 0x000055897ca16dea in eval_const_expressions_mutator (node=0x55897d95de58, context=0x7ffe648e7a80) at clauses.c:2474
#14 0x000055897c9a94bb in expression_tree_mutator (node=node@entry=0x55897d95e3d8, mutator=mutator@entry=0x55897ca16cb0 <eval_const_expressions_mutator>, context=context@entry=0x7ffe648e7a80) at nodeFuncs.c:2996
#15 0x000055897ca16d12 in eval_const_expressions_mutator (node=0x55897d95e3d8, context=0x7ffe648e7a80) at clauses.c:3606
#16 0x000055897ca18363 in eval_const_expressions (root=root@entry=0x0, node=node@entry=0x55897d95e3d8) at clauses.c:2266
#17 0x000055897cbee8a2 in RelationGetIndexExpressions (relation=relation@entry=0x7fc9fb15b9e8) at relcache.c:4648
#18 0x000055897c849aec in BuildIndexInfo (index=index@entry=0x7fc9fb15b9e8) at index.c:2307
#19 0x000055897c8443c7 in RelationTruncateIndexes (heapRelation=heapRelation@entry=0x7fc9fb158958) at heap.c:3153
#20 0x000055897c847c6c in heap_truncate_one_rel (rel=rel@entry=0x7fc9fb158958) at heap.c:3235
#21 0x000055897c84802c in heap_truncate (relids=relids@entry=0x55897d95c8f8) at heap.c:3203
#22 0x000055897c9252bd in PreCommit_on_commit_actions () at tablecmds.c:14656
#23 0x000055897c822997 in CommitTransaction () at xact.c:2108
#24 0x000055897c823ff5 in CommitTransactionCommand () at xact.c:3062
#25 0x000055897cace441 in finish_xact_command () at postgres.c:2577
#26 finish_xact_command () at postgres.c:2570
#27 0x000055897cad0191 in exec_simple_query (query_string=0x55897d89c648 "CREATE INDEX ON temptest(bit_length(''));") at postgres.c:1240
#28 0x000055897cad18af in PostgresMain (argc=<optimized out>, argv=argv@entry=0x55897d8c7658, dbname=<optimized out>, username=<optimized out>) at postgres.c:4236
#29 0x000055897ca484d2 in BackendRun (port=0x55897d8c0760, port=0x55897d8c0760) at postmaster.c:4437
#30 BackendStartup (port=0x55897d8c0760) at postmaster.c:4128
#31 ServerLoop () at postmaster.c:1704
#32 0x000055897ca493b0 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1377
#33 0x000055897c77416f in main (argc=3, argv=0x55897d896fb0) at main.c:228
```

We will merge to pg's latest stable version for GP7, and merge to next major version pg for master when next merging.

Do we need to keep this open?  @ashwinstar

**Comment by kainwen** [comment] 2022-08-08 13:07
After cherry-pick from postgres to gpdb master (current top commit 611b788d18d6f1ad5235267aee68dc9925eeee96):

1. abb8492e08607545ce1eb3fb49517610f70467f1
2. 1b6747a5c3b32d01b224b2f7a47f2a1f775521a8

I run the SQL successfully:

```
psql (12beta2)
Type "help" for help.

gpadmin=# CREATE TEMP TABLE temptest(col int) ON COMMIT DELETE ROWS;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'col' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
gpadmin=# CREATE INDEX ON temptest(bit_length(''));
CREATE INDEX
gpadmin=#
```

**Comment by kainwen** [comment] 2022-08-08 22:54
Close this, since we definitely will catch up with later Postgres.

**Closed by kainwen** 2022-08-08 22:54 UTC
Labels: type: bug, version: 7X_ALPHA
