### ISSUE TITLE
pg_catalog.pg_statistic table size is keep on increasing in size in newly added segments.

### ISSUE THREAD

**Issue by aakashmuthuramalingam** [greenplum-db/gpdb#15847] opened 2023-06-26 12:01 UTC
Bug Report

Greenplum version or build:  'PostgreSQL 9.4.24 (Greenplum Database 6.17.2 build commit:066d9756210ec8123d984408916ccc5b31d675bf Open Source) on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit compiled on Aug 12 2021 22:07:05'

OS version and uname -a: Linux prod-gp-node-1-11 4.15.0-166-generic #174-Ubuntu SMP Wed Dec 8 19:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Expected behavior

We had 10 segment servers. Last week, we added two more segments for scaling purpose. Since then, we could see more disk space being used on the segments 11 and 12. It varies 100G increased value than the older segments.

We had not performed rebalance as we daily drop and recreates database at night.

As debugged further, on the new segments, the following table is occupying more space than the rest 10.

` 

> On 1-10
> 
> du -sh 12537
> 224K	12537
> 
> 
> On seg 11 and 12
> du -sh * | grep G
> 1.0G	12537
> 4.0K	PG_VERSION
> 
>  select
>     n.nspname AS tableschema,
>     c.relname AS tablename
> from pg_class c
> inner join pg_namespace n on (c.relnamespace = n.oid)
> where c.relfilenode =12537;
>  tableschema |  tablename
> -------------+--------------
>  pg_catalog  | pg_statistic
> (1 row)
> 
>  SELECT gp_segment_id, count(*) FROM pg_catalog.pg_statistic GROUP BY gp_segment_id order by 2 desc;
>  gp_segment_id | count
> ---------------+-------
>             -1 |  2766
> (1 row)
> `

on all databases, it is occupying huge size.

**Comment by ashwinstar** [comment] 2023-06-26 13:03
I believe the reason for same is new segments are created by copying master data directory. Master maintains stats and hence pg_statistics copied from master is having bigger size compared to other segments in the cluster. (purely guessing based on information provided). Thank you so much for fantastic details. Will let team look into it further @wenwangBJ

**Comment by yanwr1** [comment] 2023-09-05 09:28
The pg_catalog.pg_statistic table size keep on increasing issue still can't be reproduced.
In theory, the segment node won't store user tables' statistic info.  Can you provide more details about the operations after add segments?

**Comment by adam8157** [comment] 2024-03-11 07:51
Not reproduced, closing. Feel free to reopen it with more details.

**Closed by adam8157** 2024-03-11 07:51 UTC
Labels: type: bug, topic: gpexpand, version: 6X_STABLE, version: 7X_ALPHA, Priority 2
