### ISSUE TITLE
selecting from external table return empty rows

### ISSUE THREAD

**Issue by xiaoxiaoHe-E** [greenplum-db/gpdb#10982] opened 2020-10-15 09:06 UTC
### autoconf options used ( config.status --config )
`$ ./configure --disable-orca --without-perl --without-python --with-libxml --without-gssapi --disable-pxf --without-zstd`

### Expected behavior
It should report errors.

### Actual behavior
It returns successfully with empty data

### Step to reproduce the behavior
```sql
test=# create external table aaa (c1 int) location ('gpfdist://aaaa:8080/abc.txt') format 'csv';
CREATE EXTERNAL TABLE
test=# select * from aaa;
 c1
----
(0 rows)
```

```sql
test=# create external table bbb (c1 int) location ('file://sdw/abc/d') format 'csv';
CREATE EXTERNAL TABLE
test=# select * from  bbb;
 c1
----
(0 rows)
```

**Comment by pf-qiu** [comment] 2020-10-16 09:44
This issue is caused by incorrect python environment, not a gpdb bug actually.
If submodule ```gpMgmt/bin/pythonSrc/ext``` is not initialized, or system shell default to python2 path, gpinitisystem can't correctly setup the cluster, but reports success.
Only master node is started in utility mode, and thus nothing is executed on segment. We will get empty result then.
Closing this issue.

**Closed** 2020-10-16 09:44 UTC
Labels: area: clients, type: bug

**Comment by ashwinstar** [comment] 2020-10-16 16:29
@pf-qiu shouldn't we emit some error if expecting to connect in dispatch mode but connected to master only mode and ran the query. Silently passing with empty data seems not good behavior.

**Comment by lij55** [comment] 2020-10-17 10:38
so is it better if we could raise error if the cluster is not initialized successfully?

**Comment by asimrp** [comment] 2020-10-19 07:35
Yes, `gpinitsystem` should not report success if it couldn't initialize segments.

**Comment by pf-qiu** [comment] 2020-10-19 07:43
I agree. Although it's not bug of external table, we need to investigate further and find out the necessary safe guards to prevent this kind of issue.
