### ISSUE TITLE
how to deal with test case restore_memory_accounting_default

### ISSUE THREAD

**Issue by chenbaggio** [greenplum-db/gpdb#11983] opened 2021-05-13 14:15 UTC
### Greenplum version or build
gpdb 6x_stabled
### OS version and uname -a
Linux 192.168.10.200vagrant.hashdata.vm 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
testcase  `src/test/isolation2/sql/restore_memory_accounting_default.sql` can pass

### Actual behavior
cluster crashed
### Step to reproduce the behavior
run sql in `restore_memory_accounting_default.sql` 

gpconfig -c gp_vmem_limit_per_query -v '0' --skipvalidation 

*** Notice --skipvalidation  *** if not set, the sql will report error

but after run the command, then run gpstop -ari, the cluster can not work evenly start up (many users report the same result)

the following question:

whether the test case `restore_memory_accounting_default.sql`  is still valid to test

**Comment by paul-guo-** [comment] 2021-05-17 07:24
I'm not able to recreate on 6X.

```
gpconfig -c gp_vmem_limit_per_query -v '0' --skipvalidation
gpstop -rai
psql -c 'create table t2 (a int);'
```

You can check the pg log to see why does your error happen.

**Comment by paul-guo-** [comment] 2021-05-25 06:52
Closing this one since it is almost not a bug. Feel free to reopen it when having more details.

**Closed by paul-guo-** 2021-05-25 06:52 UTC
Labels: version: 6X_STABLE
