### ISSUE TITLE
segment coredump while running query due to lateral join

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#10013] opened 2020-04-28 07:33 UTC
### Greenplum version or build
6.5 

### OS version and uname -a
centos 7.2

### Step to reproduce the behavior
Find segment coredump  while running query on gp6.5
The sql as follow:

```
WITH t1 AS (
SELECT distinct cast(lower(u.email) as character varying) as email, cast(lower(SPLIT_PART(u.email,'@',1)) as character varying) as user_name, ut.territoryid
FROM rpl_salesforce_ec.userterritory ut
JOIN rpl_salesforce_ec.user u
ON ut.userid = u.id
WHERE u.isactive = 'true'
AND ut.isactive = 'true'
)

SELECT t1.email, c.center_name, t1.user_name,ct.city__c as city_code,ct.country__c as country_name,
ct.id as center_sfid,ct.region__c as region_name,ct.code__c as center_code,ct.company_code__c as company_code,now() as createdtime 
FROM t1
join lateral (
	with RECURSIVE  s as (
	select pt.name,pt.id, pt.parentterritoryid
	from rpl_salesforce_ec.territory  pt
	where id = t1.territoryid
```

 The client get error as follow:
```
ERROR:  Error on receive from seg0 slice3 *.*.*.*:40000 pid=2175: server closed the connection unexpectedly
DETAIL:  
        This probably means the server terminated abnormally
        before or while processing the request.
```

The segment log error as follow:
```
2020-04-27 10:36:17.747806 CST,,,p2181,th0,,,2020-04-27 10:36:05 CST,0,con117576,cmd4,seg0,sl
ice4,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",
,,,,,,0,,,,"1    0x9dac23 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x173
2    0x7f2c41ba75e0 libpthread.so.0 <symbol not found> + 0x41ba75e0
3    0x514b80 postgres toast_raw_datum_size + 0x0
4    0x98cd68 postgres texteq + 0x28
5    0x6bff58 postgres <symbol not found> + 0x6bff58
6    0x6c4b36 postgres ExecQual + 0x96
7    0x6c549f postgres ExecScan + 0xcf
8    0x6b7e08 postgres ExecProcNode + 0x408
9    0x6f580c postgres ExecMotion + 0x5c
10   0x6b7c48 postgres ExecProcNode + 0x248
11   0x6af725 postgres <symbol not found> + 0x6af725
12   0x6b0342 postgres standard_ExecutorRun + 0x3d2
13   0x87bb38 postgres <symbol not found> + 0x87bb38
14   0x87d77f postgres PortalRun + 0x26f
15   0x875de5 postgres <symbol not found> + 0x875de5
16   0x87aea1 postgres PostgresMain + 0x2171
17   0x4cc5ae postgres <symbol not found> + 0x4cc5ae
18   0x8035c7 postgres PostmasterMain + 0x10a7
19   0x4ce7eb postgres main + 0x1db
20   0x7f2c40fd4c05 libc.so.6 __libc_start_main + 0xf5
21   0x4ceff1 postgres <symbol not found> + 0x4ceff1
"
```

The attached file is the table schema, you can reproduce the error.
Any suggestion would be helpful.

[table_schema.txt](https://github.com/greenplum-db/gpdb/files/4544040/table_schema.txt)

**Comment by kainwen** [comment] 2020-04-28 23:05
Hi @lambgong 

I may know the root cause, but:

1. This SQL you posted here is not complete, **it misses some key parts(which is very important)**. Can you please provide the full SQL ? (See the bottom of the SQL):
2. Would you please also post the plan of this SQL here? **It is very important.** You can run `explain select xxx` to get the query plan.

```sql
WITH t1 AS (
SELECT distinct cast(lower(u.email) as character varying) as email, cast(lower(SPLIT_PART(u.email,'@',1)) as character varying) as user_name, ut.territoryid
FROM rpl_salesforce_ec.userterritory ut
JOIN rpl_salesforce_ec.user u
ON ut.userid = u.id
WHERE u.isactive = 'true'
AND ut.isactive = 'true'
)

SELECT t1.email, c.center_name, t1.user_name,ct.city__c as city_code,ct.country__c as country_name,
ct.id as center_sfid,ct.region__c as region_name,ct.code__c as center_code,ct.company_code__c as company_code,now() as createdtime 
FROM t1
join lateral (
	with RECURSIVE  s as (
	select pt.name,pt.id, pt.parentterritoryid
	from rpl_salesforce_ec.territory  pt
	where id = t1.territoryid

-- what's the part of SQL here ???????????
```

**Comment by lambgong** [comment] 2020-04-29 02:09
Sorry, the complete query sql:

```
WITH t1 AS (
SELECT distinct cast(lower(u.email) as character varying) as email, cast(lower(SPLIT_PART(u.email,'@',1)) as character varying) as user_name, ut.territoryid
FROM rpl_salesforce_ec.userterritory ut
JOIN rpl_salesforce_ec.user u
ON ut.userid = u.id
WHERE u.isactive = 'true'
AND ut.isactive = 'true'
)

SELECT t1.email, c.center_name, t1.user_name,ct.city__c as city_code,ct.country__c as country_name,
ct.id as center_sfid,ct.region__c as region_name,ct.code__c as center_code,ct.company_code__c as company_code,now() as createdtime 
FROM t1
join lateral (
	with RECURSIVE  s as (
	select pt.name,pt.id, pt.parentterritoryid
	from rpl_salesforce_ec.territory  pt
	where id = t1.territoryid
	union 
	select h.name,h.id,h.parentterritoryid
	from rpl_salesforce_ec.territory as h
	join s  on h.parentterritoryid = s.id
	)
	select  s.name as center_name,s.id as territory_id  from s
	join rpl_salesforce_ec.center_info__c c1
	on s.name = c1.name
) as c on true
join rpl_salesforce_ec.center_info__c ct
on ct.name = c.center_name
```

the query explain as follow:
```
 Nested Loop  (cost=10000000013.25..10000000579.13 rows=42665 width=287)
   ->  Gather Motion 2:1  (slice3; segments: 2)  (cost=0.00..10.60 rows=265 width=118)
         ->  HashAggregate  (cost=2666.68..2669.33 rows=133 width=118)
               Group Key: ((lower((u.email)::text))::character varying), ((lower(split_part((
u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
               ->  Redistribute Motion 2:2  (slice2; segments: 2)  (cost=2654.76..2662.04 row
s=133 width=118)
                     Hash Key: ((lower((u.email)::text))::character varying), ((lower(split_p
art((u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
                     ->  HashAggregate  (cost=2654.76..2656.74 rows=133 width=118)
                           Group Key: (lower((u.email)::text))::character varying, (lower(spl
it_part((u.email)::text, '@'::text, 1)))::character varying, ut.territoryid
                           ->  Hash Join  (cost=2241.45..2652.77 rows=133 width=38)
                                 Hash Cond: ((ut.userid)::text = (u.id)::text)
                                 ->  Seq Scan on userterritory ut  (cost=0.00..389.23 rows=17
45 width=38)
                                       Filter: ((isactive)::text = 'true'::text)
                                 ->  Hash  (cost=2166.68..2166.68 rows=2991 width=38)
                                       ->  Broadcast Motion 2:2  (slice1; segments: 2)  (cost
=0.00..2166.68 rows=2991 width=38)
                                             ->  Seq Scan on "user" u  (cost=0.00..2076.95 ro
ws=1496 width=38)
                                                   Filter: ((isactive)::text = 'true'::text)
   ->  Materialize  (cost=13.25..35.62 rows=81 width=223)
         ->  Hash Join  (cost=13.25..34.81 rows=161 width=223)
               Hash Cond: ((c.center_name)::text = (ct.name)::text)
               ->  Subquery Scan on c  (cost=6.62..25.97 rows=161 width=178)
                     ->  Hash Join  (cost=6.62..24.36 rows=161 width=232)
                           Hash Cond: ((s.name)::text = (c1.name)::text)
                           ->  Subquery Scan on s  (cost=0.00..13.59 rows=680 width=232)
                                 ->  Recursive Union  (cost=0.00..73.55 rows=680 width=45)
                                       ->  Gather Motion 1:1  (slice4; segments: 1)  (cost=0.
00..2.97 rows=1 width=45)
                                             ->  Seq Scan on territory pt  (cost=0.00..2.96 r
ows=1 width=45)
                                                   Filter: ((id)::text = (ut.territoryid)::te
xt)
                                       ->  Hash Join  (cost=4.53..5.70 rows=68 width=45)
                                             Hash Cond: ((s_1.id)::text = (h.parentterritoryi
d)::text)
                                             ->  WorkTable Scan on s s_1  (cost=0.00..0.20 ro
ws=10 width=54)
                                             ->  Hash  (cost=2.57..2.57 rows=79 width=45)
                                                   ->  Gather Motion 1:1  (slice5; segments: 
1)  (cost=2.57..2.57 rows=157 width=45)
                                                         ->  Seq Scan on territory h  (cost=0
.00..2.57 rows=157 width=45)
                           ->  Hash  (cost=4.61..4.61 rows=81 width=7)
                                 ->  Gather Motion 1:1  (slice6; segments: 1)  (cost=4.61..4.
61 rows=161 width=7)
                                       ->  Seq Scan on center_info__c c1  (cost=0.00..4.61 ro
ws=161 width=7)
               ->  Hash  (cost=4.61..4.61 rows=81 width=52)
                     ->  Gather Motion 1:1  (slice7; segments: 1)  (cost=4.61..4.61 rows=161 
width=52)
                           ->  Seq Scan on center_info__c ct  (cost=0.00..4.61 rows=161 width
=52)
 Optimizer: Postgres query optimizer
(40 rows)
```

**Comment by kainwen** [comment] 2020-04-29 04:37
From the plan, I see the root cause. The is a lateral join, and Greenplum is MPP database and does not support passing params across motion.

The non-recursive part of the recursive cte query adds a motion above params ref:

```
Recursive Union  (cost=0.00..73.55 rows=680 width=45)
                                       ->  Gather Motion 1:1  (slice4; segments: 1)  
                                             ->  Seq Scan on territory pt  =
                                                   Filter: ((id)::text = (ut.territoryid)::text)
```

Params of outer is `(ut.territoryid)::text)`.

I think this issue can be fixed by pull-up the filter. Will spike to fix it.

Thanks for reporting this.

**Comment by lambgong** [comment] 2020-04-29 07:39
Thanks for you reply, but i don't get the way pull-up the filter.

Is that mean the follow query:

```
WITH t1 AS (
SELECT distinct cast(lower(u.email) as character varying) as email, cast(lower(SPLIT_PART(u.email,'@',1)) as character varying) as user_name, ut.territoryid
FROM rpl_salesforce_ec.userterritory ut
JOIN rpl_salesforce_ec.user u
ON ut.userid = u.id
WHERE u.isactive = 'true'
AND ut.isactive = 'true'
)

SELECT t1.email, c.center_name, t1.user_name,ct.city__c as city_code,ct.country__c as country_name,
ct.id as center_sfid,ct.region__c as region_name,ct.code__c as center_code,ct.company_code__c as company_code,now() as createdtime 
FROM t1
join lateral (
	with RECURSIVE  s as (
	select pt.name,pt.id, pt.parentterritoryid
	from rpl_salesforce_ec.territory  pt
	union 
	select h.name,h.id,h.parentterritoryid
	from rpl_salesforce_ec.territory as h
	join s  on h.parentterritoryid = s.id
	)
	select  s.name as center_name,s.id as territory_id  from s
	join rpl_salesforce_ec.center_info__c c1
	on s.name = c1.name
	where s.id = t1.territoryid
) as c on true
join rpl_salesforce_ec.center_info__c ct
on ct.name = c.center_name
```

But gp seems don't support this sql
```
ERROR:  illegal rescan of motion node: invalid plan (nodeMotion.c:1623)
HINT:  Likely caused by bad NL-join, try setting enable_nestloop to off
```
By the way, the enable_nestloop  set to off already

The query explain as follow:
```
 Nested Loop  (cost=10000000068.73..10000000104.31 rows=1943 width=287)
   ->  Gather Motion 2:1  (slice3; segments: 2)  (cost=0.00..10.60 rows=265 width=118)
         ->  HashAggregate  (cost=2666.68..2669.33 rows=133 width=118)
               Group Key: ((lower((u.email)::text))::character varying), ((lower(split_part((
u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
               ->  Redistribute Motion 2:2  (slice2; segments: 2)  (cost=2654.76..2662.04 row
s=133 width=118)
                     Hash Key: ((lower((u.email)::text))::character varying), ((lower(split_p
art((u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
                     ->  HashAggregate  (cost=2654.76..2656.74 rows=133 width=118)
                           Group Key: (lower((u.email)::text))::character varying, (lower(spl
it_part((u.email)::text, '@'::text, 1)))::character varying, ut.territoryid
                           ->  Hash Join  (cost=2241.45..2652.77 rows=133 width=38)
                                 Hash Cond: ((ut.userid)::text = (u.id)::text)
                                 ->  Seq Scan on userterritory ut  (cost=0.00..389.23 rows=17
45 width=38)
                                       Filter: ((isactive)::text = 'true'::text)
                                 ->  Hash  (cost=2166.68..2166.68 rows=2991 width=38)
                                       ->  Broadcast Motion 2:2  (slice1; segments: 2)  (cost
=0.00..2166.68 rows=2991 width=38)
                                             ->  Seq Scan on "user" u  (cost=0.00..2076.95 ro
ws=1496 width=38)
                                                   Filter: ((isactive)::text = 'true'::text)
   ->  Materialize  (cost=68.73..69.45 rows=4 width=223)
         ->  Hash Join  (cost=68.73..69.41 rows=8 width=223)
               Hash Cond: ((ct.name)::text = (c.center_name)::text)
               ->  Gather Motion 1:1  (slice4; segments: 1)  (cost=4.61..4.61 rows=161 width=
52)
                     ->  Seq Scan on center_info__c ct  (cost=0.00..4.61 rows=161 width=52)
               ->  Hash  (cost=64.03..64.03 rows=4 width=178)
                     ->  Subquery Scan on c  (cost=63.28..64.03 rows=8 width=178)
                           ->  Hash Join  (cost=63.28..63.96 rows=8 width=232)
                                 Hash Cond: ((c1.name)::text = (s.name)::text)
                                 ->  Gather Motion 1:1  (slice5; segments: 1)  (cost=4.61..4.
61 rows=161 width=7)
                                       ->  Seq Scan on center_info__c c1  (cost=0.00..4.61 ro
ws=161 width=7)
                                 ->  Hash  (cost=58.64..58.64 rows=2 width=232)
                                       ->  Subquery Scan on s  (cost=0.00..58.64 rows=3 width
=232)
                                             Filter: ((s.id)::text = (ut.territoryid)::text)
                                             ->  Recursive Union  (cost=0.00..892.53 rows=260
7 width=45)
                                                   ->  Gather Motion 1:1  (slice6; segments: 
1)  (cost=0.00..4.14 rows=157 width=45)
                                                         ->  Seq Scan on territory pt  (cost=
0.00..2.57 rows=157 width=45)
                                                   ->  Hash Join  (cost=4.53..83.78 rows=245 
width=45)
                                                         Hash Cond: ((s_1.id)::text = (h.pare
ntterritoryid)::text)
                                                         ->  WorkTable Scan on s s_1  (cost=0
.00..31.40 rows=1570 width=54)
                                                         ->  Hash  (cost=2.57..2.57 rows=79 w
idth=45)
                                                               ->  Gather Motion 1:1  (slice7
; segments: 1)  (cost=2.57..2.57 rows=157 width=45)
                                                                     ->  Seq Scan on territor
y h  (cost=0.00..2.57 rows=157 width=45)
 Optimizer: Postgres query optimizer
(40 rows)
```

**Comment by kainwen** [comment] 2020-04-29 07:58
> Thanks for you reply, but i don't get the way pull-up the filter.
> 
> Is that mean the follow query, i pull the filter out of the cte recursive block:
> 
> ```
> WITH t1 AS (
> SELECT distinct cast(lower(u.email) as character varying) as email, cast(lower(SPLIT_PART(u.email,'@',1)) as character varying) as user_name, ut.territoryid
> FROM rpl_salesforce_ec.userterritory ut
> JOIN rpl_salesforce_ec.user u
> ON ut.userid = u.id
> WHERE u.isactive = 'true'
> AND ut.isactive = 'true'
> )
> 
> SELECT t1.email, c.center_name, t1.user_name,ct.city__c as city_code,ct.country__c as country_name,
> ct.id as center_sfid,ct.region__c as region_name,ct.code__c as center_code,ct.company_code__c as company_code,now() as createdtime 
> FROM t1
> join lateral (
> 	with RECURSIVE  s as (
> 	select pt.name,pt.id, pt.parentterritoryid
> 	from rpl_salesforce_ec.territory  pt
> 	union 
> 	select h.name,h.id,h.parentterritoryid
> 	from rpl_salesforce_ec.territory as h
> 	join s  on h.parentterritoryid = s.id
> 	)
> 	select  s.name as center_name,s.id as territory_id  from s
> 	join rpl_salesforce_ec.center_info__c c1
> 	on s.name = c1.name
> 	where s.id = t1.territoryid
> ) as c on true
> join rpl_salesforce_ec.center_info__c ct
> on ct.name = c.center_name
> ```
> 
> But gp seems don't support this sql
> 
> ```
> ERROR:  illegal rescan of motion node: invalid plan (nodeMotion.c:1623)
> HINT:  Likely caused by bad NL-join, try setting enable_nestloop to off
> ```
> 
> By the way, the enable_nestloop set to off already
> 
> The query explain as follow:
> 
> ```
>  Nested Loop  (cost=10000000068.73..10000000104.31 rows=1943 width=287)
>    ->  Gather Motion 2:1  (slice3; segments: 2)  (cost=0.00..10.60 rows=265 width=118)
>          ->  HashAggregate  (cost=2666.68..2669.33 rows=133 width=118)
>                Group Key: ((lower((u.email)::text))::character varying), ((lower(split_part((
> u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
>                ->  Redistribute Motion 2:2  (slice2; segments: 2)  (cost=2654.76..2662.04 row
> s=133 width=118)
>                      Hash Key: ((lower((u.email)::text))::character varying), ((lower(split_p
> art((u.email)::text, '@'::text, 1)))::character varying), ut.territoryid
>                      ->  HashAggregate  (cost=2654.76..2656.74 rows=133 width=118)
>                            Group Key: (lower((u.email)::text))::character varying, (lower(spl
> it_part((u.email)::text, '@'::text, 1)))::character varying, ut.territoryid
>                            ->  Hash Join  (cost=2241.45..2652.77 rows=133 width=38)
>                                  Hash Cond: ((ut.userid)::text = (u.id)::text)
>                                  ->  Seq Scan on userterritory ut  (cost=0.00..389.23 rows=17
> 45 width=38)
>                                        Filter: ((isactive)::text = 'true'::text)
>                                  ->  Hash  (cost=2166.68..2166.68 rows=2991 width=38)
>                                        ->  Broadcast Motion 2:2  (slice1; segments: 2)  (cost
> =0.00..2166.68 rows=2991 width=38)
>                                              ->  Seq Scan on "user" u  (cost=0.00..2076.95 ro
> ws=1496 width=38)
>                                                    Filter: ((isactive)::text = 'true'::text)
>    ->  Materialize  (cost=68.73..69.45 rows=4 width=223)
>          ->  Hash Join  (cost=68.73..69.41 rows=8 width=223)
>                Hash Cond: ((ct.name)::text = (c.center_name)::text)
>                ->  Gather Motion 1:1  (slice4; segments: 1)  (cost=4.61..4.61 rows=161 width=
> 52)
>                      ->  Seq Scan on center_info__c ct  (cost=0.00..4.61 rows=161 width=52)
>                ->  Hash  (cost=64.03..64.03 rows=4 width=178)
>                      ->  Subquery Scan on c  (cost=63.28..64.03 rows=8 width=178)
>                            ->  Hash Join  (cost=63.28..63.96 rows=8 width=232)
>                                  Hash Cond: ((c1.name)::text = (s.name)::text)
>                                  ->  Gather Motion 1:1  (slice5; segments: 1)  (cost=4.61..4.
> 61 rows=161 width=7)
>                                        ->  Seq Scan on center_info__c c1  (cost=0.00..4.61 ro
> ws=161 width=7)
>                                  ->  Hash  (cost=58.64..58.64 rows=2 width=232)
>                                        ->  Subquery Scan on s  (cost=0.00..58.64 rows=3 width
> =232)
>                                              Filter: ((s.id)::text = (ut.territoryid)::text)
>                                              ->  Recursive Union  (cost=0.00..892.53 rows=260
> 7 width=45)
>                                                    ->  Gather Motion 1:1  (slice6; segments: 
> 1)  (cost=0.00..4.14 rows=157 width=45)
>                                                          ->  Seq Scan on territory pt  (cost=
> 0.00..2.57 rows=157 width=45)
>                                                    ->  Hash Join  (cost=4.53..83.78 rows=245 
> width=45)
>                                                          Hash Cond: ((s_1.id)::text = (h.pare
> ntterritoryid)::text)
>                                                          ->  WorkTable Scan on s s_1  (cost=0
> .00..31.40 rows=1570 width=54)
>                                                          ->  Hash  (cost=2.57..2.57 rows=79 w
> idth=45)
>                                                                ->  Gather Motion 1:1  (slice7
> ; segments: 1)  (cost=2.57..2.57 rows=157 width=45)
>                                                                      ->  Seq Scan on territor
> y h  (cost=0.00..2.57 rows=157 width=45)
>  Optimizer: Postgres query optimizer
> (40 rows)
> ```

This is a planner bug and should be fixed by us.

**Comment by kainwen** [comment] 2020-04-29 11:06
I have come up with a simple reproduce-scripts:

```sql
drop table if exists t1;
drop table if exists t2;
drop type if exists mt;

create type mt as (x int, y int);

create table t1 (a int, b mt);
create table t2 (a int, b mt) distributed replicated;

insert into t1 select i, '(1,1)' from generate_series(1, 1)i;
insert into t2 select i, '(1,1)' from generate_series(1, 1)i;

explain
select * from t1
cross join lateral
(with recursive s as
 (select * from t2 where (t1.b).x = (t2.b).y
  union all
  select a+1, b from s where a+1 < 10)
 select * from s) x;

select * from t1
cross join lateral
(with recursive s as
 (select * from t2 where (t1.b).x = (t2.b).y
  union all
  select a+1, b from s where a+1 < 10)
 select * from s) x;
```

This issue does not exist on master. Because on master branch, we have the logic of `bring_to_outer_query` to make things correct.

On 6X, there is no logic of `bring_to_outer_query`. We might consider how to partially backport this skill to fix such kind of issues.

As analyzed before, the root cause is we generate a plan with motions cutting off the path of outer params.

**Comment by kainwen** [comment] 2020-04-29 12:02
Then I try another case with the non-recursive part is general locus, it works on 6x:

```sql
drop table if exists t1;
drop table if exists t2;
drop type if exists mt;

create type mt as (x int, y int);

create table t1 (a int, b mt);
create table t2 (a int, b mt) distributed replicated;

insert into t1 select i, '(1,1)' from generate_series(1, 1)i;
insert into t2 select i, '(1,1)' from generate_series(1, 1)i;

explain
select * from t1
cross join lateral
(with recursive s as
 (select t2 as a from generate_series(1, 10) t2 where (t1.b).x = t2
  union all
  select a+1 from s where a+1 < 10)
 select * from s) x;

select * from t1
cross join lateral
(with recursive s as
 (select t2 as a from generate_series(1, 10) t2 where (t1.b).x = t2
  union all
  select a+1 from s where a+1 < 10)
 select * from s) x;
```

The plan is 

```sql
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=10000000000.00..10000000002.56 rows=35 width=37)
   ->  Nested Loop  (cost=10000000000.00..10000000002.56 rows=12 width=37)
         ->  Seq Scan on t1  (cost=0.00..1.01 rows=1 width=33)
         ->  Materialize  (cost=0.00..1.20 rows=12 width=4)
               ->  Recursive Union  (cost=0.00..15.77 rows=12 width=4)
                     ->  Function Scan on generate_series t2  (cost=0.00..12.50 rows=1 width=4)
                           Filter: ((t1.b).x = t2)
                     ->  WorkTable Scan on s  (cost=0.00..0.26 rows=2 width=4)
                           Filter: ((a + 1) < 10)
 Optimizer: Postgres query optimizer
```

SegmentGeneral should be the same as General under this case.

It is my previous commit that https://github.com/greenplum-db/gpdb/commit/fb90769e5b7cc63b6f5b7d852b2540628d8d9c60
that will add a gather motion above the non-recurisve part if it is segmentgeneral.

Will spend more time on this and may reconsider the above commit's solution.

**Comment by lambgong** [comment] 2020-04-29 13:32
Thank for you reply, for my case, what do you suggest me to do?

**Comment by kainwen** [comment] 2020-04-29 23:03
> Thank for you reply, for my case, what do you suggest me to do?

In fact, there are some issues on gpdb6's lateral join, and in the document https://gpdb.docs.pivotal.io/6-7/ref_guide/feature_summary.html
we doc that we do not support lateral join in gpdb6.

I highly recommend you to change the SQL to use subquery or something like that.

But we will continue to fix this crash issue. It may be fixed in later 6 minor versions.

**Comment by lambgong** [comment] 2020-04-30 02:10
Thank you so much!

**Comment by kainwen** [comment] 2020-04-30 08:06
The PANIC case on Master branch is built:

```sql

create type mytype_for_lateral_test as (x int, y int);
create table t1_lateral_limit(a int, b int, c mytype_for_lateral_test);
create table t2_lateral_limit(a int, b int);
insert into t1_lateral_limit values (1, 1, '(1,1)');
insert into t2_lateral_limit values (2, 2);
insert into t2_lateral_limit values (3, 3);

gpadmin=# explain select * from t1_lateral_limit as t1 cross join lateral
((select ((c).x+t2.b) as n  from t2_lateral_limit as t2 order by n limit 1) union all select 1)s;
                                                 QUERY PLAN
-------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=10000000001.03..10000000002.16 rows=4 width=41)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.03 rows=1 width=37)
         ->  Seq Scan on t1_lateral_limit t1  (cost=0.00..1.01 rows=1 width=37)
   ->  Materialize  (cost=1.03..1.11 rows=2 width=4)
         ->  Append  (cost=1.03..1.08 rows=2 width=4)
               ->  Limit  (cost=1.03..1.05 rows=1 width=4)
                     ->  Gather Motion 3:1  (slice2; segments: 3)  (cost=1.03..1.05 rows=1 width=4)
                           Merge Key: (((t1.c).x + t2.b))
                           ->  Limit  (cost=1.03..1.03 rows=1 width=4)
                                 ->  Sort  (cost=1.02..1.03 rows=1 width=4)
                                       Sort Key: (((t1.c).x + t2.b))
                                       ->  Seq Scan on t2_lateral_limit t2  (cost=0.00..1.01 rows=1 width=4)
               ->  Result  (cost=0.00..0.01 rows=1 width=4)
 Optimizer: Postgres query optimizer
(14 rows)

gpadmin=# select * from t1_lateral_limit as t1 cross join lateral
((select ((c).x+t2.b) as n  from t2_lateral_limit as t2 order by n limit 1) union all select 1)s;
ERROR:  Error on receive from seg0 slice2 127.0.1.1:7002 pid=23903: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

```

The idea is just taken from this issue.

It is the commit https://github.com/greenplum-db/gpdb/commit/625797280c55033147354ba831a6ae6c1a478fa5 does not handle things correct.
We should not only rely on the limit clause in the subquery. We should check the projection of the rel if they contain outer Params ref.

There are a few problems that we need to fix for lateral join.

What's more, we might reconsider the replicated table in recursive union.

**Comment by lij55** [comment] 2022-03-31 10:38
this issue is still on GP6 (by 6.19) but seems OK on master/GP7
```sql
test=# select * from t1_lateral_limit as t1 cross join lateral
test-# ((select ((c).x+t2.b) as n  from t2_lateral_limit as t2 order by n limit 1) union all select 1)s;
 a | b |   c   | n 
---+---+-------+---
 1 | 1 | (1,1) | 3
 1 | 1 | (1,1) | 1
(2 rows)
```

we need to fix the crash issue despite GP6 doesn't support lateral join.

**Comment by dpandhi-git** [comment] 2022-12-23 01:02
@kainwen crash needs to fix for 6x

**Comment by kainwen** [comment] 2023-12-19 09:49
This PR https://github.com/greenplum-db/gpdb/pull/16840 can let this issue get rid of crash.
And the issue's case is included in the merged PR.

Later we will estimate the support lateral in gpdb7, so we can close this.

**Closed by kainwen** 2023-12-19 09:49 UTC
Labels: type: bug, topic: planner, area: server, version: 6X_STABLE, Priority 3
