### ISSUE TITLE
response with status 400

### ISSUE THREAD

**Issue by mirkos-vf** [greenplum-db/gpdb#9015] opened 2019-11-08 08:56 UTC
version 5.0

linux redhut

When initial request was sent with sequence num 1, I sent post request with data and sequence num 2.  In logs it wrote: 
```
got an out of order request, sequence number is 2, expected sequence number is 3904674963453378562.
```

Why expected number is 3904674963453378562 and not 2? What I should do with this problem?

**Comment by asimrp** [comment] 2019-11-11 06:01
@pf-qiu do you or @hxiaodon want to take a look into this error?  By the way, @mirkos-vf, if you are running Greenplum 5.0, I suggest upgrading to the latest 5X version, 5.23.0 as of now.

**Comment by mirkos-vf** [comment] 2019-11-11 07:04
@asimrp this error occurs in GPFDIST, when sending data post request

**Comment by adam8157** [comment] 2021-12-14 08:05
Where it puts the previous sequence number, it's not initialized by zero.

So the problem is your initial request, which was not successfully processed.

I would suggest dumping the normal gpfdist dataflow, and taking it as an example to write your own.

Closing this. If someone has a gpfdist programming guide, please share.

**Closed by adam8157** 2021-12-14 08:05 UTC
Labels: version: 5X_STABLE
