### ISSUE TITLE
end-of-copy marker corrupt

### ISSUE THREAD

**Issue by lambgong** [greenplum-db/gpdb#10417] opened 2020-07-03 09:19 UTC
### Greenplum version or build
gp6.5 

### Step to reproduce the behavior

table schema as follow:
```
CREATE TABLE test (
id int,
name text,
dep text
) DISTRIBUTED BY(id)
```

text file as follow:
```
122,as\.d,adad
133,sa dad,adadad
```

when run the copy sql, 
```
\copy test from '/root/file' DELIMITER ',';
```
we will get error info 
ERROR:  end-of-copy marker corrupt

So my question is :
1. why this copy sql done well on gp5?
2. As far as I know, end-of-data marker(\.) is needed only when copying data to or from client applications using pre-3.0 client protocol, but our sql is copy from file

**Comment by JunfengYang** [comment] 2020-07-07 07:21
This just keeps the same behavior with Postgres.

```
postgres=# select version();
                                                 version
----------------------------------------------------------------------------------------------------------
 PostgreSQL 14devel on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
(1 row)
postgres=# CREATE TABLE test (
id int,
name text,
dep text
) ;
CREATE TABLE
postgres=#
postgres=#
postgres=#
postgres=# copy test from '/tmp/file' DELIMITER ',';
ERROR:  end-of-copy marker corrupt
CONTEXT:  COPY test, line 1
postgres=#
```

The reason is the default format used is `text`, and there's the end of copy mark in the first line `122,as\.d,adad`. 
But there still data after the `\.` mark.

For more details please refer to:
https://www.postgresql.org/docs/current/sql-copy.html

Since it should be the expected behavior, so I'll close this issue.

**Closed by JunfengYang** 2020-07-07 07:21 UTC
