### ISSUE TITLE
duplicate key violates unique constraint when insert item

### ISSUE THREAD

**Issue by lufeng1102** [greenplum-db/gpdb#676] opened 2016-04-26 11:43 UTC
Hi All

How to solve this issue when I insert the duplicate items.

```bash
insert into cell_test_insert_temp_test values(20160426171500000,3,'test3',200,2001),(20160426173000000,4,'test4',200,2001);
ERROR:  duplicate key violates unique constraint "cell_test_insert_temp_test_pkey"  (seg15 compute-04-02-39:40003 pid=18154)
```

GP version is 4.3.8. 

Thanks

**Comment by danielgustafsson** [comment] 2016-04-26 12:30
Can you please share what your table definition looks like?

**Comment by lufeng1102** [comment] 2016-04-27 10:58
Hi @danielgustafsson , following is the table definition 

```bash
create table cell_test_insert_temp_test(
  starttime bigint,
  cell_id bigint,
  cell_name varchar(255),
  province_id int,
  city_id int,
 CONSTRAINT cell_test_insert_temp_test_pkey primary key(starttime,cell_id))
DISTRIBUTED BY (starttime,cell_id);
```

**Comment by vraghavan78** [comment] 2016-05-11 22:20
@lufeng1102 you have a constraint 

CONSTRAINT cell_test_insert_temp_test_pkey primary key(starttime,cell_id))

```
vraghavan=# insert into cell_test_insert_temp_test values(20160426171500000,3,'test3',200,2001),(20160426173000000,4,'test4',200,2001);
INSERT 0 2
vraghavan=# insert into cell_test_insert_temp_test values(20160426171500000,3,'test3',200,2001),(20160426173000000,4,'test4',200,2001);
ERROR:  duplicate key value violates unique constraint "cell_test_insert_temp_test_pkey"  (seg1 Venkateshs-MacBook-Pro.local:25433 pid=39539)
DETAIL:  Key (starttime, cell_id)=(20160426171500000, 3) already exists.
```

This is the correct behavior. If you want to support duplicate remove the constraint. Closing the issue since this is an expected behavior.

Please re-open if there is more I can help with.

**Closed by vraghavan78** 2016-05-11 22:20 UTC
