### ISSUE TITLE
ERROR: |58P01|could not open file "base/863243/t_40704489": No such file or directory

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#13809] opened 2022-07-16 03:37 UTC
### Greenplum version or build

- 6.19.1

### Actual behavior

```
$ gpssh -f /opt/greenplum/config/seg_hosts -e 'source /usr/local/greenplum-db/greenplum_path.sh ; gplogfilter -t /disk3/gpdata/gpsegment/primary/*/pg_log/gpdb-2022-07-16_090208.csv' >> seg_error.log
$ cat seg_error.log
...
[gp6sdw3] 2022-07-16 11:08:39.518195 CST|||p248|th1436305536||||0|||seg10|||||ERROR: |58P01|could not open file "base/863243/t_40704489": No such file or directory|||||writing block 1 of relation base/863243/t_40704489||0||md.c|665|Stack trace:
[gp6sdw3] 1    0xbf112c postgres errstart (elog.c:557)
[gp6sdw3] 2    0xa7ee33 postgres <symbol not found> (md.c:663)
[gp6sdw3] 3    0xa817f7 postgres mdwrite (md.c:1937)
[gp6sdw3] 4    0xa4f40a postgres <symbol not found> (bufmgr.c:2193)
[gp6sdw3] 5    0xa4fdb7 postgres BgBufferSync (bufmgr.c:2105)
[gp6sdw3] 6    0x9ff483 postgres BackgroundWriterMain (bgwriter.c:289)
[gp6sdw3] 7    0x785953 postgres AuxiliaryProcessMain (bootstrap.c:389)
[gp6sdw3] 8    0xa0d535 postgres <symbol not found> (postmaster.c:5854)
[gp6sdw3] 9    0xa0dba5 postgres <symbol not found> (postmaster.c:3262)
[gp6sdw3] 10   0x7dd152fbb630 libpthread.so.0 <symbol not found> + 0x52fbb630
[gp6sdw3] 11   0x7dd152434983 libc.so.6 __select + 0x13
[gp6sdw3] 12   0x6ad905 postgres <symbol not found> (postmaster.c:1894)
[gp6sdw3] 13   0xa0f982 postgres PostmasterMain (postmaster.c:1523)
[gp6sdw3] 14   0x6b24a1 postgres main (main.c:205)
[gp6sdw3] 15   0x7dd152361555 libc.so.6 __libc_start_main + 0xf5
[gp6sdw3] 16   0x6be1bc postgres <symbol not found> + 0x6be1bc
...
```

[seg_error.log](https://github.com/greenplum-db/gpdb/files/9125081/seg_error.log)

**Comment by kainwen** [comment] 2022-07-16 09:26
Hi, @cobolbaby 

Thanks for reporting the issue.

Would you please paste the following SQL result (run them in the same session) here?

```
set gp_select_invisible = 1;
select * from gp_dist_random('pg_class') where relfilenode = 40704489;
```

**Comment by cobolbaby** [comment] 2022-07-17 02:06
In order to reduce the impact on online business, I took seg10 offline first. 
After switching to mirror, the error does not happen again. 

```
pg_ctl -D /disk3/gpdata/gpsegment/primary/gpseg10 stop -m fast
```

In addition, I executed the following command before I offline the seg10, but no result was returned. Maybe `gp_dist_random` works, but I didn't get the idea at that time. Next time I encounter this problem I will record it.

```
SELECT datname FROM pg_database WHERE oid = 863243;

\c xxx;

SELECT c.relname, c.relkind, n.nspname 
FROM pg_class c
	JOIN pg_namespace n on n.oid = c.relnamespace
WHERE c.relfilenode = 40704489;
```

**Comment by kainwen** [comment] 2022-07-17 06:55
@cobolbaby 
do you set gp_select_invisible？

**Comment by cobolbaby** [comment] 2022-07-17 07:11
> do you set gp_select_invisible？

No. I have not set this parameter before.

**Comment by kainwen** [comment] 2022-07-17 07:29
> > do you set gp_select_invisible？
> 
> No. I have not set this parameter before.

So would you please collect the result as I mentioned in https://github.com/greenplum-db/gpdb/issues/13809#issuecomment-1186130642

```sql
set gp_select_invisible = 1;
select * from gp_dist_random('pg_class') where relfilenode = 40704489;
FROM pg_class c
	JOIN pg_namespace n on n.oid = c.relnamespace
WHERE c.relfilenode = 40704489;
```

**Comment by cobolbaby** [comment] 2022-07-17 09:19
It should be an intermediate temporary table, which will be destroyed when it is used up.

```
F6_BDC=# set gp_select_invisible = 1;
SET
F6_BDC=# select * from gp_dist_random('pg_class') where relfilenode = 40704489;
F6_BDC=# 
F6_BDC=# 
F6_BDC=# select count(1) from gp_dist_random('pg_class') where relfilenode = 40704489;
 count 
-------
     0
(1 行记录)
```

**Comment by cobolbaby** [comment] 2022-07-17 09:38
Same Question:

```
F6_BDC=# select count(1) from gp_dist_random('pg_class') where relfilenode = 40786969;
 count 
-------
     0
(1 行记录)

F6_BDC=# SELECT current_database() datname, sosdnsp AS nspname, sosdschematablesize AS table_size_bytes, sosdschemaidxsize AS idx_size_bytes FROM gp_toolkit.gp_size_of_schema_disk;
WARNING:  could not write block 4 of base/863243/t_40786969  (seg10 10.13.0.31:50002 pid=139685)
描述:  Multiple failures --- write error might be permanent.
ERROR:  could not open file "base/863243/t_40786969": No such file or directory  (seg10 10.13.0.31:50002 pid=139685)
背景:  writing block 4 of relation base/863243/t_40786969
F6_BDC=# select count(1) from gp_dist_random('pg_class') where relfilenode = 40786969;
 count 
-------
     0
(1 行记录)

F6_BDC=# set gp_select_invisible = 1;
SET
F6_BDC=# select count(1) from gp_dist_random('pg_class') where relfilenode = 40786969;
 count 
-------
     0
(1 行记录)

```

**Comment by kainwen** [comment] 2022-07-17 12:43
The direct reason seems that there is a bad buffer in shared buffer, a buffer is dirty and point to the not-exists path. Then any SQL in theory might lead to the error shown in the logs: if the SQL decide to switch out just this dirty page.

But what is the root cause leading to such case is still unknown.

Do you still have the XLOGs in the errored segments?

**Comment by cobolbaby** [comment] 2022-07-17 12:59
> But what is the root cause leading to such case is still unknown.

I suspect that `SELECT current_database() datname, sosdnsp AS nspname, sosdschematablesize AS table_size_bytes, sosdschemaidxsize AS idx_size_bytes FROM gp_toolkit.gp_size_of_schema_disk;` caused this problem, because I have not encountered such a problem before executing this SQL regularly.

**Comment by interma** [comment] 2022-07-23 11:41
@cobolbaby You can grep xlog by
```
find . -name '000000030*' | xargs -i pg_xlogdump {} | grep 40704489
```
Please provide the outputs, thanks.

**Comment by ashwinstar** [comment] 2023-02-18 15:06
This https://github.com/greenplum-db/gpdb/pull/14949 explains the scenario and also has test to demonstrate the same

**Comment by haolinw** [comment] 2023-03-01 00:34
Close the issue as a quick fix https://github.com/greenplum-db/gpdb/pull/15035 was merged.

**Closed by haolinw** 2023-03-01 00:34 UTC
Labels: type: bug
