### ISSUE TITLE
COPY IN WITH BINARY sets wrong default values

### ISSUE THREAD

**Issue by volkovandr** [greenplum-db/gpdb#4844] opened 2018-04-11 11:02 UTC
The problem is that when the records are inserted using the COPY command with BINARY, the default field values for the field of type timestamptz are not used or maybe used in a wrong way.
Here is an example reproducing the issue:

```
test=# select version();
                                                                                      version                                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit compiled on Jan 14 2018 19:03:36
(1 row)
```

Creating a table with a default field value `now()`. Inserting a record leaving the field out to check if default value is set:
```
gpadmin@server:~$ psql test
psql (8.3.23)
Type "help" for help.

test=# create table test_table(i int, ts timestamptz default now());
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
test=# insert into test_table (i) values (1);
INSERT 0 1
test=# select * from test_table;
 i |              ts               
---+-------------------------------
 1 | 2018-04-11 11:20:52.847176+02
(1 row)
```
Everything is fine, default works.
Now copying data to the table using COPY WITH BINARY. Copying only the field `i` leaving the other field out. I expect the field `ts` to be set to current time, about 2018-04-11 11:20
```
gpadmin@server:~$ psql test -c "COPY (SELECT 2) TO STDOUT WITH BINARY" | psql test -c "COPY test_table(i) FROM STDIN WITH BINARY"
```
Let's check what is in the table:
```
gpadmin@server:~$ psql test
psql (8.3.23)
Type "help" for help.

test=# select * from test_table;
 i |              ts              
---+------------------------------
 1 | 2018-04-11 11:20:52.847176+02
 2 | 2000-01-01 01:00:51.80416+01
(1 row)

test=# \q
```
The timestamp field is set to 2000-01-01 instead of 2018-04-11
Trying to do the same with COPY without BINARY, i.e. with text:
```
gpadmin@server:~$ psql test -c "COPY (SELECT 3) TO STDOUT" | psql test -c "COPY test_table(i) FROM STDIN"
gpadmin@server:~$ psql test
psql (8.3.23)
Type "help" for help.

test=# select * from test_table;
 i |              ts              
---+------------------------------
 1 | 2018-04-11 11:20:52.847176+02
 2 | 2000-01-01 01:00:51.80416+01
 3 | 2018-04-11 11:22:15.07177+02
(2 rows)
```
In the new row the timestamp is set to current time as expected.
Trying copying through a file instead of direct piping:
```
test=# COPY (SELECT 4) TO '/tmp/file.dmp' WITH BINARY;
COPY 1
test=# COPY test_table(i) FROM '/tmp/file.dmp' WITH BINARY;
COPY 1
test=# select * from test_table;
 i |              ts              
---+------------------------------
 1 | 2018-04-11 11:20:52.847176+02
 2 | 2000-01-01 01:00:51.80416+01
 3 | 2018-04-11 11:22:15.07177+02
 4 | 2000-01-01 01:00:53.53264+01
(3 rows)
```
The same. I also tried a small Java program that performs copy in with binary with the same result. The default value for a timestamp field is wrong.

Tried this on another cluster:
```
test=# select version();
                                                                           version                                                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (Debian 4.9.2-10) 4.9.2 compiled on Nov 15 2017 10:59:32
(1 row)
```
The same issue.

Tried this with PostgreSQL, works fine:
```
user=# select version();
                                                                   version                                                                    
----------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.8 on x86_64-pc-linux-gnu (Ubuntu 9.6.8-1.pgdg16.04+1), compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit
(1 row)

user=# create table test(i int, ts timestamptz default now());
CREATE TABLE
user=# COPY (SELECT 1) TO '/tmp/file.dmp' WITH BINARY;
COPY 1
user=# COPY test(i) FROM '/tmp/file.dmp' WITH BINARY;
COPY 1
user=# select * from test;
 i |              ts               
---+-------------------------------
 1 | 2018-04-11 11:59:15.730581+02
(1 row)
```

**Comment by yydzero** [comment] 2018-05-16 07:29
tried on master, still exists.

**Comment by hlinnaka** [comment] 2019-01-15 06:59
I cannot reproduce this on GPDB master anymore. I think it got fixed by the big refactoring to COPY code, in the 9.1 merge.

Closing, thanks for the report!

**Closed by hlinnaka** 2019-01-15 06:59 UTC
Labels: Hacktoberfest, help wanted
