### ISSUE TITLE
planner generate motion below append node

### ISSUE THREAD

**Issue by kainwen-zz** [greenplum-db/gpdb#9074] opened 2019-11-20 07:30 UTC
I believe this issue on 5, 6, master. Only for planner.

```sql
CREATE TABLE sales (id int, date date, amt decimal(10,2))
DISTRIBUTED BY (id)
PARTITION BY RANGE (date)
( START (date '2016-01-01') INCLUSIVE
   END (date '2017-01-01') EXCLUSIVE
   EVERY (INTERVAL '1 day') );

insert into sales values (generate_series(1,10000),'2016-02-01',10) ; 
insert into sales values (generate_series(1,10000),'2016-02-01',10) ;
insert into sales values (generate_series(1,10000),'2016-02-01',10) ;
insert into sales values (generate_series(1,10000),'2016-03-01',10) ;
insert into sales values (generate_series(1,10000),'2016-04-01',10) ;
insert into sales values (generate_series(1,10000),'2016-05-01',10) ;
insert into sales values (generate_series(1,10000),'2016-06-01',10) ;
create table sales1 as select * from sales ;

delete from sales a using sales1 b where a.id=b.id and a.date=b.date and a.amt=b.amt;
```

If under planner, the last delete statement will generate a plan with about 1000 slices. The RCA is the motion is added below the append node for each partition.

I notice a PR (now closed) https://github.com/greenplum-db/gpdb/pull/8001 also try to fix the similar issue. I do not know why it is closed.

**Comment by hlinnaka** [comment] 2020-08-15 20:47
I cannot reproduce this. Was it fixed already?

**Comment by kainwen** [comment] 2020-08-16 05:46
> I cannot reproduce this. Was it fixed already?

In master, I previously push a commit to remove the useless explicit motion.

If change the sales to a randomly distributed table, we reproduce this issue.

```sql
  Delete on sales_1_prt_361 a_360
   Delete on sales_1_prt_362 a_361
   Delete on sales_1_prt_363 a_362
   Delete on sales_1_prt_364 a_363
   Delete on sales_1_prt_365 a_364
   Delete on sales_1_prt_366 a_365
   ->  Explicit Redistribute Motion 3:3  (slice1; segments: 3)  (cost=2020.00..6513.98 rows=6 width=16)
         ->  Hash Join  (cost=2020.00..6513.66 rows=6 width=16)
               Hash Cond: ((a.id = b.id) AND (a.date = b.date) AND (a.amt = b.amt))
               ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..1918.00 rows=20200 width=34)
                     Hash Key: a.id
                     ->  Seq Scan on sales_1_prt_1 a  (cost=0.00..706.00 rows=20200 width=34)
               ->  Hash  (cost=795.00..795.00 rows=23334 width=19)
                     ->  Seq Scan on sales1 b  (cost=0.00..795.00 rows=23334 width=19)
   ->  Explicit Redistribute Motion 3:3  (slice3; segments: 3)  (cost=2020.00..6513.98 rows=6 width=16)
         ->  Hash Join  (cost=2020.00..6513.66 rows=6 width=16)
               Hash Cond: ((a_1.id = b.id) AND (a_1.date = b.date) AND (a_1.amt = b.amt))
               ->  Redistribute Motion 3:3  (slice4; segments: 3)  (cost=0.00..1918.00 rows=20200 width=34)
                     Hash Key: a_1.id
                     ->  Seq Scan on sales_1_prt_2 a_1  (cost=0.00..706.00 rows=20200 width=34)
               ->  Hash  (cost=795.00..795.00 rows=23334 width=19)
                     ->  Seq Scan on sales1 b  (cost=0.00..795.00 rows=23334 width=19)
   ->  Explicit Redistribute Motion 3:3  (slice5; segments: 3)  (cost=2020.00..6513.98 rows=6 width=16)
         ->  Hash Join  (cost=2020.00..6513.66 rows=6 width=16)
               Hash Cond: ((a_2.id = b.id) AND (a_2.date = b.date) AND (a_2.amt = b.amt))
               ->  Redistribute Motion 3:3  (slice6; segments: 3)  (cost=0.00..1918.00 rows=20200 width=34)
                     Hash Key: a_2.id
                     ->  Seq Scan on sales_1_prt_3 a_2  (cost=0.00..706.00 rows=20200 width=34)
               ->  Hash  (cost=795.00..795.00 rows=23334 width=19)
                     ->  Seq Scan on sales1 b  (cost=0.00..795.00 rows=23334 width=19)
   ->  Explicit Redistribute Motion 3:3  (slice7; segments: 3)  (cost=2020.00..6513.98 rows=6 width=16)
         ->  Hash Join  (cost=2020.00..6513.66 rows=6 width=16)
               Hash Cond: ((a_3.id = b.id) AND (a_3.date = b.date) AND (a_3.amt = b.amt))
               ->  Redistribute Motion 3:3  (slice8; segments: 3)  (cost=0.00..1918.00 rows=20200 width=34)
                     Hash Key: a_3.id
                     ->  Seq Scan on sales_1_prt_4 a_3  (cost=0.00..706
```

**Comment by lij55** [comment] 2022-03-25 08:06
Hi @kainwen-zz , 

could you please confirm whether it is fixed on master or not?
I got following plan which seems correct because there is no motion any more:
```sql
   Delete on sales_1_prt_361 a_361
   Delete on sales_1_prt_362 a_362
   Delete on sales_1_prt_363 a_363
   Delete on sales_1_prt_364 a_364
   Delete on sales_1_prt_365 a_365
   Delete on sales_1_prt_366 a_366
   ->  Hash Join  (cost=2020.00..4774.28 rows=16 width=16)
         Hash Cond: ((a_1.id = b.id) AND (a_1.date = b.date) AND (a_1.amt = b.amt))
         ->  Seq Scan on sales_1_prt_1 a_1  (cost=0.00..706.00 rows=60600 width=34)
         ->  Hash  (cost=795.00..795.00 rows=70000 width=19)
               ->  Seq Scan on sales1 b  (cost=0.00..795.00 rows=70000 width=19)
   ->  Hash Join  (cost=2020.00..4774.28 rows=16 width=16)
         Hash Cond: ((a_2.id = b.id) AND (a_2.date = b.date) AND (a_2.amt = b.amt))
         ->  Seq Scan on sales_1_prt_2 a_2  (cost=0.00..706.00 rows=60600 width=34)
         ->  Hash  (cost=795.00..795.00 rows=70000 width=19)
               ->  Seq Scan on sales1 b  (cost=0.00..795.00 rows=70000 width=19)
```

**Comment by dpandhi-git** [comment] 2022-11-20 01:42
@kainwen can you update latest?

**Comment by dpandhi-git** [comment] 2022-12-23 00:52
with @ashwinstar 7x does not report motion both for distributed randomly and by id

**Closed by dpandhi-git** 2022-12-23 00:52 UTC
Labels: type: bug, topic: planner, area: server, needs: more information
