### ISSUE TITLE
FOREIGN KEY creation on partition table fails with "ALTER TABLE"

### ISSUE THREAD

**Issue by dkrieger-pvtl** [greenplum-db/gpdb#10217] opened 2020-06-01 23:29 UTC
### Greenplum version or build
GPDB-5, GPDB-6

### OS version and uname -a
Mac OSX High Sierra

### autoconf options used ( config.status --config )
n/a

### Installation information ( pg_config )
n/a

### Expected behavior
Consistent behavior for creation or error whether a FOREIGN KEY is added to a partition table either during CREATE TABLE or later using ALTER TABLE.

### Actual behavior
CREATE TABLE to add the foreign key constraint works, but adding it later using ALTER TABLE fails.

### Step to reproduce the behavior
* create an empty table to be used as the foreign key
```sql
create table mfk(a int unique);
```

Adding the foreign key constraint during CREATE TABLE works:
```sql
postgres# CREATE TABLE public.pt (
    a integer references mfk(a)
)
DISTRIBUTED BY (a) PARTITION BY RANGE(a)
( START (1) END (3) EVERY (2) WITH (tablename='pt_1_prt_1', appendonly=false ) );
...
WARNING:  Referential integrity (FOREIGN KEY) constraints are not supported in Greenplum Database, will not be enforced.
```

Adding the foreign key constraint later using ALTER TABLE fails:
```sql
CREATE TABLE public.pt (
    a integer
)
DISTRIBUTED BY (a) PARTITION BY RANGE(a)
( START (1) END (3) EVERY (2) WITH (tablename='pt_1_prt_1', appendonly=false ) );


ALTER TABLE ONLY public.pt
    ADD CONSTRAINT pt_fkey FOREIGN KEY (a) REFERENCES public.mfk(a);

ERROR:  can't add a constraint to "pt"; it is a partitioned table or part thereof
```

**Comment by soumyadeep2007** [comment] 2020-06-01 23:39
Hey @dkrieger-pvtl , could you post the failure ERROR message? Or is it a silent failure?

**Comment by dkrieger-pvtl** [comment] 2020-06-02 00:00
For context, we can across this using [gpugprade](https://github.com/greenplum-db/gpupgrade).  You can create a partition table with a foreign key constraint in 5 using CREATE TABLE, but using gpdb-6's `pg_dump` to dump that table generates the DDLs using two steps: CREATE TABLE and ALTER TABLE to add the foreign key constraint.  That causes `pg_restore` to fail due to this bug.

**Comment by d** [comment] 2020-06-02 00:02
This is sadly a known issue that's at the intersection of pg_dump and the backend ("server"). It's similar to how `PRIMARY KEY` (and `UNIQUE`) constraints on a partitioned table cannot be properly dumped (and upgraded).

**Comment by d** [comment] 2020-06-02 00:04
I'd recommend we treat foreign keys just like how we treat primary keys during an upgrade: we either need to pay to cost to support both, or we'd have to support neither

**Comment by dkrieger-pvtl** [comment] 2020-06-02 00:05
In other words, add a gpdb-6 `pg_upgrade --check` step that fails to upgrade a partition table with a foreign key constraint?  Then, users can re-add it after upgrade using the CREATE TABLE DDL?

**Comment by soumyadeep2007** [comment] 2020-06-02 23:28
@dkrieger-pvtl We had a conversation on this today. @d mentioned that the problem is with the `ONLY` clause in the `ALTER` statement. This means that `ALTER TABLE ADD FOREIGN KEY` without `ONLY` would still work. We can't support that for partitioned tables in GP. I guess we have two options:
1. Add the `--check` exclusion as you mentioned above and have the user do a `ALTER TABLE ADD FOREIGN KEY` without the ONLY clause..
Note: Creating a partition table with the foreign key constraint **does not** create foreign key constraints in the children.
Note: Calling `ALTER TABLE ADD FOREIGN KEY` without `ONLY` **does not** create foreign key constraints in the children.
2. Change pg_dump to remove the ONLY clause for partition tables w/ foreign key constraints.

@d seemed to suggest 2. is not worth the effort.

**Comment by dkrieger-pvtl** [comment] 2020-06-08 18:44
@soumyadeep2007 Thanks for the response.  

We are considering doing option 1, that is, having `pg_upgrade` check for foreign keys.  

Since Greenplum does not support foreign keys(processing the DDL for adding a foreign key produces the warning `WARNING:  Referential integrity (FOREIGN KEY) constraints are not supported in Greenplum Database, will not be enforced.`):

Can we assume that recreating the foreign keys is fast, even for a very large table?

That is, during gpugprade, a user would have to drop their foreign constraints on partition tables, run the upgrade, and then recreate those foreign constraints on the updated database.  We'd like to assume that recreation is fast, but are not sure.

**Comment by soumyadeep2007** [comment] 2020-06-08 22:03
In Postgres, adding a foreign key constraint to a table causes `validateForeignKeyConstraint` to be called, which in turn calls `RI_Initial_Check`, which is the main workhorse for checking if the existing data is valid against the referenced table's unique index.

In GP, when you add a foreign key constraint to a table already having data, nothing is validated. (The above functions aren't even called. Reason: the foreign key carries `skipValidation = true` in GP). Thus, adding the foreign key constraint using an `ALTER TABLE` will be instantaneous.

**Comment by dkrieger-pvtl** [comment] 2020-06-08 23:54
@soumyadeep2007 Thanks.  We will workaround this bug by adding a pg_upgrade check for partition tables with foreign key constraints.

Do you want to keep this bug open? It's still a bug, but as far as gpugprade is concerned, we'll workaround it so we don't need any action on this.  In a sense, it's "closed, won't fix" but I don't see a workflow for that.

**Comment by soumyadeep2007** [comment] 2020-06-10 03:53
I guess we can err on the side of leaving it open.

**Comment by lij55** [comment] 2022-08-04 23:40
let's close this long living known issue with work around now. how to really support foreign key in greenplum is another big topic.

**Closed by lij55** 2022-08-04 23:40 UTC
