### ISSUE TITLE
wrong information in pg_appendonly after executing alter table set distributed by statement  

### ISSUE THREAD

**Issue by yangqi2004** [greenplum-db/gpdb#160] opened 2015-12-08 20:42 UTC
### table information in pg_appendonly is wrong after 'alter table set distributed by ' statement. 
 
* create an columar appendonly table with compression.
```
gpadmin=# drop table public.test123;
DROP TABLE
gpadmin=# create table public.test123 (
gpadmin(# col1 text,
gpadmin(# col2 text,
gpadmin(# col3 int
gpadmin(# )
gpadmin-# with ( appendonly = true, orientation = column, compresslevel = 4, compresstype=zlib)
gpadmin-# distributed by (col1);
CREATE TABLE
gpadmin=# \dt test123
                     List of relations
 Schema |  Name   | Type  |  Owner  |       Storage
--------+---------+-------+---------+----------------------
 public | test123 | table | gpadmin | append only columnar
(1 row)
```
* table information in pg_appendonly, the table is compressed with zlib.
```
gpadmin=#
gpadmin=# SELECT c.relname, a.compresstype, a.compresslevel, a.blocksize, a.checksum
gpadmin-# FROM pg_catalog.pg_appendonly a, pg_catalog.pg_class c
gpadmin-# WHERE c.oid = a.relid AND c.oid = 'public.test123'::regclass;
 relname | compresstype | compresslevel | blocksize | checksum
---------+--------------+---------------+-----------+----------
 test123 | zlib         |             4 |     32768 | t
(1 row)
```
* alter table set new distribution key
```
gpadmin=# alter table public.test123 set distributed by (col1);
ALTER TABLE
```
* After the change, the information in pg_appendonly - column compresstype and compresslevel is wrong.
```
gpadmin=#
gpadmin=# SELECT c.relname, a.compresstype, a.compresslevel, a.blocksize, a.checksum
gpadmin-# FROM pg_catalog.pg_appendonly a, pg_catalog.pg_class c
gpadmin-# WHERE c.oid = a.relid AND c.oid = 'public.test123'::regclass;
 relname | compresstype | compresslevel | blocksize | checksum
---------+--------------+---------------+-----------+----------
 test123 |              |             0 |     32768 | t
(1 row)

gpadmin=#
gpadmin=# \dt test123
                     List of relations
 Schema |  Name   | Type  |  Owner  |       Storage
--------+---------+-------+---------+----------------------
 public | test123 | table | gpadmin | append only columnar
(1 row)
```

**Comment by asimrp** [comment] 2015-12-09 23:58
Hi @yangqi2004 

Glad that you are interested in column oriented tables to the point of looking into `pg_appendonly`.  Your observation is not a bug.  For column oriented tables, Greenplum offers column specific encodings for compression and block size.  Therefore, `pg_appendonly` is not adequate to capture this information for each column.  We have a separate catalog table called `pg_attribute_encoding` for column oriented tables, that captures each column's compression details and block size.

Can you try inspecting contents of `pg_attribute_encoding`? 
```
select attrelid::regclass, * from pg_attribute_encoding;
```

Hope that helps.
Asim

**Comment by hlinnaka** [comment] 2015-12-10 06:28
On 10/12/15 01:58, Asim RP wrote:
> Hi @yangqi2004
>
> Glad that you are interested in column oriented tables to the point of looking into `pg_appendonly`.  Your observation is not a bug.  For column oriented tables, Greenplum offers column specific encodings for compression and block size.  Therefore, `pg_appendonly` is not adequate to capture this information for each column.  We have a separate catalog table called `pg_attribute_encoding` for column oriented tables, that captures each column's compression details and block size.

Hmm. What are the compression-related columns in pg_appendonly used for, 
then?

- Heikki

**Comment by asimrp** [comment] 2015-12-11 00:40
The compression columns in `pg_appendonly` are used only for row-oriented tables.

**Comment by ashwinstar** [comment] 2016-01-04 17:54
Closing this issue as not a bug, feel free to let us know if something needs to be fixed.

**Closed by ashwinstar** 2016-01-04 17:54 UTC
