### ISSUE TITLE
two DISTRIBUTED REPLICATED tables union all causes exception

### ISSUE THREAD

**Issue by xiangruixiang** [greenplum-db/gpdb#10083] opened 2020-05-11 13:03 UTC
### Greenplum version or build
greenplum-db-6.2.1-rhel7-x86_64.rpm

### OS version and uname -a
Linux gp-mdw 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Actual behavior

org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [08006]: An I/O error occurred while sending to the backend.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:488)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:425)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:417)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:775)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2918)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3423)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:335)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:308)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	... 20 more

### Step to reproduce the behavior
CREATE TABLE t_company (
  f_id varchar PRIMARY KEY NOT NULL ,
  f_organiztion_id varchar DEFAULT NULL
 )
DISTRIBUTED REPLICATED;

SELECT f_id FROM t_company where  f_id='0a30476f-cc50-4caa-9691-94cc1ef1df40'
union all
SELECT f_id FROM t_company where  f_id='0a30476f-cc50-4caa-9691-94cc1ef1df40'

**Comment by gaos1** [comment] 2020-05-12 02:54
i cannot reproduce with 6.7.1.  could you upgrade and try again? if the issue is still there,  please also paste master error logs for the sql.

**Comment by gfphoenix78** [comment] 2020-06-22 06:28
@xiangruixiang When you got the error in the java call stack, do you get the error in the command line with the same SQL? It's a long calling path. We must know where the error occurs. Propagated errors are not very helpful for analyze.

**Comment by hlinnaka** [comment] 2020-08-28 06:49
There have been a few fixes to replicated tables and UNION on 6X_STABLE, so I suspect this has been fixed already. Like @gaos1 suggested, please upgrade. Closing, but if the upgrade doesn't help, feel free to re-open.

**Closed by hlinnaka** 2020-08-28 06:49 UTC
