### ISSUE TITLE
A SQL  that performs normally in GP5, but reports an error when executed in GP6:  PlaceHolderVar found where not expected！

### ISSUE THREAD

**Issue by Gogogofyl** [greenplum-db/gpdb#16193] opened 2023-08-12 04:47 UTC

**Comment by kainwen** [comment] 2023-08-12 09:01
There is many syntax error in your SQL, I believe it is because copy-paste error.
Can you provide minirepro of the SQL to help debug it?

How to use minirepro, please refer to https://community.pivotal.io/s/article/How-to-Collect-DDL-and-Statistics-Information-Using-the-Minirepro-Utility?language=en_US

It is important for us to have minirepro to debug.

**Comment by Gogogofyl** [comment] 2023-08-15 18:13
The bug can now be reproduced by:
SQL：
`
postgres=#  CREATE TABLE t1( id1 int) WITH 
                              (appendonly=true,  compresstype=none,  blocksize=8192) DISTRIBUTED BY (id1);

postgres=#  CREATE TABLE t4(id1 int, id2 text ) DISTRIBUTED BY (id1);

postgres=#   explain analyze select count(t1.id1),count(t4id2) tid2 from t1 left join (select id1,format('%s',id2)t4id2 from t4) t31 on t1.id1=t31.id1 having count(t4id2) is not null ;
`
ERROR:  PlaceHolderVar found where not expected (var.c:757)

**Comment by Gogogofyl** [comment] 2023-08-15 18:16
> There is many syntax error in your SQL, I believe it is because copy-paste error. Can you provide minirepro of the SQL to help debug it?
> 
> How to use minirepro, please refer to https://community.pivotal.io/s/article/How-to-Collect-DDL-and-Statistics-Information-Using-the-Minirepro-Utility?language=en_US
> 
> It is important for us to have minirepro to debug.

The bug can now be reproduced by the simple SQL：
```

postgres=#  CREATE TABLE t1( id1 int) WITH   (appendonly=true,  compresstype=none,  blocksize=8192) DISTRIBUTED BY (id1);

postgres=#  CREATE TABLE t4(id1 int, id2 text ) DISTRIBUTED BY (id1);

postgres=#   explain analyze select count(t1.id1),count(t4id2) tid2 from t1 left join (select id1,format('%s',id2)t4id2 from t4) t31 on t1.id1=t31.id1 having count(t4id2) is not null ;
```
ERROR: PlaceHolderVar found where not expected (var.c:757)

**Comment by kainwen** [comment] 2023-08-15 23:24
Thanks for the reproducible SQL. Only planner of 6X has the bug. Both version of ORCA works well and main branch's planner also work well.

**Comment by charliettxx** [comment] 2023-08-29 13:16
7x doesn't have such issue so we closed it.

**Closed by charliettxx** 2023-08-29 13:16 UTC
Labels: type: bug
