### ISSUE TITLE
Concurrently alter table's column type lead to lost of all data in the table.

### ISSUE THREAD

**Issue by uglthinx** [greenplum-db/gpdb#10216] opened 2020-06-01 13:01 UTC
### Greenplum version or build
6X_STABLE, master has such bug. 5X is OK.

### Step to reproduce the behavior

```sql
create table t(a int, b int, c int);
insert into t values (1, 1, 1) , (2,2,2);

1: begin; 
1: alter table t alter column b type text;

2: begin;
2: alter table t alter column c type text; -- this will hang on QD

1: end; -- after this the above 2 can go on
2: end;

-- after the two above transactions commit
select * from t; -- t contains nothing!
```

**Comment by kainwen** [comment] 2020-06-02 09:33
Hi @uglthinx 
I do not reproduce the issue locally.

1. Can you provide more detailed info?
2. what do you mean by `Execute the following sql when table tb redistributing`?
   
Currently, redustributing data will hold Access ExclusiveLock on the target table, so any other transactions operating on the table will hang.

Thanks.

**Comment by uglthinx** [comment] 2020-06-02 09:49
Hi @kainwen
redustributing data will indeed hold Access ExclusiveLock on the target table, and the `alter table tb alter column col type anytype;` will hang until the end of redistribution. But I found that this sql is done almost simultaneously with redistribution and the table `tb` will be emptied.

I did more tests today and found another serious Bug: Concurrent alter column type causes the data table to be emptied.
### Step to reproduce the behavior
1. Create table `customer` and insert some tuples:

![image](https://user-images.githubusercontent.com/29827608/83506136-551d0a80-a4f9-11ea-9e96-b4dea6422c69.png)
![image](https://user-images.githubusercontent.com/29827608/83505656-a973ba80-a4f8-11ea-8536-e0f91efef299.png)
2. Open two sessions, and execute the command to modify the field type on the table customer:
    `alter table customer alter column c_mktsegment type character(12);`
    `alter table customer alter column c_mktsegment type character(10);`
    Here you can select any two fields to modify the type of operation.
3. Re-verify after the two SQLs are executed:
![image](https://user-images.githubusercontent.com/29827608/83505854-f5befa80-a4f8-11ea-8d29-f4816fcb02c9.png)

I found that the two DDL statements were completed almost simultaneously, the field type was successfully modified, but the data table was cleared. I hope you have time to verify this problem,.

Thanks.

**Comment by kainwen** [comment] 2020-06-02 12:16
> Hi @kainwen
> redustributing data will indeed hold Access ExclusiveLock on the target table, and the `alter table tb alter column col type anytype;` will hang until the end of redistribution. But I found that this sql is done almost simultaneously with redistribution and the table `tb` will be emptied.
> 
> I did more tests today and found another serious Bug: Concurrent alter column type causes the data table to be emptied.
> 
> ### Step to reproduce the behavior
> 1. Create table `customer` and insert some tuples:
> 
> ![image](https://user-images.githubusercontent.com/29827608/83506136-551d0a80-a4f9-11ea-9e96-b4dea6422c69.png)
> ![image](https://user-images.githubusercontent.com/29827608/83505656-a973ba80-a4f8-11ea-8536-e0f91efef299.png)
> 2. Open two sessions, and execute the command to modify the field type on the table customer:
> `alter table customer alter column c_mktsegment type character(12);`
> `alter table customer alter column c_mktsegment type character(10);`
> Here you can select any two fields to modify the type of operation.
> 3. Re-verify after the two SQLs are executed:
> ![image](https://user-images.githubusercontent.com/29827608/83505854-f5befa80-a4f8-11ea-8d29-f4816fcb02c9.png)
> 
> I found that the two DDL statements were completed almost simultaneously, the field type was successfully modified, but the data table was cleared. I hope you have time to verify this problem,.
> 
> Thanks.

I reproduce your issue. You have found the direct cause:  `Concurrent alter column type causes the data table to be emptied.`.

This bug shocks me. Will fix it soon.

**Comment by kainwen** [comment] 2020-06-02 12:35
@uglthinx I restate the issue.

This will be fixed soon. Thanks for reporting this!

**Comment by kainwen** [comment] 2020-06-03 08:12
The root cause of this issue is:

1. distribute snapshot is generated in QD and dispatched to QEs
2. In `CdbDispatchUtilityStatement->cdbdisp_buildUtilityQueryParms->qdSerializeDtxContextInfo`, it
    uses `ActiveSnapshot->as_snap` to dispatch and it is built **before** acquiring locks on the target
    table.
3.  QD exeuctes the alter statement by `CdbDispatchUtilityStatement` but with an old distributed 
     snapshot. And that snapshot's satisfy function is `HeapTupleSatisfiesMVCC` which will first use 
     distributed snapshot.
4. Since distributed snapshot is dispatched from QD to QEs, even QEs invoke `GetLatestSnapshot`, it still can only use the old distributed snapshot.

If this will lead to other bugs need more investigation. Will look deep into this and have a fix soon.

This bug is introduced by merging Postgres 9.4 (with some snapshot related change).

**Comment by uglthinx** [comment] 2020-06-03 09:28
Thank you for your explanation and look forward to fixing it soon.

**Comment by kainwen** [comment] 2020-06-07 15:32
I have come up with another similar issue under the snapshot pattern:

```sql
drop table if exists rank;
DROP

CREATE TABLE rank (id int, rank int, year int) DISTRIBUTED BY (id) PARTITION BY RANGE (year) ( START (0) END (20) EVERY (4), DEFAULT PARTITION extra );
CREATE


insert into rank select i,i,i from generate_series(1, 100)i;
INSERT 100
select count(*) from rank;
 count
-------
 100
(1 row)

-- single transaction is OK
alter table rank split partition  for (5) at (5)  into (partition pa,  partition pb);
ALTER
select count(*) from rank;
 count
-------
 100
(1 row)


drop table rank;
DROP

CREATE TABLE rank (id int, rank int, year int) DISTRIBUTED BY (id) PARTITION BY RANGE (year) ( START (0) END (20) EVERY (4), DEFAULT PARTITION extra );
CREATE


insert into rank select i,i,i from generate_series(1, 100)i;
INSERT 100
select count(*) from rank;
 count
-------
 100
(1 row)

1: begin;
BEGIN
1: alter table rank alter column rank type text;
ALTER

2&: alter table rank split partition  for (5) at (5)  into (partition pa,  partition pb);  <waiting ...>

1:end;
END

2<:  <... completed>
ALTER

select count(*) from rank;
 count
-------
 96
(1 row)
```

----------

For the above and the issue, we have come up with local patch to fix.

We need to go through every corner and then submit a formal patch to fix completely.

**Comment by asimrp** [comment] 2020-06-08 05:31
Note that partitioning code, including split partitions, is being refactored heavily on the iteration branch, as part of PostgreSQL 12 merge effort.  If your patch to fix this issue involves changes to split partition related code, it will be good to confine the fix for 6X and look into the incoming changes in [iteration_REL_12](https://github.com/greenplum-db/gpdb-postgres-merge/tree/iteration_REL_12) branch.

**Comment by kainwen** [comment] 2020-06-08 05:33
> Note that partitioning code, including split partitions, is being refactored heavily on the iteration branch, as part of PostgreSQL 12 merge effort. If your patch to fix this issue involves changes to split partition related code, it will be good to confine the fix for 6X and look into the incoming changes in [iteration_REL_12](https://github.com/greenplum-db/gpdb-postgres-merge/tree/iteration_REL_12) branch.

Hi @asimrp 

This is not related to partition, the root cause is snapshot. The fix may not touch partition related code and it will provide a case for merge to consider.

**Comment by kainwen** [comment] 2020-06-09 08:25
Open a pr to fix this: https://github.com/greenplum-db/gpdb/pull/10272

**Comment by uglthinx** [comment] 2020-06-09 15:35
Hi @kainwen, In your pr I see the comment:
"if the first transaction is to rewrite the whole heap, and then the second Alter Table or Alter Domain statements continues with the distributed snapshot that txn1 does not commit yet, it will see no tuples in the new heap!"

I still don’t know why no tuples in the new heap instead of old snapshot.

**Comment by kainwen** [comment] 2020-06-10 01:04
> Hi @kainwen, In your pr I see the comment:
> "if the first transaction is to rewrite the whole heap, and then the second Alter Table or Alter Domain statements continues with the distributed snapshot that txn1 does not commit yet, it will see no tuples in the new heap!"
> 
> I still don’t know why no tuples in the new heap instead of old snapshot.

Hi @uglthinx  you can debug using the cases in that pr for better understanding.

Greenplum is merging upstream code. Postgres is a single segment database and everything in a query happens in one process. However, Greenplum is MPP database, segments contain data, master do parse, analyze, plan related work and then dispatch to segments to execute.

Postgres logic to implement alter table like statement:
1. get snapshot when running portal run, this is just after parse-analyze
2. process the utility statement, first try to hold the lock on the target table
3. Then, when it is to scan the heap data, get the latest snapshot, and use the latest snapshot to scan the heap

Greenplum has just the same logic and framework as above. But step 3 in the above, will be only executed on segments because only segment contains data. Greenplum is MPP database, it depends on distributed snapshot to implement MVCC on the heap data. Distributed snapshot is generated on master and then dispatched to segment. The function `GetLatestSnapshot` invoked in segments, can not ask for the latest distributed snapshot.

So, the bug is:

1. Txn 1 on master(QD) rewrite the heap, its distributed xid is 1; and it is not commited yet
2. Txn2 comes in and it creates a snapshot (also it creates the distributed snapshot `ds`, in `ds`,
    Txn1 is not committed
3. Txn2 continues to execute on master, and blocked by txn1 when it wants to hold locks on the target 
     table, so it hangs
4. Txn1 committed, and wake up txn2
5. txn2 goes on, but the active snapshot of txn2 still thinks that txn1 is not committed, because txn2 does not ask for to renew snapshot
6. txn2 dispatch utility to segments (with the snapshot `ds`, and remember in `ds`, txn1 is not committed, but txn1 is committed now)
7. txn1 does heap rewrite, and now the heap data in segments's xmax is null, only xmin is set using txn1's xid
8. txn2 scan the heap table in segments, with mvcc snapshot `ds`, it invokes the function `DistributedSnapshotWithLocalMapping_CommittedTest` to test if it can see the tuple,  since
  in `ds` the distributed transaction txn1 is not committed, so it cannot see the tuple.

**Comment by hidva** [comment] 2020-06-10 03:04
So we can use INSERT and ALTER COLUMN TYPE to trigger this BUG... 
```sql
create table test( i int , j int );
1: insert into test values( 1,  1 );
1: begin;
1: insert into test select i, i from generate_series(2, 100) f(i);
2: alter table test alter column j type varchar;  -- will block by 1
1: commit;
2: -- alter will finish
select * from test;  -- [2, 100) have been lost
 i | j
---+---
 1 | 1
(1 row)  
```

**Comment by uglthinx** [comment] 2020-06-15 07:24
Hi @kainwen , thanks for your previous explanation. I found that you used two ways to solve this issue, the first is "Update distributed snapshot before dispatching for some alterstmt." and the second is "GetLatestSnapshot on QEs always return without distributed snapshot.". It seems that both methods solve this problem. Which method do you prefer to choose?

**Comment by kainwen** [comment] 2020-06-15 07:29
> Hi @kainwen , thanks for your previous explanation. I found that you used two ways to solve this issue, the first is "Update distributed snapshot before dispatching for some alterstmt." and the second is "GetLatestSnapshot on QEs always return without distributed snapshot.". It seems that both methods solve this issue. Which method do you prefer to choose?

Currently we focus on the pr https://github.com/greenplum-db/gpdb/pull/10284
And see discussion in that pr's context.  Just close the previous pr and comments.

**Comment by kainwen** [comment] 2020-06-17 05:22
Fixed by https://github.com/greenplum-db/gpdb/pull/10284 for the master branch.

Fixed by https://github.com/greenplum-db/gpdb/pull/10312 for 6X stable.

Close this issue.

Thanks @uglthinx for reporting this. Please test in your env using the latest fix, if there are further problems, feel free to talk here or gpdb-dev mailing list.

**Closed by kainwen** 2020-06-17 05:22 UTC
