### ISSUE TITLE
Visibility failure in phantom_reads_update_serializable_column test.

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6241] opened 2018-11-15 07:32 UTC
I got a failure like this, on the PR pipeline, for PR #6222 (https://prod.ci.gpdb.pivotal.io/builds/154466). I'm very confident that the patch in the PR cannot have caused this, so it seems we have a visibility bug somewhere:

```
--- /tmp/build/ef6a11cc/gpdb_src/src/test/isolation2/expected/uao/phantom_reads_update_serializable_column.out	2018-11-14 23:01:34.455604364 +0000
+++ /tmp/build/ef6a11cc/gpdb_src/src/test/isolation2/results/uao/phantom_reads_update_serializable_column.out	2018-11-14 23:01:34.459606363 +0000
@@ -40,12 +40,11 @@
 22|22
 23|23
 24|24
-25|25
 26|26
 27|27
 28|28
 29|29
 30|30
-(11 rows)
+(10 rows)
 1: COMMIT;
 COMMIT
```
 
At a quick glance I couldn't see anything wrong in the snapshot handling in AOCS scan code, but clearly there is something wrong somewhere..

**Comment by l-wang** [comment] 2019-01-28 23:09
Closing as fixed. dc78e56 introduced a regression which was fixed in 2b4674a4a. This issue was filed between the two commits. Because we think that most likely GDD bumping up the dxid would have caused this failure, it is also relevant that GDD will no longer assign dxids after this recent commit 07787fb6 as well

**Closed by l-wang** 2019-01-28 23:09 UTC
