### ISSUE TITLE
hang for select from heap table

### ISSUE THREAD

**Issue by zwj19991999** [greenplum-db/gpdb#5161] opened 2018-06-15 06:04 UTC
### Greenplum version or build
5.7.0 and 5.8.1
### OS version and uname -a
3.10.0-514.26.2.el7.x86_64 #1
### Installation information ( pg_config )

BINDIR = /data/welab/gpadmin-app/greenplum-db/bin
DOCDIR = /data/welab/gpadmin-app/greenplum-db/doc/postgresql
HTMLDIR = /data/welab/gpadmin-app/greenplum-db/doc/postgresql
INCLUDEDIR = /data/welab/gpadmin-app/greenplum-db/include
PKGINCLUDEDIR = /data/welab/gpadmin-app/greenplum-db/include/postgresql
INCLUDEDIR-SERVER = /data/welab/gpadmin-app/greenplum-db/include/postgresql/server
LIBDIR = /data/welab/gpadmin-app/greenplum-db/lib
PKGLIBDIR = /data/welab/gpadmin-app/greenplum-db/lib/postgresql
LOCALEDIR = /data/welab/gpadmin-app/greenplum-db/share/locale
MANDIR = /data/welab/gpadmin-app/greenplum-db/share/man
SHAREDIR = /data/welab/gpadmin-app/greenplum-db/share/postgresql
SYSCONFDIR = /data/welab/gpadmin-app/greenplum-db/etc/postgresql
PGXS = /data/welab/gpadmin-app/greenplum-db/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/data/welab/gpadmin-app/greenplum-db/include
CFLAGS = -O3 -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -pg -DLINUX_PROFILE -I/data/welab/gpadmin-app/greenplum-db/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/home/gpadmin/app/greenplum-db/lib',--enable-new-dtags -L/data/welab/gpadmin-app/greenplum-db/lib
LDFLAGS_SL =
LIBS = -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lkrb5 -lcom_err -lgssapi_krb5 -lcrypt -ldl -lm -L/data/welab/gpadmin-app/greenplum-db/lib
VERSION = PostgreSQL 8.3.23

### Expected behavior

select heap table should get back all data

### Actual behavior

select heap table can`t get data, it hang.

### Step to reproduce the behavior

2018-06-15 13:49:54.971298 CST,"gpadmin","bdldb",p31052,th1388382336,"[local]",,2018-06-15 13:49:50 CST,0,con35,cmd1,seg-1,,dx7,,sx1,"LOG","00000","statement: select * from test;",,,,,,"select * from test;",0,,"postgres.c",1577,
2018-06-15 13:49:55.127673 CST,"gpadmin","bdldb",p31052,th1388382336,"[local]",,2018-06-15 13:49:50 CST,0,con35,cmd2,seg-1,,dx7,,sx1,"FATAL","XX000","Unexpected internal error (elog.c:4482)","FailedAssertion(""!(depth > 0)"", File: ""elog.c"", Line: 4482)","Process 31052 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,,"select * from test;",0,,"elog.c",4482,"Stack trace:
1    0x9c6000 postgres errstart (elog.c:521)
2    0x9bb0d9 postgres ExceptionalCondition (assert.c:40)
3    0x9c98f4 postgres gp_backtrace (discriminator 2)
4    0x9c9b1f postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread (elog.c:4618)
5    0x7f154ef3d6d0 libpthread.so.0 <symbol not found> + 0x4ef3d6d0
6    0x7f154e497dd6 libc.so.6 <symbol not found> + 0x4e497dd6
7    0xa5606e postgres CvtChunksToTup (tupser.c:1010)
8    0xa5352a postgres RecvTupleFrom (cdbmotion.c:99)
9    0x70a1a3 postgres ExecMotion (nodeMotion.c:405)
10   0x6d12e9 postgres ExecProcNode (execProcnode.c:1012)
11   0x6cde03 postgres <symbol not found> (tuptable.h:156)
12   0x6ce66e postgres ExecutorRun (execMain.c:914)
13   0x89e39a postgres <symbol not found> (pquery.c:1163)
14   0x8a039b postgres PortalRun (pquery.c:986)
15   0x89a8ab postgres <symbol not found> (postgres.c:1770)
16   0x89cf0b postgres PostgresMain (postgres.c:4943)
17   0x82ed8f postgres <symbol not found> (postmaster.c:6375)
18   0x83157a postgres PostmasterMain (postmaster.c:1533)
19   0x4ca56d postgres main (main.c:206)
20   0x7f154e364445 libc.so.6 __libc_start_main + 0xf5
21   0x4caad1 postgres <symbol not found> + 0x4caad1

**Comment by asimrp** [comment] 2018-06-15 14:20
@zwj19991999 can you please share some more details to help reproduce this issue?
* schema of the table
* an insert statement that causes subsequent select to fail like that
* number of segments in your cluster

**Comment by zwj19991999** [comment] 2018-06-19 02:57
CREATE TABLE test( code integer);

First Sense:
bdldb=# insert into test select generate_series(1,100000);
ERROR:  invalid memory alloc request size 1272971316 (context 'MotionLayerMemCtxt') (tupser.c:1056) (mcxt.c:475)
CONTEXT:  SQL statement "select Ta.code  from public.test as Ta where random() < 0.30000001192092895507812500000000000000 limit 30000 "

Second Sense:
bdldb=# insert into test select generate_series(1,100000);
FATAL:  Unexpected internal error (elog.c:4482)
DETAIL:  FailedAssertion("!(depth > 0)", File: "elog.c", Line: 4482)
HINT:  Process 7913 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
CONTEXT:  SQL statement "select Ta.code  from public.test as Ta where random() < 0.29613250494003295898437500000000000000 limit 30000 "
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

Third Sense:
bdldb=# select * from test;
FATAL:  Unexpected internal error (elog.c:4482)
DETAIL:  FailedAssertion("!(depth > 0)", File: "elog.c", Line: 4482)
HINT:  Process 7954 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.

Fourth Sense:
bdldb=# analyze test;
FATAL:  Unexpected internal error (elog.c:4482)
DETAIL:  FailedAssertion("!(depth > 0)", File: "elog.c", Line: 4482)
HINT:  Process 7961 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
CONTEXT:  SQL statement "select Ta.code  from public.test as Ta where random() < 0.02637381106615066528320312500000000000 limit 30000 "
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.



Our cluster have 8 segments,  machine is 32 cores , 64GB ,500GB ssd
This is very strange problem, some machine is normal, several is like this. we are use Aliyun server.
________________________________
发件人: Asim RP <notifications@github.com>
发送时间: 2018年6月15日 22:20
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


@zwj19991999<https://github.com/zwj19991999> can you please share some more details to help reproduce this issue?

  *   schema of the table
  *   an insert statement that causes subsequent select to fail like that
  *   number of segments in your cluster

―

**Comment by asimrp** [comment] 2018-06-19 17:00
Those are basic scenarios.  Their failure implies something specific to the environment is interfering.  @pivotal-ning-yu @pengzhout does this ring any bells?

**Comment by pengzhout** [comment] 2018-06-20 02:35
@zwj19991999 Looks like something bad happens on QD, can you go through the log of QD for SIGSEGV or SIGABORT and attach the backtrace? or upload the whole log, gist.github.com maybe a good choice.

**Comment by zwj19991999** [comment] 2018-06-20 03:01
@Tang pengzhou , our QD is normal, just QE not normal，we are apply 4 machine that same configuration(32 core 64GB 500G ssd) on Aliyun, but half normal, half occur these question.
where are exist that you said those log.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月20日 10:35
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


@zwj19991999<https://github.com/zwj19991999> Looks like something bad happens on QD, can you go through the log of QD for SIGSEGV or SIGABORT and attach the backtrace? or upload the whole log, gist.github.com maybe a good choice.

―

**Comment by pengzhout** [comment] 2018-06-20 03:36
@zwj19991999 Ahh, I saw the backtrace attached, a SIGSEGV happens on QD, what do you mean "QD is normal, just QE not normal", for your case "select * from test", only QD may report a backtrace as you attached.

**Comment by pengzhout** [comment] 2018-06-20 03:37
@zwj19991999 4 segments and 4 mirrors?

**Comment by zwj19991999** [comment] 2018-06-20 05:49
I had changed slave machine which run segments before yesterday. we found two were normal, other were bad that hang for select.
we  deploy 8 segments no mirrors
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月20日 11:37
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


@zwj19991999<https://github.com/zwj19991999> 4 segments and 4 mirrors?

―

**Comment by pengzhout** [comment] 2018-06-20 07:23
I still can not understand "two were normal, other hang for select", A query is supposed to involve all segments.  How do you change slave? reinitialize or change it manually?

**Comment by pengzhout** [comment] 2018-06-20 07:36
what's the output of "select * from gp_segment_configuration"?

**Comment by zwj19991999** [comment] 2018-06-20 08:19
two of these machines is ok, the other machines will hang.
we are reinitialize on these had changed machine.

all is fine when use 'select * from gp_segment_configuration'
it show the segment status is 'u',no problem.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月20日 15:36
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


what's the output of "select * from gp_segment_configuration"?

―

**Comment by zwj19991999** [comment] 2018-06-21 02:53
Hi! Could you give us more help about this issue?
________________________________
发件人: 张 文杰 <zwj19991999@hotmail.com>
发送时间: 2018年6月20日 16:19
收件人: greenplum-db/gpdb; greenplum-db/gpdb
抄送: Mention
主题: 答复: [greenplum-db/gpdb] hang for select from heap table (#5161)

two of these machines is ok, the other machines will hang.
we are reinitialize on these had changed machine.

all is fine when use 'select * from gp_segment_configuration'
it show the segment status is 'u',no problem.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月20日 15:36
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


what's the output of "select * from gp_segment_configuration"?

―

**Comment by zwj19991999** [comment] 2018-06-21 06:00
1. We are compile and build it with source code.
2. It`s down from github gpdb 5.7.0、 5.8.1 、5.9.0
3. What is core file？？？we are need help to find out solution.
4. We haven`t replaced the binary of GPDB in our server.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月21日 13:23
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


@zwj19991999<https://github.com/zwj19991999> as Asim said, it's more like an environment issue, few questions:

  1.  did you compile and build it with source code?
  2.  If it's an official release build, did you have the right GPDB version in your server? I noticed that your server is rhel7.
  3.  can you upload a core file? maybe it can help.
  4.  have you replaced the binary of GPDB ever in your server?

―

**Comment by pengzhout** [comment] 2018-06-21 06:53
A core file means a core dump file of the process, you can use gdb to generate it, refer to https://www.cnblogs.com/createyuan/p/3949001.htm. In this case, the process will exist for 120s, you can attach to it and generate a core. To help to debug, you can also change the "-O3" to "-O0" in file "src/Makefile.global" and make clean & rebuild it.

I'm trying to understand "the slave machine" you mentioned, are you trying to replace "segment/mirror" concept of GPDB with "master/slave" feature of aliyun (https://www.alibabacloud.com/help/zh/doc-detail/26182.htm)? so errors happened after you changed "slave machine"?

**Comment by zwj19991999** [comment] 2018-06-21 06:57
The means of “the slave machine" is one vm machine.if we found one of machines is hang for select, we would change a new one.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月21日 14:53
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


A core file means a core dump file of the process, you can use gdb to generate it, refer to https://www.cnblogs.com/createyuan/p/3949001.htm. In this case, the process will exist for 120s, you can attach to it and generate a core. To help to debug, you can also change the "-O3" to "-O0" in file "src/Makefile.global" and make clean & rebuild it.

I'm trying to understand "the slave machine" you mentioned, are you trying to replace "segment/mirror" concept of GPDB with "master/slave" feature of aliyun (https://www.alibabacloud.com/help/zh/doc-detail/26182.htm)? so errors happened after you changed "slave machine"?

―

**Comment by pengzhout** [comment] 2018-06-21 07:35
Can you please give a summary of your case? it's really really hard for us to guess what you have done.

1. you have 4 VM machine, 2 machines installed a GPDB cluster and another 2 VM machines installed another GPDB cluster. please clarify the layout of master and segments on VM machines.
2. 4 VM machines have the same configuration.
3. GPDB on first 2 machines works fine and another GPDB cluster gets hung for select.
4. when did you change to "slave machine", have you restart the cluster.
5. when is the hung issue happened,  before or after "slave machine" change?
6. It's also not promised that a "slave machine" change can work for GPDB.
7. Was the machine where QD exist changed to slave?

**Comment by zwj19991999** [comment] 2018-06-21 07:55
1.  we have 5 vm machine, 1 is master run QD, 4 is slave run QE.
  2.  4 slave vm machine have the same configuration.
  3.  master just connected 1 slave that test if normal every times.
  4.  We have restart the issue machine when occur hang
  5.  occur hang when we first insert into data and select data.

if it clear？
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月21日 15:35
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


Can you please give a summary of your case? it's really really hard for us to guess what you have done.

  1.  you have 4 VM machine, 2 machines installed a GPDB cluster and another 2 VM machines installed another GPDB cluster. please clarify the layout of master and segments on VM machines.
  2.  4 VM machines have the same configuration.
  3.  GPDB on first 2 machines works fine and another GPDB cluster gets hung for select.
  4.  when did you change to "slave machine", have you restart the cluster.
  5.  when is the hung issue happened, before or after "slave machine" change?
  6.  It's also not promised that a "slave machine" change can work for GPDB.
  7.  Was the machine where QD exist changed to slave?

―

**Comment by pengzhout** [comment] 2018-06-21 08:29
```
"master just connected 1 slave that test if normal every times."
```
Why does it only connect to 1 slave each time? Does 1 VM machine has 8 segments installed and another 3 VM machine is just a backup of the VM machine. Only 1 VM is actived at a time, if a VM  get hung, another VM will replace it?

Seems It's not a normal usage of GPDB as you described which brought unexpected issues.

**Comment by zwj19991999** [comment] 2018-06-21 08:31
just for test machine is normal for work.
________________________________
发件人: Tang Pengzhou <notifications@github.com>
发送时间: 2018年6月21日 16:30
收件人: greenplum-db/gpdb
抄送: zhang; Mention
主题: Re: [greenplum-db/gpdb] hang for select from heap table (#5161)


"master just connected 1 slave that test if normal every times."


Why does it only connect to 1 slave each time? Does 1 VM machine has 8 segments installed and another 3 VM machine is just a backup of the VM machine. Only 1 VM is actived at a time, if a VM get hung, another VM will replace it?

Seems It's not a normal usage of GPDB as you described which brought unexpected issues.

―

**Comment by jamesguo008** [comment] 2018-06-21 08:57
> A core file means a core dump file of the process, you can use gdb to generate it, refer to https://www.cnblogs.com/createyuan/p/3949001.htm. In this case, the process will exist for 120s, you can attach to it and generate a core. To help to debug, you can also change the "-O3" to "-O0" in file "src/Makefile.global" and make clean & rebuild it.

i got the core dump @pengzhout , but the not yet modify Makefile.global and rebuild.
[core_gdb.txt](https://github.com/greenplum-db/gpdb/files/2122795/core_gdb.txt)
[corelog.tar.gz](https://github.com/greenplum-db/gpdb/files/2122801/corelog.tar.gz)

**Comment by jamesguo008** [comment] 2018-06-21 09:05
> Why does it only connect to 1 slave each time? Does 1 VM machine has 8 segments installed and another 3 VM machine is just a backup of the VM machine. Only 1 VM is actived at a time, if a VM get hung, another VM will replace it?
> 
> Seems It's not a normal usage of GPDB as you described which brought unexpected issues.

at first we use vm1(master) vm2(4 seg) vm3(4 seg)

**Comment by jamesguo008** [comment] 2018-06-21 09:44
> Why does it only connect to 1 slave each time? Does 1 VM machine has 8 segments installed and another 3 VM machine is just a backup of the VM machine. Only 1 VM is actived at a time, if a VM get hung, another VM will replace it?
> 
> Seems It's not a normal usage of GPDB as you described which brought unexpected issues.

at first we use 3vm(16core 64gb) vm1(master) vm2(6 seg) vm3(6 seg)
after upgrade vm2/3 to 32core and reboot
we found all 6 seg at vm3 could not return data, using "select * from test where gp_segment_id=xxx"

so we apply another 32core 64gb vms for test: vm4 vm5 vm6
init gp using vm4(master) vm5(8 seg) and using test sql below:
CREATE TABLE test(code integer);
insert into test select generate_series(1,100000);     //  hang, ctrl+c
insert into test select generate_series(1,100);           //  ok
insert into test select generate_series(1,100000);     //  ok too
select * from test;                                                      // still hang

init gp using vm4(master) vm6(8 seg) and using test sql below:
CREATE TABLE test(code integer);
insert into test select generate_series(1,100000);     //  ok
select * from test;                                                      // ok

and we build gp source using 5.8.1/5.9.0/master branch, still the same.
then we apply vm7 and vm8 to be seg with vm4, same result, one ok another hang.

we update cpu core hope to get more performance
and we want to expand vm1's segment using new vms because of data scale
but being trapped by this strange issue now

**Comment by pengzhout** [comment] 2018-06-22 01:55
@jamesguo008 Thanks, it's much clearer now, I will take a look.

**Comment by pengzhout** [comment] 2018-06-22 03:14
@jamesguo008 can you help collect the core file again using packcore, packcore locates under ./gpMgmt/sbin/packcore,

the usage is like
```
./packcore -b '~/gpdb.master/bin/postgres' core.3608
```

please replace postgres path and core file accordingly. BTW, -O0 will help debuging

**Comment by jamesguo008** [comment] 2018-06-22 05:58
@pengzhout  bad news, after reboot the vm, it's normal now. So I'm afraid I can't offer you -O0 packcore. Does the -O3 one help?

**Comment by pengzhout** [comment] 2018-06-22 06:09
@jamesguo008 Yes, -O3 should be OK.

**Comment by jamesguo008** [comment] 2018-06-23 09:21
@pengzhout i sent to your email ptang@pivotal.io already

**Comment by ashwinstar** [comment] 2018-07-18 05:47
We would like to fix this issue but seems, unfortunately, don't have enough information to get to bottom of it to know what's going on. Hence closing the issue as no next step on the same. If encountering the issue again feel free to circle back with asked info to help triage and fix the issue.

**Closed by ashwinstar** 2018-07-18 05:47 UTC
