### ISSUE TITLE
System table "gp_segment_configuration" didn't get updated after some segments down!

### ISSUE THREAD

**Issue by chenkaijiang** [greenplum-db/gpdb#579] opened 2016-03-28 12:37 UTC
1) Environment info:
OS: CentOS 6.5 on VMware
GP: pull from github, Feb 10th, 2016
DB Config: 1 master on host3; 2 segments on host2, 2 segments on host1; NO mirror.

2) Step to repro

2.1)
Enter the DB with: psql gpmon -d gpperfmon
gpperfmon=# SELECT * FROM gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port  | hostname | address | replication_port | san_mounts 
------+---------+------+----------------+------+--------+-------+----------+---------+------------------+------------
    1 |      -1 | p    | p              | s    | u      |  5432 | host3  | host3 |                  | 
    2 |       0 | p    | p              | s    | u      | 40000 | host1  | host1 |                  | 
    4 |       2 | p    | p              | s    | u      | 40000 | host2  | host2 |                  | 
    3 |       1 | p    | p              | s    | u      | 40001 | host1  | host1 |                  | 
    5 |       3 | p    | p              | s    | u      | 40001 | host2  | host2 |                  | 
(5 rows)

2.2) power off the host2; wait for 30 minutes;

2.3) in master, execute the sql:
gpperfmon=# SELECT * FROM gp_segment_configuration;
 dbid | content | role | preferred_role | mode | status | port  | hostname | address | replication_port | san_mounts 
------+---------+------+----------------+------+--------+-------+----------+---------+------------------+------------
    1 |      -1 | p    | p              | s    | u      |  5432 | host3  | host3 |                  | 
    2 |       0 | p    | p              | s    | u      | 40000 | host1  | host1 |                  | 
    4 |       2 | p    | p              | s    | u      | 40000 | host2  | host2 |                  | 
    3 |       1 | p    | p              | s    | u      | 40001 | host1  | host1 |                  | 
    5 |       3 | p    | p              | s    | u      | 40001 | host2  | host2 |                  | 
(5 rows)

**Expected: the status of the segments in host2 should be 'd' (down)
Actual: all segments are 'u'
**
3) Other info
3.1)
If we try to create a table, we failed:
gpperfmon=# create table t2 (c1 int, c2 int) distributed by (c1);
ERROR:  failed to acquire resources on one or more segments

(which means the segments really down)

3.2)
In the log from the Master (%MASTER_PATH/pg_log), it clearly reports that some segments are down:

2016-03-28 18:41:13.470295 CST,,,p35217,th-1587104000,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: failed to probe segment (content=2, dbid=4) after trying 5 time(s), maximum number of retries reached.",,,,,,,0,,,,

**Comment by ashwinstar** [comment] 2016-03-28 16:31
FTS only works with mirrored configuration. Greenplum official doesn't
support mirror-less configuration.
In-case of only primaries and some of them down, the result is expected
what you see of query failing.

**Comment by chenkaijiang** [comment] 2016-03-29 03:04
In case of primary-only configuration, the query failing is expected. But if the FTS updates the gp_segment_configuration table, it will be helpful to locate the problem. And it looks un-logical that FTS has detected the segment failure while the gp_segment_configuration reports that everything is OK...

**Comment by asimrp** [comment] 2016-03-30 21:04
Hi @chenkaijiang, thank you for experimenting with GPDB.  By design, if the database becomes unavailable, FTS refrains from making any further changes.  E.g. in a mirrored configuration, if one of the replica goes down, FTS marks it down.  But if the other replica for the same content also goes down, this is a database unavailable (double fault) situation and FTS leaves the database unchanged.  The behavior you are seeing is due to this guiding principle.  In a mirror-less cluster, any segment going down is database unavailable situation.

If we want to change FTS as per your proposal, `gprecoverseg` workflow will need to change too.  As we will have to think about a way to let FTS mark a segment as up when the down segment is brought up.

**Comment by chenkaijiang** [comment] 2016-04-08 08:00
@asimrp thank you for your detailed reply. I understand the complexity. GPDB is very great product! Let's work on the mirrored configuration to make FTS work.

**Comment by asimrp** [comment] 2016-08-31 18:18
@chenkaijiang I'm closing this issue.  Please feel free to initiate a discussion on gpdb-dev mailing list about keeping `gp_segment_configuration` up to date at any cost.  Current design, as we mentioned earlier, is to refrain from making any change if the GPDB instance becomes unavailable (double fault).

**Closed by asimrp** 2016-08-31 18:18 UTC
