### ISSUE TITLE
greenplum  6.3.0 version is beta

### ISSUE THREAD

**Issue by witchang** [greenplum-db/gpdb#9502] opened 2020-01-27 03:08 UTC
we use https://github.com/greenplum-db/gpdb/tree/6.3.0 to build greenplum ,but start greenplum,it display "master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.0.0-beta.1 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit compiled on Jan 27 2020 00:05:58'   "
why the version is beta??

**Comment by danielgustafsson** [comment] 2020-01-27 09:08
The build is picking up the version in `configure.in` which needs to be adjusted during packaging. There is no automatic way to do this at the moment however.

**Comment by kmacoskey** [comment] 2020-01-27 16:20
This problem comes up every once and awhile. Let's figure out a way to fix it. I believe the issue is due to processes in upstream PostgreSQL that we are inheriting through the code that don't align with processes we currently have for Greenplum Database.

#### PostgreSQL's model (@danielgustafsson Please correct me if this is wrong):
1. There is a stable branch per "Major" version:
   - https://github.com/postgres/postgres/tree/REL_11_STABLE
2. When there is a new release of that "Major" version, it is always based on HEAD of that stable branch
3. When a release occurs, a new commit is created that updates the `configure.in` mentioned above (among others)
   - https://github.com/postgres/postgres/commit/34f805c8cf1bc4d54075526d3b023d9194ccd2cd
4.  A tag is created at that new commit
    - https://github.com/postgres/postgres/releases/tag/REL_11_6


#### The current Greenplum Database model:
1. There is a stable branch per "Major" version:
    - https://github.com/greenplum-db/gpdb/tree/6X_STABLE
2. When there is a new release of that "Major" version, it is **not** always based on HEAD of that stable branch
3. When a release occurs, the commit that should be released is picked (internal process)
4.  A tag is created at that chosen commit:
    - https://github.com/greenplum-db/gpdb/releases/tag/6.3.0

---

The process from PostgreSQL's model is inherited in the source code, such that it's expected that a new commit will be created that updates files like `configure.in` with the new release version. That new commit, being HEAD, is the point at which PostgreSQL is released. This conflicts with Greenplum's model because the commit chosen is **not** often the HEAD of the stable branch. It is fairly frequent that internal and sometimes business process necessitates releasing on an older commit. We aren't going to force push to the stable branch in order to add a new commit above the one that was chosen.

---

Here are a few options I can think of:

1. When a commit is chosen for a release, we create a new branch at that commit. In that branch, we create the necessary commit that updates files like `configure.in`. 
      - I'm not sure if the tag should exist on that new commit or on the commit where the branch was created
    - I've no idea what would be a good name for that branch
    - Any user that wants to compile a given release will need to checkout a different branch than the stable Major version branch
2. We modify the source code being inherited from PostgreSQL to remove the need to create commits in order to update files like `configure.in`
    - This would be a deviation from upstream PostgreSQL that we would need to always maintain through upstream merges
3. We no longer release Greenplum Database based on a commit that is not HEAD of the stable branch
   - This could be at conflict with business goals
   - Requires that HEAD is always releasable based on the business goals of when we release

> It is fairly frequent that internal and sometimes business process necessitates releasing on an older commit.

I think it's necessary to expand on this a bit more before the next option. The version of Greenplum Database (the tag) is not impacted by only the source code in this repository. Because the Greenplum Database version is the same as the "Pivotal Greenplum" version (Pivotal Greenplum is a suite of many products, both OSS and not), the version chosen is based on many other processes and product releases. While it hasn't yet occured, the time will come for branches like 5X_STABLE where the same commit can have multiple tags because something other than the source code here necessitates a new release. That alone could conflict with the idea of making a new commit when there is a new release among other problems.

4. We separate the Greenplum Database version from the "Pivotal Greenplum" version
   - Business goals can be separated from source code processes, which makes option (3) more possible
   - Could be confusing for enterprise users to suddenly version what looks like the same product into two different versioned products
   - We can't make this a reality by making code changes - It requires business changes

**Comment by asimrp** [comment] 2020-01-28 04:49
Thank you for the elaborate description @kmacoskey, the problem is clear in my head now.  I'm wondering how option 2 - modify source code to remove the need to create commits - would look like.  Would the version string be maintained outside of source repository?

**Comment by danielgustafsson** [comment] 2020-01-28 11:15
> This problem comes up every once and awhile. Let's figure out a way to fix it.

Agreed. Thanks for the detailed write-up!

> I believe the issue is due to processes in upstream PostgreSQL that we are inheriting through the code that don't align with processes we currently have for Greenplum Database.
> #### PostgreSQL's model (@danielgustafsson Please correct me if this is wrong):

That is a correct depiction.

> This conflicts with Greenplum's model because the commit chosen is **not** often the HEAD of the stable branch. It is fairly frequent that internal and sometimes business process necessitates releasing on an older commit.

Right, this is the main culprit and why we're having this discussion at all. More on this further down.

> We aren't going to force push to the stable branch in order to add a new commit above the one that was chosen.

Obviously not.

> Here are a few options I can think of:
> 
>     1. When a commit is chosen for a release, we create a new branch at that commit. In that branch, we create the necessary commit that updates files like `configure.in`.
>        
>        * I'm not sure if the tag should exist on that new commit or on the commit where the branch was created
>        * I've no idea what would be a good name for that branch
>        * Any user that wants to compile a given release will need to checkout a different branch than the stable Major version branch

This is doable, but messier.

>     2. We modify the source code being inherited from PostgreSQL to remove the need to create commits in order to update files like `configure.in`

Well, we kind of already have, except it only works when building in a specific way.

>     3. We no longer release Greenplum Database based on a commit that is not HEAD of the stable branch
>        
>        * This could be at conflict with business goals
>        * Requires that HEAD is always releasable based on the business goals of when we release

HEAD should always be releasable based on technical merit, else we need to practice more caution in backports (which we probably should anyways, but that's a separate discussion from this). I'll have more to say about the business goals below.

> While it hasn't yet occured, the time will come for branches like 5X_STABLE where the same commit can have multiple tags because something other than the source code here necessitates a new release.

I will object strongly to tagging a new release to satisfy the needs of a distribution.

>     1. We separate the Greenplum Database version from the "Pivotal Greenplum" version

This is what I think must happen.

Pivotal Greenplum should be a distribution consuming Greenplum Database, just like any other Greenplum derivative. Greenplum Database ships the branch based on HEAD, and distributions are then free to pick any other point in history and/or add additional code and value-adds before wrapping their releases.

>        * Business goals can be separated from source code processes, which makes option (3) more possible
>        * Could be confusing for enterprise users to suddenly version what looks like the same product into two different versioned products

Maybe, but I doubt this will be a problem in reality. Compare with the Linux kernel which in any given Linux distribution is different from upstream, even though the version numbers line up (with additional version signifiers from the distro in many cases). If there is confusion then that would be because of a branding problem, as Greenplum Database is a different product from Pivotal Greenplum, which in turn is a different product from all other Greenplum distributions.

>        * We can't make this a reality by making code changes - It requires business changes

Well, the project has no business goals per se, but given that the project originated within Pivotal and Pivotal employs the vast majority of people working it, the business goals of Pivotal shines through and has in this case dictated process. So this is a change of process, with which the business goals of Pivotal (and everyone else) can remain and probably even simplified as there is no need to synchronize.

**Comment by witchang** [comment] 2020-01-28 13:00
so，in production，which branch we can use，6X_stable，or 6.3.0tag，just manual modify configure.in or orther way


发自我的iPhone

------------------ Original ------------------

**Comment by danielgustafsson** [comment] 2020-01-28 13:03
> so，in production，which branch we can use，6X_stable，or 6.3.0tag，just manual modify configure.in or orther way

For production I recommend using the minor-rev release tag, in this case the 6.3.0 tag.

**Comment by witchang** [comment] 2020-01-29 04:13
we have modify the file "configure.in"
old content is : AC_INIT([Greenplum Database], [6.0.0-beta.1], [support@greenplum.org]);
new content is :AC_INIT([Greenplum Database], [6.3.0], [support@greenplum.org]);
but nothing changed

**Comment by danielgustafsson** [comment] 2020-01-30 10:05
> On 29 Jan 2020, at 05:13, witchang <notifications@github.com> wrote:
> 
> we have modify the file "configure.in"
> old content is : AC_INIT([Greenplum Database], [6.0.0-beta.1], [support@greenplum.org]);
> new content is :AC_INIT([Greenplum Database], [6.3.0], [support@greenplum.org]);
> but nothing changed

Did you "make distclean" before rebuilding?  What does ./getversion in the root
of the source tree give?

**Comment by witchang** [comment] 2020-02-03 01:54
we run "make distclean",but found error as below:
You need to run the 'configure' program first. See the file
'INSTALL' for installation instructions.
make: *** [distclean] 错误 1

**Comment by kmacoskey** [comment] 2020-02-03 21:55
@asimrp 

> On Mon, Jan 27, 2020 at 9:49 PM Asim R P <notifications@github.com> wrote:
> Thank you for the elaborate description @kmacoskey, the problem is clear in my head now. I'm wondering how option 2 - modify source code to remove the need to create commits - would look like. Would the version string be maintained outside of source repository?

Yes, this would essentially be the end result. We already somewhat do this in existing processes. However where it breaks down is the conflation of multiple versions. If we use the same version for both the "Server" ("Greenplum Database") and "Pivotal Greenplum" then even if we store one version in a private location and the other in the OSS repository, we will still have process conflicts.

@danielgustafsson 

> On Tue, Jan 28, 2020 at 4:15 AM Daniel Gustafsson <notifications@github.com> wrote:
> I will object strongly to tagging a new release to satisfy the needs of a distribution.

As will I, doing this is a symptom of a misaligned process. We thankfully haven't reached this day yet, but unless we change something it's going to inevitably become a topic of issue. I'd much rather fix the problem when it's not actively happening.

> On Tue, Jan 28, 2020 at 4:15 AM Daniel Gustafsson <notifications@github.com> wrote:
> This is what I think must happen.
> Pivotal Greenplum should be a distribution consuming Greenplum Database, just like any other Greenplum derivative. Greenplum Database ships the branch based on HEAD, and distributions are then free to pick any other point in history and/or add additional code and value-adds before wrapping their releases.

I'm very much an advocate for Option 4. Pivotal Greenplum is downstream from Greenplum Database and should be treated as such as it relates to versioning and processes. While it makes me slightly biased, Option 4 can significantly reduce the complexity in the current release process.

> On Tue, Jan 28, 2020 at 4:15 AM Daniel Gustafsson <notifications@github.com> wrote:
> If there is confusion then that would be because of a branding problem, as Greenplum Database is a different product from Pivotal Greenplum, which in turn is a different product from all other Greenplum distributions.

When I stated the Option 4 requires business changes, this is mostly what I was thinking. I have found surprisingly few internal R&D stakeholders, other internal stakeholders, or end users that have a clear understanding about what the difference is between "Pivotal Greenplum", "Greenplum Database", and the "Server". I think it will be non-trivial to get everyone aligned on this same topic, with the opposition being that we should solve this with technical solutions and not try to change product taxonomy for a problem that not everyone will agree is actually a problem.

---

The release engineering team is committed to supporting Option 2, 3, and 4. Option 1, while an option, will likely create a lot of work for us specifically (among others) and it only adds even more complexity. The remaining options can significantly reduce the complexity and conflicting processes. Other options are of course welcome and needed.

RelEng can advocate and discuss this topic but we have thus far made little impact in something actually changing. We are downstream of the Server and in no way should make the final decision. I believe change will require support from all of users that share code ownership in this repository and greater visibility of this topic to all of the related stakeholders (internal and external).

**Closed** 2022-02-11 08:41 UTC
