### ISSUE TITLE
Header incompatibility with Postgres 8.3 in 5x_STABLE

### ISSUE THREAD

**Issue by acmnu** [greenplum-db/gpdb#4777] opened 2018-03-27 14:26 UTC
I don't now is it trouble or not, but we have includes that is not in sync with claimed version of Postgres. (claimed 8.3, but actual is 8.4)

### Greenplum version or build

Checked on version 5.5.0, but according to source code branch 5x_STABLE affected since  
6b0e52be 

### Code analyse

In original Postgres 8.3.23 ( https://www.postgresql.org/ftp/source/v8.3.23/)
Function src/include/utils/array.h:makeMdArrayResult has following signature (5 args):

```
extern Datum makeMdArrayResult(ArrayBuildState *astate, int ndims,
                  int *dims, int *lbs, MemoryContext rcontext);
```

In GPDB 5x_STABLE it has following signature (6 args):

```
extern Datum makeMdArrayResult(ArrayBuildState *astate, int ndims,
				  int *dims, int *lbs, MemoryContext rcontext, bool release);
```

That cause following code (PostGIS):

```
#if POSTGIS_PGSQL_VERSION < 84
        result = makeMdArrayResult(state, 1, dims, lbs, mctx);
#else
        result = makeMdArrayResult(state, 1, dims, lbs, mctx, false);
#endif
```
Fails with: 

```
lwgeom_accum.c: In function 'pgis_accum_finalfn':
lwgeom_accum.c:170:2: error: too few arguments to function 'makeMdArrayResult'
  result = makeMdArrayResult(state, 1, dims, lbs, mctx);
  ^
In file included from lwgeom_accum.c:17:0:
/usr/lib/gpdb/include/postgresql/server/utils/array.h:253:14: note: declared here
 extern Datum makeMdArrayResult(ArrayBuildState *astate, int ndims,
```

Version of Postgres calculated from pg_config output. It shows 8.3.23.

Should it be fixed in GPDB in some way? Looks like we have a lot of includes from 8.4.

**Comment by acmnu** [comment] 2018-03-27 14:35
Sorry, wrong commit in issue description. Fixed.

**Comment by hlinnaka** [comment] 2018-03-28 10:25
We don't generally guarantee the all the backend functions to be compatible with the corresponding PostgreSQL version. That said, we do try to keep them compatible, on a "best effort" basis.

Looking at the git history, we've had that 6-argument version of makeMdArrayResult() IN GPDB basically forever, before GPDB was open sourced, going back all the way to 2009. And in GPDB 'master', which will eventually become GPDB 6, we have already merged with PostgreSQL 8.4, so the `POSTGIS_PGSQL_VERSION < 84` test will be false and it will just work.

I don't feel like changing it just for GPDB 5, only to change have it changed to the 6-argument version again in GPDB 6. Besides, changing it in a minor release of GPDB 5 might break other extensions that use the 6-argument version. I think the best action here from GPDB side is to do nothing. Yeah, that means that you need to patch PostGIS to fix that, I'm afraid.

**Comment by Eulerizeit** [comment] 2018-03-28 10:47
We do have a PostGIS extension that works with Greenplum that is open sourced. @fmcquillan99 is the PM and can probably point you to the code.

**Comment by d** [comment] 2018-04-01 23:53
The expectation that Greenplum 5.X is _header compatible_ with Postgres 8.3 is wrong. This is not a bug. Can we close this yet?

**Comment by acmnu** [comment] 2018-04-04 12:09
@Eulerizeit Yep, I know about special version of PostGIS now.

@d As for me it could be closed if no core developers thinks it is a bug. But from my point of view it's not good that pg_config tell something that is not truth indeed . May be it's good point for future development.

**Closed** 2018-05-02 18:29 UTC
