### ISSUE TITLE
gpinitsystem fails when run with the debug flag

### ISSUE THREAD

**Issue by bradfordb-vmware** [greenplum-db/gpdb#13439] opened 2022-04-30 00:23 UTC
## Bug Report

Running `gpinitsystem` with log output set to debug level (`-D`) fails to create a cluster

### Greenplum version or build

```console
$ git describe
7.0.0-alpha.0-15298-g2af69d736d
```

### OS version and uname -a

```console
cat /etc/os
$ cat /etc/os-release   
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux bradfordb-gpdb7 5.10.0-13-cloud-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
```

### autoconf options used ( config.status --config )

Defaults

```console
$ ./config.status --config
.
```

### Installation information ( pg_config )

```console
$ pg_config
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = 
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lrt -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl -lzstd
VERSION = PostgreSQL 12beta2
```

### Expected behavior

Running `gpinitsystem -D` should create a cluster and show detailed log messages

### Actual behavior

`gpinitsystem -D` fails to create a cluster

### Step to reproduce the behavior

```console
$ cd gpAux/gpdemo
$ source /usr/local/gpdb/greenplum_path.sh
$ sed -i -e 's@^\$GPPATH/gpinitsystem -a@\$GPPATH/gpinitsystem -D -a@' demo_cluster.sh
$ make
...
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-Start Function GET_PG_PID_ACTIVE
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-Start Function PING_HOST
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-bradfordb-gpdb7 contact established
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-End Function PING_HOST
/usr/local/gpdb/bin/lib/gp_bash_functions.sh: line 877: [: too many arguments
/usr/local/gpdb/bin/lib/gp_bash_functions.sh: line 882: [: too many arguments
/usr/local/gpdb/bin/lib/gp_bash_functions.sh: line 887: [: too many arguments
/usr/local/gpdb/bin/lib/gp_bash_functions.sh: line 899: [: too many arguments
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-End Function GET_PG_PID_ACTIVE
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[INFO]:-Start Function ERROR_EXIT
20220430:00:20:47:161496 gpinitsystem:bradfordb-gpdb7:bboyle-[FATAL]:-Host bradfordb-gpdb7 has an active database process on port = 7002 Script Exiting!
```

The system definitely does not have an active database process on port 7002

```console
$ lsof -i :7002
.
$ netstat -tlen | grep 7002
.
$ ls /tmp/.s.PGSQL.*           
zsh: no matches found: /tmp/.s.PGSQL.*
```

**Comment by bmdoil** [comment] 2022-05-10 17:17
@bradfordb-vmware I've confirmed this issue also occurs on 6X_STABLE. Seems the `-D` flag has been broken for some time.
```
$ which gpinitsystem
/usr/local/gpdb6/bin/gpinitsystem
```

```
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Standby IP address array = $2}'
/usr/local/gpdb6/bin/gpinitsystem: line 494: [: too many arguments
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Checking configuration parameters, Completed
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-End Function CHK_PARAMS
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function CHK_MULTI_HOME
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Commencing multi-home checks, please wait...
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function PING_HOST
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-bdoil-ub contact established
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-End Function PING_HOST
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Configuring build for standard array
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Commencing multi-home checks, Completed
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-End Function CHK_MULTI_HOME
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function CREATE_QE_ARRAY
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Building primary segment instance array, please wait...
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function POSTGRES_PORT_CHK
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function GET_PG_PID_ACTIVE
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function PING_HOST
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-bdoil-ub contact established
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-End Function PING_HOST
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: 2>/dev/null: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: REMOTE_EXECUTE_AND_GET_OUTPUT: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1055: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1060: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1066: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1079: [: too many arguments
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-End Function GET_PG_PID_ACTIVE
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[INFO]:-Start Function ERROR_EXIT
20220510:13:15:47:022099 gpinitsystem:bdoil-ub:bdoil-[FATAL]:-Host bdoil-ub has an active database process on port = 6002 Script Exiting!
```

**Comment by zhjwpku** [comment] 2022-07-14 07:25
This bug also reproduced on ubuntu 20.04 and macos 12.2.1.
Trying to fix it, but failed, `REMOTE_EXECUTE_AND_GET_OUTPUT`
seems to be the source of the error, really a obscure function ;(

**Comment by piyushc01** [comment] 2022-11-30 18:06
Fixed merged on 6X and Master already. 
PR: 
Master: https://github.com/greenplum-db/gpdb/pull/13942
6X: https://github.com/greenplum-db/gpdb/pull/14016

**Closed by piyushc01** 2022-11-30 18:06 UTC
Labels: type: bug, topic: cluster mgmt, version: 6X_STABLE, version: 7X_ALPHA
