### ISSUE TITLE
Incorrect result with UNION ALL

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#12031] opened 2021-05-24 08:09 UTC
### Greenplum version or build

- GP: 6.16.0

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

The contents of the original result set should not be modified after union two result sets.

### Actual behavior

One result set has two records, and the other one does not. Although the result set has two records after the two are merged, the content of the field `over` changes from `false` to `true`, which is a magical phenomenon.

### Step to reproduce the behavior

```sql
select b.type, b.plant_code1, b.model7, f.model
	, f.last_build_date::date + case when f.model~'^.F.+$' then interval '5year' else interval '1year' end <= current_date "over"
	from t_bcn_model b
	join dw.fact_mds_model_info f on f.model = b.model7
```
![2021-05-24 15-54-04屏幕截图](https://user-images.githubusercontent.com/11460848/119315731-bd37a400-bca8-11eb-93d7-b50dc64bd27a.png)

```sql
select b.type, b.plant_code1, b.model7, f.model
	, f.last_build_date::date + interval '1year' <= current_date "over"
	from t_bcn_model b
	join dw.fact_pca_model_info f on f.model = b.model7
```
![2021-05-24 15-54-17屏幕截图](https://user-images.githubusercontent.com/11460848/119315740-c0cb2b00-bca8-11eb-8781-053325818af9.png)

```sql
select b.type, b.plant_code1, b.model7, f.model
	, f.last_build_date::date + case when f.model~'^.F.+$' then interval '5year' else interval '1year' end <= current_date "over"
	from t_bcn_model b
	join dw.fact_mds_model_info f on f.model = b.model7
union all
select b.type, b.plant_code1, b.model7, f.model
	, f.last_build_date::date + interval '1year' <= current_date "over"
	from t_bcn_model b
	join dw.fact_pca_model_info f on f.model = b.model7 
```
![2021-05-24 15-53-25屏幕截图](https://user-images.githubusercontent.com/11460848/119315716-b90b8680-bca8-11eb-8d84-b56449ceef31.png)

```
"Gather Motion 20:1  (slice3; segments: 20)  (cost=1.17..120.59 rows=23 width=35) (actual time=5.774..93.301 rows=2 loops=1)"
"  ->  Append  (cost=1.17..120.59 rows=2 width=35) (actual time=4.357..5.534 rows=1 loops=1)"
"        ->  Subquery Scan on ""*SELECT* 1""  (cost=1.17..59.33 rows=1 width=36) (actual time=4.357..4.693 rows=1 loops=1)"
"              ->  Hash Join  (cost=1.17..59.21 rows=1 width=43) (actual time=4.356..4.691 rows=1 loops=1)"
"                    Hash Cond: ((f.model)::text = b.model7)"
"                    Extra Text: (seg5)   Hash chain length 1.0 avg, 1 max, using 1 of 262144 buckets."
"                    ->  Seq Scan on fact_mds_model_info f  (cost=0.00..47.50 rows=138 width=21) (actual time=0.550..0.573 rows=148 loops=1)"
"                    ->  Hash  (cost=1.12..1.12 rows=1 width=22) (actual time=3.420..3.420 rows=1 loops=1)"
"                          ->  Redistribute Motion 20:20  (slice1; segments: 20)  (cost=0.00..1.12 rows=1 width=22) (actual time=3.396..3.417 rows=1 loops=1)"
"                                Hash Key: b.model7"
"                                ->  Seq Scan on t_bcn_model b  (cost=0.00..1.04 rows=1 width=22) (actual time=0.016..0.018 rows=4 loops=1)"
"        ->  Subquery Scan on ""*SELECT* 2""  (cost=1.17..61.26 rows=1 width=35) (never executed)"
"              ->  Hash Join  (cost=1.17..61.15 rows=1 width=42) (never executed)"
"                    Hash Cond: ((f_1.model)::text = b_1.model7)"
"                    ->  Seq Scan on fact_pca_model_info f_1  (cost=0.00..48.93 rows=145 width=20) (actual time=0.319..0.348 rows=162 loops=1)"
"                    ->  Hash  (cost=1.12..1.12 rows=1 width=22) (actual time=0.014..0.014 rows=1 loops=1)"
"                          ->  Redistribute Motion 20:20  (slice2; segments: 20)  (cost=0.00..1.12 rows=1 width=22) (actual time=0.010..0.013 rows=1 loops=1)"
"                                Hash Key: b_1.model7"
"                                ->  Seq Scan on t_bcn_model b_1  (cost=0.00..1.04 rows=1 width=22) (actual time=0.051..0.053 rows=4 loops=1)"
"Planning time: 3.509 ms"
"  (slice0)    Executor memory: 263K bytes."
"  (slice1)    Executor memory: 60K bytes avg x 20 workers, 60K bytes max (seg0)."
"  (slice2)    Executor memory: 60K bytes avg x 20 workers, 60K bytes max (seg0)."
"  (slice3)    Executor memory: 4264K bytes avg x 20 workers, 4272K bytes max (seg5).  Work_mem: 1K bytes max."
"Memory used:  204800kB"
"Optimizer: Postgres query optimizer"
"Execution time: 124.450 ms"
```

**Comment by guofengrichard** [comment] 2021-05-25 02:31
@cobolbaby Thanks for the report. Would you please provide the definition of the three related tables? And what data should be in the tables to reproduce this problem?

**Comment by cobolbaby** [comment] 2021-05-27 01:11
@guofengrichard  Can't it be reproduced based on the above result level? The function test of union all should only need to focus on the result set of the two sub-queries.

**Comment by JunfengYang** [comment] 2021-05-31 03:31
@cobolbaby  I try to guess your table definitions but failed to reproduce the issue. The plan and execution may vary with different conditions. So it better to provide as much as info if possible.

Here's what I used to reproduce it:
```
create table t_bcn_model (id int, type text, plant_code1 text, model7 text);
insert into t_bcn_model values (1, 'cpu', 'CP71', 'WF2598042001'), (2, 'cpu', 'CP71', 'WZ2598005001');

create table fact_mds_model_info (id int, model varchar(12), last_build_date timestamp) distributed by (model);
insert into fact_mds_model_info values (1, 'WF2598042001', '20180101 12:00:00'), (2, 'WZ2598005001', '20201101 12:00:00');
insert into fact_mds_model_info select i, 'ttttt', '20200101 12:00:00' from generate_series(3, 1000) as i;

create table fact_pca_model_info (id int, model varchar(12), last_build_date timestamp) distributed by (model);
insert into fact_pca_model_info values (1, 'WF2598042002', '20180101 12:00:00'), (2, 'WZ2598005003', '20201101 12:00:00');
insert into fact_pca_model_info select i, 'ttttt', '20200101 12:00:00' from generate_series(3, 1000) as i;

analyze t_bcn_model;
analyze fact_mds_model_info ;
analyze fact_pca_model_info;
```

And the plan
```
                                                QUERY PLAN
-----------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice3; segments: 3)  (cost=2.08..76.00 rows=1334 width=29)
   ->  Append  (cost=2.08..76.00 rows=445 width=29)
         ->  Hash Join  (cost=2.08..32.17 rows=223 width=36)
               Hash Cond: ((f.model)::text = b.model7)
               ->  Seq Scan on fact_mds_model_info f  (cost=0.00..13.00 rows=334 width=14)
               ->  Hash  (cost=2.06..2.06 rows=1 width=22)
                     ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..2.06 rows=1 width=22)
                           Hash Key: b.model7
                           ->  Seq Scan on t_bcn_model b  (cost=0.00..2.02 rows=1 width=22)
         ->  Hash Join  (cost=2.08..30.50 rows=223 width=36)
               Hash Cond: ((f_1.model)::text = b_1.model7)
               ->  Seq Scan on fact_pca_model_info f_1  (cost=0.00..13.00 rows=334 width=14)
               ->  Hash  (cost=2.06..2.06 rows=1 width=22)
                     ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..2.06 rows=1 width=22)
                           Hash Key: b_1.model7
                           ->  Seq Scan on t_bcn_model b_1  (cost=0.00..2.02 rows=1 width=22)
 Optimizer: Postgres query optimizer
(17 rows)
```

**Comment by cobolbaby** [comment] 2021-05-31 08:52
@JunfengYang 

- dw.fact_mds_model_info

```
CREATE TABLE dw.fact_mds_model_info
(
    model character varying(16) COLLATE pg_catalog."default",
    ispo integer,
    last_build_podn character varying(30) COLLATE pg_catalog."default",
    last_build_sno character varying(30) COLLATE pg_catalog."default",
    family character varying(50) COLLATE pg_catalog."default",
    custname character varying(10) COLLATE pg_catalog."default",
    last_build_wc character varying(3) COLLATE pg_catalog."default",
    last_build_date timestamp without time zone
)
DISTRIBUTED BY (model)
;
```
[dw-fact_mds_model_info-1622450628083.csv](https://github.com/greenplum-db/gpdb/files/6569039/dw-fact_mds_model_info-1622450628083.csv)

- dw.fact_pca_model_info

```
CREATE TABLE dw.fact_pca_model_info
(
    model character varying(12) COLLATE pg_catalog."default",
    last_build_wkno character varying(20) COLLATE pg_catalog."default",
    last_build_mcbsno character(10) COLLATE pg_catalog."default",
    cust_sno character varying(30) COLLATE pg_catalog."default",
    family character varying(20) COLLATE pg_catalog."default",
    customer character varying(15) COLLATE pg_catalog."default",
    last_build_wc character(2) COLLATE pg_catalog."default",
    last_build_date timestamp without time zone,
    udt timestamp with time zone
)
DISTRIBUTED BY (model)
;
```

[dw-fact_pca_model_info-1622450555869.csv](https://github.com/greenplum-db/gpdb/files/6569044/dw-fact_pca_model_info-1622450555869.csv)

- t_bcn_model

```
create temp table t_bcn_model (id int, type text, plant_code1 text, model7 text);
insert into t_bcn_model values (1, 'cpu', 'CP71', 'WF2598042001'), (2, 'cpu', 'CP71', 'WZ2598005001');
```

**Comment by bbbearxyz** [comment] 2021-06-02 08:53
I reproduce this issue by insertting only one tuple 
`insert into dw.fact_mds_model_info values('WF2598042001', 0, '4122478841000330', 'IEC0283331713', 'SAGITTA', 'F1', 83, '2020/3/6  3:43:08 PM')`

**Comment by bbbearxyz** [comment] 2021-06-03 08:54
I simply the sql
```sql
CREATE TABLE table1
(
    model character varying(16),  
    last_build_date timestamp
)
DISTRIBUTED BY (model)
;


CREATE TABLE table2
(
    model character varying(12), 
    last_build_date timestamp
)
DISTRIBUTED BY (model)
;

create table table3 (model2 text);
insert into table3 values ('WF2598042001');

insert into table1 values('WF2598042001','2020/3/6 3:43:08 PM');



select b.model2, f.model, f.last_build_date::date + case when f.model~'^.F.+$' then interval '5year' else interval '1year' end <= current_date "over"
	from table3 b
	join table1 f on f.model = b.model2
union all
select b.model2, f.model, f.last_build_date::date + interval '1year' <= current_date "over"
	from table3 b
	join table2 f on f.model = b.model2;
	
drop table table1;
drop table table2;
drop table table3;
```

**Comment by bbbearxyz** [comment] 2021-06-03 09:17
@cobolbaby  If you want to solve this problem, you can change the ddl dw.fact_mds_model_info and dw.fact_pca_model_info. you should keep the model column length consistent(model length in dw.fact_mds_model_info  is 16, dw.fact_pca_model_info is 12), and I think this problem will not happen. And I will solve this problem later.

**Comment by cobolbaby** [comment] 2021-06-03 13:50
@bbbearxyz  Thank you for the solution.

But I'm curious why two fields with different length definitions affect the results after union.

**Comment by JunfengYang** [comment] 2021-06-04 09:26
@cobolbaby is trying to find the root cause, there's clearly a but when do the set operation on different types.

**Comment by bbbearxyz** [comment] 2021-06-15 02:49
When the tuple is distributed by hash, we need to make true that the hash key is in the targetlist. So the function `add_to_flat_tlist_junk` can add hash key to the targetlist when it isn't in it. But the problem in the issue is that when the var length is different, we think they are different and add the hash key in the targetlist but they are already in the targetlist.

**Comment by kainwen** [comment] 2021-06-15 05:03
> When the tuple is distributed by hash, we need to make true that the hash key is in the targetlist. So the function `add_to_flat_tlist_junk` can add hash key to the targetlist when it isn't in it. But the problem in the issue is that when the var length is different, we think they are different and add the hash key in the targetlist but they are already in the targetlist.

I do not think the root issue is as the above.

The problem is `create_append_plan`'s targetlist length is not the same as its `appendplans`.

And when the right above `Append` node is a motion, motion node invokes `append` to fetch tuple, and it sets tupleDesc based on the `Append`, how every the real tuple is from Append's appendplans, whose tupleDesc is no the same.

I have two advice:
1. add some assert on motion's execution code to see if such pattern happan in other cases (run the pipeline)
2. add some assert on `create_append_plan` to see if other case of append fit this pattern

We might go through each `add_to_flat_tlist_junk` invocation to see if such bad pattern happens.

**Comment by JunfengYang** [comment] 2021-07-08 00:20
As I check the code, most of the calls of `add_to_flat_tlist_junk ` seem not necessary, since if there are no sub plans in the hashExpr, it means all the elements must come from the target list, then there's no need to check the target list again and add it back from hashExpr to the target list.
I'll adjust the tests and open a PR today.

**Comment by JunfengYang** [comment] 2021-07-14 02:20
Merged into 6X_STABLE, so close this issue.

**Closed by JunfengYang** 2021-07-14 02:20 UTC
Labels: version: 6X_STABLE
