### ISSUE TITLE
postgresql jdbc very simple query  slow than 2x, 3x query with psql

### ISSUE THREAD

**Issue by gj-zhang** [greenplum-db/gpdb#11381] opened 2021-01-20 01:43 UTC
### Greenplum version or build
 5.26.0
### OS version and uname -a
Linux  4.11.1-1.el7.elrepo.x86_64 #1 SMP Sun May 14 11:54:29 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
query very fast
### Actual behavior
2s-5s

I'm have an interesting issue with the PostgreSQL driver. In GreenPlum 5.26.0, I have a very simple SELECT query which select sum(col) from table. The table only has 56 rows. When I run this query with psql, it returns in 50ms. When I run it through my Java code, it take 2s-5s.
```java
public static void main(String[] args) {
    try {
        Class.forName("org.postgresql.Driver");
    } catch (ClassNotFoundException e) {
        e.printStackTrace();
    }
    long start = System.currentTimeMillis();
    System.out.println("startTime: " + start);
    try (Connection connection = DriverManager.getConnection("jdbc:postgresql://host:port/db?loggerLevel=TRACE", "user", "password");
         PreparedStatement preparedStatement = connection.prepareStatement("select sum(num) as num from schema.table;");
         ResultSet resultSet = preparedStatement.executeQuery();) {
        while (resultSet.next()) {
            int res = resultSet.getInt(1);
            System.out.println("res: " + res);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    System.out.println("Time: " + (System.currentTimeMillis() - start));
}
```
I tried PostgreSQL JDBC 9.4-1205-jdbc41 and 42.2.16. The two versions both have the same problem, but with GreenPlum 6.8, I have no problem.

I have run arthas on my code during this exception, the PostgreSQL driver method org.postgresql.core.VisibleBufferedInputStream#readMore is taking essentially all of the time.

It's been driving me crazy for days and would appreciate any insight.

**Comment by gj-zhang** [comment] 2021-01-20 11:54
today , i change the autoCommit to false. it query fast. but i don't understand. please help.

**Comment by kainwen** [comment] 2021-01-20 13:59
> today , i change the autoCommit to false. it query fast. but i don't understand. please help.

You can compare the following two cases' speed:

1. using psql :
```sql
begin;
select .xxxxx -- your query here
end;
```

2. your jdbc code with `autoCommit = True` (the case with your report issue)

Paste the time here to further analyze.

**Comment by gj-zhang** [comment] 2021-01-21 00:24
> > today , i change the autoCommit to false. it query fast. but i don't understand. please help.
> 
> You can compare the following two cases' speed:
> 
> 1. using psql  to test the following 3 lines' running time (in a whole):
> 
> ```sql
> begin;
> select .xxxxx -- your query here
> end;
> ```
> 
> 1. your jdbc code with `autoCommit = True` (the case with your report issue)
> 
> Paste the time here to further analyze.

yes. using psql test is slow like jdbc code
```shell
begin;select sum(num) as num from datagovernance.app_system_datagovernment_norm_1d;commit;
```

so, why?

**Comment by zhangh43** [comment] 2021-01-21 05:31
> yes. using psql test is slow like jdbc code
> 
> ```shell
> begin;select sum(num) as num from datagovernance.app_system_datagovernment_norm_1d;commit;
> ```
> 
> so, why?

Could you supply how to reproduce your psql test? I tested in my environment, it's fast.

```sql
create table a(i int);
insert into a select generate_series(1,100);
```

a.sql
```sql
\timing
begin;
select sum(i) from a;
end;
```

```
$ psql postgres -f a.sql
Timing is on.
BEGIN
Time: 0.784 ms
 sum
------
 5050
(1 row)

Time: 64.455 ms
COMMIT
Time: 0.472 ms
```

**Comment by gj-zhang** [comment] 2021-01-21 05:37
> > yes. using psql test is slow like jdbc code
> > ```shell
> > begin;select sum(num) as num from datagovernance.app_system_datagovernment_norm_1d;commit;
> > ```
> > 
> > 
> > so, why?
> 
> Could you supply how to reproduce your psql test? I tested in my environment, it's fast.
> 
> ```sql
> create table a(i int);
> insert into a select generate_series(1,100);
> ```
> 
> a.sql
> 
> ```sql
> \timing
> begin;
> select sum(i) from a;
> end;
> ```
> 
> ```
> $ psql postgres -f a.sql
> Timing is on.
> BEGIN
> Time: 0.784 ms
>  sum
> ------
>  5050
> (1 row)
> 
> Time: 64.455 ms
> COMMIT
> Time: 0.472 ms
> ```

sorry i can't. 
i have two clusters, one with version 5.26 and the other with version 6.8. only 5.26 have the problem. 

and i'am newer to gp. I don't know which way to look at this problem, can you help me to point some directions?

and I read some articles about pg_stat_statement, pg_test_sync, transaction snapshot... However, it seems that none of these tools will be available in 5.26.

**Comment by gj-zhang** [comment] 2021-01-21 05:47
And i run psql with \timing 
```shell
dcw=# \timing
Timing is on.
dcw=# begin;select sum(num) as num from datagovernance.app_system_datagovernment_norm_1d;commit;
BEGIN
Time: 58.001 ms
  num   
--------
 323866
(1 row)

Time: 27.760 ms
COMMIT
Time: 3554.685 ms
```

**Comment by gj-zhang** [comment] 2021-01-21 10:47
And i run pg_test_fsync
```shell
5 seconds per test
O_DIRECT supported on this platform for open_datasync and open_sync.

Compare file sync methods using one 8kB write:
(in wal_sync_method preference order, except fdatasync
is Linux's default)
        open_datasync                   35915.892 ops/sec      28 usecs/op
        fdatasync                       29260.122 ops/sec      34 usecs/op
        fsync                           29845.096 ops/sec      34 usecs/op
        fsync_writethrough                            n/a
        open_sync                       33848.051 ops/sec      30 usecs/op

Compare file sync methods using two 8kB writes:
(in wal_sync_method preference order, except fdatasync
is Linux's default)
        open_datasync                   18039.438 ops/sec      55 usecs/op
        fdatasync                       29315.960 ops/sec      34 usecs/op
        fsync                           27148.788 ops/sec      37 usecs/op
        fsync_writethrough                            n/a
        open_sync                       16646.840 ops/sec      60 usecs/op

Compare open_sync with different write sizes:
(This is designed to compare the cost of writing 16kB
in different write open_sync sizes.)
         1 * 16kB open_sync write       31331.712 ops/sec      32 usecs/op
         2 *  8kB open_sync writes      16620.264 ops/sec      60 usecs/op
         4 *  4kB open_sync writes       8676.007 ops/sec     115 usecs/op
         8 *  2kB open_sync writes       4315.704 ops/sec     232 usecs/op
        16 *  1kB open_sync writes       2175.741 ops/sec     460 usecs/op

Test if fsync on non-write file descriptor is honored:
(If the times are similar, fsync() can sync data written
on a different descriptor.)
        write, fsync, close             27392.879 ops/sec      37 usecs/op
        write, close, fsync             27528.213 ops/sec      36 usecs/op

Non-Sync'ed 8kB writes:
        write                           469187.062 ops/sec       2 usecs/op
```

**Comment by lij55** [comment] 2022-02-15 01:19
closing the old GP5 only performance issue because it is fixed on GP6.

**Closed by lij55** 2022-02-15 01:19 UTC
