### ISSUE TITLE
Executable external table should be able to stop the external program in time after it get enough rows for the query.

### ISSUE THREAD

**Issue by lij55** [greenplum-db/gpdb#17023] opened 2024-01-24 02:53 UTC
Currently the 'executable external web table' need to run and wait the program finish even if there is a limit in query.
for example, 

```sql
test=# CREATE EXTERNAL web TABLE huge_data
(
    data text
)
EXECUTE E'for i in `seq 1 100000000`;do  echo "hello greenplum";done' ON MASTER
FORMAT 'CSV';
CREATE EXTERNAL TABLE
test=# select * from huge_data limit 3;

```

I tested in on GP6 but think both GP6 and GP7 are the same. this limitation will make any query on `gp_toolkit.__gp_log_master_ext` extremely slow if the pg_log directory is big.

**Comment by jingwen-yang-yjw** [comment] 2024-02-06 09:01
Hi @lij55, I think this issue is caused by execute command ```for i in `seq 1 100000000`;do  echo "hello greenplum";done```.
While debugging, we found that GP will wait lots of time to read the first tuple from the child process executing this command.
The child process does NOT return data in time.

Using execute command ```for (i=0;i<100000000;++i) do echo "hello greenplum" ;done``` instead, GP6 and GP7 work well.

**Comment by zhaorui20005** [comment] 2024-02-06 09:24
> Hi @lij55, I think this issue is caused by execute command `` for i in `seq 1 100000000`;do echo "hello greenplum";done ``. While debugging, we found that GP will wait lots of time to read the first tuple from the child process executing this command. The child process does NOT return data in time.
> 
> Using execute command `for (i=0;i<100000000;++i) do echo "hello greenplum" ;done` instead, GP6 and GP7 work well.

Agreed. I think most of the time and memories are taken by the sub-command `seq 1 100000000`. After this sub-command finishes, the first one tuple is about to be pushed into stdout buffer, that's why limit squelched does not work.

**Comment by zhaorui20005** [comment] 2024-03-08 08:22
Since no more update and the issue is caused by shell script, so close this issue now.

**Closed by zhaorui20005** 2024-03-08 08:22 UTC
Labels: type: feature
