### ISSUE TITLE
using orca parallel update result in wrong results

### ISSUE THREAD

**Issue by tianshisiyi** [greenplum-db/gpdb#6024] opened 2018-10-17 06:45 UTC
```
CREATE TABLE hello (
    id integer,
    name text
) DISTRIBUTED BY (id);

insert into hello select generate_series(1,100),'good';
gpsrc=# select count(*) from hello;
 count
-------
   100
(1 row)

Time: 9.617 ms
```

```
--enble orca
cat update.sql
\set id random(1,100)
set optimizer=on;
update hello set name='bad' where id=:id;
```

```
[gpsrc@gpmaster pgbench]$ pgbench -c 10 -n -T 10 -r  -f update.sql
transaction type: update.sql
scaling factor: 1
query mode: simple
number of clients: 10
number of threads: 1
duration: 10 s
number of transactions actually processed: 4547
latency average = 22.033 ms
tps = 453.869075 (including connections establishing)
tps = 454.217923 (excluding connections establishing)
statement latencies in milliseconds:
         0.004  \set id random(1,100)
         1.257  set optimizer=on;
        20.582  update hello set name='bad' where id=:id;

gpsrc=# select count(*) from hello;
 count
-------
   559
(1 row)

Time: 48.942 ms

--disable orca
[gpsrc@gpmaster pgbench]$ cat update.sql
\set id random(1,100)
set optimizer=off;
update hello set name='bad' where id=:id;

[gpsrc@gpmaster pgbench]$ pgbench -c 10 -n -T 10 -r  -f update.sql
transaction type: update.sql
scaling factor: 1
query mode: simple
number of clients: 10
number of threads: 1
duration: 10 s
number of transactions actually processed: 19042
latency average = 5.257 ms
tps = 1902.084351 (including connections establishing)
tps = 1903.593388 (excluding connections establishing)
statement latencies in milliseconds:
         0.002  \set id random(1,100)
         0.503  set optimizer=off;
         4.706  update hello set name='bad' where id=:id;

gpsrc=# select count(*) from hello;
 count
-------
   100
(1 row)

Time: 49.849 ms
```

**Comment by vraghavan78** [comment] 2018-10-17 21:54
This is a duplicate of https://github.com/greenplum-db/gpdb/issues/5930

**Comment by vraghavan78** [comment] 2018-10-24 04:02
Looks like it is not a duplicate of #5930

**Comment by lij55** [comment] 2022-02-11 07:58
```
gpadmin@24bebb782c98:~/github$ pgbench -c 10 -n -T 10 -r  -f update.sql
transaction type: update.sql
scaling factor: 1
query mode: simple
number of clients: 10
number of threads: 1
duration: 10 s
number of transactions actually processed: 5212
latency average = 19.240 ms
tps = 519.755828 (including connections establishing)
tps = 520.110856 (excluding connections establishing)
statement latencies in milliseconds:
         0.001  \set id random(1,100)
         0.336  set optimizer=on;
        18.745  update hello set name='bad' where id=:id;
gpadmin@24bebb782c98:~/github$ psql
psql (12beta2)
Type "help" for help.

test=# select count(*) from hello;
 count
-------
   100
(1 row)

test=# show optimizer;
 optimizer
-----------
 on
(1 row)
```

It looks like no longer existing on master. close it.

**Closed by lij55** 2022-02-11 07:58 UTC
Labels: area: gporca
