### ISSUE TITLE
[6X]: FailedAssertion(""!(pg_verifymbstr(*str, len, ((bool) 1)))

### ISSUE THREAD

**Issue by gfphoenix78** [greenplum-db/gpdb#12381] opened 2021-07-23 01:16 UTC
### Greenplum version or build
6X_STABLE

### Expected behavior
No fatal error
### Actual behavior
FailedAssertion
### Step to reproduce the behavior

```
2021-07-23 01:36:12.498070 UTC,"gpadmin","database10",p3680299,th113449088,"127.0.0.1","37690",2021-07-23 01:36:09 UTC,0,con783,cmd198,seg-1,,,,sx1,"FATAL","XX000","Unexpected internal error (elog.c:259)","FailedAssertion(""!(pg_verifymbstr(*str, len, ((bool) 1)))"", File: ""elog.c"", Line: 259)","Process 3680299 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.",,,,"SELECT t1.c0 FROM ONLY t1 FULL OUTER JOIN t3 ON ((((((('溋3ZP*')||(B'1111111111111111111111111111111110011111010010110000011110110001')) COLLATE ""C""))||((((('[264465353,2085865820]'::int4range)*('(-1252009430,18251032]'::int4range)))*((('[466070338,796255941)'::int4range)*('[1152508515,1819014488]'::int4range)))))))LIKE(upper(upper('0.0')))) LEFT OUTER JOIN (SELECT CAST(0.70555514 AS MONEY), 0.01146046388323773701500840616063214838504791259765625 FROM t1, ONLY t3 WHERE ((t3.c1)=(0.09411125))) AS sub0 ON NULL",56,,"elog.c",259,"Stack trace:
1    0xb6f3fb postgres errstart (elog.c:557)
2    0xb64fb2 postgres ExceptionalCondition (assert.c:37)
3    0xb6610f postgres <symbol not found> (elog.c:263)
4    0xb6fac3 postgres errmsg (discriminator 10)
5    0xb29723 postgres varbit_in (discriminator 1)
6    0xb760c8 postgres InputFunctionCall (fmgr.c:1930)
7    0xb76306 postgres OidInputFunctionCall (fmgr.c:2062)
8    0x81eece postgres stringTypeDatum (parse_type.c:687)
9    0x80a87d postgres coerce_type (parse_coerce.c:337)
10   0x8130b1 postgres make_fn_arguments (parse_func.c:1787)
11   0x816842 postgres make_op (parse_oper.c:829)
12   0x81058f postgres <symbol not found> (parse_expr.c:1005)
13   0x80fa98 postgres <symbol not found> (parse_expr.c:233)
14   0x810456 postgres <symbol not found> (parse_expr.c:2490)
15   0x80fa70 postgres <symbol not found> (parse_expr.c:223)
16   0x81056b postgres <symbol not found> (parse_expr.c:994)
17   0x80fa98 postgres <symbol not found> (parse_expr.c:233)
18   0x81056b postgres <symbol not found> (parse_expr.c:994)
19   0x80fa98 postgres <symbol not found> (parse_expr.c:233)
20   0x80f7b9 postgres transformExpr (discriminator 4)
21   0x805b99 postgres transformWhereClause (parse_clause.c:1653)
22   0x805bf6 postgres <symbol not found> (parse_clause.c:674)
23   0x80660b postgres <symbol not found> (parse_clause.c:1368)
24   0x805c82 postgres <symbol not found> (parse_clause.c:1159)
25   0x80683f postgres transformFromClause (discriminator 3)
26   0x7e645f postgres <symbol not found> (discriminator 5)
27   0x7e6f1b postgres transformStmt (analyze.c:307)
28   0x7e75aa postgres transformTopLevelStmt (analyze.c:272)
29   0x7e76ab postgres parse_analyze_varparams (discriminator 4)
30   0xa65552 postgres <symbol not found> (postgres.c:2077)
"
```

**Comment by huansong** [comment] 2021-12-09 04:53
Looked at this issue w/ @soumyadeep2007 .
Repro could be as simple as: 
```
select '溋' || (B'1');
```
PG behavior for the same scenarios is:
```
postgres=# select '溋' || (B'1');
ERROR:  "溋" is not a valid binary digit
LINE 1: select '溋' || (B'1');
               ^
Time: 0.396 ms
```
Not yet understanding the exact root cause, but seems that GP added a check `verify_and_replace_mbstr()` in `errmsg()` which checks if the error message is encoded correctly in the current DB's encoding (utf8 by default). And for some reason the character like '溋' is rendered as `\346` in the error message `"\"\346\" is not a valid binary digit`, and when we verify this message using `pg_utf8_islegal`, it's regarded as illegal and eventually caused the assertion error.

**Comment by huansong** [comment] 2021-12-10 05:23
The issue seems to be that, when `varbit_in()` found some invalid bit, it incorrectly assumes that it is single-byte and use the character format to print it: https://github.com/greenplum-db/gpdb/blob/master/src/backend/utils/adt/varbit.c#L515
So when the input is a multi-byte string, only the first byte is passed in to `errmsg` and hence `pg_utf8_islegal`regards it illegal.
PG doesn't have this issue because it's fixed in a preventive commit: https://github.com/postgres/postgres/commit/16e3ad5d143

**Comment by soumyadeep2007** [comment] 2021-12-15 22:09
Fixed in master branch with https://github.com/greenplum-db/gpdb/pull/12934
Cannot backport the above PR as the upstream backport included in the PR is not applicable to 6X and 5X.

**Closed by soumyadeep2007** 2021-12-15 22:09 UTC
Labels: version: 6X_STABLE, sqlancer, Priority 1
