### ISSUE TITLE
Planner failure for uncorrelated IN query with partitioned tables.

### ISSUE THREAD

**Issue by vraghavan78** [greenplum-db/gpdb#2689] opened 2017-06-23 21:23 UTC
```sql
create table p (a int, b int, c int) partition by range (c) (start(1) end(5) every(1), default partition extra);
create table q (a int, b int, c int) partition by range (c) (start(1) end(5) every(1), default partition extra);
explain update p set c = c + 1 where b in (select b from q where q.c = 0) and c = 0;
```

Planner:

```
vraghavan=# explain update p set c = c + 1 where b in (select b from q where q.c = 0) and c = 0;
ERROR:  Unexpected internal error (planmain.c:275)
```

GPORCA:

```
vraghavan=# explain update p set c = c + 1 where b in (select b from q where q.c = 0) and c = 0;
                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------
 Update  (cost=0.00..862.08 rows=1 width=1)
   ->  Partition Selector for p  (cost=0.00..862.00 rows=1 width=30)
         ->  Split  (cost=0.00..862.00 rows=1 width=26)
               ->  Result  (cost=0.00..862.00 rows=1 width=26)
                     ->  Hash EXISTS Join  (cost=0.00..862.00 rows=1 width=22)
                           Hash Cond: public.p.b = q.b
                           ->  Sequence  (cost=0.00..431.00 rows=1 width=22)
                                 ->  Partition Selector for p (dynamic scan id: 1)  (cost=10.00..100.00 rows=34 width=4)
                                       Filter: public.p.c = 0
                                       Partitions selected: 1 (out of 5)
                                 ->  Dynamic Table Scan on p (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=22)
                                       Filter: c = 0
                           ->  Hash  (cost=431.00..431.00 rows=1 width=4)
                                 ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=4)
                                       ->  Result  (cost=0.00..431.00 rows=1 width=4)
                                             ->  Sequence  (cost=0.00..431.00 rows=1 width=8)
                                                   ->  Partition Selector for q (dynamic scan id: 2)  (cost=10.00..100.00 rows=34 width=4)
                                                         Filter: q.c = 0
                                                         Partitions selected: 1 (out of 5)
                                                   ->  Dynamic Table Scan on q (dynamic scan id: 2)  (cost=0.00..431.00 rows=1 width=8)
                                                         Filter: c = 0
 Optimizer status: PQO version 2.34.0
(22 rows)
```

**Comment by hlinnaka** [comment] 2018-08-14 09:54
Works now:
```
postgres=# explain update p set c = c + 1 where b in (select b from q where q.c = 0) and c = 0;
                                                QUERY PLAN                                                 
-----------------------------------------------------------------------------------------------------------
 Update (slice0; segments: 3)  (rows=3 width=28)
   ->  Explicit Redistribute Motion 3:3  (slice2; segments: 3)  (cost=2152.30..2152.37 rows=3 width=28)
         ->  HashAggregate  (cost=2152.30..2152.37 rows=3 width=28)
               Group By: public.p.ctid::bigint
               ->  Hash Join  (cost=1074.72..2152.28 rows=3 width=28)
                     Hash Cond: public.q.b = public.p.b
                     ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..1076.87 rows=78 width=4)
                           ->  Append  (cost=0.00..1073.75 rows=26 width=4)
                                 ->  Seq Scan on q_1_prt_extra q  (cost=0.00..1073.75 rows=26 width=4)
                                       Filter: c = 0
                     ->  Hash  (cost=1073.75..1073.75 rows=26 width=22)
                           ->  Seq Scan on p_1_prt_extra p  (cost=0.00..1073.75 rows=26 width=22)
                                 Filter: c = 0
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
(15 rows)
```

I believe this was a duplicate of issue https://github.com/greenplum-db/gpdb/issues/1104. Closing.

**Closed by hlinnaka** 2018-08-14 09:54 UTC
Labels: Planner
