### ISSUE TITLE
An ORCA bug related with CTE.

### ISSUE THREAD

**Issue by xlxie** [greenplum-db/gpdb#11818] opened 2021-04-15 05:18 UTC
### Greenplum version or build
Tag 6.15.0

### OS version and uname -a
select version(): PostgreSQL 9.4.24 (Greenplum Database 6.15.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit compiled on Apr 15 2021 12:46:42
uname -a: Linux h68c05462.sqa.eu95 3.10.0-327.ali2010.alios7.x86_64 #1 SMP Mon Mar 20 19:58:02 CST 2017 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./configure --enable-orca --with-perl --with-python --with-libxml

### Installation information ( pg_config )
One master + 3 segments on one single machine. Actually it's the regression environment.

### Expected behavior
A CTE scan + two hash joins, with multiple gather/redistribution nodes.

### Actual behavior
The ORCA failed to generate correct redistribution nodes.

### Step to reproduce the behavior
Tabla create:
create table test_rcte_random(a int, b int, c int) distributed randomly;
insert into test_rcte_random select i, i%2, i%3 from generate_series(1, 40)i;

SQL: with x as (select * from test_rcte_random where a < 10) select * from x x1, x x2, x x3 where x2.a = x1.b and x3.b =x2.b;

Description:
For the above SQL, the ORCA generates a right plan by default, and the SQL outputs 25 rows results. However, if I run "set optimizer_segments = 6;", the ORCA will generate a wrong plan and the SQL outputs 1 rows results.

After compare plan, I find that the ORCA didn't generate right redistribution nodes when optimizer_segments = 6. The right plan includes 3 redistribution nodes OR 1 gather motion. The wrong plan has only one redistribution nodes.

I found this bug on my older build (GP 6.3), and reproduced it in the most recent release (GP 6.15.0).

What I know is, this bug is related with "optimizer_push_requirements_from_consumer_to_producer". This GUC is on by default and when I turn it off, the generated plan is right.

This bug has been reproduced in other tests that are related with CTE. And the above SQL is the easiest way to reproduced.

**Comment by kainwen** [comment] 2021-04-15 06:38
Master branch does not have this issue. cc @d @l-wang 

For 6X, reproduced as below. The new plan after setting `optimizer_segments` miss two redistribute motion for the final hash join.

```
gpadmin=# create table test_rcte_random(a int, b int, c int) distributed randomly;
CREATE TABLE
gpadmin=# insert into test_rcte_random select i, i%2, i%3 from generate_series(1, 40)i;
INSERT 0 40
gpadmin=# explain with x as (select * from test_rcte_random where a < 10) select * from x x1, x x2, x x3 where x2.a = x1.b and x3.b =x2.b;
                                                       QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice4; segments: 3)  (cost=0.00..1724.02 rows=43 width=36)
   ->  Sequence  (cost=0.00..1724.01 rows=15 width=36)
         ->  Shared Scan (share slice:id 4:0)  (cost=0.00..431.00 rows=4 width=1)
               ->  Materialize  (cost=0.00..431.00 rows=4 width=1)
                     ->  Redistribute Motion 3:3  (slice3; segments: 3)  (cost=0.00..431.00 rows=4 width=12)
                           Hash Key: test_rcte_random.b
                           ->  Seq Scan on test_rcte_random  (cost=0.00..431.00 rows=4 width=12)
                                 Filter: (a < 10)
         ->  Hash Join  (cost=0.00..1293.01 rows=15 width=36)
               Hash Cond: (share0_ref3.b = share0_ref2.b)
               ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=0.00..862.00 rows=4 width=24)
                     Hash Key: share0_ref3.b
                     ->  Hash Join  (cost=0.00..862.00 rows=4 width=24)
                           Hash Cond: (share0_ref4.b = share0_ref3.a)
                           ->  Result  (cost=0.00..431.00 rows=4 width=12)
                                 Filter: (share0_ref4.b < 10)
                                 ->  Shared Scan (share slice:id 2:0)  (cost=0.00..431.00 rows=4 width=12)
                           ->  Hash  (cost=431.00..431.00 rows=4 width=12)
                                 ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.00 rows=4 width=12)
                                       Hash Key: share0_ref3.a
                                       ->  Result  (cost=0.00..431.00 rows=4 width=12)
                                             Filter: (share0_ref3.a < 10)
                                             ->  Shared Scan (share slice:id 1:0)  (cost=0.00..431.00 rows=4 width=12)
               ->  Hash  (cost=431.00..431.00 rows=4 width=12)
                     ->  Shared Scan (share slice:id 4:0)  (cost=0.00..431.00 rows=4 width=12)
 Optimizer: Pivotal Optimizer (GPORCA)
(26 rows)

gpadmin=#  with x as (select * from test_rcte_random where a < 10) select * from x x1, x x2, x x3 where x2.a = x1.b and x3.b =x2.b;
 a | b | c | a | b | c | a | b | c
---+---+---+---+---+---+---+---+---
 7 | 1 | 1 | 1 | 1 | 1 | 5 | 1 | 2
 7 | 1 | 1 | 1 | 1 | 1 | 3 | 1 | 0
 7 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
 7 | 1 | 1 | 1 | 1 | 1 | 9 | 1 | 0
 7 | 1 | 1 | 1 | 1 | 1 | 7 | 1 | 1
 9 | 1 | 0 | 1 | 1 | 1 | 5 | 1 | 2
 9 | 1 | 0 | 1 | 1 | 1 | 3 | 1 | 0
 9 | 1 | 0 | 1 | 1 | 1 | 1 | 1 | 1
 9 | 1 | 0 | 1 | 1 | 1 | 9 | 1 | 0
 9 | 1 | 0 | 1 | 1 | 1 | 7 | 1 | 1
 1 | 1 | 1 | 1 | 1 | 1 | 5 | 1 | 2
 1 | 1 | 1 | 1 | 1 | 1 | 3 | 1 | 0
 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
 1 | 1 | 1 | 1 | 1 | 1 | 9 | 1 | 0
 1 | 1 | 1 | 1 | 1 | 1 | 7 | 1 | 1
 3 | 1 | 0 | 1 | 1 | 1 | 5 | 1 | 2
 3 | 1 | 0 | 1 | 1 | 1 | 3 | 1 | 0
 3 | 1 | 0 | 1 | 1 | 1 | 1 | 1 | 1
 3 | 1 | 0 | 1 | 1 | 1 | 9 | 1 | 0
 3 | 1 | 0 | 1 | 1 | 1 | 7 | 1 | 1
 5 | 1 | 2 | 1 | 1 | 1 | 5 | 1 | 2
 5 | 1 | 2 | 1 | 1 | 1 | 3 | 1 | 0
 5 | 1 | 2 | 1 | 1 | 1 | 1 | 1 | 1
 5 | 1 | 2 | 1 | 1 | 1 | 9 | 1 | 0
 5 | 1 | 2 | 1 | 1 | 1 | 7 | 1 | 1
(25 rows)

gpadmin=# set optimizer_segments = 6;
SET
gpadmin=# explain with x as (select * from test_rcte_random where a < 10) select * from x x1, x x2, x x3 where x2.a = x1.b and x3.b =x2.b;
                                                 QUERY PLAN
-------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..1724.01 rows=43 width=36)
   ->  Sequence  (cost=0.00..1724.00 rows=15 width=36)
         ->  Shared Scan (share slice:id 2:0)  (cost=0.00..431.00 rows=4 width=1)
               ->  Materialize  (cost=0.00..431.00 rows=4 width=1)
                     ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.00 rows=4 width=12)
                           Hash Key: test_rcte_random.a
                           ->  Seq Scan on test_rcte_random  (cost=0.00..431.00 rows=4 width=12)
                                 Filter: (a < 10)
         ->  Hash Join  (cost=0.00..1293.00 rows=15 width=36)
               Hash Cond: (share0_ref4.b = share0_ref2.b)
               ->  Hash Join  (cost=0.00..862.00 rows=4 width=24)
                     Hash Cond: (share0_ref4.a = share0_ref3.b)
                     ->  Result  (cost=0.00..431.00 rows=4 width=12)
                           Filter: (share0_ref4.a < 10)
                           ->  Shared Scan (share slice:id 2:0)  (cost=0.00..431.00 rows=4 width=12)
                     ->  Hash  (cost=431.00..431.00 rows=4 width=12)
                           ->  Result  (cost=0.00..431.00 rows=4 width=12)
                                 Filter: (share0_ref3.b < 10)
                                 ->  Shared Scan (share slice:id 2:0)  (cost=0.00..431.00 rows=4 width=12)
               ->  Hash  (cost=431.00..431.00 rows=4 width=12)
                     ->  Shared Scan (share slice:id 2:0)  (cost=0.00..431.00 rows=4 width=12)
 Optimizer: Pivotal Optimizer (GPORCA)
(22 rows)

gpadmin=#  with x as (select * from test_rcte_random where a < 10) select * from x x1, x x2, x x3 where x2.a = x1.b and x3.b =x2.b;
 a | b | c | a | b | c | a | b | c
---+---+---+---+---+---+---+---+---
 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1
(1 row)

```

**Comment by zellerh** [comment] 2021-05-03 19:32
@xlxie, thank you very much for reporting this problem! Thanks for providing an example and for already pointing out the area where the problem is, related to guc `optimizer_push_requirements_from_consumer_to_producer`. I'm able to reproduce the issue and agree with your observation where the problem is. It seems to be caused by equivalent distribution specs where the equivalent columns come from different CTE consumers. Am working on a PR with a fix.

It's a bit tricky to come up with a query that actually uses the incorrect plan. So, we probably have the same bug on master, even though the provided example doesn't produce a wrong answer on master.

**Comment by zellerh** [comment] 2021-05-03 21:44
This fixes https://github.com/greenplum-db/gpdb/issues/11818.

**Comment by zellerh** [comment] 2021-05-03 21:45
The PR is https://github.com/greenplum-db/gpdb/pull/11904.

**Comment by xlxie** [comment] 2021-05-05 06:23
Thanks, zellerh! I am very happy to see the bug fixed. It helps a lot for me to better understand the algorithm of ORCA!

**Comment by vraghavan78** [comment] 2022-12-21 20:16
PR merged

**Closed** 2022-12-21 20:16 UTC
Labels: area: gporca, version: 6X_STABLE
