### ISSUE TITLE
Owner of the table can't perform VACUUM because of lack of permissions on pg_aoseg schema

### ISSUE THREAD

**Issue by kapustor** [greenplum-db/gpdb#9001] opened 2019-11-06 20:58 UTC
### Greenplum version or build
6.1
### OS version and uname -a
NA
### autoconf options used ( config.status --config )
NA
### Installation information ( pg_config )
NA
### Expected behavior
Owner of the table can vacuum the table:
```
adb=# create table ttt1( id int) with (appendonly=true, orientation=column);
...
CREATE TABLE
adb=# alter table ttt1 owner ttt;
[gpadmin@mdw ~]$ psql -d adb -U ttt
psql (9.4.24)
Type "help" for help.

adb=> vacuum ttt1;
VACUUM
```
### Actual behavior
```
[gpadmin@mdw ~]$ psql -d adb -U ttt
psql (9.4.24)
Type "help" for help.

adb=> vacuum ttt1;
ERROR:  permission denied for schema pg_aoseg  (seg88 192.168.100.16:10016 pid=70446)
```
For heap table works ok.
### Step to reproduce the behavior
See above.

**Comment by soumyadeep2007** [comment] 2019-11-06 22:45
With @d :
Doesn't repro on 5x. This is a regression. Heap tables with a text column (that has a toast table) have the same problem with :
```
ERROR:  permission denied for schema pg_toast  ...
```

**Comment by d** [comment] 2019-11-07 01:12
An aoseg table is similarly handled like a toast table: when we transfer ownership of a table, we transfer the ownership of all "auxiliary" objects at the same time. I verified with @soumyadeep2007 and this seems to be a regression on Greenplum 7 and 6

Jesse

**Comment by soumyadeep2007** [comment] 2019-11-08 20:01
Consider the following for a heap table scenario with the database:
Repro:
```
psql postgres
create role jz;
create table heap(i int, j text);
alter table heap owner to jz;
set role to jz;
vacuum heap;
ERROR:  permission denied for schema pg_toast
```

RCA :
In GP5x, PG9_6_STABLE and GP6x+, we would do a **namespace** access check the for `heap` table for the user `jz`. However, for GP6x+ we would do an additional **namespace** access check for the `pg_toast_<reltoastoid>` table for the user `jz` and fail flagging insufficient privileges. Effectively the call (with values substitued): `LookupExplicitNamespace("pg_toast", false)` will fail with `ACLCHECK_NO_PRIV`.

The reason why GP6x+ has this additional step is that it does a separate dispatch for vacuuming the  `pg_toast_<reltoastoid>` table, which results in the call stack on the segment manifesting in the `ERROR:  permission denied for schema pg_toast` (GP-master commit: 38d8815552):
```
LookupExplicitNamespace namespace.c:2789
RangeVarGetRelidExtended namespace.c:330
get_rel_oids vacuum.c:1137
vacuum vacuum.c:337
ExecVacuum vacuum.c:204
standard_ProcessUtility utility.c:804
ProcessUtility utility.c:399
PortalRunUtility pquery.c:1403
PortalRunMulti pquery.c:1552
PortalRun pquery.c:1018
exec_mpp_query postgres.c:1328
```
If we contrast this to GP5x: There we have only 1 dispatch of vacuum for the relation 'heap' and the QE vacuums the associated `pg_toast_<reltoastoid>` tables as part of that one dispatch.

Forcing the above additional check (`LookupExplicitNamespace("pg_toast", false))` on GP5x and PG9_6_STABLE also results in the same failure. This indicates that `pg_toast_<reltoastoid>` relations should NOT undergo this check. Generalizing to include AO and AOCS tables, any such auxiliary relations like `pg_aoseg_<>` or `pg_aocsseg_<>` should NOT undergo this check.

**Comment by gaos1** [comment] 2020-01-09 08:35
fixed by https://github.com/greenplum-db/gpdb/pull/9304

**Closed by gaos1** 2020-01-09 08:35 UTC
