### ISSUE TITLE
Duplicate entries in pg_depend

### ISSUE THREAD

**Issue by jmcatamney** [greenplum-db/gpdb#10698] opened 2020-08-24 17:51 UTC
### Greenplum version or build

Master and 6X_STABLE

### Expected behavior

pg_depend should have no duplicate entries, and if duplicates do occur, gpcheckcat should identify them.

### Actual behavior

pg_depend has duplicates in both 6X:

```
postgres=# select * from pg_depend where objid=11692;
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype 
---------+-------+----------+------------+----------+-------------+---------
    2618 | 11692 |        0 |       1259 |    11689 |           0 | a
    2618 | 11692 |        0 |       1259 |    11689 |           1 | n
    2618 | 11692 |        0 |       1259 |    11689 |           2 | n
    2618 | 11692 |        0 |       1259 |    11689 |           1 | n
```
...and master:

```
postgres=# select * from pg_depend where objid=11894;
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype 
---------+-------+----------+------------+----------+-------------+---------
    2618 | 11894 |        0 |       1259 |    11891 |           0 | a
    2618 | 11894 |        0 |       1259 |    11891 |           1 | n
    2618 | 11894 |        0 |       1259 |    11891 |           2 | n
    2618 | 11894 |        0 |       1259 |    11891 |           1 | n
```
Note the second and fourth lines in each case.

This issue was identified when, during the process of converting the utilities from Python 2 to Python 3, the updated version of gpcheckcat correctly identified the duplicate issue:

```
SUMMARY REPORT: FAILED
      ===================================================================
      Completed 15 test(s) on database 'template1' at 2020-08-19 03:40:58 with elapsed time 0:00:09
      Found a total of 1 issue(s)
      
      ----------------------------------------------------
      Relation oid: 11894
      Relation schema: N/A
      Relation name: N/A
      
          Name of test which found this issue: duplicate_pg_depend
             Found 2 pg_depend entries of {'classid': 2618, 'objid': 11894, 'objsubid': 0, 'refclassid': 1259, 'refobjid': 11891, 'refobjsubid': 1, 'deptype': 'n', 'total': 2} on segment {-1,0,1}
```
However, the version of gpcheckcat currently in 6X and master does not catch the issue, and backporting the minor logic changes made in the Python 3 version doesn't change that, so the reason for the difference in behavior is currently unknown.

### Step to reproduce the behavior

The duplicate entries are present on a clean initialization of a 6X or master cluster.

**Comment by ashwinstar** [comment] 2020-08-25 22:27
Yet to find the cause but seems PostgreSQL 12 also has the same duplicate after initdb. So at least not something GPDB specific.
```
postgres=# select classid::regclass, refobjid::regclass,* from pg_depend where objid=12169 and deptype = 'n';
  classid   |  refobjid   | classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype 
------------+-------------+---------+-------+----------+------------+----------+-------------+---------
 pg_rewrite | pg_settings |    2618 | 12169 |        0 |       1259 |    12166 |           1 | n
 pg_rewrite | pg_settings |    2618 | 12169 |        0 |       1259 |    12166 |           2 | n
 pg_rewrite | pg_settings |    2618 | 12169 |        0 |       1259 |    12166 |           1 | n
(3 rows)
```

**Comment by ashwinstar** [comment] 2020-08-26 01:30
I don't know if this is issue or not (seems unnecessary wastage with duplicate entry though).
Also, don't yet what's causing it. But to help further investigation posting the simple repro
```
create table rtest_t5 (a int4, b text);
create table rtest_t7 (a int4, b text);

create rule rtest_t5_ins as on insert to rtest_t5
		where new.a > 15 do
	insert into rtest_t7 values (new.a, new.b);
```

```
# select classid::regclass, refobjid::regclass,* from pg_depend where refobjid='rtest_t5'::regclass and deptype = 'n';
  classid   | refobjid | classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype 
------------+----------+---------+-------+----------+------------+----------+-------------+---------
 pg_rewrite | rtest_t5 |    2618 | 24664 |        0 |       1259 |    24652 |           1 | n
 pg_rewrite | rtest_t5 |    2618 | 24664 |        0 |       1259 |    24652 |           1 | n
 pg_rewrite | rtest_t5 |    2618 | 24664 |        0 |       1259 |    24652 |           2 | n
(3 rows)
```

**Comment by ashwinstar** [comment] 2020-08-26 01:36
`InsertRule()` calling `recordDependencyOnExpr()` below way is causing duplicate entries to be entered

```C
    /*                                                                                                                                   
     * Also install dependencies on objects referenced in action and qual.                                                               
     */                                                                                                                                  
    recordDependencyOnExpr(&myself, (Node *) action, NIL,                                                                                
                           DEPENDENCY_NORMAL);                                                                                           
                                                                                                                                         
    if (event_qual != NULL)                                                                                                              
    {                                                                                                                                    
        /* Find query containing OLD/NEW rtable entries */                                                                               
        Query      *qry = (Query *) linitial(action);                                                                                    
                                                                                                                                         
        qry = getInsertSelectQuery(qry, NULL);                                                                                           
        recordDependencyOnExpr(&myself, event_qual, qry->rtable,                                                                         
                               DEPENDENCY_NORMAL);                                                                                       
    }                                                                                                                                    
```

**Comment by ashwinstar** [comment] 2020-08-26 01:45
@hlinnaka any quick ideas before I spend more time digging into this

**Comment by hlinnaka** [comment] 2020-08-26 07:27
PostgreSQL also creates the duplicate entries. I don't know why.

**Comment by ashwinstar** [comment] 2020-08-26 23:59
Tom answered [here](https://www.postgresql.org/message-id/2981628.1598478216%40sss.pgh.pa.us) with
```
Ashwin Agrawal <ashwinstar(at)gmail(dot)com> writes:
> If action and qual reference same object in CREATE RULE, it results in
> creating duplicate entries in pg_depend for it. Doesn't pose any harm, just
> unnecessarily bloats pg_depend.

Yeah, we generally don't try that hard to prevent duplicate pg_depend
entries.  It's relatively easy to get rid of them in limited contexts
like a single expression, but over a wider scope, I doubt it's worth
the trouble.

			regards, tom lane
```
So, closing this issue.
We should make sure `gpcheckcat` avoids duplicate entry checking for `pg_depend` as it can have duplicates.

**Closed by ashwinstar** 2020-08-26 23:59 UTC
Labels: area: management utilities, area: server
