### ISSUE TITLE
gpssh-exkeys utility ignore the AuthorizedKeysFile parameter of /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by jose-l-goncalves-alb** [greenplum-db/gpdb#17077] opened 2024-02-12 19:23 UTC
## Bug Report
We are deploying greenplum-db 7.1.0 in a cluster of VMs with AuthorizedKeysFile parameter configured at /etc/ssh/sshd_config:
`AuthorizedKeysFile      /etc/ssh/authorized_keys/%u`

_gpssh-exkeys_ ignores this configuration and assume, incorrectly, that authorized_keys file is ~/.ssh/authorized_keys instead of /etc/ssh/authorized_keys/gpadmin

### Greenplum version or build
7.1.0 (installed by rpm)

### OS version and uname -a
Red Hat Enterprise Linux release 8.6 (Ootpa)
Linux xxx 4.18.0-348.el8.x86_64 #1 SMP Wed Nov 10 11:25:16 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
NA
### Installation information ( pg_config )
NA

### Expected behavior
Assume authorized_keys file at /etc/ssh/authorized_keys/gpadmin

### Actual behavior
Assume authorized_keys file at ~/.ssh/authorized_keys

### Step to reproduce the behavior
Configure AuthorizedKeysFile parameter at /etc/ssh/sshd_config:
`AuthorizedKeysFile      /etc/ssh/authorized_keys/%u`

**Comment by piyushc01** [comment] 2024-02-20 05:25
Picking AuthorizedKeysFile from user's home directory is by design and is hardcoded in the code. 
gpssh-exkeys --help also says the same: 
```
gpssh-exkeys --help 
.
. 
       * Connects to each host using ssh and obtains the authorized_keys,
       known_hosts, and id_rsa.pub files to set up password-free access.
  ```

**Comment by piyushc01** [comment] 2024-03-06 06:09
Closing as it is by design.

**Closed by piyushc01** 2024-03-06 06:09 UTC
Labels: type: bug
