### ISSUE TITLE
Greenplum not works with linux zfs

### ISSUE THREAD

**Issue by ynqjwsm** [greenplum-db/gpdb#11198] opened 2020-11-20 12:42 UTC
### Greenplum version or build
6.8.0
### OS version and uname -a
Linux data-market 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### FS ###
zfs on linux 
raidz1 pool with lz4 compress

greenplum can't work on zfs, fts error triggers failover to mirror

error logs on segs:

2020-11-20 15:32:37.247742 CST|||p18802|th-849971072||||0|con2||seg-1|||||LOG: |00000|FTS: error response from (content=30, dbid=32) state=0, retry_count=0, conn->async
Status=1 ERROR:  disk IO check during FTS probe failed (ftsmessagehandler.c:164)
|||||||0||ftsprobe.c|719|
2020-11-20 15:32:37.248100 CST|||p18802|th-849971072||||0|con2||seg-1|||||LOG: |00000|FTS: error response from (content=8, dbid=10) state=0, retry_count=0, conn->asyncS
tatus=1 ERROR:  disk IO check during FTS probe failed (ftsmessagehandler.c:164)
|||||||0||ftsprobe.c|719|
2020-11-20 15:32:37.248203 CST|||p18802|th-849971072||||0|con2||seg-1|||||LOG: |00000|FTS: error response from (content=14, dbid=16) state=0, retry_count=0, conn->async
Status=1 ERROR:  disk IO check during FTS probe failed (ftsmessagehandler.c:164)
|||||||0||ftsprobe.c|719|
2020-11-20 15:32:37.248292 CST|||p18802|th-849971072||||0|con2||seg-1|||||LOG: |00000|FTS: error response from (content=0, dbid=2) state=0, retry_count=0, conn->asyncSt
atus=1 ERROR:  disk IO check during FTS probe failed (ftsmessagehandler.c:164)
|||||||0||ftsprobe.c|719|

**Comment by adam8157** [comment] 2020-12-03 07:23
It's probably because of the `O_DIRECT`.

What's the version of your ZFS? It supports `open()` with `O_DIRECT` option from 0.8.0.

**Comment by ynqjwsm** [comment] 2020-12-03 07:28
> It's probably because of the `O_DIRECT`.
> 
> What's the version of your ZFS? It supports `open()` with `O_DIRECT` option from 0.8.0.

zfs-0.8.5-1
zfs-kmod-0.8.5-1

**Comment by adam8157** [comment] 2020-12-04 09:34
I could not reproduce, Greenplum works well on Ubuntu 20.04/20.10 with `zfs-dkms`, your kernel version seems old.

**Comment by ashwinstar** [comment] 2021-02-19 23:32
I am closing this issue based on comment from @adam8157. If the issue is still encountered on newer versions of ZFS let us know and we can look into it.

**Closed by ashwinstar** 2021-02-19 23:32 UTC
