### ISSUE TITLE
Bug: gpinitsystem Does Not Support IP Addresses in Config File

### ISSUE THREAD

**Issue by Xangis** [greenplum-db/gpdb#105] opened 2015-11-19 19:40 UTC
in the server_ips file, there's an entry for an IP:

10.10.2.147

Running the gpinitsystem command:

gpinitsystem -c gpinitsystem_config -h server_ips

20151119:19:33:57:013585 gpinitsystem:ip-10-10-2-75:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20151119:19:33:57:013585 gpinitsystem:ip-10-10-2-75:gpadmin-[INFO]:-Checking configuration parameters, Completed
20151119:19:33:57:013585 gpinitsystem:ip-10-10-2-75:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
Script Exiting!07:gpinitsystem:ip-10-10-2-75:gpadmin-[FATAL]:-Unknown host 10.10.2.147

The problem is that a host lookup fails for an IP (because the host has already been looked up). Not all machines have resolvable hostnames, but they do have valid IPs.

Please modify gpinitsystem to accept IP addresses in addition to hostnames.

**Comment by asimrp** [comment] 2015-11-20 01:44
Hi Xangis

Thank you for creating the issue.  I was not able to reproduce your problem.  Entering IP address in the server_ips file worked just fine for me.  Can you please share some more details?  E.g. are you able to execute `ping 10.10.2.147` from the same shell as you execute `gpinitsystem`?

Asim

**Comment by Xangis** [comment] 2015-11-20 23:36
It appears that this was a misleading error. I was able to use an IP address to spin up a segment on RHEL, but it the gpinit scripts didn't play well with Debian even though I could SSH into and resolve the hostname on the target. It was some other problem being reported as an unknown host (not sure exactly what it was, though).

It looks like the setup scripts just don't play well with Debian/Ubuntu yet and I should stick to RHEL/CentOS for now.

Safe to close.

**Comment by asimrp** [comment] 2015-11-21 02:15
Closing as per Xangis' confirmation.

**Closed by asimrp** 2015-11-21 02:15 UTC
