### ISSUE TITLE
More than 8 slices on one table query caused a UDP network WARN and query will not finish

### ISSUE THREAD

**Issue by wangcarven** [greenplum-db/gpdb#12418] opened 2021-08-03 08:00 UTC
### Expected behavior 

Got a query result

### Actual behavior  

query doesn't finish and got a warn about UDP network error

### Step to reproduce the behavior

A table named player_enter partitioned by date , each partition contains 100K  records. and execute the following SQL
after 100 second a warn was displayed

```
interconnect may encountered a network error, please check your network  (seg4 slice1 172.17.200.107:6001 pid=398322)
interconnect may encountered a network error, please check your network  (seg5 slice1 172.17.200.105:6000 pid=23326)
interconnect may encountered a network error, please check your network  (seg11 slice1 172.17.200.105:6002 pid=23329)
interconnect may encountered a network error, please check your network  (seg5 slice2 172.17.200.105:6000 pid=23334)
interconnect may encountered a network error, please check your network  (seg11 slice2 172.17.200.105:6002 pid=23337)
interconnect may encountered a network error, please check your network  (seg4 slice3 172.17.200.107:6001 pid=398337)
interconnect may encountered a network error, please check your network  (seg5 slice3 172.17.200.105:6000 pid=23342)
interconnect may encountered a network error, please check your network  (seg11 slice3 172.17.200.105:6002 pid=23345)
interconnect may encountered a network error, please check your network  (seg4 slice4 172.17.200.107:6001 pid=398346)
interconnect may encountered a network error, please check your network  (seg5 slice4 172.17.200.105:6000 pid=23350)
interconnect may encountered a network error, please check your network  (seg11 slice4 172.17.200.105:6002 pid=23353)
interconnect may encountered a network error, please check your network  (seg5 slice5 172.17.200.105:6000 pid=23358)
```

then the query doesn't finish after tens of hours.
Errors like 
"WARNING","01000","interconnect may encountered a network error, please check your network","Failed to send packet (seq 1) to 127.0.0.1:4720 (pid 9487 cid -1) after 100 retries. ",0,,"ic_udpifc.c",5107,
was found in the pg_log file of segments.

```
SELECT
COUNT(_step_1.oid) ,
COUNT(_step_2.oid) ,
COUNT(_step_3.oid) ,
COUNT(_step_4.oid) ,
COUNT(_step_5.oid) ,
COUNT(_step_6.oid) ,
COUNT(_step_7.oid) ,
COUNT(_step_8.oid)
FROM
(
SELECT
tem.oid,
MIN(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-01-02'
AND '2021-01-30'
) AS tem
GROUP BY
tem.oid
) AS _step_1
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-02-02'
AND '2021-02-28'
) AS tem
GROUP BY
tem.oid
) AS _step_2 ON _step_2.oid = _step_1.oid
AND _step_2.log_time > _step_1.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-03-02'
AND '2021-03-30'
) AS tem
GROUP BY
tem.oid
) AS _step_3 ON _step_3.oid = _step_2.oid
AND _step_3.log_time > _step_2.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-04-02'
AND '2021-04-30'
) AS tem
GROUP BY
tem.oid
) AS _step_4 ON _step_4.oid = _step_3.oid
AND _step_4.log_time > _step_3.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-05-02'
AND '2021-05-30'
) AS tem
GROUP BY
tem.oid
) AS _step_5 ON _step_5.oid = _step_4.oid
AND _step_5.log_time > _step_4.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-06-02'
AND '2021-06-30'
) AS tem
GROUP BY
tem.oid
) AS _step_6 ON _step_6.oid = _step_5.oid
AND _step_6.log_time > _step_5.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2021-07-02'
AND '2021-07-30'
) AS tem
GROUP BY
tem.oid
) AS _step_7 ON _step_7.oid = _step_6.oid
AND _step_7.log_time > _step_6.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2020-01-02'
AND '2020-01-30'
) AS tem
GROUP BY
tem.oid
) AS _step_8 ON _step_8.oid = _step_7.oid
AND _step_8.log_time > _step_7.log_time
LEFT JOIN (
SELECT
tem.oid,
MAX(tem.log_time) as log_time
FROM
(
SELECT
player_enter.player_id AS oid,
player_enter.log_time AS log_time
FROM
player_enter
WHERE
player_enter.channel in ('a','b')
AND player_enter.wash_date BETWEEN '2020-02-02'
AND '2020-02-28'
) AS tem
GROUP BY
tem.oid
) AS _step_9 ON _step_9.oid = _step_8.oid
AND _step_9.log_time > _step_8.log_time
```

and the execute plan is as following

```
Aggregate  (cost=0.00..3879.02 rows=1 width=64)
  ->  Gather Motion 12:1  (slice11; segments: 12)  (cost=0.00..3879.02 rows=1 width=64)
        ->  Aggregate  (cost=0.00..3879.02 rows=1 width=64)
              ->  Hash Left Join  (cost=0.00..3879.02 rows=1 width=64)
                    Hash Cond: (player_enter_7.player_id = player_enter_8.player_id)
                    Join Filter: ((max(player_enter_8.log_time)) > (max(player_enter_7.log_time)))
                    ->  Hash Left Join  (cost=0.00..3448.02 rows=1 width=72)
                          Hash Cond: (player_enter_6.player_id = player_enter_7.player_id)
                          Join Filter: ((max(player_enter_7.log_time)) > (max(player_enter_6.log_time)))
                          ->  Hash Left Join  (cost=0.00..3017.02 rows=1 width=64)
                                Hash Cond: (player_enter_5.player_id = player_enter_6.player_id)
                                Join Filter: ((max(player_enter_6.log_time)) > (max(player_enter_5.log_time)))
                                ->  Hash Left Join  (cost=0.00..2586.01 rows=1 width=56)
                                      Hash Cond: (player_enter_4.player_id = player_enter_5.player_id)
                                      Join Filter: ((max(player_enter_5.log_time)) > (max(player_enter_4.log_time)))
                                      ->  Redistribute Motion 1:12  (slice6)  (cost=0.00..2155.01 rows=5 width=48)
                                            ->  Hash Left Join  (cost=0.00..2155.01 rows=1 width=48)
                                                  Hash Cond: (player_enter_3.player_id = player_enter_4.player_id)
                                                  Join Filter: ((max(player_enter_4.log_time)) > (max(player_enter_3.log_time)))
                                                  ->  Hash Left Join  (cost=0.00..1724.01 rows=1 width=40)
                                                        Hash Cond: (player_enter_2.player_id = player_enter_3.player_id)
                                                        Join Filter: ((max(player_enter_3.log_time)) > (max(player_enter_2.log_time)))
                                                        ->  Hash Left Join  (cost=0.00..1293.00 rows=1 width=32)
                                                              Hash Cond: (player_enter_1.player_id = player_enter_2.player_id)
                                                              Join Filter: ((max(player_enter_2.log_time)) > (max(player_enter_1.log_time)))
                                                              ->  Hash Left Join  (cost=0.00..862.00 rows=1 width=24)
                                                                    Hash Cond: (player_enter.player_id = player_enter_1.player_id)
                                                                    Join Filter: ((max(player_enter_1.log_time)) > (min(player_enter.log_time)))
                                                                    ->  Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                                          ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                                                ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                                                      Group Key: player_enter.player_id
                                                                                      ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                                            Sort Key: player_enter.player_id
                                                                                            ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                                                  ->  Partition Selector for player_enter (dynamic scan id: 1)  (cost=10.00..100.00 rows=9 width=4)
                                                                                                        Partitions selected: 17 (out of 601)
                                                                                                  ->  Dynamic Seq Scan on player_enter (dynamic scan id: 1)  (cost=0.00..431.00 rows=1 width=28)
                                                                                                        Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-01-02'::date) AND (wash_date <= '2021-01-30'::date))
                                                                    ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                                                          ->  Gather Motion 12:1  (slice2; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                                                ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                                                      ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                                                            Group Key: player_enter_1.player_id
                                                                                            ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                                                  Sort Key: player_enter_1.player_id
                                                                                                  ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                                                        ->  Partition Selector for player_enter (dynamic scan id: 2)  (cost=10.00..100.00 rows=9 width=4)
                                                                                                              Partitions selected: 27 (out of 601)
                                                                                                        ->  Dynamic Seq Scan on player_enter player_enter_1 (dynamic scan id: 2)  (cost=0.00..431.00 rows=1 width=28)
                                                                                                              Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-02-02'::date) AND (wash_date <= '2021-02-28'::date))
                                                              ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                                                    ->  Gather Motion 12:1  (slice3; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                                          ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                                                ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                                                      Group Key: player_enter_2.player_id
                                                                                      ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                                            Sort Key: player_enter_2.player_id
                                                                                            ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                                                  ->  Partition Selector for player_enter (dynamic scan id: 3)  (cost=10.00..100.00 rows=9 width=4)
                                                                                                        Partitions selected: 29 (out of 601)
                                                                                                  ->  Dynamic Seq Scan on player_enter player_enter_2 (dynamic scan id: 3)  (cost=0.00..431.00 rows=1 width=28)
                                                                                                        Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-03-02'::date) AND (wash_date <= '2021-03-30'::date))
                                                        ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                                              ->  Gather Motion 12:1  (slice4; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                                    ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                                          ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                                                Group Key: player_enter_3.player_id
                                                                                ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                                      Sort Key: player_enter_3.player_id
                                                                                      ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                                            ->  Partition Selector for player_enter (dynamic scan id: 4)  (cost=10.00..100.00 rows=9 width=4)
                                                                                                  Partitions selected: 29 (out of 601)
                                                                                            ->  Dynamic Seq Scan on player_enter player_enter_3 (dynamic scan id: 4)  (cost=0.00..431.00 rows=1 width=28)
                                                                                                  Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-04-02'::date) AND (wash_date <= '2021-04-30'::date))
                                                  ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                                        ->  Gather Motion 12:1  (slice5; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                              ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                                    ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                                          Group Key: player_enter_4.player_id
                                                                          ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                                Sort Key: player_enter_4.player_id
                                                                                ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                                      ->  Partition Selector for player_enter (dynamic scan id: 5)  (cost=10.00..100.00 rows=9 width=4)
                                                                                            Partitions selected: 29 (out of 601)
                                                                                      ->  Dynamic Seq Scan on player_enter player_enter_4 (dynamic scan id: 5)  (cost=0.00..431.00 rows=1 width=28)
                                                                                            Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-05-02'::date) AND (wash_date <= '2021-05-30'::date))
                                      ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                            ->  Broadcast Motion 12:12  (slice7; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                                  ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                        ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                              Group Key: player_enter_5.player_id
                                                              ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                                    Sort Key: player_enter_5.player_id
                                                                    ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                          ->  Partition Selector for player_enter (dynamic scan id: 6)  (cost=10.00..100.00 rows=9 width=4)
                                                                                Partitions selected: 29 (out of 601)
                                                                          ->  Dynamic Seq Scan on player_enter player_enter_5 (dynamic scan id: 6)  (cost=0.00..431.00 rows=1 width=28)
                                                                                Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-06-02'::date) AND (wash_date <= '2021-06-30'::date))
                                ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                      ->  Broadcast Motion 12:12  (slice8; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                            ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                                  ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                        Group Key: player_enter_6.player_id
                                                        ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                              Sort Key: player_enter_6.player_id
                                                              ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                                    ->  Partition Selector for player_enter (dynamic scan id: 7)  (cost=10.00..100.00 rows=9 width=4)
                                                                          Partitions selected: 29 (out of 601)
                                                                    ->  Dynamic Seq Scan on player_enter player_enter_6 (dynamic scan id: 7)  (cost=0.00..431.00 rows=1 width=28)
                                                                          Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2021-07-02'::date) AND (wash_date <= '2021-07-30'::date))
                          ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                                ->  Broadcast Motion 12:12  (slice9; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                      ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                            ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                                  Group Key: player_enter_7.player_id
                                                  ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                        Sort Key: player_enter_7.player_id
                                                        ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                              ->  Partition Selector for player_enter (dynamic scan id: 8)  (cost=10.00..100.00 rows=9 width=4)
                                                                    Partitions selected: 11 (out of 601)
                                                              ->  Dynamic Seq Scan on player_enter player_enter_7 (dynamic scan id: 8)  (cost=0.00..431.00 rows=1 width=28)
                                                                    Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2020-01-02'::date) AND (wash_date <= '2020-01-30'::date))
                    ->  Hash  (cost=431.00..431.00 rows=1 width=16)
                          ->  Broadcast Motion 12:12  (slice10; segments: 12)  (cost=0.00..431.00 rows=1 width=16)
                                ->  Result  (cost=0.00..431.00 rows=1 width=16)
                                      ->  GroupAggregate  (cost=0.00..431.00 rows=1 width=16)
                                            Group Key: player_enter_8.player_id
                                            ->  Sort  (cost=0.00..431.00 rows=1 width=16)
                                                  Sort Key: player_enter_8.player_id
                                                  ->  Sequence  (cost=0.00..431.00 rows=1 width=28)
                                                        ->  Partition Selector for player_enter (dynamic scan id: 9)  (cost=10.00..100.00 rows=9 width=4)
                                                              Partitions selected: 9 (out of 601)
                                                        ->  Dynamic Seq Scan on player_enter player_enter_8 (dynamic scan id: 9)  (cost=0.00..431.00 rows=1 width=28)
                                                              Filter: (((channel)::text = ANY ('{a,b}'::text[])) AND (wash_date >= '2020-02-02'::date) AND (wash_date <= '2020-02-28'::date))
Optimizer: Pivotal Optimizer (GPORCA)
```

**Comment by Aegeaner** [comment] 2022-01-06 08:28
This issue looks similar with [https://github.com/greenplum-db/gpdb/issues/12961](https://github.com/greenplum-db/gpdb/issues/12961)

**Comment by lij55** [comment] 2022-08-16 09:30
Hi @wangcarven , did you still hit this issue? do you have chance to check the drop rate of segment host by `ifconfig`? this issue seems to related with bad network environment. you could also try tpc interconnect as a work around.

**Comment by dpandhi-git** [comment] 2022-11-20 01:56
@kainwen Can it be marked as duplicate of #12961

**Comment by kainwen** [comment] 2022-11-20 02:13
> @kainwen Can it be marked as duplicate of #12961

Not sure. One year no update, close it.

Feel free to reopen with detailed info.

**Closed by kainwen** 2022-11-20 02:13 UTC
Labels: type: bug, area: server, version: 6X_STABLE, Priority 1
