### ISSUE TITLE
Query is hanging with planner (optimizer=off)

### ISSUE THREAD

**Issue by DevChattopadhyay** [greenplum-db/gpdb#15827] opened 2023-06-22 04:43 UTC
### Greenplum version or build
Query containing CTE is getting stuck with optimizer=off in 7X

### Step to reproduce the behavior

`Setup`
```
create table t1(a int, b int);
create table t2(a int, b int);
create table t3(a int, b int);
```

`Query`
```
set optimizer to off;
SET

with cte1 as (select * from t1), cte2 as (select * from t2), cte3 as (select * from t3) select * from cte1 where ( EXISTS ( select cte2.a from cte2 left join cte3 on (EXISTS ( select cte1.b from cte2))));
```

**Comment by kainwen** [comment] 2023-06-23 08:29
```sql
gpadmin=# explain (costs off, verbose) with cte1 as (select * from t1), cte2 as (select * from t2), cte3 as (select * from t3) select * from cte1 where ( EXISTS ( select cte2.a from cte2 left join cte3 on (EXISTS ( select cte1.b from cte2))));
                                      QUERY PLAN
--------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)
   Output: cte1.a, cte1.b
   ->  Subquery Scan on cte1
         Output: cte1.a, cte1.b
         Filter: (SubPlan 2)
         ->  Seq Scan on public.t1
               Output: t1.a, t1.b
         SubPlan 2
           ->  Nested Loop Left Join
                 Join Filter: $1
                 InitPlan 1 (returns $1)  (slice4)
                   ->  Result
                         Output: cte1.b
                         ->  Materialize
                               ->  Gather Motion 3:1  (slice5; segments: 3)
                                     ->  Subquery Scan on cte2
                                           ->  Shared Scan (share slice:id 5:0)
                                                 Output: share0_ref1.a, share0_ref1.b
                                                 ->  Seq Scan on public.t2
                                                       Output: t2.a, t2.b
                 ->  Materialize
                       ->  Broadcast Motion 3:3  (slice2; segments: 3)
                             ->  Subquery Scan on cte2_1
                                   ->  Shared Scan (share slice:id 2:0)
                                         Output: share0_ref2.a, share0_ref2.b
                 ->  Materialize
                       Output: t3.a, t3.b
                       ->  Materialize
                             Output: t3.a, t3.b
                             ->  Broadcast Motion 3:3  (slice3; segments: 3)
                                   Output: t3.a, t3.b
                                   ->  Seq Scan on public.t3
                                         Output: t3.a, t3.b
 Optimizer: Postgres query optimizer
 Settings: optimizer = 'off'
(35 rows)
```

The root cause is shared plan cannot cross InitPlan.

Use gdb to hacking force not share in `set_cte_pathlist` can make it work.

Plus, `gp_cte_sharing` does not work for this bug.

All the above points have to be carefully checked.

**Comment by charliettxx** [comment] 2023-08-18 06:45
> ```sql
>                  InitPlan 1 (returns $1)  (slice4)
>                    ->  Result
>                          Output: cte1.b
>                          ->  Materialize
>                                ->  Gather Motion 3:1  (slice5; segments: 3)
>                                      ->  Subquery Scan on cte2
>                                            ->  Shared Scan (share slice:id 5:0)
>                                                  Output: share0_ref1.a, share0_ref1.b
>                                                  ->  Seq Scan on public.t2
>                                                        Output: t2.a, t2.b
> ```

There is a strange thing here, for the `InitPlan 1` above, `cte1.b `should be come from outside of InitPlan, so
InitPlan should be `Subplan` instead of `InitPlan` or did I miss something?

**Comment by charliettxx** [comment] 2024-01-03 08:32
https://github.com/greenplum-db/gpdb/pull/16105 PR merged, closed it.

**Closed by charliettxx** 2024-01-03 08:32 UTC
Labels: type: bug, topic: planner, Priority 1, executor
