### ISSUE TITLE
Cannot Control  the amount of memory to be allocated to  single query memory  through set the parameter "statement_mem"

### ISSUE THREAD

**Issue by cartooku** [greenplum-db/gpdb#10154] opened 2020-05-20 07:06 UTC
### Greenplum version or build
greenplum 6.3
### OS version and uname -a
LINUX 3.10.0-693.el7.x86_64
### Expected behavior
I have set  the following parameter's value and restarted the GP instance 
max_statement_mem  2000MB
statement_mem 125MB
gp_vmem_protect_limit   12288MB
memeory_spill_ratio = 0

So I think    one    single query  may not exhaust the OS memory 
### Actual behavior
One single query exhausted too much memory ,and throw the error like this ：
ERROR: Canceling query because of high VMEM usage, Used: 11048MB, available 1227MB, red Zone:11059MB(runaway_clearner.c:189)

**Comment by gaos1** [comment] 2020-05-22 03:28
this looks duplicate of #10165.

**Closed by gaos1** 2020-05-22 03:28 UTC
