### ISSUE TITLE
[gpdb 6] Mirror failed with PANIC could not fsync file base/xxx/xxx: No such file or directory

### ISSUE THREAD

**Issue by diarworld** [greenplum-db/gpdb#9034] opened 2019-11-12 21:45 UTC
We have updated our production system to gpdb version 6.0.1just few weeks ago. 

Cluster configuration is 396 primary segments on 22 segment hosts with following parameters:

    HPE DL380 Gen10 5115 Xeon-G (Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz)
    256GB Memory (HPE 32GB 2Rx4 PC4-2666V-R)
    10TB RAID10 software array (HPE 1.8TB SAS 10K SFF SC 512e)
    4x10GB bonded network interfaces

And few days ago we faced with terrible situation - most mirrors accidentally fails with following error message:
```
2019-11-12 23:54:36.046279,,,p23563,th858245248,,,,0,,,seg95,,,,,"PANIC","58P01","could not fsync file ""base/16634/756774"": No such file or directory",,,,,,,0,,"md.c",1284,"Stack trace:
1    0x9f3c3c postgres errstart (elog.c:558)
2    0x8848e1 postgres mdsync (md.c:1281)
3    0x855288 postgres CheckPointBuffers (bufmgr.c:2008)
4    0x5536d2 postgres CreateRestartPoint (xlog.c:9160)
5    0x807630 postgres CheckpointerMain (checkpointer.c:519)
6    0x595fd1 postgres AuxiliaryProcessMain (bootstrap.c:437)
7    0x813195 postgres <symbol not found> (postmaster.c:5824)
8    0x81517c postgres <symbol not found> (postmaster.c:5494)
9    0x7f202f8415d0 libpthread.so.0 <symbol not found> + 0x2f8415d0
10   0x7f202ed3af53 libc.so.6 __select + 0x13
11   0x4cbb8f postgres <symbol not found> (postmaster.c:1891)
12   0x816856 postgres PostmasterMain (postmaster.c:1520)
13   0x4cf151 postgres main (main.c:205)
14   0x7f202ec683d5 libc.so.6 __libc_start_main + 0xf5
15   0x4cf72c postgres <symbol not found> + 0x4cf72c
"
```
FTS marks this mirrors as failed and then after 3-5 mins they could became up again in random order. `gprecoverseg -F` command helps to fix this issue, but yesterday we received this error simultaneously with primary segment error. Entire cluster was failed and could not start, cause primary segment was marked as down, and mirror segment fails with previous error.
```[ERROR]:-gpstart error: Do not have enough valid segments to start the array.```
We fixed this issue when stared only one postgres segment process using pg_ctl with WAL restore to correct position. Seems that WAL log on mirrors accidentally breaks:
```pg_xlogdump: FATAL:  error in WAL record at 12/651F35F0: unexpected pageaddr 12/15200000 in log segment 000000000000001200000019, offset 18874368```

Did you faced with this issue on GP 6+? I have no idea how to fix this.
 
### Greenplum version or build
Greenplum Database 6.0.1 OSS build

### OS version and uname -a
CentOS 7 kernel 3.10.0-957.12.1.el7.x86_64
### Installation information ( pg_config )
BINDIR = /usr/local/greenplum-db-6.0.1/bin
DOCDIR = /usr/local/greenplum-db-6.0.1/share/doc/postgresql
HTMLDIR = /usr/local/greenplum-db-6.0.1/share/doc/postgresql
INCLUDEDIR = /usr/local/greenplum-db-6.0.1/include
PKGINCLUDEDIR = /usr/local/greenplum-db-6.0.1/include/postgresql
INCLUDEDIR-SERVER = /usr/local/greenplum-db-6.0.1/include/postgresql/server
LIBDIR = /usr/local/greenplum-db-6.0.1/lib
PKGLIBDIR = /usr/local/greenplum-db-6.0.1/lib/postgresql
LOCALEDIR = /usr/local/greenplum-db-6.0.1/share/locale
MANDIR = /usr/local/greenplum-db-6.0.1/man
SHAREDIR = /usr/local/greenplum-db-6.0.1/share/postgresql
SYSCONFDIR = /usr/local/greenplum-db-6.0.1/etc/postgresql
PGXS = /usr/local/greenplum-db-6.0.1/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-debug-extensions' '--disable-tap-tests' '--enable-orca' '--with-zstd' '--with-gssapi' '--with-libxml' '--with-perl' '--with-python' '--with-openssl' '--with-pam' '--with-ldap' '--enable-gpperfmon' '--prefix=/usr/local/greenplum-db-oss' '--mandir=/usr/local/greenplum-db-oss/man' 'CC=gcc' 'CFLAGS=-O3 -fargument-noalias-global -fno-omit-frame-pointer -g'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/greenplum-db-6.0.1/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -O3 -fargument-noalias-global -fno-omit-frame-pointer -g -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/greenplum-db-6.0.1/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/greenplum-db-oss/lib',--enable-new-dtags -L/usr/local/greenplum-db-6.0.1/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lpam -lrt -lgssapi_krb5 -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/greenplum-db-6.0.1/lib
VERSION = PostgreSQL 9.4.24

Default installation with gpperfmon enabled only:
gp_resource_manager=group
gp_enable_gpperfmon=on
gpperfmon_port=8888
gp_external_enable_exec=on
gpperfmon_log_alert_level=warning

### Expected behavior
Correctly working mirrors.
### Actual behavior 
Mirrors randomly fails.
### Step to reproduce the behavior
When we tested GP6 cluster with TPC-DS 3TB test we didn't received this errors. I can only assume that it is reproduced on some heavy ETL workloads with OLTP queries in parallel.

**Comment by paul-guo-** [comment] 2019-11-13 01:58
Can you first find what relation name & tablespace are base/16634/756774?

You could check it on the failed segment via utility mode or single mode

To find them, run

 ```
SET gp_select_invisible = TRUE;
select * from pg_class where relfilenode = 756774;
select oid,* from pg_tablespace where oid=16634;
```

And then find related SQLs via logs or your workloads and then could try to find a repro case.

**Comment by paul-guo-** [comment] 2019-11-13 02:47
Correction: 16634 is for db oid. Updated the previous post.

**Comment by diarworld** [comment] 2019-11-26 08:04
We have reproduced this problem when tried to write big bunch of data to AO tables (more than 300 batches with 10000000 rows inside). 
I think this issue is related to this bug: https://github.com/greenplum-db/gpdb/issues/9008 cause we saw large replication lag in gp_stat_replication table right before this errors.

And as we checked by your sql - all affected relfilenodes is members of pg_aoseg schema.

**Comment by paul-guo-** [comment] 2019-11-26 08:57
https://github.com/greenplum-db/gpdb/issues/9008 is a performance issue so should be not relevant of this issue but is a good clue of reproducing. Narrowing down to pg_aoseg has been a good progress. Thanks.

**Comment by gfphoenix78** [comment] 2019-12-27 08:24
@diarworld Could you paste the script here, to reproduce this issue? So we can quickly locate the bug. Thank you.

**Comment by paul-guo-** [comment] 2019-12-30 06:57
To be clear, I was not saying that this issue is an ao related bug but probably could try to reproduce using those ao related operations. Probably we also should look at the code to see how this could happen in theory, given elog(PANIC) is annoy in real production environment.

**Comment by asimrp** [comment] 2019-12-31 04:53
@diarworld if the PANIC is seen in mirror logs next time, can you please post the output of `pg_xlogdump` for the affected WAL segment?  The WAL dump may not be sufficient to analyze the problem but what would be interesting to know is all the operations performed on the file that was reportedly not found when the mirror tried `fsync()`.

In addition, can you please elaborate the following point from issue description:
> We fixed this issue when stared only one postgres segment process using pg_ctl with WAL restore to correct position.

What command did you run?  Was it run on the mirror or the primary?

**Comment by ashwinstar** [comment] 2020-01-08 01:21
@diarworld Please if possible to share the scripts or if not possible, just share high-level what operations are performed on AO table when the issue reproduced will be super helpful to nail this down. So, knowing like only loading was performed or truncate, alter, drop, temp table, unlogged tables would be helpful to know.

**Comment by diarworld** [comment] 2020-01-09 09:42
> @diarworld Please if possible to share the scripts or if not possible, just share high-level what operations are performed on AO table when the issue reproduced will be super helpful to nail this down. So, knowing like only loading was performed or truncate, alter, drop, temp table, unlogged tables would be helpful to know.

I couldn't reproduce error now, cause it seem to be fixed with wal_sender_timeout GUC set to 0 and increased wal_keep_segments to 32.
This error were persists when we insert big bunch of data (100Gb-1Tb) into tables like {appendonly = true, compresslevel = 1, orientation = row, compresstype = zstd}, using NiFi with ~ 10000 batch size.

**Comment by asimrp** [comment] 2020-01-09 11:51
Note that `wal_keep_segments` is not effective in 6X and beyond due to replication slots.  Primary uses replication slot to keep track of mirror's state, specifically, the WAL flush LSN acknowledged by mirror.  This information is used by primary when cleaning up old WAL files during checkpoint.

**Comment by ashwinstar** [comment] 2020-01-14 20:02
Okay, I will close this issue then as "cannot reproduce" and not much info to investigate. Anytime see the issue again please let us know. I am in process of fixing similar "cannot fsync issue" but that happens in-case of same transaction CREATE and TRUNCATE AO table. I have not heard truncate being performed in this case so far.

**Closed by ashwinstar** 2020-01-14 20:02 UTC
