### ISSUE TITLE
citymodel=# select * from faa.t_sjhj_sjhjzd_sjmxzd;不返回结果原因？

### ISSUE THREAD

**Issue by gpadmin12345** [greenplum-db/gpdb#6991] opened 2019-02-15 08:25 UTC

**Comment by gaos1** [comment] 2019-02-15 09:08
could you complete the reproduce steps , specially your table definition?

**Comment by gpadmin12345** [comment] 2019-02-15 09:37
可以创建表和删除表，就是不可以插入，查询！

**Comment by gpadmin12345** [comment] 2019-02-15 09:38
它也不报错误，就是卡着不动？

**Comment by berlin-ab** [comment] 2019-02-15 15:22
@gaos1 Would you describe the problem to help us categorize and prioritize this issue? Thanks!

**Comment by gaos1** [comment] 2019-02-18 09:40
The user can create table or drop table, but cannot insert data or execute any query. e.g. the following query will hang: 
``` 
select * from faa.t_sjhj_sjhjzd_sjmxzd;
```

but there is no clear reproduce steps.

**Comment by gpadmin12345** [comment] 2019-02-19 00:36
yes

**Comment by gpadmin12345** [comment] 2019-02-19 00:38
请问这是什么原因？

**Comment by gpadmin12345** [comment] 2019-02-19 01:17
greenplum-db-5.12.0-rhel6-x86_64.bin
CentOS Linux release 7.5.1804 (Core) 
Linux y1_xxb_xxzl_data_master 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by d** [comment] 2019-02-19 01:33
Hi @gpadmin12345 . We're thrilled that you're interested in Greenplum Database and we'd love to help you. However, we need your help in reproducing the problem here. Please provide us with the following information:

1. complete DDL (e.g. `CREATE TABLE`)
1. sample data (e.g. `COPY` or `INSERT`)
1. query (e.g. `CREATE TABLE ... AS SELECT ...` or `SELECT`)
1. cluster configuration, e.g. number of segments, `optimizer=off`, or any other non-default GUC settings

Thanks!
Jesse

**Comment by gpadmin12345** [comment] 2019-02-19 02:06
citymodel=# \d faa.t_sjhj_sjzd_ysj
         Table "faa.t_sjhj_sjzd_ysj"
 Column |          Type          | Modifiers
--------+------------------------+-----------
 id     | character varying(40)  | not null
 zdlxdm | character varying(100) | not null
 zdlxmc | character varying(200) |
 ysjbmc | character varying(40)  |
 ysjbdm | character varying(40)  | not null
 bz     | character varying(200) |
 cjsj   | date                   |
 xgsj   | date                   |
 sfyx   | character varying(10)  |
Indexes:
    "t_sjhj_sjzd_ysj_pkey" PRIMARY KEY, btree (id)
Distributed by: (id)

citymodel=# select * from faa.t_sjhj_sjzd_ysj;
^CCancel request sent
ERROR:  canceling statement due to user request
citymodel=#
---------------------------------------------------------------------------
select * from faa.t_sjhj_sjzd_ysj;无返回结果，强制用ctrl+c退出。

**Comment by gpadmin12345** [comment] 2019-02-19 02:08
数据表是可以创建的，就是查询和插入数据无返回结果

**Comment by berlin-ab** [comment] 2019-02-19 15:09
```
± |5X_STABLE → gpdb ?:8 ✗| → psql
psql (8.3.23)
Type "help" for help.

adamberlin=# create schema faa;
CREATE SCHEMA
adamberlin=# create table faa.t_sjhj_sjzd_ysj (
adamberlin(#   id varchar(40) PRIMARY KEY,
adamberlin(#   zdlxdm varchar(100) not null,
adamberlin(#   zdlxmc varchar(200),
adamberlin(#   ysjbmc varchar(40),
adamberlin(#   ysjbdm varchar(40) not null,
adamberlin(#   bz varchar(200),
adamberlin(#   cjsj date,
adamberlin(#   xgsj date,
adamberlin(#   sfyx varchar(10)
adamberlin(# ) DISTRIBUTED BY (id);
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "t_sjhj_sjzd_ysj_pkey" for table "t_sjhj_sjzd_ysj"
CREATE TABLE
adamberlin=# select * from faa.t_sjhj_sjzd_ysj
adamberlin-# ;
 id | zdlxdm | zdlxmc | ysjbmc | ysjbdm | bz | cjsj | xgsj | sfyx
----+--------+--------+--------+--------+----+------+------+------
(0 rows)

adamberlin=# \d faa.t_sjhj_sjzd_ysj;
         Table "faa.t_sjhj_sjzd_ysj"
 Column |          Type          | Modifiers
--------+------------------------+-----------
 id     | character varying(40)  | not null
 zdlxdm | character varying(100) | not null
 zdlxmc | character varying(200) |
 ysjbmc | character varying(40)  |
 ysjbdm | character varying(40)  | not null
 bz     | character varying(200) |
 cjsj   | date                   |
 xgsj   | date                   |
 sfyx   | character varying(10)  |
Indexes:
    "t_sjhj_sjzd_ysj_pkey" PRIMARY KEY, btree (id)
Distributed by: (id)
```

**Comment by berlin-ab** [comment] 2019-02-19 15:10
It is possible the issue you're seeing has been addressed by a newer version of GPDB 5X.

**Comment by berlin-ab** [comment] 2019-02-19 15:42
I switched to `5.12.0`:

```
± |tag:5.12.0 ?:8 ✗| → psql
psql (8.3.23)
Type "help" for help.

adamberlin=# create schema faa;
CREATE SCHEMA
adamberlin=# create table faa.t_sjhj_sjzd_ysj (
adamberlin(#   id varchar(40) PRIMARY KEY,
adamberlin(#   zdlxdm varchar(100) not null,
adamberlin(#   zdlxmc varchar(200),
adamberlin(#   ysjbmc varchar(40),
adamberlin(#   ysjbdm varchar(40) not null,
adamberlin(#   bz varchar(200),
adamberlin(#   cjsj date,
adamberlin(#   xgsj date,
adamberlin(#   sfyx varchar(10)
adamberlin(# ) DISTRIBUTED BY (id);
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "t_sjhj_sjzd_ysj_pkey" for table "t_sjhj_sjzd_ysj"
CREATE TABLE
adamberlin=# select * from faa.t_sjhj_sjzd_ysj;
 id | zdlxdm | zdlxmc | ysjbmc | ysjbdm | bz | cjsj | xgsj | sfyx
----+--------+--------+--------+--------+----+------+------+------
(0 rows)

adamberlin=# select version();
                                                                                                 version
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.12.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit compiled on Feb 19 2019 15:35:21 (with assert checking)
(1 row)

```

**Comment by berlin-ab** [comment] 2019-02-19 15:43
I'm still not able to reproduce the issue. Is there something else that I'm missing?

**Comment by Eulerizeit** [comment] 2019-02-19 15:49
This sounds like you have compiled without QuickLZ and then created a table using that compression. We have fixed this in master.

**Comment by gpadmin12345** [comment] 2019-02-20 01:16
[gpadmin@y1_xxb_xxzl_data_master ~]$ gpstop -a
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Starting gpstop with args: -a
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Gathering information and validating the environment...
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Obtaining Segment details from master...
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 5.12.0 build commit:6b542cd470174af5559a431318037521f4ad55a6'
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-There are 0 connections to the database
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='smart'
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Master host=y1_xxb_xxzl_data_master
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Commencing Master instance shutdown with mode=smart
20190220:09:10:04:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Master segment instance directory=/data/master/gpseg-1
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Terminating processes for segment /data/master/gpseg-1
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-No standby master host configured
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Targeting dbid [2, 18, 3, 19, 4, 20, 5, 21, 6, 22, 7, 23, 8, 24, 9, 25, 10, 26, 11, 27, 12, 28, 13, 29, 14, 30, 15, 31, 16, 32, 17, 33] for shutdown
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20190220:09:10:05:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-0.00% of jobs completed
20190220:09:10:07:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-100.00% of jobs completed
20190220:09:10:07:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20190220:09:10:07:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-0.00% of jobs completed
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-100.00% of jobs completed
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-----------------------------------------------------
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-   Segments stopped successfully      = 32
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-----------------------------------------------------
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Successfully shutdown 32 of 32 segment instances
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-No leftover gpmmon process found
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20190220:09:10:09:014058 gpstop:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Cleaning up leftover shared memory
[gpadmin@y1_xxb_xxzl_data_master ~]$ cd /home/gpadmin/
.bash_history  .bash_logout   .bash_profile  .bashrc        conf/          faa/           gpAdminLogs/   .gphostcache   .psql_history  .ssh/          .viminfo
[gpadmin@y1_xxb_xxzl_data_master ~]$ cd /home/gpadmin/conf/
[gpadmin@y1_xxb_xxzl_data_master conf]$ ls
hostfile_exkeys  hostfile_gpinitsystem  hostfile_gpssh_segonly
[gpadmin@y1_xxb_xxzl_data_master conf]$ logout
[root@y1_xxb_xxzl_data_master greenplum-db]# cd /home/gpadmin/conf/
[root@y1_xxb_xxzl_data_master conf]# ls
hostfile_exkeys  hostfile_gpinitsystem  hostfile_gpssh_segonly
[root@y1_xxb_xxzl_data_master conf]# su - gpadmin
Last login: Wed Feb 20 09:09:55 CST 2019 on pts/0
[gpadmin@y1_xxb_xxzl_data_master ~]$ gpstart -a
20190220:09:12:54:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Starting gpstart with args: -a
20190220:09:12:54:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Gathering information and validating the environment...
20190220:09:12:54:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 5.12.0 build commit:6b542cd470174af5559a431318037521f4ad55a6'
20190220:09:12:54:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Greenplum Catalog Version: '301705051'
20190220:09:12:54:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Starting Master instance in admin mode
20190220:09:12:55:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20190220:09:12:55:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Obtaining Segment details from master...
20190220:09:12:55:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Setting new master era
20190220:09:12:55:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Master Started...
20190220:09:12:55:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Shutting down master
20190220:09:12:57:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Commencing parallel primary and mirror segment instance startup, please wait...
...
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Process results...
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-----------------------------------------------------
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-   Successful segment starts                                            = 32
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-   Failed segment starts                                                = 0
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-----------------------------------------------------
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Successfully started 32 of 32 segment instances
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-----------------------------------------------------
20190220:09:13:00:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Starting Master instance y1_xxb_xxzl_data_master directory /data/master/gpseg-1
20190220:09:13:01:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Command pg_ctl reports Master y1_xxb_xxzl_data_master instance active
20190220:09:13:01:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-No standby master configured.  skipping...
20190220:09:13:01:014243 gpstart:y1_xxb_xxzl_data_master:gpadmin-[INFO]:-Database successfully started
[gpadmin@y1_xxb_xxzl_data_master ~]$

**Comment by berlin-ab** [comment] 2019-02-22 20:55
Hi @gpadmin12345, was there something that stands out as interesting in this output?

**Comment by JunfengYang** [comment] 2020-11-02 08:05
Can not reproduce, close it for now. Feel free to reopen it if needed.

**Closed by JunfengYang** 2020-11-02 08:05 UTC
Labels: needs: more information, version: 5X_STABLE
