### ISSUE TITLE
can create partition without name，but can't drop it

### ISSUE THREAD

**Issue by k8king** [greenplum-db/gpdb#11274] opened 2020-12-15 04:33 UTC
I have a table like this:
create table test_partition
(
  user_id               int,
  user_name        varchar(32),
  data_type          varchar(10),
  pt_date              date
)
distributed randomly
partition by list(data_type)
subpartition by range(pt_date)
subpartition template
(
 subpartition pn start ('2020-12-01'::date) end ('2020-12-31'::date) every ('1 day'::interval)
)
(
 partition days values ('D'),
 partition weeks values ('W'),
 partition months values ('M')
);
when I add a new partition :
alter table test_partition alter partition days add partition start('2020-01-01') inclusive end ('2020-01-02') exclusive;
I missed the name of new partition,but with no warnings, I create partition succeeded.
I think it's a bug.

**Comment by ashwinstar** [comment] 2020-12-15 19:58
For deleting the partition where name was not explicitly specified can use other ways to reference the partition like can do this to drop the partition
```
alter table test_partition alter partition days drop partition for ('2020-01-01');
```
It's not a bug, name is optional part of the command. You didn't mention which version of GPDB this is being reported for generally helps to provide better help (like if its for GPDB master branch then have more options as PostgreSQL syntax is also available for managing partitions).

**Comment by ashwinstar** [comment] 2021-01-12 01:18
Closing this issue as provided the resolution for it.

**Closed by ashwinstar** 2021-01-12 01:18 UTC
