### ISSUE TITLE
ERROR:  InstrEndLoop called on running node (instrument.c:138)

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#9904] opened 2020-04-10 23:59 UTC
### Greenplum version or build
6X_STABLE (as of commit 5e04eb149f3)

### Expected behavior
`EXPLAIN ANALYZE` finishes executing the query...

### Actual behavior
```
psql:/workspace/gpdb/sql.sql:21: ERROR:  InstrEndLoop called on running node (instrument.c:138)  (seg2 slice2 172.17.0.6:6004 pid=19153) (instrument.c:138)

```

### Step to reproduce the behavior
```sql
CREATE TEMP TABLE foo (a int8, b int, c char(32768) DEFAULT 's');
INSERT INTO foo SELECT i, (i | 7) FROM generate_series(1, 1024) i;
ANALYZE foo;

SELECT $$

SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b

$$ AS qry \gset

EXPLAIN VERBOSE
:qry ;

SET statement_mem='1984kB';

EXPLAIN (COSTS OFF, ANALYZE)
:qry ;

```

**Comment by kainwen** [comment] 2021-09-13 05:33
I cannot reproduce this issue now, top 6X commit is 0de750e8c1d7422c8ba7c409a4028c947126fc4d

It runs quite well:

```
gpadmin@zlyu:~$ cat b.sql
CREATE TEMP TABLE foo (a int8, b int, c char(32768) DEFAULT 's');
INSERT INTO foo SELECT i, (i | 7) FROM generate_series(1, 1024) i;
ANALYZE foo;

SELECT $$

SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b

$$ AS qry \gset

EXPLAIN VERBOSE
:qry ;

SET statement_mem='1984kB';

EXPLAIN (COSTS OFF, ANALYZE)
:qry ;
gpadmin@zlyu:~$ psql -f b.sql
psql:b.sql:1: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
INSERT 0 1024
ANALYZE
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3)  (cost=37.76..39.37 rows=129 width=68)
   Output: (pg_catalog.sum((sum(foo.a) FILTER (WHERE false)))), (max((max(foo.c)))), foo.b
   ->  HashAggregate  (cost=37.76..39.37 rows=43 width=68)
         Output: pg_catalog.sum((sum(foo.a) FILTER (WHERE false))), max((max(foo.c))), foo.b
         Group Key: foo.b
         ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=32.92..35.50 rows=43 width=68)
               Output: foo.b, (sum(foo.a) FILTER (WHERE false)), (max(foo.c))
               Hash Key: foo.b
               ->  HashAggregate  (cost=32.92..32.92 rows=43 width=68)
                     Output: foo.b, sum(foo.a) FILTER (WHERE false), max(foo.c)
                     Group Key: foo.b
                     ->  Seq Scan on pg_temp_21.foo  (cost=0.00..25.24 rows=342 width=32784)
                           Output: foo.a, foo.c, foo.b
 Optimizer: Postgres query optimizer
(14 rows)

SET
                                                             QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice2; segments: 3) (actual time=87.925..107.816 rows=129 loops=1)
   ->  HashAggregate (actual time=87.015..93.136 rows=45 loops=1)
         Group Key: foo.b
         Extra Text: (seg1)   45 groups total in 32 batches; 1 overflows; 68 spill groups.
 (seg1)   Hash chain length 1.2 avg, 3 max, using 60 of 704 buckets; total 0 expansions.

         ->  Redistribute Motion 3:3  (slice1; segments: 3) (actual time=14.147..71.635 rows=129 loops=1)
               Hash Key: foo.b
               ->  HashAggregate (actual time=14.031..46.829 rows=125 loops=1)
                     Group Key: foo.b
                     Extra Text: (seg1)   Hash chain length 1.5 avg, 4 max, using 82 of 128 buckets; total 0 expansions.

                     ->  Seq Scan on foo (actual time=0.013..0.205 rows=349 loops=1)
 Planning time: 11.409 ms
   (slice0)    Executor memory: 364K bytes.
   (slice1)    Executor memory: 2123K bytes avg x 3 workers, 2133K bytes max (seg0).
 * (slice2)    Executor memory: 3098K bytes avg x 3 workers, 3119K bytes max (seg0).  Work_mem: 904K bytes max, 3217K bytes wanted.
 Memory used:  1984kB
 Memory wanted:  6733kB
 Optimizer: Postgres query optimizer
 Execution time: 113.604 ms
(21 rows)

gpadmin@zlyu:~$
```

----------------------------------------

Close this. Feel free to re-open this if needed. @d

**Comment by kainwen** [comment] 2021-11-16 02:09
I checkout to the version mentioned by this issue, it seems some of the segment PANIC and one does not thus leads to the confusing error message.

Even though latest 6X cannot reproduce by the script, we have to understand the root cause and confirm the fix commit (if any).

So re-open it.

**Comment by geekbosszhang** [comment] 2021-11-23 09:56
```
postgres=# EXPLAIN (COSTS OFF, ANALYZE)
postgres-# :qry ;
WARNING:  Any temporary tables for this session have been dropped because the gang was disconnected (session id = 18)
ERROR:  Unexpected internal error (execHHashagg.c:1353)  (seg1 slice2 127.0.0.1:6003 pid=5707) (execHHashagg.c:1353)
DETAIL:  FailedAssertion("!(hashtable->nbuckets > spill_set->num_spill_files)", File: "execHHashagg.c", Line: 1353)
HINT:  Process 5707 will wait for gp_debug_linger=120 seconds before termination.
Note that its locks and other resources will not be released until then.
```
The panic on seg1 is due to `hashtable->nbuckets` might equal `spill_set->num_spill_files`.
The commit  https://github.com/greenplum-db/gpdb/commit/067bb35059948e83cadae8fd3b0f14e6fee9d399 fixed the panic.

But on seg0, it printed an error "instrEndLoop called on running node".
```
InstrEndLoop(Instrumentation *instr)
{
	double		totaltime;

	/* Skip if nothing has happened, or already shut down */
	if (!instr->running)
		return;

	if (!INSTR_TIME_IS_ZERO(instr->starttime))
		elog(ERROR, "InstrEndLoop called on running node");
```
One possible reason is that when QE on seg1 panicked and dispatch the PG result error to QD. And then QD will dispatch cancel command to other QE.
But on seg0, the instr might still be running and instr->startime has values.

```
2021-11-24 01:37:45.729821 CST,"gpadmin","postgres",p5710,th-2145261504,"127.0.0.1","23044",2021-11-24 01:37:42 CST,0,con18,cmd11,seg0,slice1,,,sx1,"LOG","00000","An exception was encountered during the execution of statement: EXPLAIN (COSTS OFF, ANALYZE)
SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b
 ;",,,,,,,0,,,,
2021-11-24 01:37:45.741198 CST,"gpadmin","postgres",p5706,th-2145261504,"127.0.0.1","23040",2021-11-24 01:37:42 CST,0,con18,cmd11,seg0,slice2,,,sx1,"LOG","00000","Process interrupt for 'query cancel pending' (../../../../src/include/cdb/cdbicudpfaultinjection.h:109)",,,,,,"EXPLAIN (COSTS OFF, ANALYZE)
SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b
 ;",0,,"postgres.c",3836,
2021-11-24 01:37:45.779551 CST,"gpadmin","postgres",p5706,th-2145261504,"127.0.0.1","23040",2021-11-24 01:37:42 CST,0,con18,cmd11,seg0,slice2,,,sx1,"ERROR","XX000","Instrumentation starttime 1637689065-437076 is and tuple counts is 0 (instrument.c:133)",,,,,,"EXPLAIN (COSTS OFF, ANALYZE)
SELECT sum(a) FILTER (WHERE false), max(c)
FROM foo
GROUP BY b

 ;",0,,"instrument.c",133,"Stack trace:
1    0xad707b postgres errstart (elog.c:557)
2    0xada1f2 postgres elog_finish (elog.c:1729)
3    0x75b21e postgres InstrEndLoop (instrument.c:133)
4    0x69fd8e postgres <symbol not found> (explain_gp.c:963)
5    0x69f16a postgres <symbol not found> (explain_gp.c:607)
6    0x741a5f postgres <symbol not found> (execProcnode.c:1637)
7    0x741a22 postgres planstate_walk_node (execProcnode.c:1620)
8    0x69f011 postgres cdbexplain_sendExecStats (explain_gp.c:564)
9    0x737ec6 postgres standard_ExecutorRun (discriminator 3)
10   0x737a50 postgres ExecutorRun (execMain.c:819)
11   0x9723f5 postgres <symbol not found> (pquery.c:1152)
12   0x97206e postgres PortalRun (pquery.c:992)
```

**Closed** 2022-01-14 06:43 UTC
Labels: version: 6X_STABLE
