### ISSUE TITLE
ALTER TABLE ONLY ... EXPAND TABLE is broken

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6309] opened 2018-11-23 11:59 UTC
Modified version of test case in 'reshuffle' regression test shows that  `EXPAND TABLE` doesn't work correctly with `ONLY`: 

```
create extension if not exists gp_debug_numsegments;
select gp_debug_set_create_table_default_numsegments(2);
CREATE TABLE inherit_t1_p1(a int, b int) DISTRIBUTED BY (a);
CREATE TABLE inherit_t1_p2(a int, b int) INHERITS (inherit_t1_p1);
CREATE TABLE inherit_t1_p3(a int, b int) INHERITS (inherit_t1_p1);

insert into inherit_t1_p1 select i,i from generate_series(1,5) i;
insert into inherit_t1_p2 select i,i from generate_series(1,5) i;
insert into inherit_t1_p3 select i,i from generate_series(1,5) i;

alter table only inherit_t1_p1 expand table;

postgres=# select localoid::regclass, attrnums, policytype, numsegments from gp_distribution_policy where localoid::regclass in ('inherit_t1_p1', 'inherit_t1_p2', 'inherit_t1_p3');
   localoid    | attrnums | policytype | numsegments 
---------------+----------+------------+-------------
 inherit_t1_p2 | {1}      | p          |           2
 inherit_t1_p3 | {1}      | p          |           2
 inherit_t1_p1 | {1}      | p          |           3
(3 rows)

postgres=#  select tableoid::regclass, gp_segment_id, * from inherit_t1_p1 order by 2,1;
   tableoid    | gp_segment_id | a | b 
---------------+---------------+---+---
 inherit_t1_p1 |             0 | 4 | 4
 inherit_t1_p2 |             0 | 4 | 4
 inherit_t1_p3 |             0 | 4 | 4
 inherit_t1_p1 |             1 | 2 | 2
 inherit_t1_p1 |             1 | 5 | 5
 inherit_t1_p2 |             1 | 2 | 2
 inherit_t1_p2 |             1 | 5 | 5
 inherit_t1_p3 |             1 | 5 | 5
 inherit_t1_p3 |             1 | 2 | 2
 inherit_t1_p1 |             2 | 1 | 1
 inherit_t1_p1 |             2 | 3 | 3
 inherit_t1_p2 |             2 | 1 | 1
 inherit_t1_p2 |             2 | 3 | 3
 inherit_t1_p3 |             2 | 3 | 3
 inherit_t1_p3 |             2 | 1 | 1
(15 rows)
```

The first select shows that `numpartitions` was only changed for the parent, as you would expect with `ONLY`. But data was moved for the children, too, which is wrong.

**Comment by pengzhout** [comment] 2018-11-23 13:44
nice catch, will fix it.

**Comment by yydzero** [comment] 2019-04-02 04:30
@pengzhout is this fixed already?

**Comment by pengzhout** [comment] 2019-04-02 04:32
I believe so, should be fixed by #6341

**Comment by yydzero** [comment] 2019-04-02 04:39
I got below error when rerun the steps to reproduce:

```
yydzero=# alter table only inherit_t1_p1 expand table;
ERROR:  cannot expand table "inherit_t1_p1"
DETAIL:  table has already been expanded
yydzero=#
```

**Comment by pengzhout** [comment] 2019-04-02 04:45
Did your repro steps contain bellow statements?
```
create extension if not exists gp_debug_numsegments;
select gp_debug_set_create_table_default_numsegments(2);
```

The fix works for me on my laptop.

**Comment by yydzero** [comment] 2019-04-02 04:51
Yes, I follow all the steps, and get above error on master

**Comment by yydzero** [comment] 2019-04-02 06:06
Above error is caused by the fact that I am using cluster with 2 segments. After changed to use 1 segment, it works.

**Closed by yydzero** 2019-04-02 06:06 UTC
Labels: area: server, type: bug
