### ISSUE TITLE
gpexpand  failure

### ISSUE THREAD

**Issue by wangxy0825** [greenplum-db/gpdb#7980] opened 2019-06-23 08:28 UTC
### Greenplum version or build
  GP5.1 
### OS version and uname -a
Linux mdw 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
 
![image](https://user-images.githubusercontent.com/52123129/59973531-b8a57500-95d3-11e9-89b5-dcb5ef18be18.png)
![image](https://user-images.githubusercontent.com/52123129/59973533-cbb84500-95d3-11e9-8c2c-84d6be733aa2.png)

### Step to reproduce the behavior

![image](https://user-images.githubusercontent.com/52123129/59973537-d70b7080-95d3-11e9-8324-61dd2ca2e5d7.png)
![image](https://user-images.githubusercontent.com/52123129/59973541-e094d880-95d3-11e9-9909-2b96d0e9d3f7.png)

**Comment by wangxy0825** [comment] 2019-06-23 08:29
![Uploading image.png…]()

**Comment by gaos1** [comment] 2019-06-24 03:17
can you upload the logs for new added segments? it seems you tried to upload one image in comment, but it is not finished.

**Comment by wangxy0825** [comment] 2019-06-24 06:33
![image](https://user-images.githubusercontent.com/52123129/59996482-06ca7f00-968d-11e9-91bf-9776c334bde5.png)

**Comment by kainwen** [comment] 2019-07-14 13:41
Talked offline, the root cause of this issue is due to the UDP problem of the cloud platform. So I close this issue.

**Closed by kainwen** 2019-07-14 13:41 UTC
