### ISSUE TITLE
Memory leak in SetupUDPIFCInterconnect_Internal() with read-only transactions

### ISSUE THREAD

**Issue by fangzheng** [greenplum-db/gpdb#10314] opened 2020-06-17 05:07 UTC
### Greenplum version or build
master

### OS version and uname -a
Mac: 17.5.0 Darwin Kernel Version 17.5.0

Suppose a backend serves a large number of read-only, one-segment transactions in a row, and each transaction runs a simple query like `SELECT * FROM t WHERE primary_key=1;`. 

For each query, `SetupUDPIFCInterconnect_Internal()` function is called when initializing the motion layer in the QD process. `SetupUDPIFCInterconnect_Internal()` calls `GetAllTransactionXids()` to obtain the gxid of current transaction. Since all the transactions we run are read-only and each dispatched to a single segment, all of them have a gxid of 0. This means each call to `SetupUDPIFCInterconnect_Internal()` would add a new entry to the cursor history hash table, and set `rx_control_info.lastDXatId` to 0:

https://github.com/greenplum-db/gpdb/blob/644bde257e7780ff3dee9458bbb5cc553722e5b8/src/backend/cdb/motion/ic_udpifc.c#L3117

Therefore, upon each call to `SetupUDPIFCInterconnect_Internal()` function, current transaction's gxid and `rx_control_info.lastDXatId` are both equal to 0. Hence, the condition for pruning the history hash table can not be satisfied, causing the hash table to keep growing: 

https://github.com/greenplum-db/gpdb/blob/644bde257e7780ff3dee9458bbb5cc553722e5b8/src/backend/cdb/motion/ic_udpifc.c#L3110

To reproduce, I add a debug message just after the call to `GetAllTransactionXids()` in `SetupUDPIFCInterconnect_Internal()`:

````
elog(LOG, "im here cursor history table count = %d, distTransId = %d, lastDXatId = %d",			 rx_control_info.cursorHistoryTable.count, distTransId, rx_control_info.lastDXatId);
````

Then I run 500 queries like the following in a session: 

````
select * from t where primary_key=1;
````

From the log, I see that the number of entries in the history hash table keeps increasing from 0 to 499:

````
./gpdb-2020-06-16_211011.csv:2020-06-16 21:54:44.231294 PDT,"f.zheng","postgres",p71648,th-1505361024,"127.0.0.1","56222",2020-06-16 21:54:40 PDT,0,con11,cmd2,seg-1,,,,sx1,"LOG","00000","im here cursor history table count = 0, distTransId = 0, lastDXatId = 0",,,,,,"select * from t where primary_key=1;",0,,"ic_udpifc.c",3106,
./gpdb-2020-06-16_211011.csv:2020-06-16 21:54:44.235426 PDT,"f.zheng","postgres",p71648,th-1505361024,"127.0.0.1","56222",2020-06-16 21:54:40 PDT,0,con11,cmd4,seg-1,,,,sx1,"LOG","00000","im here cursor history table count = 1, distTransId = 0, lastDXatId = 0",,,,,,"select * from t where primary_key=1;",0,,"ic_udpifc.c",3106,
...
./gpdb-2020-06-16_211011.csv:2020-06-16 21:54:45.752945 PDT,"f.zheng","postgres",p71648,th-1505361024,"127.0.0.1","56222",2020-06-16 21:54:40 PDT,0,con11,cmd1000,seg-1,,,,sx1,"LOG","00000","im here cursor history table count = 499, distTransId = 0, lastDXatId = 0",,,,,,"select * from t where primary_key=1;",0,,"ic_udpifc.c",3106,
````

**Comment by kainwen** [comment] 2021-02-20 10:54
Would you please open a pr to address this? Thanks.

@fangzheng

**Comment by fangzheng** [comment] 2021-02-20 17:17
> Would you please open a pr to address this? Thanks.
> 
> @fangzheng

Hi Zhenghua, sure, I will work on a fix. Thanks.

**Comment by lij55** [comment] 2022-03-22 12:34
Hi @fangzheng , what about the progress of the PR of this fix? thanks in advance.

**Comment by ashwinstar** [comment] 2022-03-25 23:13
This is a memory leak not specific to "with one-segment". It's a generic memory leak on the coordinator/master node for read-only queries in `SetupUDPIFCInterconnect_Internal()`.

**Comment by ashwinstar** [comment] 2022-03-26 00:06
Also, confirmed the leak via the memory stats dump of `UdpInterconnectMemContext`

```
2022-03-25 16:47:51.628759 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd42,seg-1,,,,sx1,"LOG","00000","pid 200279: Memory statistics for /TopMemoryContext/UdpInterconnectMemContext/
",,,,,,,0,,,,
2022-03-25 16:47:51.628799 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd42,seg-1,,,,sx1,"LOG","00000","context: occurrences_count, currently_allocated, currently_available, total_allocated, total_freed, name
",,,,,,,0,,,,
2022-03-25 16:47:51.628808 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd42,seg-1,,,,sx1,"LOG","00000","context: 1, 8192, 4248, 8192, 0, .
--



2022-03-25 16:49:24.582694 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd70,seg-1,,,,,"LOG","00000","pid 200279: Memory statistics for /TopMemoryContext/UdpInterconnectMemContext/
",,,,,,,0,,,,
2022-03-25 16:49:24.582777 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd70,seg-1,,,,,"LOG","00000","context: occurrences_count, currently_allocated, currently_available, total_allocated, total_freed, name
",,,,,,,0,,,,
2022-03-25 16:49:24.582788 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd70,seg-1,,,,,"LOG","00000","context: 1, 8192, 2232, 8192, 0, .
--


2022-03-25 16:50:38.340533 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd142,seg-1,,,,,"LOG","00000","pid 200279: Memory statistics for /TopMemoryContext/UdpInterconnectMemContext/
",,,,,,,0,,,,
2022-03-25 16:50:38.340558 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd142,seg-1,,,,,"LOG","00000","context: occurrences_count, currently_allocated, currently_available, total_allocated, total_freed, name
",,,,,,,0,,,,
2022-03-25 16:50:38.340582 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd142,seg-1,,,,,"LOG","00000","context: 1, 24576, 13376, 24576, 0, .
```

**Comment by ashwinstar** [comment] 2022-03-26 00:10
As a side note interesting, for such simple command we seem to have soo much memory churn (not a leak for this other context) for "Interconnect Context"

Before the command
```
2022-03-25 16:55:01.062950 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd184,seg-1,,,,,"LOG","00000","pid 200279: Memory statistics for /TopMemoryContext/Interconnect Context/
",,,,,,,0,,,,
2022-03-25 16:55:01.063047 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd184,seg-1,,,,,"LOG","00000","context: occurrences_count, currently_allocated, currently_available, total_allocated, total_freed, name
",,,,,,,0,,,,
2022-03-25 16:55:01.063097 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd184,seg-1,,,,,"LOG","00000","context: 1, 8192, 8160, 7410856, 7402664, .
```

after the command
```
2022-03-25 16:56:10.923859 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd186,seg-1,,,,,"LOG","00000","pid 200279: Memory statistics for /TopMemoryContext/Interconnect Context/
",,,,,,,0,,,,
2022-03-25 16:56:10.923895 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd186,seg-1,,,,,"LOG","00000","context: occurrences_count, currently_allocated, currently_available, total_allocated, total_freed, name
",,,,,,,0,,,,
2022-03-25 16:56:10.923913 PDT,"ashwin","postgres",p200279,th968622720,"[local]",,2022-03-25 15:55:49 PDT,0,con9,cmd186,seg-1,,,,,"LOG","00000","context: 1, 8192, 8160, 7494032, 7485840, .
```
83176 bytes of memory allocatted and freed from/to OS (these are for demo cluster with 3 segments, not sure this number depends on number of segments / slices)

**Comment by xuebinsu** [comment] 2022-03-30 04:03
Hi, since Diskquota is affected by this issue, I will try to fix it.

**Comment by kainwen** [comment] 2022-05-17 04:41
Fixed by

(6x) https://github.com/greenplum-db/gpdb/pull/13411

and 

(master) https://github.com/greenplum-db/gpdb/pull/13355

**Closed by kainwen** 2022-05-17 04:41 UTC
Labels: type: bug, area: server, Priority 1
