### ISSUE TITLE
failed to acquire resources on one or more segments when dropping a table

### ISSUE THREAD

**Issue by flashk1021** [greenplum-db/gpdb#9549] opened 2020-02-07 18:54 UTC
### Greenplum version or build 
6.0
### OS version and uname -a
Darwin US-185278-MP.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
### Expected behavior
drop table correctly
### Actual behavior
failed with the error like
psql -d test2 -p 15432
psql (9.4.24)
Type "help" for help.

test2=# drop table tt;
ERROR:  failed to acquire resources on one or more segments
DETAIL:  FATAL:  database "test2" does not exist
DETAIL:  The database subdirectory "base/39681" is missing.
 (seg2 127.0.0.1:40002)

### Step to reproduce the behavior
1. connect to master create database test2, create table tt then quit
2. connect to one segment using utility mode and keep the connection alive
PGOPTIONS='-c gp_session_role=utility' psql -p 40001 test2
3. connect to master then drop database test2, get error like "database "test2" is being accessed by other users" which is expected
4. connect to database test2 on master, then drop table tt, got error like 
psql -d test2 -p 15432
psql (9.4.24)
Type "help" for help.

test2=# drop table tt;
ERROR:  failed to acquire resources on one or more segments
DETAIL:  FATAL:  database "test2" does not exist
DETAIL:  The database subdirectory "base/39681" is missing.
 (seg2 127.0.0.1:40002)

**Comment by ashwinstar** [comment] 2020-02-07 19:22
Interesting, thanks for reporting @flashk1021 . Yes, right now mostly upstream PostgreSQL thought process is if one was attempting to drop the database, it's not important and hence if database drop fails, attempt to drop again. Not much point working on after attempted drop failed for it. I don't agree with that stand but just stating which blocked us to fixing this issue in one sense.

I think this PR https://github.com/greenplum-db/gpdb/pull/8128 was attempting to fix this issue but was closed for stated reasons in the PR. We can revisit if required. Also just for reference this upstream discussion we had opened as part of same would be good to look at while working/fixing this issue https://www.postgresql.org/message-id/flat/CACiyaSqPp3Vuyok38QBG7HioYXF50BUHK8S6HNDT6PcRt791WA%40mail.gmail.com

**Comment by flashk1021** [comment] 2020-02-07 19:40
Thank you for the comments, Ashwin. So I guess to make it right, the only choice I have right now is to connect each segment and master in utility mode, and then drop database one by one.

**Comment by ashwinstar** [comment] 2020-02-07 19:51
I think reattempt of `drop database` still works fine via master and don't need to go to each segment in utility mode.

**Comment by flashk1021** [comment] 2020-02-07 20:08
yes you are right. Thx.

**Comment by asimrp** [comment] 2020-02-11 05:56
@flashk1021 did you observe `drop database` failure in a production deployment?  If so, does your workflow involve utility mode connections to segments?  Or did `drop database` fail due to some other reason?  I am trying to get more information because until now, my understanding was that such a failure is very rare.

**Comment by ashwinstar** [comment] 2022-02-14 20:06
I am closing this issue as works as designed, as no plan to change the same. Plus, a clear work-around exists for it.

**Closed by ashwinstar** 2022-02-14 20:06 UTC
