### ISSUE TITLE
Select for update uses PBE extended protocol will raise Error "AssignTransactionId() called by Segment Reader process (xact.c:585)"

### ISSUE THREAD

**Issue by dreamedcheng** [greenplum-db/gpdb#8365] opened 2019-08-13 08:09 UTC
### Greenplum version or build
Greenplum Database 7.0.0-alpha.0+dev.671.g38dd2da build dev

### Expected behavior
No error.

### Step to reproduce the behavior
set gp_enable_global_deadlock_detector = on;
Just use PBE extended protocol to execute a select for update.

It seems that select for update will go to reader gang. But the plan has 'lock rows' node, so it will go to the function 'heap_lock_tuple', and then try to get a trxid, which finally causes the error.

**Comment by asimrp** [comment] 2019-08-14 02:57
@dreamedcheng thank you for the report.  Could you please help us reproduce this by providing a few more details?  E.g. schema of the tables involved, what are you passing as parse (P), bind (B) and execute (E) messages?  What is the explain plan for the query?

**Comment by kainwen** [comment] 2019-08-14 03:01
> @dreamedcheng thank you for the report. Could you please help us reproduce this by providing a few more details? E.g. schema of the tables involved, what are you passing as parse (P), bind (B) and execute (E) messages? What is the explain plan for the query?

@asimrp 
This seems the same issue known by us when testing TPC-C benchmark via jdbc interface. We might take time to fix it recently.

**Comment by asimrp** [comment] 2019-08-14 06:52
Yes, thank you Zhenghua for sharing the context in-person with me.  Let me summarize what we discussed.

The problem is that extended queries are always executed in a reader gang.  When a query is submitted using parse, bind and execute messages, it is considered as extended query.  Of course, `ExecLockRows()` fails in a reader because it needs a valid transaction ID to lock a tuple.

Cursors is another type of extended query.  In the executor and dispatched, we do not distinguish a PBE extended query from a cursor and assign reader gangs for all extended queries.  It is time to question this blanket assignment of reader gangs to extended queries.  Zhenghua and team have tried executing PBE extended queries in a writer gang and things seem to work fine.

**Comment by dreamedcheng** [comment] 2019-08-14 12:15
> Yes, thank you Zhenghua for sharing the context in-person with me. Let me summarize what we discussed.
> 
> The problem is that extended queries are always executed in a reader gang. When a query is submitted using parse, bind and execute messages, it is considered as extended query. Of course, `ExecLockRows()` fails in a reader because it needs a valid transaction ID to lock a tuple.
> 
> Cursors is another type of extended query. In the executor and dispatched, we do not distinguish a PBE extended query from a cursor and assign reader gangs for all extended queries. It is time to question this blanket assignment of reader gangs to extended queries. Zhenghua and team have tried executing PBE extended queries in a writer gang and things seem to work fine.

Thanks for the reply, if a PBE select for update goes to writer gang directly, will it harm the performance? Because I think writer gang will do more things than the reader gang, such as dump shared snapshot.

**Comment by kainwen** [comment] 2019-08-15 09:18
Small reproducing steps are:

1. build gpdb cluster using lastest branch(not 6, 5, 4)
2. set GDD enabled: `gpconfig -c gp_enable_global_deadlock_detector -v on`
3. create database `gpadmin` and a user `gpadmin`
4. download postgres jdbc from https://jdbc.postgresql.org/download.html
5. run the following java test code

We will get the error message:
```
Caught SQLException
org.postgresql.util.PSQLException: ERROR: AssignTransactionId() called by Segment Reader process (xact.c:585)  (seg0 slice1 127.0.0.1:25432 pid=28082) (xact.c:585)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at JDBCTestGreenplum.performSelect(JDBCTestGreenplum.java:31)
	at JDBCTestGreenplum.main(JDBCTestGreenplum.java:11)
```

java test code is here, save it as `JDBCTestGreenplum.java`.
1. compile: `javac JDBCTestGreenplum.java`
2. run test: `java -cp "./postgresql-9.4.1212.jar:." JDBCTestGreenplum`


```java
import java.sql.*;

public class JDBCTestGreenplum {
    public static final String DRIVER = "org.postgresql.Driver";

    public static void main(String[] args) {
	String URL = "jdbc:postgresql://localhost:15432/gpadmin";
        String Q = "select * from t where c < ? for update";

        try {
            performSelect(URL, Q);
        } catch (ClassNotFoundException e) {
            System.out.println("Caught ClassNotFoundException");
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println("Caught SQLException");
            e.printStackTrace();
        }
    }

    static public void performSelect(String CONNECTION_URL, String SQL) throws SQLException, ClassNotFoundException {
        Class.forName(DRIVER);
        Connection connection = DriverManager.getConnection(CONNECTION_URL, "gpadmin", "");
        connection.setAutoCommit(false);

        try {
                PreparedStatement ps = null;
                try {
                    ps = connection.prepareStatement(SQL);
		    ps.setInt(1, 10);
                    ps.executeQuery();
                ResultSet result = ps.getResultSet();
                while ( result.next() ) {
                    System.out.print("Dumping results: ");
                    System.out.printf("%s\n",result.getInt(1));
                }

                } finally {
                    if (ps != null)
                        ps.close();
                }
        } finally {
            connection.close();
        }
    }
}
```

**Comment by dreamedcheng** [comment] 2019-08-16 06:23
Besides, when optimizer is enable (use gp orca).  Its plan is not correct, which has no node LockRows as postgres optimizer, and further leads abnormal behavior (i.e., select for update will not block an update operation on the same tuple). 

postgres=# show optimizer;
 optimizer
-----------
 on
(1 row)
postgres=# explain select * from test1 where c1 = 2 for update;
                                  QUERY PLAN
-------------------------------------------------------------------------------
 Gather Motion 1:1  (slice1; segments: 1)  (cost=0.00..431.00 rows=1 width=12)
   ->  Seq Scan on test1  (cost=0.00..431.00 rows=1 width=12)
         Filter: (c1 = 2)
 Optimizer: Pivotal Optimizer (GPORCA) version 3.63.0
(4 rows)

**Comment by kainwen** [comment] 2019-08-16 10:13
> Besides, when optimizer is enable (use gp orca). Its plan is not correct, which has no node LockRows as postgres optimizer, and further leads abnormal behavior (i.e., select for update will not block an update operation on the same tuple).
> 
> ## postgres=# show optimizer;
> optimizer
> ## on
> (1 row)
> postgres=# explain select * from test1 where c1 = 2 for update;
> QUERY PLAN
> Gather Motion 1:1 (slice1; segments: 1) (cost=0.00..431.00 rows=1 width=12)
> -> Seq Scan on test1 (cost=0.00..431.00 rows=1 width=12)
> Filter: (c1 = 2)
> Optimizer: Pivotal Optimizer (GPORCA) version 3.63.0
> (4 rows)

This has been fixed in the latest master (https://github.com/greenplum-db/gpdb/commit/0e1184414193b954dc295a8e179d250968791749). Since ORCA currently does not emit LOCKROWS plan, 
this statement will lock the whole table in ExclusiveLock mode.

**Comment by chrishajas** [comment] 2019-08-16 17:28
> > Besides, when optimizer is enable (use gp orca). Its plan is not correct, which has no node LockRows as postgres optimizer, and further leads abnormal behavior (i.e., select for update will not block an update operation on the same tuple).
> > ## postgres=# show optimizer;
> > optimizer
> > ## on
> > (1 row)
> > postgres=# explain select * from test1 where c1 = 2 for update;
> > QUERY PLAN
> > Gather Motion 1:1 (slice1; segments: 1) (cost=0.00..431.00 rows=1 width=12)
> > -> Seq Scan on test1 (cost=0.00..431.00 rows=1 width=12)
> > Filter: (c1 = 2)
> > Optimizer: Pivotal Optimizer (GPORCA) version 3.63.0
> > (4 rows)
> 
> This has been fixed in the latest master ([0e11844](https://github.com/greenplum-db/gpdb/commit/0e1184414193b954dc295a8e179d250968791749)). Since ORCA currently does not emit LOCKROWS plan,
> this statement will lock the whole table in ExclusiveLock mode.

I think we may want to just fall back to planner if the query has a `for update` clause rather than unexpectedly lock the entire table. We typically fall back to planner for features that ORCA doesn't support (for example: https://github.com/greenplum-db/gpdb/blob/master/src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp#L539).

**Comment by kainwen** [comment] 2019-08-17 13:07
> > > Besides, when optimizer is enable (use gp orca). Its plan is not correct, which has no node LockRows as postgres optimizer, and further leads abnormal behavior (i.e., select for update will not block an update operation on the same tuple).
> > > ## postgres=# show optimizer;
> > > optimizer
> > > ## on
> > > (1 row)
> > > postgres=# explain select * from test1 where c1 = 2 for update;
> > > QUERY PLAN
> > > Gather Motion 1:1 (slice1; segments: 1) (cost=0.00..431.00 rows=1 width=12)
> > > -> Seq Scan on test1 (cost=0.00..431.00 rows=1 width=12)
> > > Filter: (c1 = 2)
> > > Optimizer: Pivotal Optimizer (GPORCA) version 3.63.0
> > > (4 rows)
> > 
> > 
> > This has been fixed in the latest master ([0e11844](https://github.com/greenplum-db/gpdb/commit/0e1184414193b954dc295a8e179d250968791749)). Since ORCA currently does not emit LOCKROWS plan,
> > this statement will lock the whole table in ExclusiveLock mode.
> 
> I think we may want to just fall back to planner if the query has a `for update` clause rather than unexpectedly lock the entire table. We typically fall back to planner for features that ORCA doesn't support (for example: https://github.com/greenplum-db/gpdb/blob/master/src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp#L539).

Good idea. I will try to improve this.

**Comment by kainwen** [comment] 2019-09-05 07:47
I open a new PR for this issue. Please have a look. Thanks!

@dreamedcheng @asimrp

**Closed** 2019-09-11 06:33 UTC
Labels: type: bug

**Comment by kainwen** [comment] 2019-09-11 06:35
This PR https://github.com/greenplum-db/gpdb/pull/8565 is merged into master.

This issue should be fixed.

Feel free to open it or new issue if has any problems. Thanks.

**Comment by xiaozhongwang** [comment] 2022-05-01 01:18
I try to test this, the error is fixed by PR https://github.com/greenplum-db/gpdb/pull/8565, but the PR will cause the select for update statement execute via serialize

**Comment by xiaozhongwang** [comment] 2022-05-01 01:22
I also did some research on this issue and I found that the fix will cause the select for update statement to execute serially. But the same statement, if I execute it in psql, there is no problem, it means that GP can support such statement, but why should it be all serialized when the E message of JDBC is executed? Doing so directly tunes the TP performance to almost unscalable.

**Comment by kainwen** [comment] 2022-05-01 01:43
> I also did some research on this issue and I found that the fix will cause the select for update statement to execute serially. But the same statement, if I execute it in psql, there is no problem, it means that GP can support such statement, but why should it be all serialized when the E message of JDBC is executed? Doing so directly tunes the TP performance to almost unscalable.

Hi @xiaozhongwang 

Some background can be found in the thread https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/ugsZca1qLXU/m/CtUmzEa7CAAJ

In summary:

First, Greenplum has the concept of writer gang and reader gang, for any single session, **there is and only is a writer gang, and always be the first gang**
  
Second, cursors are async queries in a session, and currently **can only be executed by reader gangs**. Think of the following SQLs:

```sql
begin;
declare cur as select * from t; -- backgroup, async, non-block
delete from xxx; -- must be writer, doing delete
fetch cur; -- access cursor again
```

Third, extended protocol query is just cursor and can only be executed using reader gangs. But select statement with locking clause need to generate a transaction id and write this xid to tuples to lock the tuple (this kind of operation now can only be executed by writer gang).  That is why, in a cursor's `select for update` Greenplum lock the hold table now.

Last, when you run in `psql`, it is not extended protocol query and is not cursor, Greenplum can optimize some simple case:
1. not replicated table
2. gdd is enabled
3. no sublink
4. only one table in the from clause
5. orca is off

----------------

It would be a huge topic to refactor Greenplum's writer and reader architecture to support `for update` on reader.
