### ISSUE TITLE
Cluster hang after stop one segment host

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#11147] opened 2020-11-12 09:12 UTC
### Greenplum version or build

- GP: 5.28.1

### OS version and uname -a

- Docker Container: Centos7
- Docker Host: Linux mdw 4.15.0-117-generic # 118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

When I execute the command `gpstop --host sdw4` to temporarily stop a node, all running requests will fail, but afterwards new SQL requests can be executed normally.

### Actual behavior

All SQLs were blocked during the operation. After investigating the root cause, it was found that only the operation on the master node have not be completed, the process on the segment host had actually stopped. I do not know why the operation is blocked.

The large amount of congestion also directly affects the operations of all non-administrators, because the resource queue is limited.

![2020-11-12 16-32-26屏幕截图](https://user-images.githubusercontent.com/11460848/98919733-283e3c00-250a-11eb-9fca-5de6b6dbcdc8.png)

**Comment by cobolbaby** [comment] 2020-11-12 09:17
I need to stop the greenplum using `gpstop -a`, and then restart it to recover the greenplum. This is really a terrible bug.

**Comment by cobolbaby** [comment] 2020-11-19 07:00
I have confirmed that the root cause of the above phenomenon is the DNS resolution problem. 

But I would like to ask, why does greenplus need to resolve the address when the stopped node no longer provides services?

**Comment by ashwinstar** [comment] 2021-02-20 01:56
@Nirali13 please can someone from team look into this and answer the question

**Comment by divyeshddv** [comment] 2021-03-24 21:45
@ashwinstar @Nirali13 @asimrp 
We weren't able to reproduce this locally. But looking into the issue, it seems to not be related to gpstop, but instead to server internals. For `gpstop --host sdw4` executed during long running queries, master still has hanging processes but segments end those. This isn't related to gpstop since the same would have occurred if the host would have gone down normally.

**Comment by lij55** [comment] 2022-02-14 16:15
> If you specify a hostname, the resolution of the hostname to an IP address should be done locally for security. For example, you should use entries in a local /etc/hosts file to map a hostname to an IP address. The resolution of a hostname to an IP address should not be performed by an external service such as a public DNS server. 

This is from the Greenplum doc: https://gpdb.docs.pivotal.io/6-19/utility_guide/ref/gpinitsystem.html (search Specifying Hosts using Hostnames or IP Addresses).
The reason is that it is hostname that is used in gpinitsystem and gp_segment_configuration. In order to check the peer status through TPC/IP protocol, QD/master have to do the name resolving from hostname.

**Closed by lij55** 2022-02-14 16:15 UTC

**Comment by cobolbaby** [comment] 2022-02-15 01:34
For Greenplum deployed on physical machines or VMs, The resolution of a hostname to an IP address is indeed beyond doubt.
However, for the container deployment method, the communication between nodes needs to rely on the service discovery mechanism of k8s or swarm, and because the IP is not fixed, it is not suitable to configure /etc/hosts. If a node is down, the address cannot be resolved. In response to this situation, what should Greenplum do?

Please reopen this issue, thanks.
