### ISSUE TITLE
Assert in GPORCA due to PG exception raised after EC Merge

### ISSUE THREAD

**Issue by xinzweb** [greenplum-db/gpdb#364] opened 2016-02-12 16:57 UTC
@atris looked into the issue and found the following:
Repro:
```
drop table if exists r;
drop table if exists p;
create table r (a int, b int) distributed by (a);
create table p (a int, b int, c int)
distributed by (a)
partition by range (c) (start(1) end(5) every(1), default partition extra);
insert into r select generate_series(1, 10000), generate_series(1, 10000)%3;
insert into p select generate_series(1, 1000), generate_series(1, 1000)%3, generate_series(1, 1000)%6;

set optimizer=on;
set client_min_messages='log';
explain delete from p where c = 3 and a in (select b from r);
```
The problem is that there should be `Explicit Redistribute Motion` nodes on top of ALL the `HashAggregate` nodes in the below plan:
```
LOG:  statement: explain delete from p where c = 3 and a in (select b from r);
LOG:  2016-02-12 08:45:53:382809 PST,THD000,ERROR,"PG exception raised",
LOG:  Planner produced plan :0
                                                     QUERY PLAN
---------------------------------------------------------------------------------------------------------------------
 Delete (slice0; segments: 3)  (rows=23 width=20)
   ->  Append  (cost=148.11..708.48 rows=23 width=20)
         ->  Explicit Redistribute Motion 3:3  (slice2; segments: 3)  (cost=148.11..148.24 rows=5 width=20)
               ->  HashAggregate  (cost=148.11..148.24 rows=5 width=20)
                     Group By: public.p.ctid::bigint, public.p.gp_segment_id
                     ->  Hash Join  (cost=10.81..148.04 rows=5 width=20)
                           Hash Cond: r.b = public.p.a
                           ->  Seq Scan on r  (cost=0.00..112.00 rows=3334 width=4)
                           ->  Hash  (cost=10.78..10.78 rows=1 width=14)
                                 ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..10.78 rows=1 width=14)
                                       ->  Seq Scan on p_1_prt_extra p  (cost=0.00..10.74 rows=1 width=14)
                                             Filter: c = 3
         ->  HashAggregate  (cost=137.20..137.33 rows=5 width=20)
               Group By: public.p.ctid::bigint, public.p.gp_subplan_id
               ->  Hash Join  (cost=0.00..137.14 rows=5 width=20)
                     Hash Cond: r.b = public.p.a
                     ->  Seq Scan on r  (cost=0.00..112.00 rows=3334 width=4)
                     ->  Hash  (cost=0.01..0.01 rows=1 width=0)
                           ->  Result  (cost=0.00..0.01 rows=1 width=0)
                                 One-Time Filter: false
         ->  HashAggregate  (cost=137.20..137.33 rows=5 width=20)
               Group By: public.p.ctid::bigint, public.p.gp_subplan_id
               ->  Hash Join  (cost=0.00..137.14 rows=5 width=20)
                     Hash Cond: r.b = public.p.a
                     ->  Seq Scan on r  (cost=0.00..112.00 rows=3334 width=4)
                     ->  Hash  (cost=0.01..0.01 rows=1 width=0)
                           ->  Result  (cost=0.00..0.01 rows=1 width=0)
                                 One-Time Filter: false
         ->  Explicit Redistribute Motion 3:3  (slice4; segments: 3)  (cost=148.11..148.24 rows=5 width=20)
               ->  HashAggregate  (cost=148.11..148.24 rows=5 width=20)
                     Group By: public.p.ctid::bigint, public.p.gp_segment_id
                     ->  Hash Join  (cost=10.81..148.04 rows=5 width=20)
                           Hash Cond: r.b = public.p.a
                           ->  Seq Scan on r  (cost=0.00..112.00 rows=3334 width=4)
                           ->  Hash  (cost=10.78..10.78 rows=1 width=14)
                                 ->  Broadcast Motion 3:3  (slice3; segments: 3)  (cost=0.00..10.78 rows=1 width=14)
                                       ->  Seq Scan on p_1_prt_4 p  (cost=0.00..10.74 rows=1 width=14)
                                             Filter: c = 3
         ->  HashAggregate  (cost=137.20..137.33 rows=5 width=20)
               Group By: public.p.ctid::bigint, public.p.gp_subplan_id
               ->  Hash Join  (cost=0.00..137.14 rows=5 width=20)
                     Hash Cond: r.b = public.p.a
                     ->  Seq Scan on r  (cost=0.00..112.00 rows=3334 width=4)
                     ->  Hash  (cost=0.01..0.01 rows=1 width=0)
                           ->  Result  (cost=0.00..0.01 rows=1 width=0)
                                 One-Time Filter: false
 Optimizer status: legacy query optimizer
(47 rows)
```
The `Explicit Redistribute Motion` nodes are not being added and the Assertion is only seeing `HashAggregate` nodes when expecting `Explicit Redistribute Motion` nodes hence it trips assertion. @atris got the above plan by removing the assertion.

The problem is induced in the equivalence class (EC) merge patch since @atris  tested moving one commit back and testing the same and it works fine. 

Plan for pre EC merge patch for same query:
```
Delete (slice0; segments: 3) (rows=23 width=20)
-> Append (cost=148.29..709.63 rows=23 width=20)
-> Explicit Redistribute Motion 3:3 (slice3; segments: 3) (cost=148.29..148.42 rows=5 width=20)
-> HashAggregate (cost=148.29..148.42 rows=5 width=20)
Group By: public.p.ctid::bigint, public.p.gp_segment_id
-> Result (cost=10.81..148.22 rows=5 width=20)
-> Redistribute Motion 3:3 (slice2; segments: 3) (cost=10.81..148.22 rows=5 width=20)
Hash Key: public.p.ctid
-> Hash Join (cost=10.81..147.96 rows=5 width=20)
Hash Cond: r.b = public.p.a
-> Seq Scan on r (cost=0.00..112.00 rows=3334 width=4)
-> Hash (cost=10.78..10.78 rows=1 width=14)
-> Broadcast Motion 3:3 (slice1; segments: 3) (cost=0.00..10.78 rows=1 width=14)
-> Seq Scan on p_1_prt_extra p (cost=0.00..10.74 rows=1 width=14)
Filter: c = 3
-> Explicit Redistribute Motion 3:3 (slice5; segments: 3) (cost=137.47..137.60 rows=5 width=20)
-> HashAggregate (cost=137.47..137.60 rows=5 width=20)
Group By: public.p.ctid::bigint, public.p.gp_subplan_id
-> Result (cost=0.00..137.40 rows=5 width=20)
-> Redistribute Motion 3:3 (slice4; segments: 3) (cost=0.00..137.40 rows=5 width=20)
Hash Key: public.p.ctid
-> Hash Join (cost=0.00..137.14 rows=5 width=20)
Hash Cond: r.b = public.p.a
-> Seq Scan on r (cost=0.00..112.00 rows=3334 width=4)
-> Hash (cost=0.01..0.01 rows=1 width=0)
-> Result (cost=0.00..0.01 rows=1 width=0)
One-Time Filter: false
-> Explicit Redistribute Motion 3:3 (slice7; segments: 3) (cost=137.47..137.60 rows=5 width=20)
-> HashAggregate (cost=137.47..137.60 rows=5 width=20)
Group By: public.p.ctid::bigint, public.p.gp_subplan_id
-> Result (cost=0.00..137.40 rows=5 width=20)
-> Redistribute Motion 3:3 (slice6; segments: 3) (cost=0.00..137.40 rows=5 width=20)
Hash Key: public.p.ctid
-> Hash Join (cost=0.00..137.14 rows=5 width=20)
Hash Cond: r.b = public.p.a
-> Seq Scan on r (cost=0.00..112.00 rows=3334 width=4)
-> Hash (cost=0.01..0.01 rows=1 width=0)
-> Result (cost=0.00..0.01 rows=1 width=0)
One-Time Filter: false
-> Explicit Redistribute Motion 3:3 (slice10; segments: 3) (cost=148.29..148.42 rows=5 width=20)
-> HashAggregate (cost=148.29..148.42 rows=5 width=20)
Group By: public.p.ctid::bigint, public.p.gp_segment_id
-> Result (cost=10.81..148.22 rows=5 width=20)
-> Redistribute Motion 3:3 (slice9; segments: 3) (cost=10.81..148.22 rows=5 width=20)
Hash Key: public.p.ctid
-> Hash Join (cost=10.81..147.96 rows=5 width=20)
Hash Cond: r.b = public.p.a
-> Seq Scan on r (cost=0.00..112.00 rows=3334 width=4)
-> Hash (cost=10.78..10.78 rows=1 width=14)
-> Broadcast Motion 3:3 (slice8; segments: 3) (cost=0.00..10.78 rows=1 width=14)
-> Seq Scan on p_1_prt_4 p (cost=0.00..10.74 rows=1 width=14)
Filter: c = 3
-> Explicit Redistribute Motion 3:3 (slice12; segments: 3) (cost=137.47..137.60 rows=5 width=20)
-> HashAggregate (cost=137.47..137.60 rows=5 width=20)
Group By: public.p.ctid::bigint, public.p.gp_subplan_id
-> Result (cost=0.00..137.40 rows=5 width=20)
-> Redistribute Motion 3:3 (slice11; segments: 3) (cost=0.00..137.40 rows=5 width=20)
Hash Key: public.p.ctid
-> Hash Join (cost=0.00..137.14 rows=5 width=20)
Hash Cond: r.b = public.p.a
-> Seq Scan on r (cost=0.00..112.00 rows=3334 width=4)
-> Hash (cost=0.01..0.01 rows=1 width=0)
-> Result (cost=0.00..0.01 rows=1 width=0)
One-Time Filter: false
```

@hlinnaka, would you please take a look?

**Comment by hlinnaka** [comment] 2016-02-13 12:44
This is a duplicate of issue #332. As I said there, I believe the new plan is correct, and the assertion is too tight. If you think the Explicit Redistribute Motion are really needed, please leave a comment on #332.

**Closed by hlinnaka** 2016-02-13 12:44 UTC
