### ISSUE TITLE
SIGSEGV occur WHEN exec query

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#10523] opened 2020-07-28 13:08 UTC
### Greenplum version or build
greenplum 6.4
### OS version and uname -a
Linux server100 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
### Installation information ( pg_config )
[gpadmin_bn@server100 pg_log]$ pg_config
BINDIR = /home/gpadmin_bn/greenplum-db-6.4.0/bin
DOCDIR = /home/gpadmin_bn/greenplum-db-6.4.0/share/doc/postgresql
HTMLDIR = /home/gpadmin_bn/greenplum-db-6.4.0/share/doc/postgresql
INCLUDEDIR = /home/gpadmin_bn/greenplum-db-6.4.0/include
PKGINCLUDEDIR = /home/gpadmin_bn/greenplum-db-6.4.0/include/postgresql
INCLUDEDIR-SERVER = /home/gpadmin_bn/greenplum-db-6.4.0/include/postgresql/server
LIBDIR = /home/gpadmin_bn/greenplum-db-6.4.0/lib
PKGLIBDIR = /home/gpadmin_bn/greenplum-db-6.4.0/lib/postgresql
LOCALEDIR = /home/gpadmin_bn/greenplum-db-6.4.0/share/locale
MANDIR = /home/gpadmin_bn/greenplum-db-6.4.0/share/man
SHAREDIR = /home/gpadmin_bn/greenplum-db-6.4.0/share/postgresql
SYSCONFDIR = /home/gpadmin_bn/greenplum-db-6.4.0/etc/postgresql
PGXS = /home/gpadmin_bn/greenplum-db-6.4.0/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--prefix=/root/greenplum-db-6.4.0' '--enable-gpperfmon' '--with-python' '--with-perl' '--with-libxml' '--with-openssl' '--with-wal-segsize=64' '--enable-debug' 'CFLAGS=-g -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2 -I/home/gpadmin_bn/greenplum-db-6.4.0/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -ggdb -g -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -std=gnu99 -Werror=implicit-function-declaration -I/home/gpadmin_bn/greenplum-db-6.4.0/include
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/root/greenplum-db-6.4.0/lib',--enable-new-dtags -L/home/gpadmin_bn/greenplum-db-6.4.0/lib
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lgpopt -lnaucrates -lgpdbcost -lgpos -lxerces-c -lxml2 -lrt -lzstd -lrt -lcrypt -ldl -lm -L/home/gpadmin_bn/greenplum-db-6.4.0/lib
VERSION = PostgreSQL 9.4.24

### Expected behavior
exec the below sql,exected successfully executed:
```
 select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='核心层' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;
```
query's plan is below:
```
postgres=# explain select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='核心层' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;
                                                                                  QUERY PLAN                                                             
                      
---------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------
 Result  (cost=0.00..1545854.30 rows=1 width=8)
   ->  Aggregate  (cost=0.00..1545854.30 rows=1 width=8)
         ->  Gather Motion 9:1  (slice5; segments: 9)  (cost=0.00..1545854.30 rows=1 width=8)
               ->  Aggregate  (cost=0.00..1545854.30 rows=1 width=8)
                     ->  Hash Join  (cost=0.00..1545854.30 rows=18 width=8)
                           Hash Cond: (t_npa_moc_pd_ctn_link_d_2020_07.noid = t_npa_ctn_moc_link.noid)
                           ->  Nested Loop  (cost=0.00..1545421.56 rows=2145 width=16)
                                 Join Filter: ((t_npa_moc_pd_ctn_link_d_2020_07.datacolumn21)::numeric >= (((t_npa_calculator_config_1.cfgvalue)::numeric
 * 10000::numeric)))
                                 ->  Assert  (cost=0.00..431.01 rows=1 width=8)
                                       Assert Cond: ((row_number() OVER (?)) = 1)
                                       ->  Broadcast Motion 1:9  (slice4)  (cost=0.00..431.01 rows=9 width=16)
                                             ->  Result  (cost=0.00..431.01 rows=1 width=16)
                                                   ->  WindowAgg  (cost=0.00..431.01 rows=1 width=16)
                                                         ->  Result  (cost=0.00..431.01 rows=1 width=8)
                                                               ->  Gather Motion 9:1  (slice3; segments: 9)  (cost=0.00..431.01 rows=1 width=5)
                                                                     ->  Seq Scan on t_npa_calculator_config t_npa_calculator_config_1  (cost=0.00..431.0
1 rows=1 width=5)
                                                                           Filter: (((cfgcode)::text = 'CORELINK_MAX_BWUTIL_L'::text) AND (professionid =
 1))
                                 ->  Nested Loop  (cost=0.00..646.81 rows=2145 width=24)
                                       Join Filter: true
                                       ->  Materialize  (cost=0.00..431.01 rows=1 width=8)
                                             ->  Assert  (cost=0.00..431.01 rows=1 width=8)
                                                   Assert Cond: ((row_number() OVER (?)) = 1)
                                                   ->  Broadcast Motion 1:9  (slice2)  (cost=0.00..431.01 rows=9 width=16)
                                                         ->  Result  (cost=0.00..431.01 rows=1 width=16)
                                                               ->  WindowAgg  (cost=0.00..431.01 rows=1 width=16)
                                                                     ->  Result  (cost=0.00..431.01 rows=1 width=8)
                                                                           ->  Gather Motion 9:1  (slice1; segments: 9)  (cost=0.00..431.01 rows=1 width=
5)
                                                                                 ->  Seq Scan on t_npa_calculator_config  (cost=0.00..431.01 rows=1 width
=5)
                                                                                       Filter: (((cfgcode)::text = 'CORELINK_BUSY_AVG_BWUTIL_L'::text) AN
D (professionid = 1))
                                       ->  Bitmap Heap Scan on t_npa_moc_pd_ctn_link_d_2020_07  (cost=0.00..215.62 rows=2145 width=24)
                                             Recheck Cond: (timeint = 27)
                                             Filter: ((datacolumn24)::numeric >= (((t_npa_calculator_config.cfgvalue)::numeric * 10000::numeric)))
                                             ->  Bitmap Index Scan on ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid  (cost=0.00..0.00 rows=0 width=0)
                                                   Index Cond: (timeint = 27)
                           ->  Hash  (cost=432.35..432.35 rows=18 width=8)
                                 ->  Seq Scan on t_npa_ctn_moc_link  (cost=0.00..432.35 rows=18 width=8)
                                       Filter: ((column_28)::text = '核心层'::text)
 Optimizer: Pivotal Optimizer (GPORCA) version 3.88.1
(38 rows)

```

What confused me is that the param enable_nestloop is off by default but I still can see Nested Loop in the plan above?
It is that matters?

### Actual behavior

SIGSEGV occured:
```
2020-07-28 20:53:12.638982 EDT,,,p3648,th0,,,2020-07-28 20:53:12 EDT,0,con35,cmd208,seg0,slice5,,,,"PANIC","XX000","Unexpected internal error: Segment process received signal SIGSEGV",,,,,,,0,,,,"1    0xaab17c postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread (elog.c:5577)
2    0x94880f postgres CdbProgramErrorHandler (postgres.c:3556)
3    0x7efcfed595f0 libpthread.so.0 <symbol not found> + 0xfed595f0
4    0x757d2a postgres <symbol not found> (execScan.c:85)
5    0x757e5a postgres ExecScan (execScan.c:154)
6    0x76862d postgres ExecBitmapHeapScan (nodeBitmapHeapscan.c:853)
7    0x74aa5b postgres ExecProcNode (execProcnode.c:1027)
8    0x77a6bf postgres <symbol not found> (nodeNestloop.c:223)
9    0x77a996 postgres ExecNestLoop (nodeNestloop.c:352)
10   0x74ab2d postgres ExecProcNode (execProcnode.c:1070)
11   0x77a6bf postgres <symbol not found> (nodeNestloop.c:223)
12   0x77a996 postgres ExecNestLoop (nodeNestloop.c:352)
13   0x74ab2d postgres ExecProcNode (execProcnode.c:1070)
14   0x76de3e postgres <symbol not found> (nodeHashjoin.c:812)
15   0x76d0af postgres <symbol not found> (nodeHashjoin.c:282)
16   0x76d70c postgres ExecHashJoin (nodeHashjoin.c:509)
17   0x74ab57 postgres ExecProcNode (execProcnode.c:1078)
18   0x763b77 postgres <symbol not found> (nodeAgg.c:1332)
19   0x763917 postgres ExecAgg (nodeAgg.c:1220)
20   0x74ab96 postgres ExecProcNode (execProcnode.c:1093)
21   0x7916db postgres <symbol not found> (nodeMotion.c:295)
22   0x791644 postgres ExecMotion (nodeMotion.c:252)
23   0x74ac29 postgres ExecProcNode (execProcnode.c:1121)
24   0x74597b postgres <symbol not found> (execMain.c:2965)
25   0x7427ee postgres standard_ExecutorRun (execMain.c:935)
26   0x7425a9 postgres ExecutorRun (execMain.c:819)
27   0x94d704 postgres <symbol not found> (pquery.c:1152)
28   0x94d3ba postgres PortalRun (pquery.c:992)
29   0x9450e5 postgres <symbol not found> (postgres.c:1377)
30   0x94af1e postgres PostgresMain (postgres.c:5409)
31   0x8cada5 postgres <symbol not found> (postmaster.c:5434)
32   0x8ca476 postgres <symbol not found> (postmaster.c:4464)
"
2020-07-28 20:53:12.639274 EDT,,,p29565,th34830464,,,,0,,,seg0,,,,,"LOG","00000","server process (PID 3648) was terminated by signal 11: Segmentation fault","Failed process was running: select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='?????????' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;",,,,,,0,,"postmaster.c",3962,
2020-07-28 20:53:12.639323 EDT,,,p29565,th34830464,,,,0,,,seg0,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",3679,
```

### Step to reproduce the behavior
execute the SQL above

**Comment by kainwen** [comment] 2020-07-28 13:14
From the core stack, it is very similar to an issue that already fixed by the commit https://github.com/greenplum-db/gpdb/commit/cb5d18d112c229736b6b97683ea57d5ba80b24db

The similar issue is: https://github.com/greenplum-db/gpdb/issues/10398

@JunfengYang Can you please verify if they are the same issue?

**Comment by LittleWuCoding** [comment] 2020-07-28 13:27
just now ,I try to close the  orca by set optimizer to off and execute the query successfully,
Maybe it is related to orca, below is the plan by close orca:
```
postgres=# explain select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='核心层' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;
                                                                QUERY PLAN                                                                 
-------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=3602.48..3602.50 rows=1 width=32)
   InitPlan 1 (returns $0)  (slice4)
     ->  Gather Motion 9:1  (slice2; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
           ->  Seq Scan on t_npa_calculator_config  (cost=0.00..15.65 rows=1 width=5)
                 Filter: (((cfgcode)::text = 'CORELINK_BUSY_AVG_BWUTIL_L'::text) AND (professionid = 1))
   InitPlan 2 (returns $1)  (slice5)
     ->  Gather Motion 9:1  (slice3; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
           ->  Seq Scan on t_npa_calculator_config t_npa_calculator_config_1  (cost=0.00..15.65 rows=1 width=5)
                 Filter: (((cfgcode)::text = 'CORELINK_MAX_BWUTIL_L'::text) AND (professionid = 1))
   ->  Gather Motion 9:1  (slice1; segments: 9)  (cost=3571.05..3571.16 rows=1 width=32)
         ->  Aggregate  (cost=3571.05..3571.06 rows=1 width=32)
               ->  Hash Join  (cost=1350.07..3570.89 rows=7 width=8)
                     Hash Cond: (a.noid = b.noid)
                     ->  Bitmap Heap Scan on t_npa_moc_pd_ctn_link_d_2020_07 a  (cost=446.85..2638.07 rows=859 width=16)
                           Recheck Cond: (timeint = 27)
                           Filter: (((datacolumn24)::numeric >= $0) AND ((datacolumn21)::numeric >= $1))
                           ->  Bitmap Index Scan on ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid  (cost=0.00..444.92 rows=2145 width=0)
                                 Index Cond: (timeint = 27)
                     ->  Hash  (cost=901.26..901.26 rows=18 width=8)
                           ->  Seq Scan on t_npa_ctn_moc_link b  (cost=0.00..901.26 rows=18 width=8)
                                 Filter: ((column_28)::text = '核心层'::text)
 Optimizer: Postgres query optimizer
(22 rows)
```

**Comment by kainwen** [comment] 2020-07-28 13:37
> just now ,I try to close the orca by set optimizer to off and execute the query successfully,
> Maybe it is related to orca, below is the plan by close orca:
> 
> ```
> postgres=# explain select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='核心层' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;
>                                                                 QUERY PLAN                                                                 
> -------------------------------------------------------------------------------------------------------------------------------------------
>  Aggregate  (cost=3602.48..3602.50 rows=1 width=32)
>    InitPlan 1 (returns $0)  (slice4)
>      ->  Gather Motion 9:1  (slice2; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
>            ->  Seq Scan on t_npa_calculator_config  (cost=0.00..15.65 rows=1 width=5)
>                  Filter: (((cfgcode)::text = 'CORELINK_BUSY_AVG_BWUTIL_L'::text) AND (professionid = 1))
>    InitPlan 2 (returns $1)  (slice5)
>      ->  Gather Motion 9:1  (slice3; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
>            ->  Seq Scan on t_npa_calculator_config t_npa_calculator_config_1  (cost=0.00..15.65 rows=1 width=5)
>                  Filter: (((cfgcode)::text = 'CORELINK_MAX_BWUTIL_L'::text) AND (professionid = 1))
>    ->  Gather Motion 9:1  (slice1; segments: 9)  (cost=3571.05..3571.16 rows=1 width=32)
>          ->  Aggregate  (cost=3571.05..3571.06 rows=1 width=32)
>                ->  Hash Join  (cost=1350.07..3570.89 rows=7 width=8)
>                      Hash Cond: (a.noid = b.noid)
>                      ->  Bitmap Heap Scan on t_npa_moc_pd_ctn_link_d_2020_07 a  (cost=446.85..2638.07 rows=859 width=16)
>                            Recheck Cond: (timeint = 27)
>                            Filter: (((datacolumn24)::numeric >= $0) AND ((datacolumn21)::numeric >= $1))
>                            ->  Bitmap Index Scan on ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid  (cost=0.00..444.92 rows=2145 width=0)
>                                  Index Cond: (timeint = 27)
>                      ->  Hash  (cost=901.26..901.26 rows=18 width=8)
>                            ->  Seq Scan on t_npa_ctn_moc_link b  (cost=0.00..901.26 rows=18 width=8)
>                                  Filter: ((column_28)::text = '核心层'::text)
>  Optimizer: Postgres query optimizer
> (22 rows)
> ```

NO, the plan is different.

If my previous reply is correct, the bug happens for nestloop join and bitmap scan.

**Comment by LittleWuCoding** [comment] 2020-07-28 13:48
> > just now ,I try to close the orca by set optimizer to off and execute the query successfully,
> > Maybe it is related to orca, below is the plan by close orca:
> > ```
> > postgres=# explain select  CONCAT(round(avg(A.DataColumn24)/10000,2), '%') from T_NPA_MOC_PD_CTN_LINK_D_2020_07 A , T_NPA_CTN_MOC_LINK B where A.NOID = B.NOID and B.Column_28='核心层' and A.DataColumn24 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_BUSY_AVG_BWUTIL_L' and ProfessionID=1) and A.DataColumn21 >= (select cast(CfgValue as numeric)*10000 from T_NPA_Calculator_Config where CfgCode='CORELINK_MAX_BWUTIL_L' and ProfessionID=1) and  A.TimeInt=27;
> >                                                                 QUERY PLAN                                                                 
> > -------------------------------------------------------------------------------------------------------------------------------------------
> >  Aggregate  (cost=3602.48..3602.50 rows=1 width=32)
> >    InitPlan 1 (returns $0)  (slice4)
> >      ->  Gather Motion 9:1  (slice2; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
> >            ->  Seq Scan on t_npa_calculator_config  (cost=0.00..15.65 rows=1 width=5)
> >                  Filter: (((cfgcode)::text = 'CORELINK_BUSY_AVG_BWUTIL_L'::text) AND (professionid = 1))
> >    InitPlan 2 (returns $1)  (slice5)
> >      ->  Gather Motion 9:1  (slice3; segments: 9)  (cost=0.00..15.65 rows=1 width=5)
> >            ->  Seq Scan on t_npa_calculator_config t_npa_calculator_config_1  (cost=0.00..15.65 rows=1 width=5)
> >                  Filter: (((cfgcode)::text = 'CORELINK_MAX_BWUTIL_L'::text) AND (professionid = 1))
> >    ->  Gather Motion 9:1  (slice1; segments: 9)  (cost=3571.05..3571.16 rows=1 width=32)
> >          ->  Aggregate  (cost=3571.05..3571.06 rows=1 width=32)
> >                ->  Hash Join  (cost=1350.07..3570.89 rows=7 width=8)
> >                      Hash Cond: (a.noid = b.noid)
> >                      ->  Bitmap Heap Scan on t_npa_moc_pd_ctn_link_d_2020_07 a  (cost=446.85..2638.07 rows=859 width=16)
> >                            Recheck Cond: (timeint = 27)
> >                            Filter: (((datacolumn24)::numeric >= $0) AND ((datacolumn21)::numeric >= $1))
> >                            ->  Bitmap Index Scan on ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid  (cost=0.00..444.92 rows=2145 width=0)
> >                                  Index Cond: (timeint = 27)
> >                      ->  Hash  (cost=901.26..901.26 rows=18 width=8)
> >                            ->  Seq Scan on t_npa_ctn_moc_link b  (cost=0.00..901.26 rows=18 width=8)
> >                                  Filter: ((column_28)::text = '核心层'::text)
> >  Optimizer: Postgres query optimizer
> > (22 rows)
> > ```
> 
> NO, the plan is different.
> 
> If my previous reply is correct, the bug happens for nestloop join and bitmap scan.

Yes, I also thinks it is related to nestloop, I mean the orca make it go with netloop.

**Comment by vraghavan78** [comment] 2020-07-28 18:36
@kainwen if this is an Orca issue please assign it to me. The Orca plan loop looks ok to me.

**Comment by kainwen** [comment] 2020-07-29 00:30
> @kainwen if this is an Orca issue please assign it to me. The Orca plan loop looks ok to me.

I think it is not ORCA issue. The plan is good.

It should be the executor of nestloop forget to reset some pointer.

**Comment by JunfengYang** [comment] 2020-07-29 07:23
Is `ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid ` an append only table?
If yes, it may be related to https://github.com/greenplum-db/gpdb/issues/10398.

**Comment by LittleWuCoding** [comment] 2020-07-29 07:25
> Is `ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid ` an append only table?
> If yes, it may be related to #10398.

yes, this table is an AO table

**Comment by asimrp** [comment] 2020-07-29 07:29
@kainwen this may not be related to issue #10398.  That issue was specific to append-optimized tables.  See this comment from the PR: https://github.com/greenplum-db/gpdb/pull/10407#issuecomment-654038590.

**Comment by JunfengYang** [comment] 2020-07-29 07:40
@LittleWuCoding This should be fixed on 6X_STABLE branch. Please verify if you can build this branch.

@asimrp since `ix_t_npa_moc_pd_ctn_link_d_2020_07_timeint_noid ` is the the ao table, it's highly related.
The previous issue happens for nest_loop semi-join.

**Comment by JunfengYang** [comment] 2020-07-30 02:04
The cause for issue #10398 is, there still data in the current bitmap page for the Bitmap Index Scan.
And then a rescan is issued. Since some of the states in Bitmap Index Scan for AO/AOCS table get reset,
but not known in `BitmapAppendOnlyNext`. So semi-join will trigger this issue since it only read one tuple
from Bitmap Index Scan for each outer tuple.

 But for this nest-loop join, @kainwen is it possible the inner Bitmap Index Scan execute rescan before scanning all tuples?

**Comment by asimrp** [comment] 2021-06-03 06:32
@LittleWuCoding I don't think this problem is resolved.  Do you mind sharing the reason for closing this issue?

**Comment by kainwen** [comment] 2022-02-17 11:03
I feel strongly this is fixed by the above-mentioned pr. No response for a long time. Close it. Feel free to re-open if needed.

**Closed by kainwen** 2022-02-17 11:03 UTC
Labels: area: server, version: 6X_STABLE
