### ISSUE TITLE
gp_fts_probe_interval not works

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpdb#13904] opened 2022-08-04 05:17 UTC
### Greenplum version or build

- 6.20.5

### Actual behavior

- $MASTER_DATA_DIRECTORY/pg_log

The retry interval is actually 1s, not 1min

```csv
2022-08-04 11:17:51.848611 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""50000"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.851351 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""50000"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.854082 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""50001"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.856926 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""50001"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.859457 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""40000"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.862221 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""40000"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.862245 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","08006","cannot resolve network address for dbid=4",,,,,,,0,,"cdbutil.c",388,
2022-08-04 11:17:51.864919 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""40001"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.867719 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","could not translate host name ""gp6sdw2"", port ""40001"" to address: Name or service not known",,,,,,,0,,"cdbutil.c",1200,
2022-08-04 11:17:51.867738 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,sx1,"LOG","08006","cannot resolve network ddress for dbid=5",,,,,,,0,,"cdbutil.c",388,
2022-08-04 11:17:51.868303 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:51.868411 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:52.005336 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:52.005420 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:53.005321 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:53.005404 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:54.005312 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:54.005478 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:55.005339 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:55.005420 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:56.006035 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=2, dbid=4): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:56.007092 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: cannot establish libpq connection to (content=3, dbid=5): could not translate host name ""(null)"" to address: Name or service not known",,,,,,,0,,"ftsprobe.c",182,
2022-08-04 11:17:56.007114 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS max (5) retries exhausted (content=2, dbid=4) state=9",,,,,,,0,,"ftsprobe.c",788,
2022-08-04 11:17:56.007120 CST,,,p402,th-1152419712,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS max (5) retries exhausted (content=3, dbid=5) state=9",,,,,,,0,,"ftsprobe.c",788,
```

- gpconfig

```bash
[gpadmin@gp6mdw pg_log]$ gpconfig -s gp_fts_probe_timeout
Values on all segments are consistent
GUC          : gp_fts_probe_timeout
Master  value: 20s
Segment value: 20s
[gpadmin@gp6mdw pg_log]$ gpconfig -s gp_fts_probe_retries
Values on all segments are consistent
GUC          : gp_fts_probe_retries
Master  value: 5
Segment value: 5
[gpadmin@gp6mdw pg_log]$ gpconfig -s gp_fts_probe_interval
Values on all segments are consistent
GUC          : gp_fts_probe_interval
Master  value: 1min
Segment value: 1min
```

**Comment by lij55** [comment] 2022-08-04 08:42
Hi @cobolbaby , thanks for reporting. could you provide a bit more detail about what the network issue is?

it looks like that the DNS server is done and the cluster is not using static /etc/hosts for host resolving. Am I correct?

**Comment by cobolbaby** [comment] 2022-08-04 12:05
@lij55 Yes, the container DNS was temporarily unavailable. The failure lasted for half a minute.

**Comment by ashwinstar** [comment] 2022-08-04 17:52
You confused the `gp_fts_probe_interval` GUC with retry interval. `gp_fts_probe_interval` controls how frequently the FTS probe is triggered in cluster. It has nothing to do with retry. Only GUC `gp_fts_probe_retries` controls how many retries to perform in system. The time/interval between each retry is hard-coded to be 1 sec and don't reason to have knob to control the same. If you wish to have retries for longer time then just bump the value for `gp_fts_probe_retries`. Increasing the time between each retry to like 1 min would be not good for performance as if the probing end comes up in 0.5 min, FTS is unnecessarily wasting 0.5 min time. Hence, granularity of retries every sec seems fine, just let it retry for longer number of times if that's desired. I am closing the issue as functioning as designed and nothing to fix.

**Closed by ashwinstar** 2022-08-04 17:52 UTC
Labels: type: bug, area: server, version: 6X_STABLE, Priority 2

**Comment by cobolbaby** [comment] 2022-08-05 01:50
Thanks for clarifying. But I still don't understand `Increasing the time between each retry to like 1 min would be not good for performance as if the probing end comes up in 0.5 min, FTS is unnecessarily wasting 0.5 min time.`

**Comment by ashwinstar** [comment] 2022-08-08 19:31
For example there are two ways to accomplish retry for 1 min
- retry every sec for 60 times
- retry every min for 1 time
which one would be your prefer? First one gives one sec granularity for early exit second one doesn't and unnecessarily wastes sleeping for 1 min. That's the reason there is only knob to control number of retries.

**Comment by lij55** [comment] 2022-08-09 00:47
the time of looking up DNS and failure is not related with fts. the probe doesn't make sense unless it can connect to segment. the failure of DNS server in fact is out of the control of FTS. 

you can use static hosts file to work around such failure.
