### ISSUE TITLE
How to handle segment error in parallel_retrieve_cursor

### ISSUE THREAD

**Issue by lmzzzzz1** [greenplum-db/gpdb#15143] opened 2023-03-06 11:36 UTC
## Bug Report
It may not be considered a bug, but it can cause confusion during use.

The Parallel Retrieve Cursor provides an asynchronous interface for clients to declare and fetch data, where one client declares and other clients fetch the data. However, handling errors with this method is different from normal SELECT statements(which QD continuously polls QE messages in order to process errors in real-time and cancel all other QEs). In contrast, after the Parallel Retrieve Cursor is declared, it enters a "idle in transaction" state and wait for new commands. This means that if QE raises an error, it will abort and send an error message to QD. However, QD remains in an "idle in transaction" state and does not handle the QE error, causing other slices to continue running.

When a multi-slice query is declared, like:
``` 
create table t1(a int);
insert into t1 values (-1);

 begin;
 declare c1 parallel retrieve cursor for  select count(*) from t1 group by  sqrt(a);

-- the plan is like:
-- explain declare c1 parallel retrieve cursor for  select count(*) from t1 group by  sqrt(a);
                                           QUERY PLAN
------------------------------------------------------------------------------------------------
 Finalize HashAggregate  (cost=716.00..721.00 rows=333 width=16)
   Group Key: (sqrt((a)::double precision))
   ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=676.00..711.00 rows=1000 width=16)
         Hash Key: (sqrt((a)::double precision))
         ->  Partial HashAggregate  (cost=676.00..691.00 rows=1000 width=16)
               Group Key: sqrt((a)::double precision)
               ->  Seq Scan on t1  (cost=0.00..515.50 rows=32100 width=8)
 Optimizer: Postgres query optimizer
 Endpoint: on all 3 segments
(9 rows)


```
Assume that t1.a has negative value, and slice 1 will raise ERROR and abort. But QD are waiting for new command from client, and do not handle the error. QEs in root slice will hang in motion.

### Greenplum version or build
7.0 & 6X

### OS version and uname -a
Not involved

### Step to reproduce the behavior
client 1:
```
create table t1(a int);
insert into t1 values (-1);

 begin;
 declare c1 parallel retrieve cursor for  select count(*) from t1 group by  sqrt(a);
select * from gp_endpoints ;
```

client2:
```
#PGOPTIONS='-c gp_retrieve_conn=true' psql -p 7654 -d postgres -h localhost

retrieve all from endpoint c1000000ee00000011;

-- It will hang
```

**Comment by adam8157** [comment] 2023-03-08 07:58
https://github.com/greenplum-db/gpdb/blob/main/src/backend/cdb/endpoint/README

> Error Handling In Retrieve Session
> ==================================

> When error happens in a retrieve session, the endpoint will be removed from QE.
The other retrieve sessions can still retrieve from other endpoints which
belong to this session at this time. But if gp_wait_parallel_retrieve_cursor()
or CLOSE are executed on QD, the other retrieve sessions will be canceled since
the error is delivered to QD and treated as an error happens in the
transaction.

> When the endpoint is partially retrieved and then the corresponding retrieve
session quits, the case will be treated as a retrieve session error as well.
The endpoint will be removed and an error will be reported on QD when checking
or waiting on the retrieve state. "CLOSE" will also report error in this case.

It is "kind of" by design, but let's at least try to improve it.

**Comment by adam8157** [comment] 2023-03-09 06:31
Since the retrieve backend, the endpoint backend, and the aborted backend are on the same segment, how about just sending a signal to abort the retrieve backend?

**Comment by lmzzzzz1** [comment] 2023-03-09 08:44
If the endpoint receives a signal and aborts, then the master session queries gp_endpoints, other segments will still return their own endpoints, causing other retrieve conn hang(like above single slice query).

**Comment by lmzzzzz1** [comment] 2023-03-14 03:20
@zxuejing I understand your meaning now. You mean to use SIGALRM to implement a mechanism for continuous checking on QD, similar to 
```c
while(1)
{
  gp_check_parallel_retrieve_cursor;
  sleep(1);
}

```
but non-blocking.

I will work on verifying the method.

**Comment by zxuejing** [comment] 2023-03-14 03:35
yes, @lmzzzzz1 , you are right, maybe we should write a new function similar to gp_check_parallel_retrieve_cursor, because gp_check_parallel_retrieve_cursor will throw an error if there is some error in this parallel retrieve cursor, But here we should only cancel other QEs when this parallel retrieve cursor hit some error.

**Comment by adam8157** [comment] 2023-10-16 07:08
Fixed by https://github.com/greenplum-db/gpdb/pull/15203

**Closed by adam8157** 2023-10-16 07:08 UTC
Labels: type: bug, version: 6X_STABLE, version: 7X_ALPHA
