### ISSUE TITLE
Unbalanced distribution Using randomly

### ISSUE THREAD

**Issue by z17033** [greenplum-db/gpdb#11284] opened 2020-12-17 01:26 UTC
### Greenplum version or build
` PostgreSQL 9.6beta4 (Greenplum Database 7.0.0-alpha.0 build dev) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled on Nov 25 2020 06:58:38 (with asse
rt checking)`

### OS version and uname -a
`CentOS Linux release 7.7.1908 (Core)`

### Expected behavior
`Data should be evenly distributed on 3 segments`

### Actual behavior
`Data distributed on 3 segments, and not evenly`

### Step to reproduce the behavior
**S1:Create table** 
postgres=# create table test_random(id int,name varchar(20)) distributed randomly;
CREATE TABLE

**S2:Insert**
postgres=# insert into test_random values(1,'bbb');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(2,'ccc');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(3,'ddd');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(4,'eee');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(5,'fff');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(6,'ggg');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(7,'hhh');
INSERT 0 1
postgres=#
postgres=# insert into test_random values(8,'hhih');
INSERT 0 1
postgres=# insert into test_random select * from test_random ;
INSERT 0 8
postgres=# insert into test_random select * from test_random ;
INSERT 0 16
postgres=# insert into test_random select * from test_random ;
INSERT 0 32
postgres=# insert into test_random select * from test_random ;
INSERT 0 64
postgres=# insert into test_random select * from test_random ;
INSERT 0 128
postgres=# insert into test_random select * from test_random ;
INSERT 0 256
postgres=# insert into test_random select * from test_random ;
INSERT 0 512
postgres=# insert into test_random select * from test_random ;
INSERT 0 1024
postgres=# insert into test_random select * from test_random ;
INSERT 0 2048
postgres=# insert into test_random select * from test_random ;
INSERT 0 4096
postgres=# insert into test_random select * from test_random ;
INSERT 0 8192
postgres=# insert into test_random select * from test_random ;
INSERT 0 16384
postgres=# insert into test_random select * from test_random ;
INSERT 0 32768
postgres=# insert into test_random select * from test_random ;
INSERT 0 65536

**S3: Query**
postgres=# select count(1), gp_segment_id from test_random group by 2;
 count | gp_segment_id 
-------+---------------
 49152 |             1
 16384 |             0
 65536 |             2
(3 rows)

postgres=# select * from gp_segment_configuration ;
 dbid | content | role | preferred_role | mode | status | port | hostname | address |                               datadir                                
------+---------+------+----------------+------+--------+------+----------+---------+----------------------------------------------------------------------
    1 |      -1 | p    | p              | n    | u      | 7000 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/qddir/demoDataDir-1
    8 |      -1 | m    | m              | s    | u      | 7001 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/standby
    2 |       0 | m    | p              | n    | d      | 7002 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast1/demoDataDir0
    5 |       0 | p    | m              | n    | u      | 7005 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0
    4 |       2 | m    | p              | n    | d      | 7004 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast3/demoDataDir2
    7 |       2 | p    | m              | n    | u      | 7007 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror3/demoDataDir2
    3 |       1 | m    | p              | n    | d      | 7003 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast2/demoDataDir1
    6 |       1 | p    | m              | n    | u      | 7006 | node2    | node2   | /data/program/gpdb/gpAux/gpdemo/datadirs/dbfast_mirror2/demoDataDir1
(8 rows)

**S4:Test for Hash** 
postgres=# create table test_hash (id int, name varchar) distributed by (id);
CREATE TABLE
postgres=# 
postgres=# insert into test_hash select * from test_random ;
INSERT 0 131072
postgres=# select count(1), gp_segment_id from test_hash group by 2;             
 count | gp_segment_id 
-------+---------------
 32768 |             2
 16384 |             1
 81920 |             0
(3 rows)

**Comment by kainwen** [comment] 2020-12-17 01:47
For the randomly distributed test above, can you verify two things:

1. are you using orca or planner? `show optimizer;`
2. can you paste the result `explain insert into test_random select * from test_random;`

I guess you are using planner, and the root cause should be this issue: https://github.com/greenplum-db/gpdb/issues/11008
----------

For the hash distributed you described in `S4`, you can refer to this closed issue: https://github.com/greenplum-db/gpdb/issues/11243

**Comment by ashwinstar** [comment] 2021-02-19 23:40
This is duplicate of #11008 as mentioned earlier. Lets track the issue under #11008, hence I am closing this duplicate one.

**Closed by ashwinstar** 2021-02-19 23:40 UTC
