### ISSUE TITLE
Deadlock with gp_cte_sharing

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#1967] opened 2017-03-06 18:55 UTC
With gp_cte_sharing, it's possible to get a deadlock, because of nodes waiting for each other to send tuples.

One such example is in the `qp_with_functional_inlining` test in the main test suite: 
```
regression=# explain WITH v AS (SELECT a, b FROM qp_with_functional_inlining.foo_ao WHERE b < 5),
     w AS (SELECT c, d FROM qp_with_functional_inlining.bar_co WHERE c < 9)
SELECT v1.a, w1.c, w2.d
FROM v AS v1, v as v2, w AS w1, w AS w2
WHERE v1.a = v2.b
AND v1.a = w1.c
AND v1.b = w2.d ORDER BY 1;
                                                      QUERY PLAN                                                      
----------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice4; segments: 3)  (cost=14.28..14.29 rows=4 width=12)
   Merge Key: share0_ref2.a
   ->  Sort  (cost=14.28..14.29 rows=2 width=12)
         Sort Key: share0_ref2.a
         ->  Hash Join  (cost=13.72..14.25 rows=2 width=12)
               Hash Cond: share0_ref2.a = share0_ref1.b
               ->  Redistribute Motion 3:3  (slice2; segments: 3)  (cost=6.70..7.19 rows=2 width=8)
                     Hash Key: share0_ref2.a
                     ->  Hash Join  (cost=6.70..7.12 rows=2 width=8)
                           Hash Cond: share0_ref2.b = share1_ref2.d
                           ->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=3.16..3.50 rows=4 width=8)
                                 ->  Shared Scan (share slice:id 1:0)  (cost=3.16..3.37 rows=2 width=8)
                           ->  Hash  (cost=3.43..3.43 rows=3 width=4)
                                 ->  Shared Scan (share slice:id 2:1)  (cost=3.22..3.43 rows=3 width=8)
               ->  Hash  (cost=6.97..6.97 rows=2 width=8)
                     ->  Hash Join  (cost=6.70..6.97 rows=2 width=8)
                           Hash Cond: share1_ref1.c = share0_ref1.b
                           ->  Shared Scan (share slice:id 4:1)  (cost=3.22..3.43 rows=3 width=8)
                                 ->  Materialize  (cost=3.13..3.22 rows=3 width=8)
                                       ->  Append-only Columnar Scan on bar_co  (cost=0.00..3.12 rows=3 width=8)
                                             Filter: c < 9
                           ->  Hash  (cost=3.43..3.43 rows=2 width=4)
                                 ->  Redistribute Motion 3:3  (slice3; segments: 3)  (cost=3.16..3.43 rows=2 width=4)
                                       Hash Key: share0_ref1.b
                                       ->  Shared Scan (share slice:id 3:0)  (cost=3.16..3.37 rows=2 width=8)
                                             ->  Materialize  (cost=3.13..3.16 rows=2 width=8)
                                                   ->  Append-only Scan on foo_ao  (cost=0.00..3.12 rows=2 width=8)
                                                         Filter: b < 5
 Settings:  gp_cte_sharing=on
 Optimizer status: legacy query optimizer
(30 rows)
```

Another such issue was discussed on gpdb-dev recently: https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/gMa1tW0x_fk/wuzvGXBaBAAJ.

**Comment by vraghavan78** [comment] 2017-03-07 19:21
This seems like a duplicate of https://github.com/greenplum-db/gpdb/issues/1617

**Comment by hlinnaka** [comment] 2017-03-07 19:23
On 03/07/2017 09:21 PM, Venkatesh Raghavan wrote:
> This seems like a duplicate of https://github.com/greenplum-db/gpdb/issues/1617

Yes, thanks! I looked for that old issue, because I remembered I had 
opened one, but couldn't find it.

- Heikki

**Comment by hsyuan** [comment] 2017-04-25 19:27
Here is the repro:

```sql
CREATE TABLE foo(a int, b int);
INSERT INTO foo SELECT i as a, i+1 as b FROM generate_series(1,10)i;

CREATE TABLE bar(c int, d int);
INSERT INTO bar SELECT i as c, i+1 as d FROM generate_series(1,10)i;

WITH v AS (SELECT a, b FROM foo WHERE b < 5),
     w AS (SELECT c, d FROM bar WHERE c < 9)
SELECT v1.a, w1.c, w2.d
FROM v AS v1, v as v2, w AS w1, w AS w2
WHERE v1.a = v2.b
AND v1.a = w1.c
AND v1.b = w2.d;
```

When executing the query, when can see the following debug messages print out continuously without returning any result:
```sql
DEBUG1:  SISC READER (shareid=1, slice=2): Wait ready time out once  (seg2 slice2 127.0.0.1:25434 pid=5222)
```
That segment 2 is hanging all the time, waiting for the writer done.

The plan of above query is shown below:
![image](https://cloud.githubusercontent.com/assets/15352793/25402586/01038628-29ae-11e7-8ed3-c58f6423311c.png)

In 3 segments cluster environment, the data distribution of CTE `v` is:
```sql
select gp_segment_id, * from foo where b < 5;
 gp_segment_id | a | b
---------------+---+---
             0 | 1 | 2
             0 | 2 | 3
             1 | 3 | 4
(3 rows)
```

There will be no tuple output in segment 2 for the above query (CTE `v`), and the lower hash table in slice 4(in green color) will be empty. Hash Join executes inner side (Hash) first, when the hash table is empty, it decides that there is no needs to execute the outer child, which means the shared scan for CTE `w` on table `bar` will not be executed. But the hash operator in slice 2 (in blue color) is still waiting for the writer of CTE `v` to finish. Hence it hangs for ever.

There are 2 solutions:
1. Change planner to generate better plan using sequence (like Orca plan) to make sure the CTE query is always executed.
2. Change executor that which ShareInputScan get executed first becomes the producer.

Since we are on the way to merge with Postgres style CTEScan, we are not going to fix this issue right now. After the merge is done, this kind of issue should be resolved.

**Comment by Eulerizeit** [comment] 2019-01-27 16:34
@danielgustafsson it was assumed that this had the same Root Cause as https://github.com/greenplum-db/gpdb/issues/1617, which you closed.  Is this fixed as well?

**Comment by danielgustafsson** [comment] 2019-01-29 13:36
This cannot be reproduced on current master, both the original report and the reproduction work as expected. Closing.

**Closed by danielgustafsson** 2019-01-29 13:36 UTC
Labels: 8.4-9.0 CTE, Planner, bug
