### ISSUE TITLE
pg_type without index

### ISSUE THREAD

**Issue by eric0225** [greenplum-db/gpdb#11207] opened 2020-11-24 03:05 UTC
GPDB version
6.4.0
GPCC version
6.1.0
![image](https://user-images.githubusercontent.com/71756944/100041709-d7511080-2e44-11eb-8511-94fa63d62861.png)

**Comment by asimrp** [comment] 2020-11-25 13:25
@eric0225 please note that without steps to reproduce your problem, we cannot help you.

I'm closing this issue because it works on my dev environment on 6.11.  Please consider upgrading to the latest 6X.  
```SQL
select version();
                                                                                                               version
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.11.2+dev.30.g94e2979b945 build dev) on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.31.1), 64-bit compiled on Oct 16 2020 17:11:09 (with assert checking)
(1 row)

\d+ pg_type
                            Table "pg_catalog.pg_type"
     Column     |     Type     | Modifiers | Storage  | Stats target | Description
----------------+--------------+-----------+----------+--------------+-------------
 typname        | name         | not null  | plain    |              |
 typnamespace   | oid          | not null  | plain    |              |
 typowner       | oid          | not null  | plain    |              |
 typlen         | smallint     | not null  | plain    |              |
 typbyval       | boolean      | not null  | plain    |              |
 typtype        | "char"       | not null  | plain    |              |
 typcategory    | "char"       | not null  | plain    |              |
 typispreferred | boolean      | not null  | plain    |              |
 typisdefined   | boolean      | not null  | plain    |              |
 typdelim       | "char"       | not null  | plain    |              |
 typrelid       | oid          | not null  | plain    |              |
 typelem        | oid          | not null  | plain    |              |
 typarray       | oid          | not null  | plain    |              |
 typinput       | regproc      | not null  | plain    |              |
 typoutput      | regproc      | not null  | plain    |              |
 typreceive     | regproc      | not null  | plain    |              |
 typsend        | regproc      | not null  | plain    |              |
 typmodin       | regproc      | not null  | plain    |              |
 typmodout      | regproc      | not null  | plain    |              |
 typanalyze     | regproc      | not null  | plain    |              |
 typalign       | "char"       | not null  | plain    |              |
 typstorage     | "char"       | not null  | plain    |              |
 typnotnull     | boolean      | not null  | plain    |              |
 typbasetype    | oid          | not null  | plain    |              |
 typtypmod      | integer      | not null  | plain    |              |
 typndims       | integer      | not null  | plain    |              |
 typcollation   | oid          | not null  | plain    |              |
 typdefaultbin  | pg_node_tree |           | extended |              |
 typdefault     | text         |           | extended |              |
 typacl         | aclitem[]    |           | extended |              |
Indexes:
    "pg_type_oid_index" UNIQUE, btree (oid)
    "pg_type_typname_nsp_index" UNIQUE, btree (typname, typnamespace)
Has OIDs: yes
```

**Closed by asimrp** 2020-11-25 13:25 UTC
