### ISSUE TITLE
[ERROR TRACE] Test on both ARM and X86.

### ISSUE THREAD

**Issue by bzhaoopenstack** [greenplum-db/gpdb#9533] opened 2020-02-05 08:42 UTC
I figure out all failure when I exec the minimal regression test on ARM and X86 via make installcheck-world. Please see the attachment [5] for test logs.

I test on both x86 and aarch64 ARCH. Please see the test result in the attached files for details.For summary this, both ARCH seem get the same test result.
Also I find a sentence "Note that the installcheck-world make target has at least 43 out of 401 failures, some of which are non-deterministic." in the last contents of [1]. So look like the tests are in the same line now just from regression tests.

Also I repo the test via Dockerfile[2] on both ARCH. And I only found 1 issue during my testing. At first, for easier to trace the issue, I fork the gpdb to my repo[3] for making sure the code won't change frequently. Now I describe the issue what I find here:
google/cmockery seems different behavior between x86 and aarch64. So I post [4] to test, you also would found the related step in the dockerfile[2].
[1] https://github.com/greenplum-db/gpdb/blob/master/README.docker.md
[2] https://github.com/bzhaoopenstack/dockertoy/blob/master/aarch64/ubuntu/greenplum/Dockerfile
[3] https://github.com/bzhaoopenstack/gpdb
[4] https://github.com/bzhaoopenstack/gpdb/pull/4/files
[5] https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/gJbZrOvLHv0/vlFubFE9DAAJ

Test error and summary:

parallel group (14 tests):  create_cast create_am create_function_3 roleattributes create_aggregate typed_table vacuum rolenames drop_if_exists create_table_like constraints inherit triggers updatable_views
     drop_if_exists           ... FAILED (2.19 sec)  (diff:0.16 sec)
parallel group (20 tests):  limit alter_extension prepare conversion gp_foreign_data xml plancache sequence without_oid temp rowtypes polymorphism copy2 with truncate returning domain plpgsql rangefuncs alter_table
test instr_in_shmem           ... FAILED (0.20 sec)  (diff:0.17 sec)
test createdb                 ... FAILED (16.13 sec)  (diff:0.16 sec)
parallel group (14 tests):  gp_metadata gp_xml variadic_parameters default_parameters resource_queue_with_rule spi shared_scan gp_index returning_gp gp_types function_extensions gp_aggregates update_gp gp_aggregates_costs
test python_processed64bit    ... FAILED (0.15 sec)  (diff:0.13 sec)
test gp_tablespace_with_faults ... FAILED (104.35 sec)  (diff:0.29 sec)
parallel group (19 tests):  opr_sanity_gp replication_slots leastsquares gp_create_view window_views create_table_like_gp gp_constraints notin matview_ao percentile case_gp union_gp limit_gp gp_create_table gpcopy_encoding decode_expr join_gp bitmapscan_ao bitmapscan
     union_gp                 ... FAILED (5.19 sec)  (diff:0.32 sec)
parallel group (18 tests):  sublink information_schema matrix gp_explain opclass_ddl filter guc_env_var gpdist_legacy_opclasses olap_setup olap_plans gpdist_opclasses complex gpctas explain_format table_functions gpdist distributed_transactions toast
     table_functions          ... FAILED (2.21 sec)  (diff:0.63 sec)
parallel group (7 tests):  workfile/materialize_spill workfile/sort_spill workfile/hashjoin_spill workfile/sisc_sort_spill workfile/sisc_mat_sort workfile/hashagg_spill workfile/spilltodisk
     workfile/hashagg_spill   ... FAILED (8.80 sec)  (diff:0.15 sec)
     workfile/hashjoin_spill  ... FAILED (3.04 sec)  (diff:0.14 sec)
     workfile/materialize_spill ... FAILED (2.72 sec)  (diff:0.14 sec)
     workfile/sisc_mat_sort   ... FAILED (5.31 sec)  (diff:0.14 sec)
     workfile/sisc_sort_spill ... FAILED (3.12 sec)  (diff:0.14 sec)
     workfile/sort_spill      ... FAILED (2.78 sec)  (diff:0.14 sec)
test instr_in_shmem_verify    ... FAILED (0.06 sec)  (diff:0.14 sec)
parallel group (8 tests):  gptokencheck tidscan gpdiffcheck dml_in_udf gp_hashagg sequence_gp co_nestloop_idxscan gpdtm_plpgsql
     dml_in_udf               ... FAILED (0.43 sec)  (diff:0.16 sec)
parallel group (14 tests):  gp_transactions subselect_gp2 rangefuncs_cdb subselect_gp_indexes create_table_distpol gp_dqa olap_group olap_window_seq partial_table subselect_gp query_finish appendonly sirv_functions alter_distpol_dropped
     sirv_functions           ... FAILED (15.23 sec)  (diff:0.35 sec)
parallel group (6 tests):  alter_table_set subtransaction_visibility alter_table_gp udf_exception_blocks alter_table_ao oid_consistency
     oid_consistency          ... FAILED (3.36 sec)  (diff:0.21 sec)
parallel group (17 tests):  trig timeseries gp_numeric_agg expand_table_regression gp_toolkit_ao_funcs role pg_stat_last_shoperation pg_stat_last_operation auth_constraint runtime_stats portals_updatable plpgsql_cache expand_table partition_pruning partindex_test expand_table_ao expand_table_aoco
     partition_pruning        ... FAILED (13.83 sec)  (diff:0.85 sec)
     runtime_stats            ... FAILED (2.12 sec)  (diff:0.13 sec)
     expand_table_regression  ... FAILED (0.72 sec)  (diff:0.13 sec)
parallel group (4 tests):  rle not_out_of_shmem_exit_slots dsp rle_delta
     dsp                      ... FAILED (39.44 sec)  (diff:0.27 sec)
parallel group (13 tests):  nested_case_null aggregate_with_groupingsets sort bfv_catalog bfv_olap bfv_statistic bfv_index bfv_partition_plans gporca bfv_aggregate DML_over_joins bb_mpph bfv_partition
     bfv_catalog              ... FAILED (1.30 sec)  (diff:0.21 sec)
     bfv_index                ... FAILED (5.20 sec)  (diff:0.24 sec)
     bfv_aggregate            ... FAILED (30.11 sec)  (diff:0.35 sec)
     bfv_partition_plans      ... FAILED (17.42 sec)  (diff:0.32 sec)
     sort                     ... FAILED (0.75 sec)  (diff:0.20 sec)
     gporca                   ... FAILED (23.99 sec)  (diff:1.39 sec)
parallel group (2 tests):  memconsumption bb_memory_quota
     memconsumption           ... FAILED (1.93 sec)  (diff:0.16 sec)
parallel group (7 tests):  bfv_legacy bfv_cte bfv_planner bfv_dml bfv_subquery bfv_joins bfv_temp
     bfv_subquery             ... FAILED (1.09 sec)  (diff:0.17 sec)
     bfv_legacy               ... FAILED (0.41 sec)  (diff:0.14 sec)
parallel group (8 tests):  qp_executor qp_bitmapscan qp_olap_windowerr qp_with_clause qp_olap_window qp_derived_table qp_misc_jiras qp_dropped_cols
     qp_olap_window           ... FAILED (53.99 sec)  (diff:11.71 sec)
parallel group (2 tests):  qp_with_functional_noinlining qp_with_functional_inlining
     qp_with_functional_inlining ... FAILED (2.68 sec)  (diff:0.34 sec)
     qp_with_functional_noinlining ... FAILED (1.71 sec)  (diff:0.33 sec)
parallel group (14 tests):  qp_misc_rio_join_small qp_functions_in_subquery qp_targeted_dispatch qp_correlated_query qp_functions_in_select qp_functions_in_with qp_misc_rio qp_gist_indexes3 qp_functions_in_subquery_constant qp_functions_in_subquery_column qp_gist_indexes4 qp_query_execution qp_gist_indexes2 qp_functions_in_from
     qp_misc_rio              ... FAILED (10.62 sec)  (diff:0.21 sec)
     qp_gist_indexes2         ... FAILED (26.65 sec)  (diff:0.52 sec)
     qp_query_execution       ... FAILED (23.15 sec)  (diff:0.26 sec)
parallel group (10 tests):  qp_left_anti_semi_join qp_orca_fallback qp_functions_idf qp_regexp qp_dpe qp_resource_queue qp_subquery qp_functions dpe qp_union_intersect
     qp_dpe                   ... FAILED (2.62 sec)  (diff:0.15 sec)
parallel group (4 tests):  AORO_Compression ao_checksum_corruption table_statistics AOCO_Compression
     ao_checksum_corruption   ... FAILED (20.98 sec)  (diff:0.16 sec)
parallel group (4 tests):  pg_resetxlog psql_gp_commands gp_upgrade_cornercases dropdb_check_shared_buffer_cache
test instr_in_shmem_verify    ... FAILED (0.08 sec)  (diff:0.14 sec)
test alter_db_set_tablespace  ... FAILED (5418.47 sec)  (diff:0.29 sec)
test fts_recovery_in_progress ... FAILED (47.85 sec)  (diff:0.15 sec)
parallel group (2 tests):  gang_reuse gangsize
test run_utility_gpexpand_phase1 ... FAILED (1.05 sec)  (diff:0.15 sec)

=========================
 42 of 546 tests failed. 
=========================

The differences that caused some tests to fail can be viewed in the
file "/home/greenplum/src/gpdb/src/test/regress/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/greenplum/src/gpdb/src/test/regress/regression.out".

GNUmakefile:195: recipe for target 'installcheck-good' failed
make[2]: Leaving directory '/home/greenplum/src/gpdb/src/test/regress'
Makefile:31: recipe for target 'installcheck-regress-recurse' failed
make[1]: Leaving directory '/home/greenplum/src/gpdb/src/test'
GNUmakefile:151: recipe for target 'installcheck-world-src/test-recurse' failed

**Comment by hlinnaka** [comment] 2020-02-05 09:43
This sounds like a configuration problem, perhaps $PATH doesn't include the gpdb installation's bin-directory, or $GPHOME or $PYTHONPATH  or something else is set incorrectly. Did you do `. greenplum_path.sh`? 

Please take a look at the regression.diffs file, that should give a clue on what's missing.

**Comment by bzhaoopenstack** [comment] 2020-02-06 09:18
Hi @hlinnaka,
I think it seem not. I source the greenplum_path.sh before testing. As I test in a container, please see [1] . And I had shared the regression.diffs file in the email's attachment [2]. I'm trying to understand what happen. And if you guys are free, how about to take a look together. Thanks

[1] https://github.com/bzhaoopenstack/dockertoy/blob/master/aarch64/ubuntu/greenplum/Dockerfile#L146
[2] https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/gJbZrOvLHv0/g5iItN5qAAAJ

**Comment by bzhaoopenstack** [comment] 2020-02-06 12:04
I just saw a error message which mention that "language "plpythonu" does not exist", is there some wrong operation during install gpdb?

**Comment by hlinnaka** [comment] 2020-02-06 12:13
Yeah, I think that's the problem. Did you run `configure` with the `--with-python` option? Some of the regression tests require pl/python.

**Comment by bzhaoopenstack** [comment] 2020-02-07 01:16
@hlinnaka Thanks very much. I didn't. I'm trying to test again. Thank you

**Comment by bzhaoopenstack** [comment] 2020-02-07 07:20
The new test result is:

parallel group (14 tests):  create_cast create_am create_function_3 create_aggregate typed_table roleattributes vacuum drop_if_exists create_table_like rolenames constraints inherit triggers updatable_views
     drop_if_exists           ... FAILED (1.96 sec)  (diff:0.16 sec)

parallel group (20 tests):  alter_extension conversion prepare limit gp_foreign_data xml plancache temp without_oid sequence rowtypes copy2 polymorphism truncate with returning domain rangefuncs plpgsql alter_table
test instr_in_shmem           ... FAILED (0.20 sec)  (diff:0.16 sec)


parallel group (7 tests):  workfile/materialize_spill workfile/hashjoin_spill workfile/sort_spill workfile/sisc_sort_spill workfile/sisc_mat_sort workfile/spilltodisk workfile/hashagg_spill
test instr_in_shmem_verify    ... FAILED (0.08 sec)  (diff:0.13 sec)

parallel group (4 tests):  rle not_out_of_shmem_exit_slots dsp rle_delta
     dsp                      ... FAILED (22.84 sec)  (diff:0.69 sec)

parallel group (4 tests):  pg_resetxlog psql_gp_commands gp_upgrade_cornercases dropdb_check_shared_buffer_cache
test instr_in_shmem_verify    ... FAILED (0.10 sec)  (diff:0.13 sec)
test fts_recovery_in_progress ... FAILED (74.51 sec)  (diff:0.16 sec)
test run_utility_gpexpand_phase1 ... FAILED (0.54 sec)  (diff:0.13 sec)

========================
 7 of 549 tests failed.
========================

The differences that caused some tests to fail can be viewed in the
file "/home/greenplum/src/gpdb/src/test/regress/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/greenplum/src/gpdb/src/test/regress/regression.out".

GNUmakefile:195: recipe for target 'installcheck-good' failed
make[2]: Leaving directory '/home/greenplum/src/gpdb/src/test/regress'
make[2]: *** [installcheck-good] Error 1
make[1]: *** [installcheck-regress-recurse] Error 2
Makefile:31: recipe for target 'installcheck-regress-recurse' failed
make[1]: Leaving directory '/home/greenplum/src/gpdb/src/test'
make: *** [installcheck-world-src/test-recurse] Error 2
GNUmakefile:151: recipe for target 'installcheck-world-src/test-recurse' failed

And I share the regression.diffs file in https://etherpad.openstack.org/p/gpdb-arm-tests 

Thanks @hlinnaka, the option works for me. I'm trying to figure out what going on for the last 7 errors.

**Comment by bzhaoopenstack** [comment] 2020-02-07 09:28
When I add a ENV 'USER' for drop if exist test, seem so many new tests are execing, the test is not finish yet. I will upload the result once it finish

**Comment by bzhaoopenstack** [comment] 2020-02-10 07:23
My tests hang on segwalrep/dtm_recovery_on_standby for many times, this will cause that the whole tests can not finish. Due to test in Docker, this will hang on both X86 and ARM, and I can not get anyother log for it. I guess this test must be related with the gpdb deployment, right? As before my test, I just exec and deploy a demo cluster . https://github.com/bzhaoopenstack/dockertoy/blob/master/aarch64/ubuntu/greenplum/Dockerfile#L149 
Hope could get any advices from yours. Thanks

**Comment by bzhaoopenstack** [comment] 2020-02-17 09:32
make[1]: Leaving directory '/home/greenplum/src/gpdb/contrib/citext'
make -C contrib/file_fdw installcheck
make[1]: Entering directory '/home/greenplum/src/gpdb/contrib/file_fdw'
make -C ../../src/test/regress pg_regress
make[2]: Entering directory '/home/greenplum/src/gpdb/src/test/regress'
make -C ../../../src/port all
make[3]: Entering directory '/home/greenplum/src/gpdb/src/port'
make -C ../backend submake-errcodes
make[4]: Entering directory '/home/greenplum/src/gpdb/src/backend'
make[4]: Nothing to be done for 'submake-errcodes'.
make[4]: Leaving directory '/home/greenplum/src/gpdb/src/backend'
make[3]: Leaving directory '/home/greenplum/src/gpdb/src/port'
make -C ../../../src/common all
make[3]: Entering directory '/home/greenplum/src/gpdb/src/common'
make -C ../backend submake-errcodes
make[4]: Entering directory '/home/greenplum/src/gpdb/src/backend'
make[4]: Nothing to be done for 'submake-errcodes'.
make[4]: Leaving directory '/home/greenplum/src/gpdb/src/backend'
make[3]: Leaving directory '/home/greenplum/src/gpdb/src/common'
make -C ../../../src/backend generated-headers
make[3]: Entering directory '/home/greenplum/src/gpdb/src/backend'
make -C catalog schemapg.h
make[4]: Entering directory '/home/greenplum/src/gpdb/src/backend/catalog'
make[4]: 'schemapg.h' is up to date.
make[4]: Leaving directory '/home/greenplum/src/gpdb/src/backend/catalog'
make[3]: Leaving directory '/home/greenplum/src/gpdb/src/backend'
make[2]: Leaving directory '/home/greenplum/src/gpdb/src/test/regress'
../../src/test/regress/pg_regress --inputdir=. --bindir='/home/greenplum/src/gpdb/gpsql/bin'    --dbname=contrib_regression file_fdw gp_file_fdw
(using postmaster on Unix socket, port 7000)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== checking optimizer status              ==============
Optimizer disabled. Using planner answer files
============== checking gp_resource_manager status    ==============
Resource group disabled. Using default answer files
============== running regression test queries        ==============
test file_fdw                 ... FAILED
test gp_file_fdw              ... ok

======================
 1 of 2 tests failed.
======================

The differences that caused some tests to fail can be viewed in the
file "/home/greenplum/src/gpdb/contrib/file_fdw/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/greenplum/src/gpdb/contrib/file_fdw/regression.out".

make[1]: *** [installcheck] Error 1
../../src/makefiles/pgxs.mk:287: recipe for target 'installcheck' failed
make[1]: Leaving directory '/home/greenplum/src/gpdb/contrib/file_fdw'
make: *** [installcheck-world-contrib/file_fdw-recurse] Error 2
GNUmakefile:151: recipe for target 'installcheck-world-contrib/file_fdw-recurse' failed
greenplum@436e998c999b:~/src/gpdb$ cat /home/greenplum/src/gpdb/contrib/file_fdw/regression.diffs
--- /home/greenplum/src/gpdb/contrib/file_fdw/expected/file_fdw.out     2020-02-17 08:18:53.147576564 +0000
+++ /home/greenplum/src/gpdb/contrib/file_fdw/results/file_fdw.out      2020-02-17 08:18:53.151576610 +0000
@@ -176,7 +176,6 @@
    Output: a, b
    Foreign File: /home/greenplum/src/gpdb/contrib/file_fdw/data/agg.csv
  Optimizer: Postgres query optimizer
- Settings: optimizer=off

 \t off
 PREPARE st(int) AS SELECT * FROM agg_csv WHERE a = $1;
@@ -228,7 +227,6 @@
    Output: a, b
    One-Time Filter: false
  Optimizer: Postgres query optimizer
- Settings: optimizer=off

 \t off
 SELECT * FROM agg_csv WHERE a < 0;
@@ -243,7 +241,7 @@
    Output: a, b
    One-Time Filter: false
  Optimizer: Postgres query optimizer
- Settings: constraint_exclusion=on, optimizer=off
+ Settings: constraint_exclusion=on

 \t off
 SELECT * FROM agg_csv WHERE a < 0;
@@ -326,7 +324,6 @@
    Filter: (agg_text.a > 0)
    Foreign File: /home/greenplum/src/gpdb/contrib/file_fdw/data/agg.data
  Optimizer: Postgres query optimizer
- Settings: optimizer=off

 \t off
 -- file FDW allows foreign tables to be accessed without user mapping

======================================================================


Hi @hlinnaka , I got the new issue on the following test. Could you please give some help? Thanks

**Comment by bzhaoopenstack** [comment] 2020-02-18 06:30
@hlinnaka Thanks very much, I will use the new code to test.

**Comment by bzhaoopenstack** [comment] 2020-02-19 02:30
@hlinnaka , that's great that you could help. It works. And I hit another error in the following test.

**Comment by bzhaoopenstack** [comment] 2020-02-19 02:38
And I didn't see any config option about pxf during ./configure --help. only --diable-pxf. Do I miss some configure option? 
I use options now:
ENV TRAVIS_BUILD_DIR /home/greenplum/src/gpdb
./configure --with-openssl --with-ldap --with-libcurl --prefix=${TRAVIS_BUILD_DIR}/gpsql --disable-orca --disable-gpcloud --enable-pxf --without-readline --with-python --with-gssapi

**Comment by hlinnaka** [comment] 2020-02-19 09:14
On 19/02/2020 04:38, bzhaoopenstack wrote:
> And I didn't see any config option about pxf during ./configure --help. 
> only --diable-pxf. Do I miss some configure option?
> I use options now:
> ENV TRAVIS_BUILD_DIR /home/greenplum/src/gpdb
> ./configure --with-openssl --with-ldap --with-libcurl 
> --prefix=${TRAVIS_BUILD_DIR}/gpsql --disable-orca --disable-gpcloud 
> --enable-pxf --without-readline --with-python --with-gssapi

PXF is enabled by default, but you can use the --disable-pxf option to 
disable it. --enable-pxf doesn't really do anything because it's enabled 
by default, but it's accepted for consistency. It's the same with all 
the other --enable/disable-* configure options

- Heikki

**Comment by bzhaoopenstack** [comment] 2020-02-20 01:36
Thanks for suggestion, @hlinnaka . I'm trying to disable the pxf first.

**Comment by bzhaoopenstack** [comment] 2020-02-21 01:09
Thanks @hlinnaka , after disable pxf, I get the full test pass now. I will share the log and configure option in the ML.

**Comment by hlinnaka** [comment] 2020-03-08 14:56
Closing, since you got it working.

**Closed by hlinnaka** 2020-03-08 14:56 UTC
