### ISSUE TITLE
ERROR: could not pull up equivalence class using projected target list (pathkeys.c:1539)

### ISSUE THREAD

**Issue by orhankislal** [greenplum-db/gpdb#15794] opened 2023-06-16 17:09 UTC
## Bug Report
MADlib kmeans function started to get the following error.
ERROR:  could not pull up equivalence class using projected target list (pathkeys.c:1539)
MADlib-free repro is added below.

The same test was working earlier in beta3 (gpdb 7c943b04a522cbf3fc028fda5c4ee72fe4703b29 commit was green)
### Greenplum version or build
PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.3+dev.260.gf3782c6dd8 build commit:f3782c6dd89c9b6565a84518174ed4dd448f3293)
### OS version and uname -a
Red Hat Enterprise Linux release 8.8 (Ootpa)

Linux a5494a9b-0aa0-4b6f-68ac-170571dbd674 5.4.0-144-generic #161~18.04.1-Ubuntu SMP Fri Feb 10 15:55:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
gs://pivotal-gpdb-concourse-resources-prod/server/published/main/server-rc-7.0.0-beta.3+dev.260.gf3782c6dd8-el8_x86_64.tar.gz

### Step to reproduce the behavior
Pipeline: https://dev2.ci.gpdb.pivotal.io/teams/gp-ai/pipelines/dev:okislal_madlib_fix-python39/jobs/madlib_master_ic_gpdb7_planner_rhel8/builds/6

CREATE TABLE t2(
    id INTEGER,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    position DOUBLE PRECISION[]
);

insert into t2 values (1,1,1,ARRAY[1,1]);
insert into t2 values (2,2,2,ARRAY[2,2]);

SELECT array_agg(length) FROM (
            SELECT (
                array_upper( position, 1)
                - array_lower( position, 1) + 1
            ) AS length,
            array_lower( position, 1) AS lower
            FROM t2
            GROUP BY length, lower) t;

**Comment by hyongtao-db** [comment] 2023-06-17 02:00
Same as [issue-15767]( https://github.com/greenplum-db/gpdb/issues/15767)

**Comment by kainwen** [comment] 2023-06-17 02:20
> Thanks for your report. Same as [issue-15767](https://github.com/greenplum-db/gpdb/issues/15767)

NOT the real same root cause.

**Comment by kainwen** [comment] 2023-06-17 02:48
I open a PR https://github.com/greenplum-db/gpdb/pull/15797
to revert the commit that introduces the regression and also add this case as guarding so that later we can do a correct refactor.

**Comment by kainwen** [comment] 2023-06-17 06:18
Revert PR is pushed, close this issue. Later details might be found in the comment parts of https://github.com/greenplum-db/gpdb/issues/15079.

**Closed by kainwen** 2023-06-17 06:18 UTC
Labels: type: bug
