### ISSUE TITLE
stand by master failure due to orca

### ISSUE THREAD

**Issue by salahaldin** [greenplum-db/gpdb#4316] opened 2018-01-14 21:35 UTC
### Greenplum version or build 
5.3.0

### OS version and uname -a
3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### orca version
2.51.4
I have initialized a stand by master , but it failed as shown below, the master node works fine.

2018-01-14 22:14:30.648752 CET,,,p25808,th1189586816,,,,0,,,seg-1,,,,,"PANIC","XX000","Distribute transaction identifier too long (38) (cdbtm.c:1986)",,,,,,,0,,"cdbtm.c",1986,"Stack trace:
1    0x9285c6 postgres errstart + 0x1f6
2    0x92a09b postgres elog_finish + 0xab
3    0xa5d2fa postgres redoDistributedCommitRecord + 0x2fa
4    0xa5d3d4 postgres redoDtxCheckPoint + 0x74
5    0x516e37 postgres <symbol not found> + 0x516e37
6    0x524127 postgres StartupXLOG + 0x3c7
7    0x528dde postgres StartupProcessMain + 0x26e
8    0x57a84d postgres AuxiliaryProcessMain + 0x4cd
9    0x7acc6e postgres <symbol not found> + 0x7acc6e
10   0x7af2cd postgres StartMasterOrPrimaryPostmasterProcesses + 0x2d
11   0x7b8deb postgres doRequestedPrimaryMirrorModeTransitions + 0x3fb
12   0x7b290a postgres <symbol not found> + 0x7b290a
13   0x7b66fc postgres PostmasterMain + 0xc5c
14   0x4c57c2 postgres main + 0x3a2
15   0x7f7243bcbf45 libc.so.6 __libc_start_main + 0xf5
16   0x4c5d4f postgres <symbol not found> + 0x4c5d4f

**Comment by salahaldin** [comment] 2018-01-14 22:01
This is related to orca, I have disabled removed the stand by master and then disabled the optimizer and finally recreate the standby master and it worked.

**Comment by hsyuan** [comment] 2018-01-16 19:42
How can I reproduce the issue? I didn't see reason this is related with Orca.
@vraghavan78 Can you tell this is caused by Orca?

**Comment by salahaldin** [comment] 2018-01-16 21:37
I do not know how to reproduce, I have dumped a database from 4.3 cluster and restore it on 5.3 cluster. Since the restored database schema code is long I am not sure where is the root cause. I  think this is related to orca because if i disable the optimizer then I can initialize a stand by master otherwise it fails.

**Comment by vraghavan78** [comment] 2018-03-06 19:40
@salahaldin I am closing this issue since we cannot reproduce it

**Closed by vraghavan78** 2018-03-06 19:40 UTC
Labels: GPORCA
