### ISSUE TITLE
memory leak on insert data, end with High VMEM Usage error

### ISSUE THREAD

**Issue by yunlik** [greenplum-db/gpdb#10288] opened 2020-06-12 09:03 UTC
### Greenplum version or build
6.4.0 build commit:564b89a8c6bef5e329a59f39dac438b13d9cb3fa
### OS version and uname -a
Linux m1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
### Expected behavior
we use sysbench tools to insert data into greenplum database. sysbench version 1.0 
the command is  
./sysbench --threads=10 --test=/var/lib/pgsql/sysbench/share/sysbench/oltp_insert.lua --table-size=100000000 --pgsql-host=x.x.x.x --pgsql-port=5432 --pgsql-user=user1 --pgsql-password=password1 --pgsql-db=sysbench_test --db-driver=pgsql prepare
### Actual behavior
When insert process continue, the memory used increase. I use param gp_vmem_protect_limit=16384, so it's end with error message:
Canceling query because of high VMEM usage. Used: 14731MB, available 1637MB, red zone: 14745MB (runaway_cleaner.c:202)
Actually, I find an issue with the same error , link is  https://github.com/greenplum-db/gpdb/issues/1995
This issue fixed in year 2017, I compare the code and find the code in version gpdb 6.4 is changed differented. so I can't comfirm this issue is solved now.
If the issue #2319 is solved in gpdb 6.4 ,then why the problem still happened . Thanks.
### Step to reproduce the behavior
Install an gpdb 6.4 version , then create user and database , withour any other change , then use sysbench tools to insert data.
If change gp_vmem_protect_limit param more larger ,means use mem larger, will insert more data. But whatever, the memory used is continue increase, and end with VMEM Usage error.

**Comment by kainwen** [comment] 2020-06-17 07:13
What is GUC `optimizer`' s value when you test?

**Comment by paul-guo-** [comment] 2020-06-18 00:27
Please find the memory context related log after the "Canceling query because of high VMEM usage" error message" in pg_log and paste here.

**Comment by yunlik** [comment] 2020-06-22 05:22
> What is GUC `optimizer`' s value when you test?
value is on :
bash-4.2$ gpconfig -s optimizer
Values on all segments are consistent
GUC          : optimizer
Master  value: on
Segment value: on

**Comment by yunlik** [comment] 2020-06-22 05:24
> Please find the memory context related log after the "Canceling query because of high VMEM usage" error message" in pg_log and paste here.

After error message, the pg_log context :
[sysbench_test_error_log.txt](https://github.com/greenplum-db/gpdb/files/4811300/sysbench_test_error_log.txt)

**Comment by kainwen** [comment] 2020-06-22 05:31
> > What is GUC `optimizer`' s value when you test?
> > value is on :
> > bash-4.2$ gpconfig -s optimizer
> > Values on all segments are consistent
> > GUC          : optimizer
> > Master  value: on
> > Segment value: on

Thanks.

Can you re-test your case with `optimizer=false` to see if the issue still exists?

**Comment by yunlik** [comment] 2020-06-22 11:11
> > > What is GUC `optimizer`' s value when you test?
> > > value is on :
> > > bash-4.2$ gpconfig -s optimizer
> > > Values on all segments are consistent
> > > GUC          : optimizer
> > > Master  value: on
> > > Segment value: on
> 
> Thanks.
> 
> Can you re-test your case with `optimizer=false` to see if the issue still exists?

After config the optimizer off, we use sysbench insert 100000000 data successful. Thanks.
It means the optimizer problems，isn't it ?

**Comment by cobolbaby** [comment] 2023-05-09 05:31
Same issue with GP 6.23.0. GP should have a memory leak due to certain operations, and the log contains a lot of errors like `Logging memory usage because of runaway cleanup` or `Canceling query because of high VMEM usage. Used: 92MB, available 1533MB, red zone: 13950MB ` or `One or more query execution processes ran out of memory on this segment`. Finally, I had to restart the GP master node. 

![2023-05-09 12-13-26屏幕截图](https://user-images.githubusercontent.com/11460848/236992282-dfcf3e86-34f1-4757-848c-7f67cb582b7b.png)

How can I analyze and locate the cause of the issue.

```bash
[gpadmin@gp6mdw pg_log]$ ls -ltr| tail -n 30
-rw------- 1 gpadmin gpadmin    7012656 Apr 30 23:59 gpdb-2023-04-30_000000.csv
-rw------- 1 gpadmin gpadmin    2389075 May  1 08:01 gpdb-2023-05-01_000000.csv
-rw------- 1 gpadmin gpadmin       4007 May  2 17:44 gpdb-2023-05-02_174443.csv
-rw------- 1 gpadmin gpadmin    1027237 May  2 23:55 gpdb-2023-05-02_174459.csv
-rw------- 1 gpadmin gpadmin    6991488 May  3 23:59 gpdb-2023-05-03_000000.csv
-rw------- 1 gpadmin gpadmin   24140513 May  5 00:00 gpdb-2023-05-04_000000.csv
-rw------- 1 gpadmin gpadmin   43378813 May  6 00:00 gpdb-2023-05-05_000000.csv
-rw------- 1 gpadmin gpadmin   27337501 May  6 23:59 gpdb-2023-05-06_000000.csv
-rw------- 1 gpadmin gpadmin    5458255 May  7 23:55 gpdb-2023-05-07_000000.csv
-rw------- 1 gpadmin gpadmin 1073743605 May  8 23:22 gpdb-2023-05-08_000000.csv
-rw------- 1 gpadmin gpadmin 1073742612 May  8 23:49 gpdb-2023-05-08_232234.csv
-rw------- 1 gpadmin gpadmin  244738920 May  9 00:00 gpdb-2023-05-08_234928.csv
-rw------- 1 gpadmin gpadmin 1073744736 May  9 00:35 gpdb-2023-05-09_000000.csv
-rw------- 1 gpadmin gpadmin 1073745321 May  9 01:07 gpdb-2023-05-09_003505.csv
-rw------- 1 gpadmin gpadmin 1073743797 May  9 01:40 gpdb-2023-05-09_010728.csv
-rw------- 1 gpadmin gpadmin 1073742632 May  9 02:15 gpdb-2023-05-09_014040.csv
-rw------- 1 gpadmin gpadmin 1073749966 May  9 02:47 gpdb-2023-05-09_021548.csv
-rw------- 1 gpadmin gpadmin 1073747078 May  9 03:23 gpdb-2023-05-09_024720.csv
-rw------- 1 gpadmin gpadmin 1073744784 May  9 04:01 gpdb-2023-05-09_032344.csv
-rw------- 1 gpadmin gpadmin 1073745522 May  9 04:44 gpdb-2023-05-09_040140.csv
-rw------- 1 gpadmin gpadmin 1073743486 May  9 05:27 gpdb-2023-05-09_044411.csv
-rw------- 1 gpadmin gpadmin 1073749837 May  9 06:11 gpdb-2023-05-09_052725.csv
-rw------- 1 gpadmin gpadmin 1073750913 May  9 06:50 gpdb-2023-05-09_061100.csv
-rw------- 1 gpadmin gpadmin 1073743782 May  9 07:35 gpdb-2023-05-09_065029.csv
-rw------- 1 gpadmin gpadmin 1011472546 May  9 09:02 gpdb-2023-05-09_073551.csv
-rw------- 1 gpadmin gpadmin      13507 May  9 09:02 gpdb-2023-05-09_090255.csv
-rw------- 1 gpadmin gpadmin      11264 May  9 09:03 gpdb-2023-05-09_090300.csv
-rw------- 1 gpadmin gpadmin      19750 May  9 09:03 startup.log
-r-------- 1 gpadmin gpadmin        105 May  9 09:03 gp_era
-rw------- 1 gpadmin gpadmin    2154866 May  9 11:33 gpdb-2023-05-09_090320.csv
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-06_*.csv | wc  -l
0
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-07_*.csv | wc  -l
0
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-08_*.csv | wc  -l
1246
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-09_*.csv | wc -l
0
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-07_*.csv | wc -l
0
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-08_*.csv | wc -l
57483
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-09_*.csv | wc -l
333313
```

**Comment by cobolbaby** [comment] 2023-05-09 05:32
Same issue with GP 6.23.0. GP should have a memory leak due to certain operations, and the log contains a lot of errors like `Logging memory usage because of runaway cleanup` or `Canceling query because of high VMEM usage. Used: 92MB, available 1533MB, red zone: 13950MB ` or `One or more query execution processes ran out of memory on this segment`. Finally, I had to restart the GP master node. 

![2023-05-09 12-13-26屏幕截图](https://user-images.githubusercontent.com/11460848/236992282-dfcf3e86-34f1-4757-848c-7f67cb582b7b.png)

How can I analyze and locate the cause of the issue.

```bash
[gpadmin@gp6mdw pg_log]$ ls -ltr| tail -n 30
-rw------- 1 gpadmin gpadmin    7012656 Apr 30 23:59 gpdb-2023-04-30_000000.csv
-rw------- 1 gpadmin gpadmin    2389075 May  1 08:01 gpdb-2023-05-01_000000.csv
-rw------- 1 gpadmin gpadmin       4007 May  2 17:44 gpdb-2023-05-02_174443.csv
-rw------- 1 gpadmin gpadmin    1027237 May  2 23:55 gpdb-2023-05-02_174459.csv
-rw------- 1 gpadmin gpadmin    6991488 May  3 23:59 gpdb-2023-05-03_000000.csv
-rw------- 1 gpadmin gpadmin   24140513 May  5 00:00 gpdb-2023-05-04_000000.csv
-rw------- 1 gpadmin gpadmin   43378813 May  6 00:00 gpdb-2023-05-05_000000.csv
-rw------- 1 gpadmin gpadmin   27337501 May  6 23:59 gpdb-2023-05-06_000000.csv
-rw------- 1 gpadmin gpadmin    5458255 May  7 23:55 gpdb-2023-05-07_000000.csv
-rw------- 1 gpadmin gpadmin 1073743605 May  8 23:22 gpdb-2023-05-08_000000.csv
-rw------- 1 gpadmin gpadmin 1073742612 May  8 23:49 gpdb-2023-05-08_232234.csv
-rw------- 1 gpadmin gpadmin  244738920 May  9 00:00 gpdb-2023-05-08_234928.csv
-rw------- 1 gpadmin gpadmin 1073744736 May  9 00:35 gpdb-2023-05-09_000000.csv
-rw------- 1 gpadmin gpadmin 1073745321 May  9 01:07 gpdb-2023-05-09_003505.csv
-rw------- 1 gpadmin gpadmin 1073743797 May  9 01:40 gpdb-2023-05-09_010728.csv
-rw------- 1 gpadmin gpadmin 1073742632 May  9 02:15 gpdb-2023-05-09_014040.csv
-rw------- 1 gpadmin gpadmin 1073749966 May  9 02:47 gpdb-2023-05-09_021548.csv
-rw------- 1 gpadmin gpadmin 1073747078 May  9 03:23 gpdb-2023-05-09_024720.csv
-rw------- 1 gpadmin gpadmin 1073744784 May  9 04:01 gpdb-2023-05-09_032344.csv
-rw------- 1 gpadmin gpadmin 1073745522 May  9 04:44 gpdb-2023-05-09_040140.csv
-rw------- 1 gpadmin gpadmin 1073743486 May  9 05:27 gpdb-2023-05-09_044411.csv
-rw------- 1 gpadmin gpadmin 1073749837 May  9 06:11 gpdb-2023-05-09_052725.csv
-rw------- 1 gpadmin gpadmin 1073750913 May  9 06:50 gpdb-2023-05-09_061100.csv
-rw------- 1 gpadmin gpadmin 1073743782 May  9 07:35 gpdb-2023-05-09_065029.csv
-rw------- 1 gpadmin gpadmin 1011472546 May  9 09:02 gpdb-2023-05-09_073551.csv
-rw------- 1 gpadmin gpadmin      13507 May  9 09:02 gpdb-2023-05-09_090255.csv
-rw------- 1 gpadmin gpadmin      11264 May  9 09:03 gpdb-2023-05-09_090300.csv
-rw------- 1 gpadmin gpadmin      19750 May  9 09:03 startup.log
-r-------- 1 gpadmin gpadmin        105 May  9 09:03 gp_era
-rw------- 1 gpadmin gpadmin    2154866 May  9 11:33 gpdb-2023-05-09_090320.csv
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-06_*.csv | wc  -l
0
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-07_*.csv | wc  -l
0
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-08_*.csv | wc  -l
1246
[gpadmin@gp6mdw pg_log]$ grep 'Logging memory usage because of runaway cleanup' gpdb-2023-05-09_*.csv | wc -l
0
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-07_*.csv | wc -l
0
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-08_*.csv | wc -l
57483
[gpadmin@gp6mdw pg_log]$ grep 'One or more query execution processes ran out of memory on this segment' gpdb-2023-05-09_*.csv | wc -l
333313
```

**Comment by cobolbaby** [comment] 2023-05-10 03:11
Furthermore, if I want to monitor `VMEM usage`, from which system view can I get that information?

**Comment by gpopt** [comment] 2023-06-02 00:18
Should we give this issue a higher priority?

**Comment by Smyatkin-Maxim** [comment] 2023-06-19 09:38
Took a quick look into this one. My findings are:
1. It does not reproduce on main branch
2. On 6X_STABLE I found out that the culprit is cache accessor`s memory pool. While running sysbench with threads=10 there are about 13 cache accessor pools alive at the same time and only one of them leaks memory.

I didn't find what exactly eats memory in this cache accessor memory pool though. Can take a further look when I come back from vacation ~3-4 weeks later, if it doesn't get solved until then. Also it would be helpful to improve visibility of Memory Contexts created by Orca.

**Comment by Smyatkin-Maxim** [comment] 2023-07-11 12:15
> These were some fixes on main: #15507. Would any of these help?

Yes, I verified locally that backporting #15507 helps. Should we just backport it? Also should we backport the CI pipeline changes?

**Comment by chrishajas** [comment] 2023-07-11 16:34
> > These were some fixes on main: #15507. Would any of these help?
> 
> Yes, I verified locally that backporting #15507 helps. Should we just backport it? Also should we backport the CI pipeline changes?

Yes, let's backport that, including the pipeline changes so we catch these in the future.

**Comment by chrishajas** [comment] 2023-07-14 17:16
I'm currently working on backporting https://github.com/greenplum-db/gpdb/pull/15507 to 6X

**Comment by cobolbaby** [comment] 2023-07-20 03:14
Recently, I have encountered this issue multiple times, and it always happens during index creation. The GP version is 6.24.4.

I wonder if this situation will be reduced or avoided after backporting https://github.com/greenplum-db/gpdb/pull/15507 to 6X?

**Comment by chrishajas** [comment] 2023-07-20 16:10
The backport to 6X is currently in PR here: https://github.com/greenplum-db/gpdb/pull/16007. If it's during create index/copy, I don't think those will be affected though, since these are specific to Orca.

**Comment by chrishajas** [comment] 2023-08-09 23:48
Closing this, as this issue no longer repros internally after https://github.com/greenplum-db/gpdb/pull/16007, thanks for reporting!

**Closed by chrishajas** 2023-08-09 23:48 UTC
Labels: area: gporca, version: 6X_STABLE, Priority 2
