### ISSUE TITLE
[ORCA]: UDF that queries a repliclated table can't run on QE

### ISSUE THREAD

**Issue by entropaos** [greenplum-db/gpdb#14523] opened 2022-11-23 08:29 UTC
### Greenplum version or build
main branch

### Expected behavior
Output 10
### Actual behavior
```
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL statement "SELECT 'OK' || count(*)               FROM rep1"
PL/pgSQL function foo2() line 5 at SQL statement
```
### Step to reproduce the behavior

```sql
create table rep1(a int) distributed replicated;
insert into rep1 select 11;

CREATE TABLE module_test (i int) DISTRIBUTED BY (i);
INSERT INTO module_test select * from generate_series(1, 10);

create or replace function foo2() returns text
as $$
DECLARE
ok text;
BEGIN
    SELECT 'OK' || count(*) INTO ok
      FROM rep1;
    RETURN ok;
END;
$$ LANGUAGE plpgsql;

select count(foo2()) from module_test;
```
Result:
```
gpadmin=# set optimizer=on; explain (verbose) select count(foo2()) from module_test;
SET
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..431.00 rows=1 width=8)
   Output: count(foo2())
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=1)
         ->  Seq Scan on public.module_test  (cost=0.00..431.00 rows=1 width=1)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)

gpadmin=# set optimizer=off; explain (verbose) select count(foo2()) from module_test;
SET
                                        QUERY PLAN
------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=8460.31..8460.32 rows=1 width=8)
   Output: count(foo2())
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=8460.25..8460.30 rows=3 width=8)
         Output: (PARTIAL count(foo2()))
         ->  Partial Aggregate  (cost=8460.25..8460.26 rows=1 width=8)
               Output: PARTIAL count(foo2())
               ->  Seq Scan on public.module_test  (cost=0.00..355.00 rows=32100 width=0)
                     Output: i
 Optimizer: Postgres query optimizer
 Settings: optimizer = 'off'
(10 rows)

gpadmin=# set optimizer=off; select count(foo2()) from module_test;
SET
 count
-------
    10
(1 row)

gpadmin=# set optimizer=on; select count(foo2()) from module_test;
SET
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL statement "SELECT 'OK' || count(*)               FROM rep1"
PL/pgSQL function foo2() line 5 at SQL statement

```

**Comment by kainwen** [comment] 2022-11-23 10:49
Actually I don't think this is a bug. In MPP database, the function might depends on the execution location, for this case, this function has to be execute on a single host. Currently GPDB does not have a storage type for function.

And the workaround is very simple:

```
gpadmin=# explain verbose select count(a) from (select foo2() from module_test)x(a)
;
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..431.00 rows=1 width=8)
   Output: count((foo2()))
   ->  Gather Motion 2:1  (slice1; segments: 2)  (cost=0.00..431.00 rows=1 width=8)
         Output: (foo2())
         ->  Seq Scan on public.module_test  (cost=0.00..431.00 rows=1 width=1)
               Output: foo2()
 Optimizer: Pivotal Optimizer (GPORCA)
(7 rows)
gpadmin=# select count(a) from (select foo2() from module_test)x(a)
;
 count
-------
    10
(1 row)
```

------

@gpopt please take a look to double confirm. From my side I tend to close this since we don't plan to do any modification.

**Comment by gpopt** [comment] 2022-11-23 19:29
I think Orca should support this too.

```sql
set optimizer_force_multistage_agg =on;
explain select count(foo2()) from module_test;
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=0.00..431.00 rows=1 width=8)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=8)
         ->  Partial Aggregate  (cost=0.00..431.00 rows=1 width=8)
               ->  Seq Scan on module_test  (cost=0.00..431.00 rows=1 width=1)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)

select count(foo2()) from module_test;
 count
-------
    10
(1 row)
```

```sql
set optimizer_force_multistage_agg =off;
explain select count(foo2()) from module_test;
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..431.00 rows=1 width=8)
   ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=1)
         ->  Seq Scan on module_test  (cost=0.00..431.00 rows=1 width=1)
 Optimizer: Pivotal Optimizer (GPORCA)
(4 rows)
explain analyze select count(foo2()) from module_test;
ERROR:  query plan with multiple segworker groups is not supported
HINT:  likely caused by a function that reads or modifies data in a distributed table
CONTEXT:  SQL statement "SELECT 'OK' || count(*)               FROM rep1"
PL/pgSQL function foo2() line 5 at SQL statement
```

Yes, it is a bug.

**Comment by kainwen** [comment] 2022-11-24 03:44
Have an offline discussion with @gpopt , we tend to close this.

The problem is subtle, it is UDF as expression's evaluation position. Currently, users have to manually tune the SQL based on MPP knowledge. 

Reference https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/DkTx4O-kuH0

**Closed by kainwen** 2022-11-24 03:44 UTC
Labels: type: bug, area: gporca
