### ISSUE TITLE
Query locks up with gp_cte_sharing=on

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#1617] opened 2017-01-24 06:02 UTC
This query locks up forever, or until cancelled:
```
create table testsisc (i1 integer, i2 integer);
insert into testsisc values (1, 1);
set gp_cte_sharing=on;
with ctesisc as
     (select * from testsisc order by i2)
   select i1 from ctesisc where 1=2
   union all
   select count(*) from ctesisc t;
```

See discussion at https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/gMa1tW0x_fk. This issue is to make sure we don't forget about it.

**Comment by vraghavan78** [comment] 2017-03-08 07:23
Please check if it is a duplicate of #1967

**Comment by hsyuan** [comment] 2017-04-25 20:51
This issue has similar root cause with #1967 

See the plan below:
![image](https://cloud.githubusercontent.com/assets/15352793/25407060/c3825382-29bd-11e7-8497-bc8f9f4af596.png)

The CTE producer is not executed because the 1st child of `Append` has a one-time filter `false`. But the CTE consumer in the 2nd child of `Append` is always waiting for the producer to finish the writing. Hence it hangs for ever.

**Comment by BaiShaoqi** [comment] 2019-01-08 08:58
This appears to be fixed on master. We are planning on closing it.

**Comment by danielgustafsson** [comment] 2019-01-25 23:37
This indeed works in master (with the below plan), and I've been unable to tweak the query to reproduce any similar bug. 
```
                                            QUERY PLAN
--------------------------------------------------------------------------------------------------
 Append  (cost=0.00..0.12 rows=2 width=4)
   ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..0.02 rows=1 width=0)
         ->  Result  (cost=0.00..0.01 rows=1 width=0)
               One-Time Filter: false
   ->  Aggregate  (cost=0.09..0.10 rows=1 width=8)
         ->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.02..0.07 rows=1 width=8)
               ->  Aggregate  (cost=0.02..0.03 rows=1 width=8)
                     ->  Subquery Scan on t  (cost=0.00..0.02 rows=1 width=0)
                           ->  Shared Scan (share slice:id 1:0)  (cost=1.02..1.23 rows=1 width=8)
                                 ->  Sort  (cost=1.02..1.02 rows=1 width=8)
                                       Sort Key: testsisc.i2
                                       ->  Seq Scan on testsisc  (cost=0.00..1.01 rows=1 width=8)
 Optimizer: legacy query optimizer
(13 rows)
```
I haven't been able to pinpoint the commit that fixed it, but given the amount of code changes which has happened since this was opened it's hard to tell. Closing.

**Closed by danielgustafsson** 2019-01-25 23:37 UTC
Labels: 8.4-9.0 CTE, Planner, bug
