### ISSUE TITLE
client jdbc connection poool cause "Unexpected internal error: Master process received signal SIGSEGV"

### ISSUE THREAD

**Issue by kingour** [greenplum-db/gpdb#4965] opened 2018-05-10 07:08 UTC
### Greenplum version or build
5.8.0
### OS version and uname -a
Linux 3.10.0-327.el7.x86_64 #1
### autoconf options used ( config.status --config )
ORCA is enabled
### Installation information ( pg_config )
NA
### Expected behavior
Master must not fail on executing with jdbc connection pool like HikariCP
### Actual behavior
Master fails
```
"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f8a2e5fb5e0 libpthread.so.0 <symbol not found> + 0x2e5fb5e0
2    0x710878 postgres list_free (list.c:1099)
3    0x6a67c2 postgres FreeExecutorState (execUtils.c:224)
4    0x68f160 postgres ExecutorEnd (execMain.c:1106)
5    0x63a396 postgres PortalCleanup (discriminator 2)
6    0x98e4bd postgres PortalDrop (portalmem.c:347)
7    0x98eb3f postgres AtCommit_Portals (portalmem.c:706)
8    0x5194cd postgres CommitTransaction (xact.c:2594)
9    0x51a2b5 postgres CommitTransactionCommand (xact.c:3658)
10   0x82db23 postgres <symbol not found> (postgres.c:3226)
"
```
#### master failes
```
CREATE TABLE demo (
    id varchar not null,
    versionId varchar NOT NULL,
    date date NOT NULL,
    update timestamp DEFAULT current_timestamp,
    pv bigint default null
) 
DISTRIBUTED BY (id, versionId) 
PARTITION BY RANGE (date) 
( START (date '2018-04-21') INCLUSIVE
   END (date '2018-05-21') EXCLUSIVE
   EVERY (INTERVAL '1 day') );

# use HikariCP to query like this
select '1' as d from demo where id='2068801' order by d
```
#### Query executed successfully
```
CREATE TABLE demo (
    id varchar not null,
    versionId varchar NOT NULL,
    date date NOT NULL,
    update timestamp DEFAULT current_timestamp,
    pv bigint default null
) 
DISTRIBUTED BY (id, versionId);

# use HikariCP to query like this
select '1' as d from demo where id='2068801' order by d
```

**Comment by yydzero** [comment] 2018-05-16 07:07
Thanks @kingour for reporting!

So you encountered SIGSEGV even there is no data?

Would you please create a single github repo which includes all of your java code with dependencies?  Not everyone have Java experience here, so it is will be much easier if you could help make the reproduce steps as simple as possible.

**Comment by kingour** [comment] 2018-05-16 07:51
ok, i will share the simple project

**Comment by kingour** [comment] 2018-05-16 08:32
@yydzero https://github.com/kingour/gpdb-jdbc-test
this is the project

**Comment by yydzero** [comment] 2018-05-17 05:08
I could not reproduce this issue. Though I have not enabled ORCA (I don't think this is related with ORCA though)

```
yydzero=# SELECT version();
                                                                                                              version
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.3.23 (Greenplum Database 5.8.0+dev.34.gb1be9e7121 build dev) on x86_64-apple-darwin16.6.0, compiled by GCC Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit compiled on May 17 2018 13:02:06 (with assert checking)
(1 row)
```

```
 2018-05-17 12:58:09 ⌚  yydzero in ~/work/workspace/tmp/gpdb-jdbc-test
± |master U:1 ✗| → java -jar target/gpdb-jdbc-test-2018051704.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2018-05-17 13:06:44.266  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.App                : Starting App v1.0-SNAPSHOT on yydzero.local with PID 64397 (/Users/yydzero/work/workspace/tmp/gpdb-jdbc-test/target/gpdb-jdbc-test-2018051704.jar started by yydzero in /Users/yydzero/work/workspace/tmp/gpdb-jdbc-test)
2018-05-17 13:06:44.270  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.App                : No active profile set, falling back to default profiles: default
2018-05-17 13:06:44.328  INFO 64397 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@c2e1f26: startup date [Thu May 17 13:06:44 CST 2018]; root of context hierarchy
2018-05-17 13:06:45.620  INFO 64397 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-17 13:06:45.621  INFO 64397 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'dataSource' has been autodetected for JMX exposure
2018-05-17 13:06:45.626  INFO 64397 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2018-05-17 13:06:45.756  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.App                : {
	"version":1
}
2018-05-17 13:06:45.756  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.App                : Begin to run task.
2018-05-17 13:06:45.757  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : begin to do test...
2018-05-17 13:06:45.757  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 0: ...
2018-05-17 13:06:45.778  INFO 64397 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Started.
2018-05-17 13:06:45.995  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 1: ...
2018-05-17 13:06:46.001  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 2: ...
2018-05-17 13:06:46.009  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 3: ...
2018-05-17 13:06:46.016  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 4: ...
2018-05-17 13:06:46.028  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 5: ...
2018-05-17 13:06:46.035  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 6: ...
2018-05-17 13:06:46.042  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 7: ...
2018-05-17 13:06:46.051  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 8: ...
2018-05-17 13:06:46.058  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 9: ...
2018-05-17 13:06:46.065  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 0: ...
2018-05-17 13:06:46.101  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 1: ...
2018-05-17 13:06:46.115  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 2: ...
2018-05-17 13:06:46.128  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 3: ...
2018-05-17 13:06:46.144  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 4: ...
2018-05-17 13:06:46.158  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 5: ...
2018-05-17 13:06:46.167  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 6: ...
2018-05-17 13:06:46.177  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 7: ...
2018-05-17 13:06:46.187  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 8: ...
2018-05-17 13:06:46.197  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 9: ...
2018-05-17 13:06:46.210  INFO 64397 --- [           main] com.kingour.jdbc.gpdb.App                : Started App in 2.353 seconds (JVM running for 3.304)
2018-05-17 13:06:46.211  INFO 64397 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@c2e1f26: startup date [Thu May 17 13:06:44 CST 2018]; root of context hierarchy
2018-05-17 13:06:46.212  INFO 64397 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-05-17 13:06:46.212  INFO 64397 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-05-17 13:06:46.213  INFO 64397 --- [       Thread-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Close initiated...
2018-05-17 13:06:46.215  INFO 64397 --- [       Thread-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Closed.

```

**Comment by yydzero** [comment] 2018-05-17 05:09
There are below log info, while no error: `No such file or directory"` not sure whether it is related with your logic...

```
2018-05-17 13:06:46.200828 CST,"yydzero","yydzero",p64399,th-822291520,"127.0.0.1","61489",2018-05-17 13:06:45 CST,0,con8,cmd20,seg-1,,dx25,,sx1,"LOG","00000","execute S_2: select '1' as d from demo_prt where id='2068801' order by d",,,,,,"select '1' as d from demo_prt where id='2068801' order by d",0,,"postgres.c",2741,
2018-05-17 13:06:46.204843 CST,"yydzero","yydzero",p64399,th-822291520,"127.0.0.1","61489",2018-05-17 13:06:45 CST,0,con8,cmd20,seg-1,,dx25,,sx1,"LOG","00000","could not unlink file ""base/16384/pgsql_tmp/pgsql_tmp_sess8_w64399_qdxid25_qdcid0_sync1"": No such file or directory",,,,,,,0,,"fd.c",1165,
```

**Comment by kingour** [comment] 2018-05-17 06:32
that is strange

**Comment by yydzero** [comment] 2018-05-17 06:34
I tried on both 5.8/5.3 and master.

Could you please try to diagnose it on your env or maybe switch to a new env.

**Comment by kingour** [comment] 2018-05-17 06:37
set optimizer off，the problem will disappear

**Comment by kingour** [comment] 2018-05-17 06:37
so set optimizer on, have a try

**Comment by yydzero** [comment] 2018-05-17 06:43
sounds like orca related, add @vraghavan78

**Comment by kingour** [comment] 2018-05-17 06:45
This is my test:
```
psql (8.3.23)
Type "help" for help.

demo=> show optimizer;
 optimizer
-----------
 on
(1 row)


kingour@Kingour-WIN-10 /d/WorkApp/git/gpdb-jdbc-test/target master$ java -jar gpdb-jdbc-test-2018051706.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

2018-05-17 14:42:43.438  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.App                : Starting App v1.0-SNAPSHOT on Kingour-WIN-10 with PID 23240 (D:\WorkApp\git\gpdb-jdbc-test\target\gpdb-jdbc-test-2018051706.jar started by kingour in D:\WorkApp\git\gpdb-jdbc-test\target)
2018-05-17 14:42:43.453  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.App                : No active profile set, falling back to default profiles: default
2018-05-17 14:42:43.629  INFO 23240 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1c655221: startup date [Thu May 17 14:42:43 CST 2018]; root of context hierarchy
2018-05-17 14:42:47.484  INFO 23240 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-05-17 14:42:47.488  INFO 23240 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'dataSource' has been autodetected for JMX exposure
2018-05-17 14:42:47.496  INFO 23240 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2018-05-17 14:42:47.811  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.App                : {
        "version":1
}
2018-05-17 14:42:47.813  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.App                : Begin to run task.
2018-05-17 14:42:47.814  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : begin to do test...
2018-05-17 14:42:47.815  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 0: ...
2018-05-17 14:42:47.884  INFO 23240 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Started.
2018-05-17 14:42:48.761  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 1: ...
2018-05-17 14:42:48.793  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 2: ...
2018-05-17 14:42:48.835  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 3: ...
2018-05-17 14:42:48.860  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 4: ...
2018-05-17 14:42:48.888  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 5: ...
2018-05-17 14:42:48.918  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 6: ...
2018-05-17 14:42:48.933  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 7: ...
2018-05-17 14:42:49.150  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 8: ...
2018-05-17 14:42:49.167  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing no partition 9: ...
2018-05-17 14:42:49.183  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 0: ...
2018-05-17 14:42:49.306  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 1: ...
2018-05-17 14:42:49.344  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 2: ...
2018-05-17 14:42:49.378  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 3: ...
2018-05-17 14:42:49.411  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 4: ...
2018-05-17 14:42:49.443  INFO 23240 --- [           main] com.kingour.jdbc.gpdb.service.PgService  : Testing with partition 5: ...
2018-05-17 14:42:49.474  WARN 23240 --- [           main] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@5faeada1 marked as broken because of SQLSTATE(08006), ErrorCode(0)

org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:332)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
        at com.sun.proxy.$Proxy43.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:231)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
```

**Comment by wangd** [comment] 2018-07-06 18:12
We saw something similar in our installation. While trying to integrate HikariCP into our application, we saw lots of connection disruption and PANICs as well. The PANICs we see look like:
```
2018-07-05 23:00:11.824481 UTC,,,p15946,th0,,,2018-07-05 22:46:05 UTC,0,con47905,cmd28,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x9238c3 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x163
2    0x7f7fcacb5100 libpthread.so.0 <symbol not found> + 0xcacb5100
3    0x5a9757 postgres transformStmt + 0x17
4    0x5ab869 postgres parse_analyze + 0x39
5    0x80d654 postgres pg_analyze_and_rewrite + 0x24
6    0x8fc4b3 postgres RevalidateCachedPlanWithParams + 0x103
7    0x80d12a postgres <symbol not found> + 0x80d12a
8    0x80f0c7 postgres PostgresMain + 0x9b7
9    0x7b30d6 postgres <symbol not found> + 0x7b30d6
10   0x7b4a92 postgres PostmasterMain + 0xc62
11   0x4c7c3d postgres main + 0x39d
12   0x7f7fca0e6b15 libc.so.6 __libc_start_main + 0xf5
13   0x4c81cf postgres <symbol not found> + 0x4c81cf
"
```
The stack trace always looks the same. We do "SET OPTIMIZER = ON" selectively for some queries and suspect that the resetting that Hikari does when returning connections to the pool is insufficient or imperfect in some way when "set optimizer = ??" is used. I think Hikari tries to detect these so it can do more optimized isolation. Is anyone working on this? In the meantime, we're going back to PGPoolingDataSource.

**Comment by vladimirschuka** [comment] 2019-05-22 13:06
I have the same problem maybe not the same but similar. 
I use Intellij with postgres 9.4 (postgresql-9.4.1212)  driver for Greenplum and what I noticed. if I work with db all the time everything is fine, but if I have a break about 10 minutes or more and then return to the same windows with opened session and the first query which I try to execute gives me the error:

"FATAL","57P03","the database system is in recovery mode

and in the log I have:

2019-05-22 12:44:40.875377 CEST,,,p27626,th0,,,2019-05-22 11:59:40 CEST,0,con1620540,cmd15,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x92b896 postgres StandardHandlerForSigillSigsegvSigbus_OnMainThread + 0x176
2019-05-22 12:44:41.101708 CEST,,,p21775,th-1743562944,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 27626) was terminated by signal 11: Segmentation fault",,,,,,,0,,"postmaster.c",5611,
2019-05-22 12:44:41.101834 CEST,,,p21775,th-1743562944,,,,0,,,seg-1,,,,,"LOG","00000","terminating any other active server processes",,,,,,,0,,"postmaster.c",5290,

and all sessions were terminated.
It looks like jdbc driver breaks server. 
Thx

**Comment by asimrp** [comment] 2019-05-23 06:30
I was not able to reproduce this with the java app from @kingour with `optimizer=on`.  I tried 5X and master.

@vladimirschuka, @wangd if you have a repro that we can try, it will be very helpful to make progress on this issue.

**Comment by ivannovick** [comment] 2020-06-08 19:25
closing for no repro

**Closed by ivannovick** 2020-06-08 19:25 UTC
Labels: area: server, note: hacktoberfest, note: help wanted
