### ISSUE TITLE
tablespace is not created but some directories left

### ISSUE THREAD

**Issue by gaos1** [greenplum-db/gpdb#8147] opened 2019-07-16 09:10 UTC
### Greenplum version or build
Greenplum Version: 'postgres (Greenplum Database) 6.0.0-beta.4
### OS version and uname -a
Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### Step to reproduce the behavior
The user tried several commands to create tablespace and none seems correct. There is no additional tablespace in pg_tablespace. however, some tablespace directories were left in the cluster and caused gpexpand failure.  The inconsistency might also trigger other issue. 

![image](https://user-images.githubusercontent.com/17909638/61263315-f9e80980-a7ba-11e9-9256-4c926794ea9e.jpg)

```
gpadmin@gpdb-g2-node1:~$ psql postgres
psql (9.4.20)
Type "help" for help.

postgres=# select * from pg_tablespace;
  spcname   | spcowner | spcacl | spcoptions 
------------+----------+--------+------------
 pg_default |       10 |        | 
 pg_global  |       10 |        | 
(2 rows)

postgres=#
```

The log contains the following tablespace creation output: 
```
○ → ag "create tablespace"
gpdb-2019-07-12_034557.csv
3233:2019-07-12 05:49:51.818623 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd5,seg-1,,dx170,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/gpdb';",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb';",0,,"postgres.c",1617,
3234:2019-07-12 05:49:51.992139 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,749,con22,cmd5,seg-1,,dx170,x749,sx1,"ERROR","42501","could not set permissions on directory ""/gpdb"": Operation not permitted",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb';",0,,"tablespace.c",666,"Stack trace:
3250:2019-07-12 05:49:51.992396 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,749,con22,cmd5,seg-1,,dx170,x749,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/gpdb';",,,,,,,0,,,,
3251:2019-07-12 05:50:05.938215 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd6,seg-1,,dx171,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/master';",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/master';",0,,"postgres.c",1617,
3252:2019-07-12 05:50:05.956833 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,750,con22,cmd6,seg-1,,dx171,x750,sx1,"ERROR","58P01","directory ""/gpdb/master"" does not exist  (seg0 172.16.2.36:6000 pid=27316)",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/master';",0,,"tablespace.c",661,
3253:2019-07-12 05:50:05.956922 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,750,con22,cmd6,seg-1,,dx171,x750,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/master';",,,,,,,0,,,,
3254:2019-07-12 05:50:24.402257 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd7,seg-1,,dx172,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",0,,"postgres.c",1617,
3255:2019-07-12 05:50:24.402469 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,751,con22,cmd7,seg-1,,dx172,x751,sx1,"ERROR","58P01","directory ""/gpdb/segment1"" does not exist",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",0,,"tablespace.c",661,
3256:2019-07-12 05:50:24.402511 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,751,con22,cmd7,seg-1,,dx172,x751,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",,,,,,,0,,,,
3257:2019-07-12 05:50:54.881703 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd8,seg-1,,dx173,,sx1,"ERROR","42601","syntax error at or near "";""",,,,,,"CREATE TABLESPACE testtbs ;",27,,"scan.l",1066,
3258:2019-07-12 05:50:54.881789 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd8,seg-1,,dx173,,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs ;",,,,,,,0,,,,
3259:2019-07-12 05:51:18.409174 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd9,seg-1,,dx174,,sx1,"ERROR","42601","syntax error at or near "";""",,,,,,"create tablespace 
3261:2019-07-12 05:51:18.409262 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd9,seg-1,,dx174,,sx1,"LOG","00000","An exception was encountered during the execution of statement: create tablespace 
3503:2019-07-12 05:51:47.569068 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd10,seg-1,,dx215,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/;
3509:;",,,,,,"CREATE TABLESPACE testtbs LOCATION '/;
3521:"" does not exist",,,,,"CREATE TABLESPACE testtbs LOCATION '/;
3528:2019-07-12 05:51:47.569339 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,752,con22,cmd10,seg-1,,dx215,x752,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/;
3535:2019-07-12 05:51:56.296942 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd11,seg-1,,dx216,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/';",,,,,,"CREATE TABLESPACE testtbs LOCATION '/';",0,,"postgres.c",1617,
3536:2019-07-12 05:51:56.313112 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,753,con22,cmd11,seg-1,,dx216,x753,sx1,"ERROR","42501","could not set permissions on directory ""/"": Operation not permitted",,,,,,"CREATE TABLESPACE testtbs LOCATION '/';",0,,"tablespace.c",666,"Stack trace:
3552:2019-07-12 05:51:56.313287 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,753,con22,cmd11,seg-1,,dx216,x753,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/';",,,,,,,0,,,,
3553:2019-07-12 05:52:17.680488 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,0,con22,cmd12,seg-1,,dx217,,sx1,"LOG","00000","statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",0,,"postgres.c",1617,
3554:2019-07-12 05:52:17.680699 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,754,con22,cmd12,seg-1,,dx217,x754,sx1,"ERROR","58P01","directory ""/gpdb/segment1"" does not exist",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",0,,"tablespace.c",661,
3555:2019-07-12 05:52:17.680745 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,754,con22,cmd12,seg-1,,dx217,x754,sx1,"LOG","00000","An exception was encountered during the execution of statement: CREATE TABLESPACE testtbs LOCATION '/gpdb/segment1';",,,,,,,0,,,,
```

The full log is here: 
https://github.com/greenplum-db/gpdb/files/3395927/gpdb-master-log-0712.zip

More history about the issue. please see #8135.

**Comment by yangjiurong** [comment] 2019-07-16 09:39
Thank you @gaos1   for helping me solve the #8135  problem . At present, there is a strange problem that has not found the reason. If you need information about the cluster where this problem is located, and you can publish the issue at any time,I will update the required information in time.

谢谢gaos1帮我解决了 #8135  问题。目前还有个奇怪的问题没有找到原因，大家如果需要这个问题所在集群的相关信息，可以随时发布问题，我会及时更新所需信息。

**Comment by soumyadeep2007** [comment] 2019-07-18 20:42
@gaos1 I couldn't access the log file: https://github.com/greenplum-db/gpdb/files/3395927/gpdb-master-log-0712.zip.

**Comment by yangjiurong** [comment] 2019-07-19 01:25
@soumyadeep2007 
Because of the network, the connection may fail. I upload a new copy.
由于网络的原因，该连接可能失效了，我重新上传一份。

[gpdb-master-log-0712.zip](https://github.com/greenplum-db/gpdb/files/3408999/gpdb-master-log-0712.zip)

**Comment by soumyadeep2007** [comment] 2019-07-23 19:27
So the problem seems to have been caused by the command:
`CREATE TABLESPACE testtbs LOCATION '/gpdb/master'`
On seg0 we get the following:
```
2019-07-12 05:50:05.956833 UTC,"gpadmin","postgres",p20335,th2113409920,"[local]",,2019-07-12 05:44:10 UTC,750,con22,cmd6,seg-1,,dx171,x750,sx1,"ERROR","58P01","directory ""/gpdb/master"" does not exist  (seg0 172.16.2.36:6000 pid=27316)",,,,,,"CREATE TABLESPACE testtbs LOCATION '/gpdb/master';",0,,"tablespace.c",661,
```
This means that the tablespace location dir: /gpdb/master did not exist on seg0. Since it did exist on master, it left the dangling directory and symlink after the command failed. 

This class of problem has been fixed with the recent work on cleaning up after failed CREATE TABLESPACE statements such as this. 
Please refer: and 122c79f20950f41bf1a796675598add4120ee4 on master and its backport on 6X_STABLE: a36ebdbbd90c28739e2f8b21b10be18f90dd3fba.

**Closed** 2019-08-16 03:00 UTC
