### ISSUE TITLE
can not find pathkey

### ISSUE THREAD

**Issue by kainwen** [greenplum-db/gpdb#8987] opened 2019-11-05 09:12 UTC
### Greenplum version or build

Orca does not have such issue.  Planner has.

Master, 6X both have such issue.

However 5X does not have such issue.

```sql
create table t1(c1 int, c2 int, c3 int);
create table t2(c1 int, c2 int, c3 int);
create table t3(c1 int, c2 int, c3 int);

set enable_hashagg = off;

with haha(c1, c2, c3) as (
	select c1, sum(c2) as c2, c3 from t1 where c3 > 0 group by c1, c3
	union all
	select c1, sum(c2) as c2, c3 from t2 where c3 < 0 group by c1, c3
)

select * from haha where c3 = 1;

could not find pathkey item to sort (createplan.c:5614)
```

**Comment by weinan003** [comment] 2019-11-06 04:55
I can reproduce it in both merge and 6x.
will try to fix it

**Comment by weinan003** [comment] 2019-12-12 09:51
I spike this issue again, and I think I find out the root cause. Compare with upstream, gpdb force to pull up subquery's pathkeys
The reason is that a gather motion needs to keep subquery's data order. For instance, a path like that:
```
Gather Motion
 \
  Subquery Scan
   \
   Sort
```
If the Subquery Scan does not have pathkeys GatherMotion can not give the order result.
This situation always happens like, we a view `select ..... order by a;`. If we simply select the view,
the result should keep order.

But, the current method is clearly wrong, because subquery's range table list is not always the same as its parent. If the range table list is different, this issue is triggered.

**Comment by weinan003** [comment] 2020-01-17 08:38
Fix it in master so far.
Since 6X_STABLE does not contain pathfication, the patch can not simply cherry-pick

**Comment by gaos1** [comment] 2020-02-17 06:36
fixed by https://github.com/greenplum-db/gpdb/pull/9575

**Closed by gaos1** 2020-02-17 06:36 UTC
Labels: topic: planner, type: bug, version: 6X_STABLE
