### ISSUE TITLE
Wrong lock mode used for UPDATE / DELETE of the AO/AOCS partitioned table

### ISSUE THREAD

**Issue by linxuh** [greenplum-db/gpdb#15479] opened 2023-05-05 07:44 UTC
## Bug Report

With GDD enabled, when update / delete on AO/AOCS partitioned table (without unique index), i found that RowExclusiveLock was used instead of ExclusiveLock. 

After #13897  , RelationIsAppendOptimized is changed to false when relation is a partitioned table, which changed lock level to RowExclusiveLock when update / delete AO/AOCS table. Is this expected behavior or a bug?

### Greenplum version or build
master branch

### Step to reproduce the behavior
```
create table partlockt (i int, t text) using ao_row
partition by range(i)
(start(1) end(10) every(1));

begin;
delete from partlockt where i = 4;
select * from pg_locks where relation = 'partlockt_1_prt_4'::regclass;
select * from pg_locks where relation = 'partlockt'::regclass;
```

**Comment by kainwen** [comment] 2023-05-05 20:37
Greenplum is MPP database, holding RowExclusive Lock for Update|Delete statement will lead concurrently update|delete happen on segment which means it is possible for transactions wait for others on segments. This can lead to global deadlock.

Since Greenplum 6, we introduce global deadlock detector, when it is turned on, for heap table's update | delete, we can hold the same lock level as Postgres.

However, even with global deadlock detector enabled,  for AO|AOCS table, due to its implementation of visibility map design, it does not support concurrenly update|delete on segments. That is why Greenplum always hold Exclusive Lock for AO|AOCS tables. This is documented behavior: https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/admin_guide-dml.html .

I close this issue, feel free to reopen if needed.

**Comment by linxuh** [comment] 2023-05-06 01:51
> That is why Greenplum always hold Exclusive Lock for AO|AOCS tables. This is documented behavior: https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/admin_guide-dml.html .

I found that RowExclusiveLock was used instead of ExclusiveLock, when update / delete on AO/AOCS partitioned table, on master branch, Is this an expected behavior?

**Comment by kainwen** [comment] 2023-05-06 03:30
> > That is why Greenplum always hold Exclusive Lock for AO|AOCS tables. This is documented behavior: https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/admin_guide-dml.html .
> 
> I found that RowExclusiveLock was used instead of ExclusiveLock, when update / delete on AO/AOCS partitioned table, it is not an expected behavior based on the doc, can't you reproduce it on the master branch? @kainwen

Super sorry that I misread.

But I don't reproduce the issue:


```
gpadmin=# select version();
                                                                                                                   version

------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.2+dev.187.g57d95c62b3 build dev) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 12.2.0-17ubuntu1) 12
.2.0, 64-bit compiled on May  2 2023 12:43:42 (with assert checking) Bhuvnesh C.
(1 row)
gpadmin=# begin;
delete from partlockt where i = 4;
select * from pg_locks where relation = 'partlockt_1_prt_4'::regclass;
select * from pg_locks where relation = 'partlockt'::regclass;
BEGIN
DELETE 0
 locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid  |     mode      | grant
ed | fastpath | mppsessionid | mppiswriter | gp_segment_id
----------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+------+---------------+------
---+----------+--------------+-------------+---------------
 relation |    16384 |    16418 |      |       |            |               |         |       |          | 5/26               | 4677 | ExclusiveLock | t
   | f        |           18 | t           |            -1
 relation |    16384 |    16418 |      |       |            |               |         |       |          | 3/54               | 4695 | ExclusiveLock | t
   | f        |           18 | t           |             0
(2 rows)
```

**Comment by linxuh** [comment] 2023-05-09 06:34
> > > That is why Greenplum always hold Exclusive Lock for AO|AOCS tables. This is documented behavior: https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/admin_guide-dml.html .
> > 
> > 
> > I found that RowExclusiveLock was used instead of ExclusiveLock, when update / delete on AO/AOCS partitioned table, it is not an expected behavior based on the doc, can't you reproduce it on the master branch? @kainwen
> 
> Super sorry that I misread.
> 
> @linxuh
> 
> But I don't reproduce the issue:
> 
> ```
> gpadmin=# select version();
>                                                                                                                    version
> 
> ------------------------------------------------------------------------------------------------------------------------------------------------------------
> ---------------------------------------------------------------------------------
>  PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.2+dev.187.g57d95c62b3 build dev) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 12.2.0-17ubuntu1) 12
> .2.0, 64-bit compiled on May  2 2023 12:43:42 (with assert checking) Bhuvnesh C.
> (1 row)
> gpadmin=# begin;
> delete from partlockt where i = 4;
> select * from pg_locks where relation = 'partlockt_1_prt_4'::regclass;
> select * from pg_locks where relation = 'partlockt'::regclass;
> BEGIN
> DELETE 0
>  locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid  |     mode      | grant
> ed | fastpath | mppsessionid | mppiswriter | gp_segment_id
> ----------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+------+---------------+------
> ---+----------+--------------+-------------+---------------
>  relation |    16384 |    16418 |      |       |            |               |         |       |          | 5/26               | 4677 | ExclusiveLock | t
>    | f        |           18 | t           |            -1
>  relation |    16384 |    16418 |      |       |            |               |         |       |          | 3/54               | 4695 | ExclusiveLock | t
>    | f        |           18 | t           |             0
> (2 rows)
> ```

That's weird, I can reproduce the issue:
```
postgres=# select version();
                                                                                                           version                             
                                                                               
-----------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.0 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.2.1 20200522 (Alibaba 9.2.1-3 2.1
7), 64-bit compiled on May  6 2023 16:34:58 (with assert checking) Bhuvnesh C.
(1 row)

postgres=# create table partlockt (i int, t text) using ao_row
postgres-# partition by range(i)
postgres-# (start(1) end(10) every(1));
CREATE TABLE

postgres=# begin;
BEGIN
postgres=# delete from partlockt where i = 4;
DELETE 0
postgres=# select mode, gp_segment_id  from pg_locks where relation = 'partlockt'::regclass;
       mode       | gp_segment_id 
------------------+---------------
 AccessShareLock  |            -1
 RowExclusiveLock |            -1
 AccessShareLock  |             0
 RowExclusiveLock |             0
(4 rows)

postgres=# select mode, gp_segment_id  from pg_locks where relation = 'partlockt_1_prt_4'::regclass;
       mode       | gp_segment_id 
------------------+---------------
 RowExclusiveLock |            -1
 RowExclusiveLock |             0
(2 rows)
```
In CdbTryOpenTable, RelationIsAppendOptimized is false for partitioned table, so RowExclusiveLock is used. Maybe add a new macro definition works for this issue
```
#define RelationIsAO(relation) \
	((RelationIsAoRows(relation) || RelationIsAoCols(relation))
```

**Comment by linxuh** [comment] 2023-05-09 07:44
I'm not quite sure why the partitioned table is excluded from the result of RelationIsAppendOptimized, instead of introducing a new macro like RelationIsAppendOptimizedWithOutPartitonedTable, since plenty of code is written based on the previous semantics. Also, why RelationIsHeap do not have the same problem or modification？

**Comment by kainwen** [comment] 2023-05-09 08:24
@linxuh I know why. The issue is there when GDD is enabled. I should figure it out at the 1st glance (sorry for previous reply, must due to jet lag ...)

Good catch!

@haolinw can you please follow this issue:

* fix this issue
* spike the history of https://github.com/greenplum-db/gpdb/issues/15479#issuecomment-1539620211 and see if there is any other impact

**Comment by charliettxx** [comment] 2023-05-10 07:41
I think we could just fix it by ((RelationIsAoRows(relation) || RelationIsAoCols(relation)) instread of RelationIsAppendOptimized(rel) as a simple way.
```
lockmode = RowExclusiveLock;
rel = try_table_open(relid, lockmode, false);
if ((RelationIsAoRows(relation) || RelationIsAoCols(relation))
{
        xxxxxx
}
```

But more important thing is as we need to know  @linxuh said why  the partitioned table is excluded from macro 
RelationIsAppendOptimized.

**Comment by kainwen** [comment] 2023-05-10 10:21
> I think we could just fix it by ((RelationIsAoRows(relation) || RelationIsAoCols(relation)) instread of RelationIsAppendOptimized(rel) as a simple way.
> 
> ```
> lockmode = RowExclusiveLock;
> rel = try_table_open(relid, lockmode, false);
> if ((RelationIsAoRows(relation) || RelationIsAoCols(relation))
> {
>         xxxxxx
> }
> ```
> 
> But more important thing is as we need to know @linxuh said why the partitioned table is excluded from macro RelationIsAppendOptimized.

You can git blame the introduced commit and look for some background. @charliettxx

**Comment by huansong** [comment] 2023-05-10 18:46
Hi @linxuh and @charliettxx , thanks for reporting the issue and proposing the fix. 

Firstly, the reason why `RelationIsAppendOptimized` was changed to exclude partition table in https://github.com/greenplum-db/gpdb/pull/13897 is to keep existing behavior unchanged:
* Before that PR, partition tables do not have a valid access method (`pg_class.relam` is always 0). So `RelationIsAppendOptimized` would always return false for partitioned tables.
* After that PR, partition tables carries an access method. So we had to exclude partitioned tables so that `RelationIsAppendOptimized` still always returns false for partitioned tables.

However, what I didn't realize at that time is that the "existing behavior" was **not** the right behavior. In GP6, partitioned tables *could* return true for `RelationIsAppendOptimized` because GP6 uses a GP-specific data field `pg_class.relstorage` to indicate the table storage format, and partitioned tables could have valid `pg_class.relstorage`. I guess during the PG12 merge when we replaced `relstorage` with `relam`, we changed the behavior inadvertently.

That's why in GP6, exclusive lock would be acquired in the concerning scenario (due to the reason @zhenghu mentioned), but not in GP7. So yes, we should fix this issue.

Now about the fix: I agree we should remove the `relkind` check in `RelationIsAppendOptimized`. The macro should be as generic as just checking the relstorage/relam, same as `RelationIsAoRows` and `RelationIsAoCols`. However, there could be some other issues after that. For example, in `RelationBuildDesc` we build the pg_appendonly information for a non-partitioned AO table (partitioned table doesn't have pg_appendonly entry in GP7): https://github.com/greenplum-db/gpdb/blob/main/src/backend/utils/cache/relcache.c#L1297-L1298. So after the change of `RelationIsAppendOptimized`, we need to change the condition in `RelationBuildDesc` to exclude partitioned table. Basically, **we need to move the `relkind != RELKIND_PARTITIONED_TABLE` check from `RelationIsAppendOptimized` to where it is needed**. @charliettxx we can discuss more when you start working on the fix.

**Comment by charliettxx** [comment] 2023-05-11 03:55
@huansong Thanks for your detailed explanations！
So let me understand your points, the reason we changed exclude partition table is partition tables have a valid access method now.

I found there are many places call Macro `RelationIsAppendOptimized`(ex. index, vacuum, planer...), we need to spend
 more time to check these calls before we are able to move **relkind != RELKIND_PARTITIONED_TABLE check from 
RelationIsAppendOptimized**, and I think it will also rise regression risks. 

In my opinion, current behavior of `RelationIsAppendOptimized` is checking tables has real ao/aoco storage or not,
like root partition didn't store data and no need to build pg_appendonly informations. Do I understand right here?

So I tend to add another Maroc for partition table to fix this issue. `RelationIsAppendOptimized` make sense in my view,
but we also need to check the places calling it, replace by `RelationIsAO` or not.
```
#define RelationIsAO(relation) \
	((RelationIsAoRows(relation) || RelationIsAoCols(relation))
```

which approach did you guys prefer? @huansong @kainwen @linxuh, maybe we need more discussion before start working on the fix.

**Comment by huansong** [comment] 2023-05-11 22:06
> So I tend to add another Maroc for partition table to fix this issue. RelationIsAppendOptimized make sense in my view,
but we also need to check the places calling it, replace by RelationIsAO or not.

Hmm.. I agree with @linxuh that we should just change `RelationIsAppendOptimized` to not exclude partitioned tables. It should have the same behavior as GP6 to start with. I don't think we should add `RelationIsAO` which looks like an alias of `RelationIsAppendOptimized` but does different things.

But naming is just secondary issue, main thing is that we need to figure out where we need to check partitioned tables and where we don't. Even with two clearly defined macros, we need to know where to use which one. Let's discuss offline about such a list. @charliettxx

**Comment by l-wang** [comment] 2023-05-13 00:29
Don't we already have that macros `RelationAMIsAO`?

**Comment by huansong** [comment] 2023-05-15 14:29
> Don't we already have that macros RelationAMIsAO?

@l-wang You are absolutely right! IIRC it was added precisely because I changed `RelationIsAppendOptimized` to exclude partitioned tables... 

Let's remove `RelationAMIsAO` and just use the new `RelationIsAppendOptimized` in your PR. @charliettxx

**Comment by kainwen** [comment] 2023-06-29 02:30
@huansong Hi, what is latest status of this issue? I think you've fixed it?

**Comment by charliettxx** [comment] 2023-06-29 06:31
@kainwen I have merged PR https://github.com/greenplum-db/gpdb/pull/15546 to fix it, so we could close it.

**Closed** 2023-06-29 06:32 UTC
Labels: type: bug, version: 7X_ALPHA, Priority 1
