### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by waterlily8440** [greenplum-db/gpdb#12414] opened 2021-07-30 04:17 UTC
### Step to reproduce the behavior

run the query

Select objID,objInfoFlag,qualityFlag,raStack,decStack,raStackErr,decStackErr,raMean,decMean,raMeanErr,decMeanErr,epochMean,posMeanChisq,gPSFMag,gPSFMagErr,gApMag,gApMagErr,gKronMag,gKronMagErr,ginfoFlag,ginfoFlag2,ginfoFlag3,rPSFMag,rPSFMagErr,rApMag,rApMagErr,rKronMag,rKronMagErr,rinfoFlag,rinfoFlag2,rinfoFlag3,iPSFMag,iPSFMagErr,iApMag,iApMagErr,iKronMag,iKronMagErr,iinfoFlag,iinfoFlag2,iinfoFlag3,zPSFMag,zPSFMagErr,zApMag,zApMagErr,zKronMag,zKronMagErr,zinfoFlag,zinfoFlag2,zinfoFlag3,yPSFMag,yPSFMagErr,yApMag,yApMagErr,yKronMag,yKronMagErr,yinfoFlag,yinfoFlag2,yinfoFlag3 from sov where q3c_radial_query(ramean, decmean, 300, -29, 20);
--

out of memory [error]( @Venkatesh Raghavan)

**Comment by bhuvnesh2703** [comment] 2021-11-09 17:15
@waterlily8440 couple of questions:
1) does it need data to reproduce the error which you observed? If so, would you be able to provide the dump of the data?
2) Did you use planner or orca?  (You can run explain plan to see if its planner `Postgres query optimizer` or orca `Pivotal Optimizer (GPORCA)`

Without the data, the OOM is not observed
```
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..176560.40 rows=95708800 width=276)
   ->  Seq Scan on sov  (cost=0.00..78118.15 rows=31902934 width=276)
         Filter: ((((q3c_ang2ipix(ramean, decmean) >= 4971973988617027584::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5044031582654955520::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5116089176692883456::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5134103575202365440::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4917930793088581632::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4935945191598063616::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4953959590107545600::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4971973988617027584::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5062045981164437504::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5066549580791808000::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5134103575202365440::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5138607174829735936::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5066549580791808000::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5071053180419178496::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5075556780046548992::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5080060379673919488::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5138607174829735936::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5143110774457106432::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6485183463413514240::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6503197861922996224::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6521212260432478208::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6525715860059848704::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6386104271611363328::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6390607871238733824::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6525715860059848704::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6530219459687219200::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6530219459687219200::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6534723059314589696::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1152921504606846976::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1157425104234217472::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1188950301625810944::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1193453901253181440::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1197957500880551936::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1202461100507922432::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1161928703861587968::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1166432303488958464::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1::bigint) AND (q3c_ang2ipix(ramean, decmean) < (-1)::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4935945191598063616::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4940448791225434112::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4940448791225434112::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4944952390852804608::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4944952390852804608::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4949455990480175104::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5098074778183401472::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5102578377810771968::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5102578377810771968::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5107081977438142464::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5152117973711847424::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5156621573339217920::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5170132372221329408::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5174635971848699904::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4904419994206470144::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4908923593833840640::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4913427193461211136::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4917930793088581632::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5048535182282326016::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5053038781909696512::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5057542381537067008::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5062045981164437504::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5071053180419178496::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5075556780046548992::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 4949455990480175104::bigint) AND (q3c_ang2ipix(ramean, decmean) < 4953959590107545600::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5143110774457106432::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5147614374084476928::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5147614374084476928::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5152117973711847424::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 5156621573339217920::bigint) AND (q3c_ang2ipix(ramean, decmean) < 5161125172966588416::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6503197861922996224::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6507701461550366720::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6539226658941960192::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6543730258569330688::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6377097072356622336::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6381600671983992832::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6381600671983992832::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6386104271611363328::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6350075474592399360::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6354579074219769856::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6512205061177737216::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6516708660805107712::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6548233858196701184::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6552737457824071680::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6390607871238733824::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6395111470866104320::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6404118670120845312::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6408622269748215808::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 6534723059314589696::bigint) AND (q3c_ang2ipix(ramean, decmean) < 6539226658941960192::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1297036692682702848::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1301540292310073344::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1193453901253181440::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1197957500880551936::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1202461100507922432::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1206964700135292928::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1306043891937443840::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1310547491564814336::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1157425104234217472::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1161928703861587968::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1166432303488958464::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1170935903116328960::bigint)) OR ((q3c_ang2ipix(ramean, decmean) >= 1301540292310073344::bigint) AND (q3c_ang2ipix(ramean, decmean) < 1306043891937443840::bigint))) AND (q3c_sindist(ramean, decmean, 300::double precision, (-29)::double precision) < 0.0301536896070458::double precision))
 Optimizer: Pivotal Optimizer (GPORCA)
(4 rows)

Time: 118.159 ms
panstarrs=# Select objID,objInfoFlag,qualityFlag,raStack,decStack,raStackErr,decStackErr,raMean,decMean,raMeanErr,decMeanErr,epochMean,posMeanChisq,gPSFMag,gPSFMagErr,gApMag,gApMagErr,gKronMag,gKronMagErr,ginfoFlag,ginfoFlag2,ginfoFlag3,rPSFMag,rPSFMagErr,rApMag,rApMagErr,rKronMag,rKronMagErr,rinfoFlag,rinfoFlag2,rinfoFlag3,iPSFMag,iPSFMagErr,iApMag,iApMagErr,iKronMag,iKronMagErr,iinfoFlag,iinfoFlag2,iinfoFlag3,zPSFMag,zPSFMagErr,zApMag,zApMagErr,zKronMag,zKronMagErr,zinfoFlag,zinfoFlag2,zinfoFlag3,yPSFMag,yPSFMagErr,yApMag,yApMagErr,yKronMag,yKronMagErr,yinfoFlag,yinfoFlag2,yinfoFlag3 from sov where q3c_radial_query(ramean, decmean, 300, -29, 20);
NOTICE:  One or more columns in the following table(s) do not have statistics: sov
HINT:  For non-partitioned tables, run analyze <table_name>(<column_list>). For partitioned tables, run analyze rootpartition <table_name>(<column_list>). See log for columns missing statistics.
 objid | objinfoflag | qualityflag | rastack | decstack | rastackerr | decstackerr | ramean | decmean | rameanerr | decmeanerr | epochmean | posmeanchisq | gpsfmag | gpsfmagerr | gapmag | gapmagerr | gkronmag | gkronmagerr | ginfoflag | ginfoflag2 | ginfoflag3 | rpsfmag | rpsfmagerr | rapmag | rapmagerr | rkronmag | rkronmagerr | rinfoflag | rinfoflag2 | rinfoflag3 | ipsfmag | ipsfmagerr | iapmag | iapmagerr | ikronmag | ikronmagerr | iinfoflag | iinfoflag2 | iinfoflag3 | zpsfmag | zpsfmagerr | zapmag | zapmagerr | zkronmag | zkronmagerr | zinfoflag | zinfoflag2 | zinfoflag3 | ypsfmag | ypsfmagerr | yapmag | yapmagerr | ykronmag | ykronmagerr | yinfoflag | yinfoflag2 | yinfoflag3
-------+-------------+-------------+---------+----------+------------+-------------+--------+---------+-----------+------------+-----------+--------------+---------+------------+--------+-----------+----------+-------------+-----------+------------+------------+---------+------------+--------+-----------+----------+-------------+-----------+------------+------------+---------+------------+--------+-----------+----------+-------------+-----------+------------+------------+---------+------------+--------+-----------+----------+-------------+-----------+------------+------------+---------+------------+--------+-----------+----------+-------------+-----------+------------+------------
(0 rows)

Time: 86.165 ms
panstarrs=# select version();
                                                                                                    version
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.24 (Greenplum Database 6.18.1+dev.18.g484264160b build dev) on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit compiled on Nov  9 2021 09:08:44
```

**Comment by kainwen** [comment] 2022-05-08 09:39
Hi @waterlily8440 
Do you still have this issue? If so, can you please paste the OOMed plan and OOMed segments log here?

**Comment by bhuvnesh2703** [comment] 2022-05-09 04:06
Closing the issue, since there is no repro. Please reopen if a repro could be provided.

**Closed by bhuvnesh2703** 2022-05-09 04:06 UTC
Labels: area: gporca, Priority 1
