### ISSUE TITLE
Is RangeVarGetRelidExtended() retired?

### ISSUE THREAD

**Issue by kuien** [greenplum-db/gpdb#3874] opened 2017-11-14 03:57 UTC
I found an interesting commit (@asimrp) on DROP TABLE, it introduced function 'RangeVarGetRelidExtended()',but it seems non places are using it now.

My question is: what is the original issue? How it be fixed currently?

> 
> commit 4739cd229b481a1a960395000aef360088e8ad5c
> Author: Asim Praveen <apraveen@pivotal.io>
> Date:   Tue Sep 22 16:51:31 2015 -0700
> 
>     DROP TABLE should look up the name again, if blocked.
> 
>     If DROP has to wait for a lock on the relation after its OID was looked up, it
>     may happen that the name is no longer valid by the time DROP acquires the lock.
> 
>     This case is handled by pulling a function from upstream commit
>             commit 4240e429d0c2d889d0cda23c618f94e12c13ade7
>             Author: Robert Haas <rhaas@postgresql.org>
>             Date:   Fri Jul 8 22:19:30 2011 -0400
>             Try to acquire relation locks in RangeVarGetRelid.

**Comment by asimrp** [comment] 2017-11-14 18:14
Indeed, the function is unused at this point.  Thank you for catching this!  I see that `RemoveRelation()` that originally used this function has now become `RemoveRelations()`.  The commit was pulled from 9.3 and probably got reverted during the ongoing 8.4 merge.  That also means we have a regression.  Let me include full commit message, that describes the problem:
```
commit 4240e429d0c2d889d0cda23c618f94e12c13ade7
Author: Robert Haas <rhaas@postgresql.org>
Date:   Fri Jul 8 22:19:30 2011 -0400

    Try to acquire relation locks in RangeVarGetRelid.
    
    In the previous coding, we would look up a relation in RangeVarGetRelid,
    lock the resulting OID, and then AcceptInvalidationMessages().  While
    this was sufficient to ensure that we noticed any changes to the
    relation definition before building the relcache entry, it didn't
    handle the possibility that the name we looked up no longer referenced
    the same OID.  This was particularly problematic in the case where a
    table had been dropped and recreated: we'd latch on to the entry for
    the old relation and fail later on.  Now, we acquire the relation lock
    inside RangeVarGetRelid, and retry the name lookup if we notice that
    invalidation messages have been processed meanwhile.  Many operations
    that would previously have failed with an error in the presence of
    concurrent DDL will now succeed.
    
    There is a good deal of work remaining to be done here: many callers
    of RangeVarGetRelid still pass NoLock for one reason or another.  In
    addition, nothing in this patch guards against the possibility that
    the meaning of an unqualified name might change due to the creation
    of a relation in a schema earlier in the user's search path than the
    one where it was previously found.  Furthermore, there's nothing at
    all here to guard against similar race conditions for non-relations.
    For all that, it's a start.
    
    Noah Misch and Robert Haas
```

**Comment by tvesely** [comment] 2017-11-14 22:36
This is a legitimate bug in GPDB.  It can be reproduced by the following isolation2 spec:
```SQL
1:drop table if exists t3;
1:create table t3 (a int, b text) distributed by (a);
1:insert into t3 select i, '123 '||i from generate_series(1,10)i;
1:begin;
1:alter table t3 rename to t3_new;
2&:drop table if exists t3;
1:commit;
2<:
2:select count(*) from t3;
2:select relname from pg_class where relname like 't3%';
2:select relname from gp_dist_random('pg_class') where relname like 't3%';
```
The `drop if exists` transaction drops the table on master and dispatches the drop statement to segments.  Segments no longer find the table with the old name because the `alter table rename` transaction has renamed the table and committed.

**Comment by hlinnaka** [comment] 2017-11-20 18:23
Thanks for the repro, @tvesely!

On my laptop, I get this output from it:
```
1:drop table if exists t3;
DROP
1:create table t3 (a int, b text) distributed by (a);
CREATE
1:insert into t3 select i, '123 '||i from generate_series(1,10)i;
INSERT 10
1:begin;
BEGIN
1:alter table t3 rename to t3_new;
ALTER
2&:drop table if exists t3;  <waiting ...>
1:commit;
COMMIT
2<:  <... completed>
DROP
2:select count(*) from t3;
ERROR:  relation "t3" does not exist
LINE 1: select count(*) from t3;
                             ^
2:select relname from pg_class where relname like 't3%';
relname
-------
(0 rows)
2:select relname from gp_dist_random('pg_class') where relname like 't3%';
relname
-------
t3_new 
t3_new 
t3_new 
(3 rows)
```

Which seems correct. Am I missing something?

This repro seems to be a variant of the existing `drop_rename` tests. Are the existing tests not covering this?

**Comment by hlinnaka** [comment] 2017-11-20 18:47
Oh, I'm blind, now I see that that's wrong. The table was dropped on master, but not on the segments.

**Comment by hlinnaka** [comment] 2017-11-21 07:54
Fixed, thanks for the report @kuien!

**Closed by hlinnaka** 2017-11-21 07:54 UTC
