### ISSUE TITLE
An unenforceable unique index can be created on a partitioned table

### ISSUE THREAD

**Issue by hlinnaka** [greenplum-db/gpdb#6977] opened 2019-02-13 20:21 UTC
This isn't allowed, as expected:
```
postgres=# create table region                                    
(
r_regionkey integer not null unique,
r_name char(25),
r_comment varchar(152)
)
distributed by (r_regionkey)
partition by range (r_regionkey)
subpartition by list (r_name) subpartition template
(
subpartition africa values ('AFRICA'),
subpartition america values ('AMERICA'),
subpartition asia values ('ASIA'),
subpartition europe values ('EUROPE'),
subpartition mideast values ('MIDDLE EAST'),
subpartition australia values ('AUSTRALIA'),
subpartition antarctica values ('ANTARCTICA')
)
(
partition region1 start (0),
partition region2 start (3),
partition region3 start (5) end (8)
);
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1" for table "region"
ERROR:  UNIQUE constraint must contain all columns in the partition key
HINT:  Include column "r_name" in the UNIQUE constraint or create a part-wise UNIQUE index after creating the table instead.
```
However, leaving out the UNIQUE clause, and creating the same unique index with CREATE UNIQUE INDEX is allowed:
```
postgres=# create table region
(
r_regionkey integer not null /* unique */, 
r_name char(25),
r_comment varchar(152)
)
distributed by (r_regionkey)
partition by range (r_regionkey)
subpartition by list (r_name) subpartition template
(
subpartition africa values ('AFRICA'),
subpartition america values ('AMERICA'),
subpartition asia values ('ASIA'),
subpartition europe values ('EUROPE'),
subpartition mideast values ('MIDDLE EAST'),
subpartition australia values ('AUSTRALIA'),
subpartition antarctica values ('ANTARCTICA')
)
(
partition region1 start (0),
partition region2 start (3),
partition region3 start (5) end (8)
);
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1" for table "region"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_africa" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_america" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_asia" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_europe" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_mideast" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_australia" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region1_2_prt_antarctica" for table "region_1_prt_region1"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2" for table "region"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_africa" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_america" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_asia" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_europe" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_mideast" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_australia" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region2_2_prt_antarctica" for table "region_1_prt_region2"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3" for table "region"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_africa" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_america" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_asia" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_europe" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_mideast" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_australia" for table "region_1_prt_region3"
NOTICE:  CREATE TABLE will create partition "region_1_prt_region3_2_prt_antarctica" for table "region_1_prt_region3"
CREATE TABLE
postgres=# create unique index region_pkey on region(r_regionkey);
NOTICE:  building index for child partition "region_1_prt_region1"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_africa"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_america"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_asia"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_europe"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_mideast"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_australia"
NOTICE:  building index for child partition "region_1_prt_region1_2_prt_antarctica"
NOTICE:  building index for child partition "region_1_prt_region2"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_africa"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_america"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_asia"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_europe"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_mideast"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_australia"
NOTICE:  building index for child partition "region_1_prt_region2_2_prt_antarctica"
NOTICE:  building index for child partition "region_1_prt_region3"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_africa"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_america"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_asia"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_europe"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_mideast"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_australia"
NOTICE:  building index for child partition "region_1_prt_region3_2_prt_antarctica"
CREATE INDEX
```
Expected to get an error with that too.

**Comment by hlinnaka** [comment] 2019-02-14 20:37
Or is this expected behavior? Is it expected that CREATE UNIQUE INDEX creates a separate unique index on each partition, without enforcing "global" uniqueness?

**Comment by soumyadeep2007** [comment] 2019-08-16 21:45
Seems that it is intentional?

This line in our documentation seems to suggest just that:
https://github.com/greenplum-db/gpdb/blob/81fd620e7ca282c406a6716ddab4eb5e46e67421/gpdb-doc/dita/admin_guide/ddl/ddl-partition.xml#L338

**Comment by d** [comment] 2019-08-16 21:54
> Or is this expected behavior? Is it expected that CREATE UNIQUE INDEX creates a separate unique index on each partition, without enforcing "global" uniqueness?

I find this strange too

**Comment by soumyadeep2007** [comment] 2019-08-16 22:16
^ Same here... According to https://www.postgresql.org/docs/9.4/indexes-unique.html, a CREATE UNIQUE INDEX is interchangeable for a unique constraint specified on a column(s). Allowing one and not the other seems weird. 

We need more information as to why this was ever intended, if at all.

**Comment by soumyadeep2007** [comment] 2019-08-16 22:19
If we are to outlaw, the fix is simple:
In `DefineIndex` we have the conditional:
```
if ( stmt->isconstraint && rel_is_partitioned(relationId) )
		checkUniqueConstraintVsPartitioning(rel,
											indexInfo->ii_KeyAttrNumbers,
											indexInfo->ii_NumIndexAttrs,
											stmt->primary);
```
The if statement should be updated to be:
((stmt->isconstraint || stmt->unique) && rel_is_partitioned(relationId))

**Comment by soumyadeep2007** [comment] 2019-08-16 22:22
If we decide to outlaw, we should do it as part of 6GA as it is a breaking change.

**Comment by lij55** [comment] 2022-03-24 09:58
the behavior is fixed on GP7:
```sql
test=#  create unique index region_pkey on region(r_regionkey);
ERROR:  insufficient columns in UNIQUE constraint definition
DETAIL:  UNIQUE constraint on table "region_1_prt_region1" lacks column "r_name" which is part of the partition key.
test=# select version();
                                                                                                 version                                                                            
                     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------
 PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.15107.g71664c2aa8 build dev) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-16ubuntu1) 11.2.0, 64-bit compiled on 
Feb 21 2022 16:15:26
(1 row)

```

**Comment by ashwinstar** [comment] 2022-07-22 19:54
This ship has sailed to make this breaking change for GPDB6. Given the problem is not present for GPDB7 and forward, closing the issue as won't fix for STABLE branch.

**Closed by ashwinstar** 2022-07-22 19:54 UTC
Labels: type: bug, area: server, version: 6X_STABLE, Priority 3
