### ISSUE TITLE
Error: Relation with OID ### does not exist

### ISSUE THREAD

**Issue by orhankislal** [greenplum-db/gpdb#2284] opened 2017-04-22 00:28 UTC
We encounter this error on GPDB5 alpha with some MADlib functions. The error is inconsistent, sometimes the function just works as intended. Here is the function call and the error:
```
SELECT madlib.elastic_net_train(
    'lin_housing_wi', 'house_en','y','x','gaussian',0.1, 0.2, True,NULL, 
    'fista', $$ eta = 2, max_stepsize = 0.5, use_active_set = f, n_folds = 3,
    validation_result=house_en_cv, n_lambdas = 3, alpha = {0, 0.1, 1}, 
    warmup = True, warmup_lambdas = {10, 1, 0.1} $$, NULL, 100, 1e-6
);
```
```
ERROR:  plpy.SPIError: relation with OID 1832621 does not exist  (seg0 slice1 10.194.10.84:40000 pid=22995)
```
The OID, segment and slice numbers change as well. 
We saw this error in a number of functions that contain `plpy.execute` calls where we drop a table and create a new one in the same call. We decoupled those statements to work around the issue but some functions still give the same error. 
This issue might have the same cause as #2269

**Comment by orhankislal** [comment] 2017-04-24 21:22
Here is a different function that give a similar error. 
```
okislal=# select * from mat;
 id |                  row_vec                  | grp
----+-------------------------------------------+-----
  3 | {293,742,298,75,404,857,941,662,846,2}    |   1
  7 | {877,59,260,302,891,498,710,286,864,675}  |   1
 11 | {528,1,860,18,814,242,314,965,935,809}    |   2
 15 | {909,472,871,695,930,455,398,893,693,838} |   2
  4 | {462,532,787,265,982,306,600,608,212,885} |   1
  8 | {458,959,774,376,228,354,300,669,718,565} |   2
 12 | {492,220,576,289,321,261,173,1,44,241}    |   2
 16 | {739,651,678,577,273,935,661,47,373,618}  |   2
  1 | {396,840,353,446,318,886,15,584,159,383}  |   1
  5 | {304,151,337,387,643,753,603,531,459,652} |   1
  9 | {824,390,818,844,180,943,424,520,65,913}  |   2
 13 | {415,701,221,503,67,393,479,218,219,916}  |   2
  2 | {691,58,899,163,159,533,604,582,269,390}  |   1
  6 | {327,946,368,943,7,516,272,24,591,204}    |   1
 10 | {882,761,398,688,761,405,125,484,222,873} |   2
 14 | {350,192,211,633,53,783,30,444,176,932}   |   2

okislal=# select madlib.pca_train('mat', 'result_table', 'id', 0.8, 'grp', 5, FALSE, 'summary_table');
ERROR:  plpy.SPIError: plpy.SPIError: plpy.SPIError: relation not found (OID 1867197)  (seg1 slice1 10.194.10.84:40001 pid=22056)
DETAIL:  This can be validly caused by a concurrent delete operation on this object.
CONTEXT:  Traceback (most recent call last):
  PL/Python function "pca_train", line 23, in <module>
    return pca.pca(**globals())
  PL/Python function "pca_train", line 87, in pca
  PL/Python function "pca_train", line 235, in pca_wrap
PL/Python function "pca_train"
```

**Comment by jimmyyih** [comment] 2017-04-24 21:30
Can you check if the "relation not found (OID 1867197)" is related to this change: https://github.com/greenplum-db/gpdb/commit/1fd11387d2b9f250c14f0ccb893c0956b1bf1487

Something like this should determine that:
``` sql
select oid, relfilenode, relname from pg_class where oid = 1867197 or relfilenode = 1867197;
select oid, relfilenode, relname from gp_dist_random('pg_class') where oid = 1867197 or relfilenode = 1867197;
```

**Comment by asimrp** [comment] 2017-04-27 07:15
Let me note down steps to reproduce this in detail.
1. Install and deploy madlib as per my comment in #2269.
1. Create a file with the content from mat.  E.g.
```sh
$ cat > ~/workspace/madlib_repro_mat.txt
  3 | {293,742,298,75,404,857,941,662,846,2}    |   1
  7 | {877,59,260,302,891,498,710,286,864,675}  |   1
 11 | {528,1,860,18,814,242,314,965,935,809}    |   2
 15 | {909,472,871,695,930,455,398,893,693,838} |   2
  4 | {462,532,787,265,982,306,600,608,212,885} |   1
  8 | {458,959,774,376,228,354,300,669,718,565} |   2
 12 | {492,220,576,289,321,261,173,1,44,241}    |   2
 16 | {739,651,678,577,273,935,661,47,373,618}  |   2
  1 | {396,840,353,446,318,886,15,584,159,383}  |   1
  5 | {304,151,337,387,643,753,603,531,459,652} |   1
  9 | {824,390,818,844,180,943,424,520,65,913}  |   2
 13 | {415,701,221,503,67,393,479,218,219,916}  |   2
  2 | {691,58,899,163,159,533,604,582,269,390}  |   1
  6 | {327,946,368,943,7,516,272,24,591,204}    |   1
 10 | {882,761,398,688,761,405,125,484,222,873} |   2
 14 | {350,192,211,633,53,783,30,444,176,932}   |   2
$
```
3. Load it in a table named `mat`:
```SQL
create table mat (id int, row_vec int[], grp int);
CREATE TABLE

copy mat FROM '/home/asim/workspace/madlib_repro_mat.txt' delimiter '|';
COPY 16
```
4. Run the `pca_train()` function as per Orhan's comment
```SQL
select madlib.pca_train('mat', 'result_table', 'id', 0.8, 'grp', 5, FALSE, 'summary_table');
 pca_train 
-----------
 
(1 row)

select * from summary_table;
 rows_used | exec_time (ms) | iter |  recon_error  | relative_recon_error | use_correlati
on | grp 
-----------+----------------+------+---------------+----------------------+--------------
---+-----
         7 |  15515.8159733 |    5 | 121.694448215 |       0.452080313331 | f            
   |   1
         9 |  15197.3171234 |    5 |  117.04899308 |       0.444684891313 | f            
   |   2
(2 rows)
```

**Comment by orhankislal** [comment] 2017-04-27 17:28
@asimrp To reproduce this error more easily, you might want to change the madlib branch to `latest_branch`. Current master branch has the temporary fix that decouples the `DROP TABLE` and `CREATE TABLE` statements but latest_branch doesn't.

**Comment by asimrp** [comment] 2017-06-02 14:10
Fixed by https://github.com/greenplum-db/gpdb/commit/b52ca70fdfde78d4de0cd31b3a9cf7855c7a7239

Thank you for the report.

**Closed by asimrp** 2017-06-02 14:10 UTC

**Comment by ashwinstar** [comment] 2024-04-18 22:18
Fetched some old context for this issue and posting the reasoning which was found to help current situation at hand...

The cause `GetSubXidsInXidBuffer()` is called only on `GetSnapshotData()`. So, for case where sub-transactionIDs are getting allocated lazily, Writer (and also reader) correctly gets updated with new sub transactionId when allocated delayed way via `AssignTransactionId()`. But reader would be using stale info if spill happens (> 100 sub transactions) still from when snapshot was taken as subxbuf is not refreshed.

`TransactionIdIsCurrentTransactionId()` is of interest here, the issue doesn't exist in 4.3 as subtransaction ids are not getting allocated lazily hence its seen in 5.0+ only and doesn't relate to LazyXids as that changed only for main transactions.

        /*
         * For readers if sub-transactions fit in-memory can leverage the
         * writers array instead of subxbuf.
         */
        if (SharedLocalSnapshotSlot->inmemory_subcnt ==
                SharedLocalSnapshotSlot->total_subcnt)
        {
            for (sub = 0; sub < SharedLocalSnapshotSlot->total_subcnt; sub++)
            {
                if (TransactionIdEquals(xid, SharedLocalSnapshotSlot->subxids[sub]))
                {
                    isCurrentTransactionId = true;
                    break;
                }
            }
        }
        else
        {
            isCurrentTransactionId = FindXidInXidBuffer(&subxbuf, xid, &cnt, &index); <<====== This is stale
        }

This was proposed as fix and was done... (read the comment as were made in 2017)

Need to think through a lot but seems time to take-up the enhancement I had noted in that story
1] SharedLocalSnapshot should only be used for snapshot. Its currently overloaded and instead of just storing the snapshot information is also storing the current TransactionTree.
2] I think the assumption it was coded was READER should inherit the state (snapshot and TransactionTree) of WRITER while acquiring the snapshot and then later just use the sam to perform all the actions. I feel that's not needed or breaks with new postgres code and specially with LazyXIDs. Only snapshot is something it needs to inherit from WRITER at time of taking the snapshot. But can refer to current WRITER state while performing all other actions.

Just need to be careful as lifecycle of writer and reader is little fuzzy. If its guaranteed writer always lives beyond reader then we can store its PROC pointer in SharedLocalSnapshotSlot instead of just PID and leverage the same for checking TransactionIdIsCurrentTransactionId() as Heikki mentioned. Completely stop maintaining TransactionState in SharedLocalSnapshotSlot.

Ashwin, the cause you've identified is exactly the case. The reader acquires a snapshot when total subtransaction count was exactly 100, so that the list of subtransactions is in-memory in SharedLocalSnapshotSlot and the reader's local copy, subxbuf, is empty. Then the writer lazily obtains a transaction ID and sets SharedLocalSnapshotSlot->inmemory_subcnt = 0. For the reader, this means that any tuple inserted by previously committed subtransactions becomes invisible, because TransactionIdIsCurrentTransactionId() sees empty shared in-memory subtransactions list and empty local copy subxbuf.

I'm coming up with a non-madlib repro for this:

1. Create 100 subtransactions, one or more of these should insert some tuples.
2. 101st subtransaction should be a command that needs more than one slices / reader gangs.
3. The reader should acquire a snapshot before writer is assigned a XID.
4. The reader should read the tuples inserted by previously committed subtransactions after the writer is assigned a XID. Due to the bug, tuples should be incorrectly deemed invisible to the reader.

https://github.com/greenplum-db/gpdb/pull/2491 which fixed this issue.
