### ISSUE TITLE
The data in the random distribution table is not actually randomly distributed by using 'insert into table values ...' method

### ISSUE THREAD

**Issue by StevenLuoo** [greenplum-db/gpdb#4778] opened 2018-03-28 03:16 UTC
Version: GP 5.5.0
OS:CentOS 6.3

The script is as below:
`create table test (id int,aaa varchar(20),bbb varchar(20)) distributed randomly;`

When I use the “insert into ... values ... ” method to add data, I find that all the data is concentrated in a single instance, rather than randomly distributed.

such as:
insert into test values ( 11,'aaaa','bbbbb');
insert into test values ( 21,'aaaa','bbbbb');
insert into test values ( 31,'aaaa','bbbbb');
insert into test values ( 41,'aaaa','bbbbb');
insert into test values ( 51,'aaaa','bbbbb');
insert into test values ( 61,'aaaa','bbbbb');
insert into test values ( 71,'aaaa','bbbbb');
insert into test values ( 81,'aaaa','bbbbb');
insert into test values ( 91,'aaaa','bbbbb');
……
or
insert into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),……

test=# select gp_segment_id,count(*) from test group by 1;
 gp_segment_id | count
---------------+-------
             5 |    60
(1 row)

All data is on a single instance(segment id 5), not random distribution in actually.

**Comment by kainwen** [comment] 2018-03-28 04:18
@StevenLuoo 
I cannot reproduce the data-skew by `insert into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),……` on GPDB5.5.

Can you re-test it and paste the plan here?

**Comment by StevenLuoo** [comment] 2018-03-28 07:12
@kainwen 
I run it again. All the output is here

test=# create table test (id int,aaa varchar(20),bbb varchar(20)) distributed randomly;
CREATE TABLE
test=# insert into test values
test-# ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),( 41,'aaaa','bbbbb'),( 51,'aaaa','bbbbb'),( 61,'aaaa','bbbbb'),( 71,'aaaa','bbbbb'),( 81,'aaaa','bbbbb'),( 91,'aaaa','bbbbb'),(101,'aaaa','bbbbb'),(111,'aaaa','bbbbb'),(121,'aaaa','bbbbb'),(131,'aaaa','bbbbb'),(141,'aaaa','bbbbb'),(151,'aaaa','bbbbb'),(161,'aaaa','bbbbb'),(171,'aaaa','bbbbb'),(181,'aaaa','bbbbb'),(191,'aaaa','bbbbb'),(201,'aaaa','bbbbb'),(211,'aaaa','bbbbb'),(221,'aaaa','bbbbb'),(231,'aaaa','bbbbb'),(241,'aaaa','bbbbb'),(251,'aaaa','bbbbb'),(261,'aaaa','bbbbb'),(271,'aaaa','bbbbb'),(281,'aaaa','bbbbb'),(291,'aaaa','bbbbb'),(301,'aaaa','bbbbb'),(311,'aaaa','bbbbb'),(321,'aaaa','bbbbb'),(331,'aaaa','bbbbb'),(341,'aaaa','bbbbb'),(351,'aaaa','bbbbb'),(361,'aaaa','bbbbb'),(371,'aaaa','bbbbb'),(381,'aaaa','bbbbb'),(391,'aaaa','bbbbb'),(401,'aaaa','bbbbb'),(411,'aaaa','bbbbb'),(421,'aaaa','bbbbb'),(431,'aaaa','bbbbb'),(441,'aaaa','bbbbb'),(451,'aaaa','bbbbb'),(461,'aaaa','bbbbb'),(471,'aaaa','bbbbb'),(481,'aaaa','bbbbb'),(491,'aaaa','bbbbb'),(501,'aaaa','bbbbb'),(511,'aaaa','bbbbb'),(521,'aaaa','bbbbb'),(531,'aaaa','bbbbb'),(541,'aaaa','bbbbb'),(551,'aaaa','bbbbb'),(561,'aaaa','bbbbb'),(571,'aaaa','bbbbb'),(581,'aaaa','bbbbb'),(591,'aaaa','bbbbb'),(601,'aaaa','bbbbb');
INSERT 0 60
test=# select gp_segment_id,count(*) from test group by 1;
 gp_segment_id | count
---------------+-------
             5 |    60
(1 row)

test=#

**Comment by StevenLuoo** [comment] 2018-03-28 07:24
@Eulerizeit 
hi, Rob
    I don't think so. Even if the cyclic Robin distribution is not a completely random distribution, it should not be all to one instance when inserting multiple rows of data at a time. I tested again in a old version(4.3.6.2), and the data was distributed to each instance.

**Comment by kainwen** [comment] 2018-03-29 07:47
@StevenLuoo 
Reproduced this issue. It is a bug of ORCA. @yydzero 

@vraghavan78 The plan generated by ORCA do not have a redistribute motion. I just test on GP5.5.0, no idea on other verisons.
```bash
gpadmin=# show optimizer
gpadmin-# ;
 optimizer
-----------
 on
(1 row)

gpadmin=# explain INSERT into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),( 41,'aaaa','bbbbb'),( 51,'aaaa','bbbbb'),( 61,'aaaa','bbbbb'),( 71,'aaaa','bbbbb'),( 81,'aaaa','bbbbb'),( 91,'aaaa','bbbbb'),(101,'aaaa','bbbbb'),(111,'aaaa','bbbbb'),(121,'aaaa','bbbbb'),(131,'aaaa','bbbbb'),(141,'aaaa','bbbbb'),(151,'aaaa','bbbbb'),(161,'aaaa','bbbbb'),(171,'aaaa','bbbbb'),(181,'aaaa','bbbbb'),(191,'aaaa','bbbbb'),(201,'aaaa','bbbbb'),(211,'aaaa','bbbbb'),(221,'aaaa','bbbbb'),(231,'aaaa','bbbbb'),(241,'aaaa','bbbbb'),(251,'aaaa','bbbbb'),(261,'aaaa','bbbbb'),(271,'aaaa','bbbbb'),(281,'aaaa','bbbbb'),(291,'aaaa','bbbbb'),(301,'aaaa','bbbbb'),(311,'aaaa','bbbbb'),(321,'aaaa','bbbbb'),(331,'aaaa','bbbbb'),(341,'aaaa','bbbbb'),(351,'aaaa','bbbbb'),(361,'aaaa','bbbbb'),(371,'aaaa','bbbbb'),(381,'aaaa','bbbbb'),(391,'aaaa','bbbbb'),(401,'aaaa','bbbbb'),(411,'aaaa','bbbbb'),(421,'aaaa','bbbbb'),(431,'aaaa','bbbbb'),(441,'aaaa','bbbbb'),(451,'aaaa','bbbbb'),(461,'aaaa','bbbbb'),(471,'aaaa','bbbbb'),(481,'aaaa','bbbbb'),(491,'aaaa','bbbbb'),(501,'aaaa','bbbbb'),(511,'aaaa','bbbbb'),(521,'aaaa','bbbbb'),(531,'aaaa','bbbbb'),(541,'aaaa','bbbbb'),(551,'aaaa','bbbbb'),(561,'aaaa','bbbbb'),(571,'aaaa','bbbbb'),(581,'aaaa','bbbbb'),(591,'aaaa','bbbbb'),(601,'aaaa','bbbbb');
                                  QUERY PLAN
-------------------------------------------------------------------------------
 Insert  (cost=0.00..1.13 rows=12 width=20)
   ->  Result  (cost=0.00..0.00 rows=12 width=24)
         ->  Result  (cost=0.00..0.00 rows=12 width=20)
               ->  Values Scan on "Values"  (cost=0.00..0.00 rows=12 width=20)
 Optimizer status: PQO version 2.55.0
(5 rows)

gpadmin=# set optimizer = off
gpadmin-# ;
SET
gpadmin=# sho
gpadmin=# \q
[gpadmin@sdw3-1 tpz]$ psql
psql (8.3.23)
Type "help" for help.

gpadmin=# set optimizer=off
gpadmin-# ;
SET
gpadmin=# show optimizer;
 optimizer
-----------
 off
(1 row)

gpadmin=# explain INSERT into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),( 41,'aaaa','bbbbb'),( 51,'aaaa','bbbbb'),( 61,'aaaa','bbbbb'),( 71,'aaaa','bbbbb'),( 81,'aaaa','bbbbb'),( 91,'aaaa','bbbbb'),(101,'aaaa','bbbbb'),(111,'aaaa','bbbbb'),(121,'aaaa','bbbbb'),(131,'aaaa','bbbbb'),(141,'aaaa','bbbbb'),(151,'aaaa','bbbbb'),(161,'aaaa','bbbbb'),(171,'aaaa','bbbbb'),(181,'aaaa','bbbbb'),(191,'aaaa','bbbbb'),(201,'aaaa','bbbbb'),(211,'aaaa','bbbbb'),(221,'aaaa','bbbbb'),(231,'aaaa','bbbbb'),(241,'aaaa','bbbbb'),(251,'aaaa','bbbbb'),(261,'aaaa','bbbbb'),(271,'aaaa','bbbbb'),(281,'aaaa','bbbbb'),(291,'aaaa','bbbbb'),(301,'aaaa','bbbbb'),(311,'aaaa','bbbbb'),(321,'aaaa','bbbbb'),(331,'aaaa','bbbbb'),(341,'aaaa','bbbbb'),(351,'aaaa','bbbbb'),(361,'aaaa','bbbbb'),(371,'aaaa','bbbbb'),(381,'aaaa','bbbbb'),(391,'aaaa','bbbbb'),(401,'aaaa','bbbbb'),(411,'aaaa','bbbbb'),(421,'aaaa','bbbbb'),(431,'aaaa','bbbbb'),(441,'aaaa','bbbbb'),(451,'aaaa','bbbbb'),(461,'aaaa','bbbbb'),(471,'aaaa','bbbbb');
                                        QUERY PLAN
-------------------------------------------------------------------------------------------
 Insert (slice0; segments: 5)  (rows=10 width=120)
   ->  Redistribute Motion 1:5  (slice1; segments: 1)  (cost=0.00..0.59 rows=47 width=120)
         ->  Values Scan on "*VALUES*"  (cost=0.00..0.59 rows=10 width=120)
 Settings:  optimizer=off
 Optimizer status: legacy query optimizer
(5 rows)
```

**Comment by StevenLuoo** [comment] 2018-03-30 07:17
@kainwen thanks！

**Comment by d** [comment] 2018-04-01 23:51
@StevenLuoo This is not a bug. Here's why:

1.  Greenplum supports explicit data (hash) distribution as a syntactic extension `DISTRIBUTE BY (col[, col2]...)`, for example
    ```sql
    CREATE TABLE foo (a int, b int) DISTRIBUTED BY (a);
    ```

    The semantic of the above example is: for any two tuples `(a1, b1)` and `(a2, b2)`, they are co-located if (but not only if)

      1.  `a1 = b1`; or
      1.  `a1 is NULL AND a2 IS NULL`

    In a boolean table, this would look like:

    a1 IS NULL | a2 IS NULL | a1 = a2 | `(a1,b1)` is on the same segment as `(a2,b2)`
    ---|---|---|---
    f|f|t|t
    f|f|f|X
    t|f|X|X
    t|t|X|t

    Where "X" denotes unknown or "undefined": i.e. when `a1 != a2`, it is not a bug if `(a1,b1)` and `(a2,b2)` are stored on the same segments.

1.  With that in mind, let's discuss the semantic of `DISTRIBUTED RANDOMLY`. Let's use a similar example

    ```sql
    CREATE TABLE bar (c int, d int) DISTRIBUTED RANDOMLY;
    ```

    What can we expect whether two tuples, `(c1, d1)` and `(c2, d2)` are stored on the same segments? Here's the boolean table:

    c1 IS NULL | c2 IS NULL | c1 = c2 | `(c1,d1)` is on the same segment as `(c2,d2)`
    ---|---|---|---
    f|f|t|X
    f|f|f|X
    t|f|X|X
    t|t|X|X

    Right, `DISTRIBUTED RANDOMLY` does *not* guarantee anything. It is *permissible* that the database performs some "random distribution", or "round robin", but pretty much all bets are off: as long as the database doesn't store your data on master, it is compliant with `DISTRIBUTED RANDOMLY`

**Comment by yydzero** [comment] 2018-04-02 02:02
@d so behavior between planner and orca is different?  Shall we make it consistent? @vraghavan78

**Comment by d** [comment] 2018-04-02 06:45
@yydzero Yes they are different: ORCA is way more awesome than planner.

**Comment by yydzero** [comment] 2018-04-02 06:52
Yes, I know. While there are behavior difference now. Defer to PM to make a call.

**Comment by Eulerizeit** [comment] 2018-04-02 13:00
@yydzero my understanding is that Orca chose to default to Random Distribution whereas the planner defaults to distributing to the first column. I'm not sure how much of a problem this is since in both cases the user isn't specifying a distribution key. (I could be very wrong with this assumption) 

I think the bigger issue is that our Random Distribution is poorly named and it causes confusion as it did here.

**Comment by dhanashreek89** [comment] 2018-04-02 18:52
>> @yydzero my understanding is that Orca chose to default to Random Distribution whereas the planner defaults to distributing to the first column. I'm not sure how much of a problem this is since in both cases the user isn't specifying a distribution key. (I could be very wrong with this assumption)

Yes that is correct, but only for `CTAS (CREATE TABLE AS <query>)` statements without `DISTRIBUTED` clause.
For normal `CREATE` statements without `DISTRIBUTED`, the default distribution is always hashed (with optimizer ON/OFF). This can be controlled by `gp_create_table_random_default_distribution`.

**Comment by StevenLuoo** [comment] 2018-04-03 02:36
@d 
I agree that what you say "X" may also be distributed to the same segment when the data is not explicitly assigned to the same segment. But it's only maybe.
In the above scenario, 100% of all data is distributed to the same segment. I think it's not 'maybe', it's 'absolutely'.
So I think it's still not normal.

**Comment by StevenLuoo** [comment] 2018-04-03 02:45
@Eulerizeit 
The data is distributed randomly with optimizer OFF, and is not randomly distribution with optimizer ON. I think it's poor optimization. ^_^

Maybe Random Distribution is poorly named, but I think it's what we really need.

**Comment by Eulerizeit** [comment] 2018-04-03 03:03
> @Eulerizeit
> The data is distributed randomly with optimizer OFF, and is not randomly distribution with optimizer ON. I think it's poor optimization. ^_^

@dhanashreek89 based on what you wrote this doesn't make sense. Or I am having difficulty understanding what both you and @d wrote.

**Comment by hsyuan** [comment] 2018-04-03 06:54
Agree with @StevenLuoo, distributing all the tuples to a single segment should not be the expected behavior of clause `distributed randomly`.

**Comment by dhanashreek89** [comment] 2018-04-03 19:19
>> @dhanashreek89 based on what you wrote this doesn't make sense. Or I am having difficulty understanding what both you and @d wrote.

Sorry if I was not clear in my previous comment. To elaborate, I was only adding to the discussion about DEFAULT distribution i.e. when a table is created WITHOUT a `DISTRIBUTED` clause.

In the current repro, there is an explicit distribute randomly hence that does not apply here.
`create table test (id int,aaa varchar(20),bbb varchar(20)) distributed randomly;`

**Comment by hlinnaka** [comment] 2019-01-15 06:55
I cannot reproduce this on gpdb master anymore:
```
psql (9.4.20)
Type "help" for help.

postgres=# set optimizer=on;
SET
postgres=#  create table test (id int,aaa varchar(20),bbb varchar(20)) distributed randomly;
CREATE TABLE
postgres=# explain insert into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),( 41,'aaaa','bbbbb'),( 51,'aaaa','bbbbb'),( 61,'aaaa','bbbbb'),( 71,'aaaa','bbbbb'),( 81,'aaaa','bbbbb'),( 91,'aaaa','bbbbb'),(101,'aaaa','bbbbb'),(111,'aaaa','bbbbb'),(121,'aaaa','bbbbb'),(131,'aaaa','bbbbb'),(141,'aaaa','bbbbb'),(151,'aaaa','bbbbb'),(161,'aaaa','bbbbb'),(171,'aaaa','bbbbb'),(181,'aaaa','bbbbb'),(191,'aaaa','bbbbb'),(201,'aaaa','bbbbb'),(211,'aaaa','bbbbb'),(221,'aaaa','bbbbb'),(231,'aaaa','bbbbb'),(241,'aaaa','bbbbb'),(251,'aaaa','bbbbb'),(261,'aaaa','bbbbb'),(271,'aaaa','bbbbb'),(281,'aaaa','bbbbb'),(291,'aaaa','bbbbb'),(301,'aaaa','bbbbb'),(311,'aaaa','bbbbb'),(321,'aaaa','bbbbb'),(331,'aaaa','bbbbb'),(341,'aaaa','bbbbb'),(351,'aaaa','bbbbb'),(361,'aaaa','bbbbb'),(371,'aaaa','bbbbb'),(381,'aaaa','bbbbb'),(391,'aaaa','bbbbb'),(401,'aaaa','bbbbb'),(411,'aaaa','bbbbb'),(421,'aaaa','bbbbb'),(431,'aaaa','bbbbb'),(441,'aaaa','bbbbb'),(451,'aaaa','bbbbb'),(461,'aaaa','bbbbb'),(471,'aaaa','bbbbb'),(481,'aaaa','bbbbb'),(491,'aaaa','bbbbb'),(501,'aaaa','bbbbb'),(511,'aaaa','bbbbb'),(521,'aaaa','bbbbb'),(531,'aaaa','bbbbb'),(541,'aaaa','bbbbb'),(551,'aaaa','bbbbb'),(561,'aaaa','bbbbb'),(571,'aaaa','bbbbb'),(581,'aaaa','bbbbb'),(591,'aaaa','bbbbb'),(601,'aaaa','bbbbb');
                                        QUERY PLAN                                        
------------------------------------------------------------------------------------------
 Insert  (cost=0.00..1.88 rows=20 width=20)
   ->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..0.01 rows=20 width=24)
         ->  Result  (cost=0.00..0.00 rows=20 width=24)
               ->  Result  (cost=0.00..0.00 rows=20 width=20)
                     One-Time Filter: (gp_execution_segment() = 0)
                     ->  Values Scan on "Values"  (cost=0.00..0.00 rows=20 width=20)
 Optimizer: PQO version 3.19.0
(7 rows)

postgres=# insert into test values ( 11,'aaaa','bbbbb'),( 21,'aaaa','bbbbb'),( 31,'aaaa','bbbbb'),( 41,'aaaa','bbbbb'),( 51,'aaaa','bbbbb'),( 61,'aaaa','bbbbb'),( 71,'aaaa','bbbbb'),( 81,'aaaa','bbbbb'),( 91,'aaaa','bbbbb'),(101,'aaaa','bbbbb'),(111,'aaaa','bbbbb'),(121,'aaaa','bbbbb'),(131,'aaaa','bbbbb'),(141,'aaaa','bbbbb'),(151,'aaaa','bbbbb'),(161,'aaaa','bbbbb'),(171,'aaaa','bbbbb'),(181,'aaaa','bbbbb'),(191,'aaaa','bbbbb'),(201,'aaaa','bbbbb'),(211,'aaaa','bbbbb'),(221,'aaaa','bbbbb'),(231,'aaaa','bbbbb'),(241,'aaaa','bbbbb'),(251,'aaaa','bbbbb'),(261,'aaaa','bbbbb'),(271,'aaaa','bbbbb'),(281,'aaaa','bbbbb'),(291,'aaaa','bbbbb'),(301,'aaaa','bbbbb'),(311,'aaaa','bbbbb'),(321,'aaaa','bbbbb'),(331,'aaaa','bbbbb'),(341,'aaaa','bbbbb'),(351,'aaaa','bbbbb'),(361,'aaaa','bbbbb'),(371,'aaaa','bbbbb'),(381,'aaaa','bbbbb'),(391,'aaaa','bbbbb'),(401,'aaaa','bbbbb'),(411,'aaaa','bbbbb'),(421,'aaaa','bbbbb'),(431,'aaaa','bbbbb'),(441,'aaaa','bbbbb'),(451,'aaaa','bbbbb'),(461,'aaaa','bbbbb'),(471,'aaaa','bbbbb'),(481,'aaaa','bbbbb'),(491,'aaaa','bbbbb'),(501,'aaaa','bbbbb'),(511,'aaaa','bbbbb'),(521,'aaaa','bbbbb'),(531,'aaaa','bbbbb'),(541,'aaaa','bbbbb'),(551,'aaaa','bbbbb'),(561,'aaaa','bbbbb'),(571,'aaaa','bbbbb'),(581,'aaaa','bbbbb'),(591,'aaaa','bbbbb'),(601,'aaaa','bbbbb');
INSERT 0 60
postgres=# select gp_segment_id, count(*) from test group by gp_segment_id;
 gp_segment_id | count 
---------------+-------
             0 |    22
             2 |    19
             1 |    19
(3 rows)

```
Not sure when or how this changed, but I guess it's fixed now. Closing.

**Closed by hlinnaka** 2019-01-15 06:55 UTC
Labels: GPORCA, Hacktoberfest, help wanted, skew
