### ISSUE TITLE
error on multi dqa from planner plan

### ISSUE THREAD

**Issue by MengqiWu** [greenplum-db/gpdb#14308] opened 2022-10-21 02:06 UTC
### Greenplum version or build
6x_stable

### Actual behavior
ERROR:  could not find hash function for hash operator 0 (execGrouping.c:241)

### Step to reproduce the behavior
create table t1 (a int primary key, b int);
create table t2 (i int, j int);
set enable_groupagg to off;
explain select a, count(distinct b), count(distinct j) from t1 join t2 on t1.a = t2.i group by a;
ERROR:  could not find hash function for hash operator 0 (execGrouping.c:241)

**Comment by kainwen** [comment] 2023-02-05 10:29
Seems the same issue as https://github.com/greenplum-db/gpdb/issues/14817 and can be fixed by https://github.com/greenplum-db/gpdb/pull/14781

@CharlieTTXX would you please help double confirm? If is the same, please close this. Thanks!

So sorry @MengqiWu long time no reply.

**Comment by CharlieTTXX** [comment] 2023-02-06 02:04
I've confirmed that this issue had been solved by PR https://github.com/greenplum-db/gpdb/pull/14781. 
Since that PR will be merged soon, we could close the issue.

**Comment by kainwen** [comment] 2023-02-06 02:05
Duplicated with https://github.com/greenplum-db/gpdb/issues/14817

**Closed by kainwen** 2023-02-06 02:05 UTC
Labels: type: bug
