### ISSUE TITLE
Incorrect environment variables generation with greenplum_path.sh

### ISSUE THREAD

**Issue by mannikov** [greenplum-db/gpdb#12420] opened 2021-08-03 23:44 UTC
I'm using symlinks in my greenplum installation and I noticed the issue with environment variables generation

### Greenplum version or build
6.17.1

### OS version and uname -a
Centos 7.7
Linux 634ec5414959 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce the behavior
1. Install latest version of GreenPlum
Example: sudo yum install https://github.com/greenplum-db/gpdb/releases/download/6.17.1/open-source-greenplum-db-6.17.1-rhel7-x86_64.rpm
2. Make symlink to GP directory from any other directory. Folder name should not be equal to "greenplum-db"
Example: sudo ln -s /usr/local/greenplum-db ~/gpdb
3. Init GP environment variables
Example: source ~/gpdb/greenplum_path.sh
4. Print the value of GPHOME variable
Example: echo ${GPHOME}

### Expected behavior
/usr/local/greenplum-db

### Actual behavior
/home/gpadmin/greenplum-db

### Cause
The problem is in file greenplum_path.sh, need to fix the code that generated GPHOME value

**Comment by BaiShaoqi** [comment] 2021-08-17 03:26
Hi, @mannikov 
From release's team's perspective: 
the expected behavior should be the following:
`/usr/local/greenplum-db-6.17.1`

instead of your assumption:
`/usr/local/greenplum-db`

To me , the actual fix should be here: https://github.com/greenplum-db/greenplum-database-release/blob/main/ci/concourse/scripts/greenplum-db-6.spec#L152
since the sed command is not work as expected, it should replace the GPHOME pointing to `/usr/local/greenplum-db-6.17.1`, right now the sed command does not replace anything. which makes the bug you see.

**Comment by BaiShaoqi** [comment] 2021-08-17 07:22
correct myself, with @50wu  the https://github.com/greenplum-db/greenplum-database-release/blob/main/ci/concourse/scripts/greenplum-db-6.spec#L152 should be removed. 
So the bug should be fixed in gpMgmt/bin/generate-greenplum-path.sh.

**Comment by khuddlefish** [comment] 2021-08-19 00:23
Hi @mannikov, thanks for raising an issue. I notice in your example you seem to be creating multiple layers of symlinks. 
`~/gpdb -> /usr/local/greenplum-db -> /usr/local/greenplum-db-6.17.1`

We usually expect $GPHOME to point at the lowest level installation directory rather than a symlink. Even with your $GPHOME change in `greenplum_plath.sh` your $GPHOME would be pointing at the symlink `/usr/local/greenplum-db`. I think it will probably be ok, but it's possible there are places in the code that assume $GPHOME is a regular file rather than a symlink.

**Comment by ashwinstar** [comment] 2021-09-01 18:41
This commit https://github.com/greenplum-db/gpdb/commit/b9a2acec5956ab5a2288757d7bc9d8bb52622d8f fixed the issue closing.

**Closed by ashwinstar** 2021-09-01 18:41 UTC
