### ISSUE TITLE
Vacuum on individual AO partitions of AO partitioned table may result in breaking SELECT against main table.

### ISSUE THREAD

**Issue by sokolval** [greenplum-db/gpdb#16545] opened 2023-10-04 10:49 UTC
### Greenplum version or build
PostgreSQL 9.4.26 (Greenplum Database 6.25.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit compiled on Aug 23 2023 15:46:59

### OS version and uname -a
Ubuntu Xenial  Linux  5.4.196-37 #1 SMP Thu May 26 12:08:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
### autoconf options used ( config.status --config )
./configure --with-perl --with-python --without-gssapi --disable-gpcloud --with-libxml --with-system-tzdata=/usr/share/zoneinfo --prefix=/usr/local/gpdb LDFLAGS=-L/usr/lib/jni/ --with-pam --with-openssl
### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /etc/postgresql
PGXS = /usr/local/gpdb/lib/x86_64-linux-gnu/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/local/gpdb/include' '--mandir=/usr/local/gpdb/share/man' '--infodir=/usr/local/gpdb/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--libexecdir=/usr/local/gpdb/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-perl' '--with-python' '--without-gssapi' '--disable-gpcloud' '--with-libxml' '--with-system-tzdata=/usr/share/zoneinfo' '--prefix=/usr/local/gpdb' 'LDFLAGS=-L/usr/lib/jni/' '--with-pam' '--with-openssl' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/local/gpdb/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -Werror=uninitialized -Werror=implicit-function-declaration -I/usr/local/gpdb/include
CFLAGS_SL = -fPIC
LDFLAGS = -L/usr/lib/jni/ -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib/x86_64-linux-gnu',--enable-new-dtags -L/usr/local/gpdb/lib/x86_64-linux-gnu
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxerces-c -lxml2 -lpam -lrt -lzstd -lrt -lcrypt -ldl -lm -L/usr/local/gpdb/lib/x86_64-linux-gnu
VERSION = PostgreSQL 9.4.26

### Expected behavior
When vacuum is run against individual partitions of AO table, it should go as follows, not conflicting with any other process, lock partition object for the duration of vacuum  at maximum is expected.
### Actual behavior
When vacuum runs against individual partitions of AO table, and SELECT query is run against Main partitioned table, sometimes SELECT falls into situation when file for partition of AO table is not in place after vacuum, thus giving out an error: read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59272170.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg106 slice1 *:*:*:*:*:4106 pid=331311) (cdbbufferedread.c:211)
### Step to reproduce the behavior
We reproduced this issue in our Non-prod environment consisting of 128 segments on 16 hosts. However this is regularly happening on PROD one with 128 segments on 64 hosts. Not sure if less segments will suit to make this behaviour happen.
How to reproduce:
1. Create AO Partitioned table. I used following script:
```
create table test_vacuum_prt
(rec_date timestamp without time zone,
a bigserial,
 b text, c text,
 d text, e bigint, f text, g text, h text, i text, j text, k text)    with (appendoptimized=true, orientation=row,compresstype=zstd, compresslevel=19)
    distributed randomly
    partition by range(rec_date) (start ('2020-01-01 00:00:00.00000'::timestamp without time zone) end  ('2024-01-01 00:00:00.00000'::timestamp without time zone) every ('1 month'::INTERVAL))
```
I put high compress level to make read write to table slower, perhaps this is excessive.

2. Fill table with data: e.g. 
`insert into test_vacuum_prt (rec_date,e) select '2020-01-01',generate_series(1,200000000);
update test_vacuum set b=(md5(a::text||'d'));
update test_vacuum set c=(md5(a::text||'ef'));
update test_vacuum set d=(md5(a::text||'d')||md5(c));
update test_vacuum set f=(md5(a::text||'d')||md5(c||'g'));
update test_vacuum set g=(md5(a::text||'d')||e::text);
update test_vacuum set h=(md5(g||'d')||md5(d));
update test_vacuum set i=(md5(a::text||'d'));
update test_vacuum set j=(md5(i||'d'));
update test_vacuum set k=(md5(h));
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k)
select rec_date+'32 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+200000001, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')) from test_vacuum_prt;
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k)
select rec_date+'64 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+400000002, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')) from test_vacuum_prt;
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k)
select rec_date+'127 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+800000008, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')) from test_vacuum_prt;
select rec_date+'257 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+1600000010, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')) from test_vacuum_prt;
select rec_date+'514 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+3200000012, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')) from test_vacuum_prt;
`
In our case partitions got size approximately 20-30 GB
3. Update table data, to make size of partitions 2x-4x from initial, for example like this - here I update just portion of partitions, for me it was enough.
`update test_vacuum_prt set c=md5(c)||'f', b=md5(b||'f')||'f' where round(e*10/3)/10=round(e/3) and rec_date<'2021-01-01';
update test_vacuum_prt set c=md5(d)||'d', d=md5(c||'g')||'f' where round(e*10/5)/10=round(e/5) and rec_date<'2021-01-01';
update test_vacuum_prt set b=md5(b)||'h', c=md5(b||'f')||'f' where round(e*10/7)/10=round(e/7) and rec_date<'2021-01-01';
update test_vacuum_prt set d=md5(d)||'e', b=md5(b||'u')||'u' where round(e*10/4)/10=round(e/4) and rec_date<'2021-01-01';
update test_vacuum_prt set d=md5(c)||'f', b=md5(b||'f')||'f' where round(e*10/2)/10=round(e/2) and rec_date<'2021-01-01';
update test_vacuum_prt set h=md5(h)||'f', j=md5(b||'f')||'f' where round(e*10/3)/10=round(e/3) and rec_date<'2021-01-01';
update test_vacuum_prt set i=md5(d)||'d', d=md5(c||'g')||'f' where round(e*10/5)/10=round(e/5) and rec_date<'2021-01-01';
update test_vacuum_prt set j=md5(b)||'h', c=md5(b||'f')||'f' where round(e*10/7)/10=round(e/7) and rec_date<'2021-01-01';
update test_vacuum_prt set k=md5(d)||'e', b=md5(b||'u')||'u' where round(e*10/4)/10=round(e/4) and rec_date<'2021-01-01';
update test_vacuum_prt set f=md5(c)||'f', i=md5(b||'f')||'f' where round(e*10/2)/10=round(e/2) and rec_date<'2021-01-01';
`
This could be extended and run several times if needed.
4. Get prepared to run test - you can open 2 consoles - one will run select; another will run vacuum. We tried running vacuum on all partitions - but it just overloaded cluster and was not helpful to reproduce the case. Finally just several vacuums was able to reproduce the case. So in console 1 please run the following:
`psql -d test1 -c "select count(*) from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(e), max(e)  from test_vacuum_prt" & sleep 3 ; psql -d test1 -c "select min(f), max(f)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(g), max(g)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(k), max(k)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(i), max(i)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(j), max(j)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select min(c), max(c)  from test_vacuum_prt" & sleep 3; psql -d test1 -c "select avg(e), max(h)  from test_vacuum_prt"`

on another console 2 please run the following:
`sleep 5; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_1;" & sleep 1; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_2;" & sleep 2; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_3;" & sleep 2; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_4;" & sleep 2; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_5;" & sleep 2; psql -d test1 -c "vacuum test_vacuum_prt_1_prt_6;"`

In my case it required couple of dry runs, but finally I got in console 1 result + set of error messages;
` min |    max    
-----+-----------
   1 | 807006737
(1 row)

                min                |                                                max                                                 
-----------------------------------+----------------------------------------------------------------------------------------------------
 00000000c64b310dd7277e2840d0fc65f | fffffff9230f605bfbd47ffe69aa857d5fd85114f30e2330ee70d22af4764c12f592862089fcd79471d67d489dc3d03bx4
(1 row)

ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59272170.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg106 slice1 *:*:*:*:4106 pid=331311) (cdbbufferedread.c:211)
ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59259704.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg105 slice1 *:*:*:*4105 pid=331495) (cdbbufferedread.c:211)
ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59264068.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg115 slice1 *:*:*:*:4115 pid=381045) (cdbbufferedread.c:211)
[2]   Done                    psql -d test1 -c "select min(e), max(e)  from test_vacuum_prt"

[3]+  Stopped                 psql -d test1 -c "select min(f), max(f)  from test_vacuum_prt"
[4]   Exit 1                  psql -d test1 -c "select min(g), max(g)  from test_vacuum_prt"
[6]   Exit 1                  psql -d test1 -c "select min(i), max(i)  from test_vacuum_prt"
[8]   Done                    psql -d test1 -c "select min(c), max(c)  from test_vacuum_prt"
$ ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59264068.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg111 slice1 test1:4111 pid=330824) (cdbbufferedread.c:211)
ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59287138.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg109 slice1 test1:4109 pid=331330) (cdbbufferedread.c:211)
ERROR:  read beyond eof in table "test_vacuum_prt_1_prt_4" file "base/16504/59264068.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg107 slice1 test1:4107 pid=331241) (cdbbufferedread.c:211)
`

This issue is basically the reincarnation of Issue #11785 (https://github.com/greenplum-db/gpdb/issues/11785) previously we were unable to reproduce it, however now it was successful.
This error hits us 3-10 times daily in PROD, during maintenance vacuum window.....

**Comment by ashwinstar** [comment] 2023-10-04 11:25
Thanks for report. We will look into the issue. Most likely reason being while dropping drop-pending state file not able to block concurrent select via root table.

**Comment by sokolval** [comment] 2023-10-05 14:24
I have additional info regarding this issue.
At some rare cases similar situation leads to another error:
at master segment we can see error message: con570007,cmd46,seg-1,,dx4988541,x203372020,sx1,"ERROR","58M01","Invalid execution statistics received stats node-count mismatch: cdbexplain_recvExecStats() ctx.nStatInst 0 hdr->nInst 15",,"Please verify that all instances are using the correct Greenplum Database software version.

When looking at segments there are such messages: 

- a lot of such ones but not on all segs: "ERROR","XX000","read beyond eof in table ""wo_empty_hist_1_prt_2023"" file ""pg_tblspc/18827/GPDB_6_301908232/16384/242436848.115"", read position 0 (small offset 0), actual read length 0 (large read length 18480) (cdbbufferedread.c:211)  
- very rarely on some segment: "ERROR","XX000","relation 1061216674 deleted while still in use (relcache.c:2306)"
- most of other segments report Interconnect error or cancelling MPP operation.

It seems that "Invalid execution statistics received stats node-count mismatch" is caused by "read beyond eof in table" hope that you can confirm?

**Comment by VladislavePolyakov** [comment] 2023-10-09 22:17
Can repeat ERROR
```
2023-10-10 00:00:27.662134 MSK,"gpadmin","gpms228",p2072,th-327497600,"[local]",,2023-10-09 23:45:52 MSK,0,con225522,cmd2,seg-1,,,,sx1,"ERROR","XX000","read beyond eof in table ""test_vacuum_prt_1_prt_6"" file ""base/6015522/4746151.1"", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:211)  (seg2 slice1 192.168.10.207:33000 pid=26337) (cdbbufferedread.c:211)",,,,,,"select min(f), max(f)  from test_vacuum_prt",0,,"cdbbufferedread.c",211,"Stack trace:
1    0xbff15c postgres errstart (elog.c:557)
2    0xca48be postgres cdbdisp_get_PQerror (cdbdispatchresult.c:585)
3    0xca4a2d postgres cdbdisp_dumpDispatchResult (cdbdispatchresult.c:497)
4    0xca4b2b postgres cdbdisp_dumpDispatchResults (cdbdispatchresult.c:652)
5    0xca1d83 postgres CdbDispatchHandleError (cdbdisp.c:188)
6    0x8da091 postgres mppExecutorCleanup (execUtils.c:2376)
7    0x8bdda2 postgres standard_ExecutorRun (execMain.c:1190)
8    0x8bde65 postgres ExecutorRun (execMain.c:992)
9    0xa9a097 postgres <symbol not found> (pquery.c:1159)
10   0xa9c0c1 postgres PortalRun (pquery.c:1006)
11   0xa960c0 postgres <symbol not found> (postgres.c:1855)
12   0xa991b0 postgres PostgresMain (postgres.c:5326)
13   0x6b2b93 postgres <symbol not found> (postmaster.c:4484)
14   0xa1d3a6 postgres PostmasterMain (postmaster.c:1520)
15   0x6b6af1 postgres main (main.c:205)
16   0x7f27e914d555 libc.so.6 __libc_start_main + 0xf5
17   0x6c299c postgres <symbol not found> + 0x6c299c
"
2023-10-10 00:00:27.662264 MSK,"gpadmin","gpms228",p2072,th-327497600,"[local]",,2023-10-09 23:45:52 MSK,0,con225522,cmd2,seg-1,,,,sx1,"LOG","00000","An exception was encountered during the execution of statement: select min(f), max(f)  from test_vacuum_prt",,,,,,"select min(f), max(f)  from test_vacuum_prt",0,,"elog.c",2116,
```

PS:
Little correct you query in part insert
```
update test_vacuum_prt set b=(md5(a::text||'d')); 
update test_vacuum_prt set c=(md5(a::text||'ef')); 
update test_vacuum_prt set d=(md5(a::text||'d')||md5(c)); 
update test_vacuum_prt set f=(md5(a::text||'d')||md5(c||'g')); 
update test_vacuum_prt set g=(md5(a::text||'d')||e::text); 
update test_vacuum_prt set h=(md5(g||'d')||md5(d)); 
update test_vacuum_prt set i=(md5(a::text||'d')); 
update test_vacuum_prt set j=(md5(i||'d')); 
update test_vacuum_prt set k=(md5(h)); 
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k) select rec_date+'32 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+200000001, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')),(md5(i||'d')) from test_vacuum_prt; 
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k) select rec_date+'64 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+400000002, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')),(md5(k||'d')) from test_vacuum_prt; 
insert into test_vacuum_prt (rec_date,b,c,d,e,f,g,h,i,j,k) select rec_date+'127 days'::interval,(md5(a::text||'ef')), (md5(i||'d')),(md5(h)||md5(g)), e+800000008, (md5(a::text||'d')),(md5(a::text||'ef')), (md5(g||'d')||md5(d)), (md5(a::text||'d')||e::text),(md5(i||'d')),(md5(k||'d')) from test_vacuum_prt; 
```

Have same problem on production. Now clear undestend tha reason is vacuum on AO table.

**Comment by l-wang** [comment] 2023-10-12 01:52
Thanks for reporting. I can reproduce locally and I'm looking into the issue. Looks like the segfile which SELECT is reading is truncated by VACUUM during DROP phase. So seems what Ashwin said: holding `AccessEclusiveLock` during the drop phase on the leaf partition only is not enough to block SELECT on the root table. I will report back tomorrow.

**Comment by l-wang** [comment] 2023-10-13 03:52
Here's a minimal repro:

table setup:
```sql
drop table if exists foo;
create table foo (a int, b int) WITH (appendonly=true) partition by range(b) (start (1) end (10) every (5));
insert into foo select i, i%9+1 from generate_series(1, 2000000)i;
update foo set a = a + 2 where a % 2 = 1;
update foo set a = a + 2 where a % 2 = 0;
```
attach gdb to seg0 and break at GetTransactionSnapshot()
```
(gdb) b GetTransactionSnapshot
(gdb) continue
```
psql session 1:
```sql
select count(*) from foo; -- this should block
```
psql session 2:
```sql
-- setting below debugging GUCs is optitional
set Debug_appendonly_print_compaction to on;
set client_min_messages to log;
vacuum analyze foo_1_prt_1; -- "vacuum foo;" also works
```
detach from gdb

session 1 emit following ERROR:
```
ERROR:  read beyond eof in table "foo_1_prt_1" file "base/12812/82554.1", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:202)  (seg0 slice1 127.0.1.1:6002 pid=3570172) (cdbbufferedread.c:202)
```
stack trace in seg0 LOG:
```
2023-10-12 20:33:55.338407 PDT,"pivotal","postgres",p3570172,th-1097385600,"127.0.0.1","47264",2023-10-12 20:21:16 PDT,0,con7,cmd40,seg0,slice1,,,sx1,"ERROR","XX000","read beyond eof in table ""foo_1_prt_1"" file ""base/12812/82554.1"", read position 0 (small offset 0), actual read length 0 (large read length 65536) (cdbbufferedread.c:202)",,,,,,"select count(*) from foo;",0,,"cdbbufferedread.c",202,"Stack trace:
1    0x55c591931b0d postgres errstart + 0x473
2    0x55c591a1d492 postgres <symbol not found> + 0x91a1d492
3    0x55c591a1d2c0 postgres BufferedReadSetFile + 0x2b6
4    0x55c591a16031 postgres <symbol not found> + 0x91a16031
5    0x55c591a16222 postgres AppendOnlyStorageRead_OpenFile + 0x1e7
6    0x55c591335ce8 postgres <symbol not found> + 0x91335ce8
7    0x55c5913378b4 postgres <symbol not found> + 0x913378b4
8    0x55c591337a64 postgres <symbol not found> + 0x91337a64
9    0x55c591338769 postgres appendonly_getnext + 0x3c
10   0x55c59156d669 postgres <symbol not found> + 0x9156d669
11   0x55c59153ce1d postgres <symbol not found> + 0x9153ce1d
12   0x55c59153cfa4 postgres ExecScan + 0x185
13   0x55c59156d73b postgres ExecSeqScan + 0x2d
14   0x55c591590aee postgres ExecDynamicSeqScan + 0xd6
15   0x55c59152c620 postgres ExecProcNode + 0x2e4
16   0x55c59159124d postgres ExecSequence + 0x1c7
17   0x55c59152c5f6 postgres ExecProcNode + 0x2ba
18   0x55c5915892f9 postgres <symbol not found> + 0x915892f9
19   0x55c591589196 postgres ExecMotion + 0x231
20   0x55c59152c857 postgres ExecProcNode + 0x51b
21   0x55c59152618b postgres <symbol not found> + 0x9152618b
22   0x55c59152215d postgres standard_ExecutorRun + 0x41d
23   0x55c591521d3d postgres ExecutorRun + 0x54
24   0x55c5917a4986 postgres <symbol not found> + 0x917a4986
25   0x55c5917a4576 postgres PortalRun + 0x30a
26   0x55c59179a6e6 postgres <symbol not found> + 0x9179a6e6
27   0x55c5917a19e7 postgres PostgresMain + 0x14a2
28   0x55c5916f9641 postgres <symbol not found> + 0x916f9641
29   0x55c5916f8b6e postgres <symbol not found> + 0x916f8b6e
30   0x55c5916f4279 postgres <symbol not found> + 0x916f4279
```

**Comment by l-wang** [comment] 2023-10-17 08:36
RCA: problem has two folds:
1. The SELECT query locks only the root table `foo` with `AccessShareLock` on QD before the query gets dispatched to the QEs. Up until `ExecDynamicSeqScan()` (or `ExecInitSeqScan()` for planner) which opens the child partition  `foo_1_prt_1` with `AccessShareLock`, no one locks the child partition `foo_1_prt_1` on either QD or QE.
```
postgres=# select relation::regclass, relation, pid, mode, granted, mppsessionid, mppiswriter, gp_segment_id from pg_locks where relation = 'foo_1_prt_1'::regclass or relation = 'foo'::regclass;
 relation | relation |  pid   |      mode       | granted | mppsessionid | mppiswriter | gp_segment_id 
----------+----------+--------+-----------------+---------+--------------+-------------+---------------
 foo      |   139503 | 242085 | AccessShareLock | t       |           10 | t           |            -1
(1 row)
```
The lack of lock on the child partition `foo_1_prt_1` allows the concurrent VACUUM drop phase to open it with `AccessExclusiveLock`, and then procceed to truncate the old awaiting drop segment file and update pg_aoseg_rel. Had the child partition been locked by SELECT, the VACUUM drop phase would have been skipped via below code path:
https://github.com/greenplum-db/gpdb/blob/3369e14ffd0a338926b83712468e538bb4906f10/src/backend/commands/vacuum.c#L923-L941

2. SELECT scans pg_aoseg_rel in `GetAllFileSegInfo_pg_aoseg_rel()` to collect the segment files to read. It uses `appendOnlyMetaDataSnapshot` for visibility check of the tuples in pg_aoseg_rel. 
https://github.com/greenplum-db/gpdb/blob/adfca719d39c368eac719fb038fedb14571a6cc8/src/backend/access/appendonly/aosegfiles.c#L395
However, `appendOnlyMetaDataSnapshot` is just the same as the SELECT query's transaction snapshot, so it has an older xmin than the snapshot for VACUUM drop phase.
https://github.com/greenplum-db/gpdb/blob/6195b96780312d836473b04fd08cc0345999eb9a/src/backend/executor/nodeSeqscan.c#L149
Hence, SELECT thinks the old segment file is still in use with a non-zero EOF, even though the segment has already been truncated by VACUUM drop phase.

The fix needs more thoughts, here're some ideas:
1. Let SELECT acquire `AccessShareLock` on QD for the child partition during query planning. 7X does this:
ORCA:
https://github.com/greenplum-db/gpdb/blob/5e9bc3a250421ba20247805f6b41bfccf6ded35a/src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp#L574-L588
planner:
https://github.com/greenplum-db/gpdb/blob/0f5f6635da048d1e74ce28c1c3140475571d949b/src/backend/optimizer/util/inherit.c#L372-L381
2. Use a more refreshed snapshot for scanning pg_aoseg_rel in `GetAllFileSegInfo_pg_aoseg_rel()`. Maybe use `GetCatalogSnapshot()` instead?
3. 7X improved the logic in `AppendOptimizedCollectDeadSegments()` so that if there was a reader accessing a segment file which was changed to AWAITING_DROP in later VACUUM compaction, the segment file will not be dropped. See commit https://github.com/greenplum-db/gpdb/commit/5778f31124d5737e18d76f8d06f07f96c31c8be7

Option 1 seems most feasible. Although for ORCA it would lock all child partitions even if they're supposed to be pruned, since ORCA in 6X does partition pruning during query execution.
Option 2 needs more thoughts.
Option 3 seems too much code change for stable version. 

Temporary workaround:
Explicitly enclose the concurrent SELECT statement in a BEGIN;END block, for example:
```sql
begin;
lock table foo in access share mode;
select count(*) from foo;
end;
```

PS: 
1. The above minimal repro has stack trace with ORCA, but the same ERROR happens to planner as well. Planner does briefly hold AccessShareLock on the partition on QE, but the lock gets released soon after static partition pruning.
2. AOCS partitioned table can also hit this ERROR for similar reasons.

**Comment by divyeshddv** [comment] 2023-10-20 22:22
w/ @soumyadeep2007

We believe that ideally this problem should be solved by acquiring and releasing appropriate locks at correct time.
Exploring solution 1 with acquiring AccessShareLock on QD:

7X: Partitioned children are treated as inherited tables, and use the same locking mechanism as inherited tables
```
relation_open relation.c:55
table_open table.c:48
expand_partitioned_rtentry inherit.c:381
expand_inherited_rtentry inherit.c:146
add_other_rels_to_query initsplan.c:173
query_planner planmain.c:298
```
6X: For partitioned tables, we don't grab locks for child tables.
However, For inherited tables, We grab AccessSharelocks for inherited children, and are held for query duration
```
LockRelationOid lmgr.c:105
find_inheritance_children pg_inherits.c:121
find_all_inheritors pg_inherits.c:211
expand_inherited_rtentry prepunion.c:1431
expand_inherited_tables prepunion.c:1354
subquery_planner planner.c:706
```
Need to explore:
Can we treat partitioned children as inherited tables (just for locking) for 6X?
Can we implement similar locks for partitioned children when we add the rtentry?

**Comment by divyeshddv** [comment] 2023-10-23 17:59
> 6X: For partitioned tables, we don't grab locks for child tables - **_Which is causing the problem_** However, For inherited tables, We grab AccessSharelocks for inherited children, and are held for query duration
> 
> ```
> LockRelationOid lmgr.c:105
> find_inheritance_children pg_inherits.c:121
> find_all_inheritors pg_inherits.c:211
> expand_inherited_rtentry prepunion.c:1431
> expand_inherited_tables prepunion.c:1354
> subquery_planner planner.c:706
> ```

The same stack trace actually grabs locks for child partitions, but we release those locks later in `expand_inherited_rtentry()`
```
/* Close child relations, but keep locks */
		if (childOID != parentOID)
			heap_close(newrelation, rel_needs_long_lock(childOID) ? NoLock: lockmode);
```
This is because rel_needs_long_lock turns false for partitioned children.
**This is a regression introduced by d40e48265fd1f1c9d2435e84952b1b19820449a1 (in 6.24.0 onwards)**
We tried with earlier commit and the issue doesn't repro as the locks don't get released.

**Comment by divyeshddv** [comment] 2023-10-23 21:25
[v1-0001-WIP-Keep-partition-child-lock-until-end-of-select.patch.txt](https://github.com/greenplum-db/gpdb/files/13079320/v1-0001-WIP-Keep-partition-child-lock-until-end-of-select.patch.txt)
This simple patch fixes the above issue and also passes the test failure which caused the earlier revert: snapshot_index_corruption

**Comment by divyeshddv** [comment] 2023-10-25 23:29
w/ @soumyadeep2007 
implemented the 'SELECTs holding locks until end of transaction' solution on https://github.com/greenplum-db/gpdb/compare/6X_STABLE...divyeshddv:gpdb:fix_vacuum_select
However, with this solution we easily run out of `max_locks_per_transaction`.
Considering this fix would go in a minor version upgrade, it won't be ideal to run out of `max_locks_per_transaction` on existing workloads- requiring a guc update. However, it might be necessary if there is no other viable solution.

Next steps:
Explore solution: During VACUUM, Do a conditional drop phase based on whether latest xmin for aoseg entries are visible on another transactions. This won't require getting extra locks.

**Comment by divyeshddv** [comment] 2023-11-02 02:18
w/ @soumyadeep2007 
Implemented a check if the file can be safely dropped on QE during Vacuum drop phase. This check is done by comparing Oldest xmin of any ongoing distributed transaction, with the xmin of the vacuum.
The check ensures that if any transaction can see the file, we skip dropping the file. Only drop the file if no other transaction is currently trying to read it.
branch: https://github.com/greenplum-db/gpdb/compare/6X_STABLE...divyeshddv:fix_vacuum_select_xmin?expand=1

**Comment by sokolval** [comment] 2023-11-08 16:59
Hello!
Do you have any idea when it will be  released?

**Comment by gpopt** [comment] 2024-02-15 18:17
This has been fixed by https://github.com/greenplum-db/gpdb/pull/16790

**Closed by gpopt** 2024-02-15 18:17 UTC
Labels: type: bug, version: 6X_STABLE
