### ISSUE TITLE
Enabling `gp_enable_global_deadlock_detector` causes concurrent update failure when updating data on non-distribution columns

### ISSUE THREAD

**Issue by CC-Hsu** [greenplum-db/gpdb#12357] opened 2021-07-20 13:05 UTC
### Greenplum version or build
GPDB v6.16.2

### OS version and uname -a
RHEL 7.8

### Expected behavior
When `gp_enable_global_deadlock_detector` is `off`, the following two sessions does not cause any SQL failure, just waiting for lock release.
And we expect that the same holds even when `gp_enable_global_deadlock_detector` is `on`.

**SESSION1**
```
[gpadmin@mdw ~]$ gpconfig -s gp_enable_global_deadlock_detector
Values on all segments are consistent
GUC          : gp_enable_global_deadlock_detector
Master  value: off
Segment value: off
[gpadmin@mdw ~]$ 
[gpadmin@mdw ~]$ psql
Timing is on.
Null display is "(NULL)".
psql (9.4.24)
Type "help" for help.

postgres=# --SESSION1
postgres=# create table dba_test1(c1 int, c2 int) distributed by (c1);
CREATE TABLE
Time: 100.655 ms
postgres=# insert into dba_test1 values(1,2), (2,3);
INSERT 0 2
Time: 28.146 ms
postgres=# select * from dba_test1 ;
 c1 | c2 
----+----
  1 |  2
  2 |  3
(2 rows)

Time: 3.507 ms
postgres=# begin;
BEGIN
Time: 0.374 ms
postgres=# update dba_test1 set c2=6 where c1 = 1;
UPDATE 1
Time: 12.356 ms
postgres=# -- Waiting and step on to SESSION2
```

Open another new **SESSION2**
```
postgres=# --SESSION2
postgres=# update dba_test1 set c2=7 where c1=1;
(it will hang and wait for SESSION1)
```

Back to **SESSION1**
```
postgres=# --Back to SESSION1
postgres=# commit;
COMMIT
Time: 46.226 ms
postgres=# 
```

And **SESSION2** finishes immediately.
```
postgres=# update dba_test1 set c2=7 where c1=1;
UPDATE 1
Time: 4800.454 ms
postgres=# 
postgres=# select * from dba_test1 ;
 c1 | c2 
----+----
  2 |  3
  1 |  7
(2 rows)

postgres=# 
```

### Actual behavior
When `gp_enable_global_deadlock_detector` is `on`, performing the steps above will cause error on the **SESSION2** with error message `ERROR:  tuple to be updated was already moved to another segment due to concurrent update`, but we think that the update SQL in **SESSION1** does not move the tuple to another segment instance.
See below for test example.

### Step to reproduce the behavior

**SESSION1**
```
[gpadmin@mdw ~]$ gpconfig -s gp_enable_global_deadlock_detector
Values on all segments are consistent
GUC          : gp_enable_global_deadlock_detector
Master  value: on
Segment value: on

[gpadmin@mdw ~]$ psql
Timing is on.
Null display is "(NULL)".
psql (9.4.24)
Type "help" for help.

postgres=# select * from dba_test1;
 c1 | c2 
----+----
  1 |  2
  2 |  3
(2 rows)

Time: 22.142 ms
postgres=# 
postgres=# begin ;
BEGIN
Time: 0.309 ms
postgres=# update dba_test1 set c2=6 where c1 = 1;
UPDATE 1
Time: 7.915 ms
postgres=# -- Waiting and step on to SESSION2
```

Open another new **SESSION2**
```
[gpadmin@mdw ~]$ psql
Timing is on.
Null display is "(NULL)".
psql (9.4.24)
Type "help" for help.

postgres=# update dba_test1 set c2=7 where c1=1;
(it will hang and wait for SESSION1)
```

Back to **SESSION1**
```
postgres=# commit ;
COMMIT
Time: 30.901 ms
postgres=# 
```

Now **SESSION2** immediately failed, and retry in SESSION2 works.
```
postgres=# update dba_test1 set c2=7 where c1=1;
ERROR:  tuple to be updated was already moved to another segment due to concurrent update  (seg0 127.0.1.1:6000 pid=2117)
Time: 54127.785 ms
postgres=# -- Now SESSION2 can update now
postgres=# select * from dba_test1;
 c1 | c2 
----+----
  2 |  3
  1 |  6
(2 rows)

Time: 11.162 ms
postgres=# update dba_test1 set c2=7 where c1=1;
UPDATE 1
Time: 35.476 ms
postgres=# 
```

It seems that updating data on non-distribution columns causes another concurrent UPDATE on the same row failed rather than blocking it.

Is this a bug of  `gp_enable_global_deadlock_detector` to be fixed?

Best Regards.

**Comment by CC-Hsu** [comment] 2021-07-20 13:10
Besides, whenever the cluster configuration is multi-node or single-node, the same situation holds, even when the single node only contains 1 master+1primary instances.

**Comment by kainwen** [comment] 2021-07-20 13:13
Can you please paste the result of:

1. `show optimizer; `
2.  `explain update dba_test1 set c2=7 where c1=1;`

I believe you are using ORCA, and ORCA always implements update using Split-update.

Please try to `set optimizer = off` and the re-test.

**Comment by CC-Hsu** [comment] 2021-07-20 13:26
Hi, kainwen,

Please see below.
```
[gpadmin@gpdb ~]$ gpconfig -s gp_enable_global_deadlock_detector      
Values on all segments are consistent
GUC          : gp_enable_global_deadlock_detector
Master  value: on
Segment value: on
[gpadmin@gpdb ~]$ 
[gpadmin@gpdb ~]$ psql
psql (9.4.24)
Type "help" for help.

postgres=# show optimizer;
 optimizer 
-----------
 on
(1 row)

postgres=# 
postgres=# explain update dba_test1 set c2=7 where c1=1;
                                     QUERY PLAN                                     
------------------------------------------------------------------------------------
 Update  (cost=0.00..431.20 rows=1 width=1)
   ->  Result  (cost=0.00..431.00 rows=2 width=26)
         ->  Split  (cost=0.00..431.00 rows=2 width=22)
               ->  Result  (cost=0.00..431.00 rows=1 width=22)
                     ->  Seq Scan on dba_test1  (cost=0.00..431.00 rows=1 width=18)
                           Filter: (c1 = 1)
 Optimizer: Pivotal Optimizer (GPORCA)
(7 rows)

postgres=# 
```

Retest again with `optimizer = off` in both sessions (`gp_enable_global_deadlock_detector = on`, too), it does the trick.
**SESSION1**
```
postgres=# --SESSION1
postgres=# set optimizer = off;
SET
Time: 0.915 ms
postgres=# select * from dba_test1 ;
 c1 | c2 
----+----
  1 |  2
  2 |  3
(2 rows)

Time: 1.150 ms
postgres=# begin;
BEGIN
Time: 0.357 ms
postgres=# update dba_test1 set c2=6 where c1 = 1;
UPDATE 1
Time: 2.757 ms
postgres=# --Head to SESSION2
```

**SESSION2**
```
postgres=# --SESSION2
postgres=# set optimizer = off;
SET
Time: 7.653 ms
postgres=# update dba_test1 set c2=7 where c1=1;
(it hangs and waits for SESSION1)
```
Back to **SESSION1**
```
postgres=# --SESSION1
postgres=# commit ;
COMMIT
Time: 33.188 ms
postgres=# 
```
And **SESSION2** also finishes it job immediately.
```
postgres=# --SESSION2
postgres=# update dba_test1 set c2=7 where c1=1;
UPDATE 1
Time: 9323.356 ms
postgres=# 
postgres=# select * from dba_test1 ;
 c1 | c2 
----+----
  2 |  3
  1 |  7
(2 rows)

Time: 7.057 ms
postgres=# --Check EXPLAIN again
postgres=# explain update dba_test1 set c2=7 where c1=1;
                           QUERY PLAN                           
----------------------------------------------------------------
 Update on dba_test1  (cost=0.00..1.02 rows=1 width=14)
   ->  Seq Scan on dba_test1  (cost=0.00..1.02 rows=1 width=14)
         Filter: (c1 = 1)
 Optimizer: Postgres query optimizer
(4 rows)

Time: 1.086 ms
postgres=# 
```

**Comment by kainwen** [comment] 2021-07-20 13:33
So this is known and it is not a bug.

In the future ORCA may change the implementation. Close this issue.

**Closed by kainwen** 2021-07-20 13:33 UTC

**Comment by ducking-repo** [comment] 2022-08-26 02:05
I would like to ask, in addition to the above error when setting optimizer = ON and GP_ENABLE_GLOBAL_DEADLOCK_detector = ON, there are other situations where this error code may occur, because I have the same error here. But the configuration is the same as what you said above.

**Comment by kainwen** [comment] 2022-08-26 02:31
> I would like to ask, in addition to the above error when setting optimizer = ON and GP_ENABLE_GLOBAL_DEADLOCK_detector = ON, there are other situations where this error code may occur, because I have the same error here. But the configuration is the same as what you said above.

Would you please offer more details? 

Version, SQLs, logs...

**Comment by dragon-hl** [comment] 2022-08-26 03:07
Greenplum version or build
GPDB v6.16.3

Some logs are in pg_log
```2022-08-26 08:50:02.325866 CST,"gpadmin","byt",p121945,th-2094593920,"10.2.5.101","37806",2022-08-26 08:50:00 CST,0,con6341082,cmd6,seg-1,,dx90327468,,sx1,"ERROR","40001","tuple to be updated was already moved to another segment due to concurrent update  (seg0 10.2.5.126:6000 pid=82901)",,,,,,"UPDATE mes.dws_second_data_hourly
SET ""date"" = $1
,   line_id = $2
,   id = $3
,   raw_ts = $4
,   raw_cl = $5
,   raw_yzsj = $6
,   raw_jcyxsj = $7
,   raw_yzl = $8
,   raw_shsxhl = $9
,   raw_shsxpb = $10
,   raw_syxh = $11
,   raw_sypb = $12
,   raw_yyxh = $13
,   raw_yypb = $14
,   raw_tfxh = $15
,   raw_tfpb = $16
,   coal_ts = $17
,   coal_cl = $18
,   coal_tmxhl = $19
,   coal_wmxhl = $20
,   coal_mfrz = $21
,   coal_yzsj = $22
,   coal_jcyxsj = $23
,   coal_yzl = $24
,   fire_ts = $25
,   fire_cl = $26
,   fire_yzsj = $27
,   fire_jcyxsj = $28
,   fire_yzl = $29
,   fire_swmh = $30
,   fire_bzmh = $31
,   fire_tmwml = $32
,   fire_wmwml = $33
,   fire_yxtwll = $34
,   heat_yzsj = $35
,   heat_yzl = $36
,   heat_dslfdl = $37
,   heat_yrfdl = $38
,   heat_slcl = $39
,   heat_dslgdl = $40
,   heat_yrgdl = $41
,   heat_zydl = $42
,   mill_ts = $43
,   mill_cl = $44
,   mill_yzsj = $45
,   mill_jcyxsj = $46
,   mill_yzl = $47
,   mill_slpb = $48
,   mill_slxhl = $49
,   mill_sgpb = $50
,   mill_sgxhl = $51
,   mill_hhcpb = $52
,   mill_hhcxhl = $53
,   raw_fqyzl = $54
,   raw_pqyzl = $55
,   raw_gqyzl = $56
,   raw_fqyzsj = $57
,   raw_pqyzsj = $58
,   raw_gqyzsj = $59
,   raw_plan_fqyzsj = $60
,   raw_plan_pqyzsj = $61
,   raw_plan_gqyzsj = $62
,   raw_fault_fqyzsj = $63
,   raw_fault_pqyzsj = $64
,   raw_fault_gqyzsj = $65
,   coal_fqyzl = $66
,   coal_pqyzl = $67
,   coal_gqyzl = $68
,   mill_fqyzl = $69
,   mill_pqyzl = $70
,   mill_gqyzl = $71
,   raw_gxddh = $72
,   raw_ddlcb = $73
,   raw_zydl = $74
,   raw_zdf = $75
,   coal_gxddh = $76
,   coal_ddlcb = $77
,   coal_zydl = $78
,   coal_zdf = $79
,   fire_gxddhzh = $80
,   fire_ddlcbzh = $81
,   fire_zydlzh = $82
,   fire_zdfzh = $83
,   fire_gxddh = $84
,   fire_ddlcb = $85
,   fire_zydl = $86
,   fire_zdf = $87
,   mill_gxddhzh = $88
,   mill_ddlcbzh = $89
,   mill_zydlzh = $90
,   mill_zdf = $91
,   mill_snzdh = $92
,   crush_shsgxddhzh = $93
,   crush_shsddlcbzh = $94
,   crush_shszydlzh = $95
,   crush_shszdf = $96
,   crush_sygxddhzh = $97
,   crush_syddlcbzh = $98
,   crush_syzydlzh = $99
,   crush_syzdf = $100
,   raw_cxzydl = $101
,   raw_cxzydcb = $102
,   raw_fddcb = $103
,   raw_pddcb = $104
,   raw_gddcb = $105
,   raw_slmfqyd = $106
,   raw_slmpqyd = $107
,   raw_slmgqyd = $108
,   coal_fddcb = $109
,   coal_pddcb = $110
,   coal_gddcb = $111
,   coal_mmfqyd = $112
,   coal_mmpqyd = $113
,   coal_mmgqyd = $114
,   mill_fddcb = $115
,   mill_pddcb = $116
,   mill_gddcb = $117
,   mill_snmfqyd = $118
,   mill_snmpqyd = $119
,   mill_snmgqyd = $120
,   fire_slzxl = $121
,   mill_thrccl = $122
,   mill_fourccl = $123
WHERE  ( ( ""date"" = $124  ) ) AND    ( ( line_id = $125  ) ) ",0,,"nodeModifyTable.c",905,
```
