### ISSUE TITLE
selectforupdate against upgrate lock lead to deadlock

### ISSUE THREAD

**Issue by uglthinx** [greenplum-db/gpdb#10666] opened 2020-08-18 12:09 UTC
### Greenplum version or build
master, 6X_STABLE

### Step to reproduce the behavior
```
create table t1 (id1 int, id2 int) distributed by (id1);
```
session A:
```
begin;
LOCK TABLE t1 in EXCLUSIVE MODE ;
```
session B:
```SELECT * FROM t1 FOR UPDATE ;``` and it will be blocked for waiting lock.

session A:
```LOCK TABLE t1 in ACCESS EXCLUSIVE MODE;```
then lead to deadock:
```
ERROR:  deadlock detected
DETAIL:  Process 1312 waits for AccessExclusiveLock on relation 24597 of database 16384; blocked by process 127997.
Process 127997 waits for ExclusiveLock on relation 24597 of database 16384; blocked by process 1312.
HINT:  See server log for query details
```

In my opinion, session B never hold any locks on `t1`, session A lock table in a transaction, it should not lead to deadlock. Could you show me any explanation？

**Comment by kainwen** [comment] 2020-08-18 12:51
This is by design.

`Select for update` will always hold ExclusiveLock on the tables in gpdb6. See the doc: https://gpdb.docs.pivotal.io/6-10/admin_guide/dml.html  (search for update in that page)
 
In master branch, there are some optimizations on the lock level of `select for update`. 
There are some commits (not backport to 6):

* https://github.com/greenplum-db/gpdb/pull/7705 
* https://github.com/greenplum-db/gpdb/pull/7805 
* https://github.com/greenplum-db/gpdb/pull/7950

One of my blog summarizes locks in gpdb: https://kainwen.com/2020/01/27/distributed-lock-in-greenplum/

**Comment by kainwen** [comment] 2020-08-18 12:58
Close this, it is by design in MPP env.

Feel free to discuss more if your have further questions.

**Closed by kainwen** 2020-08-18 12:58 UTC
