### ISSUE TITLE
Help left join the query is very slow But join  it's very fast

### ISSUE THREAD

**Issue by 444728248** [greenplum-db/gpdb#5172] opened 2018-06-20 01:38 UTC
**EXPLAIN SELECT * FROM aaa aa LEFT JOIN wifiinfo3 bb ON aa.f_id = bb.mac;**

Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..862.00 rows=2 width=64)
  ->  Hash Left Join  (cost=0.00..862.00 rows=1 width=64)
        Hash Cond: aaa.f_id = wifiinfo3.mac
        ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
        ->  Hash  (cost=431.00..431.00 rows=1 width=36)
              ->  Table Scan on wifiinfo3  (cost=0.00..431.00 rows=1 width=36)
Settings:  effective_cache_size=64000MB; enable_hashjoin=off; enable_indexscan=on; enable_nestloop=on; enable_seqscan=off; optimizer=on
Optimizer status: PQO version 2.53.8

**EXPLAIN SELECT * FROM aaa aa JOIN wifiinfo3 bb ON aa.f_id = bb.mac;**

Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.50 rows=1 width=64)
  ->  Nested Loop  (cost=0.00..431.50 rows=1 width=64)
        Join Filter: true
        ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
        ->  Index Scan using wifiinfo3_pkey on wifiinfo3  (cost=0.00..0.50 rows=1 width=36)
              Index Cond: wifiinfo3.mac = aaa.f_id
Settings:  effective_cache_size=64000MB; enable_hashjoin=off; enable_indexscan=on; enable_nestloop=on; enable_seqscan=off; optimizer=on
Optimizer status: PQO version 2.53.8

**Comment by d** [comment] 2018-06-20 04:29
Can you post the result of `EXPLAIN ANALYZE` of both queries?

I will not be shocked if you never ran `ANALYZE` on your tables ...

**Comment by 444728248** [comment] 2018-06-20 06:06
That is, the first SQL query did not index, and hash left join was used, second SQL queries have gone indexed, and Nested Loop has been used.



The first SQL is about 50 seconds, while the second sqk is 0.002ms.

**Comment by 444728248** [comment] 2018-06-20 06:16
**EXPLAIN ANALYZE SELECT * FROM aaa aa LEFT JOIN wifiinfo3 bb ON aa.f_id = bb.mac;**

Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..862.00 rows=2 width=64)
  Rows out:  1 rows at destination with 82851 ms to first row, 86818 ms to end, start offset by 0.589 ms.
  ->  Hash Left Join  (cost=0.00..862.00 rows=1 width=64)
        Hash Cond: aaa.f_id = wifiinfo3.mac
        Rows out:  1 rows (seg4) with 64428 ms to first row, 82849 ms to end, start offset by 2.121 ms.
        Executor memory:  127701K bytes avg, 127701K bytes max (seg0).
        Work_mem used:  127701K bytes avg, 127701K bytes max (seg0). Workfile: (12 spilling)
        Work_mem wanted: 3323773K bytes avg, 3324147K bytes max (seg4) to lessen workfile I/O affecting 12 workers.
        (seg4)   Initial batch 0:
        (seg4)     Wrote 2616800K bytes to inner workfile.
        (seg4)   Overflow batches 1..31:
        (seg4)     Read 3621755K bytes from inner workfile: 116831K avg x 31 nonempty batches, 291936K max.
        (seg4)     Wrote 1005536K bytes to inner workfile: 67036K avg x 15 overflowing batches, 207584K max.
        (seg4)     Read 1K bytes from outer workfile.
        (seg4)   Hash chain length 6.4 avg, 24 max, using 8371376 of 8388608 buckets.
        ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
              Rows out:  1 rows (seg4) with 0.098 ms to first row, 0.099 ms to end, start offset by 58995 ms.
        ->  Hash  (cost=431.00..431.00 rows=1 width=36)
              Rows in:  Avg 1662155.7 rows x 12 workers.  Max 1664096 rows (seg5) with 59118 ms to end, start offset by 5.282 ms.
              ->  Table Scan on wifiinfo3  (cost=0.00..431.00 rows=1 width=36)
                    Rows out:  Avg 53180356.8 rows x 12 workers.  Max 53186352 rows (seg4) with 0.168 ms to first row, 30918 ms to end, start offset by 5.329 ms.
Slice statistics:
  (slice0)    Executor memory: 386K bytes.
  (slice1)  * Executor memory: 168707K bytes avg x 12 workers, 168722K bytes max (seg4).  Work_mem: 127701K bytes max, 3324147K bytes wanted.
Statement statistics:
  Memory used: 128000K bytes
  Memory wanted: 3324547K bytes
Settings:  effective_cache_size=64000MB; enable_hashjoin=off; enable_indexscan=on; enable_nestloop=on; enable_seqscan=off; optimizer=on
Optimizer status: PQO version 2.53.8
Total runtime: 86819.131 ms

**EXPLAIN ANALYZE SELECT * FROM aaa aa JOIN wifiinfo3 bb ON aa.f_id = bb.mac;**

Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.50 rows=1 width=64)
  Rows out:  1 rows at destination with 2.124 ms to first row, 3.864 ms to end, start offset by 0.531 ms.
  ->  Nested Loop  (cost=0.00..431.50 rows=1 width=64)
        Join Filter: true
        Rows out:  1 rows (seg4) with 0.137 ms to first row, 0.149 ms to end, start offset by 2.380 ms.
        ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
              Rows out:  1 rows (seg4) with 0.055 ms to first row, 0.057 ms to end, start offset by 2.386 ms.
        ->  Index Scan using wifiinfo3_pkey on wifiinfo3  (cost=0.00..0.50 rows=1 width=36)
              Index Cond: wifiinfo3.mac = aaa.f_id
              Rows out:  1 rows (seg4) with 0.050 ms to first row, 0.052 ms to end, start offset by 2.465 ms.
Slice statistics:
  (slice0)    Executor memory: 386K bytes.
  (slice1)    Executor memory: 182K bytes avg x 12 workers, 193K bytes max (seg4).
Statement statistics:
  Memory used: 128000K bytes
Settings:  effective_cache_size=64000MB; enable_hashjoin=off; enable_indexscan=on; enable_nestloop=on; enable_seqscan=off; optimizer=on
Optimizer status: PQO version 2.53.8
Total runtime: 5.711 ms

**Comment by 444728248** [comment] 2018-06-20 06:18
We have tens of billions of data per month, and we need left join operation between two tables.

**Comment by d** [comment] 2018-06-20 06:33
Obviously you forgot to run `ANALYZE wifiinfo3;`. Try that maybe? It works like a charm for me 99 out of 100 times.

Jesse

**Comment by 444728248** [comment] 2018-06-20 06:36
Don't understand what you mean? Can you print a sentence

**Comment by d** [comment] 2018-06-20 06:53
`ANALYZE wifiinfo3;`

**Comment by 444728248** [comment] 2018-06-20 08:35
**ANALYZE wifiinfo3;**

[SQL] ANALYZE wifiinfo3
times:28.185s
Affected lines ： 0

**Comment by d** [comment] 2018-06-20 14:12
After analyzing the table, can you post the result of `explain analyze` of both queries?

**Comment by hsyuan** [comment] 2018-06-21 05:10
You are using Orca query optimizer. Setting `effective_cache_size=64000MB; enable_hashjoin=off; enable_indexscan=on; enable_nestloop=on; enable_seqscan=off;` doesn't work for Orca, it only works for legacy planner. You should use `optimizer_enable_hashjoin=off` to turn off hashjoin for Orca.

But can you post the table and index DDL for the 2 tables?

**Comment by 444728248** [comment] 2018-06-22 02:45
**EXPLAIN ANALYZE SELECT * FROM wifiinfo aa  JOIN wifiinfo3 bb ON aa.mac = bb.mac LIMIT 1**

Limit  (cost=0.00..431.50 rows=1 width=92)
  Rows out:  1 rows with 3.247 ms to first row, 3.270 ms to end, start offset by 0.590 ms.
  ->  Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.50 rows=1 width=92)
        Rows out:  1 rows at destination with 3.235 ms to end, start offset by 0.602 ms.
        ->  Nested Loop  (cost=0.00..431.50 rows=1 width=92)
              Join Filter: true
              Rows out:  Avg 209.0 rows x 12 workers.  Max 289 rows (seg3) with 0.171 ms to first row, 0.987 ms to end, start offset by 1.830 ms.
              ->  Table Scan on wifiinfo  (cost=0.00..431.00 rows=1 width=56)
                    Rows out:  Avg 209.0 rows x 12 workers.  Max 289 rows (seg3) with 0.106 ms to first row, 0.168 ms to end, start offset by 1.839 ms.
              ->  Index Scan using wifiinfo3_pkey on wifiinfo3  (cost=0.00..0.50 rows=1 width=36)
                    Index Cond: wifiinfo3.mac = wifiinfo.mac
                    Rows out:  Avg 209.0 rows x 12 workers.  Max 289 rows (seg3) with 0.033 ms to first row, 0.650 ms to end of 289 scans, start offset by 4.228 ms.
Slice statistics:
  (slice0)    Executor memory: 386K bytes.
  (slice1)    Executor memory: 217K bytes avg x 12 workers, 217K bytes max (seg0).
Statement statistics:
  Memory used: 128000K bytes
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8
Total runtime: 15.614 ms

**EXPLAIN ANALYZE SELECT * FROM wifiinfo aa  LEFT JOIN wifiinfo3 bb ON aa.mac = bb.mac LIMIT 1**

Limit  (cost=0.00..102400000086410752.00 rows=1 width=92)
  ->  Gather Motion 12:1  (slice2; segments: 12)  (cost=0.00..102400000086410752.00 rows=2 width=92)
        ->  Nested Loop Left Join  (cost=0.00..102400000086410752.00 rows=1 width=92)
              Join Filter: wifiinfo.mac = wifiinfo3.mac
              ->  Table Scan on wifiinfo  (cost=0.00..431.00 rows=1 width=56)
              ->  Materialize  (cost=0.00..100000000028896.42 rows=638166784 width=36)
                    ->  Broadcast Motion 12:12  (slice1; segments: 12)  (cost=0.00..100000000005922.42 rows=638166784 width=36)
                          ->  Table Scan on wifiinfo3  (cost=0.00..2361.45 rows=53180566 width=36)
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8



**select  gp_segment_id,count(*) as num  from wifiinfo3    group by gp_segment_id**
gp_segment_id num
8	53180572
1	53176065
6	53176653
4	53186352
9	53178847
2	53179469
3	53184442
7	53179794
5	53185989
0	53177061
10	53174027
11	53185010

- Now I set up this parameter you said, join execution is faster, or that problem left join is very slow, I look at the data distribution is more uniform, now know where the problem is, you can help to see the gods?

**Comment by d** [comment] 2018-06-22 17:23
You didn't run `EXPLAIN ANALYZE` on your `LEFT JOIN` query, can you do that again?

Also, I have a little eyesore having to stare at un-formatted output. Maybe a [little bit of markdown](https://guides.github.com/features/mastering-markdown/) would be really helpful for other members of the community to help you here.

**Comment by 444728248** [comment] 2018-06-25 08:14
**EXPLAIN ANALYZE SELECT * FROM  wifiinfo3 bb**  
Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..65233.65 rows=638166784 width=36)
  Rows out:  638164281 rows at destination with 3.061 ms to first row, 257551 ms to end, start offset by 0.492 ms.
  ->  Table Scan on wifiinfo3  (cost=0.00..2361.45 rows=53180566 width=36)
        Rows out:  Avg 53180356.8 rows x 12 workers.  Max 53186352 rows (seg4) with 0.098 ms to first row, 13416 ms to end, start offset by 1.495 ms.
Slice statistics:
  (slice0)    Executor memory: 322K bytes.
  (slice1)    Executor memory: 162K bytes avg x 12 workers, 179K bytes max (seg4).
Statement statistics:
  Memory used: 128000K bytes
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8
Total runtime: 300824.082 ms

**EXPLAIN ANALYZE SELECT * FROM aaa aa** 
Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.00 rows=1 width=28)
  Rows out:  1 rows at destination with 53 ms to end, start offset by 0.513 ms.
  ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
        Rows out:  1 rows (seg4) with 13 ms to end, start offset by 38 ms.
Slice statistics:
  (slice0)    Executor memory: 322K bytes.
  (slice1)    Executor memory: 155K bytes avg x 12 workers, 155K bytes max (seg0).
Statement statistics:
  Memory used: 128000K bytes
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8
Total runtime: 56.018 ms

**EXPLAIN ANALYZE SELECT * FROM aaa aa JOIN wifiinfo3 bb ON aa.f_id = bb.mac LIMIT 1**

Limit  (cost=0.00..431.50 rows=1 width=64)
  Rows out:  1 rows with 0.984 ms to first row, 0.985 ms to end, start offset by 0.516 ms.
  ->  Gather Motion 12:1  (slice1; segments: 12)  (cost=0.00..431.50 rows=1 width=64)
        Rows out:  1 rows at destination with 0.972 ms to end, start offset by 0.527 ms.
        ->  Nested Loop  (cost=0.00..431.50 rows=1 width=64)
              Join Filter: true
              Rows out:  1 rows (seg4) with 0.355 ms to first row, 0.364 ms to end, start offset by 1.043 ms.
              ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
                    Rows out:  1 rows (seg4) with 0.128 ms to first row, 0.131 ms to end, start offset by 1.049 ms.
              ->  Index Scan using wifiinfo3_pkey on wifiinfo3  (cost=0.00..0.50 rows=1 width=36)
                    Index Cond: wifiinfo3.mac = aaa.f_id
                    Rows out:  1 rows (seg4) with 0.201 ms to first row, 0.204 ms to end, start offset by 1.195 ms.
Slice statistics:
  (slice0)    Executor memory: 386K bytes.
  (slice1)    Executor memory: 169K bytes avg x 12 workers, 193K bytes max (seg4).
Statement statistics:
  Memory used: 128000K bytes
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8
Total runtime: 1.742 ms

**EXPLAIN ANALYZE SELECT * FROM aaa aa LEFT JOIN wifiinfo3 bb ON aa.f_id = bb.mac LIMIT 1**
Limit  (cost=0.00..102400000086410752.00 rows=1 width=64)
  Rows out:  1 rows with 947853 ms to end, start offset by 13 ms.
  ->  Gather Motion 12:1  (slice2; segments: 12)  (cost=0.00..102400000086410752.00 rows=2 width=64)
        Rows out:  1 rows at destination with 947853 ms to end, start offset by 13 ms.
        ->  Nested Loop Left Join  (cost=0.00..102400000086410752.00 rows=1 width=64)
              Join Filter: aaa.f_id = wifiinfo3.mac
              Rows out:  1 rows (seg4) with 797049 ms to first row, 947850 ms to end, start offset by 16 ms.
              ->  Table Scan on aaa  (cost=0.00..431.00 rows=1 width=28)
                    Rows out:  1 rows (seg4) with 70 ms to end, start offset by 795741 ms.
              ->  Materialize  (cost=0.00..100000000028896.42 rows=638166784 width=36)
                    Rows out:  Avg 53180357.8 rows x 12 workers.  Max 638164282 rows (seg4) with 795725 ms to first row, 871834 ms to end of 2 scans, start offset by 795811 ms.
                    Work_mem used:  127584K bytes avg, 127584K bytes max (seg0). Workfile: (12 spilling)
                    Work_mem wanted: 32466211K bytes avg, 32466240K bytes max (seg4) to lessen workfile I/O affecting 12 workers.
                    ->  Broadcast Motion 12:12  (slice1; segments: 12)  (cost=0.00..100000000005922.42 rows=638166784 width=36)
                          Rows out:  Avg 638164281.0 rows x 12 workers at destination.  Max 638164281 rows (seg0) with 0.144 ms to first row, 590632 ms to end, start offset by 17 ms.
                          ->  Table Scan on wifiinfo3  (cost=0.00..2361.45 rows=53180566 width=36)
                                Rows out:  Avg 53180356.8 rows x 12 workers.  Max 53186352 rows (seg4) with 0.472 ms to first row, 15394 ms to end, start offset by 15 ms.
Slice statistics:
  (slice0)    Executor memory: 386K bytes.
  (slice1)    Executor memory: 368K bytes avg x 12 workers, 442K bytes max (seg11).
  (slice2)  * Executor memory: 127963K bytes avg x 12 workers, 127963K bytes max (seg0).  Work_mem: 127584K bytes max, 32466240K bytes wanted.
Statement statistics:
  Memory used: 128000K bytes
  Memory wanted: 32466840K bytes
Settings:  effective_cache_size=64000MB; enable_indexscan=on; enable_seqscan=off
Optimizer status: PQO version 2.53.8
Total runtime: 947866.820 ms

that's ok?

**Comment by d** [comment] 2018-06-25 14:04
although it would've been better if you formatted your comment (surround the long output from psql with triple back tick ```), this is already better than not posting it. we'll take a look at it

**Comment by d** [comment] 2018-06-25 14:05
Can you run minirepro to capture the statistics and attach it here? That way the engineers working on the optimizer can precisely reproduce the query plans

**Comment by vraghavan78** [comment] 2018-06-25 18:11
@444728248 questions:

As @d said, if you can provide us the minirepro we will be happy to RCA the underlying issue. 
https://community.pivotal.io/s/article/How-to-Collect-DDL-and-Statistics-Information-Using-the-Minirepro-Utility

**Comment by vraghavan78** [comment] 2019-04-29 20:56
closing issue due to no update (minirepro)

**Closed** 2019-04-29 20:56 UTC
Labels: area: gporca
