### ISSUE TITLE
Query plan size includes size of the UDA input argument 

### ISSUE THREAD

**Issue by khannaekta** [greenplum-db/gpdb#9434] opened 2020-01-16 00:34 UTC
### Greenplum version or build
Greenplum Database 7.0.0-alpha.0+dev.5440.g1223ffa
Greenplum Database 6.2.1 build dev

### OS version and uname -a
Mac OS, centos6

### Step to reproduce the behavior
SETUP
```
drop table if exists foo;
create table foo(x bytea);

CREATE language plpythonu;

create or replace function repro_trans(bytea, bytea, bytea) returns bytea as
$$
return None
$$
language plpythonu;

drop aggregate repro_uda(bytea, bytea);
create aggregate repro_uda(bytea, bytea)(STYPE=BYTEA, SFUNC=repro_trans);

drop function call_uda(text, text);
create or replace function call_uda(table_name text) returns void as
$$
import plpy
query = plpy.prepare("select repro_uda($1,x) from {0}".format(table_name),["bytea"])
plpy.execute(query,["a"*100000]) ## 100 KB
$$ language plpythonu;
```

Repro query and error
```
set gp_max_plan_size=1; select call_uda('foo');

ERROR:  spiexceptions.StatementTooComplex: Query plan size limit exceeded, current size: 98KB, max allowed size: 1KB
HINT:  Size controlled by gp_max_plan_size
CONTEXT:  Traceback (most recent call last):
  PL/Python function "call_uda", line 4, in <module>
    plpy.execute(query,["a"*100000])
PL/Python function "call_uda"
```
This works fine on GPDB5. Seems like for GPDB6 and master, the query plan size also includes the size of the input argument to the UDA (100 KB in the above example) 
It Fails with both ORCA and planner.

**Comment by d** [comment] 2020-01-16 01:31
Yup, that's expected: in Postgres 9.0 (or maybe 8.4), planner is able to fold more "constants", parameters being one of them. This results in better plans in most cases, but results in bigger plans in others. You just found one.

**Comment by d** [comment] 2020-01-16 01:32
I recall creating a WONTFIX label a while back, or am I dreaming?

**Comment by hlinnaka** [comment] 2020-01-20 09:20
Closing, not a bug.

**Closed by hlinnaka** 2020-01-20 09:20 UTC
