### ISSUE TITLE
FailedAssertion("!(!((_Bool) ((def->collOid) != ((Oid) 0))))", File: "view.c", Line: 118)

### ISSUE THREAD

**Issue by interma** [greenplum-db/gpdb#15032] opened 2023-02-23 03:03 UTC
## Bug Report
This issue was found by sqlancer.

### Greenplum version or build
main branch

### Expected behavior
No Fatal

### Actual behavior
```
// the last command fire this FATAL:
psql:bug22.sql:19: FATAL:  Unexpected internal error (assert.c:48)
DETAIL:  FailedAssertion("!(!((_Bool) ((def->collOid) != ((Oid) 0))))", File: "view.c", Line: 118)
```

### Step to reproduce the behavior
```
\c test;
DROP DATABASE IF EXISTS sqlancer;
CREATE DATABASE sqlancer ;
\c sqlancer;
CREATE UNLOGGED TABLE t0(c0 int4range  CHECK (((t0.c0)<@(t0.c0))), c1 boolean ) PARTITION BY LIST((((((((((B'1111111111111111111111111111111110000010111010001010001101110001')#(B'1111111111111111111111111111111111101011110011110111110001001101')))&(((B'101101001001011000101010000111')&(B'101100100111111111101101101110')))))<<(((((B'1111111111111111111111111111111110000000110111011011101000111011')#(B'1111111111111111111111111111111110001101001111100000010111011111')))&(((B'1111111111111111111111111111111111011001110011101010101100011110')||(B'1111111111111111111111111111111111011111000111010000100111011010')))))))>>(((((((B'1111111111111111111111111111111110000100000010000100011100010001')&(B'1111111111111111111111111111111111110100011110111100111000101000')))|(((B'110110101111111010011110011110')||(B'111100100100100001000100001011')))))#(B'110010010100110101010100100100'))))));
CREATE TEMP TABLE IF NOT EXISTS t0(c0 smallint  GENERATED ALWAYS AS IDENTITY, c1 smallint ) PARTITION BY HASH(((CAST(0.5026955 AS MONEY))::VARCHAR), (((B'1001001010010101011100001010011')&(((((((B'101100010000011110011011011111')||(B'1111111111111111111111111111111111000100110011011010000101111111')))&(((B'1000111111011010101110100101110')<<(B'1111111111111111111111111111111110111101100011101101110101001010')))))&(((((B'1010010101000100011111000101111')<<(B'10001001100101111110110110')))||(((B'1111111111111111111111111111111111100101010100110100000010001110')<<(B'1111111111111111111111111111111110111011100100111010100001011110')))))))))cdbhash_int2_ops);
CREATE TABLE IF NOT EXISTS t0(c0 money  DEFAULT ((0.3747286)::MONEY));
CREATE UNLOGGED TABLE IF NOT EXISTS t1(c0 money  NULL DEFAULT (CAST(0.18341412 AS MONEY)));
CREATE TEMPORARY TABLE IF NOT EXISTS t2(c0 DECIMAL ) INHERITS(t0) USING ao_column WITH (autovacuum_enabled=1, autovacuum_analyze_scale_factor=0.2, autovacuum_vacuum_threshold=1698808406, autovacuum_freeze_table_age=131234165, autovacuum_vacuum_scale_factor=0.01, autovacuum_freeze_min_age=29306613, fillfactor=10, autovacuum_freeze_max_age=1569716171);
CREATE TEMPORARY TABLE IF NOT EXISTS t2(c0 VARCHAR(140) COLLATE "C"  NULL) PARTITION BY HASH((0.37245372), (0.06808391410653091835314398849732242524623870849609375)) WITH (autovacuum_freeze_min_age=862419471, parallel_workers=917, autovacuum_vacuum_threshold=210373259, autovacuum_vacuum_scale_factor=0, autovacuum_vacuum_cost_limit=997, autovacuum_freeze_max_age=481886500) ON COMMIT DROP ;
CREATE UNLOGGED TABLE t2(c0 REAL  CHECK (CAST(0.41643885830907378942100649510393850505352020263671875 AS BOOLEAN))) WITH (fillfactor=97, autovacuum_freeze_max_age=1504889584, autovacuum_freeze_table_age=1057700686, autovacuum_vacuum_cost_limit=4638, autovacuum_vacuum_cost_delay=33, autovacuum_analyze_threshold=471966933, autovacuum_vacuum_threshold=1622549039, autovacuum_enabled=1, autovacuum_vacuum_scale_factor=0.8, autovacuum_analyze_scale_factor=0.9, parallel_workers=132);
CREATE TEMPORARY TABLE IF NOT EXISTS t2(c0 FLOAT  NULL DEFAULT (0.799914516371798)) PARTITION BY HASH((((((length('D'))-(450893503)))>((0.555388582820331322409401764161884784698486328125)::INT)))cdbhash_oid_ops, (0.9071015606090425)) ON COMMIT DROP ;
CREATE TEMP TABLE IF NOT EXISTS t2(c0 FLOAT , c1 smallint );
CREATE TEMP TABLE IF NOT EXISTS t3(c0 boolean  DEFAULT (CAST(FALSE AS BOOLEAN)), c1 BIT VARYING(366) ) WITH (parallel_workers=311, autovacuum_freeze_min_age=528762454, autovacuum_vacuum_threshold=820913551);
CREATE TABLE t4(LIKE t3 EXCLUDING INDEXES EXCLUDING DEFAULTS);
CREATE TABLE IF NOT EXISTS t5(c0 int4range , c1 money ) INHERITS(t4, t2, t1) PARTITION BY HASH((t5.c1), (t5.c0), (t5.c1));
CREATE UNLOGGED TABLE t5(c0 int4range , c1 inet ) PARTITION BY LIST((t5.c0)complex_ops);
CREATE TABLE t5(c0 REAL ) USING heap;
-- PANIC here
CREATE OR REPLACE TEMPORARY RECURSIVE VIEW v0(c0, c1) AS (SELECT DISTINCT ON (t1.c0) CAST((((('0.05006835273966759' COLLATE "C"))||(0.4901836276924920188236001195036806166172027587890625)) COLLATE "C") AS INT), t4.c1 FROM ONLY t1, ONLY t0, t5*, t4);

```

**Comment by higuoxing** [comment] 2023-03-05 10:20
I cannot reproduce the PANIC as of commit 132ca083a295b7a2e2797ee8c5b8b7949c661b4f. Need more time to investigate.

**Comment by interma** [comment] 2023-03-05 11:40
Thanks Xing, my env is a bit old (don't know how to confirm its top commit):
```
demo=# select version();
                                                                                                                          version
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.16123.ge7ea88e6ada build dev) on arm-apple-darwin22.1.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit compiled on Jan  9 2023 18:14:36 (with assert checking) Bhuvnesh C.
(1 row)
```
I am going to use the latest main code and verify all of them again.

**Comment by higuoxing** [comment] 2023-03-06 01:23
> ```
> demo=# select version();
>                                                                                                                           version
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>  PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.16123.ge7ea88e6ada build dev) on arm-apple-darwin22.1.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit compiled on Jan  9 2023 18:14:36 (with assert checking) Bhuvnesh C.
> (1 row)
> ```
> 
> I am going to use the latest main code and verify all of them again.

It looks that the top commit of your branch is e7ea88e6ada4dc3fa281bb37b8eee4094d5e7386.

I executed the given sql script against this commit and got the following error message.

```
postgres=# CREATE OR REPLACE TEMPORARY RECURSIVE VIEW v0(c0, c1) AS (SELECT DISTINCT ON (t1.c0) CAST((((('0.05006835273966759' COLLATE "C"))||(0.4901836276924920188236001195036806166172027587890625)) COLLATE "C") AS INT), t4.c1 FROM ONLY t1, ONLY t0, t5*, t4);
ERROR:  collations are not supported by type integer
```

It might be fixed by some commit, I'm going to try to find it out.

**Comment by interma** [comment] 2023-03-06 01:36
Have verified in the latest main branch (https://github.com/greenplum-db/gpdb/commit/132ca083a295b7a2e2797ee8c5b8b7949c661b4f), confirmed it disappears.

No hurry to find which commit fixes it, lowered the priority of this Issue.

**Comment by ashwinstar** [comment] 2023-05-10 00:07
I am closing this issue as its fixed based on comments. Only archaeology remains to trace for knowledge which actual commit fixed it.

**Closed by ashwinstar** 2023-05-10 00:07 UTC
Labels: type: bug, version: 7X_ALPHA, sqlancer detected
