### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by z17033** [greenplum-db/gpdb#9342] opened 2020-01-02 10:32 UTC
### Greenplum version or build
 ```
PostgreSQL 8.3.23 (Greenplum Database 5.0.0 build dev) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28) compiled on Aug 22 2018 06:22:06
```
### OS version and uname -a
`Linux node4.hde.h3c.com 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

### Actual behavior
This situation occured many times, the content of table `gp_configuration_history` as below:
```
=# select * from gp_configuration_history order by time desc  limit 10;
             time              | dbid |                                             desc                                              
-------------------------------+------+-----------------------------------------------------------------------------------------------
 2020-01-02 11:15:39.309074+08 |    9 | FTS: content 3 fault marking status DOWN role m
 2020-01-02 11:15:39.308967+08 |    5 | FTS: content 3 fault marking status UP mode: change-tracking role p
 2020-01-02 11:02:54.411528+08 |    6 | FTS: content 0 fault marking status DOWN role m
 2020-01-02 11:02:54.411429+08 |    2 | FTS: content 0 fault marking status UP mode: change-tracking role p
 2020-01-01 14:05:26.456798+08 |    7 | FTS: content 1 fault marking status DOWN role m
 2020-01-01 14:05:26.456695+08 |    3 | FTS: content 1 fault marking status UP mode: change-tracking role p
```
2020-01-02 11:15:38 log is below
**--master log**
```
2020-01-02 11:15:38.971453 CST,"gpadmin","postgres",p8734,th460892224,"[local]",,2020-01-02 11:15:38 CST,0,con7940783,cmd1,seg-1,,dx22064167,,sx1,"LOG","00000","statement: select count(1) from pg_stat_activity;",,,,,,"select count(1) from pg_stat_activity;",0,,"postgres.c",1624,
2020-01-02 11:15:39.166523 CST,"hbsiadmin","hbsidb",p4879,th460892224,"172.16.1.1","64937",2020-01-02 10:52:12 CST,0,con7919197,cmd30,seg-1,,dx22064124,,sx1,"LOG","00000","Process interrupt for 'query cancel pending' (ic_udpifc.c:3700)",,,,,,"                select kch,kcmc,xn,xq,zgh,xm,ssyxdm,ssyxmc,zcxx,kcdl,avg(fs_xspj1) fs_xspj1,avg(fs_ldpj1) fs_ldpj1,avg(fs_thpj1) fs_thpj1 from^M
                (SELECT kch,kcmc,xn,xq,zgh,xm,ssyxdm,ssyxmc,zcxx,b.kcdl kcdl,CASE WHEN ssfl='?-|?<94><9f>иибе<84>??бд' THEN avg(wjdf) END AS fs_xspj1,^M
                CASE WHEN ssfl='ижбщ<86>?бе?иибе<84>??бд' THEN avg(wjdf) END AS fs_ldpj1,^M
                CASE WHEN ssfl='?<90><8c>ии?<8c>иибе<84>??бд' THEN avg(wjdf) END AS fs_thpj1 from ^M
                 (SELECT kch,kcmc,kclx,xn,xq,a.pjdx_yhm zgh,a.pjdx_xm xm,a.dwdm ssyxdm,a.dwmc ssyxmc,ssfl,wjdf,^M
                 CASE WHEN b.zcxx IS NULL THEN '?<85>???<83>'^M
                ELSE b.zcxx END AS zcxx FROM (select * from edu_app_wjdc_fsgx ^M
                WHERE sfjf='?<98>бе' and wjdf is not NULL and ssfl!='иж<9a><8f>??<82>иибе<84>??бд' and kch is not null  and cjr_yhm = '123521060319' AND pjdx_yhm='123522180345' AND xn = '2019-2020' ) a INNER join ^M
                (select zgh,zcxx from edu_app_jzg_jbxx where 1=1  ) b ^M
                on a.pjdx_yhm = b.zgh) wa LEFT JOIN (select ca.kcdl kcdl,cb.kclx kclx from edu_app_kcdl ca ^M
                left join edu_app_map_kclx cb on ca.id = cb.sskcdl^M
                ) b on wa.kclx=b.kclx group by kch,kcmc,xn,xq,zgh,xm,ssyxdm,ssyxmc,zcxx,b.kcdl,ssfl) kab^M
          group by kch,kcmc,xn,xq,zgh,xm,ssyxdm,ssyxmc,zcxx,kcdl^M
",0,,"postgres.c",3718,
2020-01-02 11:15:39.308853 CST,,,p2199,th35915520,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: segment (dbid=5, content=3) reported fault FaultMirror segmentstatus 11 to the prober.",,,,,,,0,,,,
2020-01-02 11:15:39.308915 CST,,,p2199,th460892224,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: primary (dbid=5) reported mirroring fault with mirror (dbid=9), mirror considered to be down.",,,,,,,0,,"ftsfilerep.c",371,
2020-01-02 11:15:39.308941 CST,,,p2199,th460892224,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: change state for segment (dbid=5, content=3) from ('u','p') to ('u','p')",,,,,,,0,,"fts.c",984,
2020-01-02 11:15:39.308959 CST,,,p2199,th460892224,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: change state for segment (dbid=9, content=3) from ('u','m') to ('d','m')",,,,,,,0,,"fts.c",984,
2020-01-02 11:15:39.308978 CST,,,p2199,th460892224,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","probeUpdateConfig called for 2 changes",,,,,,,0,,"fts.c",840,
2020-01-02 11:15:39.310980 CST,,,p2199,th460892224,,,,0,con2,,seg-1,,,,,"LOG","00000","FTS: primary (dbid=5) on node7.hde.h3c.com:40002 transitioning to change-tracking mode, mirror marked as down.",,,,,,,0,,"ftsfilerep.c",509,
```

**--primary log**
```
2020-01-02 08:52:58.043390 CST,,,p36369,th-2128480192,"192.168.28.21","13996",2020-01-02 08:52:57 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 10:12:48.072120 CST,,,p12013,th-2128480192,"192.168.28.21","26187",2020-01-02 10:12:48 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 11:02:54.465648 CST,,,p33201,th-2128480192,"192.168.28.21","23483",2020-01-02 11:02:53 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 11:14:59.545075 CST,,,p30974,th-2128480192,,,,0,,,seg-1,,,,,"WARNING","08006","mirror failure, could not sent message to mirror msg header count '1911341' local count '1911341' : Connection reset by peer, failover requested","identifier 'base/17431/100895' operation 'flush (fsync)' relation type 'buffer pool' message count '1911341'","run gprecoverseg to re-establish mirror connectivity",,,"mirroring role 'primary role' mirroring state 'sync' segment state 'up and running' process name(pid) 'primary sender process(30974)' filerep state 'up and running'
position begin '0x7f6171f52040' position end '0x7f6172752100' position insert '0x7f61724a1278' position consume '0x7f61724a0230' position wraparound '0x7f6172752100' insert count '1911341' consume count '1911341' ",,0,,"cdbfilerepprimary.c",1771,
2020-01-02 11:14:59.545186 CST,,,p30974,th-2128480192,,,,0,,,seg-1,,,,,"LOG","00000","'set segment state', mirroring role 'primary role' mirroring state 'sync' segment state 'up and running' filerep state 'up and running' process name(pid) 'primary sender process(30974)' 'cdbfilerep.c' 'L2440' 'FileRep_SetSegmentState'",,,,,,,0,,"cdbfilerep.c",1822,
```

**--mirror log**
```
2020-01-02 08:52:58.043390 CST,,,p36369,th-2128480192,"192.168.28.21","13996",2020-01-02 08:52:57 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 10:12:48.072120 CST,,,p12013,th-2128480192,"192.168.28.21","26187",2020-01-02 10:12:48 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 11:02:54.465648 CST,,,p33201,th-2128480192,"192.168.28.21","23483",2020-01-02 11:02:53 CST,0,,,seg-1,,,,,"LOG","08P01","incomplete startup packet",,,,,,,0,,"postmaster.c",2638,
2020-01-02 11:14:59.545075 CST,,,p30974,th-2128480192,,,,0,,,seg-1,,,,,"WARNING","08006","mirror failure, could not sent message to mirror msg header count '1911341' local count '1911341' : Connection reset by peer, failover requested","identifier 'base/17431/100895' operation 'flush (fsync)' relation type 'buffer pool' message count '1911341'","run gprecoverseg to re-establish mirror connectivity",,,"mirroring role 'primary role' mirroring state 'sync' segment state 'up and running' process name(pid) 'primary sender process(30974)' filerep state 'up and running'
position begin '0x7f6171f52040' position end '0x7f6172752100' position insert '0x7f61724a1278' position consume '0x7f61724a0230' position wraparound '0x7f6172752100' insert count '1911341' consume count '1911341' ",,0,,"cdbfilerepprimary.c",1771,
2020-01-02 11:14:59.545186 CST,,,p30974,th-2128480192,,,,0,,,seg-1,,,,,"LOG","00000","'set segment state', mirroring role 'primary role' mirroring state 'sync' segment state 'up and running' filerep state 'up and running' process name(pid) 'primary sender process(30974)' 'cdbfilerep.c' 'L2440' 'FileRep_SetSegmentState'",,,,,,,0,,"cdbfilerep.c",1822,
```

### Step to reproduce the behavior
` it crashes randomly`

**Comment by asimrp** [comment] 2020-01-02 12:13
The "incomplete startup packet" messages look interesting.  Does this problem happen after you run certain kind of workload?  Or do the segments go down even when no queries are running?  @z17033

**Comment by ashwinstar** [comment] 2020-01-02 20:15
@z17033 reported version being used is "Greenplum Database 5.0.0". Please can you try latest 5X_STABLE and see if the problem continues to happen. Lot of fixes and enhancements were made since 5.0.0 and hence would be helpful to try out latest stable version.

**Comment by z17033** [comment] 2020-01-03 06:47
> @z17033 reported version being used is "Greenplum Database 5.0.0". Please can you try latest 5X_STABLE and see if the problem continues to happen. Lot of fixes and enhancements were made since 5.0.0 and hence would be helpful to try out latest stable version.

**Comment by z17033** [comment] 2020-01-03 06:48
> @z17033 reported version being used is "Greenplum Database 5.0.0". Please can you try latest 5X_STABLE and see if the problem continues to happen. Lot of fixes and enhancements were made since 5.0.0 and hence would be helpful to try out latest stable version.

This is an online environment, and copying the data to local environment is forbidden. Before Using this version, I have test it by tpcds.

**Comment by z17033** [comment] 2020-01-03 06:58
> The "incomplete startup packet" messages look interesting. Does this problem happen after you run certain kind of workload? Or do the segments go down even when no queries are running? @z17033
The segments go down even when no queries are running. And sometimes this error happpens when some queries are running.
```
2020-01-02 16:18:46.415870 CST,"hbsiadmin","hbsidb",p35521,th460892224,"192.168.28.46","58465",2020-01-02 16:18:46 CST,0,con8034439,cmd1,seg-1,,dx22161794,,sx1,"LOG","00000","statement: BEGIN",,,,,,"BEGIN",0,,"postgres.c",1624,
2020-01-02 16:18:46.468013 CST,"hbsiadmin","hbsidb",p35521,th460892224,"192.168.28.46","58465",2020-01-02 16:18:46 CST,0,con8034440,,seg-1,,dx22161794,,sx1,"LOG","00000","The previous session was reset because its gang was disconnected (session id = 8034439). The new session id = 8034440",,,,,,"BEGIN",0,,"cdbgang.c",1594,
2020-01-02 16:18:46.468089 CST,"hbsiadmin","hbsidb",p35521,th460892224,"192.168.28.46","58465",2020-01-02 16:18:46 CST,0,con8034440,,seg-1,,dx22161794,,sx1,"ERROR","58M01","failed to acquire resources on one or more segments","could not connect to server: Connection refused
        Is the server running on host ""192.168.28.23"" and accepting
        TCP/IP connections on port 40001?
 (seg0 192.168.28.23:40001)",,,,,"BEGIN",0,,"cdbgang_async.c",200,
2020-01-02 16:18:46.468199 CST,"hbsiadmin","hbsidb",p35521,th460892224,"192.168.28.46","58465",2020-01-02 16:18:46 CST,0,con8034440,,seg-1,,dx22161794,,sx1,"LOG","00000","An exception was encountered during the execution of statement: BEGIN",,,,,,,0,,,,
```

**Comment by z17033** [comment] 2020-01-08 09:45
> The "incomplete startup packet" messages look interesting. Does this problem happen after you run certain kind of workload? Or do the segments go down even when no queries are running? @z17033

@asimrp
@ashwinstar

In `GPDB500Docs`, It says that:

> A primary segment that is unable to send data to its mirror can change the status of the mirror to down. The primary queues up the data and after gp_segment_connect_timeout seconds passes, indicates a mirror failure, causing the mirror to be marked down and the primary to go into change tracking mode.

So, what is the cause of unable to send data to its mirror ? Have you met before？

**Comment by asimrp** [comment] 2020-01-09 11:00
@z17033 to upgrade to newer 5X release from 5.0.0, you do not need any data movement.  The data can remain in your cluster, the upgrade involves simply switching the old binaries with the new ones.  All you need is to shutdown your cluster, install new binaries and start the cluster.  If that is doable, please try upgrading to 5.24.0.

I took another look at the logs provided in the issue description.  The logs under **"--mirror log"** heading seem to be primary logs.  Please see if logs for the corresponding mirror can be provided for the same time interval as the logs under "-- primary log" heading.

**Comment by z17033** [comment] 2020-01-10 03:03
> @z17033 to upgrade to newer 5X release from 5.0.0, you do not need any data movement. The data can remain in your cluster, the upgrade involves simply switching the old binaries with the new ones. All you need is to shutdown your cluster, install new binaries and start the cluster. If that is doable, please try upgrading to 5.24.0.
> 
> I took another look at the logs provided in the issue description. The logs under **"--mirror log"** heading seem to be primary logs. Please see if logs for the corresponding mirror can be provided for the same time interval as the logs under "-- primary log" heading.

@asimrp 
I'm sorry, I write it wrongly. The correct mirror log is:
```
2020-01-02 11:15:59.455070 CST,,,p13627,th782305344,,,2000-01-01 08:00:00 CST,0,,,seg-1,,,,,"LOG","08006","could not receive data from client: Connection reset by peer",,,,,,,0,,"pqcomm.c",896,
2020-01-02 11:15:59.455153 CST,,,p13627,th782305344,,,2000-01-01 08:00:00 CST,0,,,seg-1,,,,,"WARNING","08006","receive EOF on connection: Connection reset by peer",,,,,,,0,,"cdbfilerepconnserver.c",333,
2020-01-02 11:15:59.455174 CST,,,p13627,th782305344,,,,0,,,seg-1,,,,,"LOG","00000","'set segment state', mirroring role 'mirror role' mirroring state 'sync' segment state 'up and running' filerep state 'up and running' process name(pid) 'mirror receiver process(13627)' 'cdbfilerep.c' 'L2440' 'FileRep_SetSegmentState'",,,,,,,0,,"cdbfilerep.c",1822,
```
I also want to upgrade, But the customer would like an explanation. Is this phenomenon related to `net.core.somaxconn`?

**Comment by asimrp** [comment] 2020-01-15 05:50
@z17033 you closed this issue, does that mean the system was upgraded and the problem went away?

**Comment by z17033** [comment] 2020-03-25 09:30
@asimrp NO.

**Comment by z17033** [comment] 2020-04-01 03:47
@asimrp. Finally, It's a network problem. The switch send rst messages to the cluster.

**Comment by asimrp** [comment] 2020-04-02 05:19
Thank you for sharing the reason.  Even when the problem is solved, I would strongly advise upgrading to the latest 5X version sooner than later.

**Closed by asimrp** 2020-04-02 05:19 UTC

**Comment by kakaliuu** [comment] 2021-06-29 02:19
hello , 

> @asimrp. Finally, It's a network problem. The switch send rst messages to the cluster.

hello ，i  met the same error in greenplum(4.3.30).
i'd like to ask question,
The switch connected by the segment sends a rst message to the segment,so What the  switch refers to?the  three layer switch？
thx~
